### PR TITLE
Move `//third_party/java` to `//flutter/third_party/java`

### PR DESCRIPTION
**Pull request by matanlurey**
... as part of buildmoot.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by yaakovschectman** [comment]
From Android triage: FYI, the last time resources were moved, Java linting failed silently.

**Comment by matanlurey** [comment]
> From Android triage: FYI, the last time resources were moved, Java linting failed silently.

Sorry what does that mean? Don't land this? What linting?

**Comment by yaakovschectman** [comment]
@reidbaker Any thoughts? Does our previous experience with migrating resources amount to anything more than an FYI here, or impact how this PR should move forward in any way?

**Comment by reidbaker** [comment]
It means be on the lookout for weird behavior related to java. Tests passing is not a good indication of stability when it comes to moving the locations of resources.

**Comment by matanlurey** [comment]
> It means be on the lookout for weird behavior related to java. Tests passing is not a good indication of stability when it comes to moving the locations of resources.

I don't think that kind of comment is very helpful, I can't possibly be on the lookout for behavior that isn't triggered on CI.

Maybe what you're saying is "we would like to have more assurance Java linting is working/enforced on CI before landing this change", which is a reasonable request. By Java linting, I assume you mean [`android_lint`](https://github.com/flutter/engine/blob/2f7e9ab274933e1ed221ad793dec85b99331426d/tools/android_lint/bin/main.dart)?

If so I could add a CI check that intentionally makes a change that should be blocked, for example. Wdut?

/cc @gaaclarke if you have any thoughts about the above.

**Comment by gaaclarke** [comment]
I'm unfamiliar with the linting problems of the past but I agree that we shouldn't accommodate any behavior that isn't tested on CI.  I think intentionally introducing a linting exception that the linter catches it as part of the CI checks makes sense if this is something we want to make sure doesn't break in the future.

**Comment by matanlurey** [comment]
I will wait to land this Monday, so there isn't engine breaks of LUCI cache weirdness over the weekend.

**Comment by chinmaygarde** [comment]
The failures do look related. Perhaps you missed a spot where the paths need a fixup?

**Comment by matanlurey** [comment]
> The failures do look related. Perhaps you missed a spot where the paths need a fixup?

Updated!

**Pull request merged**
