### PR TITLE
support embedder_id for pointer events in embedder API

### PR DESCRIPTION
**Pull request by hansihe**
This implements what has been proposed in https://github.com/flutter/flutter/issues/100680

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
@hansihe Is this something you would be able to write a test for? We can't land PRs without tests.

**Comment by hansihe** [comment]
@Hixie For sure, I would definitely be willing to write tests for this. I tried asking in the testing discord channel and in another issue for hints on how such a PR would be testable, but I haven't gotten any reply yet.

Do you have any tips here? I couldn't find any other tests in the repo that tests such things with the embedder API as a reference, but I might have overlooked something.

**Comment by hansihe** [comment]
@Hixie Using https://github.com/flutter/flutter/issues/100680 as the main discussion area.

Any feedback on how a change like this could be tested would be much appreciated.

**Comment by Hixie** [comment]
@hansihe I recommend asking in #hackers-new (I don't see your question in the #hackers-tests channel; you might be on a different server? There's a link in the contributing guidelines to the flutter team server.)

**Comment by Hixie** [comment]
@hansihe Thanks for the contribution, I'm going to close this because it doesn't have tests but please don't hesitate to submit a new PR if you have the opportunity to write some!

**Pull request closed without merging**
