### PR TITLE
Distinguish between touch and mouse input

### PR DESCRIPTION
**Pull request by dnfield**
Addresses the Windows side of https://github.com/flutter/flutter/issues/78232

Fixes https://github.com/flutter/flutter/issues/78206

Adds tests that we check for the extra info.

The test app provided in the bug works when these changes are added.

I have no idea what if anything needs to be done for UWP for this - /cc @clarkezone.

I'm also not entirely clear if the framework should treat pen and touch inputs as the same - but unfortunately, I don't think the win32 API offers a way to distinguish between them either. It probably works out ok, since I assume there'd be about as much slop with a pen as with touch (compared to a mouse).

/cc @jonahwilliams FYI since you worked on the slop stuff in the framework for this.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
> I'm also not entirely clear if the framework should treat pen and touch inputs as the same 

The touch slop is the same for stylus and touch, only mouse has reduced slop.

**Comment by ds84182** [comment]
For distinguishing between pen input vs mouse and touch input: https://docs.microsoft.com/en-us/windows/win32/tablet/system-events-and-mouse-messages#distinguishing-pen-input-from-mouse-and-touch

I think in the future Flutter should probably use Windows Touch to get higher frequency/lower latency pen and touch input, along with multitouch support. Windows Touch is also usable for Win32 apps, as its a Windows 7 API

**Comment by dnfield** [comment]
> For distinguishing between pen input vs mouse and touch input: https://docs.microsoft.com/en-us/windows/win32/tablet/system-events-and-mouse-messages#distinguishing-pen-input-from-mouse-and-touch

This is in fact what I used, but despite its headline if you read it it says that lumps touch/pen together as distinct from mouse.


> I think in the future Flutter should probably use Windows Touch to get higher frequency/lower latency pen and touch input, along with multitouch support. Windows Touch is also usable for Win32 apps, as its a Windows 7 API

I'm not really sure what else is needed fo rmulti-touch support, but I believe this is a step in that direction.

**Comment by ds84182** [comment]
> This is in fact what I used, but despite its headline if you read it it says that lumps touch/pen together as distinct from mouse.

There's a documentation issue on that page, but this is the relevant piece: `Additionally, in Windows Vista, the eighth bit, masked by 0x80, is used to differentiate touch input from pen input (0 = pen, 1 = touch).`

This should say "in Windows Vista **or later**", Chrome relies on this to differentiate between the two. https://source.chromium.org/chromium/chromium/src/+/master:ui/events/win/events_win_utils.cc;l=26

**Comment by dnfield** [comment]
Ahhh ok, cool. I'll add a comment to that effect here - right now the framework doesn't know about any distinction between pen/touch anyway.

**Comment by jonahwilliams** [comment]
we do have stylus device types @dnfield

**Comment by dnfield** [comment]
Ahh I see now. It's just the embedder API doesn't have it. I can add that then.

**Comment by dnfield** [comment]
Ok, updated the patch to add stylus support as well.

**Comment by dnfield** [comment]
Adding fixes for UWP...

**Comment by thedarkknight197** [comment]
> Addresses the Windows side of [flutter/flutter#78232](https://github.com/flutter/flutter/issues/78232)
> 
> Adds tests that we check for the extra info.
> 
> The test app provided in the bug works when these changes are added.
> 
> I have no idea what if anything needs to be done for UWP for this - /cc @clarkezone.
> 
> I'm also not entirely clear if the framework should treat pen and touch inputs as the same - but unfortunately, I don't think the win32 API offers a way to distinguish between them either. It probably works out ok, since I assume there'd be about as much slop with a pen as with touch (compared to a mouse).
> 
> /cc @jonahwilliams FYI since you worked on the slop stuff in the framework for this.

Hi, how could develop an hello world with flutter for Xbox? Whag i need for UWP? Windows pc, and..?

**Comment by dnfield** [comment]
@thedarkknight197 - please see for resources about asking for help developing Flutter apps. This is a pull request for a specific change to the Windows embedding, and not a suitable place for discussion about that.

@clarkezone @cbracken - I've udpated the UWP embedding and it now compiles, but I have no idea how to test it (whether writing tests or actually testing it in a windows app). Running with it as a local engine still seems to use the win32 embedding.

**Comment by clarkezone** [comment]
> @thedarkknight197 - please see for resources about asking for help developing Flutter apps. This is a pull request for a specific change to the Windows embedding, and not a suitable place for discussion about that.
> 
> 
> 
> @clarkezone @cbracken - I've udpated the UWP embedding and it now compiles, but I have no idea how to test it (whether writing tests or actually testing it in a windows app). Running with it as a local engine still seems to use the win32 embedding.

We don't yet have tests lit up but I'll add you to the repo we're developing the UWP template in.. flutter run works with local engine with one manual step that is working pretty well.

**Review by clarkezone — APPROVED** [review]
LGTM assuming UWP bits still work ok.

**Pull request merged**
