### PR TITLE
Add copyright notices to java test files

### PR DESCRIPTION
**Pull request by reidbaker**
Fixes flutter/flutter/issues/155118

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by yaakovschectman — APPROVED** [review]
LGTM. Do you need to add to the ci/licenses files?

**Comment by reidbaker** [comment]
> LGTM. Do you need to add to the ci/licenses files?

Can you link to an example of what you are talking about?

**Comment by yaakovschectman** [comment]
Previously, when I have added files that needed accompanying license headers, lines needed to be added/altered in https://github.com/flutter/engine/blob/main/ci/licenses_golden/licenses_flutter

**Comment by reidbaker** [comment]
> flutter/flutter/issues/155118

Nothing was flagging these files before and checking I found no examples of test/io/flutter/embedding. 
The answer is probably "literally no but something should be checking these files". 

I have a open question out for what should have been checking all these files.

**Comment by zanderso** [comment]
The license checker is probably skipping tests since they are not part of the shipped engine, however when we get around to improving the license checker it should check that all source files outside of third_party have the engine header.

**Review by zanderso — APPROVED** [review]
Thanks!

**Comment by reidbaker** [comment]
> The license checker is probably skipping tests since they are not part of the shipped engine, however when we get around to improving the license checker it should check that all source files outside of third_party have the engine header.

Filed https://github.com/flutter/flutter/issues/155163 to track licence checker work.

**Pull request merged**
