### PR TITLE
Revert "[Impeller Scene] Change how property resolution works to fix Animation blending; add mutation log to nodes; enable backface culling; add vertex color contribution back to meshes"

### PR DESCRIPTION
**Pull request by itsjustkevin**
Reverts flutter/engine#38766 which broke internal tests at b/265394242

### CODE REVIEW

**Comment by zanderso** [comment]
I think a fix already landed in g3 for this here cl/501123168. Has FRoB not picked it up?

**Comment by zanderso** [comment]
Ah, actually never mind. That CL excluded `ui/painting/scene`, but these build failures are in `impeller/scene`.

**Comment by zanderso** [comment]
Depending on timing, reverting this may have wider impacts, so waiting for @bdero to weigh in.

**Comment by zanderso** [comment]
I filed https://github.com/flutter/flutter/issues/118464 for the jazzy install failure in the iOS presubmit checks.

**Comment by chinmaygarde** [comment]
This was resolved via a fix forward.

**Pull request closed without merging**
