### PR TITLE
[Proposal] Improve Canvas Documentation

### PR DESCRIPTION
**Pull request by MasahideMori-SimpleAppli**
The following suggestions. For clarity, the text has been improved over when it was suggested.
https://github.com/flutter/flutter/issues/93190

- Added description about paint parameter of Canvas.drawVertice method.
- Added description of Vertices-class constructor parameters.

I'm not a native English speaker, so I'm sorry if it's strange English.
If there is a mistake in the English grammar I wrote, it is difficult for me to correct it.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by flar** [comment]
There are 2 constructors for Vertices, the second one `Vertices.raw` was left unmodified leading to similar issues as before if developers are targeting the typed list version of the constructor.

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @flar,
I just checked about Vertices.raw documentation. Indeed, the documentation seems to have room for improvement.
However, I've never used that constructor, so I don't know how it works. If I have time, I'll dig into it and make new fixes.
Thank you.

**Comment by flar** [comment]
@MasahideMori-SimpleAppli it's the same data, just packed into a few raw typed data lists that can be shared directly with the native implementation. the constructor you documented simply converts its Dart lists into typed arrays before it calls to the native init method whereas the raw constructor can dive directly into the native init.

It's easier for developers to work with dart List objects of flutter classes then the typed lists of basic numerical values, but the latter is faster for getting the data down to C++ for handing off to Skia.

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @flar,
Thank you for the detailed information on the constructor.
I understand. Thank you for teaching me!

**Pull request merged**
