### PR TITLE
Revert "add signal to pointer kinds"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/engine#8065

TBR @stuartmorgan

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Do you want to remove kSignal at the same time to address the Flutter test issue?

**Comment by jonahwilliams** [comment]
I suppose its a small revert so we might as well

**Comment by jonahwilliams** [comment]
should this value be removed from FlutterView.java as well?

**Comment by stuartmorgan** [comment]
> should this value be removed from FlutterView.java as well?

Yes `kPointerDeviceKindSignal` is cruft too; ugh, I did a terrible job cleaning up the pointer type change when I switched away from that approach :(

**Comment by jonahwilliams** [comment]
Thank you!

**Pull request merged**
