### PR TITLE
more dart:ui dartdocs

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/2384

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Travis is mad about consty things.

**Comment by Hixie** [comment]
Yeah I'd added a const where it didn't belong. Removed it already.

**Pull request merged**
