### PR TITLE
Fix windows build by using lambda capture workaround

### PR DESCRIPTION
**Pull request by aam**
This fixes windows build breakage.

### CODE REVIEW

**Comment by cbracken** [comment]
lgtm

**Comment by aam** [comment]
> Is there a MS bug we can track here in a todo?

Not sure if it's MS bug or what. I created https://github.com/flutter/flutter/issues/13908 to investigate further.

**Comment by bkonyi** [comment]
This is an MS bug, but I can't remember where I saw it... here's a SO question with the same issue and a broken link to MS support: https://stackoverflow.com/questions/39147294/lambda-capture-by-move-fails-for-const-variables

**Comment by aam** [comment]
> This is an MS bug

What is the bug, do you know? Is it handling of `const` references in the std::move?

**Pull request merged**
