### PR TITLE
add backdrop option to DisplayList::saveLayer

### PR DESCRIPTION
**Pull request by flar**
Fixes https://github.com/flutter/flutter/issues/105465

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by bdero** [comment]
Just to clarify: Other than drawing the filtered texture of the parent layer, SaveLayer ops with a backdrop filter should be treated exactly the same as non-backdrop calls, right? In other words, the layer won't be drawn until restored -- and when it's drawn, it'll respect all of the paint state such as the opacity and blend mode.

**Review by bdero — APPROVED** [review]

**Comment by flar** [comment]
> Just to clarify: Other than drawing the filtered texture of the parent layer, SaveLayer ops with a backdrop filter should be treated exactly the same as non-backdrop calls, right? In other words, the layer won't be drawn until restored -- and when it's drawn, it'll respect all of the paint state such as the opacity, blend mode, and filters.

I believe so.

**Comment by flar** [comment]
Actually, it changes the dimensions of the layer. With no specific clipping it will apply the filter to the entire underlying layer and so the saveLayer layer will be larger to accomodate that.

**Comment by bdero** [comment]
Alright perfect, makes sense. Thanks!

**Pull request merged**
