### PR TITLE
FontVariation.lerp, custom FontVariation constructors, and more documentation

### PR DESCRIPTION
**Pull request by Hixie**
This should aid with implementing the framework side of https://github.com/flutter/flutter/issues/105120 This should also address https://github.com/flutter/flutter/issues/28543.

### CODE REVIEW

**Review by eyebrowsoffire — APPROVED** [review]
Awesome! Thanks for adding all this documentation!

**Comment by feinstein** [comment]
@eyebrowsoffire when you approved it, did you see my previous post? I think there's a typo.

**Comment by Hixie** [comment]
@feinstein Can you point out the typo? I'm not sure where you mean.

**Comment by feinstein** [comment]
@Hixie I did on my previous comment, it says `meigh`, I think it should be `weigh`, unless that's a term I am not familiar with.

**Comment by Hixie** [comment]
Follow-up in https://github.com/flutter/engine/pull/44996.

**Pull request merged**
