### PR TITLE
Add dart:ui color to VM embedder entry points.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by Hixie** [comment]
There's a worryingly high number of places these entry points have to be mentioned.

**Comment by chinmaygarde** [comment]
> There's a worryingly high number of places these entry points have to be mentioned.

They have to be mentioned once in https://github.com/chinmaygarde/flutter_engine/blob/c4391be1e6753169021b14537ed720cb8c8f58fa/sky/engine/bindings/dart_vm_entry_points.txt

Which other places are you referring to?

**Comment by Hixie** [comment]
oh, my bad, I misunderstood what direction this was going in. I see. These are the Dart functions that C++ can call into, as opposed to the C++ functions Dart can call into.

**Pull request merged**
