### PR TITLE
Fix broken build by removing non-existent entry point

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by Hixie** [comment]
https://github.com/flutter/engine/blob/master/sky/engine/core/dart/natives.dart has a _setupHooks; why is this non-existent? Isn't it called from https://github.com/flutter/engine/blob/master/sky/engine/bindings/dart_runtime_hooks.cc#L83 ?

**Comment by tvolkert** [comment]
Huh - build was complaining to me that this symbol didn't exist, but a clean build works.  Reverting.

**Comment by eseidelGoogle** [comment]
If we can write down the set of command line instructions to reproduce this build configuration, I'm happy to help wire them up on the bots.  (With or w/o a flutter wrapper like https://github.com/flutter/flutter/issues/1417)

**Comment by chinmaygarde** [comment]
@Hixie The released package resolves to https://gist.github.com/chinmaygarde/4cae201956b7aea60354 which does not yet contain those updates. This is on ToT master. I am going to roll the engine forward locally and check if it is updated.

**Comment by chinmaygarde** [comment]
The last update to natives.dart was three days ago while the last engine roll 4 days ago. Also, the `_getCreateTimerClosure` is now no longer present. I will update the embedder entry points and release the engine.

**Comment by Hixie** [comment]
Cool.

**Pull request closed without merging**
