### PR TITLE
Add an asset copy phase for platform specific assets (i.e. not in the FLX archive)

### PR DESCRIPTION
**Pull request by chinmaygarde**
cc @collinjackson If you create a `Resources` folder in the `ios` directory of your Flutter project, the contents in that directory will be copied over to the application bundle no questions asked.

### CODE REVIEW

**Comment by collinjackson** [comment]
lgtm

**Comment by krisgiesing** [comment]
Should we do the same for Android?

**Comment by chinmaygarde** [comment]
@krisgiesing: This is mostly for third party framework that bundle in their own resources (Google SSO in this case). Not sure how that works on Android.

**Comment by collinjackson** [comment]
We already look for the res folder on Android. Haven't gotten it working for Google SSO yet, but in theory it might be enough.

**Comment by krisgiesing** [comment]
@collinjackson Ah, cool then.

**Pull request merged**
