### PR TITLE
Revert Dart SDK to c766fffb626e

### PR DESCRIPTION
**Pull request by zanderso**
This reverts Dart to 3.0.0-322.0.dev

There are two issues:

A pub roll is failing to roll into the framework https://github.com/flutter/flutter/pull/122730.

There is a compiler bug https://github.com/flutter/flutter/issues/122724

### CODE REVIEW

**Comment by zanderso** [comment]
> You probably want to revert #40178 as well, which just went in and was based on this.

Revert of that change can go in separately here https://github.com/flutter/engine/pull/40317

**Comment by a-siva** [comment]
>>>> A pub roll is failing to roll into the framework https://github.com/flutter/flutter/pull/122730.
Is this the error ?
```
| Analyzing rfw...
|
| warning • This API is available since SDK 2.14.0, but constraints '>=2.13.0 <3.0.0' don't guarantee it • lib/src/dart/model.dart:82:30 • sdk_version_since
| warning • This API is available since SDK 2.14.0, but constraints '>=2.13.0 <3.0.0' don't guarantee it • lib/src/dart/model.dart:127:30 • sdk_version_since
| warning • This API is available since SDK 2.14.0, but constraints '>=2.13.0 <3.0.0' don't guarantee it • lib/src/flutter/runtime.dart:1078:30 • sdk_version_since
| warning • This API is available since SDK 2.14.0, but constraints '>=2.13.0 <3.0.0' don't guarantee it • lib/src/flutter/runtime.dart:1078:51 • sdk_version_since
|
| 4 issues found. (ran in 4.4s)
ERROR: One or more tests from flutter_packages failed.
```

**Comment by zanderso** [comment]
No. It's the "Not a valid package name ..." issue as in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8786538012879301585/+/u/run_entrypoint_dart_registrant/test_stdout

**Comment by a-siva** [comment]
I have created a revert of the pub roll in Dart here https://dart-review.googlesource.com/c/sdk/+/289062

**Pull request merged**
