### PR TITLE
Update (flipping the default from false -> true) and deprecate Paint.enableDithering.

### PR DESCRIPTION
**Pull request by matanlurey**
Update: Blocked on https://github.com/flutter/engine/pull/44912 landing, and merging into google3.

---

Partial work towards https://github.com/flutter/flutter/issues/112498.

_**tl;dr**: In Impeller's backend we intend to _always_ dither gradients, and never allow any changes long-term (i.e., write your own shader if you want different behavior) with the assumption that dithered gradients look better most of the time, and don't typically hurt elsewhere._

Note that, at the time of this writing, I couldn't find a single case of this being set explicitly to `true` inside Google, and there are between [100 and 200 publicly accessible on GitHub](https://github.com/search?q=%22Paint.enableDithering%22+language%3ADart&type=code&l=Dart), of which virtually all are setting it explicitly to `true`.

There are some (valid) concerns this would cause a lot of golden-file image diffs, so I'm going to seek explicit approval from the Google testing team as well as someone from the framework team before landing this commit.

### CODE REVIEW

**Comment by matanlurey** [comment]
It appears this will [break at least 1 framework test](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Framework%20Smoke%20Tests/34932/overview):

```
flutter/test/painting/text_style_test.dart: backgroundColor [E]                                                                                   
  Expected: contains 'background: Paint(Color(0xff00ff00))'
    Actual: 'TextStyle(color: unspecified, decoration: unspecified, decorationColor: unspecified, decorationStyle: unspecified, decorationThickness: unspecified, fontWeight: unspecified, fontStyle: unspecified, textBaseline: unspecified, fontFamily: unspecified, fontFamilyFallback: unspecified, fontSize: unspecified, letterSpacing: unspecified, wordSpacing: unspecified, height: unspecified, leadingDistribution: unspecified, locale: unspecified, background: Paint(Color(0xff00ff00); dither: true), foreground: unspecified, shadows: unspecified, fontFeatures: unspecified, fontVariations: unspecified)'
     Which: does not contain 'background: Paint(Color(0xff00ff00))'
  
  package:matcher                                     expect
  package:flutter_test/src/widget_tester.dart 458:18  expect
  test/painting/text_style_test.dart 462:5            main.<fn>
  ```

... and a [number of engine tests will need to be updated](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8772742877781402001/+/u/test:_test:_Host_Tests_for_host_debug_unopt/stdout). One example:

```
flutter/shell/platform/embedder/tests/embedder_gl_unittests.cc:1469: Failure
Value of: ImageMatchesFixture( FixtureNameForBackend(backend, "gradient.png"), rendered_scene)
  Actual: false
Expected: true
[0;31m[  FAILED  ] [mEmbedderTestGlVk/EmbedderTestMultiBackend.CanRenderGradientWithCompositorOnNonRootLayer/1, where GetParam() = 4-byte object <03-00 00-00> (15612 ms)
[0;32m[----------] [m1 test from EmbedderTestGlVk/EmbedderTestMultiBackend (15613 ms total)

[0;32m[----------] [mGlobal test environment tear-down
[0;32m[==========] [m1 test from 1 test suite ran. (15614 ms total)
[0;32m[  PASSED  ] [m0 tests.
[0;31m[  FAILED  ] [m1 test, listed below:
[0;31m[  FAILED  ] [mEmbedderTestGlVk/EmbedderTestMultiBackend.CanRenderGradientWithCompositorOnNonRootLayer/1, where GetParam() = 4-byte object <03-00 00-00>
```

A couple of options:

1. I could hardcode this off in a test environment(s)
2. I could update the tests to be less brittle, i.e. allow dithering/check less pixels
3. I could update the tests to always assume dithering

Thoughts?

**Comment by chinmaygarde** [comment]
This will definitely blow up Scubas. But if we think this is the right change, we shouldn't let the pain of updating Scubas stop us. @CaseyHillers indicated that he has a workflow for dealing with a lot of Scubas. And it makes sense to exercise that playbook on a non-on-fire change.

**Comment by CaseyHillers** [comment]
Preferably, can we update this outside of the roll process? @LongCatIsLooong recently did this with a build flag, and was able to update all the scubas without blocking the roll.

**Comment by matanlurey** [comment]
@chinmaygarde:

> This will definitely blow up Scubas

After disabling Skia image diffing, I'm actually not sure it will anymore. There are virtually no gradients internally.

@CaseyHillers:

> Preferably, can we update this outside of the roll process?

Yes. I'm going to make sure google3 looks green (or at least, 99% green) before I land this.

**Review by chinmaygarde — APPROVED** [review]

**Comment by matanlurey** [comment]
Blocked by https://github.com/flutter/flutter/issues/133375.

**Pull request merged**
