### PR TITLE
Delete unused method from engine_layer.h

### PR DESCRIPTION
**Pull request by dnfield**
Noticed this while working on something related to this code.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by Hixie** [comment]
test-exempt: purely code deletion

**Comment by dnfield** [comment]
@chinmaygarde  - do you know why clang or clang-tidy didn't complain about this?

**Comment by chinmaygarde** [comment]
Clang won't complain about static methods in headers as they may eventually end up in a TU. Try putting it in a single TU and clang will complain then.

**Comment by dnfield** [comment]
CI failures are https://github.com/flutter/flutter/issues/81837

**Pull request merged**
