### PR TITLE
Add an operator == to ui.Path (needed for testing).

### PR DESCRIPTION
**Pull request by amirh**

### CODE REVIEW

**Comment by Hixie** [comment]
How expensive is this equals?

If it's expensive, we should not add it, especially if the use case is just testing. We have a policy of only exposing features that are performant.

**Comment by Hixie** [comment]
(see https://flutter.io/design-principles/#api-design)

**Comment by amirh** [comment]
If I understand the doc for [SkPath::operator==](https://github.com/google/skia/blob/master/include/core/SkPath.h#L102) correctly, this will be O(N) where N is the size of the path.

"expensive" in our docs is not well defined...

Do we have any way to expose an engine API for testing only?

**Comment by cbracken** [comment]
nit: If we're going to add equals, we should technically also add `hashCode` consistent with equals...

**Comment by amirh** [comment]
Travis just complained on this as well.
I'm actually thinking instead of adding an operator == to just add a static "pathEquals" method, as I'll have to do a lot of plumbing to implement an hashCode method.

But first waiting to figure out if we're ok to add this at all.

**Comment by Hixie** [comment]
If it's just for testing I would find another way to do the testing (e.g. write the test in C++ so you can directly target the underlying API).

**Comment by amirh** [comment]
It is not for testing the engine code.
It's for testing framework code, e.g to verify that a path clipper passed to a RenderPhysicalShape returns the expected Path when using Material with some ShapeBorder.

**Comment by Hixie** [comment]
Oh, for that you can just create a test ShapeBorder subclass that returns a fixed instance of a Path, and then check to see if it's the same instance that you find in the mock_canvas output.

**Comment by amirh** [comment]
e.g in the new implementation of Material, we are creating a specific ShapeBorder based on the input parameters, we might create a CircleBorder, or a RoundedRectangleBorder, or a custom path one.

So if I get your suggestion correctly, you suggest that I inject a CircleBorderFactory into Material, and then in the test replace it with a fake implementation that returns a fixed ShapedBorder that I can later assert against?

That can work, but I think it will be cleaner to just directly assert that a path is equals to an expected path. And I believe that it will come handy in other test use cases as well.
If we think adding an equals method here is too dangerous in the sense that users might do expensive things without noticing, maybe we can find a trick to somehow embed a static pathEquals method only in flutter_tester?

**Comment by Hixie** [comment]
I would write the following tests:
* pass a `shape: new TestShapeBorder` to the Material and verify that the Path gets all the way to the canvas.
* pass the things that should trigger a circle, and then check to see if the shape border passed down from Material to the next widget is a circle. (ditto rectangle, rounded rect, etc)
* test that CircleBorder's output has includes/excludes points that match the unit circle matcher (and similarly for rectangle, rounded rect, etc).

**Comment by amirh** [comment]
We can do it, it will require some public API changes from our current plan (currently the widget that converts the ShapeBorder to a clipper is private so we cannot check it in test).

But still - the ability to assert that a path equals to some expected path sounds like a pretty basic tool we should have for tests.
I'm not sure I understand why we are trying hard to find ways around it?

**Comment by Hixie** [comment]
You can get to private widgets from tests. Just walk from the public one and cast it to `dynamic`.

The concern is having slow APIs. People have a tendency to use all the APIs that are available, assuming that they are all O(1) with a zero constant overhead, and then when they find their app is slow they blame the platform (us). By only exposing APIs that are O(1) with low constant overhead, we mitigate that problem.

A `Path.==` method would not be O(1). Paths can be incredibly complex. Comparing paths is an operation likely to be done in performance-sensitive code. We don't want to encourage it.

**Pull request closed without merging**
