### PR TITLE
Roll Skia and remove PngPixelSerializer

### PR DESCRIPTION
**Pull request by brianosman**
SkPixelSerializer has been removed, and the default behavior for SkPicture serialization is the same as what was being done here before.

### CODE REVIEW

**Comment by brianosman** [comment]
Hmm - I didn't modify the file that's failing the format check. How did that land originally?

**Comment by jason-simmons** [comment]
The format warning was introduced by https://github.com/flutter/engine/pull/4471

Looks like that PR didn't pass the Travis check:
    https://travis-ci.org/flutter/engine/builds/318042055?utm_source=github_status&utm_medium=notification

**Comment by Hixie** [comment]
When this rolled into Flutter in https://github.com/flutter/flutter/pull/13696, there was a more than 2x regression on `flutter_gallery__transition_perf worst_frame_rasterizer_time_millis`. This is not the only commit that was involved, but it's the most suspicious.

**Comment by brianosman** [comment]
Here's the list of Skia commits included in that roll: https://skia.googlesource.com/skia.git/+log/58a3fcd4..ef038483

Eyeballing the list - ~140 commits? Is it easy to reproduce this, to perform some kind of bisect (into the roll)?

**Pull request merged**
