### PR TITLE
Fix-up tree-shaking entry points. Toward making missing entry points …

### PR DESCRIPTION
**Pull request by rmacnak-google**
…an error.

(Compare Dart change https://chromiumcodereview.appspot.com/1663893002/)

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I'm not really sure what this does.  @abarth or @johnmccutchan may have context?

**Comment by chinmaygarde** [comment]
lgtm

**Comment by johnmccutchan** [comment]
lgtm

**Comment by chinmaygarde** [comment]
Is this waiting on anything to be merged in?

**Pull request merged**
