### PR TITLE
Make sure to hit the test font resolver in case of empty font family name.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/7978

### CODE REVIEW

**Comment by chinmaygarde** [comment]
This might lead to more test failures since we are not resolving more fonts to Ahem. Earlier, fonts with an empty font family would not be resolved using our test font resolver and would instead fallback to the per platform SkFontHost.

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
I verified in the debugger that no instances of SkTypeface other than the Ahem font were being created. The change did however lead to the failure of a test. It could be that the test was measuring text. I am not sure. https://www.youtube.com/watch?v=n5PgWb1U5Js&feature=youtu.be

**Comment by tvolkert** [comment]
> This might lead to more test failures since we are not resolving more fonts to Ahem.

Yep, I saw this internally when I hard-coded a test to use Ahem.  We'll probably have to update tests when we pull this engine build into flutter/flutter and into Google.

**Comment by cbracken** [comment]
Heads-up: looks like this broke the paragraph overflow test:
```
00:29 +547 ~3 -13: /Users/cbracken/src/flutter/flutter/packages/flutter/test/rendering/paragraph_test.dart: overflow test
  Expected: <28.0>
    Actual: <14.0>

  package:test                         expect
  rendering/paragraph_test.dart 115:5  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                           _StreamController.add
  websocket_impl.dart 1116             _WebSocketImpl._WebSocketImpl._fromSocket.<fn>
  dart:async                           _EventSinkWrapper.add
  websocket_impl.dart 337              _WebSocketProtocolTransformer._messageFrameEnd
  websocket_impl.dart 232              _WebSocketProtocolTransformer.add
```

**Comment by jason-simmons** [comment]
@hixie has a pending set of fixes to tests that depend on text metrics: https://github.com/flutter/flutter/pull/9332

**Pull request merged**
