### PR TITLE
Fix iOS accessibility bridge leak

### PR DESCRIPTION
**Pull request by xujim**
see issue: https://github.com/flutter/flutter/issues/45599
When accessibility element got focus, it will be kept by __UIAccessibilityFocusedElements. 
Consequently, accessibility bridge will fail to dealloc the kept semantics objects when FlutterEngine need to reset its FlutterViewController( in the function: **FlutterEngine::setViewController**) and reset the platform view's accesssiblity bridge( int the function: **PlatformViewIOS::SetOwnerViewController**).
To fix it, we use focusedAccessibilityElements( a vector) to keep those transiently focused elements, and reset its bridge to the new one. As long as __UIAccessibilityFocusedElements release them, those semantics objects will be dealloced accordingly.

### CODE REVIEW

**Comment by xujim** [comment]
To test it, use my example in https://github.com/flutter/flutter/issues/45599, and turn on the voice over. Click push flutter page, and open second route repeatedly. Without this fix, it will crash due to leaked semantics object has no bridge, which has been reset by SetOwnerViewController

**Comment by liyuqian** [comment]
Thank you @xujim for reporting the issue and finding a fix! It would be nice if you can also transform your test in https://github.com/flutter/flutter/issues/45599 into a test either in the flutter/engine or flutter/flutter repo, so we won't accidentally break it again in the future.

CC @goderbauer @cbracken for accessibility review, @xster for add-to-app, and @chinmaygarde for iOS and engine unit tests.

**Comment by xujim** [comment]
@liyuqian no problem, I have written an small example to reproduce it, but I don't know how to transform it to unit test or flutter test to support the automation test. Because it is a kind of hybrid app, XCTest or Flutter Test seems all not sufficient. Could you show me an example to automate the hybrid app( include flutter and native plugin)?

**Comment by xujim** [comment]
@liyuqian see my code: https://github.com/xujim/testaccessibility.git

**Comment by liyuqian** [comment]
Thank you @xujim  for the effort of making https://github.com/xujim/testaccessibility.git ! Making a nice test is often more tricky and time consuming than the fix itself so we really appreciate your contributions here.

It seems Flutter doesn't currently have any real-device iOS integration tests with accessibility. The closest test I can find is [android_semantics_integration_test][1]. In order to test https://github.com/flutter/flutter/issues/45599 automatically, we probably have to write some test for [devicelab](https://github.com/flutter/flutter/tree/master/dev/devicelab) that automatically turns the VoiceOver on for a real iOS device.

CC one of our test guru @dnfield who is going to give a talk in accessibility in Flutter Interact tomorrow. Dan: do you have any thought on the best way to write a test for this?

[1]: https://github.com/flutter/flutter/blob/master/dev/devicelab/manifest.yaml#L212

**Comment by xster** [comment]
Also cc @gaaclarke on review and/or testing thoughts

**Comment by dnfield** [comment]
How do we end up with multiple focused accessibility elements?

**Comment by xujim** [comment]
@gaaclarke , yes, the ideal fix is let the __UIAccessibilityFocusedElements forget the focused element, However seems there is no such API to do it. I have tried a lot of method, but none of them works. For example: UIAccessibilityPostNotification(Layout/Screenchange). Besides, I don't know how to nil out the semantics object in the bridge if it is string referenced by __UIAccessibilityFocusedElements. If I call release directly, it will go to crash, because __UIAccessibilityFocusedElements then access a wild pointer.

**Comment by darrenaustin** [comment]
This appears to be dealing with a similar issue that PR https://github.com/flutter/engine/pull/13857 was trying to fix. Not sure if it is the same thing, but in that case the problem was that when the a11y bridge shut down it correctly released everything it was referencing. However, for some reason iOS was still holding on to the a11y focused semantic object. 

Like @xujim I was unable to find a way to get it to release these objects with the publicly available APIs. My solution was just guard the bridge reference in the objects so that if they tried to access a dead bridge it would no longer crash. Once VoiceOver comes up again these objects would be released by iOS.

**Comment by xujim** [comment]
@darrenaustin , it is similar, however #13857 cannot fix the problem cleanly. At the beginning, I used the similar way, it can avoid crash, but will let the second flutter page unable to receive accessibility events.

**Comment by chinmaygarde** [comment]
cc @cbracken

**Comment by zanderso** [comment]
@cbracken advises that this PR is stale, though may have some salvageable bits. He will take a look.

**Pull request closed without merging**
