### PR TITLE
Roll vulkan-deps and vs_toolchain

### PR DESCRIPTION
**Pull request by dnfield**
Rolls vulkan-deps to https://chromium.googlesource.com/vulkan-deps/+/40b75117a60b11c42a1fb87bf14c0f49bcdb8b3d

### CODE REVIEW

**Comment by dnfield** [comment]
@loic-sharma the windows failure looks like a flake (see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8782914159211749409/+/u/build_host_debug_arm64_flutter_build_archives:artifacts_flutter_build_archives:embedder_flutter_tools_font-subset_flutter_build_archives:dart_sdk_archive_flutter_shell_platform_windows_client_wrapper:client_wrapper_archive_flutter_build_archives:windows_flutter/stdout for example). Is this being tracked? Or did rolling ANGLE actually break this somehow?

**Comment by loic-sharma** [comment]
Hm I don't think I've seen that error before, and I couldn't find an issue tracking that error. I'm not sure if it's a flake or a new issue from your roll. Let me know if you'd like me to try building your changes on my Windows machine.

**Comment by dnfield** [comment]
Needs https://flutter-review.googlesource.com/c/recipes/+/42462.

I'm trying to figure out why Linux Unopt sometimes gives LSAN/ASAN errors.

**Comment by dnfield** [comment]
@bdero @zanderso fyi this rolls vulkan-deps past the hashes used in impeller-cmake.

**Comment by dnfield** [comment]
Rolling ANGLE to that revision is causing one of the embedder unittests to hang. I'm going to hold off on that for now and just do vulkan-deps/vs_toolchain

**Review by zanderso — APPROVED** [review]

**Pull request merged**
