### PR TITLE
Upgrade builder configuration to Xcode 12.3

### PR DESCRIPTION
**Pull request by jmagman**
The `flutter` tool enforces a minimum of Xcode 12.3 as of https://github.com/flutter/flutter/pull/93094.  Use that version in engine builders to support arm64 mac host builds.

https://github.com/flutter/flutter/issues/84453#issuecomment-961599885

Note: this may cause slow builds until the Xcode caches have been populated.

Successful `led` test runs:
[Mac Web Engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/61b07a8f18553785ac948373c5ffaa9b62eb8d1b61c551eefa55328197b889d2/+/build.proto?server=chromium-swarm.appspot.com)
[Mac Unopt](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/55dccb4dd0d0e41e9c771587d98c7050f82c2eadd284b40e67fa798ef7a78d1e/+/build.proto?server=chromium-swarm.appspot.com)
[Mac iOS Engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/cf00ae61060cd6170ee6e0d38e758f939a387ed9dafed919bf82fc2899d087a0/+/build.proto?server=chromium-swarm.appspot.com)
[Mac Host Engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/7a3280a90cff34faccf526e04796b5085ae444e7495754b49ebee7cbeccf646f/+/build.proto?server=chromium-swarm.appspot.com)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
@CaseyHillers any idea where the `$flutter/osx_sdk | { "sdk_version": "12a7209" }` is still coming from during these try builds?  `xcode | "12c33"` is set, but it's still installing Xcode 12a7209
https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/25597?
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8827736746077309041/+/u/install_xcode/execution_details

**Comment by CaseyHillers** [comment]
Install and select are taking less than 5 seconds. It looks like it's reusing from the cache:

```
                {
                      "name": "old_osx_sdk",
                      "path": "osx_sdk"
                    },
```

We'll need to also roll the cache to make this take effet

**Comment by CaseyHillers** [comment]
Ah I see, the deps version is still not being used.

It could either be https://cs.opensource.google/flutter/infra/+/main:config/lib/ci_yaml/ci_yaml.star;l=149-162

Or https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/model/ci_yaml/target.dart;l=72-83

**Comment by jmagman** [comment]
@CaseyHillers so how should I fix this? Or will it just work itself out post-submit once the configurations roll?

**Comment by CaseyHillers** [comment]
I followed https://cs.opensource.google/flutter/infra/+/main:config/lib/ci_yaml/README.md to see what this would look like in starlark. This gave me the diff https://flutter-review.googlesource.com/c/infra/+/24520 which looks to be expected.

I suspect this is a bug in the Cocoon related code, which only impacts presubmit.

**Comment by CaseyHillers** [comment]
Talked offline. It's fine to land this as is, and monitor it. I filed https://github.com/flutter/flutter/issues/95429 to track. Due to the code freeze, the Cocoon fix will be on hold from being deployed until January.

**Comment by jmagman** [comment]
> Talked offline. It's fine to land this as is, and monitor it. I filed [flutter/flutter#95429](https://github.com/flutter/flutter/issues/95429) to track. Due to the code freeze, the Cocoon fix will be on hold from being deployed until January.

Thanks @CaseyHillers.  I'll merge this tomorrow morning when I have time to watch it roll and merge an empty commit to verify, and also fewer people will be working and waiting for those Xcode caches to populate.

**Comment by jmagman** [comment]
> tomorrow morning 

I meant Monday morning...

**Comment by jmagman** [comment]
Casey gave me an in-person verbal LGTM, and Zach a literal thumbs up over a GVC call.  Taking that as a LGTM on this PR, merging.

**Review by zanderso — COMMENTED** [review]
lgtm

**Comment by jmagman** [comment]
> lgtm

Forgot you were kind of working this week or I would have pinged you.  🙂

**Pull request merged**
