### PR TITLE
Roll dart forward to match the version needed by Fuchsia.

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by zanderso** [comment]
The travis build is stalling. I don't want to mess anything up, so I am going to retry until it goes through.

**Comment by zanderso** [comment]
I've been trying to update the license file, but it pulled in a bunch of stuff for generated files that wasn't there before. It took a long time to work out what was going wrong and how to fix it. Now I've tried to amend this CL, but apparently I've done that wrong. I give up. I'm going to roll Fuchsia without rolling Flutter. This process needs some attention.

**Comment by abarth** [comment]
@Hixie @jason-simmons See above for license frustration ^^^

**Comment by zanderso** [comment]
I filed: https://github.com/flutter/flutter/issues/8492

**Comment by abarth** [comment]
Thanks for filing the issue.

**Pull request closed without merging**
