### PR TITLE
Expose getters of TextStyle and its siblings

### PR DESCRIPTION
**Pull request by fzyzcjy**
As usual, I will add tests if you think this looks roughly OK :)

This is a part of https://github.com/flutter/flutter/issues/129098

### Why

In order to record the current frame, the `TextStyle` and its siblings has to be dumped and restored.

IMHO these getters are intuitive, since users often expect an object has corresponding getter to the data that they provide.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
From Triage: TextStyle probably doesn't hurt to make introspect-able on its own but we don't think having all picture elements be introspect-able for generic playback is a non-goal and we think capture and playback can be done a different layers (perhaps the renderer). For this reason, I don't we are going to accept patches that work towards this goal.

**Comment by dnfield** [comment]
It is not only a non-goal, it is currently an anti-goal.

The engine's various implementations optimize these things at different levels/layers and the way the data arragments get optimized are currently completely invisible to users. We don't want users to have any way to inspect these optimizations at the current time.

You should, instead, take whatever is using these interfaces and wrap them such that the wrapper can do the recording that you want.

**Comment by fzyzcjy** [comment]
@chinmaygarde Thank you!

> From Triage:

Btw just curious, does this mean you discussed this in triage meeting and made a conclusion?

>  we think capture and playback can be done a different layers (perhaps the renderer)

Yes I do implement that in EngineLayer level. https://github.com/fzyzcjy/flutter_screen_recorder/tree/master/vector_impl/screen_recorder

Why not Layer level: Consider LeaderLayer/FollowerLayer, there is no way to serialize those callback functions.
Why not RenderObject, Element, Widget level: Similar reasons.

The problem is that, if I want to implement it in EngineLayer level, I have to extract information from ui.TextStyle etc, because I have no way to control the construction of these objects - except that you allow something like IOOverrides (override constructor).

**Comment by fzyzcjy** [comment]
@dnfield Thank you!

> take whatever is using these interfaces and wrap them such that the wrapper can do the recording that you want.

Then maybe I have to to sth like IOOverrides (override constructor). Otherwise, users can construct ui.TextStyle at anywhere in the code.

**Pull request closed without merging**
