### PR TITLE
lerpDouble return value should be "double"

### PR DESCRIPTION
**Pull request by abarth**
Fixes https://github.com/flutter/flutter/issues/5783

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

**Comment by Hixie** [comment]
We should probably change the arguments too.

**Comment by abarth** [comment]
Why?  As written, the function works for ints too..

**Comment by Hixie** [comment]
Yeah, ok.

**Pull request merged**
