### PR TITLE
Ensure //flutter/fml is dependency free.

### PR DESCRIPTION
**Pull request by chinmaygarde**
This patch removes tracing from FML and moves it into a separate library at
//flutter/fml/trace. This is similar to the pattern followed by
//flutter/fml/dart which contains Dart converters for FML utilities.

The presence of tracing in FML was problematic because the tracing subsystem is
provided by Dart. So, depending on FML would automatically pull in a Dart
dependency. This happened for unit-test targets that did not depend on Dart and
even had no mechanisms to collect traces from the Dart timeline.

Now, applications that want to trace will explicitly need to depend on the trace
library with a clear message indicating the GN rule to be included. This is an
improvement over the current situation where including FML but not including the
Dart dependency would lead to link errors with no indication of which target to
include. This has tripped up the others in the past
https://github.com/flutter/flutter/issues/41414.

With this patch, FML has no other dependencies and users of FML that don't need
Dart can be small and compile quickly.

Fixes https://github.com/flutter/flutter/issues/41414.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @gw280 and @cbracken who were working on using FML as a generic utils library. Now it is actually dependency free instead of depending on the Dart VM.

**Comment by chinmaygarde** [comment]
This improves build times of profile and release modes because some tests were importing libdart_jit solely to satisfy the Dart VM dependency. So the tests in those modes that did not use the VM compiled the JIT VM and the tests that did use the VM compiled the AOT VM. One VM variant was compiled for no reason and if the tests that did not use a VM started to use one in the future, there would be linker errors due to duplicate symbols.

**Comment by chinmaygarde** [comment]
This should also fix the mysterious link errors in Fuchsia https://github.com/flutter/flutter/issues/81135 as deps are now introduced at the level in which they are used instead of at the top level target.

**Review by jason-simmons — APPROVED** [review]

**Comment by chinmaygarde** [comment]
An unrelated flutter_tester Dart test is failing repeatedly. I filed a flake report and now I am not sure its really flaky. Trying to reproduce it locally.

**Comment by chinmaygarde** [comment]
Hmm, Flutter Tester is being tested in release mode where AOT needs to be used but the tester was never configured for AOT.

**Review by cbracken — APPROVED** [review]
lgtm

**Comment by chinmaygarde** [comment]
https://github.com/flutter/engine/pull/25381

**Comment by chinmaygarde** [comment]
This one is blocked because we still have CI steps that depend on a JIT variant of flutter_tester to be necessary in AOT modes.

**Pull request closed without merging**
