### PR TITLE
Update third_party/{icu,boringssl} dependencies

### PR DESCRIPTION
**Pull request by mkustermann**
This updates ICU and BoringSSL dependencies, which was already done in Dart, see:

* https://dart-review.googlesource.com/c/sdk/+/151220
* https://dart-review.googlesource.com/c/sdk/+/151221

Issue https://github.com/flutter/flutter/issues/43968

### CODE REVIEW

**Comment by alexmarkov** [comment]
It looks like there are some changes in ICU licenses which fail Flutter's licenses check.

**Comment by zanderso** [comment]
fyi @gw280

**Comment by mkustermann** [comment]
@zanderso Can we land this even though `luci-engine` is red? Also: What is the `Linux Engine Drone` (it seems stuck in Pending state)?

**Comment by zanderso** [comment]
It looks like the Linux Drone might be dependent on the tree (luci-engine) being green. So, we'll have to wait for the tree to be green before landing. I'm following up with the engine sheriff, so hopefully this will clear up soon.

**Comment by zanderso** [comment]
The Linux Engine Drone builds look green to me on luci https://ci.chromium.org/p/flutter/builders/try/Linux%20Engine%20Drone/36491

Not sure why the PR isn't updating. @godofredoc @digiter any ideas?

**Comment by godofredoc** [comment]
> The Linux Engine Drone builds look green to me on luci https://ci.chromium.org/p/flutter/builders/try/Linux%20Engine%20Drone/36491
> 
> Not sure why the PR isn't updating. @godofredoc @digiter any ideas?

x drone should not be added as checks. Here is the context https://github.com/flutter/flutter/issues/59526

**Comment by zanderso** [comment]
Got it. So this is safe to land whenever luci-engine is green.

**Comment by godofredoc** [comment]
> Got it. So this is safe to land whenever luci-engine is green.

Yes, it is safe to land it.

**Comment by a-siva** [comment]
Have created a new PR https://github.com/flutter/engine/pull/19074 which resolves the conflicts.

**Comment by mkustermann** [comment]
@a-siva Is it all right with you if I land this PR first?

**Comment by mkustermann** [comment]
I saw you copied my changes from this PR into yours, so I'll close this one.

**Pull request closed without merging**
