### PR TITLE
Move images to flutter/assets-for-api-docs

### PR DESCRIPTION
**Pull request by jtmcdole**
27MB of images should not be in the source tree.

Caveat: If you use VSCode's markdown preview, it does not support images outside the workspace. One solution to this would be to submodule the assets back into the assets folder - however that would break github rendering of images.

Fixes flutter/flutter#151691

### CODE REVIEW

**Comment by jtmcdole** [comment]
You can see that this works in github by previewing the actual files: https://github.com/flutter/engine/blob/dcf9bd36cb051df0250a601a74464df40419db69/impeller/README.md

**Comment by chinmaygarde** [comment]
Local tools like Obsidian break if you don't use the RAW URL. I think GitHub may be doing the conversions automagically. But, it works if I change the asset URL to use https://raw.githubusercontent.com/flutter/assets-for-api-docs/5da33067f5cfc7f177d9c460d618397aad9082ca/assets/engine/impeller/android_profiling/image.avif

Before:
Screenshot 2024-07-15 at 3 04 18 PM

After:

Screenshot 2024-07-15 at 3 04 30 PM

**Comment by chinmaygarde** [comment]
Does viewing on GitHub break if you directly reference the images from raw.githubusercontent.com?

**Comment by jtmcdole** [comment]
will try it out

**Comment by jtmcdole** [comment]
This looks fine: https://github.com/flutter/engine/blob/3bf53f017dffb6b549806b7c0d550e3055962ca6/impeller/docs/android_cpu_profile.md

**Review by chinmaygarde — APPROVED** [review]

**Pull request merged**
