### PR TITLE
Add mock capability to PerformanceOverlayLayer

### PR DESCRIPTION
**Pull request by liyuqian**
So we can do golden test on PerformanceOverlay to avoid regression like https://github.com/flutter/flutter/issues/26387

### CODE REVIEW

**Comment by liyuqian** [comment]
Ping...

**Comment by chinmaygarde** [comment]
I am not comfortable having mock data present in the file itself. Can you make the layer accept data to display (instead of collect it on its own) and have the unittest supply said data.

**Comment by liyuqian** [comment]
@chinmaygarde : now the unittest supply the data.

**Comment by liyuqian** [comment]
Ping...

**Comment by liyuqian** [comment]
@chinmaygarde @Hixie golden test the performance overlay will run into font rendering mismatch issues in different Linux versions. My current solution is to use our Docker container which ensures the identical environment as our presubmit checks. Please let me know your comments.

**Comment by Hixie** [comment]
I don't have an opinion on the approach here. FWIW, in other situations we avoid the font issue by using the "Ahem" font, which is carefully designed to be predictable and identical everywhere.

**Comment by liyuqian** [comment]
Ok, I modified PerformanceOverlayLayer so it can take an additional font_path parameter. Now I found that specifying "Roboto-Regular" is sufficient to make sure that pixels match. This is a little better than "Ahem" because we can see more meaningful texts in the golden image. I guess that we don't have to worry too much about the font rendering since this font is just for this specific test only.

**Comment by liyuqian** [comment]
Ping...

**Comment by liyuqian** [comment]
Ping @chinmaygarde ...

**Comment by dnfield** [comment]
This is breaking no post-submit - is there an image missing?  see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8922049806835306640/+/steps/Test_Flow/0/stdout or https://build.chromium.org/p/client.flutter/builders/Linux%20Engine/builds/4762/steps/Test%20Flow/logs/stdio

**Comment by dnfield** [comment]
Ahh it looks like the file is there, but the engine recipe has the tests running from the `src/out/whatever_debug_unopt/` directory (https://cs.chromium.org/chromium/build/scripts/slave/recipes/flutter/engine.py?q=file:recipes/flutter/engine.py&g=0&l=51)

We need to either let the file come in as a parameter or maybe copy it over as part of a build step, or edit the recipe to run this specific test in the correct directory (but I'd rather avoid modifying the recipe for this).

**Comment by dnfield** [comment]
In the mean time I'm going to revert this to un-red the bots.

**Pull request merged**
