### PR TITLE
Revert "Skip LayerTree::Preroll LayerTree::Paint & Swapbuffer when fr…

### PR DESCRIPTION
**Pull request by iskakaushik**
…ame_damage is empty (#32351)"

This reverts commit 5b81baaef734b4347653d4bacc32c8364fc56eb7.

See b/230416004

### CODE REVIEW

**Comment by iskakaushik** [comment]
I plan on investigating this more and see why frame timing metrics are affected by this.

**Comment by iskakaushik** [comment]
cc: @dnfield , @flar

**Review by dnfield — APPROVED** [review]

**Comment by zanderso** [comment]
Was this ever investigated / relanded? Also the original PR author should have been cc'd on the revert. @linxuebin1990

**Comment by linxuebin1990** [comment]
> Was this ever investigated / relanded? Also the original PR author should have been cc'd on the revert. @linxuebin1990

@zanderso @iskakaushik What does "b/230416004" mean ? I am very interested for this.

**Pull request merged**
