### PR TITLE
[Impeller] Made the new blur work on devices without the decal address mode

### PR DESCRIPTION
**Pull request by gaaclarke**
This also adds a new mechanism of override the device capabilities.

fixes https://github.com/flutter/flutter/issues/139773

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

Noting that there is already code in the gaussian blur contents to ensure that the decal sampler mode isn't selected, this patch adds selection of the correct pipeline + testing.

**Review by bdero — APPROVED** [review]

**Comment by gaaclarke** [comment]
fyi, I switched the test to use an image filter since that would demonstrate better decal problems.

**Comment by gaaclarke** [comment]
Screenshot 2023-12-13 at 10 49 42 AM
The golden image isn't quite right.  It doesn't match what I'm seeing in the playgrounds renders.  It looks like it's being scaled about 2x.

**Comment by gaaclarke** [comment]
Okay, the golden does what we expect now.  I think the output looks a wee bit wonky, but this is the old blur filter.  This isn't actually rendering anything new, so landing it to keep track of it for when we turn the new blur on.

**Pull request merged**
