### PR TITLE
Import Abseil at 8f612ebb152fb7e05643a2bcf78cb89a8c0641ad

### PR DESCRIPTION
**Pull request by chinmaygarde**
See OSRB approval in OSRB-49.

This only imports the repository without any build files or other Flutter specific additions. I will add those in the next commit to make it easier to distinguish our additions.

### CODE REVIEW

**Comment by jason-simmons** [comment]
Can this be fetched from the source repository through DEPS?

**Comment by chinmaygarde** [comment]
According to the discussion on OSRB-49, getting a mirror provisioned for this repo was a no-go.

**Comment by jason-simmons** [comment]
@jamesr @Hixie Can Fuchsia set up a mirror of Abseil?

**Comment by chinmaygarde** [comment]
cc @abarth

**Pull request closed without merging**
