### PR TITLE
[Impeller] Implement vulkan push constants.

### PR DESCRIPTION
**Pull request by gaaclarke**
issue: https://github.com/flutter/flutter/issues/131095

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
@jonahwilliams @chinmaygarde I haven't tested this out yet but I think I have all the pieces I need to start trying to test this out tomorrow.

**Comment by gaaclarke** [comment]
As this stands it's not going to work since on iOS the metal reflect headers are used.  As a temporary hack this will start using the vulkan headers.

```diff
diff --git a/impeller/tools/impeller.gni b/impeller/tools/impeller.gni
index 2c20acf26d..7d544d6532 100644
--- a/impeller/tools/impeller.gni
+++ b/impeller/tools/impeller.gni
@@ -427,6 +427,7 @@ template("_impeller_shaders_metal") {
     sl_file_extension = "metal"
     use_half_textures = use_half_textures
     shader_target_flag = ""
+    intermediates_subdir = "metal"
     defines = [ "IMPELLER_TARGET_METAL" ]
     if (is_ios) {
       shader_target_flag = "--metal-ios"
@@ -466,7 +467,7 @@ template("_impeller_shaders_metal") {
   group(target_name) {
     public_deps = [
       ":$embed_mtl_lib",
-      ":$reflect_mtl",
+      #":$reflect_mtl",
     ]
   }
 }
@@ -591,7 +592,7 @@ template("_impeller_shaders_vk") {
         metal_version = invoker.metal_version
       }
 
-      intermediates_subdir = "vk"
+      #intermediates_subdir = "vk"
     }
     shader_target_flag = "--vulkan"
 
@@ -640,9 +641,9 @@ template("_impeller_shaders_vk") {
       public_deps += [ ":$analyze_lib" ]
     }
 
-    if (!impeller_enable_metal) {
+    #if (!impeller_enable_metal) {
       public_deps += [ ":$reflect_vk" ]
-    }
+    #}
   }
 }
```

**Comment by gaaclarke** [comment]
I ran some testing on push constants.  There is a bug in the implementation still where half of the time it draws a garbage color.  I think the performance results should be indicative of the final implementation though since it's probably just a matter of making sure someone doesn't reuse that buffer or it isn't deleted before push constants is run.

```
Device: pixel 4a
Test: drive --profile test_driver/transitions_perf.dart
Gallery hash: 

— PUSH CONSTANTS
Engine hash: 2c03735608b6efd2ba18bc5728eaaa2a58040f44

Run 1:
  "average_frame_build_time_millis": 1.3360747663551407,
  "90th_percentile_frame_build_time_millis": 2.127,
  "99th_percentile_frame_build_time_millis": 14.204,
  "worst_frame_build_time_millis": 28.45,
  "missed_frame_build_budget_count": 2,
  "average_frame_rasterizer_time_millis": 7.998996894409933,
  "stddev_frame_rasterizer_time_millis": 2.803715134446972,
  "90th_percentile_frame_rasterizer_time_millis": 10.673,
  "99th_percentile_frame_rasterizer_time_millis": 29.66,
  "worst_frame_rasterizer_time_millis": 55.786,
  "missed_frame_rasterizer_budget_count": 22,
  "frame_count": 321,
  "frame_rasterizer_count": 322,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Run 2:
  "average_frame_build_time_millis": 1.4149221183800622,
  "90th_percentile_frame_build_time_millis": 3.29,
  "99th_percentile_frame_build_time_millis": 14.269,
  "worst_frame_build_time_millis": 41.094,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 7.440485981308408,
  "stddev_frame_rasterizer_time_millis": 2.378525751885169,
  "90th_percentile_frame_rasterizer_time_millis": 8.973,
  "99th_percentile_frame_rasterizer_time_millis": 30.985,
  "worst_frame_rasterizer_time_millis": 44.888,
  "missed_frame_rasterizer_budget_count": 14,
  "frame_count": 321,
  "frame_rasterizer_count": 321,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Run 3:
  "average_frame_build_time_millis": 1.5372274143302176,
  "90th_percentile_frame_build_time_millis": 1.841,
  "99th_percentile_frame_build_time_millis": 15.427,
  "worst_frame_build_time_millis": 41.114,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 8.250130841121496,
  "stddev_frame_rasterizer_time_millis": 2.5818014964916904,
  "90th_percentile_frame_rasterizer_time_millis": 9.771,
  "99th_percentile_frame_rasterizer_time_millis": 32.996,
  "worst_frame_rasterizer_time_millis": 45.078,
  "missed_frame_rasterizer_budget_count": 18,
  "frame_count": 321,
  "frame_rasterizer_count": 321,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Median:
  "average_frame_rasterizer_time_millis": 7.998996894409933,
  "99th_percentile_frame_rasterizer_time_millis": 30.985,
  "worst_frame_rasterizer_time_millis": 45.078,

— VARYING
Engine hash: 2d8cff44261bc8e04f204ca27da7d4554964b4bb

Run 1:
  "average_frame_build_time_millis": 1.504015625,
  "90th_percentile_frame_build_time_millis": 2.956,
  "99th_percentile_frame_build_time_millis": 13.876,
  "worst_frame_build_time_millis": 39.599,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 9.788130841121495,
  "stddev_frame_rasterizer_time_millis": 3.762917401810929,
  "90th_percentile_frame_rasterizer_time_millis": 13.729,
  "99th_percentile_frame_rasterizer_time_millis": 25.865,
  "worst_frame_rasterizer_time_millis": 33.126,
  "missed_frame_rasterizer_budget_count": 15,
  "frame_count": 320,
  "frame_rasterizer_count": 321,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Run 2:
  "average_frame_build_time_millis": 1.5388473520249222,
  "90th_percentile_frame_build_time_millis": 1.762,
  "99th_percentile_frame_build_time_millis": 15.306,
  "worst_frame_build_time_millis": 38.919,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 8.101571875,
  "stddev_frame_rasterizer_time_millis": 2.3663774609374997,
  "90th_percentile_frame_rasterizer_time_millis": 9.847,
  "99th_percentile_frame_rasterizer_time_millis": 32.979,
  "worst_frame_rasterizer_time_millis": 44.926,
  "missed_frame_rasterizer_budget_count": 13,
  "frame_count": 321,
  "frame_rasterizer_count": 320,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Run 3:
  "average_frame_build_time_millis": 1.58299375,
  "90th_percentile_frame_build_time_millis": 2.313,
  "99th_percentile_frame_build_time_millis": 15.545,
  "worst_frame_build_time_millis": 40.303,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 7.975815625000008,
  "stddev_frame_rasterizer_time_millis": 2.5537102734375057,
  "90th_percentile_frame_rasterizer_time_millis": 10.61,
  "99th_percentile_frame_rasterizer_time_millis": 33.362,
  "worst_frame_rasterizer_time_millis": 44.068,
  "missed_frame_rasterizer_budget_count": 14,
  "frame_count": 320,
  "frame_rasterizer_count": 320,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

Median:
  "average_frame_rasterizer_time_millis": 7.975815625000008,
  "99th_percentile_frame_rasterizer_time_millis": 32.979,
  "worst_frame_rasterizer_time_millis": 44.068,

— UNIFORM
Engine hash:18e58680fdbce333959158d722134c799fca5e55

Run 1:
  "average_frame_build_time_millis": 1.5365172413793107,
  "90th_percentile_frame_build_time_millis": 2.945,
  "99th_percentile_frame_build_time_millis": 13.473,
  "worst_frame_build_time_millis": 40.9,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 8.449236760124606,
  "stddev_frame_rasterizer_time_millis": 2.509424695024308,
  "90th_percentile_frame_rasterizer_time_millis": 10.873,
  "99th_percentile_frame_rasterizer_time_millis": 28.389,
  "worst_frame_rasterizer_time_millis": 45.074,
  "missed_frame_rasterizer_budget_count": 18,
  "frame_count": 319,
  "frame_rasterizer_count": 321,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [
```

**Comment by jonahwilliams** [comment]
I don't think you'll be able to use raster stats to measure push constant improvements. You'll want to use a GPU profiler to get performance counters for a particular vendor.

**Comment by gaaclarke** [comment]
Here's the AGI results for drawing the materials->card view which has a full screen solid color (this engine doesn't have clip fix).  I'll look into the glitch tomorrow to see if resolving it has an effect on the performance and also check the numbers in renderdoc.

## push constants
(notice the extra command for push constants)
Screenshot 2023-07-25 at 3 39 47 PM

## uniforms
Screenshot 2023-07-25 at 3 45 39 PM

**Comment by gaaclarke** [comment]
RenderDoc is showing that this doesn't make a difference on the pixel 4a.  It's also worth noting that the solid fills no longer are measured as being much more expensive (I wasn't measuring against the `varying data` approach, just straight uniforms).

There is still a bug in the implementation where it sometimes doesn't render correctly but based on the frame captures I believe the measurement won't differ much if that bug is resolved since it is rendering correctly sometimes and I can see that it is indeed using the push constants.

## push constants

Screenshot (1)

## uniforms

Screenshot (2)

**Comment by gaaclarke** [comment]
I'm going to abandon this PR.

I asked jonah to profile with his setup too and he didn't notice any difference in the Streamline profiles.  I'm abandoning it since the changes required to get this landed would introduce complexity to impeller and it doesn't have a measurable impact on rendering performance.

Particularly, I had to hack the shader compilation to create special reflection headers that gave the information necessary to do push constants.  We'd either have to make each backend have its own reflection headers (everyone just uses metal headers today) or to do a runtime check to see if we can do push constants.

**Comment by chinmaygarde** [comment]
I moved this to the icebox should we want to revive the patch in the future.

Before you page this out though, can you add a note to the linked bug on what differences you noticed, if any, to any of the either the Streamline counters (possibly related to CVTs without the varying workaround) or `malioc` stats? Just valuable context to have even if we aren't going to attempt to land this.

**Pull request closed without merging**
