### PR TITLE
expose setMatrix for Canvas

### PR DESCRIPTION
**Pull request by dnfield**
Currently the canvas API only provides a method for multiplying the current matrix.  I have a use case in the framework where I want to do something like this:

```dart
context.canvas.save();
context.canvas.setMatrix(Matrix4.identity().storage);
context.canvas.drawPath( // my pre-transformed path
context.canvas.restore(); // get back to whatever transforms were applied to the canvas before this
```

Unfortunately, it looks like our only tests for canvas is that the methods don't blow up.  I think to really test this we'd need some kind of golden, as the canvas doesn't expose any information about its current matrix.

### CODE REVIEW

**Comment by dnfield** [comment]
This is needed for https://github.com/flutter/flutter/pull/27137 - specifically, to draw the final path around the error widgets (or the erroneous area) without worrying about whatever transforms have been applied directly to the canvas.

**Comment by dnfield** [comment]
This will require a manual roll into the framework to update the `_MulticastCanvas` implementation in widget_inspector.dart

**Comment by Hixie** [comment]
Generally I would recommend against this, because it breaks composition.

Here are some examples of issues it would cause:

 - You have a widget that paints something, and happens to use this to break out of its own transform. It all works fine. Then you put it inside a FittedBox to make the widget bigger/smaller/whatever, and... it breaks.

 - You have a widget that wants to use this to break out of any transforms that are applied. It all works fine, until one day you add a Video to your app, and suddenly it's not breaking out of as many transforms because some of them are being done to the canvas and some are being done to layers.

 - You use this to break out of a transform, and then you rotate the device. The image doesn't rotate, because we're using a transform to rotate the screen on that device. But on some other device it doesn't, because the OS does the rotation.

 - You use this to break out of a transform to draw an image, and on devices with a device pixel ration of 1.0 the image is correctly scaled, and on others it's incorrectly scaled because we use a transform to apply the device pixel ratio.

 - A widget uses this to break out of a transform, and on an embedded device the widget draws upside down because on that device the developed is using a transform to flip the screen the right way because the display itself is mounted upside down.

**Comment by dnfield** [comment]
Closing in favor of solution proposed on related PR in framework.

**Pull request closed without merging**
