### PR TITLE
Fix Observatory

### PR DESCRIPTION
**Pull request by johnmccutchan**
Fixes https://github.com/flutter/flutter/issues/1694

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@Hixie

**Comment by Hixie** [comment]
RSLGTM, but cc @abarth for more real review.

**Comment by johnmccutchan** [comment]
Some context- I'm moving all embedders to use shared Dart source for the service isolate that is maintained in the Dart runtime tree. This CL deletes Flutter's copy and uses the shared source.

**Comment by abarth** [comment]
\o/  LGTM

**Pull request merged**
