### PR TITLE
Throw on unhandled license type

### PR DESCRIPTION
**Pull request by cbracken**
If a LicenseType is ever left unhandled in the switch statement, we now
throw an exception. This also fixes a 'missing return statements' lint.

### CODE REVIEW

**Comment by Hixie** [comment]
this shouldn't be necessary, the linter will complain if there's ever an enum value added that isn't handled by the switch.

**Comment by cbracken** [comment]
See the description: This is specifically to address the missing return lint.

**Comment by Hixie** [comment]
The usual pattern we use is to assert non-null before the switch, and return null after. The assert and the return with go away with NNBD.

**Comment by cbracken** [comment]
> The usual pattern we use is to assert non-null before the switch, and return null after.

Happy to change it, though that seems less safe than throwing.

> The assert and the return with go away with NNBD.

I'm looking forward to this as much as anyone :)

**Comment by Hixie** [comment]
why is it less safe?

**Comment by cbracken** [comment]
For the reason in my comment — if the enum lint were ever removed we’d want to throw with an obvious error message.

**Comment by Hixie** [comment]
If that lint were ever removed we'd have bigger problems.
I think the way to address that is to have a test that verifies the lint is still working.

**Comment by cbracken** [comment]
sgtm - I'm happy to add something like the existing fail test both here and in the framework.

Would you prefer I change this to return null rather than throw or fine to land as-is?

**Comment by Hixie** [comment]
Returning null would be more consistent with the rest of the codebase, but I don't feel strongly. It'll be moot soon anyway since NNBD will turn the `throw` or `return null` into dead code and we'll have to remove it.

**Comment by cbracken** [comment]
Done.

**Comment by pq** [comment]
Sorry for the slow follow-up on this one.  My sense is that we should be able to detect that the return is unnecessary (and actually dead code).  @bwilkerson: does that seem right?

**Pull request merged**
