### PR TITLE
adding support for ios custom action overrides when switch control is enabled

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

The framework counter part https://github.com/flutter/flutter/pull/82746

The custom action overrides will now be support in ios in favor of adding fake switch control. There is currently no available api to turn on native switch control(scrolling for example) for UIView. We have to workaround it by adding custom actions to imitate those native switch control. This pr makes accessibility bridge in ios to accept custom action overrides for existing semantics action. If it receive such overrides, it will add the imitating custom action into all of its children but itself.

## Related Issues

https://github.com/flutter/flutter/issues/37974

## Tests

I added the following tests:

see files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [ ] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @goderbauer Do you have additional context on how to review and land this? The linked framework PR seems to be open still. If, OTOH, this PR is stale, can we close it for now?

**Comment by chunhtai** [comment]
close until i have time to get back to this pr

**Comment by chunhtai** [comment]
waiting for review

**Comment by chunhtai** [comment]
superseded by https://github.com/flutter/engine/pull/26671

**Pull request closed without merging**
