### PR TITLE
Rev the Dart SDK to pick up better dartdocs.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
The problem on travis is this new warning:

"dynamic doesn't extend Foo" (where Foo is a class)

Specifically, we're trying to see if some class "is" a Bar&lt;dynamic, Baz>, where Bar is defined as Bar&lt;T extends Foo, U> and it doesn't like the "dynamic" there.

Need to file a bug on the analyzer about this once I can confirm a small repro.

**Comment by Hixie** [comment]
Filed https://github.com/dart-lang/sdk/issues/24713

**Comment by Hixie** [comment]
Also blocked on https://github.com/dart-lang/sdk/issues/24717

**Comment by Hixie** [comment]
I'm not sure about some of the pubspec.yaml changes. Was there a reason that many of the `pubspec.yaml`s for our demos depended on `flutter: ">=0.0.3 <0.1.0"` instead of "`any`"? they have a dependency override, which makes it moot, no? I've made them `any` in this patch, but if I'm wrong, I'm happy to revert it.

**Comment by Hixie** [comment]
Other than that, this is ready for review and can be checked in once I publish the new sky_tools package.

**Comment by abarth** [comment]
LGTM w/ the "any" changes removed

**Pull request merged**
