### PR TITLE
Move //dart to //third_party/dart.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
This matches what we are doing for Fuchsia, and allows the Dart team to have to worry about 2 locations (// and //third_party/dart) instead of three (same plus //dart).

**Comment by chinmaygarde** [comment]
Makes sense.

**Comment by pylaligand** [comment]
A buildroot update is needed too: https://github.com/flutter/buildroot/pull/108

**Comment by aam** [comment]
This seems to have broken dart master with engine master build

**Comment by aam** [comment]
```
[1944/1989] ACTION //flutter/lib/snapshot:flutter_patched_sdk(//build/toolchain/linux:clang_x64)
FAILED: flutter_patched_sdk/lib/libraries.json 
python ../../third_party/dart/tools/patch_sdk.py --quiet flutter /b/build/slave/flutter/build/src/third_party/dart/sdk /b/build/slave/flutter/build/src/out/host_debug_unopt/gen/flutter/lib/snapshot/patches flutter_patched_sdk /b/build/slave/flutter/build/src/third_party/dart/.packages
Unhandled exception:
FileSystemException: Directory listing failed, path = '/b/build/slave/flutter/build/src/third_party/flutter/lib/ui/' (OS Error: No such file or directory, errno = 2)
```

**Comment by tvolkert** [comment]
@pylaligand is the build failure is due to the fact that it hasn't picked up the buildroot change in the engine repo?  If so, can you update `DEPS` to pick up the buildroot change?  If not, we should revert.

**Comment by zanderso** [comment]
_copyExtraLibraries in Dart's //tools/patch_sdk.dart looks like it might need to be updated to reflect the new layout.

**Comment by aam** [comment]
Hopefully https://dart-review.googlesource.com/c/sdk/+/15220 fixes the issue

**Pull request merged**
