### PR TITLE
[Impeller] fixes alpha blend for plus blend mode

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/142549

**WIP** Non-draft to get golden results.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jason-simmons — CHANGES_REQUESTED** [review]
This does not match the specification of `BlendMode.plus` or Skia's implementation

See https://github.com/flutter/flutter/issues/142549#issuecomment-2000421589

**Comment by gaaclarke** [comment]
This `dst_alpha_blend_factor-kOneMinusSourceAlpha` gives the correct results for 4 points, all permutations of alpha being zero or one.  The max error is 0.25.

A graph of the difference:
Screenshot 2024-03-15 at 5 50 47 PM

**Comment by gaaclarke** [comment]
Using `1-src` is 8 times more accurate than the status quo when measuring the MSE:
```c
#include <math.h>
#include <stdio.h>

double blend_add(double x, double y) {
  return x + y;
}

double blend_src(double x, double y) {
  return x + (1.0 - x) * y;
}

double blend_clamped(double x, double y) {
  return fmin(x + y, 1.0);
}

double square_error(double expected, double actual) {
  double diff = expected - actual;
  return diff * diff;
}

int main() {
  const double kStepSize = 0.01;
  double add_tally = 0.0;
  double src_tally = 0.0;
  double count = 0.0;
  for (double y = 0; y <= 1.0; y += kStepSize) {
    for (double x = 0; x <= 1.0; x += kStepSize) {
      double expected = blend_clamped(x, y);
      double add = blend_add(x, y);
      double src = blend_src(x, y);

      add_tally += square_error(expected, add);
      src_tally += square_error(expected, src);
      count += 1.0;
    }
  }

  printf("add square MSE: %f\n", add_tally / count);
  printf("1 - src square MSE: %f\n", src_tally / count);

  return 0;
}
```
output:
```
add square MSE: 0.080042
1 - src square MSE: 0.011114
```

Something to consider as we look into moving this over to an advanced blend.

**Comment by gaaclarke** [comment]
This fixes the linked issue, is more mathematically correct and eliminates disaster scenarios where alpha > 1 all while being low risk.  We've decided that the issue that it addresses does not raise to the level of needing a cherry-pick so we are going to drop it for just landing the advanced blend.

**Pull request closed without merging**
