### PR TITLE
Ensure that gradient tile mode enum values in Dart match SkShader::TileMode.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Regression introduced in https://github.com/flutter/engine/pull/3668.

### CODE REVIEW

**Comment by Hixie** [comment]
Ooops.

Please add a comment saying that the order is critical. :-)

LGTM!

**Comment by chinmaygarde** [comment]
Done. There are other enum values in that file. Will add similar comments.

**Comment by Hixie** [comment]
Thanks! You rock.

**Comment by chinmaygarde** [comment]
Done.

**Pull request merged**
