### PR TITLE
Try to fix the RasterCache benchmark gone down problems

### PR DESCRIPTION
**Pull request by JsouLiang**
Reworking the logic and fixing the DisplayList and Layer RasterCacheItem problems.

### CODE REVIEW

**Comment by JsouLiang** [comment]
I use the Flutter to this version:
```
flutter --version
Flutter 3.1.0-0.0.pre.1443 • channel unknown • unknown source
Framework • revision 9f467c2975 (4 days ago) • 2022-06-30 02:14:09 -0400
Engine • revision 557655b7f5
Tools • Dart 2.18.0 (build 2.18.0-238.0.dev) • DevTools 2.14.1
```
That engine is the RasterCache refactoring change version. I also change my local engine to this version:`557655b7f5`;

I added this change, and run the benchmark 
`../../bin/cache/dart-sdk/bin/dart bin/run.dart --local-engine-src-path=/Volumes/Extreme/flutterEngine/engine/src --local-engine=android_profile -t textfield_perf__timeline_summary --ab=4`

To get the benchmark result is this:
```

═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	1.78 (1.83%)	1.69 (4.59%)	1.05x	
worst_frame_build_time_millis	6.24 (49.92%)	6.66 (42.11%)	0.94x	
90th_percentile_frame_build_time_millis	2.98 (11.18%)	3.02 (5.15%)	0.99x	
99th_percentile_frame_build_time_millis	6.24 (49.92%)	6.13 (46.03%)	1.02x	
average_frame_rasterizer_time_millis	7.40 (4.45%)	7.03 (5.22%)	1.05x	
worst_frame_rasterizer_time_millis	56.04 (8.81%)	57.63 (3.07%)	0.97x	
90th_percentile_frame_rasterizer_time_millis	13.71 (3.47%)	11.18 (13.44%)	1.23x	
99th_percentile_frame_rasterizer_time_millis	56.04 (8.81%)	51.81 (18.51%)	1.08x	
average_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_picture_cache_count	0.63 (4.39%)	0.61 (8.84%)	1.04x	
90th_percentile_picture_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_picture_cache_count	16.50 (3.03%)	15.75 (8.25%)	1.05x	
worst_picture_cache_count	16.50 (3.03%)	16.00 (7.65%)	1.03x	
average_picture_cache_memory	0.57 (4.39%)	0.55 (8.84%)	1.04x	
90th_percentile_picture_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_picture_cache_memory	14.92 (3.03%)	14.24 (8.25%)	1.05x	
worst_picture_cache_memory	14.92 (3.03%)	14.47 (7.65%)	1.03x	
new_gen_gc_count	2.00 (0.00%)	4.00 (0.00%)	0.50x	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_vsync_transitions_missed	1.83 (2.26%)	1.87 (8.65%)	0.98x	
90th_percentile_vsync_transitions_missed	3.00 (0.00%)	3.50 (24.74%)	0.86x	
99th_percentile_vsync_transitions_missed	5.50 (9.09%)	5.75 (7.53%)	0.96x	
30hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
60hz_frame_percentage	8.89 (0.76%)	8.85 (0.88%)	1.00x	
80hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90hz_frame_percentage	91.11 (0.07%)	91.15 (0.09%)	1.00x	
120hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
illegal_refresh_rate_frame_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
```

**Comment by flar** [comment]
It looks like some of the changes are to prevent the list of cache items from getting cluttered with entries that don't need to update. That's useful, but it doesn't seem like it would account for the size of the regressions to just process the entries. If it does, then we can make the processing more efficient in a number of ways, but it can't hurt to also restrict the list of entries to only those who are needing to be cached.

Another aspect is reworking the way that we determine if there are too many DLs being cached in a given frame. If we were getting that wrong then I can easily see how that would account for the amount of time taken in the 90/99th percentile cases. But, if we are getting that wrong I don't see how the old code had an error in it and the new code requires a bit of phantom bookkeeping to answer the same questions (i.e. "I think I will generate a cache entry, so I will increment the count so that others don't even get to try").

**Comment by JsouLiang** [comment]
About this code（#31892）, it means that DL will create Entry as soon as possible, in previous version Touch method will increase access_count when Entry exists, but because we speed up DL Entry creation, it may lead to successful Touch for some nodes (node exists Entry), which will make some DL reach access_thresold faster and then generate Image
@flar

**Comment by JsouLiang** [comment]
Do you have any specific suggestions for this pitch? From the benchmark data, this pitch does make the final result of the #31892 better

**Comment by flar** [comment]
> About this code（#31892）, it means that DL will create Entry as soon as possible, in previous version Touch method will increase access_count when Entry exists, but because we speed up DL Entry creation, it may lead to successful Touch for some nodes (node exists Entry), which will make some DL reach access_thresold faster and then generate Image @flar

The DL always created Entry objects as soon as possible. On the first frame, Generate would never return false and so all DL layers would call Prepare which would generate an Entry and start its access_count. How did 31892 have any impact on that?

**Comment by flar** [comment]
OK, so it looks like we are caching a lot of items that are never used. Here are 2 graphs that show the difference in the RasterCacheFlows. The green parts are pretty much the same, but the "after-refactor" graph has a lot of red bars (indicating a cache entry that exists but is used/cache-hit in the bottom 99% of all entries).

<details>
  <summary>DisplayList cache flows before refactor</summary>

before-refactor-DLcache-flow
</details>

<details>
  <summary>DisplayList cache flows after refactor</summary>

after-refactor-DLcache-flow
</details>

Something is definitely causing extra DisplayList objects to be cached.

**Comment by flar** [comment]
I see the problem now.

We used to not add an entry for a DL until it was in frame (intersecting the cull rect), but now we always add it in PrerollSetup. Touch only increments the access_count if the entry exists so, previously, an item would have to be "in frame" before it started its count but now it will start its count immediately.

I think the problem is that we are overloading the concept of whether or not an entry exists. Touch needs to be reworked to ask "if I have ever been visible" with more deterministic indications and then populate should only create an entry if it is visible.

"used_this_frame" and "whether or not an entry exists" should not be overloaded in so many ways. I think we need:

```
  // the DL/Matrix pair is still participating in the layer tree
  // whether or not it is visible
  entry.encountered_this_frame

  // the DL/Matrix pair intersects the cull rect
  entry.visible_this_frame

  // (redundant with access_count > 0)
  // has it ever been visible in any frame
  entry.has_been_visible
```

We always set "encountered" so that a cache entry is kept around, cache evictions will use this flag primarily. But we only set "visible" when we see it inside the cull rect. MarkSeen then would take a flag for whether it is in the cull rect and always set "encountered" and conditionally set "visible". access_count will then only increment if non-zero or if it is visible this frame.

Touch isn't really needed any more.

Prepare/Populate will not generate a cache entry if the item is not "visible_this_frame" so that once we hit 3 counts we delay the actual populate until it is inside the cull rect. We could also later work out a mechanism whereby these non-visible entries might be populated lazily on frames that are well within budget. These methods will also honor the "limit per frame".

What you've done sort of accomplishes this, but it does so in a round-about way that uses side effects of whether an entry is present and the single flag we've created which has a name that isn't really descriptive.

**Comment by flar** [comment]
I filed a different PR with the proposed concept of explicitly tracking visibility before starting the access_count threshold countdown. See https://github.com/flutter/engine/pull/34562

**Comment by zanderso** [comment]
Closing as I believe this is now obsolete.

**Pull request closed without merging**
