### PR TITLE
Fix issues with nested gradients in html renderer.

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
https://github.com/flutter/flutter/issues/99045

The DOM canvas does need to be able to handle gradient shaders, since if we are
inside of a context that is affected by an SVG filter we can't fall back to the
using canvas. This is because webkit doesn't apply the SVG filters to canvas
elements for some reason. In these situations, just do a full GL render of the
gradient and apply it as the background image on the DOM element.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/31887

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/31887

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 4.
View them at https://flutter-engine-gold.skia.org/cl/github/31887

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 5.
View them at https://flutter-engine-gold.skia.org/cl/github/31887

**Comment by skia-gold** [comment]
Gold has detected about 18 new digest(s) on patchset 6.
View them at https://flutter-engine-gold.skia.org/cl/github/31887

**Pull request merged**
