### PR TITLE
Avoid importing the internal lib into the builtin since its disallowed after Dart_Precompile.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Import the library directly in dart_ui.dart.

Fixes https://github.com/flutter/flutter/issues/2586

cc @johnmccutchan, @rmacnak-google, @abarth

### CODE REVIEW

**Comment by rmacnak-google** [comment]
John, why was the import done through the API and only for the main isolate?

**Comment by chinmaygarde** [comment]
The analyzer is failing because of the _internal import.

**Comment by Hixie** [comment]
you can just add more ignore magic to https://github.com/flutter/engine/blob/master/travis/analyze.sh to silence the analyzer

**Comment by chinmaygarde** [comment]
@Hixie Done. I also made the script a bit more readable. But I may be missing some reason it was all on the same line earlier.

**Comment by Hixie** [comment]
lgtm

**Pull request merged**
