### PR TITLE
Cleanup refactoring in FlKeyboardManager

### PR DESCRIPTION
**Pull request by robert-ancell**
Remove pending keyboard event ID and use the object directly.

Use references to make sure FlKeyboardManagerData is freed.

Refactor marking events as handled

### CODE REVIEW

**Comment by stuartmorgan** [comment]
test-exempt: code refactor with no semantic change

**Comment by mattkae** [comment]
@robert-ancell does [this other PR](https://github.com/flutter/engine/pull/56959) contain the same changes as this one? Maybe an accident?

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by robert-ancell** [comment]
> @robert-ancell does [this other PR](https://github.com/flutter/engine/pull/56959) contain the same changes as this one? Maybe an accident?

The other PR is built on top of these changes.

**Pull request merged**
