### PR TITLE
Use the ELF loader to setup AOT symbols in benchmark runner.

### PR DESCRIPTION
**Pull request by chinmaygarde**
We no longer package AOT artifacts as discrete blobs. The portable ELF loader
from the testing library may be used instead.

Fixes https://github.com/flutter/flutter/issues/52263

### CODE REVIEW

**Comment by chinmaygarde** [comment]
I am not sure I want to start building an entire engine variant just to run a benchmark whose results we won't collect. I'll see if the profile stuff will work instead.

**Comment by chinmaygarde** [comment]
Oh. I see what you meant. Won't this be checked implicitly when `parse_and_send.dart` is used to collect this benchmark?

**Comment by liyuqian** [comment]
@chinmaygarde : the `build_and_benchmark_linux_release` tasks only runs in post-submit (`only_if: $CIRRUS_BRANCH == 'master'`). That's why I suggest creating another task `build_and_test_linux_release` without the `only_if` condition. Such task also does more  test in release mode than just benchmarks since it's using `./flutter/testing/run_tests.sh host_release` instead of triggering benchmarks individually.

**Comment by chinmaygarde** [comment]
Roger. I will patch that separately after I shepherd another patch to master.

**Comment by liyuqian** [comment]
@chinmaygarde : no worry, I can also do that: https://github.com/flutter/engine/pull/17073

**Comment by chinmaygarde** [comment]
Thanks. I appreciate it.

**Pull request merged**
