### PR TITLE
Reland "Remove pipeline in favor of layer tree holder"

### PR DESCRIPTION
**Pull request by iskakaushik**
This reverts commit 04afdadbb55201133f956fd0346423c8527dffc8.

This had to be reverted because of https://github.com/flutter/flutter/issues/76216. This has been fixed in 28603f15e67a67f6222c7fcd14ce162c221b211a.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
I specifically reviewed https://github.com/flutter/engine/commit/28603f15e67a67f6222c7fcd14ce162c221b211a. I believe the rest was identical to the reverted patch.

**Comment by chinmaygarde** [comment]
@iskakaushik This removed the PipelineItem flow that DevTools was using to detect the duration of a frame as it was being serviced on the two threads. I think we can recreate the flow in this new mechanism. Can we revert it (sadly, once again) and add that flow to unblock DevTools or do you want to fix forward by adding the flow?

cc @kenzieschmoll

**Comment by iskakaushik** [comment]
Yup, will revert it. I want to debug https://github.com/flutter/flutter/issues/78257#issuecomment-800603775 as well so maybe two birds with one stone. Though this particular stone (reverting this change) has been used multiple times.

**Comment by chinmaygarde** [comment]
Right, subtle changes to scheduling are no fun to push through. We need to tackle https://github.com/flutter/flutter/issues/27609 correctly anyway. Right now, I doubt we have the bandwidth to create a test harness that allows us to reason about frame scheduling and trace emission.

**Comment by flar** [comment]
Are they prepared for flows that start and never end? Should we establish a "flow aborted" event that they can look for to see when frames are dropped on the floor?

**Comment by chinmaygarde** [comment]
> Are they prepared for flows that start and never end?

Likely not. The current behavior [is to "end" flows](https://github.com/flutter/engine/blob/5b3bbfa2bebe99940e6c726094293744a765540f/shell/common/pipeline.h#L57) that are being prematurely terminated. That is, there is no difference between a successful or unsuccessful flow. But it always ends.

**Comment by flar** [comment]
It looks like there already were existing ways to prematurely end flows before so this should be no different - but it will be more common.

We might want to ask them if they'd like a way to distinguish dropped frames from completed frames now that they will be more common.

**Pull request merged**
