### PR TITLE
Exclude frontend_server from the license crawl

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@Hixie @aam

**Comment by aam** [comment]
The thinking is that we need to keep track only of the licenses of the artifacts that ends up the users device(rather than a flutter developer's workstation)?

**Comment by Hixie** [comment]
We have to keep track of all the licenses, but the license script itself generates the LICENSE file only for the engine-specific bits that end up in the APK or IPA file.

**Comment by Hixie** [comment]
(Having said that, this should have no impact on the actual license.)

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
