### PR TITLE
Codesign pub package vended service dylibs after copying them to the application bundle.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Xcode wrecked the formatting. The formatted script for reference https://gist.github.com/chinmaygarde/e691e0b256588a1ae885276b26899f5b

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/issues/4226

**Comment by abarth** [comment]
Can we put this script in `packages/flutter_tools/bin` so that we can maintain it even when we don't control the Xcode project?

**Comment by chinmaygarde** [comment]
The EXPANDED_CODE_SIGN_IDENTITY variable is one that is automatically set by Xcode during its build process. So I am pretty sure we can't separate this step out of Xcode.

**Comment by chinmaygarde** [comment]
We could export it out and read it from ENV in the script though. Not sure if that is cleaner though.

**Comment by abarth** [comment]
Xcode doesn't set it in the env already?  It lets it locally and then sources the script?

**Comment by chinmaygarde** [comment]
I am thinking of moving out `BuildFlutterApp` as well as this script out into `flutter_tools` in a single patch. For some reason I thought I was already out of the Xcode project.

**Comment by abarth** [comment]
Yeah, I haven't landed that patch yet.

**Comment by abarth** [comment]
LGTM to land as-is.

**Pull request merged**
