### PR TITLE
[Linux] FlValue: add foreach functions for list & map

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

Inspired by g_xxx_foreach(). These are convenient for iterating entire collections when the index is not needed.

## Related Issues

-

## Tests

I added the following tests:

- FlValueTest, ListForeach
- FlValueTest, MapForeach

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by jpnurmi** [comment]
@robert-ancell: What do you think?

**Comment by jpnurmi** [comment]
Example: https://github.com/jpnurmi/plugins/blob/file_selector_linux/packages/file_selector/file_selector_linux/linux/file_selector_linux_plugin.cc#L86

**Comment by robert-ancell** [comment]
@jpnurmi one of the things we want to avoid with `FlValue` is implementing a full container system. These objects should be light-weight and the user can transform the data into other containers if required. Is there a particular case you had where iterating over a list/map with these functions was easier than just using `fl_value_get_length`, `fl_value_get_list_value`, `fl_value_lookup`?

**Comment by jpnurmi** [comment]
Ok, this was just about syntactic sugar and convenience.

```
fl_value_list_foreach(list, do_something);
```

vs.

```
size_t length = fl_value_get_length(list);
for (size_t i = 0; i < length; ++i) {
  FlValue *value = fl_value_get_list_value(i);
  do_something(value);
}
```

The latter can be of course compacted to:

```
for (size_t i = 0; i < fl_value_get_length(list); ++i) {
  do_something(fl_value_get_list_value(i));
}
```

But no matter how you format it, readability is not on the same level as the foreach version, and you end up calling `fl_value_get_length()` repeatedly.

**Comment by jpnurmi** [comment]
Could the internal storage of `FL_VALUE_TYPE_LIST` and `FL_VALUE_TYPE_MAP` be `GPtrArray` and `GHashTable`, respectively? (And provide API to allow conversion from/to `FlValue`.) This would also solve the efficiency problem of `fl_value_lookup_index`?

**Comment by chinmaygarde** [comment]
@robert-ancell @jpnurmi: Can we make progress on this PR?

**Comment by robert-ancell** [comment]
I'm leaning towards not landing this change, due to us not wanting to add a full container system. I think we'd have to have evidence that the existing containers were sufficiently inefficient to justify APIs to improve them. Note of course you can easily write a helper function in your own application to implement `fl_value_list_foreach` if that better matches the style of the consuming code.

@stuartmorgan I need a second opinion on this - I think you had a stronger opinion on keeping this API light.

Exposing the internal structures for the objects would be dangerous, as then they could be changed in inconsistent ways. Note that `FL_VALUE_TYPE_MAP` can't be a `GHashTable` as we want to retain the order the values were received.

**Comment by jpnurmi** [comment]
Yeah, I've used such a helper in some personal projects, which is how I got the idea of contributing this. I just missed the memo and didn't know the goal was to keep FlValue as slim as possible. Anyway, I don't have anyhow strong feelings about having this in the official plugin API. :)

**Comment by stuartmorgan** [comment]
> @stuartmorgan I need a second opinion on this - I think you had a stronger opinion on keeping this API light.

I don't want us to end up in the business of maintaining entire complex collection classes; that said, if there are targeted, high-utility convenience methods we could consider them. In the C++ version I avoided this problem by exposing the STL containers directly, so we wouldn't have to have a trade-off between complexity of code to maintain and ease of use, but since there wasn't a comparable standard container to use here we can adjust that balancing point as necessary.

**Pull request closed without merging**
