### PR TITLE
[icu] Update icu to 12de966fcbe1d1a48dba310aee63807856ffeee8

### PR DESCRIPTION
**Pull request by filmil**
Issue: https://github.com/flutter/flutter/issues/105342

Rolls a very new version of the ICU library.

Fixes: https://github.com/flutter/flutter/issues/87073

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by filmil** [comment]
Needs an update of the license parsing code.  I think we had this somewhere in the prior attempt at updating this, so I will try to go there and see how the fix was done.

**Comment by filmil** [comment]
https://github.com/flutter/engine/pull/33274 has the needed license fixes, I think.

**Comment by filmil** [comment]
Correction: https://github.com/flutter/engine/pull/32879

**Comment by filmil** [comment]
@jason-simmons Would you mind approving this for merge if you are OK with the change?

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
