### PR TITLE
solve some crash issues on some Huawei phones

### PR DESCRIPTION
**Pull request by buaashuai**
**This commit solved the following crash on some Huawei and Xiaomi phones.**

```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: , PID: 18747
AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.left' on a null object reference
AndroidRuntime: at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:608)
AndroidRuntime: at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:1261)
AndroidRuntime: at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1174)
AndroidRuntime: at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
AndroidRuntime: at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
AndroidRuntime: at android.view.AccessibilityInteractionController.-wrap1(Unknown Source:0)
AndroidRuntime: at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: at android.os.Looper.loop(Looper.java:176)
AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6651)
AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

Edit: related issue: [flutter/flutter#55210](https://github.com/flutter/flutter/issues/55210).

### CODE REVIEW

**Comment by buaashuai** [comment]
@googlebot I signed it!

**Comment by liyuqian** [comment]
The fix looks good. @goderbauer @xster : I'm curious if `semanticsNode.parent.getGlobalRect()` returning `null` signals some other bugs in our system, and if there's a nice way to test this `null` situation?

**Comment by goderbauer** [comment]
I believe `globalRect` is never supposed to be null (see also error check in [1]). If it ever ends up being null we should figure out why. This fix just seems to be papering over another issue somewhere else in Flutter.

[1] https://github.com/flutter/engine/blob/b9059b55d7925f34e4c5d55a6afba14e3f1d9ba4/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L2189

**Comment by liyuqian** [comment]
@buaashuai : What's the exact Huawei or Xiaomi device model that triggers this issue? What's the detailed steps to reproduce this null pointer exception?

@kf6gpe has a few popular Huawei and Xiaomi low-end devices for us to fix this kind of device-specific issue. Hopefully the device model matches.

**Comment by buaashuai** [comment]
@liyuqian This is a crash with the higher probability of occurrence, but is not always happen. We counted over 400 crashes caused by it. The 3 phones with the highest probability of appearing this crash are the following:  REDMI 5 PLUS, Huawei MHA AL00, and Huawei BLA AL00. 
We compiled our own flutter engine based on this commit record. Our own compiled flutter engine was online for over 2 months and this crash never came back!

**Comment by liyuqian** [comment]
@kf6gpe has "HUAWEI BKL-AL00 华为荣耀v10" so we can reproduce locally if there's a sample app.

@goderbauer : shall we land this `null` guard, and maybe add some error reporting code to get us more information about how this could happen? My concern is that many devices could be crashing without this patch, and we also don't get any more details about the crash if we don't make any code changes.

@buaashuai : can you please post your Flutter version, and let us know if you have any local changes to the Flutter engine? This issue could also be caused by an older Flutter version which is later fixed, or maybe some conflicts in your local engine changes.

**Comment by buaashuai** [comment]
@liyuqian Our flutter engine is based on the 1.9.1.hotfix.6. Once again, we compared the code differences between our engine source code directory and the official engine directory as a whole. No other code changes were found.

**Comment by GaryQian** [comment]
@liyuqian Just a ping to see if we can move forwards with this.

**Comment by goderbauer** [comment]
@liyuqian I would very much prefer that we figure out why this ends up to be null instead of papering over the failure. There may be a more serious issue underneath. 

/cc @xster

**Comment by liyuqian** [comment]
@goderbauer : I'd love to figure out the root cause and fix it too. I'm not sure if we have enough information to figure it out so I'm curious if we need to add some code to report more information. @xster may have more knowledge about that.

While we're searching the root cause, we can either:
1. Paper the crash issue; add some error/warning logging, and create a critical Github issue to track it.
2. Or leave the crash issue as is.

Which option would you prefer?

**Comment by gaaclarke** [comment]
The issue this PR is addressing doesn't present itself in version 1.17.3 so it appears to have been fixed elsewhere: https://github.com/flutter/flutter/issues/55210#issuecomment-644586104

**Comment by zhoujuanjuan** [comment]
Has anyone found the root cause of this problem, this crash still exists.

**Pull request closed without merging**
