### PR TITLE
Modernize GrContext creation.

### PR DESCRIPTION
**Pull request by bsalomon**
Use backend-specific factories that take and return sk_sp<>s rather than bare pointers.

### CODE REVIEW

**Comment by bsalomon** [comment]
@jason-simmons, could you review and land this if ok?

**Comment by jason-simmons** [comment]
@chinmaygarde does this affect your refactoring?

**Comment by chinmaygarde** [comment]
Yes. But should merge cleanly. LGTM.

**Comment by bsalomon** [comment]
Great! I don't have rights to land this. Could one of you submit it?

**Pull request merged**
