### PR TITLE
[WIP] Throw error sync instead of completing with error

### PR DESCRIPTION
**Pull request by jonahwilliams**
If a synchronous completer completes with an error before a listener has been added, the error will propagate through the Zone's uncaught exception handler. To prevent this from happening, we should throw the error synchronously instead of into the completer, so that it can be caught normally.

### CODE REVIEW

**Comment by cbracken** [comment]
Curious whether you considered async-ifying sync tasks (e.g. by throwing them on the microtask queue), which has the advantage of being easier to follow and preserving the existing contract?

I haven't looked at where and how this is used and what impact that would have.

Also, we'll need a test.

**Comment by jonahwilliams** [comment]
> Curious whether you considered async-ifying sync tasks (e.g. by throwing them on the microtask queue), 

I think the concern with non-sync completers is the risk of pushing a synchronous operation out n-frames due to a chain of futures. I think that won't happen with the microtask queue though?

**Comment by cbracken** [comment]
The microtask queue is always flushed at the beginning of the next event loop turn.

**Comment by jonahwilliams** [comment]
Closing until I get more time to look at this

**Pull request closed without merging**
