### PR TITLE
DEPS in impeller and build unit tests

### PR DESCRIPTION
**Pull request by zanderso**
To get the impeller unit tests building, I had to make these changes along with https://github.com/flutter/buildroot/pull/545 in the buildroot.

Impeller expects `flutter::Dispatcher::transformReset()` to exist so I added it to the interface, and empty implementations where needed to build, but I don't know if they need real implementations.

@chinmaygarde @bdero @flar

### CODE REVIEW

**Comment by zanderso** [comment]
Expected to fail outside of Mac. But failing on Mac with:
```
FAILED: shaders/shader_fixtures.metallib 
python3 ../../flutter/impeller/tools/build_metal_library.py --output shaders/shader_fixtures.metallib --depfile /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/flutter/impeller/fixtures/shader_deps/shader_fixtures.depfile --platform=mac --source gen/flutter/impeller/fixtures/box_fade.vert.metal --source gen/flutter/impeller/fixtures/box_fade.frag.metal --source gen/flutter/impeller/fixtures/test_texture.vert.metal --source gen/flutter/impeller/fixtures/test_texture.frag.metal
metal: error: unknown argument: '-frecord-sources'
```

**Comment by zanderso** [comment]
Maybe this is an xcode version issue? @jmagman can you remind me which version of XCode is on Engine CI. I also remember there were discussions about upgrading. Do you know which version the upgrade is targeting?

**Comment by zanderso** [comment]
https://developer.apple.com/documentation/metal/libraries/generating_and_loading_a_metal_library_symbol_file seems to be saying that `-frecord-sources` is Xcode 13 and later.

**Comment by jmagman** [comment]
> https://developer.apple.com/documentation/metal/libraries/generating_and_loading_a_metal_library_symbol_file seems to be saying that `-frecord-sources` is Xcode 13 and later.

Ugh that's unfortunate, the engine builders are on Xcode 12.3.  @yusuf-goog is working on getting the engine builders macOS version updated to unblock the migration to Xcode 13 https://docs.google.com/document/d/1M9HqJeEAisqgClRfxdXYBhYWJdiu2A-zSOovCBO7yjg/edit# (internal link)

**Comment by chinmaygarde** [comment]
We don't need Xcode 13 for Impeller. The `-frecord-sources` is the much more readable version of the [older `-M0` flag](https://github.com/flutter/impeller/commit/cae1b1a3bb0b11843e45dbafe55a6f2f6eb1377c#diff-342e7503062f700b6baddd37ff8d256d6e8dcc0959877e747a5f8f97471be6d8L42) that puts sources and driver options in the compiled shader output so that profile mode builds enable shader debugging and profiling.

I used the newer flag after reading about it in the man page when I was re-reading my own code and could not figure out what M0 meant. I'll back it out.

**Comment by zanderso** [comment]
Adjusted license checker for stb and filed https://github.com/flutter/flutter/issues/97843 for its removal.

**Review by bdero — APPROVED** [review]
lgtm 👍 I wiped away my setup and successfully ran `impeller_unittests` against this branch.

**Pull request merged**
