### PR TITLE
Update the default iOS simulator launch scheme to include command line arguments for launching directly from source.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I don't really know what this does. :)  Could you update the description?

**Comment by chinmaygarde** [comment]
When launching the application for the simulator from Xcode (i.e. without any support from flutter_tools) the new arguments tell the the engine to load the dart sources directly instead of looking inside the app.flx for the script snapshot. This should only affect users who use Xcode directly. flutter_tools should do this for you automatically.

**Comment by eseidelGoogle** [comment]
Does `flutter start` automatically upgrade this part of the xcode project, or will this only affect users who create projects after this?  Doesn't really matter, just curious.  lgtm regardless.

**Comment by chinmaygarde** [comment]
Yeah, `flutter start` sets this up automatically and manages updates to this.

**Pull request merged**
