### PR TITLE
[Linux][a11y] implement AtkText::get_text/string_at_offset()

### PR DESCRIPTION
**Pull request by jpnurmi**
This PR implements `AtkText::get_string_at_offset()` (and the deprecated `AtkText::get_text_at_offset()` still used by e.g. Orca) for `FlAccessibleTextField` to allow Orca to read out loud the current character while moving the text cursor around.

### Before (unmute to hear the screen reader)

[textfield-a11y-before.webm](https://user-images.githubusercontent.com/140617/206556644-fb4f4df8-acca-4d97-86d5-7120f0a4871d.webm)

### After (unmute to hear the screen reader)

[textfield-a11y-after.webm](https://user-images.githubusercontent.com/140617/206556678-4fbf9112-291e-4518-a258-e9ca33469430.webm)

Fixes: flutter/flutter#113049

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by robert-ancell — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
I can reproduce the fontconfig leaks with:
```c
#include <cairo/cairo.h>
#include <fontconfig/fontconfig.h>
#include <pango/pango.h>
#include <pango/pangocairo.h>

int main()
{
    PangoFontMap* font_map = pango_cairo_font_map_get_default();

    PangoContext* context = pango_font_map_create_context(font_map);
    pango_context_set_base_dir(context, PANGO_DIRECTION_LTR);

    PangoLayout* layout = pango_layout_new(context);
    pango_layout_set_text(layout, "Lorem ipsum dolor sit amet.", -1);

    gint n_attrs = 0;
    pango_layout_get_log_attrs_readonly(layout, &n_attrs);

    g_object_unref(context);
    g_object_unref(layout);

    //cairo_debug_reset_static_data(); // cairo-hash.c:217: _cairo_hash_table_destroy: Assertion `hash_table->live_entries == 0' failed.

    //FcFini(); // fccache.c:801: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.
}
```
```
=================================================================
==661327==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2560 byte(s) in 4 object(s) allocated from:
    #0 0x557f9e5bf1a6 in __interceptor_realloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa41a6) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df6ba0 in FcPatternObjectInsertElt /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:536:24

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x557f9e5bed7e in malloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3d7e) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df6b01 in FcPatternObjectInsertElt /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:545:24

Indirect leak of 8224 byte(s) in 257 object(s) allocated from:
    #0 0x557f9e5bed7e in malloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3d7e) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5de389f in FcConfigValues /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fccfg.c:1374:25

Indirect leak of 2967 byte(s) in 247 object(s) allocated from:
    #0 0x557f9e5a90b3 in __interceptor_strdup (/home/jpnurmi/Temp/pango-test/pango-test+0x8e0b3) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5de2f5a in IA__FcValueSave /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:103:10
    #2 0x7f30b5de2f5a in FcConfigEvaluate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fccfg.c:996:6

Indirect leak of 2272 byte(s) in 71 object(s) allocated from:
    #0 0x557f9e5bef68 in __interceptor_calloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3f68) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df95fe in FcValueListCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:136:12
    #2 0x7f30b5df95fe in FcPatternObjectAddWithBinding /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:707:11

Indirect leak of 1600 byte(s) in 50 object(s) allocated from:
    #0 0x557f9e5bef68 in __interceptor_calloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3f68) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df673a in FcValueListCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:136:12
    #2 0x7f30b5df673a in FcValueListDuplicate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:230:16

Indirect leak of 447 byte(s) in 46 object(s) allocated from:
    #0 0x557f9e5a90b3 in __interceptor_strdup (/home/jpnurmi/Temp/pango-test/pango-test+0x8e0b3) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df65d7 in FcValueSave /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:103:10

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x557f9e5bef68 in __interceptor_calloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3f68) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5dff1ee in FcValueListCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:136:12
    #2 0x7f30b5dff1ee in FcValueListPrepend /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:180:11
    #3 0x7f30b5dff1ee in FcFontRenderPrepare /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcmatch.c:601:13

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x557f9e5bef68 in __interceptor_calloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3f68) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5dff18d in FcValueListCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:136:12
    #2 0x7f30b5dff18d in FcValueListPrepend /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:180:11
    #3 0x7f30b5dff18d in FcFontRenderPrepare /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcmatch.c:597:13

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x557f9e5bed7e in malloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3d7e) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5dedc24 in IA__FcLangSetCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fclang.c:476:10
    #2 0x7f30b5dedc24 in FcLangSetCopy /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fclang.c:504:11

Indirect leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x557f9e5bef68 in __interceptor_calloc (/home/jpnurmi/Temp/pango-test/pango-test+0xa3f68) (BuildId: 685597842a2e40c7906d33c2793590f2c36cd54f)
    #1 0x7f30b5df66dc in FcValueListCreate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:136:12
    #2 0x7f30b5df66dc in FcValueListDuplicate /build/fontconfig-Aho6Ty/fontconfig-2.13.1/src/fcpat.c:234:16

SUMMARY: AddressSanitizer: 18870 byte(s) leaked in 692 allocation(s).
```

**Comment by chinmaygarde** [comment]
Was this leak related to the patch?

**Comment by jpnurmi** [comment]
Yeah, the leak is related to this patch. An indirect dependency (libfontconfig) leaks some static data that I didn't find a way to reset.

**Comment by chinmaygarde** [comment]
If its static data in a third party dependency, we can add it to the list of suppressions to work around it. The suppressions list is at [lsan_suppressions.txt here](https://github.com/flutter/engine/blob/33d7f8a1b307dc46fe969facf0e1feba6f40aeb2/testing/lsan_suppressions.txt).

**Comment by chinmaygarde** [comment]
The suppressions seemed to have worked but the test failure seems related to the patch.

**Comment by jpnurmi** [comment]
@chinmaygarde could it be that the CI is missing libfontconfig debug symbols?

The tests are passing locally with the same build flags and sanitizers and with `libfontconfig1-dbgsym` installed:
```
$ fle-test --gtest_filter="*FlAccessibleTextField*"
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
Note: Google Test filter = *FlAccessibleTextField*
[==========] Running 16 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from FlAccessibleTextFieldTest
[ RUN      ] FlAccessibleTextFieldTest.SetValue
[       OK ] FlAccessibleTextFieldTest.SetValue (9 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetTextSelection
[       OK ] FlAccessibleTextFieldTest.SetTextSelection (5 ms)
[ RUN      ] FlAccessibleTextFieldTest.PerformAction
[       OK ] FlAccessibleTextFieldTest.PerformAction (4 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetCharacterCount
[       OK ] FlAccessibleTextFieldTest.GetCharacterCount (3 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetText
[       OK ] FlAccessibleTextFieldTest.GetText (4 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetCaretOffset
[       OK ] FlAccessibleTextFieldTest.GetCaretOffset (5 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetCaretOffset
[       OK ] FlAccessibleTextFieldTest.SetCaretOffset (4 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetNSelections
[       OK ] FlAccessibleTextFieldTest.GetNSelections (6 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetSelection
[       OK ] FlAccessibleTextFieldTest.GetSelection (8 ms)
[ RUN      ] FlAccessibleTextFieldTest.AddSelection
[       OK ] FlAccessibleTextFieldTest.AddSelection (9 ms)
[ RUN      ] FlAccessibleTextFieldTest.RemoveSelection
[       OK ] FlAccessibleTextFieldTest.RemoveSelection (8 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetSelection
[       OK ] FlAccessibleTextFieldTest.SetSelection (10 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetTextContents
[       OK ] FlAccessibleTextFieldTest.SetTextContents (15 ms)
[ RUN      ] FlAccessibleTextFieldTest.InsertDeleteText
[       OK ] FlAccessibleTextFieldTest.InsertDeleteText (18 ms)
[ RUN      ] FlAccessibleTextFieldTest.CopyCutPasteText
[       OK ] FlAccessibleTextFieldTest.CopyCutPasteText (15 ms)
[ RUN      ] FlAccessibleTextFieldTest.TextBoundary
[       OK ] FlAccessibleTextFieldTest.TextBoundary (64 ms)
[----------] 16 tests from FlAccessibleTextFieldTest (197 ms total)

[----------] Global test environment tear-down
[==========] 16 tests from 1 test suite ran. (197 ms total)
[  PASSED  ] 16 tests.
-----------------------------------------------------
Suppressions used:
  count      bytes template
   1027      27939 Fc*
-----------------------------------------------------
```

If I uninstall `libfontconfig1-dbgsym`, I get similar results than the CI:
```
$ fle-test --gtest_filter="*FlAccessibleTextField*"
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
Note: Google Test filter = *FlAccessibleTextField*
[==========] Running 16 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from FlAccessibleTextFieldTest
[ RUN      ] FlAccessibleTextFieldTest.SetValue
[       OK ] FlAccessibleTextFieldTest.SetValue (11 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetTextSelection
[       OK ] FlAccessibleTextFieldTest.SetTextSelection (3 ms)
[ RUN      ] FlAccessibleTextFieldTest.PerformAction
[       OK ] FlAccessibleTextFieldTest.PerformAction (3 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetCharacterCount
[       OK ] FlAccessibleTextFieldTest.GetCharacterCount (4 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetText
[       OK ] FlAccessibleTextFieldTest.GetText (5 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetCaretOffset
[       OK ] FlAccessibleTextFieldTest.GetCaretOffset (6 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetCaretOffset
[       OK ] FlAccessibleTextFieldTest.SetCaretOffset (7 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetNSelections
[       OK ] FlAccessibleTextFieldTest.GetNSelections (10 ms)
[ RUN      ] FlAccessibleTextFieldTest.GetSelection
[       OK ] FlAccessibleTextFieldTest.GetSelection (16 ms)
[ RUN      ] FlAccessibleTextFieldTest.AddSelection
[       OK ] FlAccessibleTextFieldTest.AddSelection (19 ms)
[ RUN      ] FlAccessibleTextFieldTest.RemoveSelection
[       OK ] FlAccessibleTextFieldTest.RemoveSelection (16 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetSelection
[       OK ] FlAccessibleTextFieldTest.SetSelection (13 ms)
[ RUN      ] FlAccessibleTextFieldTest.SetTextContents
[       OK ] FlAccessibleTextFieldTest.SetTextContents (14 ms)
[ RUN      ] FlAccessibleTextFieldTest.InsertDeleteText
[       OK ] FlAccessibleTextFieldTest.InsertDeleteText (11 ms)
[ RUN      ] FlAccessibleTextFieldTest.CopyCutPasteText
[       OK ] FlAccessibleTextFieldTest.CopyCutPasteText (10 ms)
[ RUN      ] FlAccessibleTextFieldTest.TextBoundary
[       OK ] FlAccessibleTextFieldTest.TextBoundary (54 ms)
[----------] 16 tests from FlAccessibleTextFieldTest (216 ms total)

[----------] Global test environment tear-down
[==========] 16 tests from 1 test suite ran. (216 ms total)
[  PASSED  ] 16 tests.

=================================================================
==497613==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3840 byte(s) in 6 object(s) allocated from:
    #0 0x555ec77521f8 in __interceptor_realloc (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x27b21f8) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c419ba0  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1fba0) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x555ec7751dce in malloc (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x27b1dce) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c419b01  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1fb01) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

Indirect leak of 12192 byte(s) in 381 object(s) allocated from:
    #0 0x555ec7751dce in malloc (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x27b1dce) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c40689f  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc89f) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

Indirect leak of 4493 byte(s) in 372 object(s) allocated from:
    #0 0x555ec773bd50 in strdup (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x279bd50) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c405f5a  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbf5a) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

Indirect leak of 3360 byte(s) in 105 object(s) allocated from:
    #0 0x555ec7751fb8 in calloc (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x27b1fb8) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c41c5fe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x225fe) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

Indirect leak of 2304 byte(s) in 72 object(s) allocated from:
    #0 0x555ec7751fb8 in calloc (/home/jpnurmi/Projects/flutter/engine/src/out/host_debug_unopt/flutter_linux_unittests+0x27b1fb8) (BuildId: 2969a0e1625b6bd5644513c6a4bee2f1d698cf77)
    #1 0x7fc54c41973a  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1f73a) (BuildId: ce289bdc2072549c61ee8b046ce1b3d42cab36be)

-----------------------------------------------------
Suppressions used:
  count      bytes template
     90       1494 Fc*
-----------------------------------------------------

SUMMARY: AddressSanitizer: 26445 byte(s) leaked in 937 allocation(s).
```

**Comment by chinmaygarde** [comment]
Not sure. cc @cbracken might know.

**Comment by zanderso** [comment]
@chinmaygarde @cbracken @jason-simmons Do we know why fontconfig is dynamically linked? Looks like we're DEPSing it in here https://github.com/flutter/engine/blob/main/DEPS#L578.

**Comment by cbracken** [comment]
I think the TL;DR is that what's going on is a static allocation in libfontconfig that's being caught by asan, but because it's not built with debug symbols availabole, we're unable to filter it out in our allow-list. If we're building fontconfig ourselves, then we can probably just update build flags for the debug build, assuming we're not running sanitisers on non-debug builds.

**Comment by chinmaygarde** [comment]
> If we're building fontconfig ourselves

Are we building it ourselves? I don't see build rules for it.

**Comment by chinmaygarde** [comment]
cc @cbracken. This seems to have been blocked for a while. I am not sure how to make progress here. Can you please take a look at this when you get a chance please?

**Comment by chinmaygarde** [comment]
Closing as stale.

**Comment by jpnurmi** [comment]
Testing if #40725 helped

**Comment by chinmaygarde** [comment]
I don't think it did. Can we asses the scope of the leak and suppress it and investigate in a followup?

**Review by cbracken — APPROVED** [review]
re-lgtm!

**Pull request merged**
