### PR TITLE
Script for running javadoc on the Flutter Android libraries

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Aw man, more python. :-P

**Comment by eseidelGoogle** [comment]
If we feel passionately anti-python, I know it's possible to run dart scripts on travis and our chromium infra.  I'm not entirely sure the constraints for one language vs. another are.

**Comment by Hixie** [comment]
I don't think there's any passionate feeling one way or the other, I just prefer everything in one language for sanity's sake. :-)

**Pull request merged**
