### PR TITLE
[impellerc] remove remaining remap sampler support

### PR DESCRIPTION
**Pull request by jonahwilliams**
Usage removed in https://github.com/flutter/flutter/pull/119346

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I don't believe I need a test exception because this is a delete-only PR

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
> I don't believe I need a test exception because this is a delete-only PR

Is this a bug in the bot?

**Comment by jonahwilliams** [comment]
bug and/or limitation 😄

**Comment by zanderso** [comment]
Removing the flag from building the shaders for the text fixture is also updating the test.

**Pull request merged**
