### PR TITLE
[Fuchsia] Create dedicated testers to run tests and deprecate femu_test

### PR DESCRIPTION
**Pull request by zijiehe-google-com**
This change creates a fuchsia_profile_arm64_tester builder inside of the existing linux_fuchsia group. Comparing with fuchsia_profile_arm64, it uses `--no-lto` to limit the cost of compilation of test suites.
Similar to the fuchsia_profile_x64, it runs release build test cases + aot test.

E.g. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1998852/overview or more accurately https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755990392554423809/+/u/test:_arm64_emulator_based_profile___aot_tests/stdout.

The same approach also applied to other builders. Now each fuchsia builder has its own tester which compiles test cases without lto. The change reduces the time cost of linux_fuchsia to around 20 min, e.g. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_fuchsia/6662/overview

After this change, linux_fuchsia group has a higher coverage than the combination of linux fuchsia emu + linux fuchsia emu arm64. So I removed both builders from the `.ci.yaml` as well.

Bug: https://github.com/flutter/flutter/issues/140179

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]
Nice, thanks!

\cc @keyonghan as we can remove https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/femu_test.py after this lands.

**Comment by zijiehe-google-com** [comment]
Yes, Zachary, as we discussed before, I do believe the current setup is not ideal.
The time consumption can be categorized into three,
1) build & test, ~10min. Multiple drones are running in parallel, so changes like this one won't meaningfully impact the overall time.
2) archive, upload and download via cas. 6 out of 7 (without the one added in this change) are uploading the binaries to cas in parallel, and they will then be downloaded in sequential. Each of them costs around 40 seconds. Previously it was ~10 seconds each, but newly added test targets increased the consumption. (from ~1 min to ~4 min).
3) upload archives to cipd. The binaries from the step 2 are uploaded to cipd. It costs 10-15 min. Newly added targets do not noticeably increase the time, time consumption of cipd itself is not very stable anyway.

So it's pretty obvious, both the try & prod builds do not need to run every step above. I.e.
Try: run build & test only, the cost will be dropped to ~10min.
  - Archiving the try built binaries seems not reasonable.
Prod: run build, archive & upload only. The cost reduction may not be noticeable, since the lto build usually is the slowest, and they are running in parallel.
  - The tests are fairly reliable - I haven't noticed any flakiness so far. Any broken changes should be caught by the try builders anyway.

But the above improvements need to make the try and prod builds different, I am not very sure if it's easy doable in the current setup.

For the immediate action, I can go through several latest prod runs and see if any noticeable slow tests can be excluded as low hanging fruit, and update this CL.

Let me know your opinion.

**Comment by zanderso** [comment]
Reducing are sharding the tests that are running sounds like the right approach to me. The appropriate differences between prod and try would need to be coordinated with @CaseyHillers.

**Comment by zijiehe-google-com** [comment]
> Reducing are sharding the tests that are running sounds like the right approach to me. The appropriate differences between prod and try would need to be coordinated with @CaseyHillers.

Done

**Comment by zanderso** [comment]
I see https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_fuchsia/6672/overview completed in 18 minutes. Awesome!

**Review by zanderso — APPROVED** [review]

**Comment by zijiehe-google-com** [comment]
I will wait for next Monday to submit this change.

**Review by jrwang — APPROVED** [review]

**Comment by zijiehe-google-com** [comment]
FYI, the latest run dropped from 46m to 24m:

```
[1520](https://ci.chromium.org/ui/b/8755549448127997041)	2024-02-20 10:39	2024-02-20 11:03	24m	[22a709cc7](https://flutter.googlesource.com/mirrors/engine/+/22a709cc7bdd24f9a94c918639c96c33019467b8)	
No Summary.

[1519](https://ci.chromium.org/ui/b/8755553208092091921)	2024-02-20 09:40	2024-02-20 10:25	46m	[d2b5dfdb4](https://flutter.googlesource.com/mirrors/engine/+/d2b5dfdb4e0c6b2891159500f1520226fffa8049)	
No Summary.
```

**Pull request merged**
