### PR TITLE
fuchsia: Enable most unittests

### PR DESCRIPTION
**Pull request by arbreng**
Tweak the primary flutter build rule so that fuchsia is more similar to
other platforms in how tests and the shell are built.

Only embedder_unittests and GLFW tests are disabled on Fuchsia now.

TEST: Ran unittests on host/fuchsia; workstation on fuchsia
BUG: fxb/53847, fxb/54056

### CODE REVIEW

**Comment by gw280** [comment]
Try run: https://ci.chromium.org/swarming/task/4d484c899cc07310?server=chromium-swarm.appspot.com

**Comment by gw280** [comment]
I think we should add the new tests to run_tests.sh in this PR. At the very least, we should have a try run on LUCI with those tests enabled so we can see what's happening right now.

**Comment by arbreng** [comment]
Agreed, will upload a new version soon with the tests added to the script (and hopefully passing).

**Comment by arbreng** [comment]
https://chromium-swarm.appspot.com/task?id=4d6340dbf67b9d10

**Comment by a-siva** [comment]
How come this PR did not run through all the usual engine checks (24 checks) , in the comments above when I click on the green arrow I see only 1 successful check or in the final one 7 successful checks.

**Comment by arbreng** [comment]
> How come this PR did not run through all the usual engine checks (24 checks) , in the comments above when I click on the green arrow I see only 1 successful check or in the final one 7 successful checks.

Your guess is as good as mine :(  I have to run jobs on the try bots because for some reason all the engine checks don't run on my PR

**Pull request merged**
