### PR TITLE
[CP][Impeller] Adds test to verify wide gamut indexed png decompression fix for Skia. (#45399)

### PR DESCRIPTION
**Pull request by gaaclarke**
cherry pick of https://github.com/flutter/engine/pull/45399

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Is this cherry picking just the test or the fix + test?

**Comment by gaaclarke** [comment]
just the test, the fix is in skia

**Comment by chinmaygarde** [comment]
@CaseyHillers We are not sure what to do with this. The linked CP issue was closed but this patch is still open.

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
Sorry @gaaclarke for letting this slip. Autosubmit didn't notify us we needed to review it. I've gone ahead and approved it, and will let autosubmit reland it.

**Comment by gaaclarke** [comment]
I got distracted by the effort to cherry-pick the fixes in skia.  I was thinking these getting left behind was a byproduct of that, otherwise I would have poked.

**Pull request merged**
