### PR TITLE
Restore creation of engine before Linux widget is realized.

### PR DESCRIPTION
**Pull request by robert-ancell**
Due to changes in the renderer in 6b857de the engine was created once a widget is realized, not when the widget is created. If a Flutter application changed the default my_application.cc template to show the Flutter widget after plugins are run then these plugins would not be able to access the engine.

Solved by removing the GdkWindow from the renderer constructor and setting in later when the widget is realized. This works because the renderer is not used until the widget is realized.
    
Fixes https://github.com/flutter/flutter/issues/144873

### CODE REVIEW

**Comment by robert-ancell** [comment]
Note this change also includes fixes for the weak reference handling which were causing the tests to crash after this change. This change should not be squashed so these commits are separate from the fix.

**Comment by robert-ancell** [comment]
@spydon please confirm if this fixes the issue for you.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by cbracken** [comment]
Kicked the failing mac bot. Looked like a Metal related flake unrelated to your change.

**Review by spydon — COMMENTED** [review]
Lgtm! Tried it on our the installer and the app center and it works with the plugins.

We still have the (most likely unrelated) issue where the start-up screen is black:
[Screencast from 2024-07-01 14-56-54.webm](https://github.com/flutter/engine/assets/744771/0891c4b8-7b76-4972-863c-dbb28e6fb8cc)
EDIT: The above only happens in debug mode

**Comment by Merrit** [comment]
I had thought this would be cherry-picked for a hotfix, but it still seems broken today with Flutter 3.22.3 - is the fix only available in `main` still?

**Comment by robert-ancell** [comment]
@merrit it is only availale in main. Since the change wasn't trivial I didn't want to propose it for a hotfix without being sure it is working well. I haven't seen any issues since this applied - @spydon have you seen any problems?

**Comment by spydon** [comment]
> @merrit it is only availale in main. Since the change wasn't trivial I didn't want to propose it for a hotfix without being sure it is working well. I haven't seen any issues since this applied - @spydon have you seen any problems? 

Everything has worked fine while I've tested it!

**Comment by robert-ancell** [comment]
Great, proposing for a cherry pick.

**Comment by robert-ancell** [comment]
This is now in 3.24, I won't propose it for 3.22 unless there is a need.

**Comment by Merrit** [comment]
Excellent! Thank you for all your hard work! :bowing_woman: 

I appreciate you :blue_heart: :grin:

**Comment by alexmercerind** [comment]
Thank you very much... it was very important.

**Pull request merged**
