### PR TITLE
[macOS] Do not block main thread during resizing if there is no content

### PR DESCRIPTION
**Pull request by knopp**
Fixes: https://github.com/flutter/flutter/issues/92673

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @cbracken

**Comment by a-wallen** [comment]
I'm not sure that this PR fixes https://github.com/flutter/flutter/issues/92673 because https://github.com/flutter/flutter/issues/92673 has two problems. 
> - [ ] The red box to immediately be replaced with nothing (a grey background)
> - [x] Upon resize, the window to be able to be resized, still just showing a grey background.

At the time of writing, this PR seems to solve _one_. I do think that we want this change, but I'm not sure if we can keep 
> Fixes: https://github.com/flutter/flutter/issues/92673

in the PR description without solving _both_ issues mentioned in https://github.com/flutter/flutter/issues/92673.

**Comment by chinmaygarde** [comment]
Ping @cbracken @a-wallen

**Comment by cbracken** [comment]
We'll need to author a test for this. I'll give it a shot.

**Review by cbracken — APPROVED** [review]
@a-wallen is writing a test for this. The fix itself lgtm; we can land this once his test has been added.

> The red box to immediately be replaced with nothing (a grey background)

Covered by this separate bug: https://github.com/flutter/flutter/issues/76082

**Comment by a-wallen** [comment]
Writing a unit test for this PR in the engine would be easiest via embedding this flutter application 
```dart
import 'package:flutter/widgets.dart';

void main() async {
  runApp(const ColoredBox(color: Color(0xffff0000)));
  runApp(const LimitedBox());
}
```
in a custom entry point for the embedder to consume. However, the engine cannot depend on the framework since the framework depends on the engine. There are two options to test this PR:
1. use `dart:ui` to emulate the behavior in the above program in a custom dart entrypoint.
2. write integration test in the framework which runs the example above and performs resize in an XCUITest.

**Comment by a-wallen** [comment]
The [PR above](https://github.com/flutter/flutter/pull/112008) should address the tests for this PR.

**Comment by Hixie** [comment]
test-exempt: test is separate

**Comment by chinmaygarde** [comment]
@knopp May I land this please? Everything looks good to go.

**Comment by a-wallen** [comment]
FYI @chinmaygarde, the test for this isn't done.

**Pull request merged**
