### PR TITLE
Don't wake up in GetNextTask

### PR DESCRIPTION
**Pull request by iskakaushik**
The thread is already awake at this point, and the next wake is scheduled in RegisterTask.

### CODE REVIEW

**Comment by iskakaushik** [comment]
@cyanglaz  I wasn't sure why we were waking up in GetNextTask, we have a lock held there and if a new task were to be registered, RegisterTask would call wake up anyways.

**Comment by chinmaygarde** [comment]
The old code doesn't make sense to me either as the wake seems redundant. Any updates @cyanglaz or issues you can think of with this patch?

**Comment by cyanglaz** [comment]
@chinmaygarde We talked offline, this change looks good. We just need tests to land this.

**Comment by chinmaygarde** [comment]
Is a testing strategy determined?

**Comment by chinmaygarde** [comment]
@iskakaushik I can't tell if the test failure in `EmbedderTest.CompositorRenderTargetsNotRecycledWhenAvoidsCacheSet` is related to this patch. It seems unlikely but I am not sure. Can you verify and make the presubmits pass please?

**Comment by chinmaygarde** [comment]
@iskakaushik Is progress on this patch likely? Perhaps we can close it for now and file a bug for followup instead?

**Pull request closed without merging**
