### PR TITLE
Reorganize darwin for shared ios/macOS

### PR DESCRIPTION
**Pull request by stuartmorgan**
When the macOS framework was initially landed, it included some iOS code
using a localized hack. This reorganizes the code structure to clearly
indicate which files are shared between iOS and macOS, vs. those that
are platform-specific.

### CODE REVIEW

**Comment by cbracken** [comment]
@stuartmorgan is this ready to land?

**Comment by dnfield** [comment]
This appeared to break our doc generation for iOS

**Comment by dnfield** [comment]
By break, I mean our docs no longer include the classes in files that got moved here.

**Comment by stuartmorgan** [comment]
I didn't realize there was automated document generation being pointed at this code. Could you file a bug, ideally with a pointer to the code that's generating it, and assign to me?

**Comment by dnfield** [comment]
See #9772 - which restores the old behavior.  It also adds a test of sorts that sanity checks the class output.

**Pull request merged**
