### PR TITLE
Dynamically link against system fontconfig

### PR DESCRIPTION
**Pull request by vially**
This is the engine counterpart for https://github.com/flutter/buildroot/pull/701. That pull-request contains more context and the main motivation for this change.

This should fix some startup performance issues related to font loading on desktop linux: https://github.com/flutter/flutter/issues/118911.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Waiting on hearing back on the original issue regarding the impact of this for third party embedders.

**Comment by chinmaygarde** [comment]
We believe this is good to go. The [buildroot patch that has been approved](https://github.com/flutter/buildroot/pull/701) needs to land first though.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by cbracken** [comment]
Thanks for applying the update. Looks great! Thanks for your patience @vially.

**Comment by cbracken** [comment]
Just noticed this doesn't include the buildroot roll. Can you update [this line](https://github.com/flutter/engine/blob/d953d0cdd36e9c5575070df5e12cfd301f445fe0/DEPS#L259) in the DEPS file with the value `e522d38d629d7522f0589e754886ed2b82232d9e`?

**Comment by cbracken** [comment]
Actually no worries - I pushed a commit to do it :)

**Pull request merged**
