### PR TITLE
Roll skia to 76d640d14ea78e1f827a2f545e7f0729cdc2896f

### PR DESCRIPTION
**Pull request by goderbauer**

### CODE REVIEW

**Comment by jason-simmons** [comment]
Has anyone tried the Skia tip of tree to see whether the GrTextureOp/drawImage performance issue is still happening?

(see https://github.com/flutter/flutter/issues/11721)

**Comment by goderbauer** [comment]
Looking at a few local runs of `flutter_gallery__transition_perf`, it looks like the problem has been fixed:

With Skia roll:
```
    "missed_transition_count": 0,
    "average_frame_build_time_millis": 4.855784469096672,
    "worst_frame_build_time_millis": 96.0,
    "missed_frame_build_budget_count": 98,
    "average_frame_rasterizer_time_millis": 12.751188589540412,
    "worst_frame_rasterizer_time_millis": 108.0,
    "missed_frame_rasterizer_budget_count": 505,
    "frame_count": 631,
```

Before:
```
    "missed_transition_count": 0,
    "average_frame_build_time_millis": 4.909233176838811,
    "worst_frame_build_time_millis": 96.0,
    "missed_frame_build_budget_count": 99,
    "average_frame_rasterizer_time_millis": 11.615987460815047,
    "worst_frame_rasterizer_time_millis": 102.0,
    "missed_frame_rasterizer_budget_count": 511,
    "frame_count": 639,
```

**Comment by Hixie** [comment]
We'll have to see the benchmark graphs but average_frame_rasterizer_time_millis is substantially slower in the numbers you just quoted.

**Comment by goderbauer** [comment]
@Hixie, the new data point is within the noise bounds of what I can currently see on the dashboard for that metrics. It's not 5x as claimed by the issue linked by Jason. That's what I mean by it appears like that issue is fixed.

But again, it's hard to tell from a single data point.

**Comment by jason-simmons** [comment]
We're currently using a version of Skia from almost a month ago and I'd prefer to get back in sync with the Skia tip of tree.

The original https://github.com/flutter/flutter/issues/11721 yielded 6-7x higher rasterizer times, so at least we aren't seeing that anymore.  I'd vote for landing this roll and working with the Skia team to improve any performance issues that arise.

**Comment by Hixie** [comment]
Oh I definitely wasn't saying we shouldn't land.

**Comment by goderbauer** [comment]
Happy to land if somebody LGTMs.

**Pull request merged**
