### PR TITLE
Roll CanvasKit to 0.16.2.

### PR DESCRIPTION
**Pull request by hterkelsen**
## Description

Rolls CanvasKit to 0.16.2. This includes a crash fix for memory intensive operations.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by hterkelsen** [comment]
Never mind, the app eventually crashed.

**Comment by hterkelsen** [comment]
Let's submit this anyways

**Comment by ferhatb** [comment]
@hterkelsen any regressions on 16.2 ?

**Comment by yjbanov** [comment]
@hterkelsen Can you please check that our benchmarks still complete without crashing? This happened in the past on one of the CK upgrades.

**Comment by hterkelsen** [comment]
Tested this change on the benchmarks and the gallery.

**Pull request merged**
