### PR TITLE
Allow `mac_android_aot_engine` swarming tasks to run on arm bots

### PR DESCRIPTION
**Pull request by jmagman**
Don't specify a cpu dimension on `mac_android_aot_engine` swarming tasks to let the scheduler figure out which bots to run based on capacity.

All swarming tests pass on arm Macs: https://ci.chromium.org/p/flutter/builders/try/Mac%20mac_android_aot_engine/7608

### CODE REVIEW

**Comment by jmagman** [comment]
> Is it possible to do a manual check that the same artifacts are generated regardless of the host platform arch?

Intel darwin-x64.zip artifacts
https://pantheon.corp.google.com/storage/browser/flutter_infra_release/flutter/experimental/a74da5d5651d79ca8a19ca21078ba63852374281/android-x64-release;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

from https://ci.chromium.org/p/flutter/builders/prod/Mac%20mac_android_aot_engine/2635 drone 


Intel darwin-x64.zip artifacts:
https://pantheon.corp.google.com/storage/browser/flutter_archives_v2/flutter_infra_release/flutter/experimental/f1b4e83769430f60cccf5238cebdb2eaaf0ade3c/android-x64-release;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

from https://ci.chromium.org/p/flutter/builders/try/Mac%20mac_android_aot_engine/7608 drone

**Comment by jmagman** [comment]
> Is it possible to do a manual check that the same artifacts are generated regardless of the host platform arch?

```
Binary files /Users/m/Downloads/flutter_experimental_00bef00f64a7d3ba58f5805becbb98df499bd29f_android-x64-release_darwin-x64/gen_snapshot and /Users/m/Downloads/flutter_infra_release_flutter_experimental_f1b4e83769430f60cccf5238cebdb2eaaf0ade3c_android-x64-release_darwin-x64/gen_snapshot differ
```
🤔

**Comment by zanderso** [comment]
I don't have a better suggestion than inspecting the compiler and linker flags and comparing them between the intel and arm64 builds. If you add `--verbose` to the `ninja` commands, the compilation and link commands should get printed to the build logs.

**Comment by jmagman** [comment]
Closing, this isn't the easy win I was expecting.  🙂 
Thanks for being fastidious @zanderso!

**Pull request closed without merging**
