### PR TITLE
Disable windows tests

### PR DESCRIPTION
**Pull request by dnfield**
They're failing on Cirrus at setup - see e.g. https://cirrus-ci.com/task/5072715013160960

@liyuqian @chinmaygarde

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Is this temporarily reverted till a fix is devised or is this gone because it was untenable?

**Comment by liyuqian** [comment]
Do we know why and when it started to fail?

**Comment by dnfield** [comment]
This is meant to be temporary.  We can remove it entirely if you prefer, I just don't want it blocking things landing while we triage.

@liyuqian it seems like an infra issue, Python isn't running.  I'm hoping you can look at it since you're familiar with the Windows setup there.  Alternatively, I'm working to get LUCI presubmits running so maybe we can just focus our energies on that....

**Comment by liyuqian** [comment]
From the log, it seems that the error is probably caused by an update of Chrome depot_tools, which becomes no longer compatible with the Windows VM setup we have. I'll wait for LUCI presubmit then since depot_tolls will be supported much better there.

**Pull request merged**
