### PR TITLE
Revert "Revert "[Fuchsia] Execute most of the testing/fuchsia/test_suites.yaml on debug and release builds""

### PR DESCRIPTION
**Pull request by zijiehe-google-com**
Reverts flutter/engine#50291, https://github.com/flutter/flutter/issues/142811

Following is the original change description.

This change implements a BundledTestRunner to run most of the tests in testing/fuchsia/test_suites.yaml as ExecutableTestRunner.

- Tests with packages out of out/fuchsia_*_x64/ are ignored for now.
- Tests with extra test command line parameters are ignored for now.

The BundledTestRunner can share most of the logic in ExecutableTestRunner and avoid reinventing the wheel.

This change also fixes the build break of fuchsia_tests in fuchsia_release_x64 which allows tests to run on the build as well.

- Tests not built with AOT are filtered out with variant field in test_suites.yaml.

Bug: https://github.com/flutter/flutter/issues/140179

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zijiehe-google-com** [comment]
The goma cache may slowly take effect, and I cannot reproduce the slowness caused by the linux_fuchsia release builder. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1933243/overview

@keyonghan Do you happen to have any suggestions of merging this change without blocking the tree?

**Comment by keyonghan** [comment]
> The goma cache may slowly take effect, and I cannot reproduce the slowness caused by the linux_fuchsia release builder. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1933243/overview
> 
> @keyonghan Do you happen to have any suggestions of merging this change without blocking the tree?

Yeah, seems some goma cache difference. The one you linked hit 100% local caches, whereas the 40min ones just hit a portion.

We can either moving the target to staging as: https://github.com/flutter/engine/pull/50288, or increase the timeout: https://github.com/flutter/engine/blob/main/.ci.yaml#L196

Assuming this is goma cache populating related, we can try increasing the timeout temporary. At the same, please create a bug to track to restore the timeout after validating goma cache works (targeting build time back to <30min). /cc @zanderso

**Comment by zanderso** [comment]
Let's not reland this on a Friday, please.

**Review by keyonghan — APPROVED** [review]
Temporary timeout increase LGTM.

**Comment by zijiehe-google-com** [comment]
Created https://github.com/flutter/flutter/issues/142932 and assigned to me.

**Comment by zijiehe-google-com** [comment]
If you have no more comments, I will submit this change after the latest try run.

**Comment by zijiehe-google-com** [comment]
The last try run is still showing a reasonable build cost under 5 minutes, https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1947624/overview. I will go ahead and merge this change.

**Comment by zanderso** [comment]
Reason for revert: Timing out on CI

**Pull request merged**
