### PR TITLE
[Impeller] compute path bounds once, use Skia computed bounds where possible.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Now that Paths are externally immutable, we can compute the bounds once at construction. This also allows the Skia conversions to set the already computed bounds.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The motivation for this is that bounds computation ended up being a fairly slow part of the aiks canvas patch, as we were computing the bounds of things multiple times. While this may not make a huge difference without that patch, I do think there are places where we may compute the bounds of a path more than once.

**Review by matanlurey — APPROVED** [review]
LGTM and  the comments were really helpful, thanks!

**Comment by jonahwilliams** [comment]
This shows a small improvement on the tessellation benchmarks:

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26test%3Ddynamic_path_tessellation_perf__timeline_summary&selected=commit%3D36676%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Ddynamic_path_tessellation_perf__timeline_summary%252C

**Comment by zanderso** [comment]
SkiaPerf also noted a measurable drop in CPU util: https://flutter-flutter-perf.skia.org/e/?begin=1693944748&end=1693976367&keys=X482a7810cfb443f67edcbab15e03f59b&num_commits=50&request_type=1&xbaroffset=36676

**Comment by matanlurey** [comment]
> SkiaPerf also noted a measurable drop in CPU util: https://flutter-flutter-perf.skia.org/e/?begin=1693944748&end=1693976367&keys=X482a7810cfb443f67edcbab15e03f59b&num_commits=50&request_type=1&xbaroffset=36676

giphy

**Pull request merged**
