### PR TITLE
[Android] Send connectionClosed message when keyboard becomes invisible to ensure framework focus state is correct.

### PR DESCRIPTION
**Pull request by ksballetba**
Fix:
- https://github.com/flutter/flutter/issues/123523

### Before this patch:

https://user-images.githubusercontent.com/30322203/228413196-29c57bb0-3220-495b-9e73-f58777de440f.mp4

### After this patch:

https://user-images.githubusercontent.com/30322203/228413249-fc06f49d-6579-4476-9788-90f12a53b8c3.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by reidbaker — COMMENTED** [review]
This looks reasonable to me but I would like and LGTM from someone who understands this code better. Possibly @LongCatIsLooong

**Comment by chinmaygarde** [comment]
Ping @LongCatIsLooong for +1/

**Comment by luckysmg** [comment]
Thx @chinmaygarde ^_^ . Adding label for merging. ^_^

**Comment by luckysmg** [comment]
Emm any plan to reland this? I think this is necessary. What changes we should make to reland this? 
@reidbaker  Do you have any advice?

**Comment by ksballetba** [comment]
image

set otherwise to `VisibleForTesting.PACKAGE_PRIVATE` for `VisibleForTesting` annotation could solve this problem.

**Comment by MeandNi** [comment]
I think this PR is unnecessary. Is there a situation where I want to keep the focus when the keyboard disappears? For example, when I pop up a custom emoji picker, I will put away the keyboard. At this time, I want the focus to remain on above the input box.

As for the situation described above, we can choose whether we need to retain focus by monitoring whether the keyboard is visible.

**Pull request merged**
