### PR TITLE
Call SkGraphics::Init on shell initialization.

### PR DESCRIPTION
**Pull request by chinmaygarde**
This ensures SkOpts are initialized before we start using Skia.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Are there two separate changes here?  Is there a perf bug this should be related to?

**Comment by chinmaygarde** [comment]
Using rowBytes makes no functional difference. @reed-at-google just pointed it out as a convenient accessor while we were investigating the profile.

**Comment by reed-at-google** [comment]
A bit more safe, since the pixmap is not required to have a tight rowbytes.
i.e. width*4 can be < actual rowbytes.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
