### PR TITLE
Reland "Split DisplayListBuilder into DlCanvas optimizer and DlOp recorder classes #44718"

### PR DESCRIPTION
**Pull request by flar**
Fixes: https://github.com/flutter/flutter/issues/133200

### CODE REVIEW

**Comment by flar** [comment]
The original was reverted due to rendering issues with some Flare assets. The problem was that a layer could decide that it was a "NOP" due to the paint it will use to blend in with the scene - but clip and transform methods could also become a NOP due to setting the transform or clip to empty/non-invertible. Both conditions can happen independently and so neither should override the other's conclusion, but that is exactly what the clip/transform methods were doing.

The fix is in the last commmit - only have clip/transform methods set the NOP flag to true when they cause a NOP condition. It can only become false on a restore that ends the NOP layer.

**Comment by flar** [comment]
Verified with internal testing that the project that discovered the bug is now working with this fix.

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Comment by flar** [comment]
Some benchmark improvements from relanding this work:

- [gradient static perf, 90% frame build times](https://flutter-flutter-perf.skia.org/e/?begin=1691693636&end=1693090952&keys=X4271a125d2c0d4ce3000fb7dce9fa102&requestType=0&selected=commit%3D36480%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_build_time_millis%252Ctest%253Dgradient_static_perf__e2e_summary%252C&xbaroffset=36480)
- [gradient static perf, average frame build times](https://flutter-flutter-perf.skia.org/e/?begin=1691536612&end=1693090952&keys=Xc7b1f0b182b072c5fa29cf7b0d8e6de5&requestType=0&selected=commit%3D36480%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_build_time_millis%252Ctest%253Dgradient_static_perf__e2e_summary%252C&xbaroffset=36439)

**Comment by chinmaygarde** [comment]
Awesome. I am assuming the preview dip was from the last attempt that got reverted?

**Comment by flar** [comment]
> Awesome. I am assuming the preview dip was from the last attempt that got reverted?

Yes, it does line up perfectly with those commits.

**Comment by flar** [comment]
My guess is that I removed some cases where I avoided an extra "pointer to shared_ptr" copy that was independent from the actual work being done in this PR. It could have been patched in independently.

(DlPaint has both `Foo* getFooPtr()` and `shared_ptr getFoo()` methods as well as set-by-pointer and set-by-shared equivalents. When you transfer a value from one paint to another using the Ptr versions you end up needing to create a copy rather than sharing the value. I found a couple of those in the builder code while I was implementing this change.)

**Pull request merged**
