### PR TITLE
Update to Dart revision de63e4fa94a1cebf86f0541ac14f25fd0bff73c0

### PR DESCRIPTION
**Pull request by jamesr**
This contains some fixes for Fuchsia and I'd like to keep the version
of Dart used in fuchsia and flutter builds consistent. Should have no
other impactful changes for Flutter.

### CODE REVIEW

**Comment by jamesr** [comment]
> You are most definitely going to have to update the licenses file though. 

How do I do that?

**Comment by chinmaygarde** [comment]
Instructions are here: https://github.com/flutter/engine/blob/e01d1b39efd5d83de53adeb6413a8dcfd2470dc7/tools/licenses/README. It is quite slow but @jason-simmons is working to make it faster.

**Comment by jamesr** [comment]
30 minutes of chugging later, let's see how this one goes

**Comment by jamesr** [comment]
OK never mind, time to regenerate :(

**Comment by jamesr** [comment]
Hmm, apparently the licenses golden file is platform-specific as well, since it contains the contents of the android NDK which is different on different host platforms:

 ====================================================================================================
 LIBRARY: ndk
-ORIGIN: ../../../third_party/android_tools/ndk/shader-tools/linux-x86_64/NOTICE
+ORIGIN: ../../../third_party/android_tools/ndk/shader-tools/darwin-x86_64/NOTICE
 TYPE: LicenseType.apache


... so time to regenerate from a linux box.

**Comment by jamesr** [comment]
After rebasing on linux I'm unable to regenerate the licenses.golden file:

$ time dart --checked lib/main.dart ../../.. > ../../travis/licenses.golden
Finding files...
Collecting licenses...
     31569 of 31570 ██████████ 100% (0 missing licenses)  ../../../third_party/zlib/zutil.h    error searching for copyright in: ../../../tagsson    
'file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart': Failed assertion: line 2161 pos 12: 'false' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:24)
#1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:31)
#2      RepositoryRoot.libraryName (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:2161:12)
#3      RepositoryFile.libraryName (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:39:36)
#4      RepositorySourceFile.licenses.<anonymous closure> (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:100:74)
#5      List.forEach (dart:core-patch/growable_array.dart:258)
#6      RepositorySourceFile.licenses (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:100:15)
#7      RepositoryDirectory.getLicenses (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:1210:41)
#8      main (file:///ssd/flutter_engine/src/flutter/tools/licenses/lib/main.dart:2251:57)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)



     31570 of 31570 ██████████ 100% (1 missing licenses)  Done.    
real    21m19.878s
user    23m16.602s
sys     0m16.881s

Note the time there - 21 minutes :(

The zlib header I have matches https://github.com/flutter/buildroot/blob/master/third_party/zlib/zutil.h

/cc @jason-simmons @Hixie

**Comment by jamesr** [comment]
Ah, maybe it failed because I have a ctags file locally.  Will remove and try again and find out in 20 minutes if that was it.  This is a highly frustrating process.

**Comment by abarth** [comment]
> This is a highly frustrating process.

Yes.

Hopefully this patch will make it 33x faster:

https://github.com/flutter/engine/pull/3437

/cc @Hixie

**Comment by jamesr** [comment]
#3437 won't help at all for this, or future Dart rolls, since this changes things outside the flutter/ tree.

**Comment by jamesr** [comment]
Travis says we aren't going to space today:

 Total license count: 695
-     31569 of 31569 ██████████ 100% (0 missing licenses)  Done.    
+     31567 of 31567 ██████████ 100% (0 missing licenses)  Done.

**Comment by jamesr** [comment]
Ah, it found some .pyc files in my tree.  Time to go again..

**Comment by abarth** [comment]
> since this changes things outside the flutter/ tree

It should still skip analyzing third_party, right?  I presume that's where most of the time goes.  But yes.  This area is painful currently.

**Comment by jamesr** [comment]
```
Done.    License script got different results than expected.
Please rerun the licenses script locally to verify that it is
correctly catching any new licenses for anything you may have
changed, and then update this file:
  flutter/sky/packages/sky_engine/LICENSE
For more information, see the script in:
  https://github.com/flutter/engine/tree/master/tools/licenses
--- flutter/travis/licenses.golden	2017-02-25 00:02:26.731273425 +0000
+++ out/license-script-output	2017-02-25 00:28:17.107273425 +0000
@@ -72132,7 +72132,7 @@
    appreciated but is not required.
 2. Altered source versions must be plainly marked as such, and must not be
    misrepresented as being the original software.
 3. This notice may not be removed or altered from any source distribution.
 ====================================================================================================
 Total license count: 695
-     31567 of 31567 ██████████ 100% (0 missing licenses)  Done.
+     31567 of 31567 ██████████ 100% (0 missing licenses)  Done.    
```
Well then...

**Pull request merged**
