### PR TITLE
Vulkan transition images

### PR DESCRIPTION
**Pull request by cdotstout**

### CODE REVIEW

**Comment by Hixie** [comment]
@cdotstout @chinmaygarde Can this be landed?

**Comment by cdotstout** [comment]
Looks like I've got some formatting problems.  Attempting to resolve.

**Comment by cdotstout** [comment]
I don't have much experience making flutter changes, but the format complaint coming from Travis looks bogus to me.

I made sure that 'git clang-format' had already been run on these changes, as per CONTRIBUTING.md.

So I think these 2 changes are fine.

Potential caveat: I have tested these changes only on fuchsia.

**Comment by cdotstout** [comment]
@Hixie or @chinmaygarde can you comment on the Travis format issue?

**Comment by Hixie** [comment]
Please don't land on red; doing so will allow errors to creep in (two errors in this case, one with formatting and one with licensing).

**Pull request merged**
