### PR TITLE
Guard unobstructed platform views by a build and embedding flag

### PR DESCRIPTION
**Pull request by blasten**
Issue: https://github.com/flutter/flutter/issues/53841

This PR allows to disable unobstructed platform views per plugin. For example:

```objc
[registrar registerViewFactory:factory
                              withId:@"<platform-view-id>"
                       compositeMode:FlutterPlatformViewCompositeModeObstructed];
```

The default behavior is:
```objc
[registrar registerViewFactory:factory
                              withId:@"<platform-view-id>"
                       compositeMode:FlutterPlatformViewCompositeModeUnobstructed];
```

### CODE REVIEW

**Comment by blasten** [comment]
@chinmaygarde sounds good. I makes more sense to control this behavior per plugin.

**Comment by blasten** [comment]
@amirh PTAL

**Comment by chinmaygarde** [comment]
My objection to the flag initially in the engine was not so that we could add similar flags elsewhere. I am trying to understand the use-case for these flags. This use-case has not been documented in either go/flutter-hybrid-composition or [the linked issue](https://github.com/flutter/flutter/issues/53841). For example, why the plugin would ever have to opt for obstructed platform views when the unobstructed platform views support covers a superset of the functionality of the former. Exposing additional modality over a public API means we have to support it going forward. For reference, anything in ios/framework/headers is part of the public API that we cannot freely change moving forward unless we risk breaking plugins.

**Comment by blasten** [comment]
@chinmaygarde Amir raised a concern recently. Amir mentioned that unobstructed platform views was a significant change in behavior, and that in the past they added a flag to `FlutterPlugin.h`.  e.g. `FlutterPlatformViewGestureRecognizersBlockingPolicy`. 

If agreed, we could keep this API undocumented, and remove it in preparation for the next stable release.

@amirh do you want to add something?

**Comment by amirh** [comment]
@chinmaygarde Essentially I'm hesitant to change the way we composite platform views by deploying the recent changes to stable (that had very little soak time) with no quick way to change our decision once it's out other than waiting for another stable release.

I want to have some *temporary* kill switch that will allow us to deploy new plugin versions that will use the previous composition mechanism if we figure out something went wrong. I think this kill switch should be introduced as a parameter (probably a deprecated one) that plugins can set. After we get some soak time and see that things are working well we can remove that switch.

Or alternatively if we make the maximal number of overlays per platform view before we go with a fullscreen overlay configurable, that could be our kill switch (if we discover issues we can set the max to 0 in plugin code).

**Comment by chinmaygarde** [comment]
Ok, Some followup questions:

* What are we doing to ensure this is temporary?
* If this is temporary, who is gong to remove this flag and when?
* If plugins start using this temporary flag, who is on the hook for modifying the same when the temporary flag goes away?

I am all for doing whats necessary to ship something in a timely manner as long as we have a clear plan of action to deal with the tech debt incurred along the way. Also, I would appreciate the need for stuff like this to be mentioned in the design docs or linked issues. This feels really unexpected at this stage and I feel our hand is being forced into making some poor long term decisions.

**Comment by blasten** [comment]
@chinmaygarde 
> What are we doing to ensure this is temporary?
> If this is temporary, who is gong to remove this flag and when?

If this is agreed, I can file an issue and add a TODO.

> Also, I would appreciate the need for stuff like this to be mentioned in the design docs or linked issues. 

Agreed

> If plugins start using this temporary flag, who is on the hook for modifying the same when the temporary flag goes away?

As of now, I'm thinking of the 1P plugins (webview, maps, ads). In this case, I can own the item.

**Comment by chinmaygarde** [comment]
Hmm, I was in a dilemma about patches of this nature (the "not sure this is stable enough and may need more soak time" type patches that are temporary and need to backed out later) and reading go/flutter-backwards-compatibility and go/breaking-packages for inspiration. If anything, this highlighted that we need a policy for the Flutter Engine and its various API surfaces for how we manage API churn. I am writing one now and will send it our for review later this week. In the meantime, the most relevant guidance I could find was in the common mitigations section of the API docs which mentioned "Careful API design" and the susceptibility of APIs for breakage as we move forward (this reading is tenuous at best as the section does not deal with experimental flags at all). On the basis of this, I am inclined to recommend that we **_don't_** land this patch as this API will almost assuredly break in the near future.

@blasten I apologize for getting it the way of landing this work. Unfortunately, the tight schedule and the uncertainty of stability of the feature has led to us doing a few more things by the seat of our pants than I would usually be comfortable with.

**Comment by amirh** [comment]
@chinmaygarde I agree with your points, and I would want us to land such a safeguard mechanism in a forward-compatible way. Allowing to control the max number of overlays is probably useful regardless (e.g for performance optimizations with views that don't care of being obstructed) and would have been the forward-compatible kill-switch.

I had thought that it will be simple to add a kill switch, but if it turns out to not be I'm fine with relying on a hotfix as our kill mechanism. It may take a little longer to land but I assume it won't be very significant.

**Pull request closed without merging**
