### PR TITLE
Fix sample video frame rate and reenable ExternalTextureTests

### PR DESCRIPTION
**Pull request by ds84182**
FFMPEG selects a default video frame rate of 25fps when encoding a static image as a video. Since the video is 1 second long, we want a frame rate of 1fps so there is only a single frame encoded for the entire video.

Verified using `ffprobe` that the file contains a single frame now.

Closes flutter/flutter#106673

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/34479

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/34479

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 6.
View them at https://flutter-engine-gold.skia.org/cl/github/34479

**Comment by chinmaygarde** [comment]
cc @dnfield

**Comment by dnfield** [comment]
Looks like the test is not completing...

**Comment by ds84182** [comment]
There's a race condition where the wrong scenario is displayed sometimes. Haven't dug deeper into it, but `animated_color_square` is incorrect and it never completes because it's the wrong scenario. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8809266353870242305/+/u/Android_Unit_Tests/stdout#L21359_0

**Comment by ds84182** [comment]
Nevermind about the race condition above, I realized the specific test that's failing isn't the scenario app integration test.

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 7.
View them at https://flutter-engine-gold.skia.org/cl/github/34479

**Review by jason-simmons — APPROVED** [review]

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
Thank you!

**Pull request merged**
