### PR TITLE
[Impeller] Round out subpass coverage.

### PR DESCRIPTION
**Pull request by bdero**
Resolves https://github.com/flutter/flutter/issues/146967

I added a detailed comment inline explaining why we need this. The visual issues in the reported issue were due to nearest sampling while straddling a half pixel offset.

Before:
image

After:
image

### CODE REVIEW

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/145180

The round out caused https://github.com/flutter/flutter/issues/144213 . But maybe we should have fixed that bug elsewhere?

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by bdero** [comment]
Hmm, there is a slightly different way I could fix this that wouldn't make that issue worse. Trying it out now.

**Comment by bdero** [comment]
Pushed the change. We can just round the texture position instead of modifying the coverage. This will keep the texture edges the same and avoid resurfacing https://github.com/flutter/flutter/issues/144213.

**Comment by bdero** [comment]
Golden changes are looking as expected.

**Pull request merged**
