### PR TITLE
fix Memory leak when using PlatformView [IOS] #24714

### PR DESCRIPTION
**Pull request by ashawn**
This is my investigation, thanks!
https://juejin.im/post/5c6e6dd5f265da2dcf62821f

### CODE REVIEW

**Comment by ashawn** [comment]
I signed it!

**Comment by amirh** [comment]
Thanks!

**Comment by amirh** [comment]
cc @chinmaygarde

**Comment by amirh** [comment]
Will land on green

**Comment by chinmaygarde** [comment]
Good catch. Thanks. I wonder if we should provide a custom GL proc resolver with instrumented variants of the OpenGL methods where we can do sanity checks like this. There may be more instances of such leaks. CC @jason-simmons

**Comment by xujunquan** [comment]
@chinmaygarde it is a big problem to me ,can you give me some help

**Comment by xujunquan** [comment]
[https://github.com/flutter/flutter/issues/37225](url)

**Pull request merged**
