### PR TITLE
Do not warn if a requested asset does not exist

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/2229

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
why? doesn't this make it harder for us to notice when we have forgotten assets in the manifest?

**Comment by jason-simmons** [comment]
Some assets (such as the font manifest) are optional

**Comment by abarth** [comment]
We should handle that at in the framework where the issue is clearer.  Consider the case when you have a network bundle and you get a 404 from the server.  We'd want the framework to do something sensible in that case too.

**Comment by Hixie** [comment]
fair enough.

**Comment by HansMuller** [comment]
Right now warnings like:
```
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'action/ic_visibility_black_24dp.png' does not exist.
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'content/ic_link_black_24dp.png' does not exist.
```
Are really useful. Can we not delete this warning until we have some other way to tell the developer that the icon they want isn't available?

**Comment by abarth** [comment]
The trouble is this warning is triggered on the default out-of-the-box app from `flutter create`, which doesn't use custom fonts.

I can add an error handler to AssetImage that gives a more sensible message.

**Pull request merged**
