### PR TITLE
Revert "Lazily allocate RasterCacheItems only when caching is enabled"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#45211

b/298583505

### CODE REVIEW

**Comment by zanderso** [comment]
Prospective revert. Not sure this is right. Need input from @jason-simmons and/or @flar

**Comment by jason-simmons** [comment]
Confirmed that the b/298583505 issue does not occur if https://github.com/flutter/engine/pull/45211 is reverted in a local engine build.

**Review by jason-simmons — APPROVED** [review]

**Comment by flar** [comment]
I confirmed that it does reproduce in a local engine build on the commit *JUST PRIOR* to that PR commit...?

**Review by flar — CHANGES_REQUESTED** [review]
My attempts to reproduce the problem indicated that this change was not suspect.

**Review by flar — APPROVED** [review]
It looks like my reproducing attempts weren't correct so I'm going to defer to Jason on this one.

**Pull request merged**
