### PR TITLE
Sync analyzer_options.yaml

### PR DESCRIPTION
**Pull request by goderbauer**

### CODE REVIEW

**Comment by zanderso** [comment]
I guess if the tests pass then things are okay, but removing some of those `await`s looks like it could change behavior.

**Comment by goderbauer** [comment]
@zanderso I believe removing those awaits shouldn't change anything. It is is only removing awaits from Futures that are directly returned from methods. Either those methods are awaited on the other side (which means the Future is still awaited) or they are not awaited there and in that case the await within the method shouldn't make a difference. All tests (except for the unrelated failure tracked in https://github.com/flutter/flutter/issues/78804) seem to be passing.

**Review by zanderso — APPROVED** [review]

**Comment by GaryQian** [comment]
Does this fix the analyzer_options failure seen in https://github.com/flutter/flutter/pull/78900/checks?check_run_id=2182989685

**Comment by GaryQian** [comment]
Also, https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851920400027736576/+/steps/run_test.dart_for_web_tests_shard_and_subshard_0/0/stdout began failing after this PR, unclear if it is responsible at a glance.

**Pull request merged**
