### PR TITLE
[infra] Support archiving the built Dart SDK in the non-prebuilt case

### PR DESCRIPTION
**Pull request by whesse**
The BUILD.gn files include support for creating a zip archive of the Dart SDK for an engine build
in the case that a prebuilt Dart SDK has been downloaded.

Extend this support for archiving the Dart SDK to the case where it is built from source during an engine build.
This is needed to support automated build and test of tip-of-tree and pre-submit builds of the engine and Dart.

Bug: https://github.com/flutter/flutter/issues/106494

### CODE REVIEW

**Comment by whesse** [comment]
This is not working, because no gn target I can find is listing $root_out_dir/dart-sdk as an output.
The zip target template requires its inputs to be the output of some target that it depends on directly or indirectly.

No target in Dart's sdk build rules lists the directory as an output, only the individual files that are created.  So a major addition to the build rules would be needed to make a target whose output was the entire directory.

I would suggest removing the approval of this PR until it can be fixed.

**Comment by whesse** [comment]
Closing the PR. Either more extensive changes need to be made, or the archive creation must be moved out of the build process.

**Comment by whesse** [comment]
I was able to fix this PR by switching from the zip_bundle template to the zip_bundle_from_file template.
Because that template has no inputs, the target may run unconditionally when it is requested, but that seems correct in this case.

**Comment by XilaiZhang** [comment]
Thanks for the info Casey! I can add entitlement config for this block.

**Comment by whesse** [comment]
Do you want to add it in this PR, or should I land it?

**Pull request closed without merging**
