### PR TITLE
[Impeller] Use fast path for CPU generated textures where possible

### PR DESCRIPTION
**Pull request by dnfield**
Offers a slight improvement on glyph atlas rendering by making the texture upload basically free. Shows improvements locally on our text based benchmarks.

### CODE REVIEW

**Comment by dnfield** [comment]
@jonahwilliams this might be useful for the Gradient textures as well, although those are tiny.

**Comment by jonahwilliams** [comment]
They can end up quite big sometimes, if the stops are close together.

**Comment by jonahwilliams** [comment]
Cheap!

tim-eric-discount

**Comment by dnfield** [comment]
This needs some work around how the row bytes are handled. Metal expects them to be aligned to a particular value.

**Comment by dnfield** [comment]
The tests are passing locally on an M1 mac, going to see if I can try them on an x64...

**Comment by dnfield** [comment]
Testing that the pixmap dimensions match the texture mipmap size doesn't work across platforms anymore, because we might be allocating rowbytes beyond what the texture dimensions actually are because the platform needs us to do that to keep the alignment requirements for MTLBuffer/MTLTexture working.

**Comment by dnfield** [comment]
(The check happened to work out fine on arm64 environments but not x64).

**Comment by dnfield** [comment]
I've refactored this to update the DeviceBuffer API to make the allocation make more sense.

The `AsTexture` method will now do a texture upload on Vulkan and GLES, but metal has a faster path this way.

GLES could use https://registry.khronos.org/OpenGL/extensions/ARB/ARB_pixel_buffer_object.txt to improve things here, but I'm not sure if we want to pursue that. Vulkan should have something better but that can wait for a subsequent patch.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
I had thought of a variant of the AsTexture interface but eventually gave up because it couldn't be implemented across all APIs. The workaround you mention where a texture upload is performed in OpenGL leaves you susepctible to change to the host buffer you make after calling the AsTexture method not actually updating the texture in OpenGL as they would with Metal. I am nervous of having APIs not behaving consistently across all backends. Perhaps AsTexture should just fail on OpenGL and the caller then has to figure out to do the copy. We can have a wrapper method that makes this convenient of course.

**Comment by dnfield** [comment]
> I had thought of a variant of the AsTexture interface but eventually gave up because it couldn't be implemented across all APIs. The workaround you mention where a texture upload is performed in OpenGL leaves you susepctible to change to the host buffer you make after calling the AsTexture method not actually updating the texture in OpenGL as they would with Metal. I am nervous of having APIs not behaving consistently across all backends. Perhaps AsTexture should just fail on OpenGL and the caller then has to figure out to do the copy. We can have a wrapper method that makes this convenient of course.

Maybe something on the context about whether this is supported or not, like offscreen MSAA?

There are pixel buffer object extensions for GL as well but it's not clear to me how available they are (although anything on EGL 3 would have them).

**Comment by dnfield** [comment]
That benchmark is unfortunately noisy - locally I had some runs look better and others not. But looking at a different app that just repeatedly pumped that frame, the frame times seemed better on average.

**Pull request merged**
