### PR TITLE
Fix color swapping on Fuchsia

### PR DESCRIPTION
**Pull request by abarth**
Previously we were swapping the wrong color channels. This change makes it
correct.

### CODE REVIEW

**Comment by abarth** [comment]
@mikejurka @chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm. Is there really no ARGB SkColorType?

**Comment by abarth** [comment]
https://cs.chromium.org/chromium/src/third_party/skia/include/core/SkImageInfo.h?l=73

Apparently there used to be judging from some sample code that still exists in the Skia repo that I don't believe compiles.

**Comment by mikejurka** [comment]
i was incrementing by 5 bytes... that's embarrassing.

Thanks for testing it out. Forgot that endianness matters here too.

**Comment by abarth** [comment]
> i was incrementing by 5 bytes

You were also always operating on the first pixel.

**Comment by mikejurka** [comment]
jeez yeah. no more submitting code late-night.

**Pull request merged**
