### PR TITLE
Use track-widget-creation transformer included in the sdk.

### PR DESCRIPTION
**Pull request by jacob314**
This improves performance as the version in the SDK is able to work more
incrementally and avoids creating an expensive ClassHierarchy.
There is now no measureable performance difference with the option so the
kernel transformer can be enabled by default.

Test output results:
`flutter test`
04:06 +4043 ~86:

`flutter test --track-widget-creation`
04:06 +4051 ~78:

### CODE REVIEW

**Comment by jacob314** [comment]
This CL depends on https://dart-review.googlesource.com/c/sdk/+/102920

**Comment by jacob314** [comment]
This CL won't pass until the matching dart-sdk change has landed first.

**Comment by terrylucas** [comment]
Ben did a Flutter build and Dart Roll, the Dart includes:
- Jacob's [CL](https://dart-review.googlesource.com/c/sdk/+/102920)
- Slava's [CL](https://dart-review.googlesource.com/c/sdk/+/103135) to make Flutter-hhh bot green.

When this roll works I'll sync to TIP of flutter this CL if it works I'll commit.

**Comment by dgrove** [comment]
@terrylucas any updates here?

**Comment by terrylucas** [comment]
Finally, 1.6.3 of Flutter has the dart-sdk track-widget-creation checkin.  Was able to apply this CL, successfully compile, Flutter run launches with --track-widget-creation (by default) and DevTools inspector works.

Awaiting Travis test passes and will apply CL (minor change DEPS reverted, Dart-sdk SHA has updated).

**Comment by terrylucas** [comment]
I have committed this CL (see https://github.com/flutter/engine/pull/9085) patched in Jacob's original with a few minor changes DEPS (used tip dart-sdk SHA) and a merge conflict in  frontend_server/lib/server.dart

**Pull request closed without merging**
