### PR TITLE
Reland "[ci.yaml] Remove default properties"

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/engine#30100

Opening to see if the failures are being detected now

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@godofredoc as FYI this PR is now blocked due to what looks like the same issue. I'm not sure why it wasn't blocked last week (possibly it has a clean bot)

**Comment by chinmaygarde** [comment]
Is progress being made on this patch? Can we re-land this?

**Comment by CaseyHillers** [comment]
> Is progress being made on this patch? Can we re-land this?

No, we want this to be tested with `clobber: true` every first to make sure it's not reusing previous artifacts.

**Comment by CaseyHillers** [comment]
Abandoning this as it would be better to wait for the engine v2 recipes where we have a way to validate the artifacts being built.

**Pull request closed without merging**
