### PR TITLE
[Impeller] Apply color filters on the CPU for solid colors & gradients.

### PR DESCRIPTION
**Pull request by bdero**
Apply color filters on the CPU for solid colors and gradients. This fixes https://github.com/flutter/flutter/issues/127232 for the purely color-based color sources.

We still need to make the other special color blending paths respect the geometry mask in order to fully resolve the underlying issue:
* SaveLayers (if they have an interesting matrix filter -- without a matrix filter, it'll always work today)
* TiledTextureContents
* TextContents
* VerticesContents
* AtlasContents

### CODE REVIEW

**Comment by bdero** [comment]
Let's see those goldens.

**Comment by bdero** [comment]
Those goldens are looking mighty fine.

**Review by jonahwilliams — COMMENTED** [review]
How does this work with decal gradients + color blending that changes transparent black?

**Comment by jonahwilliams** [comment]
I'm not really sure what the correct result should be in this case, but I think If you apply a color filter to a decal texture you can observe the transparent black pixels getting changed, where a CPU blend afterwards might not do that?

**Comment by bdero** [comment]
> I'm not really sure what the correct result should be in this case, but I think If you apply a color filter to a decal texture you can observe the transparent black pixels getting changed, where a CPU blend afterwards might not do that?

Not sure if I'm fully answering your question, but:

Today, when applying a color blend to the color source, pixels that lie outside the geometry can be affected, which is incorrect behavior. This patch fixes that behavior for solid colors and gradients.

Fixing it for the other drawing ops will require more expensive tricks. For example, tracking the geometry mask as a separate texture and compositing post-blend, or drawing the geometry outline to a stencil and then using it inside the GPU blend filter.

**Comment by jonahwilliams** [comment]
Here is an example of what I'm talking about: https://dartpad.dev/?id=80d0af639ec8952a3e31bac084fb202b

With decal and certain gradient parameters you can inset the color source in the geometry, and in that case you'd need to handle blending being done with transparent black pixels

**Comment by bdero** [comment]
Ah yeah, that needs to be fixed. I'll fix it by throwing the blended border color in the shader uniforms. It makes sense to allow the border color to be set in our emulated decal anyhow. [Metal allows this](https://developer.apple.com/documentation/metal/mtlsamplerdescriptor/2092299-bordercolor), for example.

**Comment by bdero** [comment]
Great catch, btw. :)

**Comment by bdero** [comment]
Alrighty, added `CanRenderLinearGradientDecalWithColorFilter` to demonstrate that this is handled now.

Before:

Screenshot 2023-07-10 at 6 38 35 PM

After:

Screenshot 2023-07-10 at 6 35 14 PM

**Comment by bdero** [comment]
Goldens are good.

**Review by jonahwilliams — APPROVED** [review]
LGTM

At some point we'll need to reckon with how complex we've made gradients...

**Pull request merged**
