### PR TITLE
Make license-checker ignore Vim swap files.

### PR DESCRIPTION
**Pull request by ErikCorryGoogle**
Vim swap files typically end with .swp or .swo. They
must be ignored without being read because they contain
broken UTF-8 and cause an exception to be thrown
just from being read in.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Ping @Hixie

**Comment by Hixie** [comment]
For the swap files, you just want to add the relevant extensions to:
https://github.com/flutter/engine/blob/master/tools/licenses/lib/filesystem.dart#L110

**Comment by Hixie** [comment]
@ErikCorryGoogle Are you still working on this patch?

**Comment by Hixie** [comment]
Closing for now, please feel free to reopen when ready! :-)

**Pull request closed without merging**
