### PR TITLE
Copy the flutter_gpu package into the engine artifacts.

### PR DESCRIPTION
**Pull request by bdero**
Part of https://github.com/flutter/flutter/issues/131711.

### CODE REVIEW

**Comment by zanderso** [comment]
@christopherfujino Will adding new artifacts here confuse any tests in the framework repo? The code signing tests?

**Comment by christopherfujino** [comment]
> @christopherfujino Will adding new artifacts here confuse any tests in the framework repo? The code signing tests?

Yeah, if this is a binary then I think we need to add a rule to codesign it, I think here: https://github.com/flutter/flutter/wiki/code-signing-metadata#add--update-code-signing-metadata

If these are already codesigned, then this should be fine.

**Comment by bdero** [comment]
This is purely a Dart package and doesn't contain any native binaries. So I think we're good?

**Review by chinmaygarde — APPROVED** [review]

**Comment by bdero** [comment]
Gonna give this a land and see how it shakes out in the roll.

**Pull request merged**
