### PR TITLE
Roll expat and buildroot

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/91384

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by chinmaygarde** [comment]
The licenses need to be updated.

**Comment by Hixie** [comment]
@jason-simmons looks like this PR updates the goldens but doesn't actually update the LICENSES file itself, which is the important part :-)

**Comment by jason-simmons** [comment]
The `sky/packages/sky_engine/LICENSE` file has been updated by an automated dependency roll (https://github.com/flutter/engine/commit/4867ae0249b63acadd33d0953c1ef89dd9b20d7d)

**Comment by Hixie** [comment]
Cool, awesome.

**Pull request merged**
