### PR TITLE
[WIP] Exposing matrix convolution as image filter.

### PR DESCRIPTION
**Pull request by panmari**
There's still a few things missing, I'd love to get some input on
* What type of tests to create (and where)
* How to best passing down kernel width and height (just append to data? Or introduce new members to `_ImageFilter`?)
* Should the first version expose all parameters available in SkImageFilters::MatrixConvolution? If yes, how do I best wrap all of these types?

## Description

Exposing MatrixConvolution as Image filter, still a work in progress.

## Related Issues

https://github.com/flutter/flutter/issues/37919

## Tests

I added the following tests:

Unsure what tests would make sense here, 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Comment by panmari** [comment]
Hi @chinmaygarde, do you have some pointers for the questions in my initial post? I tried looking for other examples in the code, but couldn't find an exact equivalent.

**Comment by deakjahn** [comment]
@panmari Did you leave this? It would be very nice to have this. It's been a pet peeve of mine for several years now that Skia, even before the time of Flutter, actually, removed many interesting things that the devs, back then, considered unused and they simply didn't want to support any more. I tried to argue (even on the Skia mailing list) but had no success. Those never appeared in Flutter, either, of course.

The convolution filter was just one of those, another interesting items were 1D and 3D tables (the first to be used with arbitrary gamma and curves operations, the second with LUT conversion).

**Comment by panmari** [comment]
I never found the time to come back to this, but I'm still interested to have this available in flutter :)

**Comment by deakjahn** [comment]
Apart from the tests, did it actually work for you?

**Comment by panmari** [comment]
I think I got it working in an example app, but it's been a long time. The
implementation also had some other awkward spots left, e.g. that I
hardcoded the size of the filter.

Am Mi., 11. Aug. 2021 um 09:55 Uhr schrieb Gábor ***@***.***>:

**Comment by deakjahn** [comment]
Well, then, it should be started again with a current copy of the engine...

**Comment by MrBirb** [comment]
@panmari If you won’t be working on this again, I suggest we just close this PR.

**Comment by deakjahn** [comment]
@MrBirb I would consider it very unfortunate. This is something badly needed and the PR should have been accepted while there was any chance of success. It's small wonder that if contributions are left to bit rot, they rot. :-))

**Comment by Hixie** [comment]
I'm going to close this PR since it can't be merged in its current state (since it lacks tests), but if anyone is interested in working with us on this, please don't hesitate to take this PR and run with it. You can find us on the Discord (see contributing guidelines doc for the link) if you would like advice on writing tests and such.

**Pull request closed without merging**
