### PR TITLE
[Impeller] Use triangle strips to dedupe rectangle vertices.

### PR DESCRIPTION
**Pull request by bdero**
Remove a couple of duplicate verts in a bunch of situations.

Pedantic improvements: "Brandon, why are you like this" edition.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
So if you change these from triangle, the default constructed PSO won't match anymore for these. Though if we're going to unconditionally use triangle strip, you could probably change the initialization code to specify that geometry instead?

**Comment by bdero** [comment]
> Though if we're going to unconditionally use triangle strip, you could probably change the initialization code to specify that geometry instead?

Done.

I also got the ordering wrong on some of these. Let's see those new goldens.

**Review by jonahwilliams — COMMENTED** [review]
You will probably need to update default_options L832 content_context.h

**Comment by bdero** [comment]
I'm working on a solution for tracking different prototype defaults for different pipeline sets here: https://github.com/flutter/engine/pull/46751

**Comment by bdero** [comment]
This should be good now. This is using the new solution for differing defaults and the goldens are looking good. :)

**Comment by bdero** [comment]
The previous solution I tried to employ in this patch didn't work as intended because of the mismatching default lookup in content_context.h routines.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
