### PR TITLE
Remove single window/view assumption from `SceneBuilder`

### PR DESCRIPTION
**Pull request by a-wallen**
fixes https://github.com/flutter/flutter/issues/112202

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
Even though the Scene needs a physical size and dpr, it can actually be given these values directly instead of taking them from the window. See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L1428-L1505

It would be odd the make these cases require supplying a dummy window. 

Instead I would consider deferring the lookup of physical size/dpr until the scene is rendered instead of doing it eagerly and then throwing this information away in some cases

**Comment by a-wallen** [comment]
> Instead I would consider deferring the lookup of physical size/dpr until the scene is rendered instead of doing it eagerly and then throwing this information away in some cases

@jonahwilliams if the scene is given different values than those in the view it's being rendered into should those values be overridden?

**Comment by jonahwilliams** [comment]
conceptually Scenes don't have these metrics, they take them from either the arguments to toImage or from the window they are rendered into. Its sort of an implementation detail that constructing a scene eagerly looks up the viewport metrics but this could be done later

**Comment by jonahwilliams** [comment]
None of the methods that reference the viewport metrics are called until the scene is moved to the raster thread.

**Comment by Hixie** [comment]
I'm going to close this because @dkwingsmt has an alternative approach he's chasing down.

**Pull request closed without merging**
