### PR TITLE
[ci.yaml] Explicitly define open jdk dependency

### PR DESCRIPTION
**Pull request by CaseyHillers**
https://github.com/flutter/flutter/issues/86892

After this lands, it can populate the LUCI configs with the current expected info. Afterwards, we can look at upgrading to JDK 11.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by blasten** [comment]
@CaseyHillers thanks. I was adding`api.flutter_deps.required_deps(env, env_prefixes, deps) to `engine.py`. That is required for this to work, right?

**Comment by CaseyHillers** [comment]
> @CaseyHillers thanks. I was addingapi.flutter_deps.required_deps(env, env_prefixes, deps) to engine.py`. That is required for this to work, right?

Correct. To get the deps resolving, we need to update the LUCI configs and the recipes to include the dependencies.

We're in the middle of transitioning the luci configs to be based on .ci.yaml (go/flutter-automatic-builders), so we add the luci config change here.

**Comment by blasten** [comment]
cool. I updated: https://flutter-review.googlesource.com/c/recipes/+/16122

**Review by blasten — APPROVED** [review]

**Review by dnfield — APPROVED** [review]
Consider adding a comment explaining where to find these

**Pull request merged**
