### PR TITLE
Migrate Fuchsia runners to SDK tracing API

### PR DESCRIPTION
**Pull request by cbracken**
Migrates the Fuchsia Flutter and Dart runners off the internal tracing
APIs and onto the public SDK.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Does this work in the Fuchsia tree? Because we are still rolling into the same during the transition.

**Comment by cbracken** [comment]
I'm actually just testing that as we speak :)

**Comment by cbracken** [comment]
Needed one tweak to fml/BUILD.gn. Fixed now.

**Comment by cbracken** [comment]
Partial fix to [FL-250](https://github.com/flutter/flutter/issues/33991).

**Pull request merged**
