### PR TITLE
Reland: Migration to PlatformDispatcher and multi-window

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This re-lands https://github.com/flutter/engine/pull/20496 and https://github.com/flutter/engine/pull/21780 after fixing the semantics-enabling code that was causing the post-submit `web_smoke_test` to fail.

Below is the description from the original PR:

This is a PR for converting the `dart:ui` code in the engine to use a multi-window API. The goal here is to convert from the window singleton to an API that has the concept of multiple windows. Also, I'm matching up the new `PlatformDispatcher` class to talk directly to the `PlatformConfiguration` class in the engine. I'm not attempting to actually enable creating multiple windows here, just migrate to an API that has a concept of multiple windows. The multi-window API in this PR currently only ever creates one window.

The design doc for this change is [here](https://flutter.dev/go/desktop-multi-window-support).

The major changes in this PR:
 - Move the platfom-specific attributes out of `Window`, and into the new `PlatformDispatcher` class that holds all of the platform state, so that the platform code need only update the configuration on this class.
 - Create `FlutterView`, `FlutterWindow`, and `SingletonFlutterWindow` classes to separate out the concepts of a view (of which there may be multiple in a window), a window (of which there may be multiple on a screen, and they host views), and a window where there is only ever expected to be one (this hosts the entire API of the former `Window` class, and will eventually be the type of the `window` singleton).

Next step after this PR lands:
 - Remove the `Window` class entirely (it is replaced by `SingletonFlutterWindow`). Some minor changes in the Framework are needed to switch to using `SingletonFlutterWindow` directly first.

   The `Window` class still exists in this PR, but will be removed as soon as the framework is converted to point to the `SingletonFlutterWindow` class instead. They share the same API, just have different names (`Window` is currently a subclass of `SingletonFlutterWindow`). The intention is that the `Window` name will be freed up to use as a widget class name in the framework for managing windows. The singleton called `window` will remain, and keep the same API it has now.

## Related Issues

 - https://github.com/flutter/flutter/issues/30701
 - https://github.com/flutter/flutter/issues/48838
 - https://github.com/flutter/flutter/issues/60131

## Tests

 - Existing tests pass, as do Framework tests.
 - Tests were modified to use the new platform dispatcher instead of the window singleton.

## Breaking Change

 - No, this is not a breaking change, either for the embedding API or for the Framework.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
@gspencergoog Looks like this conflicted pretty heavily with https://github.com/flutter/engine/pull/21572, if you have any advice on how to merge that PR in it would be much appreciated. (Not critical, I'll look at it on Monday and try to figure it out.)

**Comment by gspencergoog** [comment]
@Hixie Yes, I can help you out with that: it's pretty hairy, I agree.  Mostly the bodies of the functions moved to static functions on PlatformDispatcher, and the platform message dispatch mechanism moved there too (because that's a main point of the class). They mostly weren't changed, just moved.

I'll see if I can try a merge today and send you a diff to apply.

**Comment by IvanVishnevskiy** [comment]
Does this mean we will get multiple windows in flutter rather soon-ish?

**Comment by gspencergoog** [comment]
@IvanVishnevskiy It's going to be a while. There is still a lot of work left to do, both in the engine and the framework.

**Pull request merged**
