### PR TITLE
Manual Dart SDK roll 6e015bd9cddb to 9c6e76468ca4 (6 revisions)

### PR DESCRIPTION
**Pull request by mkustermann**
This includes the commits from

  https://dart.googlesource.com/sdk.git/+log/6e015bd9cddb..9c6e76468ca4

as well as the changes from

  https://github.com/flutter/engine/pull/22149/files

which are needed due to dart-lang/sdk@23ee425de7533b

### CODE REVIEW

**Review by a-siva — APPROVED** [review]

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by mkustermann** [comment]
@a-siva @dnfield Could one of you Squash&Merge once the try-jobs are done?

After this PR lands the dart -> engine auto-roller should hopefully work again.

**Comment by dnfield** [comment]
There's an app for that!

**Comment by zanderso** [comment]
The tree is closed on infra failures that should now be addressed. Landing this.

**Comment by amirh** [comment]
Starting this roll `flutter/plugins` driver tests are hanging on CI, see: https://github.com/flutter/flutter/issues/69439

**Pull request merged**
