### PR TITLE
Add Picture.toImage

### PR DESCRIPTION
**Pull request by abarth**
Fixes https://github.com/flutter/flutter/issues/6774

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde I'm passing null for the color space.  Is that the right thing, or should I be passing an explicit color space?

**Comment by Hixie** [comment]
I think we should have made `Picture.toImage` async, returning only once the texture has been uploaded to the GPU.

**Comment by abarth** [comment]
> I think we should have made Picture.toImage async, returning only once the texture has been uploaded to the GPU.

There's no guarantee that `Image` objects are backed by GPU memory.  For example, if an `Image` hasn't been drawn in a while and we're low on GPU memory, we might purge the `Image` from GPU memory but keep some other representation of the image in CPU memory.

We could add a method to `Image` to upload the data to the GPU and return a `Future` that completes when that's done.

**Comment by Hixie** [comment]
Can we synchronously tell if something is in GPU memory or not?

**Comment by abarth** [comment]
We'd need to track that state.

**Comment by Hixie** [comment]
If we don't track that state, then how do we know when to upload the image today? I feel I'm missing some key factoid here...

**Comment by abarth** [comment]
We don't always upload the data explicitly.  An SkImage isn't a handle to a block of memory allocated somewhere.  An `SkImage` is something that is capable of filling a block of memory with an image when asked.  That's why you can synchronously create an `SkImage` from an `SkPicture`.  All you do is make an object that holds onto the `SkPicture` and is prepared to rasterize it to a block of memory when asked.

On top of that, Skia layers a caching system.  That cache helps you avoid continually doing all the work of filling up a block of memory with the image.  Roughly, it holds on to the block of memory in a weak sort of way so that you can either re-use that block of memory when you need the image in a block of memory or you can do an efficient blit from your cached block of memory to the block of memory where you need the image to appear.

Essentially, what you're asking for is to know whether there's a cached block of memory associated with the `SkImage` and what sort of cached memory block it is (i.e., CPU-resident, GPU-resident).  Skia probably knows the answer to that question internally (at least under some lock or on some thread).  From the client's perspective, you can also remember whether `onGenerateTexture` has been called:

https://github.com/google/skia/blob/master/include/core/SkImageGenerator.h#L193

You might also be able to know something about the current status of the object you returned from `onGenerateTexture`.

**Comment by Hixie** [comment]
The problem that came up is someone is using this, then immediately turning around and trying to paint it, and finding that they miss frames. I like the idea of an API that says "hey, make sure this is on the GPU", but if it can be evicted arbitrarily, how would the programmer know whether it's worth delaying for a bit or not?

**Comment by abarth** [comment]
> if it can be evicted arbitrarily, how would the programmer know whether it's worth delaying for a bit or not?

You're basically asking whether the end-developer should be responsible for managing the budget for GPU memory.  We can certainly expose that if you like.  Skia scheme is roughly that it has an overall budget for GPU memory use, and you can select for a given allocation whether it's charged against that budget and whether it's evictable.  Of course, if you mark something as included in the budget and non-evictable, then that leaves less budget for other parts of the system to work with.  At some level, that's the reality of having a scarce resource to manage.

My guess is that an approach that might work well in practice is to have a function that warms the cache and returns a future that completes when we've successfully warmed the cache.  The advice we'd give developers is to call that function between when they create the image and when they start using the image (assuming they can delay the use of the image).  If the app is in-budget, then everything will run smoothly.  If the app is out-of-budget, then its out of budget and will have reduced performance as a result.

**Comment by Hixie** [comment]
The case I'm worried about is where they used the image a long time ago, and now want to use it again, but don't know if they went out of budget in the meantime. I suppose we could say that when it's been that long, you should always assume that you've gone out of budget in the meantime and call the warming method, and await the future.

**Comment by chinmaygarde** [comment]
> There's no guarantee that Image objects are backed by GPU memory.

We can make this guarantee for all images generated on the IO thread. All images created using `SkImage::MakeCrossContextFromEncoded` are backed only by GPU memory. There is no host side copy of the image data and associated structures.

> if an Image hasn't been drawn in a while and we're low on GPU memory, we might purge the Image from GPU memory but keep some other representation of the image in CPU memory.

We do not do this today for all images because of the following reasons:
* We don't have the host side copy of the image data for most images since we already got rid of it after our call to `SkImage::MakeCrossContextFromEncoded` mentioned above.
* There is no reliable way to query a platform to see if it is running low on GPU memory. The Flutter engine has no such querying mechanisms and neither does Skia. The only way to know if we are running out of memory is when attempts to allocate new GPU resource start failing.

Only images created on the UI thread (for example, the `toImage()` call in this thread) can upload their data to GPU memory on demand. Skia may choose to optimize the rendering of such images by maintaining a mapping from the host side copy image to the GPU side copy by putting the GPU side counterpart in a budgeted cache.

In practice, this caching mechanism is unreliable and inefficient and must only be used for extremely small images that are OK to upload on a per frame basis anyway. This is because of the following reasons:
* As previously mentioned, there is no reliable way to query if the platform is running low on GPU memory. Hence, the cache maintained by Skia has a fixed size. Attempting to put large images into this cache that will benefit most from being cached in the first place will cause the cache size to exceed it limit. So Skia will immediately refuse to keep the item around. This will lead to it attempt to upload the texture per frame.
  * We have seen this before in this issue https://github.com/flutter/flutter/issues/6581. We worked around the issue by loading the image on the IO thread (essentially taking texture upload responsibility away from Skia by giving it the raw texture handle).
* Even when the cache works, we will always have two decompressed copies on the image (one on the host side and one of the device) instead of the necessary one.

Once Skia has a GPU memory backed copy of the image, it will not attempt to move it from GPU to CPU memory on demand. It will only transfer it from CPU to GPU again if necessary (and it has the CPU side copy).

I feel like a lot of this discussion assumes that we have a way of detecting resource scarcity. All we can ever know reliably is whether we can allocate the next resource or not. So I would advocate APIs that are as explicit as possible and allocate the fewest GPU resources instead of depending on caches to manage this in some automated fashion.

**Comment by abarth** [comment]
@chinmaygarde Sounds like you're suggesting that the method that ensures that the image is uploaded to the GPU sets the Skia bits to not charge the image against Skia's budget.

The remaining question is whether we want to support non-GPU resident `Image` objects at all.  If not, then the simpler API would be for this method to return `Future<Image>` and wait for the raster/upload to complete before resolving.

**Comment by chinmaygarde** [comment]
> Sounds like you're suggesting that the method that ensures that the image is uploaded to the GPU sets the Skia bits to not charge the image against Skia's budget.

Yes. In fact, since these images are uploaded in an entirely different `GrContext`, we don't even want the incidental expenses of creating the cache for this context. We disable the [same here](https://github.com/flutter/engine/blob/e07eafae1d14b454c33b1ae68d14b7a5694c22b6/shell/common/platform_view.cc#L205).

> The remaining question is whether we want to support non-GPU resident Image objects at all.

The only reason to support such images is if the caller wanted to manipulate the bytes of the images. Since `ui.Image` [provides](https://docs.flutter.io/flutter/dart-ui/Image-class.html) no such methods currently, we can safely switch to making the guarantee that all images are GPU resident and not have to change the API at all (we would still need to return the future to the image however since there is no way of synchronously getting a GPU image on the IO thread).

**Comment by abarth** [comment]
Ok, sounds reasonable to me!

**Comment by chinmaygarde** [comment]
On it. Should I modify the current call to return a future to an image or add a new method? Modifying this would be a breaking change.

**Comment by abarth** [comment]
That's a question for @Hixie ^^^

**Comment by Hixie** [comment]
Modify it, otherwise people will depend on the sync version. Make sure to check the breaking change policy on the design principles doc and do what it says there though.

**Comment by nsreenath** [comment]
@abarth Can we simply use `SkImage->encodeToData()` to solve this issue [#11648](https://github.com/flutter/flutter/issues/11648) in flutter/flutter ?
If so it would be great help.

**Comment by chinmaygarde** [comment]
> Can we simply use SkImage->encodeToData() to solve this issue flutter/flutter#11648 ?
If so it would be great help.

Not quite. The picture may reference images obtained as a result of asynchronous texture upload. Dart code only holds references to raw texture handles. Besides, Dart code runs on a thread that does not have access to GPU resources. Calling `encodeToData` might give you a bitmap (if Skia does not assert on the missing resource) but it will definitely be missing a lot of content.

**Comment by nsreenath** [comment]
@chinmaygarde So FlutterView.getBitmap() in Android also has this missing issue due to async texture upload ?

**Comment by nsreenath** [comment]
@chinmaygarde When I tested on my Android phone, `FlutterView.getBitmap()` is not rendering image loaded with ` Image.asset()` and `Image.network()`, but `Icon(Icons.add)` is rendered.
I tested by displaying a `FlutterView `on one part of screen and an `android.widget.ImageView` on another part using `imageView.setImageBitmap(flutterView.getBitmap())`on response to button click, and I am clicking the button only after image is loaded inside `FlutterView`.

**Pull request merged**
