### PR TITLE
Revert "[Impeller] Enable on-by-default on Android."

### PR DESCRIPTION
**Pull request by reidbaker**
Reverts flutter/engine#54156

Potential fix forward https://github.com/flutter/engine/pull/54296
Pull request to stop testing the crash path https://github.com/flutter/packages/pull/7294 
Discord thread. https://discord.com/channels/608014603317936148/1268607913971417240

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
Per the thread, we are also working on unblocking the roller directly.

**Comment by reidbaker** [comment]
Holding this pr until the discord thread makes a decision.

**Comment by chinmaygarde** [comment]
xref https://github.com/flutter/packages/pull/7294

**Comment by chinmaygarde** [comment]
Stepping away to grab a bite, but the plan as or right now is to to unblock the autoroller by disabling Impeller in the test in https://github.com/flutter/packages/pull/7294, fixing the actual issue in https://github.com/flutter/engine/pull/54296 to follow the iOS style platform view deletion scheme. This is a fallback in case there are still blockers.

**Comment by chinmaygarde** [comment]
I don't think we need this anymore. Please close it when convenient.

**Comment by chinmaygarde** [comment]
Jonah is OOO this week so I can't promise a timeline deadline to land the proposed fix. Though, I can take over getting it across the finish line if needed.

Rest sounds good.

I figured I should also spend some understanding why the race is triggered more often in Impeller.

**Comment by reidbaker** [comment]
Ok sounds good, lets sync back up on thursday and see if the revert should land.

**Pull request closed without merging**
