### PR TITLE
[Android] Fixes a memory leak caused by KeyboardChannel

### PR DESCRIPTION
**Pull request by gtbluesky**
A memory leak will happen when I use multiple FlutterActivity/FlutterFragment share reused flutter engine.

The following is the stack captured by Leakcanary:
┬───
│ GC Root: Input or output parameters in native code
│
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (Fusion↓ is not leaking and A ClassLoader is never leaking)
│    ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (Fusion↓ is not leaking)
│    ↓ Object[156]
├─ com.gtbluesky.fusion.Fusion class
│    Leaking: NO (a class is never leaking)
│    ↓ static Fusion.defaultEngine
│                    ~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.FlutterEngine instance
│    Leaking: UNKNOWN
│    Retaining 1.0 kB in 31 objects
│    ↓ FlutterEngine.dartExecutor
│                    ~~~~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartExecutor instance
│    Leaking: UNKNOWN
│    Retaining 78 B in 2 objects
│    ↓ DartExecutor.dartMessenger
│                   ~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartMessenger instance
│    Leaking: UNKNOWN
│    Retaining 57.6 kB in 1291 objects
│    ↓ DartMessenger.messageHandlers
│                    ~~~~~~~~~~~~~~~
├─ java.util.HashMap instance
│    Leaking: UNKNOWN
│    Retaining 57.2 kB in 1278 objects
│    ↓ HashMap["flutter/keyboard"]
│             ~~~~~~~~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo instance
│    Leaking: UNKNOWN
│    Retaining 49.1 kB in 844 objects
│    ↓ DartMessenger$HandlerInfo.handler
│                                ~~~~~~~
├─ io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler instance
│    Leaking: UNKNOWN
│    Retaining 49.1 kB in 843 objects
│    ↓ MethodChannel$IncomingMethodCallHandler.handler
│                                              ~~~~~~~
├─ io.flutter.embedding.engine.systemchannels.KeyboardChannel$1 instance
│    Leaking: UNKNOWN
│    Retaining 49.0 kB in 841 objects
│    Anonymous class implementing io.flutter.plugin.common.
│    MethodChannel$MethodCallHandler
│    ↓ KeyboardChannel$1.this$0
│                        ~~~~~~
├─ io.flutter.embedding.engine.systemchannels.KeyboardChannel instance
│    Leaking: UNKNOWN
│    Retaining 49.0 kB in 839 objects
│    ↓ KeyboardChannel.keyboardMethodHandler
│                      ~~~~~~~~~~~~~~~~~~~~~
├─ io.flutter.embedding.android.KeyboardManager instance
│    Leaking: UNKNOWN
│    Retaining 48.9 kB in 838 objects
│    ↓ KeyboardManager.viewDelegate
│                      ~~~~~~~~~~~~
├─ io.flutter.embedding.android.FlutterView instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    Retaining 48.6 kB in 822 objects
│    View not part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.null
│    View.mWindowAttachCount = 1
│    mContext instance of com.gtbluesky.fusion_example.CustomFusionActivity
│    with mDestroyed = true
│    ↓ View.mContext
╰→ com.gtbluesky.fusion_example.CustomFusionActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.gtbluesky.
​     fusion_example.CustomFusionActivity received Activity#onDestroy()
​     callback and Activity#mDestroyed is true)
​     Retaining 34.3 kB in 565 objects
​     key = 6cda8d0d-c905-406d-9a84-ea528cc88741
​     watchDurationMillis = 5685
​     retainedDurationMillis = 682
​     mApplication instance of com.gtbluesky.fusion_example.MyApplication
​     mBase instance of android.app.ContextImpl

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gtbluesky** [comment]
Hi @math1man, could you please review and merge my pr? THX!

**Comment by xster** [comment]
math1man is away for the month. This will follow @reidbaker team's normal triaging process.

**Review by camsim99 — COMMENTED** [review]
This looks good but can we add a test to verify `keyboardChannel` is set and removed as the keyboard method handler in `destroy` as we'd expect?

**Comment by gtbluesky** [comment]
> This looks good but can we add a test to verify `keyboardChannel` is set and removed as the keyboard method handler in `destroy` as we'd expect?

of course

**Comment by jonahwilliams** [comment]
Status update: this is waiting for a test.

**Comment by chinmaygarde** [comment]
Any update expected on the test?

**Comment by gtbluesky** [comment]
> This looks good but can we add a test to verify `keyboardChannel` is set and removed as the keyboard method handler in `destroy` as we'd expect?

Is there any code or documentation available for reference regarding the test? THX!

**Comment by camsim99** [comment]
> Is there any code or documentation available for reference regarding the test? THX!

Let me know if you need a specific sort of example, but the tests should live in [`KeyboardManagerTest.java`](https://github.com/flutter/engine/blob/main/shell/platform/android/test/io/flutter/embedding/android/KeyboardManagerTest.java) and the sorts of tests we're looking for to verify the logic you added are in there :)

**Comment by johnmccutchan** [comment]
@gtbluesky I suggest you start by trying to write a test that fails without this PR applied.

**Comment by chinmaygarde** [comment]
Closing this stale.

**Pull request closed without merging**
