### PR TITLE
Conditional directives are a snapshotter option. Remove the same from the embedder VM and add the flag to the precomp snapshotter.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
@rmacnak-google explained that since conditional directives change how the parser works, it is a snapshotter option. This flag makes no sense on the embedder VM as the snapshot has already been generated from the parsed source. The script snapshotter already includes this flag (`sky/tools/sky_snapshot/vm.cc`). I have added the flag to the precomp snapshotter in this patch and removed the same from the embedder VM.

cc @collinjackson

**Comment by collinjackson** [comment]
thank you! lgtm

**Comment by Hixie** [comment]
does this affect cases where we skip the snapshotter? I think @jasonsimmons may have been working on something that did that?

**Comment by Hixie** [comment]
er, @jsimmons maybe? autocomplete isn't working on my phone...

**Comment by Hixie** [comment]
I give up. ☺

**Comment by krisgiesing** [comment]
@jason-simmons

**Comment by Hixie** [comment]
Thanks!

**Comment by chinmaygarde** [comment]
@Hixie: I think you're right. I didn't think there were cases where the embedder was not working from a snapshot (script or precomp). But the VM on the iOS simulator does not need any snapshotting. I will add the flag back to embedder VM on the non-precomp variant (the flag is not present on the precomp stuff and the VM exits if one is provided).

**Comment by rmacnak-google** [comment]
More accurately it is a compile-time option, which means it affects the JIT and the AOT snapshotter but not the AOT runtime.

**Pull request merged**
