### PR TITLE
Make FlutterAppDelegate an empty AppDelegate

### PR DESCRIPTION
**Pull request by collinjackson**
The code from FlutterAppDelegate is moving into the iOS template project. See flutter/flutter#4895 (which should be merged before this one)

### CODE REVIEW

**Comment by abarth** [comment]
We should remove all the clients of this code before landing this patch.  Once all the clients are removed, this LGTM.

**Comment by collinjackson** [comment]
I've updated this PR so that the FlutterViewController can be instantiated directly from storyboards without having to do anything in the AppDelegate. This means that previous clients of FlutterAppDelegate will have completely empty AppDelegates.

**Comment by abarth** [comment]
Nice!

**Comment by collinjackson** [comment]
Thinking about this some more, I think we should keep FlutterAppDelegate around and just have it be an empty implementation. That way we don't have to worry about updating the clients, and the examples/benchmarks will have less boilerplate in them. Seem reasonable? I updated the PR to this effect.

**Comment by collinjackson** [comment]
Basically, there are a two options here:

1) Make the examples and benchmarks as similar as possible to the output of flutter create, so we're always going down the same code path as our users when we are running them. (I can't think of a good way to ensure they stay in sync, though.)

2) Make the examples and benchmarks as simple as possible (e.g. don't have an xcworkspace, Podfile, AppDelegate, etc.). In this universe, it makes sense for engine to have an empty FlutterAppDelegate class (which could potentially be renamed FlutterEmptyAppDelegate)

Do you have a preference?

**Comment by abarth** [comment]
> That way we don't have to worry about updating the clients,

I think that's fine for a transition, but we should file a bug and be sure to remove it before we finish stablizing the Flutter.framework API.

> Do you have a preference?

I think we should make them as simple as possible.

**Comment by collinjackson** [comment]
Thanks! I filed #4907 to track figuring out what to do with the empty FlutterAppDelegate class. I don't particularly care one way or another.

**Pull request merged**
