### PR TITLE
Set a higher filter quality for drawing raster cache images

### PR DESCRIPTION
**Pull request by jason-simmons**
According to Skia, kLow offers a quality improvement with little cost over
the default kNone

Fixes https://github.com/flutter/flutter/issues/12091

### CODE REVIEW

**Comment by jason-simmons** [comment]
@cbracken @chinmaygarde

**Comment by Hixie** [comment]
Maybe might fix https://github.com/flutter/flutter/issues/11898 ?

**Comment by cbracken** [comment]
lgtm

**Comment by sethladd** [comment]
Thank you so much! What's the path for merging this into flutter/flutter ? https://github.com/flutter/engine/pull/4116

**Comment by cbracken** [comment]
Rolled in flutter/flutter#12169.

**Comment by apwilson** [comment]
I can confirm that this does *not* fix  flutter/flutter#11898

**Pull request merged**
