### PR TITLE
Wire up the Fuchsia SDK into the engine and build the Flutter runner.

### PR DESCRIPTION
**Pull request by chinmaygarde**
This imports the Flutter runner target currently residing at
`//topaz/runtime/flutter_runner` into the Flutter engine as a sibling of the
iOS & Android shells.

To use the Fuchsia SDK to build this target, the buildroot has been updated
to use the toolchain vended with the SDK.

GN templates have been created in `//flutter/build/fuchsia/fuchsia.gni` that
can read the JSON metadata that describes the vended SDK.

GN targets that describe all known SDK parts (as described in the SDK
manifest) can be instantiated in one shot by defining a top level `fuchsia_sdk`
target. This stamping needs to happen once and can be done anywhere (currenly
in `//flutter/shell/platform/fuchsia`). Once stamped, targets that depend on
specific Fuchsia SDK parts need to explicitly depend on them by using the
name of that part. For example, depending on the `:fuchsia.images` part of the
SDK will generate headers for all fidl files in that part, compile any source
libraries and link the required dynamic libraries into the executable. Unlike regular
targets, this target does not exist in a GN file. The name must be looked up
from JSON manifest. This scheme seems to work well but is not resilient
to part name collision.

So that SDK and non-SDK Fuchsia builds may co-exist till the migration is done,
the `is_fuchsia_sdk` GN variable and `FUCHSIA_SDK` preprocessor defines are
set in all Fuchsia SDK builds. This allows code to target both variants. It is
the hope that the non SDK variant will be turned down and the Flutter team
assumes ownership of this component.

The libraries that were not vended in the SDK have been copied as source
in `//flutter/build/fuchsia/`. The appropriate issues in the internal issue
tracker and documents have been updated to expedite the process of getting
the same into the SDK.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
WIP till the dependencies land so I do update the DEPS file. But the binary builds.

**Comment by dnfield** [comment]
Will the flutter_runner be in the engine repo after this, or would we still have to work out of the topaz repo to make changes to it?

Relevant to work I'm doing on the accessibility bridge.

**Comment by chinmaygarde** [comment]
> Will the flutter_runner be in the engine repo after this, or would we still have to work out of the topaz repo to make changes to it?

After this, it will be in the engine repo.

> Relevant to work I'm doing on the accessibility bridge.

During the transition, this workflow is probably not going to suitable for development. I don't want to block your work. If you continue patching to the repo in topaz, I will pick those patches and apply them here.

**Comment by abarth** [comment]
Definitely looks like its on the right track.  It's a bit hard to review in such a large change.  Looks like there's a networking-related C library that we need to give you a better solution for.  Copying the ioctl declaration here is going to cause pain later.  Can you file a bug on that issue?

**Comment by chinmaygarde** [comment]
> It's a bit hard to review in such a large change.

Agreed. I'll blow up this patch into multiple smaller chunks for landing. This is the entirety of the changes and wanted some sanity checks on direction.

While I have your attention, can you chime in on the thread in DX chat regarding how SDK and non-SDK buildroots will be handled in dependencies of Flutter?

**Comment by chinmaygarde** [comment]
[fxb/DX-1450](http://fxb/DX-1450) filed for the ioctl declaration.

**Comment by abarth** [comment]
> chime in on the thread in DX chat

I can never find chat messages.  I'm happy to reply to an email thread if there is one.

**Comment by chinmaygarde** [comment]
I sent you an email instead.

**Comment by chinmaygarde** [comment]
Closing in favor of smaller patches for landing.

**Pull request closed without merging**
