### PR TITLE
add support for FlutterView reusing in multiple Activities

### PR DESCRIPTION
**Pull request by SupSaiYaJin**
When add flutter in existing apps, we need to use FlutterView in multiple Activities. Creating multiple FlutterViews for each Activity will cause memory problem and low performance. My solution is let FlutterView use application's context, provide attachActivity and detachActivity Methods to support reusing one FlutterView in multiple Activities. Of course, the original usage won't be affected.

### CODE REVIEW

**Comment by dnfield** [comment]
I didn't look too deeply but suspected it either duplicated or conflicted with your ongoing work.

**Comment by SupSaiYaJin** [comment]
> I didn't look too deeply but suspected it either duplicated or conflicted with your ongoing work.

When will the new embedding be released? Will it be release with v1.0 together?

**Comment by matthew-carroll** [comment]
There is currently no release date for the new embedding, but it is actively being developed and it is a high priority.

**Comment by SupSaiYaJin** [comment]
> @SupSaiYaJin there is work going on right now to overhaul the entire Android embedding for Flutter, so I think it's probably best that we don't take this change. The ability to utilize multiple FlutterViews will be facilitated by the new embedding.
> 
> Also, I'm not sure this change works for plugins. The reason the Activity was being passed as a Context is because the PluginRegistry needs an Activity.
> 
> @dnfield do you have any opinions on this?

In my changes, Activity is still passed as a Context in constructor and is passed to PlatformPlugin.
`attachActivity` will be called in constructor to do this.
```java
public void attachActivity(Activity activity) {
    detachActivity();
    mNativeView.attachViewAndActivity(this, activity);
    mPlatformPlugin = new PlatformPlugin(activity);
    mFlutterPlatformChannel.setMethodCallHandler(mPlatformPlugin);
    addActivityLifecycleListener(mPlatformPlugin);
}
``` 
But Activity context won't pass to superclass's constructor, pass Application Context instead.
```java
public FlutterView(Context context, AttributeSet attrs, FlutterNativeView nativeView) {
    super(context.getApplicationContext(), attrs);
    // ...
}
```

**Comment by cbracken** [comment]
@SupSaiYaJin thank you for your contribution. I'll close this PR since this is likely to conflict with the updated Flutter embedding that @matthew-carroll is working on, which should solve this issue.

**Pull request closed without merging**
