### PR TITLE
[windows] use angle fast path on d3d11 backend

### PR DESCRIPTION
**Pull request by jonahwilliams**
Experimentally this makes things render faster on my end.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
ideally the test for something like this would be a benchmark

**Comment by dnfield** [comment]
I agree on the benchmark. It'd be good to attach a timeline here of what we're working on to see what it looks like now.

This change LGTM - we don't have a good way to verify if or how this attribute gets used by angle short of benchmarking it. @zanderso WDYT?

**Review by dnfield — COMMENTED** [review]
LGTM

**Review by dnfield — APPROVED** [review]

**Comment by zanderso** [comment]
Would any of our existing benchmarks show a benefit from this change if we were running them on Windows in CI and sending the results to SkiaPerf?

**Comment by dnfield** [comment]
Jonah's going to attach a trace, but raster times should get better on any Windows benchmark with this patch.

**Comment by jonahwilliams** [comment]
Timeline: [dart-timeline-2022-3-4 (1).zip](https://github.com/flutter/engine/files/8187909/dart-timeline-2022-3-4.1.zip)

**Comment by jonahwilliams** [comment]
I think it is still worthwhile to write a test that grabs the extensions to make sure this is enabled correctly - but I don't know if that would _actually_ pass on a bot unless that bot supports D3D11.

**Comment by zanderso** [comment]
@godofredoc do you know if the Windows bots have d3d11?

**Comment by jonahwilliams** [comment]
I guess in that sense, its not _really_ a unit test given that it is hardware dependent

**Comment by zanderso** [comment]
It looks like there's no devicelab support for running benchmarks on Windows desktop https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/devices.dart#L55. I wonder if we have an issue for that? @cbracken

**Comment by dnfield** [comment]
I don't think there's any device support for running on Desktop _period_.

@gspencergoog I think worked on adding an integration test for desktop at some point though, he may know more.

**Comment by godofredoc** [comment]
> @godofredoc do you know if the Windows bots have d3d11?

Not sure, we are re-using chrome images. We can create a test and giving it a try.

**Comment by godofredoc** [comment]
> It looks like there's no devicelab support for running benchmarks on Windows desktop https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/devices.dart#L55. I wonder if we have an issue for that? @cbracken

From the bots point of view the benchmark can use windows-android bot.

**Comment by jonahwilliams** [comment]
Do those bots have visual studio and other windows dependencies installed?

**Comment by godofredoc** [comment]
> Do those bots have visual studio and other windows dependencies installed?

Visual studio is installed at runtime during the task execution, not sure what other dependencies are needed but once we identify them we can install them.

**Comment by jonahwilliams** [comment]
Seeing if I can create a benchmark here: https://github.com/flutter/flutter/pull/99564

**Comment by godofredoc** [comment]
> Seeing if I can create a benchmark here: [flutter/flutter#99564](https://github.com/flutter/flutter/pull/99564)

@keyonghan can you please help craft a led command and properties file to test https://github.com/flutter/flutter/pull/99564 in a devicelab bot?

**Review by cbracken — APPROVED** [review]

**Comment by keyonghan** [comment]
> > Seeing if I can create a benchmark here: [flutter/flutter#99564](https://github.com/flutter/flutter/pull/99564)
> 
> @keyonghan can you please help craft a led command and properties file to test [flutter/flutter#99564](https://github.com/flutter/flutter/pull/99564) in a devicelab bot?

Here is an LED run based on the above PR: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a2959aaf43d320eeb3e5800d0f3dc1c63a4431d38439b1e8c9e630a017cba20f/+/build.proto,  it failed from the very beginning when resolving depencies:

```
stdout: [  +88 ms] Running "flutter pub get" in flutter_gallery...
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [   +5 ms] executing: [C:\b\s\w\ir\x\w\recipe_cleanup\tmpaorsxrej\flutter sdk\dev\integration_tests\flutter_gallery/] C:\b\s\w\ir\x\w\recipe_cleanup\tmpaorsxrej\flutter sdk\bin\cache\dart-sdk\bin\dart __deprecated_pub --trace --verbose get --no-precompile
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [ +123 ms] FINE: Pub 2.17.0-169.0.dev
[windows_home_scroll_perf__timeline_summary] [STDOUT] stdout: [  +94 ms] MSG : Resolving dependencies...
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [  +30 ms] SLVR: fact: flutter_gallery is 0.0.0
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [   +7 ms] SLVR: derived: flutter_gallery
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [  +45 ms] SLVR: fact: flutter_gallery depends on flutter from sdk
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [        ] SLVR: fact: flutter_gallery depends on collection 1.15.0
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [        ] SLVR: fact: flutter_gallery depends on device_info 2.0.3
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [        ] SLVR: fact: flutter_gallery depends on intl 0.17.0
[windows_home_scroll_perf__timeline_summary] [STDOUT] stderr: [        ] SLVR: fact: flutter_gallery depends on connectivity 3.0.6
```

**Comment by jonahwilliams** [comment]
Ahh, its trying to screenshot - I can fix that

**Comment by jonahwilliams** [comment]
I updated the PR so it should be able to get further

**Comment by keyonghan** [comment]
> I updated the PR so it should be able to get further

Thanks for the quick fix. It passed through: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/fcd53b2134e182a9566e74c487a0ca45a3f580516a53a462fb78775d7ad25bc0/+/build.proto

**Comment by jonahwilliams** [comment]
Nice, thank you for the help @keyonghan . I guess the next step is to merge that to get at least one benchmark running, then get a test exception to land this and see if it helps the numbers

**Comment by jonahwilliams** [comment]
Benchmark is running now: https://flutter-flutter-perf.skia.org/e/?queries=test%3Dwindows_home_scroll_perf__timeline_summary

**Comment by christopherfujino** [comment]
test-exempt: this will be tested by the benchmark in https://github.com/flutter/flutter/pull/99564

**Pull request merged**
