### PR TITLE
Roll Harfbuzz to 2.7.0 (c6ca30dc757ff86416d97d358f20080b979b80c9)

### PR DESCRIPTION
**Pull request by dnfield**
Rolls harfbuzz to 2.7.0, which contains fixes that improve font-subset (and presumably other good things, we hope).

It is expected that this will impact golden tests that render text. /cc @renyou @mehmetf @Piinks 

Fixes https://github.com/flutter/flutter/issues/60325

/cc @zanderso @jonahwilliams FYI

### CODE REVIEW

**Comment by jason-simmons** [comment]
This is not building because HarfBuzz 2.7.0 apparently requires choosing an implementation of threading primitives.

Previously we had been using a default fallback implementation (see https://fuchsia.googlesource.com/third_party/harfbuzz/+/f5c000538699a4e40649508a44f41d37035e6c35/src/hb-mutex.hh#104).  But that has been removed.

Defining HAVE_PTHREAD should work for Android and Linux.  I'm not sure what the best option is for Fuchsia.

**Comment by dnfield** [comment]
I'm assuming based on  https://fuchsia.dev/fuchsia-src/concepts/system/libc?hl=en#pthreads that this usage of pthreads on Fuchsia is OK.

**Comment by zanderso** [comment]
> I'm assuming based on https://fuchsia.dev/fuchsia-src/concepts/system/libc?hl=en#pthreads that this usage of pthreads on Fuchsia is OK.

Maybe @arbreng or @dreveman can confirm.

**Comment by dnfield** [comment]
May be a moot point. @chinmaygarde pointed out that we don't really need harfbuzz to do any locking, so we can just tell it to not use mutexes.

**Comment by dnfield** [comment]
License bot finally seems happy.

**Pull request merged**
