### PR TITLE
Use bundled Roboto in all tests

### PR DESCRIPTION
**Pull request by yjbanov**
This is so our screenshots do not change depending on whether tests run locally, Cirrus, or LUCI.

/cc @godofredoc

### CODE REVIEW

**Comment by mdebbar** [comment]
What happens if I forget to call `setUpStableTestFonts()` in my tests? Should we make it easier to spot? Like maybe use an unreadable font by default or something.

**Comment by yjbanov** [comment]
> What happens if I forget to call `setUpStableTestFonts()` in my tests? Should we make it easier to spot? Like maybe use an unreadable font by default or something.

We actually have that already: https://github.com/flutter/engine/blob/48eadbb312ed923a171199693072bd9d221dca99/lib/web_ui/lib/src/engine/dom_renderer.dart#L345. But perhaps the default style is not outrageous enough to spot :)

**Comment by mdebbar** [comment]
Not styles, I meant the font itself. Like if I use `Roboto` in my test but forget to call `setUpStableTestFonts()`. What happens?

**Comment by yjbanov** [comment]
> Not styles, I meant the font itself. Like if I use `Roboto` in my test but forget to call `setUpStableTestFonts()`. What happens?

So in the engine our tests use at least three modes:

- Use the default (i.e. nothing is configured) - typically tests that do not render any text end up in this mode because they do not care about font styles at all.
- Use Ahem (i.e. all font families are routed to Ahem irrespective of the family specified in the test). Our text measurement tests use this, and maybe some tests that ended up in this mode accidentally. **In this mode it is totally OK to specify Roboto and not call setUpStableTestFonts**.
- Use Roboto (after this PR) where visual legibility of text is important to the test. This is when specifying Roboto and calling setUpStableTestFonts is important, otherwise you get OS/environment sensitivity.

We could have a more structured API for running engine tests, just like the framework does with `testWidgets`, but currently we use plain `package:test` and tests are free to do whatever they like, and configure the runtime however they like. I'm happy to chat about what we can do here to make things more manageable.

**Comment by mdebbar** [comment]
Thanks for breaking down the use cases. This makes it easier for me to clarify where my concern is coming from.

So in the 3rd case (i.e. `Use Roboto (after this PR) where visual legibility of text is important`). It's super easy for me to forget to call `setUpStableTestFonts()` and I won't even notice it. Unless I'm misunderstanding something (which I likely am).

Happy to discuss this when I'm back in the office tomorrow or Monday. It's not a blocker for this PR, so feel free to merge!

**Comment by yjbanov** [comment]
@mdebbar Funny enough I _did_ forget to call `setUpStableTestFonts` in one test (see https://github.com/flutter/engine/pull/16218/commits/bcada895ffcdc3b0de88b90f780df47d1d874eb8). That caused an outright test failure though, so I didn't need to rely on visual inspection to catch it.

**Pull request merged**
