### PR TITLE
Ensure correct child isolate initialization in enable-isolate-groups dart vm configuration.

### PR DESCRIPTION
**Pull request by aam**
Dart_SetRootLibrary and LoadKernel needs to be done only for a root isolate in the isolate group. When in `--enable-isolate-groups` dart vm mode child isolates will reuse kernel and object store set up by root isolate.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Just curious about progress on this patch. Is there some blocker?

**Comment by mkustermann** [comment]
@chinmaygarde

This change will be required iff `--enable-isolate-groups` is also enabled in JIT mode. So turning on the flag will require these changes.

We could land the PR now (despite being the flag off atm) by guarding the changes via `Dart_IsVMFlagSet("--enable-isolate-groups")`. Then once flipping the flag, it will do the right thing. Is that something you prefer?

**Comment by mkustermann** [comment]
@aam Could you update this PR to guard the changes under the `Dart_IsVMFlagSet("--enable-isolate-groups")` condition? That would make it easy to enable the flag (and if something goes wrong, disable it again without reverting bigger changes)

**Comment by aam** [comment]
> @aam Could you update this PR to guard the changes under the `Dart_IsVMFlagSet("--enable-isolate-groups")` condition? That would make it easy to enable the flag (and if something goes wrong, disable it again without reverting bigger changes)

Done, but I left the code in dart_vm.cc that enables the flag too.

**Comment by mkustermann** [comment]
> Done, but I left the code in dart_vm.cc that enables the flag too.

@aam Could you limit this change to only avoid the kernel loading (i.e. not enable the flag, not roll DEPS and all the other changes)?

I think we will avoid flipping the flag here in the embedder and instead turn it on by-default in the VM instead, which will transparently make us use the right code path here.

**Comment by aam** [comment]
> @aam Could you limit this change to only avoid the kernel loading (i.e. not enable the flag, not roll DEPS and all the other changes)?

There should be only four files changed in this PR(runtime/dart_isolate.cc, runtime/dart_isolate.h, runtime/dart_vm.cc, runtime/isolate_configuration.cc).
Do you see more(DEPS, anything else)?

**Comment by aam** [comment]
> I think we will avoid flipping the flag here in the embedder

Done.

**Review by mkustermann — APPROVED** [review]

**Comment by mkustermann** [comment]
> Do you see more(DEPS, anything else)?

I did. Not sure why, but after your latest push the `Files changed` shows the right thing.

**Pull request merged**
