### PR TITLE
Revert "[Impeller] switch Pipeline to use raw ptr instead of shared ptr for recorded references."

### PR DESCRIPTION
**Pull request by gaaclarke**
Reverts flutter/engine#57015
fixes https://github.com/flutter/flutter/issues/160004

### CODE REVIEW

**Comment by gaaclarke** [comment]
I was unable to verify the revert fixes this issue since the flake doesn't seem to be able to be reproduced by isolating the failing test.  All failures show up after this PR and the ones after it are opengles and a skia role so they are unlikely to have caused it, while this one did change pipelines.

**Comment by jonahwilliams** [comment]
LGTM

**Comment by gaaclarke** [comment]
Is the revert PR going to merge automatically or does it need approval?  I can't remember.

**Comment by jonahwilliams** [comment]
should be automatic, provided the bot created it

**Comment by jonahwilliams** [comment]
oh, you manually created the revert. You need to add the label to the original PR with a comment, then the bot will merge it ASAP.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by gaaclarke** [comment]
> oh, you manually created the revert. You need to add the label to the original PR with a comment, then the bot will merge it ASAP.

Pedantic note: I didn't manually merge it.  I pressed the "revert" button in the github ui.

**Comment by gaaclarke** [comment]
landing on red to open the tree since I dun goofed the revert bot

**Pull request merged**
