### PR TITLE
strip docs from stub_ui

### PR DESCRIPTION
**Pull request by dnfield**
Replace all docs in stub_ui with placeholder pointing to ui.

These docs are not in sync in multiple places and are very likely to continue to drift.

### CODE REVIEW

**Comment by cyanglaz** [comment]
Just curious why does a stub have dart docs? are they public?

**Comment by dnfield** [comment]
@cyanglaz AFAIK it's because the files were copied and pasted.  The problem at this point is that some people have added new parts of the public API with docs, while others have added them without, and sometimes people update a doc but forget to do it in stub_ui.

**Comment by cyanglaz** [comment]
@dnfield I like that you refer to the old doc to keep them in sync. Is it possible that we just make them private comments like `//`? I feel like if the stub is not some sort of public API then they shouldn't need to have a public doc.

**Comment by dnfield** [comment]
Ahh I see what you're saying.  If I do that though, I have to add ignores to every file for missing docs on public members.

**Comment by jonahwilliams** [comment]
I don't think we should do this - in very short order, the existing stub_ui will be replaced with real implementations. There will inevitably be some transition period where primary development has not moved to the engine but is synced. Maintaining a diff during that period will be more difficult than not.

Furthermore, I would leave it up to the web team what they wish to do with documentation

**Comment by dnfield** [comment]
In that case I'll close this.  @yjbanov if you are interested in pursuing this let me know.

**Pull request closed without merging**
