### PR TITLE
Remove a pile of dead code

### PR DESCRIPTION
**Pull request by abarth**
This patch removes a large amount of dead code, which will make it easier to port to Fuchsia because we have fewer dependencies on //base.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by Hixie** [comment]
You should rerun the license script, it might have a big impact.

**Comment by Hixie** [comment]
(see https://github.com/flutter/engine/blob/master/tools/licenses/README )

**Comment by chinmaygarde** [comment]
lgtm

**Comment by abarth** [comment]
I'm going to remove a bunch more stuff shortly.  I'll run the license script when things settle down.

**Pull request merged**
