### PR TITLE
Migrate `third_party/gradle` to `flutter/third_party/gradle`.

### PR DESCRIPTION
**Pull request by matanlurey**
Part of https://github.com/flutter/flutter/issues/67373.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
@jason-simmons says he can take this to completion next week in case @matanlurey is busy.

**Comment by matanlurey** [comment]
@jason-simmons Thanks, I think that is a good idea - I'm at least 2+ weeks out from spending more time on buildmoot at the moment - happy to review PRs or answer questions though.

**Comment by matanlurey** [comment]
@jason-simmons Still planning to do this/maybe you did it already?

**Comment by jason-simmons** [comment]
Planning to do this next after the libcxx migration lands (https://github.com/flutter/engine/pull/52773)

**Comment by chinmaygarde** [comment]
This is obsolete and a continuation of this has landed. Closing.

**Pull request closed without merging**
