### PR TITLE
Move //sky/compositor to //flow

### PR DESCRIPTION
**Pull request by abarth**
Now that the compositor doesn't have any tricky deps, we can make it a
top-level project, which saves a bunch of typing.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @chinmaygarde

**Comment by Hixie** [comment]
Why not //compositor? Is flow a term of art?

**Comment by Hixie** [comment]
RSLGTM though I find the new name unintuitive.

**Comment by abarth** [comment]
> Why not //compositor?

There are a bunch of things called compositors in the system.  If we call it "compositor" we'll have to distinguish between the "Flutter compositor" and the "Mojo compositor", etc.  Giving it a slightly fanciful name makes it easier to refer to unambiguously.

> Is flow a term of art?

Nope.  Just a snappy name.

**Comment by abarth** [comment]
I'm open to other suggestions that alliterate or rhyme with flutter.

**Comment by chinmaygarde** [comment]
> I'm open to other suggestions that alliterate or rhyme with flutter.

Nah, I think I will just go with the flow on this one. lgtm

**Comment by abarth** [comment]
We chatted it out in #flutter if you're worried that I just steamrolled over @Hixie :)

**Pull request merged**
