### PR TITLE
Roll dart to pick up new BoringSSL

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by zanderso** [comment]
@abarth @Hixie

**Comment by abarth** [comment]
LGTM

Thanks so much!!

**Comment by Hixie** [comment]
we should comment out my commenting out of the boringssl entry in the licenses script and rerun it

**Comment by zanderso** [comment]
It looks like I don't have commit permissions, so I'll need help landing this.

**Comment by Hixie** [comment]
landed

**Pull request merged**
