### PR TITLE
Set the CSS overflow-wrap property to enable line breaks within a word

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/162

### CODE REVIEW

**Comment by Hixie** [comment]
lgtm

**Comment by Hixie** [comment]
It would be great if you could separately add a test to the flutter framework that verifies that we don't regress this.

**Comment by eseidelGoogle** [comment]
Ahha!  So this just came as a result of our deleting the default style sheet?

**Comment by eseidelGoogle** [comment]
Previously many of the "initial style" defaults were not tested due to being overridden by the default stylesheet.

**Pull request merged**
