### PR TITLE
[Impeller] Fix the clip replay mechanism.

### PR DESCRIPTION
**Pull request by bdero**
Clips were being ignored whenever MSAA backdrop restores were being done by attachment load.

Unblocks the StC flag flip: https://github.com/flutter/engine/pull/50856

Note that the new Gaussian blur does not currently work on GLES, and it's expected that this will cause backdrop blurs to cut a transparent hole wherever the backdrop blur should render.

This happens because the gaussian blur renders as fully transparent black (among other things, it uses arrays of structs for the uniforms, which is unsupported in GLES). Then, the backdrop blur renders the blur's result with the `Source` blend mode, cutting out a hole in this case.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Do we have a test case (golden or otherwise) that will cover this?

**Comment by jonahwilliams** [comment]
basically, do we have a golden of this that was rendering incorrectly before but renders correctly now - perhaps on Metal/Vulkan backends too so its not just the broken gaussians on GLES?

**Comment by bdero** [comment]
I think this change only impacts GLES in practice, since `Picture::ToImage` and `EntityPass` shouldn't ever be creating non-MSAA pass textures on Metal/Vulkan. The large volume of Vulkan goldens I was getting towards the end of last week are a mystery... I wonder if they were leftovers from previous test runs/due to force pushing or something.

In terms of testing GLES: `AiksTest.DrawAdvancedBlendPartlyOffscreen/OpenGLES` starts rendering correctly with this change (unlike the backdrop blurs, which still render incorrectly, but differently).

**Comment by jonahwilliams** [comment]
Sounds good to me

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
