### PR TITLE
Raise an exception when converting a DartWrappable with empty native …

### PR DESCRIPTION
**Pull request by jason-simmons**
…fields

Fixes https://github.com/flutter/flutter/issues/2391

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by krisgiesing** [comment]
Does this disallow passing wrapped native objects that might naturally contain a null field?

**Comment by jason-simmons** [comment]
This checks the DartWrappable::kPeerIndex native field, which contains a pointer to the C++ object associated with this Dart object.
If that is null, then the DartWrappable is invalid.

(The C++ object and the Dart object themselves can contain anything)

**Comment by krisgiesing** [comment]
Cool, thanks for clarifying.

**Pull request merged**
