### PR TITLE
Flutter 1.20.3 engine cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Cherrypicks:

* Dart 2.9.2
  * [Commit b07da893](https://github.com/dart-lang/sdk/commit/b07da893600eadc4efafc5a54b8f9533e43c0034)
* App freezes when switching via task switcher on API 25 - Android 7.1.1
  * [Issue #64414](https://github.com/flutter/flutter/issues/64414)
  * [PR #20735](https://github.com/flutter/engine/pull/20735)
  * [`45f09403d897dcac63787071169be7cdc90cce7f`](https://github.com/flutter/engine/commit/45f09403d897dcac63787071169be7cdc90cce7f)
  * Author @blasten, original approver @jason-simmons 
* WebView is frozen in release mode with flutter 1.20.2 stable version
  * [Issue #64228](https://github.com/flutter/flutter/issues/64228)
  * [PR #20708](https://github.com/flutter/engine/pull/20708)
  * [`1c13abaab120d8d2d4c07e5b5fc75100f56a89e2`](https://github.com/flutter/engine/commit/1c13abaab120d8d2d4c07e5b5fc75100f56a89e2)
  * Author @cyanglaz, original approver @dnfield 
* Image performance regression
  * [Issue #63876](https://github.com/flutter/flutter/issues/63876)
  * [PR #20673](https://github.com/flutter/engine/pull/20673)
  * [`e09af86a26df0fc05ec727d72deb7ae9fc89f446`](https://github.com/flutter/engine/commit/e09af86a26df0fc05ec727d72deb7ae9fc89f446)
  * Author @jason-simmons, original approver @dnfield 
* Disabled the lint step (actually updated `lint.sh` to always exit 0) because it was enabled after the branch point https://flutter-review.googlesource.com/c/recipes/+/4561 (and presubmit still runs latest recipe https://github.com/flutter/flutter/issues/53371).

### CODE REVIEW

**Comment by christopherfujino** [comment]
@jason-simmons & @dnfield I actually got a merge conflict trying to cherry-pick [`e09af86a26df0fc05ec727d72deb7ae9fc89f446`](https://github.com/flutter/engine/commit/e09af86a26df0fc05ec727d72deb7ae9fc89f446). I might need help, but I'll put this on hold until Monday.

**Comment by christopherfujino** [comment]
@jason-simmons and @dnfield can you double-check my merge (that resolved a conflict) https://github.com/flutter/engine/pull/20838/commits/14864c30397c4e7c1643f98fff9a73c7e4ae2482#diff-36581c173eef0311bb48263255854c24, especially line 298?

**Comment by dnfield** [comment]
LGTM but needs a format.

**Comment by christopherfujino** [comment]
> LGTM but needs a format.

how do I do that? is it a specific line I can hand format?

**Comment by dnfield** [comment]
Sorry, it doesn't need a format, there's some failure about NNBD in the web UI code... Tried kicking the bot just in case but I'd ask about this on #hackers-nnbd

**Comment by christopherfujino** [comment]
> Sorry, it doesn't need a format, there's some failure about NNBD in the web UI code... Tried kicking the bot just in case but I'd ask about this on #hackers-nnbd

There's an open issue for this one: https://github.com/flutter/flutter/issues/63686

**Comment by christopherfujino** [comment]
@cyanglaz can I get an LGTM for the webview cherrypick?

**Comment by christopherfujino** [comment]
I will land this, as everything is green except `format_and_dart_test` which is a known failure on release branches https://github.com/flutter/flutter/issues/63686 and luci-engine which is irrelevant to a release branch.

**Comment by christopherfujino** [comment]
Post-submit, it is expected that Fuchsia will fail due to https://github.com/flutter/flutter/issues/64975. Ultimately, we would like to skip that test on release branches.

**Pull request merged**
