### PR TITLE
WIP: Override isFlipped on FlutterViewWrapper to be consistent with FlutterView

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/84490

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.
- [X] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Won't this break all of the accessibility layout?

**Comment by knopp** [comment]
> Won't this break all of the accessibility layout?

This is what `accessiblityChildren` on `FlutterViewWrapper` returns now:

```objc
- (NSArray*)accessibilityChildren {
  return @[ _flutterView ];
}
```

So I didn't think there was anything to break yet :) But assuming there are children in future (or maybe I'm just reading the code wrong), wouldn't it be easier to position them in flipped layout, just like everything else in flutter?

**Comment by chunhtai** [comment]
yes, this causes the accessibility layout to be flipped
sample code
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
          body: Scaffold(
              body: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      TextField(controller: TextEditingController(text: 'thisistext'),),
                      TextField(controller: TextEditingController(text: 'thisistext'),),
                      TextField(controller: TextEditingController(text: 'thisistext'),)
                    ],
                  )))),
    ),
  );
}
```
cmd+f5 to turn on voiceover, and uses control+option+shift down to go into the content and use control+option to navigate between the textfield.

It is weird the nativeshell hardcoded the rect based on view is flipped. @stuartmorgan do we promise the view is always flipped or not?

**Comment by knopp** [comment]
My bad, I was reading the code wrong it seems. The accessibility code was added just two weeks ago so I missed it. It seems that `FlutterTextPlatformNode::GetFrame` flips the Y coordinate. I'm wondering if it wouldn't be easier to just override `isFlipped` on `FlutterViewWrapper` instead.

I don't think Flutter makes any public guarantees about `FlutterViewController.view isFlipped`. It's just that `isFlipped` is the sane thing to do. I can update the PR to flip the accessibility tree, but if you want to keep `FlutterViewWrapper` without `isFlipped`, I'll happily accept that and wrap the flutter view in another view, it just that it seems a bit redundant.

**Comment by stuartmorgan** [comment]
> @stuartmorgan do we promise the view is always flipped or not?

We don't. It's never been documented, and if someone wants a guarantee off this behavior going forward it would need a customer test.

I don't think that the argument in the bug that this must be done since the view used to be flipped is sufficient on its own, although I can see that not breaking clients who have been (incorrectly, IMO) relying it is better than not, all other things being equal, even if it doesn't meet the Flutter breaking change policy requirements.

> It's just that `isFlipped` is the sane thing to do.

It depends on whether everything we want to position in it has coordinates that are coming from Flutter. In general, using flipped coordinates only makes sense when the content is itself flipped, which is true of the Flutter view itself, but not the wrapper. It may be easier to maintain with flipped coordinates since we do have other Flutter-sources coordinates, or it may be more confusing because it's inconsistent with what people expect from Cocoa.

@cbracken should make the final call; I can see arguments either way.

**Comment by knopp** [comment]
> although I can see that not breaking clients who have been (incorrectly, IMO) relying it is 

The thing is - I've been relying on isFlipped behavior without even realizing that. 

For example here's showing popup menu:

```objc
[menu popUpMenuPositioningItem:nil atLocation:<location_from_flutter> inView:<flutter_view]
```

This used to just work as long as FlutterView was [isFlipped true]. 

It would be really nice if we could at least guarantee isFlipped value. Either way (flipped or not)  is fine for me. Flipping the coordinates is still less work than having to wrap flutter view in another view just to be able to show a menu.

**Comment by chunhtai** [comment]
> > although I can see that not breaking clients who have been (incorrectly, IMO) relying it is
> 
> The thing is - I've been relying on isFlipped behavior without even realizing that.
> 
> For example here's showing popup menu:
> 
> ```objc
> [menu popUpMenuPositioningItem:nil atLocation:<location_from_flutter> inView:<flutter_view]
> ```
> 
> This used to just work as long as FlutterView was [isFlipped true].
> 
> It would be really nice if we could at least guarantee isFlipped value. Either way (flipped or not) is fine for me. Flipping the coordinates is still less work than having to wrap flutter view in another view just to be able to show a menu.

Ideally, the code should be adaptive, it should work whether or not the view is flipped. In case we flips it again in the future.

**Comment by knopp** [comment]
> Ideally, the code should be adaptive, it should work whether or not the view is flipped. In case we flips it again in the future.

That's a good point. I guess I'll just flip the coordinates if !`[view isFlipped]`.

**Comment by knopp** [comment]
I'm closing this PR. I think my original assumption was wrong and the proper solution here is to make my code work correctly regardless of whether flutterView isFlipped is true or not.

**Pull request closed without merging**
