### PR TITLE
Return null in Future<WebSocketChannel>.catchError handler

### PR DESCRIPTION
**Pull request by srawlins**
## Description

A `Future<T>.catchError`'s `onError` handler should be a function which returns `FutureOr<T>`. This has not been statically verified because the type signature of `onError` cannot be expressed. The analyzer will soon start reporting this as an error, as part of https://github.com/dart-lang/sdk/issues/35825.

In the code below, a `return;` statement is found in an `onError` handler for a `Future<WebSocketChannel>`.

## Tests

I added no tests:

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by srawlins** [comment]
🙌 

Is the CI failure unrelated? It is unfamiliar to me.

**Comment by yjbanov** [comment]
It looks unrelated but the failed code is too close to the code that's changed in this PR. Would you mind rebasing the PR to kick off another build?

Filed https://github.com/flutter/flutter/issues/73601 to look into this later. I've never seen this error.

**Comment by srawlins** [comment]
Rebased, but I cannot see what the error is in the logs...

**Comment by yjbanov** [comment]
I'm checking if other PRs are affected right now. The error is:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8860791064884473328/+/steps/felt_ios-safari_test/0/stdout

```
Unhandled exception:
Exception: Error getting requested simulator. Try running `felt create` command first before running the tests. Exception: Exception: Requested simulator version iOS 13.0 is not available.
#0      IosSafariArgParser.initIosSimulator (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/safari_installation.dart:106:7)
<asynchronous suspension>
#1      TestCommand._prepare (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:224:7)
<asynchronous suspension>
#2      TestCommand.runUnitTests (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:191:5)
<asynchronous suspension>
#3      TestCommand.run (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:164:18)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/felt.dart:39:26)
<asynchronous suspension>
```

**Comment by yjbanov** [comment]
Looked at a few PRs and none are failing in the same way. I'm going to patch in your change and try it locally.

**Comment by yjbanov** [comment]
Ok, so I was able to reproduce this error without your change (sorry, took me a while to restore my engine dev environment on my laptop). In my case, I didn't have iOS 13.0 simulator installed. After I installed it everything worked.

Perhaps what's happening is one of our macOS machines is missing iOS 13.0 simulator, although that doesn't explain why your PR specifically is failing and so consistently too.

I'd say let's merge your PR, and if it causes trouble we'll revert it.

**Comment by srawlins** [comment]
Excellent @yjbanov would you mind merging? Thanks!

**Comment by yjbanov** [comment]
The engine team is fighting some fires right now. To avoid making the situation worse, I'll wait for engine sheriff's green light before landing.

**Comment by srawlins** [comment]
Thanks much!

**Pull request merged**
