### PR TITLE
Reland enable DisplayList by default

### PR DESCRIPTION
**Pull request by flar**

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by gw280** [comment]
I'm a little out of the loop, but how confident are we in the test coverage for this?

**Comment by chinmaygarde** [comment]
> but how confident are we in the test coverage for this?

I am adequately confident with the coverage in https://github.com/flutter/engine/pull/26928. This was also attempted once before and findings have been incorporated into fixes in the engine.

**Comment by flar** [comment]
I think it has survived the engine post-submit tests and the framework roll, except that I think there is an outstanding issue with the framework tests were the SVG tests do some golden tests that require exact results and we end up with some +/-1 errors. I was asking @dnfield about adjusting those SVG golden tests to have a build-in epsilon for comparison, but I don't think that conversation was resolved.

**Comment by dnfield** [comment]
In the past what we've done is just update the goldens in flutter_svg - is there some reason we can't do that now?

**Comment by flar** [comment]
> In the past what we've done is just update the goldens in flutter_svg - is there some reason we can't do that now?

If this were guaranteed to stick all the way up the pipeline then we might do that, but we may eventually perform similar optimizations as SkPicture used to do and so the rendering may fluctuate even if this PR does stick. Expect some volatility here over the next few weeks.

**Comment by flar** [comment]
@dnfield https://github.com/dnfield/flutter_svg/pull/575

**Comment by flar** [comment]
Waiting to land: https://github.com/flutter/tests/pull/116

**Pull request merged**
