### PR TITLE
Remove sky_services, flutter_services

### PR DESCRIPTION
**Pull request by dnfield**
These packages are unused, and flutter_services even has a TODO to remove it.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: only removes code

**Comment by zanderso** [comment]
Looks like the GN files need some formatting. Did the pre-push hook not stop the upload?

**Comment by dnfield** [comment]
I might have skipped it :(

**Comment by dnfield** [comment]
This needs a recipe change - created https://flutter-review.googlesource.com/c/recipes/+/15240

**Pull request merged**
