### PR TITLE
[Impeller] Vertices support for color sources

### PR DESCRIPTION
**Pull request by jonahwilliams**
Allow ColorSource contents to accept either a Path or a Vertices object. Update VertexBuilder to accept specified indices instead of always generating them. Update drawVertices to check for a color_source proc and conditionally use this.

Doesn't cover texture coordinates for image shaders.

See https://github.com/flutter/flutter/issues/104757
See https://github.com/flutter/flutter/issues/109956

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This isn't quite ready. We actually still need to handle blending of colors in the shader, which means we may need specialized gradient shaders for vertices instead

**Comment by bdero** [comment]
Cool! I have a half baked design doc that aims to fix up this situation if you're interested in taking a swing at solving this more generally: https://docs.google.com/document/d/1t-dzzi04nCdkIReoJp8ZyGNskqIip1TG3WhGEz7Osd8/edit#

I'm currently dumping the rest of my notes in the "Proposed Design" section to make the ideas clearer/more complete.

**Comment by jonahwilliams** [comment]
Awesome, I will take a look at that

**Comment by jonahwilliams** [comment]
I'm going to close this and follow along in the document

**Pull request closed without merging**
