### PR TITLE
Cast ::GetLastError to int

### PR DESCRIPTION
**Pull request by bryanoltman**
`GetLastError` returns an unsigned 32 bit integer that was being implicitly cast to an int for the std::variant<..., int>. This was causing my build to fail with:

```
../../flutter/shell/platform/windows/platform_handler.cc(178,12): error: no viable conversion from returned value of type 'DWORD' (aka 'unsigned long') to function return type 'std::variant<std::wstring, int>' (aka 'variant<basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t>>, int>')
  178 |     return ::GetLastError();
      |            ^~~~~~~~~~~~~~~~
../../../../../../../Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.42.34433/include\variant(923,7): note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'DWORD' (aka 'unsigned long') to 'const variant<basic_string<wchar_t>, int> &' for 1st argument
  923 | class variant : private _SMF_control<_Variant_destroy_layer<_Types...>, _Types...> { // discriminated union
      |       ^~~~~~~
```

Commands:

```
 ./flutter/tools/gn --runtime-mode release --no-rbe
ninja -C .\out\host_release windows gen_snapshot flutter/build/archives:windows_flutter
```

Explicitly casting `::GetLastError` to an int fixes this issue.

I'm running on Windows 11 (Version 10.0.26100 Build 26100) with VS 2022 Community Edition.

@loic-sharma

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]
LGTM

**Comment by loic-sharma** [comment]
I requested a [test exemption](https://discord.com/channels/608014603317936148/608018585025118217/1316469778344316999).

**Comment by eseidel** [comment]
@bryanoltman do you have merge permission or did you want Loic or I to press ze button?

**Comment by bryanoltman** [comment]
@eseidel I do not have permissions, so be my guest 😄

**Comment by eseidel** [comment]
Checks have passed and you have lgtm, so merging.  Hopefully I'm still doing this correctly. 🤞

**Comment by stuartmorgan** [comment]
test-exempt: code refactor with no semantic change

@eseidel Please don't land PRs that need a test exemption without them having a test exemption.

**Comment by eseidel** [comment]
Apologies, my bad. Checks passed so I assumed it was clear. (I assumed something like that would have been a check.)

**Pull request merged**
