### PR TITLE
Flutter should not stop registering unregistered plugins in case of an error registering a plugin

### PR DESCRIPTION
**Pull request by ekasetiawans**
## Description

When a plugin fails to register with a FlutterEngine it will cause unregistered plugins not to be registered because GeneratedPluginRegistrant.registerWith throws an error and stops the plugin registration process.

## Related Issues

https://github.com/flutter/flutter/issues/65525

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A
change in behaviour with no test covering it will likely get reverted
accidentally sooner or later. PRs must include tests for all
changed/updated/fixed behaviors. See [testing the engine] for instructions on
writing and running engine tests.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [ ] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by ekasetiawans** [comment]
@googlebot I signed it!

**Review by cbracken — CHANGES_REQUESTED** [review]
Can you provide more details on a scenario in which you'd want to continue plugin registration/app startup rather than failing immediately with an error?

I'd imagine most app developers will want to know immediately if there are issues with the plugins they intend to register so that they can correct those issues as quickly as possible.

/cc @amirh for his thoughts since he'll have the most context here.

**Comment by ekasetiawans** [comment]
As we know that plugins are registered to FlutterEngine using reflection which is executed when we create instances of FlutterEngine. However, flutter doesn't limit that FlutterEngine is created for FlutterActivity only. 

We can create instances of FlutterEngine on a Broadcast Receiver, Service, etc. that are not instances of FlutterActivity. 
Some plugins when added to FlutterPluginRegistrant via GeneratedPluginRegistrant may fail. For example, when registering the plugin requires an Activity, it can get an error if a FlutterEngine is created on a Service. When this error occurs, the entire process in GeneratedPluginRegistrant.registerWith () fails and plugins that have not been registered will not be registered. 

The important point that is my target is, flutter must still register plugins that have not been registered in the order in GeneratedPluginRegistrant even though there has been a failure registering one of the plugins. 

I think this could be unfair to the other plugins, because the other plugins became unusable just because of an error in one of the plugins.

**Comment by ekasetiawans** [comment]
https://github.com/ekasetiawans/flutter_plugin_issue.git

this is a simple project I created to reproduce this issue. I created instances from FlutterEngine in the Application class (we can also make it on the Service class, Broadcast Receiver, etc).

The FlutterEngine that I created is intended to execute dart code using a specific entrypoint. In this case the dart code I want to execute has nothing to do with the UI.

Then we look at the GeneratedPluginRegistrant.java class, where there is a sequence of plugin registration processes. First is flutter_bluetooth_basic then next is shared_preferences.

Then we can see in main.dart, there is a startExample () method that is the method I will make as the entrypoint for the FlutterEngine instance.

In the startExample () method, I only want to use the SharedPreferences plugin. However, because the GeneratedPluginRegistrant process encountered an error while registering flutter_bluetooth_basic, the SharedPreferences plugin is not registered with FlutterEngine and this causes a MissingPluginException.

**Comment by ekasetiawans** [comment]
After I did some more research on plugin registration, I found that plugins are registered to FlutterEngine based on the plugin name order, https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/plugins.dart. 

So I can conclude that if we use plugins A, B, C, and D and then a problem occurs when plugin B is registered, plugins B, C and D cannot be used.

**Comment by dnfield** [comment]
Should we instead avoid using reflection to instantiate plugins, and have developers explicitly provide a list of plugins to register for a specific engine?

**Comment by cbracken** [comment]
@dnfield that seems pretty reasonable. Allow the developer to specify a list explicitly and if they don't, fall back on the current behaviour.

**Comment by ekasetiawans** [comment]
@dnfield yes i agree, that would make more sense.

**Review by ekasetiawans — COMMENTED** [review]
Plugins registered to the flutter engine are sorted by the package name of the plugins. 
Since the plugin is registered using reflection on the GeneratedPluginRegistrant there may be a failure during the registration process. 

For example, if we use the `shared_preferences` and `flutter_bluetooth_basic plugins`, then `flutter_bluetooth_basic` will be registered first before `shared_preferences`. 

However, if `flutter_bluetooth_basic` fails while registering, for example when `FlutterEngine` is created outside of `FlutterActivity` for isolated purposes, `shared_preferences` cannot be used because it is not registered to the `FlutterEngine`.

Many developers get confused when adding a plugin which turns out to cause other plugins to no longer be used, and there is no explanation which plugin caused the failure.

**Comment by dnfield** [comment]
This pull request only addresses the v1 embedding, and will not change anything for the v2 embedding. But in the v2 embedding, there are constructors that allow you to control whether the FlutterEngine class automatically registers plugins.

Given that the v1 embedding is currently being deprecated, I think we should probably not take this fix.

**Comment by dnfield** [comment]
> However, if `flutter_bluetooth_basic` fails while registering, for example when `FlutterEngine` is created outside of `FlutterActivity` for isolated purposes, `shared_preferences` cannot be used because it is not registered to the `FlutterEngine`.

In that case, you should use the constructor on `FlutterEngine` that says to not register plugins.

> This change will keep plugins usable except for plugins that have failed. But we have also provided logs to tell which plugins cannot be used.

We should probably update the code in `FlutterEngine.java` rather than here, because in this case there's no way to fix it and we're recommending people get away from this embedding anyway. But if we can add instructive logs about how to avoid registering plugins in a background isolate that would be good.

**Comment by ekasetiawans** [comment]
> This pull request only addresses the v1 embedding, and will not change anything for the v2 embedding. But in the v2 embedding, there are constructors that allow you to control whether the FlutterEngine class automatically registers plugins.
> 
> Given that the v1 embedding is currently being deprecated, I think we should probably not take this fix.

That means we have to tell the plugin developer to immediately upgrade to embedding v2 because staying in v1 will potentially render other plugins unusable.

**Comment by ekasetiawans** [comment]
> > However, if `flutter_bluetooth_basic` fails while registering, for example when `FlutterEngine` is created outside of `FlutterActivity` for isolated purposes, `shared_preferences` cannot be used because it is not registered to the `FlutterEngine`.
> 
> In that case, you should use the constructor on `FlutterEngine` that says to not register plugins.
> 
> > This change will keep plugins usable except for plugins that have failed. But we have also provided logs to tell which plugins cannot be used.
> 
> We should probably update the code in `FlutterEngine.java` rather than here, because in this case there's no way to fix it and we're recommending people get away from this embedding anyway. But if we can add instructive logs about how to avoid registering plugins in a background isolate that would be good.

In my opinion, giving a false value to registerPluginsAutomatically in the FlutterEngine constructor is not quite right, because developers have to manually register the plugin to be used and that makes it more difficult for developers because at least they have to be quite familiar with the native programming language.

**Comment by dnfield** [comment]
Plugins do not have to migrate, applications do.

Using plugins in a background isolate is a more advanced feature. It is not particularly well supported right now.

I think that a developer would be _more_ surprised to find that a plugin is just completely unavailable than that they have to write some Java or Kotlin code to do it. Either way, I don't think just continuing on and waiting for some later failure when they try to access the plugin in Dart code is going to be much help here.

**Comment by ekasetiawans** [comment]
I've created a `flutter_background_service` plugin to run dart code behind the scenes, my FlutterEngine runs inside the Service class. So far the dart code has been running successfully without the UI and without having to create an instance of the Application class to run FlutterEngine. But at this point I am having a problem with this issue, because if a developer uses a plugin that hasn't been upgraded to v2 and it crashes, then the dart code can't use a plugin that hasn't been registered.

I think, by continuing with plugin registration, at least the dart code can still use other plugins that do not fail during registration. It is also very helpful for plugins that are not related to the UI such as firebase_messaging to handle background messages, if the callback wants to use third party plugins too.

**Pull request closed without merging**
