### PR TITLE
Rename GPU to raster thread in PerformanceOverlay

### PR DESCRIPTION
**Pull request by liyuqian**
For https://github.com/flutter/flutter/issues/29443.

This changes the only user-faced UI where "GPU thread" would appear.

We'll later change all the reference of GPU thread in the engine code, document, and trace later.

### CODE REVIEW

**Comment by liyuqian** [comment]
@cbracken : please check the doc here: https://docs.google.com/document/d/1iYLpozHB7zkoi3JIki3htRD7YL3pTNyCROHJJ8XLqM0/edit

I tend to do this rename in piece meals so we don't get a lot of merge conflicts. Please let me know if you'd like a giant engine commit that changes everything that I can find at once.

**Comment by chinmaygarde** [comment]
> I'm not sure how we want to approach constants that are part of the embedder API such as kFlutterNativeThreadTypeRender, similar for when we get to the UI thread.

We can keep them as-is for now. If we are really antsy about that terminology, we could probably add an alias at the end of the enum.

**Comment by liyuqian** [comment]
@dnfield @iskakaushik : I started retrying "Linux Fuchsia" from https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/5800. Is that the right way to retry a possibly flaky build in LUCI?

**Comment by dnfield** [comment]
It won't get updated in the GitHub UI.  Just manually merge it once the retry passes.

**Comment by liyuqian** [comment]
@dnfield : in that case, I'll miss your auto-merge bot very much!

**Comment by dnfield** [comment]
The real fix is to make the thing that runs the LUCI checks check for retries.  /cc @digiter @keyonghan @godofredoc

**Pull request merged**
