### PR TITLE
Fix memory leaks in FlTextInputPlugin

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

This PR fixes a few small memory leaks in FlTextInputPlugin. All three cases
are creating temporary FlValue instances for lookups and comparison without
ever releasing them.

## Related Issues

\-

## Tests

I updated the following tests:

StringEqual and StringNotEqual in fl_value_test.cc.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by robert-ancell — CHANGES_REQUESTED** [review]
Thanks for fixing the `fl_value_lookup` - they are definitely bugs.

The `fl_value_equal_string` is not as clear if this is an improvement. The issue is if we add a `fl_value_equal_string` then we really need to add a `fl_value_equal_int` etc. In this case the code should probably be more like:
```c
if (fl_value_get_type(input_type_name) == FL_VALUE_STRING && g_strcmp0(fl_value_get_string(input_type_name), kMultilineInputType) == 0) {
  // ...
}
```

Can you please just make this PR do the `lookup` -> `lookup_string` changes and make a second PR if you still think adding the new API is useful?

**Review by cbracken — APPROVED** [review]
Thanks for the fix and quick turnaround on the review comments!

LGTM; will wait for @robert-ancell to approve as the primary maintainer.

**Review by robert-ancell — APPROVED** [review]
Thanks @jpnurmi!

**Comment by robert-ancell** [comment]
Might need to be merged with master to fix the unrelated build failure?

**Pull request merged**
