### PR TITLE
[CP] Runtime effect clip fix

### PR DESCRIPTION
**Pull request by jonahwilliams**
Cherry pick for https://github.com/flutter/flutter/issues/127123

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
It looks like the includes in the unit test file need some adjustment.

**Comment by ricardoamador** [comment]
Can anyone who has write access to this branch add the 'autosubmit' label please?

**Review by XilaiZhang — APPROVED** [review]
images (1)

**Comment by itsjustkevin** [comment]
@ricardoamador are we still using this cherry-pick to test auto-submit?

**Comment by ricardoamador** [comment]
@itsjustkevin one more try then you can merge it. I don't want to hold you up.

**Comment by ricardoamador** [comment]
Sorry go ahead and merge this if you need to @itsjustkevin. My version of autosubmit is not longer taking traffic due to the newest deployment. I can redeploy and look for a different cp.

**Pull request merged**
