### PR TITLE
iOS: Implementation of ::activity::Activity from activity.mojom

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by abarth** [comment]
It seems wrong to implement Activity on iOS.  We probably want to form an abstraction that makes sense both on Android and iOS...

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/game/issues/46

**Comment by chinmaygarde** [comment]
@abarth I agree. I was hoping this would be a stopgap measure to help get the game out the door. But the longer we avoid the change, the more painful it becomes.

**Comment by chinmaygarde** [comment]
I will draft a .mojom with a more sensible abstraction. Go/no-go on this stopgap?

**Comment by abarth** [comment]
LGTM as a stopgap

**Comment by chinmaygarde** [comment]
Will do https://github.com/flutter/flutter/issues/1420

**Pull request merged**
