### PR TITLE
[Impeller] Add explicit color filter types to Aiks.

### PR DESCRIPTION
**Pull request by bdero**
Part of https://github.com/flutter/flutter/issues/127232.

Adds an explicit ColorFilter concept to Aiks which wraps the GPU and CPU implementations. We're not using the CPU implementations yet, but I'll be getting it wired up in a follow-up patch.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
IIRC the last time we tried to land something like this all of the rendering broke in the gallery. Did we ever root cause that? 

The change itself LGTM

**Comment by bdero** [comment]
Hmm, I don't recall landing something like this. Might you be referring to one of my previously failed ColorSource refactors that I had to roll back due to CPU benchmark regressions? I wound up taking a different approach for that in the end.

In terms of avoiding fidelity regressions I think we've been doing pretty well now that we have a lot of stuff covered by goldens.

**Comment by jonahwilliams** [comment]
I'm thinking of this one: https://github.com/flutter/engine/pull/37677

**Comment by jonahwilliams** [comment]
I guess that was color sources and not filters.

**Pull request merged**
