### PR TITLE
Remove doc comments in copied web interfaces

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This removes the doc comments in the copied web interfaces so that they don't need to be kept in sync with the main files that they are a copy of. The doc comments in these files are ignored by dartdoc for the website doc generation, and because these are forks of the ones in `lib/ui`, they are constantly out of date.

## Tests
 - Just removing comments: no tests needed.

### CODE REVIEW

**Comment by yjbanov** [comment]
See also https://github.com/flutter/engine/pull/19815. I wanted to remove these too, but turns out they are useful to some team members.

/cc @ferhatb @nturgut @hterkelsen @mdebbar @ditman

**Comment by ditman** [comment]
I rarely touch the engine package nowadays, so I don't have a strong opinion on these comments leaving or staying :)

**Comment by gspencergoog** [comment]
For those who think these are useful: in what context are they useful, and what kinds of comments are useful here?

Because if these really are useful comments, then we should be making sure that they are maintained and correct with respect to the matching published docs, which I think is error prone, and unlikely to actually happen unless they appear on a web site that people use. Having out of date/incorrect docs is usually worse than having no docs at all, which is why I put together this PR.

Would it be sufficient to have the docs just point to the file that contains the published, maintained docs for the interface?

**Comment by ferhatb** [comment]
> For those who think these are useful: in what context are they useful, and what kinds of comments are useful here?
> 
> Because if these really are useful comments, then we should be making sure that they are maintained and correct with respect to the matching published docs, which I think is error prone, and unlikely to actually happen unless they appear on a web site that people use. Having out of date/incorrect docs is usually worse than having no docs at all, which is why I put together this PR.
> 
> Would it be sufficient to have the docs just point to the file that contains the published, maintained docs for the interface?

Contributors to web engine will loose docs in IDEs. Out of sync is as bad as not having them and since multiple team members requested this approving.

**Pull request merged**
