### PR TITLE
Roll Dart to da1f52592ef73fe3afa485385cb995b9aec0181a

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by zanderso** [comment]
I'll do the next roll since I am around this week.

**Comment by crelier** [comment]
Thanks! I can do the next one when I am back on Monday.

Regis

**Comment by Hixie** [comment]
Looks like this regressed the aot_snapshot_size_vmisolate benchmarks (though weirdly not the release_size_bytes benchmarks).

**Comment by rmacnak-google** [comment]
@ErikCorryGoogle 

dart-lang/sdk@42e2a555bed42e09a8bce2353c29e773b00ad720 probably decreased the load factor on the symbol table

**Comment by jason-simmons** [comment]
VMIsolate size increased by about 1KB, which isn't noticeable in the total release_size_bytes

**Comment by Hixie** [comment]
Ok. I'll rebaseline the benchmarks.

**Pull request merged**
