### PR TITLE
Roll ICU to 62.1 and harfbuzz to 1.8.4

### PR DESCRIPTION
**Pull request by goderbauer**
This will enable us to switch to the new minimal ICU data configuration in a follow-up PR.

### CODE REVIEW

**Comment by goderbauer** [comment]
There is still one remaining error with the license, which I do not know how to fix yet:

```
error searching for copyright in: ../../../third_party/harfbuzz/util/hb-fc-list.c
unmatched potential copyright and license statements; first twenty lines:
----8<----
/*
 * Copyright © 2002 Keith Packard
 * Copyright © 2014  Google, Inc.
 *
 * Permission to use, copy, modify, distribute, and sell this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the name of the author(s) not be used in
 * advertising or publicity pertaining to distribution of the software without
 * specific, written prior permission.  The authors make no
 * representations about the suitability of this software for any purpose.  It
 * is provided "as is" without express or implied warranty.
 *
 * THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
 * EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
----8<----
```

**Comment by goderbauer** [comment]
License script has been fixed.

**Comment by goderbauer** [comment]
@Hixie Can you review the changes to the script? Thanks.

**Comment by najeira** [comment]
I think this is the cause of https://github.com/flutter/flutter/issues/22417

**Pull request merged**
