### PR TITLE
Fix janks caused by await vsync in classical Flutter

### PR DESCRIPTION
**Pull request by fzyzcjy**
1. I will finish code details, refine code, add tests, make tests pass, etc, after a code review that thinks the *rough idea* is acceptable. It is because, from my past experience, reviews may request changing a lot. If the general idea is to be changed, all detailed implementation efforts are wasted :)
2. The PR has an already-working counterpart, and it produces ~60FPS smooth experimental results. The benchmark results and detailed analysis is in chapter https://cjycode.com/flutter_smooth/benchmark/. All the source code is in  https://github.com/fzyzcjy/engine/tree/flutter-smooth and https://github.com/fzyzcjy/flutter/tree/flutter-smooth.
3. Possibly useful as a context to this PR, there is a whole chapter discussing the internals - how flutter_smooth is implemented. (Link: https://cjycode.com/flutter_smooth/design/)

---

*This fixes the jank happened in **classical** Flutter, even without the existence of flutter_smooth*

*I will add tests and refine code etc after some code review - since review may request changing the code :)*

*This works pretty well in flutter_smooth, see https://github.com/fzyzcjy/engine/blob/flutter-smooth/shell/common/animator.cc for full code.*

During experiments, I observe a phenomenon: Even when the UI thread finishes everything *before* the deadline (vsync) a few milliseconds, the next frame is scheduled *one* vsync later, causing one jank. For example, UI thread may run from 0-15ms, but the next frame starts from 33.33ms instead of the correct 16.67ms.

An example screenshot can be seen at the end of this proposal. I added a timeline event, `Animator::AwaitVSync`, so we can clearly see when vsync await is called. (This screenshot has roughly 3ms space; but more frequently, I see this bug when there is about 0.5-2ms space.)

Therefore, this PR tries to fix this problem. The main idea is that, when detecting we are very near the next vsync, we do not wait at all, but instead directly start the next frame.

image

zoom in:

image

further zoom in:

image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests. -- see above
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by dnfield** [comment]
This seems very similar to https://github.com/flutter/engine/pull/29276

Similar concerns as to that one: we need some motivating benchmarks that clearly show what benefits would be gained here, and we need to see that changes to this won't negatively impact existing benchmarks/users.

**Comment by fzyzcjy** [comment]
Thanks for pointing out the related PR.

> Similar concerns as to that one: we need some motivating benchmarks that clearly show what benefits would be gained here, and we need to see that changes to this won't negatively impact existing benchmarks/users.

Sure. I will try to make one.

**Comment by fzyzcjy** [comment]
Thanks for pointing out the related PR.

> Similar concerns as to that one: we need some motivating benchmarks that clearly show what benefits would be gained here, and we need to see that changes to this won't negatively impact existing benchmarks/users.

Sure. I will try to make one.

> we need to see that changes to this won't negatively impact existing benchmarks/users.

May I know how to do this? does not see benchmark data on CI IMHO

**Comment by dnfield** [comment]
flutter-flutter-perf.skia.org and flutter-engine-perf.skia.org has benchmark data

**Comment by fzyzcjy** [comment]
@dnfield Thanks, may I know some doc, or how to see perf benchmark of a PR? Click "help" gives http://go/perf-user-doc which cannot be opened (google internal only?)

**Comment by fzyzcjy** [comment]
@dnfield 

## Reproduction

### Setup and analysis

In the benchmark, I deliberately make a dead loop to mimic the case when ui thread runs for smaller than but very close to 16.67ms. This is quite hacky and may not work on your device, so please modify the hardcoded time in the code if you cannot reproduce it. But hopefully this is ok as a "motivating" benchmark you mentioned :)

I also realize this seems hard to reproduce if the await vsync is called per 16ms. Instead, when I make ui thread deliberately janky (e.g. ~100ms), so that await vsync is not called for ~100ms, this is reproduced. Not sure why, but anyway regardless of why this happens, the PR can solve it.

In the screenshots below, I add red vertical lines manually by mimicking the `VSYNC` interval (this is the correct interval that I have fixed previously, so can use it). As we can see, the AwaitVsync is called *before* the vsync (which is imaginary and not shown in figure), but we miss it for a whole 16.67ms.

### Data

Code: https://github.com/fzyzcjy/flutter/tree/feat/await-vsync-directly-call
Run it: `/path/to/flutter drive --profile -t test_driver/run_app.dart --driver test_driver/near_full_tim_perf_test.dart`

Sample result timeline json: 
[near_full_time_perf.timeline.json.zip](https://github.com/fzyzcjy/flutter_smooth/files/9942874/near_full_time_perf.timeline.json.zip)

Sample screenshot:

image
image

**Comment by fzyzcjy** [comment]
> @dnfield and we need to see that changes to this won't negatively impact existing benchmarks/users

Could you please give some hints? I guess I have no permission to execute skia perf as it seems only run on master or other flutter branches. Thus, maybe I can do nothing except for creating a PR and see skia perf after it is merged...

**Pull request closed without merging**
