### PR TITLE
Fix Mac build error due to -Wsign-compare.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Innocent question: Can we add this warning to our linux builds as well? to have one true set of build flags? :D

**Comment by abarth** [comment]
Looks like its part of -Wall in gcc.  Not sure why we wouldn't have that set...

**Pull request merged**
