### PR TITLE
iOS: Always regenerate the precompilation snapshot when building for the device

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
So this is again a partial fix.  We're now in slow-but-correct mode always for ios, correct?

**Comment by chinmaygarde** [comment]
Correct. It is not easy to detect if any of the dart source files have changed (especially when dependencies have path overrides). So we always rebuild.

**Comment by eseidelGoogle** [comment]
OK.  Seems like we should just always call `flutter build` and maybe it should do the dependency checking if possible.  lgtm

**Comment by chinmaygarde** [comment]
I like having the dependency tracking at the flutter tools level. Reproducing the logic in Xcode build scripts is awkward since it does not have references to all the dart sources

**Pull request merged**
