### PR TITLE
Cherry-pick Avoid animation jank by setting FlutterViewController backgroundColor to clearColor

### PR DESCRIPTION
**Pull request by jmagman**
Cherry-pick of https://github.com/flutter/engine/pull/39359 by @luckysmg.

https://github.com/flutter/flutter/issues/120130

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Test failures are due to https://github.com/flutter/flutter/issues/120093, which hasn't been cherry-picked to the release candidate branch yet.

**Comment by godofredoc** [comment]
> @jonahwilliams can you please rebase this change? it will help to pass all the presubmit checks.

Oops sorry I meant @jmagman

**Comment by jmagman** [comment]
> can you please rebase this change? it will help to pass all the presubmit checks.

Done!

**Comment by jmagman** [comment]
@godofredoc should I merge this or will the release team do it?

**Pull request merged**
