### PR TITLE
Revert "Apply dpr transform to fuchsia accessibility bridge"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#21364

Build failure on Fuchsia

```
../../flutter/shell/platform/fuchsia/flutter/accessibility_bridge_unittest.cc:144:67: error: too few arguments to function call, expected 2, have 1
  accessibility_bridge_->AddSemanticsNodeUpdate(std::move(updates));
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ^
../../flutter/shell/platform/fuchsia/flutter/accessibility_bridge.h:85:3: note: 'AddSemanticsNodeUpdate' declared here
  void AddSemanticsNodeUpdate(const flutter::SemanticsNodeUpdates update,
  ^
1 error generated.
```

### CODE REVIEW

**Comment by zanderso** [comment]
Landing immediately to fix the build. /cc @chunhtai

**Comment by zanderso** [comment]
@dnfield @arbreng

**Comment by zanderso** [comment]
Maybe the presubmit checks were invalidated by a breaking change in a Fuchsia SDK roll?

**Comment by chunhtai** [comment]
oops, it was a bad merge, thanks for revert

**Comment by dnfield** [comment]
LGTM

**Pull request merged**
