### PR TITLE
Path metrics/getBounds/combinations again

### PR DESCRIPTION
**Pull request by dnfield**
#4799 caused the build bots to fail after being merged and was reverted in #.

I've made the following changes:

1. Explicitly declare value as `SkScalar` to avoid MSVC giving warning that's treated as an error
2. Import `'dart:collection' as collection` in `window_hooks_integration_test.dart` to ensure the updated `painting.dart` will compile properly.
3. (Unrelated to failure): use `closeTo` instead of the `moreOrLessEquals` `Matcher` that I ripped out of flutter_test_library.  `closeTo` is already built in to test and does the same thing in this context.

I have validated that the tests all pass now.  I've also validated a Win32 MSVC build on a Windows machine after this change (it failed before the most recent commit).

### CODE REVIEW

**Comment by Hixie** [comment]
RSLGTM

**Comment by eseidelGoogle** [comment]
We had a ton of stuff land last week all in combination which lead to some instability in our latest couple dev releases.  We're sorting that out right now to make sure `dev` gets back on track before we change `master` too much more.  After we sort that out (hopefully today/tomorrow?) we'll make sure this gets landed!  Thanks for the patch and sorry for the delay!

**Comment by Hixie** [comment]
I have landed it! Hopefully the bots pass! Thanks again for your contribution!

**Comment by Hixie** [comment]
Bots look good!

**Comment by Hixie** [comment]
This will roll into the framework next time we roll the engine (shouldn't be long).

**Pull request merged**
