### PR TITLE
Add the `scenario_app` `'solid_blue'` golden to the Android test suite

### PR DESCRIPTION
**Pull request by matanlurey**
This test is already running in the iOS scenario app:

DrawSolidBlueScreenTest

It should help debug https://github.com/flutter/flutter/issues/143602 by showing if the Android UI is bleeding.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

what does this look like locally?

**Review by jonahwilliams — APPROVED** [review]
Looks Blue To Me

**Comment by matanlurey** [comment]
Looks like Skia gold didn't even detect this :(

**Comment by jonahwilliams** [comment]
Did the check get skipped for some reason?

**Comment by jonahwilliams** [comment]
Looks like gold got the screenshot: https://flutter-engine-gold.skia.org/search?issue=50801&crs=github&patchsets=5&corpus=flutter-engine

But cocoon did not notify the PR

**Pull request merged**
