### PR TITLE
[Impeller] Pack 👏 the 👏 atlas 👏

### PR DESCRIPTION
**Pull request by bdero**
...with individual glyph bounds.

Before:
1024 x 1024
Screen Shot 2022-12-01 at 7 24 08 PM

After:
512 x 512
Screen Shot 2022-12-01 at 7 21 06 PM

### CODE REVIEW

**Comment by jonahwilliams** [comment]
man I wish Github had gifs like discord and gchat so I could post a funny meme on this

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
Pretty good speedup on Android. Unfortunately we don't have the benchmark on iOS, but I assume it would be a good improvement there, too.

https://flutter-flutter-perf.skia.org/e/?begin=1669946990&end=1670017066&keys=Xbe52a0bd5622e359e13dd9b924b88ea6&selected=commit%3D32354%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dlist_text_layout_impeller_perf__e2e_summary%252C&xbaroffset=32354

**Comment by bdero** [comment]
I expect this to be mostly a GPU improvement for cases like:
* Large text (like in Wondrous), which tends to have extreme glyph spacing.
* Any screen with high text density. Most fonts seem to have quite a large min/max X boundary range (like 4-6x the width of most glyphs), making the step that samples from the atlas, well, 4-6x more fragment load on the GPU -- epic tons of overdraw rendering nothing.

**Pull request merged**
