### PR TITLE
Make native wrapper classes non-abstract

### PR DESCRIPTION
**Pull request by alexmarkov**
Certain native wrapper classes are instantiated from native code but they were declared abstract.
This confuses Dart VM precompiler: it only includes constructors into compilation set as they are listed in entry points manifest, but doesn't record the fact that those classes might be instantiated. So far we got away with that, but with the addition of global type inference it starts to matter.

This CL makes those classes non-abstract.

### CODE REVIEW

**Comment by Hixie** [comment]
Please add non-callable private constructors, otherwise people will create broken versions of these.

Something like:
```
  // This class is created by the engine, and should not be instantiated or extended directly.
  factory Image._() => null;
```

**Comment by alexmarkov** [comment]
> Please add non-callable private constructors, otherwise people will create broken versions of these.

Previously, it was possible to extend those native wrapper classes and instantiate a subclass if needed. Are you sure we should prevent this by declaring private constructors? It sounds like a breaking change.

Maybe we should add default constructors (if missing) and document that they are not capable of creating a usable object?

For example, the following existing non-abstract native wrappers have such default constructors:

```dart
class Scene extends NativeFieldWrapperClass2 {
  /// Creates an uninitialized Scene object.
  ///
  /// Calling the Scene constructor directly will not create a useable
  /// object. To create a Scene object, use a [SceneBuilder].
  Scene(); // (this constructor is here just so we can document it)
```

```dart
class SemanticsUpdate extends NativeFieldWrapperClass2 {
  /// Creates an uninitialized SemanticsUpdate object.
  ///
  /// Calling the SemanticsUpdate constructor directly will not create a useable
  /// object. To create a SemanticsUpdate object, use a [SemanticsUpdateBuilder].
  SemanticsUpdate(); // (this constructor is here just so we can document it)
```

Although Picture and Paragraph were abstract, they also have default constructors:

```dart
class Picture extends NativeFieldWrapperClass2 {
  /// Creates an uninitialized Picture object.
  ///
  /// Calling the Picture constructor directly will not create a useable
  /// object. To create a Picture object, use a [PictureRecorder].
  Picture(); // (this constructor is here just so we can document it)
```

```dart
  /// Creates an uninitialized Paragraph object.
  ///
  /// Calling the [Paragraph] constructor directly will not create a useable
  /// object. To create a [Paragraph] object, use a [ParagraphBuilder].
  Paragraph(); // (this constructor is here just so we can document it)
```

**Comment by Hixie** [comment]
Yikes, I hadn't even realised we allowed people to extend and create these. Good point.

That sounds like a disaster. I don't think we should enable that. I agree it could be a breaking change but such code would presumably be pretty dubious as it is.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
