### PR TITLE
Bump third_party/wuffs DEPS to 0.3.0-alpha.4

### PR DESCRIPTION
**Pull request by nigeltao**
This syncs with the corresponding Skia change:
https://github.com/google/skia/commit/b54946b86d33619b0205f789ed6cc10fd31a7982

### CODE REVIEW

**Comment by nigeltao** [comment]
Thanks @jason-simmons, although I think (1) I also need to change `DEPS` in some way, but (2) I can't run `ci/licenses.sh` on my puny laptop (it doesn't have `dart` or `pub` installed, and in any case, disk space is low), so I'm waiting for the CI to fail, so I can copy/paste the `DEPS` change...

Yeah, it's a janky workflow, sorry.

Feel free to submit the equivalent change properly, instead of accepting this pull request.

**Comment by jason-simmons** [comment]
The change to `DEPS` looks fine.

`ci/licenses_golden/licenses_third_party` needs to be updated.  The diffs can be found in https://cirrus-ci.com/task/4719243839143936?command=build#L3707

**Comment by nigeltao** [comment]
Oops, `ci/licenses_golden/licenses_third_party` is what I meant.

@jason-simmons PTAL.

**Comment by jason-simmons** [comment]
Rebased and landed as https://github.com/flutter/engine/pull/19171

**Pull request closed without merging**
