### PR TITLE
Platform view implementation on Linux

### PR DESCRIPTION
**Pull request by huanghongxun**
This pull request aims at supporting platform views on Linux. 

To support platform views:
1. We replaced original `FlRenderer` implementation (creating `EGLSurface` and `EGLContext` by X11 and Wayland) with a new and platform-independent implementation (creating OpenGL context by GdkGLContext, and draw textures to `FlGLArea`)
2. Now Flutter Linux window may have multiple `FlGLArea`s as backing store layer and `GtkWidget`s from plugins as platform view layer. They are stacked in `FlView` which extends `GtkContainer` now.
3. We deal with gestures like the way in iOS. First we listen to gtk pointer events, send it to Flutter framework side, accept gesture if gesture detector test hit positively on the platform view, and finally embedder will send all stored pointer events to platform view(GtkWidget) by `gtk_widget_event`.
4. No longer requires EGL, wayland-client, x11 now. `libepoxy` is added for GL operations, such as creating Framebuffers and textures, and procs for Skia.

This pr closes https://github.com/flutter/flutter/issues/41724.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Comment by robert-ancell** [comment]
Thanks @huanghongxun! Can you split this PR into smaller PRs, perhaps starting with the FlGLArea change? It's a lot of changes to review at once.

**Comment by robert-ancell** [comment]
@wmww - I think we'll need some of your help reviewing this.

**Comment by wmww** [comment]
Not a full review, but I tested and the default demo app works on Wayland (both Sway and Mir). It removes my dirty hacks for Wayland and seems to make resizing a little less flickery. Only oddity is 
```
Status 8cd5
```
is dumped to the terminal repeatedly.

**Comment by huanghongxun** [comment]
For `FlGLArea` changes, please see https://github.com/flutter/engine/pull/24011

**Comment by huanghongxun** [comment]
For platform view implementation, please see #24169.

**Comment by chinmaygarde** [comment]
I am a bit confused about whether this or https://github.com/flutter/engine/pull/24169 is the right issue to track the implementation of platform views on Linux. Based on the review activity, it seems like the other one is the way to go? If so, can we close this one please?

**Pull request closed without merging**
