### PR TITLE
Make TapTracker and TapGesture private classes

### PR DESCRIPTION
**Pull request by abarth**
We don't want to expose these from the gesture package. This patch moves
DoubleTapGestureRecognizer into tap.dart so we can make TapTracker and
TapGesture private to that file.

### CODE REVIEW

**Comment by Hixie** [comment]
I think these classes were intentionally public because you would want to use them to make variants on this gesture detector. @krisgiesing should review.

**Comment by krisgiesing** [comment]
They were intentionally public after a discussion with Hixie :)

I honestly don't have a strong opinion.

**Comment by krisgiesing** [comment]
Since I reverted the tap behaviors yesterday, the shared code is actually between DoubleTapGestureRecognizer and MultiTapGestureRecognizer; TapGestureRecognizer now doesn't share any code with those other classes. So an alternative is to move MTGR into DTGR.dart.

**Comment by krisgiesing** [comment]
LGTM, either all stuff in tap.dart or the shared stuff all going into double_tap.dart.

**Pull request merged**
