### PR TITLE
[Impeller] Simplify color source + text with new Skia API.

### PR DESCRIPTION
**Pull request by jonahwilliams**
The original implementation of arbitrary color source + text was quite complicated due to the fact that I had to use blending to emulate this functionality. Now that we can get paths from a given text data, I can instead make non solid color color sources and text just use the regular geometry + color source pipelines.

Fixes https://github.com/flutter/flutter/issues/132928
Fixes https://github.com/flutter/flutter/issues/132972

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by bdero** [comment]
Can we merge https://github.com/flutter/engine/pull/45079 first to simplify the cherry-pick?

**Comment by jonahwilliams** [comment]
We can't CP this change, it depends on an API that was added after the branch cut.

**Comment by bdero** [comment]
I mean simplify the cherry-pick of https://github.com/flutter/engine/pull/45079

**Comment by jonahwilliams** [comment]
Ahh yeah no rush!

**Pull request merged**
