### PR TITLE
iOS: Always rebuild the FLX file

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
This is a temporary solution until we have dependency tracking across the .flx boundary, right?  @abarth

**Comment by abarth** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Partial fix for https://github.com/flutter/flutter/issues/1345 ?

**Comment by chinmaygarde** [comment]
Yeah, its a partial fix

**Pull request merged**
