### PR TITLE
Revert "Remove pipeline in favor of layer tree holder (#18901)"

### PR DESCRIPTION
**Pull request by iskakaushik**
Reverting for b/158816279

cc: @chinmaygarde , @renyou

### CODE REVIEW

**Comment by iskakaushik** [comment]
landing tbr since its a revert.

**Comment by chinmaygarde** [comment]
For cross-referencing purposes, can you post a one line summary of the reason for the revert?

**Comment by chinmaygarde** [comment]
@iskakaushik Can we accommodate the reliance of the devtools on the stability of the trace event names? If not, let's figure out a transition plan.

**Comment by iskakaushik** [comment]
The tests that were broken in our internal system were relying on a behavior that we don't explicitly state: every frame that gets built gets rendered. Given that this invariant is broken by this PR, we ended up breaking some tests. I'm going to fix the tests and attempt a reland of this PR.

@chinmaygarde i'll coordinate with @kenzieschmoll next time I try to reland this roll. I wasn't familiar with this breakage.

**Pull request merged**
