### PR TITLE
flow::Semaphore for simple platform specific unnamed semaphores.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @jason-simmons @abarth

**Comment by abarth** [comment]
LGTM but please create a new top-level folder called `synchronization` to hold this class.  That will make it easier to move into //lib/ftl if we decide that's the right thing.

**Comment by chinmaygarde** [comment]
Sure. Top-level in `flow` or `flutter`?

**Comment by abarth** [comment]
I was thinking flutter, but either way is fine.  The key is just to make a separate BUILD.gn file with a source_set that has very few dependencies.

**Comment by chinmaygarde** [comment]
Ok, will move to `flutter/synchronization` within the `flutter` namespace. We can move it later.

**Comment by chinmaygarde** [comment]
@abarth Done. Another look please.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
