### PR TITLE
Revert "Make drain() consistently asynchronous."

### PR DESCRIPTION
**Pull request by Hixie**
Reverts flutter/engine#21062, which caused a hang in a google3 test.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @gaaclarke for review.

**Review by gaaclarke — APPROVED** [review]

**Comment by Hixie** [comment]
We should land this if we determine that https://github.com/flutter/flutter/pull/66073 has landed in google's codebase and that the original engine PR here is still causing issues. If landing https://github.com/flutter/flutter/pull/66073 fixes google's issues then this can be closed without landing.

**Comment by renyou** [comment]
I have confirmed the flutter/flutter#66073 is landed in google already. I double checked and the test still fails. See b/169314044.

**Comment by Hixie** [comment]
Follow-up in https://github.com/flutter/flutter/issues/66699.

**Pull request merged**
