### PR TITLE
Add api 21 check to LocalizationChannel.java

### PR DESCRIPTION
**Pull request by GaryQian**
Fix forward for https://github.com/flutter/flutter/issues/28495

Missing and API 21 check.

### CODE REVIEW

**Comment by Hixie** [comment]
Can we add a test to make sure we don't regress this? (Or ideally, a test so that we catch this entire class of bugs going forward?)

**Comment by matthew-carroll** [comment]
I think we can probably "test" this by creating a few example apps that target different APIs.  @dnfield do you think we could work together tomorrow to try to do that?  I also need to do something like that to prove out the direction of the embedding anyway....

**Comment by GaryQian** [comment]
@cbracken mentioned he filed an issue to add a device lab test that uses an API 16 android device to ensure we are still functional on the earliest API we support.

**Comment by dnfield** [comment]
Let's sit together tomorrow at some point on this stuff.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/27790

**Pull request merged**
