### PR TITLE
Implement cursor support for Windows

### PR DESCRIPTION
**Pull request by stuartmorgan**
## Description

Adds the basic support for the cursor channel in the Windows embedding, supporting the subset of the current Dart cursors that are standard Win32 cursors.

## Related Issues

https://github.com/flutter/flutter/issues/31952

## Tests

I added the following tests: None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@dkwingsmt FYI

**Comment by dkwingsmt** [comment]
@stuartmorgan We'll probably want to use a hashmap for `GetCursorForKind`. https://github.com/flutter/flutter/pull/60931 is adding the complete set of cursors (> 60). You don't have to support the new ones in this PR, but the linear search is probably unwanted.

**Comment by stuartmorgan** [comment]
> @stuartmorgan We'll probably want to use a hashmap for `GetCursorForKind`. [flutter/flutter#60931](https://github.com/flutter/flutter/pull/60931) is adding the complete set of cursors (> 60).

Thanks for the heads up, done.

**Comment by stuartmorgan** [comment]
Mac Android Debug Engine was infra flake, and [green on re-run](https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20Debug%20Engine/5293)

**Comment by SahajRana** [comment]
Hi @stuartmorgan, I tried to work with new cursor implementation. It looks like it currently only supports: SIMPLE, HAND, TEXT & UNAVAILABLE cursor works for Windows. Should we expect the addition of Resize arrow cursors, CROSS hair, BUSY system cursors soon, or later?

**Comment by dkwingsmt** [comment]
Yes, they eill be available after https://github.com/flutter/engine/pull/19550 is merged.

**Comment by SahajRana** [comment]
@dkwingsmt, Sure, it would be a great help.

**Pull request merged**
