### PR TITLE
Remove master mirroring workflow.

### PR DESCRIPTION
**Pull request by godofredoc**
All the uses of master in the engine have been removed. We are removing mirroring in preparation to archive the master branch.

Bug: https://github.com/flutter/flutter/issues/90476

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
This requires ensuring that docs on the wiki and website have been updated to match before it can land. It should be also be preceded by a PSA to the internal mailing list.

**Comment by godofredoc** [comment]
> This requires ensuring that docs on the wiki and website have been updated to match before it can land. It should also be preceded by a PSA to the internal mailing list.

We already did all of that back in 2021. http://go/flutter-master2main the only missing part is to remove the mirroring and actually archive the branch.

**Comment by godofredoc** [comment]
> > This requires ensuring that docs on the wiki and website have been updated to match before it can land. It should also be preceded by a PSA to the internal mailing list.
> 
> We already did all of that back in 2021. http://go/flutter-master2main the only missing part is to remove the mirroring and actually archive the branch.

Checking the website again and wiki to ensure we didn't miss anything.

**Comment by zanderso** [comment]
> > This requires ensuring that docs on the wiki and website have been updated to match before it can land. It should also be preceded by a PSA to the internal mailing list.
> 
> We already did all of that back in 2021. http://go/flutter-master2main the only missing part is to remove the mirroring and actually archive the branch.

It would be amazing if there have been no regressions in 2 years ;-)

**Comment by godofredoc** [comment]
> uld be amazing if there have been no regressions in 2 years ;-)

Adding both website and wiki to the open source code search to simplify the search.

**Comment by chinmaygarde** [comment]
Are we still working on this one? Leaving it be or removing it is fine by me.

**Comment by godofredoc** [comment]
I'm checking out the wiki and the website to ensure there are no references to engine/master

**Comment by godofredoc** [comment]
Updated wiki pages:

* https://github.com/flutter/flutter/wiki/Testing-the-engine
* https://github.com/flutter/flutter/wiki/The-Engine-architecture
* https://github.com/flutter/flutter/wiki/Desktop-shells

Website: no references to engine master branch.

website-cms:

* https://github.com/flutter/website-cms/pull/113/

flutter/flutter: no references to engine master branch.
flutter/engine: no references to engine master branch.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
