### PR TITLE
Avoid vsync scheduling delay

### PR DESCRIPTION
**Pull request by jiahaog**
The `Handler` created through `new Handler(Looper.getMainLooper())` is subject to synchronization barriers like vsync. This means that posting tasks to it can result in scheduling delays of up to 16ms. Empirically I have noticed this happening only before the first frame has been drawn, but not sure if it might happen on other occasions.

This is a common pattern for platform message handlers on the main thread, and the delay can stack up and affect startup latency when apps do something like:

```dart
void main() async {
  final a = await sendPlatformMessage();
  final b = await sendPlatformMessageWithA(a);
  final c = await sendPlatformMessageWithB(b);

  runApp(MyApp(c));
}
```

`Handler.createAsync` helps to avoid this, but this API is only available on SDK >=28. Ideally we would use [`androidx.core.os.HandlerCompat`](https://developer.android.com/reference/androidx/core/os/HandlerCompat#createAsync(android.os.Looper)) but we don't have a dependency on it so I opted for a small reimplementation. It differs slightly in that we [don't do](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/os/HandlerCompat.java;l=110-111;drc=7e9c4bfcbd0a3bebc25ec4747922bcf80cd278fe) the reflection fallback to keep things simple. 

Tested: Internal global presubmit. I did not add new tests since this is an implementation change and should be covered by existing tests.

This also improves the startup latency for `customer:money` by 3%. See b/237035671 for more details.

## Related Issues

b/237035671
Might be related to https://github.com/flutter/flutter/issues/81559#issuecomment-843613233

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by jiahaog** [comment]
Dan, can you take a look since @gaaclarke is out?

**Comment by dnfield** [comment]
Test?

**Comment by jiahaog** [comment]
This is an implementation detail covered by existing tests. Not sure how it can be tested in a simple manner, would you be able to advise?

**Comment by dnfield** [comment]
I guess you could test that a handler created with the createAsync compat layer makes isAsynchronous true on messages it sends?

**Review by dnfield — APPROVED** [review]

**Comment by jiahaog** [comment]
Thanks, yes we can add a test for the `HandlerCompat`. Done 🙂

**Comment by gaaclarke** [comment]
FYI I know I've seen this issue with `customer: money` and it helps with their benchmarks but I just checked and we don't have a microbenchmark that seems captures the benefit.  That would be nice to have at some point.

**Comment by jiahaog** [comment]
Going to revert this in https://github.com/flutter/engine/pull/36091 first since it causes https://github.com/flutter/flutter/issues/110867#issuecomment-1240343101

**Pull request merged**
