### PR TITLE
Enable `_Float16` "half-float" Functionality Only When Available.

### PR DESCRIPTION
**Pull request by johnoneil**
# Description:

We're cross-compiling impeller for Android, but x86 Android targets don't  have half float (`_Float16`) _ support. This change disables half float support in `impeller/geometry/half.h` for platforms where the `_Float16` builtin is lacking.

As can be seen in `half.h`, `Float16` support is enabled for all non-windows platforms, which doesn't not allow our use case.

# Issues

I can't seem to find a way to file an issue describing this, but

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jonahwilliams** [comment]
We actually only use the half types on iOS and macOS platforms, everywhere else we end up using floats for compatibility reasons. You could ifdef out the Half precision support for non-apple platforms, but you'd also need to turn off the tests in the non-apple configurations as well.

**Comment by johnoneil** [comment]
> You could ifdef out the Half precision support for non-apple platforms

Thanks for this Jonah. I'll take that approach. Will update this in a few hours.

**Comment by jonahwilliams** [comment]
You also need to update the ifdef here: https://github.com/flutter/engine/blob/main/impeller/geometry/geometry_unittests.cc#L1623-L1654

**Comment by johnoneil** [comment]
Updated PR to green.
If there's anything further you'd like on this just let me know.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by bdero — APPROVED** [review]

**Pull request merged**
