### PR TITLE
iOS: make unopt debug builds unopt and debug

### PR DESCRIPTION
**Pull request by cbracken**
The following iOS builds were named "unopt" and "debug" but did not have
the `--unoptimized` flag passed to `gn`, resulting in them not being
unopt, and having the gn `is_debug` setting set to `false`:

* ios_debug_unopt_sim
* ios_debug_unopt_sim_arm64
* ios_debug_unopt_sim_arm64_extension_safe

No test changes because this is a compile config change.

Issue: https://github.com/flutter/flutter/issues/156166

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by cbracken** [comment]
I do think we should add a test run of the Scenario app to an opt build (maybe profile?) though since this actually did actually catch an ARC migration bug.

**Review by jmagman — APPROVED** [review]
🤦‍♀️ 
Can you check there aren't other obvious instances of this in the other configs?

**Comment by cbracken** [comment]
Yes -- I checked all of them and these were the only unopt configs that were missing the flag.

**Review by zanderso — COMMENTED** [review]
lgtm. Thanks!

**Pull request merged**
