### PR TITLE
Expose a method to shut down Flutter using the GLFW controller.

### PR DESCRIPTION
**Pull request by skycomposter**

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This class isn't threadsafe, so it's not clear to me what purpose this method serves without restructuring the API to allow running the runloop incrementally instead of forever (which does need to be done). Can you explain how this would be used?

**Comment by skycomposter** [comment]
I'm my scenario, I am running a server which spins out a Flutter instance in a separate thread. I want to be able to send a message to the server to shut down Flutter (or a SIGINT for the whole process). Currently I'm calling FlutterDesktopTerminate() directly, but that doesn't seem right (though in practice it gets the job done).

If restructuring the runloop is a prerequisite for this, I can turn it into a feature request instead.

**Comment by stuartmorgan** [comment]
What I'm not understanding is how you would call this method. The only thread it would be valid to call it from is the thread that called RunEventLoop.

**Comment by skycomposter** [comment]
In my prototype I'm calling it from the main server thread, though I understand now that it's not valid from a thread safety perspective.

**Pull request closed without merging**
