### PR TITLE
[Linux] add missing AtkObject::get_index_in_parent implementation

### PR DESCRIPTION
**Pull request by jpnurmi**
Due to missing `AtkObject::get_index_in_parent` implementation, the Orca screen reader would lose track of accessibility objects and they would turn to "zombies".

Fixes: flutter/flutter#101513
See also: https://gitlab.gnome.org/GNOME/orca/-/blob/master/src/orca/script_utilities.py#L5041

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
@jpnurmi can you think of a way we can write a test for this?

**Comment by jpnurmi** [comment]
Sure, I'll come up with something :+1:

**Comment by jpnurmi** [comment]
I'm glad you pushed me to add a test because it made me realize that the first fix attempt wasn't correct. :slightly_smiling_face:

**Comment by cbracken** [comment]
Added @chunhtai for second review.

**Pull request merged**
