### PR TITLE
Update Objective-C column limit to 100

### PR DESCRIPTION
**Pull request by cbracken**
The Google style guide specifies a limit of 100 columns.
https://google.github.io/styleguide/objcguide.xml?showone=Line_Length#Line_Length

The Chromium style guide specifies 80.
https://chromium.googlesource.com/chromium/src/+/master/styleguide/objective-c/objective-c.md

### CODE REVIEW

**Comment by cbracken** [comment]
Please?

**Comment by xster** [comment]
+1

**Comment by abarth** [comment]
LGTM

**Comment by cbracken** [comment]
Yep; sent out the PR to test the waters. I'll push a reformat commit here in 10s.

**Pull request merged**
