### PR TITLE
Silence some compilation warnings.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
https://gist.github.com/pylaligand/49ddab33cfa7ca636c351a5beff85bb2

**Comment by chinmaygarde** [comment]
The warnings are caused by buildroot confit differences. I'd like to keep the warnings enabled on the Flutter buildroot. Can we wrap that in a is_fuchsia_host block please?

**Comment by pylaligand** [comment]
Could you point me at the proper config in the buildroot? I'll replicate in Fuchsia.

**Comment by pylaligand** [comment]
ping

**Comment by chinmaygarde** [comment]
I believe the -Werror in the [build/config/compiler/BUILD.gn](https://github.com/flutter/buildroot/blob/49dc17e37e24ae153a3d2426c958254be1904562/build/config/compiler/BUILD.gn#L618) enable the warning in Flutter.

**Comment by pylaligand** [comment]
Wait, so that would turn the warnings into errors, right? I wonder why you are not seeing these warnings in the Flutter build.

**Comment by Hixie** [comment]
@pylaligand Please reopen this PR when you are ready to land it. Thanks! (I'm just cleaning out our review queue and this one has been open with no activity for more than a week.)

**Pull request closed without merging**
