### PR TITLE
[Impeller] Set impeller_enabled flag consistently in Preroll and Paint.

### PR DESCRIPTION
**Pull request by flar**
Fixes https://github.com/flutter/flutter/issues/134689

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by flar** [comment]
This PR will become obsolete (if/)when https://github.com/flutter/engine/pull/43759 is reverted.

**Comment by jonahwilliams** [comment]
We should still land this if we can, as the preroll flag is used elsewhere too.

**Comment by jonahwilliams** [comment]
nvm, you were right. I backed the change out manually and the flag could be removed entirely

**Pull request closed without merging**
