### PR TITLE
Add setIsVolatile to path to accelerate animation

### PR DESCRIPTION
**Pull request by liyuqian**
The should fix https://github.com/flutter/flutter/issues/17889

### CODE REVIEW

**Comment by liyuqian** [comment]
@chinmaygarde : Are most paths going to be repeatedly drawn in Flutter unless we have raster cache, or animated paths? If so, is setIsVolatile for all paths going to decrease our performance in the most common cases? @Hixie @cbracken @jason-simmons : what are your thoughts on this?

From my Skia experience, the texture cache works very well for scenes like [chalkboard benchmark](https://testdrive-archive.azurewebsites.net/performance/chalkboard/): our CPU backend is usually much faster than GPU backend on path rendering before CCPR; but CPU never caches path textures while GPU does, and that caching makes GPU backend much faster than CPU on that benchmark because there are tons of small paths that can be cached without re-rasterizing. @reed-at-google @bsalomon : what's your suggestion on setIsVolatile with flutter?

**Comment by Hixie** [comment]
I believe most paths get created, used once, and thrown away.

I think if we were to add something like this, we should add it as a second constructor, not as something you mutate on the object, because really this is something you have to think about when you create the path, not later.

**Comment by Hixie** [comment]
> I believe most paths get created, used once, and thrown away.

...but we should test this, don't take my word for it.

**Comment by chinmaygarde** [comment]
>  Are most paths going to be repeatedly drawn in Flutter unless we have raster cache, or animated paths? If so, is setIsVolatile for all paths going to decrease our performance in the most common cases.

We probably don't use the same paths over and over. But that is just a guess. The engine has no way of knowing any better as that information is lost before it gets to the engine.

Adding texture caches increases per frame performance at the cost of memory and an initial hit during cache population (what we ran into with the bezier demo). I am sure my workstation has enough memory to spare but I really don't think using texture caches liberally is the way to go on mobile.

**Comment by liyuqian** [comment]
@Hixie : according to my discussion with @chinmaygarde , we will record the path into SkPicture through recording canvas and potentially reuse it repeatedly by drawing that SkPicture multiple times. But just as you mentioned, it's unclear what impact there would be between `setIsVolatile(true)` or not. We'll benchmark both frame time and memory usage to decide whether we should default to `setIsVolatile(true)`.

**Comment by Hixie** [comment]
Ah yeah if we're going to reuse the path as part of a picture then this is mostly moot.

**Comment by liyuqian** [comment]
Temporally close this PR until we can figure out the memory and performance impacts of setIsVolatility.

**Pull request closed without merging**
