### PR TITLE
Fixed a case where the KeyUp event is not called by Command+Key on MacOS

### PR DESCRIPTION
**Pull request by zuvola**
Fixes https://github.com/flutter/flutter/issues/133832

The KeyUp event was not being called when the first responder was the FlutterViewWrapper.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by knopp** [comment]
I don't know if this is the correct solution. Why is `FlutterViewWrapper` first responder in the first place?

**Comment by zuvola** [comment]
@knopp 
FlutterTextInputPlugin sets self.nextResponder as first responder, so FlutterViewWrapper, the parent of FlutterTextInputPlugin, becomes the first responder It seems to be the case.

https://github.com/flutter/engine/blob/727fd967973a931bd24f331ec31ad928ab285b37/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L384-L392

Should I have fixed the resignAndRemoveFromSuperview?

**Comment by knopp** [comment]
I'm not sure what the correct solution is here, I will look into it, but I think the responder chain should be consistent before and after text input plugin is added/removed from hierarchy.

**Comment by zuvola** [comment]
Ok, I understand. Thanks for the correction.

**Pull request closed without merging**
