### PR TITLE
Fix first batch of warnings in the Android embedding

### PR DESCRIPTION
**Pull request by blasten**
Fixes ~400 warnings. Almost all the warnings are about specifying nullability annotations 
for better compatibility with Kotlin.

https://developer.android.com/kotlin/interop#nullability_annotations

There are 986 warnings left.

### CODE REVIEW

**Review by GaryQian — APPROVED** [review]
LGTM! Thanks for all these tiny fixes!

**Comment by GaryQian** [comment]
Tests seem to be stuck, this may benefit from a rebase and a test kick

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

thanks for doing this!!

**Comment by chinmaygarde** [comment]
The test failures are definitely related to the updates in this patch.

**Pull request merged**
