### PR TITLE
Fix css changes with macOS 13 and Safari

### PR DESCRIPTION
**Pull request by vashworth**
Safari on macOS 13 outputs different styling than before. Adjust tests to accept new changes. 

Fixes https://github.com/flutter/flutter/issues/136274. Fixes https://github.com/flutter/flutter/issues/136279.

Example passing on macOS 12: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_web_engine/16401/overview
Example passing on macOS 13: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_web_engine/16396/overview

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by vashworth** [comment]
Ooof I was hoping this would be as simple as just making the expectations more flexible, but looks like it also affects the golden files. This might be too far out of my knowledge to fix.

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by vashworth** [comment]
@yjbanov Do you know what I need to do about the goldens? I'm not familiar with how that works

**Comment by vashworth** [comment]
@yjbanov I changed this back to keep only running on macOS 12. I also filed a separate issue for the golden files since I'm unsure how to fix: https://github.com/flutter/flutter/issues/139924

**Pull request merged**
