### PR TITLE
[Impeller] Turns on the Metal validator for impeller_unittests.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/121017

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
I patched in jonahs change to verify it fixes the problem (i don't have an x86_64 machine to test locally).  I'll revert it after the test.

**Comment by jonahwilliams** [comment]
You'll need one more cmmit to make it work (I messed up the mipmap setting)

**Review by chinmaygarde — APPROVED** [review]

**Comment by jonahwilliams** [comment]
I rebased after the upload to private patch landed. If these all pass we should land it this week

**Comment by chinmaygarde** [comment]
Does this need another rebase?

**Comment by gaaclarke** [comment]
> Does this need another rebase?

Ahh no I don't think so.  It looks like our tests genuinely fail with validation turned on.  I can take a look at this later today or next week.  I thought this passed locally and didn't follow up with the CI results.

**Comment by gaaclarke** [comment]
On ci `GlyphAtlasTextureIsRecreatedIfTypeChanges` failed, but locally it passed for me.  I will try rebasing.

**Comment by gaaclarke** [comment]
Looks like the tests pass on debug builds, but on profile builds and release builds there are validation errors.

**Comment by gaaclarke** [comment]
I've tried to reproduce the failure in the profile build locally 3 times, but it runs fine locally.  I'll attempt a rerun to see if we get the same failure or a different failure.  For reference the previous failure was:
```
[ RUN      ] Play/RendererTest.TheImpeller/Metal

STDERR: 
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
2023-04-27 15:17:25.839 impeller_unittests[82338:468259] Metal API Validation Enabled
-[MTLDebugDevice newTextureWithDescriptor:]:1008: failed assertion `Texture Descriptor Validation
MTLStorageModeShared not allowed for textures
'
```

**Comment by gaaclarke** [comment]
This is jonah's fix to the validation problem: https://github.com/flutter/engine/pull/41001

There is no obvious reason why that change would behave differently on debug and profile builds.

**Comment by gaaclarke** [comment]
Weird, on "Mac mac_host_engine" the debug build passes, on "Linux mac_unopt" it doesn't pass so we can just run with validation for debug builds.

@jonahwilliams Do you have any theories why we are still running into this issue, even after a rebase and why we seem to be seeing different results locally?

**Comment by jonahwilliams** [comment]
WTF is "Linux mac_unopt" 🤔

**Comment by zanderso** [comment]
> WTF is "Linux mac_unopt" 🤔 

The orchestrator is Linux and the actual build is on a mac. It's an engine v2 thing because we have more Linux capacity.

**Comment by jonahwilliams** [comment]
Do we know which tests are failing? There is a lot more usage of StorageMode::kHostVisible than the one I removed

**Comment by gaaclarke** [comment]
I've seen these fail:
- `Play/RendererTest.TheImpeller/Metal`
- `Play/SceneTest.FlutterLogo/Metal`

Do we have bots that run on arm64?  Maybe we could just turn off x86_64 validation for now.

**Comment by gaaclarke** [comment]
Oh you know what, you probably need a discrete graphics card to actually get the failure locally.  Running through rosetta probably isn't enough.  I can simulate this failure with conditional compilation possibly.

In the meantime I've asked godofredo if we can possibly just turn this on for arm64 bots.  I'm not sure if we are guaranteed an execution on an arm64 bot.

**Pull request merged**
