### PR TITLE
Include raw_keyboard.mojom in the Linux build too.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by krisgiesing** [comment]
Is there anything that uses this path right now? I thought the service didn't have an implementation on Linux (that's actually what I'm looking at right now).

**Comment by abarth** [comment]
That's correct, but the sky_services package should be the same across all platforms.

**Comment by krisgiesing** [comment]
OK, just checking, thanks.

**Comment by Hixie** [comment]
The analyzer is about to use the .dart files here, that's how I ran across the inconsistency.

**Pull request merged**
