### PR TITLE
[Impeller] Reland: Use the scissor to limit all draws by clip coverage. 

### PR DESCRIPTION
**Pull request by bdero**
Reland https://github.com/flutter/engine/pull/51698.

This reverts commit https://github.com/flutter/engine/commit/73c145c9ac3a3d7ea7b644e696b0ea4306ec849f.

Attempts to improve https://github.com/flutter/flutter/issues/145274.

Our new clipping technique paints walls on the depth buffer "in front" of the Entities that will be affected by said clips. So when an intersect clip is drawn (the common case), the clip will cover the whole framebuffer.

Depth is divvied up such that deeper clips get drawn _behind_ shallower clips, and so many clips actually don't end up drawing depth across the whole framebuffer. However, if the app does a lot of transitioning from a huge clips to a small clips, a lot of unnecessary depth churn occurs (very common in Flutter -- this happens with both the app bar and floating action button in the counter template, for example).

Since progressively deeper layers in the clip coverage stack always subset their parent layers, we can reduce waste for small intersect clips by setting the scissor to the clip coverage rect instead of drawing the clip to the whole screen.

Note that this change _does not_ help much with huge/fullscreen clips.

Also, we could potentially improve this further by computing much stricter bounds. Rather than just using clip coverage for the scissor, we could intersect it with the union of all draws affected by the clip at the cost of a bit more CPU churn per draw. I don't think that's enough juice for the squeeze though.

Before (`Play/AiksTest.CanRenderNestedClips/Metal`):

https://github.com/flutter/engine/assets/919017/7858400f-793a-4f7b-a0e4-fa3581198beb

After (`Play/AiksTest.CanRenderNestedClips/Metal`):

https://github.com/flutter/engine/assets/919017/b2f7c96d-a820-454d-91df-f5fae4976e91

### CODE REVIEW

**Comment by bdero** [comment]
The new golden reproduces the issue that triggered the revert.

Before:

https://github.com/flutter/engine/assets/919017/030502e6-fb44-47ed-8862-039e09d5d72f

After:

https://github.com/flutter/engine/assets/919017/d82e407c-89c2-419a-8c7c-1b442035ab08

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by bdero** [comment]
The new golden is missing for some reason. I'm going to push a blank commit to see if it shows up...

**Comment by jonahwilliams** [comment]
At least on the flutter gallery benchmark, we're back to the pre StC baseline: 

https://flutter-flutter-perf.skia.org/e/?begin=1709165450&end=1711599083&queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_gpu_frame_time%26sub_result%3D99th_percentile_gpu_frame_time%26sub_result%3Daverage_gpu_frame_time%26sub_result%3Dworst_gpu_frame_time%26test%3Dnew_gallery_impeller__transition_perf&requestType=0&selected=commit%3D40040%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_gpu_frame_time%252Ctest%253Dnew_gallery_impeller__transition_perf%252C

**Pull request merged**
