### PR TITLE
Add a --use-glfw flag to //sky/tools/gn

### PR DESCRIPTION
**Pull request by abarth**
This flag makes it easier to enable the glfw configuration.

Also, fix an unrelated build error in loader.cc.

### CODE REVIEW

**Comment by abarth** [comment]
@jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
I'm missing context here.  I assumed glfw was just the linux sky_shell view system.  Does linux have a separate one?  Or does glfw work on other platforms?  Surprised this is an option and not just a linux-default.

**Comment by abarth** [comment]
> I assumed glfw was just the linux sky_shell view system.

It's an option for one.  We could add other options like glx or wayland in the future.

> Does linux have a separate one?

The default Linux build is still headless.

> Or does glfw work on other platforms?

glfw has the potential to work on Linux, Mac, and Windows.  Currently we only use it on Linux but we might want to use it on those other platforms in the future.

> Surprised this is an option and not just a linux-default.

We could make it the default on Linux if we wanted.  That would introduce a dependency on X11 to the base Linux build, which seemed like something we might want to avoid if we want to make it easy to build for non-X11 Linux configurations (e.g., Wayland) in the future.

**Comment by abarth** [comment]
If you like, we can make glfw be the default configuration on Linux and keep the headless configuration as an option.

**Comment by eseidelGoogle** [comment]
@abarth: What we have now sounds fine. :)  Thanks for the context.

**Pull request merged**
