### PR TITLE
Return an empty optional in HardwareBuffer::GetSystemUniqueID if the underlying NDK API is unavailable

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
IMO we should have a test for this, espcially since its causing a regression.

**Review by chinmaygarde — APPROVED** [review]
💀

This should happen on devices with levels >=29 and < 31 (so just 29 and 30).

I know we have tests on < 29 and pretty sure one of the later ones. But not sure about just those two versions.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by chinmaygarde** [comment]
I filed https://github.com/flutter/flutter/issues/146146 to list the current major version breaks.

**Pull request merged**
