### PR TITLE
Finish clangd testing.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/141641, yay we done!

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by matanlurey** [comment]
@zanderso It appears this might not work, or doesn't work in try-bot mode?

**Comment by zanderso** [comment]
Might just need a rebase.

**Comment by zanderso** [comment]
I pushed a change to copy [these properties](https://github.com/flutter/engine/blob/main/ci/builders/mac_unopt.json#L30) from mac_unopt.json into the new unopt build.

**Comment by zanderso** [comment]
Looks like that did the trick: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_clangd/2/overview

**Pull request merged**
