### PR TITLE
FlRenderer cleanup in preperation for Wayland support

### PR DESCRIPTION
**Pull request by wmww**
## Description

Clean up some minor problems in `FlRenderer` in preparation for adding Wayland support.

- Fix a problem where some errors were incorrectly showing `EGL_SUCCESS`. A successful EGL call was being made between the failed call and the diagnostic message. This calls `eglGetError()` earlier to handle that.
- Make `FlRenderer` hold a generic `FlRenderer`, rather than a `FlRendererX11`
- Remove a `GError` that was being ignored anyway

## Related Issues

https://github.com/flutter/flutter/issues/57932
Piece of my previous PR: https://github.com/flutter/engine/pull/19736

## Tests

None

## Checklist

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by wmww** [comment]
CLA check should be passing, we're looking into why it's not

**Comment by wmww** [comment]
@googlebot I signed it!

**Comment by wmww** [comment]
Third times a charm

@googlebot I signed it!

**Comment by liyuqian** [comment]
This seems to be related with the desktop and @stuartmorgan might be a better reviewer.

**Comment by wmww** [comment]
Roger. As I look at this some more, there's a lot more simplification we can do. Expect good error handling, but also more structural changes.

**Comment by wmww** [comment]
On second thought, let me do all that in another PR. I removed the questionable commit so no new problems are being introduced. Future PR will also address unhanded error you mentioned.

**Pull request merged**
