### PR TITLE
Check for a detached FlutterNativeView before sending messages

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/13481

### CODE REVIEW

**Comment by jason-simmons** [comment]
@zanderso

**Comment by amirh** [comment]
I think this might trade the crash with potentially missing data...
The Firebase plugin should probably either disconnect listeners right before we set mNativeView to null, or otherwise queue the update...

**Comment by jason-simmons** [comment]
Ideally plugins would have better connections to the lifecycle of the FlutterView and activity.  But for now this will restore the behavior FlutterView used prior to the FlutterNativeView refactoring.

**Comment by zanderso** [comment]
This specific issue is probably fixed after https://github.com/flutter/engine/commit/619f452ece9b8fec405c9b1c499f2509caaa79da since the BinaryMessenger handed to the plugin is the FlutterNativeView rather than the FlutterView. See: https://github.com/flutter/engine/commit/619f452ece9b8fec405c9b1c499f2509caaa79da#diff-0fee8a5b0006794b358771128c92c9c8R96

However, adding these checks is probably harmless.

**Pull request merged**
