### PR TITLE
Add a task runner for the Win32 embedding

### PR DESCRIPTION
**Pull request by stuartmorgan**
Split off of #11829

Adds a task runner, and exposes API to allow application-level runloops to know when they need to next call the API to process engine events. Internally, sends null events to wake up the app runloop when new events are scheduled to ensure the wait time is updated accordingly.

Fixes #36420

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I just realized that I didn't apply all the changes I requested in initial review of #11829 so this will need at least a few minor tweaks, but it can still get a review for all the new parts and the overall structure.

**Comment by stuartmorgan** [comment]
> According to Chimay, nanosecond precision isn’t strictly required for the runloop.. so not sure if it makes sense to maintain that somewhat extreme precision for events that don’t need it

I considered changing it at the C API, but since we don't need long periods of time anyway, discarding precision only when necessary to interact with the Win32 APIs rather than earlier seemed like the best option.

**Comment by stuartmorgan** [comment]
@clarkezone Can you add a comment consenting to the use of your commits per the googlebot instructions above?

**Comment by clarkezone** [comment]
@googlebot I consent.

**Pull request merged**
