### PR TITLE
Switch to Android 14 for physical device firebase tests

### PR DESCRIPTION
**Pull request by gmackall**
Switch to the latest android version for tests.

Device is high capacity, and [currently in use in flutter/flutter](https://github.com/flutter/flutter/blob/dbb79e63ebdfdc0f11c9d1ab4125a80384a59d56/.ci.yaml#L451). See [here](https://firebase.google.com/docs/test-lab/android/available-testing-devices) to get the list of devices.

Related to https://github.com/flutter/flutter/pull/136736

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gmackall** [comment]
It's actually not clear to me that this configuration is being used at all. Asked about it in #hackers-engine, anyone who finds this can ignore for now (unless you know the answer, then please let me know!)

**Comment by gmackall** [comment]
Blocked on https://github.com/flutter/flutter/issues/136767

**Comment by gmackall** [comment]
This is no longer blocked so marking as ready for review

**Review by camsim99 — APPROVED** [review]

**Comment by gmackall** [comment]
Looks like the `Linux linux_android_aot_engine` test failed the first run because the `android_profile_arm64` sub-test crashed during the firebase testing.

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_android_aot_engine/21164/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1582941/overview

Crashed with the error
```
java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterEngine io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.getFlutterEngine()' on a null object reference
     FATAL EXCEPTION: main
Process: dev.flutter.scenarios, PID: 17095
java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterEngine io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.getFlutterEngine()' on a null object reference
	at io.flutter.embedding.android.FlutterActivity.getFlutterEngine(FlutterActivity.java:1232)
	at dev.flutter.scenarios.TestActivity.writeTimelineData(TestActivity.java:107)
	at dev.flutter.scenarios.TestActivity$1.run(TestActivity.java:56)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

It seems to have passed on re-run

**Pull request merged**
