### PR TITLE
Make `fml/status_or.h` compatible with `.clang_tidy`.

### PR DESCRIPTION
**Pull request by matanlurey**
Work towards https://github.com/flutter/flutter/issues/134969.

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]

**Review by gaaclarke — COMMENTED** [review]
Oh wait, implicit constructors were on purpose to be compatible with absl usage.  I think it would be better to just turn off that lint.

**Review by gaaclarke — APPROVED** [review]
LGTM.  I think NOLINTNEXTLINE would be preferable since the end scope can't get messed up, not a big deal though.

**Comment by matanlurey** [comment]
> LGTM. I think NOLINTNEXTLINE would be preferable since the end scope can't get messed up, not a big deal though.

Works for me! Done.

**Comment by stuartmorgan** [comment]
test-exempt: helps unblock turning on a check that will automatically enforce the change

**Pull request merged**
