### PR TITLE
DO NOT MERGE: Let's find out if NDEBUG is defined in ios_debug_sim builds

### PR DESCRIPTION
**Pull request by cbracken**
Do not LGTM. Do not merge.

For context, see: https://github.com/flutter/engine/pull/55621

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by cbracken** [comment]
@jmagman let's see what happens.

**Comment by cbracken** [comment]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1210053/overview
```
Test Suite 'IOSSurfaceNoopTest' started at 2024-10-03 12:06:10.179.
Test Case '-[IOSSurfaceNoopTest testCreateSurface]' started.
2024-10-03 12:06:10.183176-0700 IosUnitTests[19489:122395] ============================= NDEBUG is defined
Test Case '-[IOSSurfaceNoopTest testCreateSurface]' passed (0.007 seconds).
Test Suite 'IOSSurfaceNoopTest' passed at 2024-10-03 12:06:10.192.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.014) seconds
```

Well that's interesting.

**Comment by jmagman** [comment]
```
2024-10-03 13:00:54.001709-0700 IosUnitTests[56905:353895] ============================= NDEBUG is defined
2024-10-03 13:00:54.001862-0700 IosUnitTests[56905:353895] ============================= DEBUG is NOT defined
```

**Comment by chinmaygarde** [comment]
The NDEBUG macros [are set here](https://github.com/flutter/buildroot/blob/9ac1734caed767e6add4eeb2d3f1a306beed8113/build/config/BUILD.gn#L66). Perhaps its easier to tell by using `gn desc` instead.

**Comment by chinmaygarde** [comment]
May I close this?

**Comment by cbracken** [comment]
Closed -- sorry about that! Should have closed it right away.

**Pull request closed without merging**
