### PR TITLE
Removed unnecessary dynamic dispatch

### PR DESCRIPTION
**Pull request by gaaclarke**
Small performance tweak.
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Should any of these be virtual?

**Review by chinmaygarde — APPROVED** [review]
I suppose we can change these interfaces all we want since they are internal. But cc @flar may have additional context on why this needs to be one way or another.

**Comment by gaaclarke** [comment]
> Should any of these be virtual?

I suspect they did that to facilitate testing.  There is no need for runtime polymorphism though.  We never switch out the implementation at runtime.

**Comment by flar** [comment]
I guess I wanted to leave it to an implementation if it wanted to override the helper variants and do them directly. For example, for the drawImage with no bounds, maybe the implementation might be slightly faster if it knew that the source rect was "the entire image"????

In reality I probably just slammed virtual in front of everything in a big robotic paste frenzy.

**Pull request merged**
