### PR TITLE
Roll skia and enable API guards

### PR DESCRIPTION
**Pull request by brianosman**
This pulls latest skia, but also includes the new API guard functionality from #3877. This should allow us to re-enable the Fuchsia auto-roller, and then stage fixes to call-sites in flutter.

### CODE REVIEW

**Comment by brianosman** [comment]
Am I reading the travis failures correctly that the build is just timing out because the license script is taking > 10 minutes?

**Comment by jason-simmons** [comment]
Yes - it looks like the license script froze in the middle of processing Skia sources.  Try restarting the Travis job.

**Comment by brianosman** [comment]
Hmm. I re-ran job, and it failed in the same way. Guess I'll try running it locally to see if something in the Skia tree is causing the script to choke.

**Comment by brianosman** [comment]
... and it stalls locally as well. Interesting note: We've recently modified how we write/build shaders in Ganesh. We have a custom language for the shader source code, and a tool that emits C++ headers and source files from those. We have the C++ code checked in, so that clients don't need to modify their build process, but those files are definitely not formatted like the rest of our code (line length and indentation are both pretty bizarre). The file that's causing the hang is one of those files (and probably the first one being encountered by the script). I've just started looking at the details of the license script, but my dart knowledge is pretty minimal. I'm wondering if one of the regular expressions has some bad construct that we're triggering with the formatting of our generated source?

**Comment by eseidelGoogle** [comment]
Which file path specifically is hanging?  @jason-simmons and @Hixie wrote the license script.

**Comment by brianosman** [comment]
It's hanging on src/effects/GrCircleBlurFragmentProcessor.cpp. The RegEx that it appears to be running (from breaking in with observatory) is below, but I don't see this particular pattern anywhere in the license script source code:
`$ p _re
= _RegExp (^((?:[-;@#<!.\\"/* ]*(?:REM[-;@#<!.\\"/* ]*)?[-;@#<!.\"/*]+)?)( *)(?:Portions *(?:(?:\*/ *|[*#])?(?:\n\1 *(?:\*/ *)?)*\n\1\2 *)?)`

Running clang-format on that source file did prevent the hang, so we've landed that as a workaround, and I'm now going to roll Skia at that revision.

**Comment by brianosman** [comment]
Multiple attempts at getting the sky license check to pass convinced me that I probably had stale third_party libs (that had been removed from DEPS?), so I just abandoned this and started with a fresh repo in #3884.

**Pull request closed without merging**
