### PR TITLE
[Impeller] organize texture shaders / delete blend.frag + external_texture_fill

### PR DESCRIPTION
**Pull request by jonahwilliams**
* Deletes blend.frag/vert . This was identical to the existing texture_fill shader.
* Move alpha to frag info and stop passing as varying.
~~* Deletes strict src rect fragment shader. We should be able to compute the UVs on the CPU, which is trivial since this is only used for rectangular draws.~~
* Deletes external texture fill in favor of tiled texture external fill. The former shader is marginally faster, but we don't use it since we don't correctly check for the right extensions needed for non-emulated sampling modes with external textures on GLES. Easier to just always use emulated tile modes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I think we don't need the strict src rect fragment shader, but when I run the golden NinePatchImagePrecision before/after or with the feature disabled altogether I don't notice a difference.

**Comment by jason-simmons** [comment]
This PR changes the output for the example app from https://github.com/flutter/flutter/issues/140393.

With `texture_fill_strict_src.frag` the output matches Skia's behavior.  With this patch it looks like the sampler may be blending color from adjacent pixels into the corners.

**Comment by jonahwilliams** [comment]
Does this require a specific screen size or device? Visually this looks correct for me on a Pixel 7 Pro, and the playground test you added also looks correct for me on an m1 mac. But I can reproduce the pixel bleeding if I turn of the kStrict flag entirely.

**Comment by jason-simmons** [comment]
The issue is that with this PR the colors of the corners are lighter than expected.

| Original | With PR #52137 |
| ----- | ----- |
| original | with_52137 |

The above was taken from a Pixel 6a, but this should reproduce on any device.

The bleeding outside the corners does not happen with this PR.  But the corners themselves look like they are not sampling exclusively from the color of the corners in the nine-patch image.

**Comment by jonahwilliams** [comment]
Okay I see it now! I think I'll leave this one as is. Since we only use it in the drawRect case its not going to cause problems with the tiled texture refacor.

**Comment by jonahwilliams** [comment]
@chinmaygarde speaking of reducing shader count

**Review by chinmaygarde — APPROVED** [review]

**Comment by jonahwilliams** [comment]
reason for revert: investigating breakages in https://github.com/flutter/engine/pull/52299

**Pull request merged**
