### PR TITLE
Dont snap in pre-roll (#36173)

### PR DESCRIPTION
**Pull request by jonahwilliams**
Don't snap during pre-roll. This doesn't fix all of the issues, but does make things more consistent

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/36181

**Review by dnfield — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Going to merge one more commit into this to pickup and additional case

**Review by dnfield — APPROVED** [review]

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/36181

**Comment by jonahwilliams** [comment]
now this is updated

**Comment by chinmaygarde** [comment]
@itsjustkevin I believe this needs to be cherry-picked.

**Pull request merged**
