### PR TITLE
[Impeller] fix some OpenGL Linux desktop issues.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/130514

The context wasn't current so we couldn't get the GL version.

The extension lookup was throwing an invalid enum error, the desktop opengl docs say to use a different method.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by ardera** [comment]
Does this really work? This will call `gl_context_make_current` on the platform thread, AFAICT without calling `gl_context_clear_current` after, and the raster thread will also attempt to call `gl_context_make_current`.

I also came across this issue (that `FlutterEngineRunInitialized` needs a GL context) and I had to use a different context because the raster thread was also calling `gl_context_make_current`.  (While `FlutterEngineRunInitialized` was still running on the platform thread) See https://github.com/ardera/flutter-pi/commit/369a818db87365b2bdb5389b180a0c62f026f6da

I haven't tested yet with flutter-pi, so idk maybe it works fine. But if it doesn't work with flutter-pi, I'm wondering why it works with the desktop embedder.

**Comment by jonahwilliams** [comment]
I mean maybe, but it really is just based off of a mirror of what we do on the Skia embedder: GPUSurfaceGLSkia

But in general the impeller backend doesn't work yet on desktop OpenGL.

**Comment by ardera** [comment]
Okay I'll try, maybe it works differently than I expected

With the fixes flutter-pi actually ran with impeller, though it wasn't that smooth and it crashed after 1-2 minutes

**Comment by jonahwilliams** [comment]
The OpenGL backend hasn't really seen a lot of focus, so I'd definitely expect poor performance. Through crashing shouldn't happen in general.  Though If you find particular crashes or scenes that are unusually slow please file issues on them.

**Pull request merged**
