### PR TITLE
Implement `Paint.from(other)` for `dart:ui`.

### PR DESCRIPTION
**Pull request by matanlurey**
(Tenatively) Closes https://github.com/flutter/flutter/issues/142871.

I personally think this is a reasonable request, and we (framework authors) can make some users happy in a fairly simple way (https://github.com/flutter/flutter/issues/142871, https://github.com/flutter/flutter/issues/40497).

Some questions:

1. Is the web implementation good enough or would we want to "ship" with an optimized impl?
2. Can folks imagine other edge cases to test beyond correctness and deep/immutable copies?

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
This would need a VM implementation as well to really evaluate.

I don't think we should do this. dart:ui avois implementing convenience APIs in general. Paint is kind of on the edge, but at the very least, we should see what this would look like on the VM implementation. In that case, `Paint.from` is going to have to copy some `ByteData` (not so bad) and copy a list of Objects (which probably will all need their own `.from` methods).

I'll add a comment about this to the bug as well.

/cc @goderbauer

**Comment by jonahwilliams** [comment]
Paint is unique in that we don't have a higher level API that wraps it. Pretty much all custom painter/painting code in Flutter will directly create and manipulate paint objects. For this case in particular I don't think its unreasonable to add convienence API to it.

**Comment by matanlurey** [comment]
Oh shoot I had a VM implementation and I think I just didn't add it to the PR. Next week 😄

**Comment by dnfield** [comment]
We don't have higher level APIs wrapping Rect or Offset either, and those don't have these kind of convenience constructors.

My bigger concern is what to do about some of the mutable fields on paint if we adopt this. I think that however we try to document it, it will be counterintuitive ... and I'm really not sure why we'd support this kind of API when it's so easy for a user who wants the simple case to work to do the right thing themselves.

**Comment by dnfield** [comment]
We _do_, OTOH, have `Path.from`, and that is documented as doing some CoW behavior.

**Comment by jonahwilliams** [comment]
We clearly don't need a Rect.from or Offset.from, those are very simple classes. But Paint is a big old bag of properties. IIRC the filters objects stored on Paint are actually immutable so we don't need to deeply copy

**Comment by matanlurey** [comment]
Updated with the missing code for `lib/ui/painting.dart` and tests.

A convenience method makes a lot of sense here:

1. A user that wants to copy is going to have to implement it themselves
2. We can do better than the user, because we know the internal data structure
3. Every field, AFAICT, is deeply immutable, so the operation is very low-complexity:

```dart
Paint.from(Paint other) {
  _data.buffer.asUint32List().setAll(0, other._data.buffer.asUint32List());
  _objects = other._objects?.toList();
}
```

`Rect` and `Offset` are simple immutable classes, where-as `Paint` is more complicated.

**Comment by matanlurey** [comment]
@eyebrowsoffire Jackson, the web failure (that I can't reproduce locally) only happens on `chrome-dart2wasm-skwasm-ui` - is there anything about this configuration that would cause hangs?

**Comment by matanlurey** [comment]
@eyebrowsoffire I'll need some help debugging why the WASM implementation hits an infinite loop. I setup a few minutes this Friday to pair if that's more helpful, thanks!

**Comment by matanlurey** [comment]
> @eyebrowsoffire I'll need some help debugging why the WASM implementation hits an infinite loop. I setup a few minutes this Friday to pair if that's more helpful, thanks!

Might be easy - @eyebrowsoffire let me know there was an issue with `storkeMiterLimit` not being hooked up as expected, which recently got fixed. I am re-running rebased on CI to see if true :)

**Comment by matanlurey** [comment]
Yup that did it, all tests passing!

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
