### PR TITLE
4x4.png -> 2x2.png; this file is actually 2x2

### PR DESCRIPTION
**Pull request by dnfield**
The checked in file is 2 pixels by 2 pixels. Just renames it.

### CODE REVIEW

**Comment by nturgut** [comment]
This will still fail on Web Engine tests, @jason-simmons also sent this fix: https://github.com/flutter/engine/pull/20024

**Comment by iskakaushik** [comment]
I multiplied an additional time when naming it looks like :-/

**Comment by nturgut** [comment]
Looks like this one passed all the LUCI tests, which makes sense since this [PR](https://github.com/flutter/engine/pull/20024) have fixed dependency issues for web_ui build.

However, [engine](https://ci.chromium.org/p/flutter/g/engine/console) still has a broken build which successfully run on many other occasions with the latest commit, therefore we believe it is an issue with dart tags and caching. (Ex: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine/1018, https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/7002) 

Shall we try to merge this PR on Monday morning to see if we can get a green build?

/cc @godofredoc @christopherfujino

**Comment by dnfield** [comment]
Why is the cirius check still failing?

**Comment by nturgut** [comment]
> Why is the cirius check still failing?

That tests fails due to flutter. I think that one will only get fixed once we roll the engine. /cc @jonahwilliams  know the plans on the roll.

**Comment by jonahwilliams** [comment]
I'm not going to roll anything until its a workday again 😄

**Pull request merged**
