### PR TITLE
Remove rasterizerTracingThreshold, checkerboardRasterCacheImages, and checkerboardOffscreenLayers, etc

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by chinmaygarde — COMMENTED** [review]
Should this follow the deprecation policy?

**Comment by Hixie** [comment]
I expect this to not count as a breaking change per the [breaking change policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change), but it's hard to tell before we try to roll it into the framework, because flutter/tests doesn't support pre-commit testing for the engine repo.

**Comment by chinmaygarde** [comment]
Yeah, I suspect thats why these old APIs have stuck around for so long. Perhaps break these up into separate patches so for each removal. But I'm fine removing everything wholesale as well.

**Review by chinmaygarde — APPROVED** [review]

**Comment by Hixie** [comment]
downstream: https://github.com/flutter/flutter/pull/147663
documentation: https://github.com/flutter/website/pull/10484

**Pull request merged**
