### PR TITLE
[Impeller] Reverse the clip replay order when StC is enabled.

### PR DESCRIPTION
**Pull request by bdero**
Attempt at partially addressing https://github.com/flutter/flutter/issues/144748.

With the new depth clipping scheme, clips are order independent. So we can replay the clips in reverse to reduce framebuffer churn.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The overhead seems to be CPU based though, why would framebuffer churn be the issue?

**Comment by jonahwilliams** [comment]
Here is one of the frames from CI:

### Before

image

### After

image

I would start with a CPU profile?

**Comment by jonahwilliams** [comment]
Do we no longer create clip restore contents with depth clipping?

**Comment by jonahwilliams** [comment]
I think I know what is happening, before we would remove old clips when the paired restore was added, so the set of clips didn't really grow much. But now we don't have restores so the set of clips keeps growing.

We might need a smarter technique for restoring the depth values.

**Comment by bdero** [comment]
> The overhead seems to be CPU based though, why would framebuffer churn be the issue?

True, must be the extra draw calls...

After I went to bed I realized this isn't going to make a difference either way because most of the clips already collapse to the same or reversed depth.

> I think I know what is happening, before we would remove old clips when the paired restore was added

Yeah I think you're right. This should be an easy fix once I get a sec today.

**Pull request closed without merging**
