### PR TITLE
[Impeller] fixed units for memory measurement

### PR DESCRIPTION
**Pull request by gaaclarke**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
But we're reporting the units as MB and not MiB.

**Comment by gaaclarke** [comment]
> But we're reporting the units as MB and not MiB.

Yea, they are unfortunately used interchangeably.  MB can mean MiB.

**Comment by jonahwilliams** [comment]
But maybe I meant MB and not MiB :)

At any rate, please update allocator_vk too so these are in sync.

**Review by jonahwilliams — COMMENTED** [review]
This one: https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/allocator_vk.cc#L512-L523

**Comment by gaaclarke** [comment]
> But maybe I meant MB and not MiB :)

I thought it mentioned it elsewhere.  The convention is that disk space is measured in decimal units, but RAM is measured in power of 2 units 🙃

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
This doesn't quite sit right. We measure in bytes but the reported units can be anything. I think we can make this better by having typed sizes similar to the chrono variants.

**Pull request merged**
