### PR TITLE
changed the docs

### PR DESCRIPTION
**Pull request by Abhishek01039**
Screenshot 2021-01-26 at 1 26 02 PM

**The app is running fine on my simulator even after override the fuchsia platform and docs say it causes an error but it running fine.**

So I have removed that line of documentation.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please review this PR?
Thanks

**Comment by Hixie** [comment]
If it's not needed any more we should just remove the hack, not half the comment leaving the other half with a trailing comma...

**Comment by Abhishek01039** [comment]
```This is a hack to make Flutter think you are running on Google Fuchsia.```
This comment is needed I guess @Hixie

**Comment by chinmaygarde** [comment]
The comment is necessary for custom embedders. The example is in the glfw directory which is a custom embedder implementation. The sample project generated for you to run in the simulator will not contain that message. The comment holds so let's not remove it.

**Pull request closed without merging**
