### PR TITLE
Do not call restartInput twice when setting a new text input client.

### PR DESCRIPTION
**Pull request by jason-simmons**
If restartInput is called twice in quick succession, then the IME may output
warnings related to usage of the obsolete connection resulting from the first
call.

Fixes https://github.com/flutter/flutter/issues/10730

### CODE REVIEW

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
Can this be tested?

**Comment by jason-simmons** [comment]
AFAIK we don't have a good solution for unit testing of Android Java code in the engine

**Comment by Hixie** [comment]
Can we use existing Java unit test frameworks to do it?

**Pull request merged**
