### PR TITLE
fix null access for CkParagraph.dispose

### PR DESCRIPTION
**Pull request by dnfield**

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by dnfield** [comment]
@yjbanov let me know if this still makes sense.

**Comment by dnfield** [comment]
I feel like I might be missing something about the distinction between `delete` and `didDelete`

**Comment by yjbanov** [comment]
`delete` and `didDelete` only affect Safari 13 and older, which did not support `FinalizationRegistry` (a.k.a. weak refs).

**Pull request merged**
