### PR TITLE
Delete `ci/lint.sh`, which is no longer used.

### PR DESCRIPTION
**Pull request by matanlurey**
Found out while working on https://github.com/flutter/flutter/issues/134969.

I suspect this stopped being used when we sharded out the Clang Tidy builders?

### CODE REVIEW

**Review by zanderso — COMMENTED** [review]
I suspect there are references in a small number of docs or comments that you'll find by grepping the repo for 'lint.sh'.

**Comment by matanlurey** [comment]
Yeah reasonable. I'll take a quick look, I didn't see anything _in_ the repo.

**Comment by matanlurey** [comment]
Ok, did find a few places to update :). PTAL!

**Review by zanderso — APPROVED** [review]
Thanks!

**Pull request merged**
