### PR TITLE
add todo comment about outdated asset manifest fallback

### PR DESCRIPTION
**Pull request by andrewkolos**
Adds a todo comment linking to https://github.com/flutter/flutter/issues/128619

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
Why are you adding a TODO instead of removing it?

**Comment by jonahwilliams** [comment]
Or you could fix it?

**Comment by andrewkolos** [comment]
> Or you could fix it?

I could try. The reason I resorted to a TODO is that I haven't tried building/testing engine changes before and was prioritizing other things. I wanted to at least get a TODO comment in for the scenario where this doesn't get addressed for a while and someone else comes across this code and would be confused by it otherwise (also to prevent https://github.com/flutter/flutter/issues/128619 from being lost).

**Comment by jonahwilliams** [comment]
I mean if its not important enough to work on thats fair, but then I don't think its important enough to check in a todo either. The issue is good enough

**Comment by andrewkolos** [comment]
Fair enough

**Pull request closed without merging**
