### PR TITLE
NNBD migration for //testing

### PR DESCRIPTION
**Pull request by dnfield**
Addresses two of the items in https://github.com/flutter/flutter/issues/71507

verify_exported seems to "just work." Unfortunately, I don't think it will be run in CI until post submit and I may not have covered all the cases exercised there in my quick local test.

The parse_and_send stuff was relatively trivial to migrate. The fallout if there is anything bad there is we may not get benchmark data showing up.

### CODE REVIEW

**Comment by zanderso** [comment]
Looks like the benchmark runner has some non-null-safe dependencies.

**Comment by dnfield** [comment]
metrics_center is assuming some values can't be null in the JSON when in fact they can.

For example, in sound null safety it fails to parse a benchmark json stub like 

```json
{
      "name": "ParagraphFixture/TextBigO_RMS",
      "family_index": 5,
      "per_family_instance_index": 0,
      "run_name": "ParagraphFixture/TextBigO",
      "run_type": "aggregate",
      "repetitions": 1,
      "threads": 1,
      "aggregate_name": "RMS",
      "aggregate_unit": "percentage",
      "rms": 4.8948864875330522e-01
    },
```

because it has no `time_unit` key.

It will need to be patched and rolled into the engine.

**Comment by dnfield** [comment]
https://github.com/flutter/packages/pull/2347 needs to roll into this to work.

**Comment by dnfield** [comment]
This looks like it'll be green now.

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
