### PR TITLE
MacOS: Release backbuffer surface when idle

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/85971

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Perhaps we should have a mechanism in the engine that tells embedders when it is suitable to release such resources? I do think the idea here is sound though.

**Comment by knopp** [comment]
> Perhaps we should have a mechanism in the engine that tells embedders when it is suitable to release such resources? I do think the idea here is sound though.

I think it is the other way around :) Generally the engine asks for a buffer and then renders to it. It doesn't know anything about the buffering scheme, nor it needs to (except for partial redraws which is a separate isse)  Also I think that macOS right now is the only platform where we're completely in charge of buffer management and can actually release back buffer when not needed.

**Comment by iskakaushik** [comment]
Finally got a chance to try this out. Thanks for the PR @knopp. LGTM

**Review by iskakaushik — APPROVED** [review]

**Comment by iskakaushik** [comment]
@knopp : I think this doesn't handle the following case:

1. Surface has been obtained, but wasn't rendered to in a while.
2. We free the back-buffer after 1 sec of inactivity.
3. Swap-buffers will fail.

One manifestation of this is: https://github.com/flutter/flutter/issues/86932.

**Comment by knopp** [comment]
The delay timeout should be killed as soon as the surface is requested (inside `ensureBackBuffer`). This is quite weird. I'll look into this as soon as possible.

**Comment by knopp** [comment]
See https://github.com/flutter/flutter/issues/86932#issuecomment-887647302 for explanation of what is going on. Fortunately this should be a fairly straightforward fix.

**Pull request merged**
