### PR TITLE
Build a GTK4 version of libflutter_gtk

### PR DESCRIPTION
**Pull request by robert-ancell**
Since only recent versions of GTK4 will work with Flutter we need to continue to support GTK3. This draft PR is the first stage of this and compiles two versions of the libflutter_gtk library to support both 3 and 4. The GTK4 library won't be useful at this point, that is being tackled in https://github.com/flutter/engine/pull/50960. I expect it will make sense to break out classes from FlView so we can more easily handle both GTK3 and 4 without too many confusing ifdefs.

At this point the first thing that needs confirming is this is a suitable way of building two libraries using gn, and making those rules as clear and concise as possible (they currently have a lot of copied code).

### CODE REVIEW

**Comment by robert-ancell** [comment]
@chinmaygarde would love some help on how the gn rules should look!

**Comment by chinmaygarde** [comment]
I highly recommend having the GN reference handy for this as that's what I am using throughout this reply. You can either access it online at https://gn.googlesource.com/gn/+/main/docs/reference.md or `gn help` at the command line.

It seems like you want to build a source set multiple times. Each with a different config applied to it. Besides the different config (and perhaps the name of the output artifacts), a lot of details seem to be the same.

Remember that a GN source_set, shared_library, executable, etc.. will only result in its sources being processed once. But you can use a template instead (`gn help template`) and stamp multiple targets from a template. The way the template is put together can be mostly identical to the source_set. But you will have to instantiate the template as many times as you need. In the template implementation, you’ll need to control the config based on template arguments.

Some rough pseudo code:

```gn
template("flutter_linux") {
  assert(defined(invoker.gtk_version), "The GTK version must be specified")

  shared_library(target_name) {
    # Tip: See `gn help forward_variables_from`
    if (defined(invoker.output_name)) {
      output_name = invoker.output_name
    }

    # All the common stuff goes here.
    sources = [
      "a.cc",
      "a.h",
    ]

    # This make it easier to use in string interpolation.
    gtk_version = invoker.gtk_version

    # Now, do stuff that is specific to the GTK version. I'd put everything
    # specific to a version in its own public and private configs. That way, it
    # cleaner and easier to maintain and reuse.

    # This assumes there is a :public_gtk3 and :public_gtk4 defined already.
    public_configs = [ "//path/to/config:public_gtk$gtk_version" ]

    # This assumes there is a :private_gtk3 and :private_gtk4 defined already.
    configs = [ ":private_gtk$gtk_version" ]

    # Follow the same pattern or use conditionals. Like so:
    if (gtk_version == "4") {
      deps = [ "something/only/4/needs" ]
    }
  }
}

# Now, stamp the templates

group("flutter_linux") {
  flutter_linux("gtk4") {
    gtk_version = "4"
    output_name = "flutter_linux_gtk4"
  }
  flutter_linux("gtk3") {
    gtk_version = "3"
    output_name = "flutter_linux_gtk3"
  }
  deps = [
    "gtk3",
    "gtk4",
  ]
}
```

**Comment by Piinks** [comment]
(PR triage): Hey @robert-ancell, thanks for your continued contributions! Is this PR still on your radar?

**Comment by robert-ancell** [comment]
Closing this, not currently working on it.

**Comment by kjxbyz** [comment]
GTK4 support dropped?

**Comment by robert-ancell** [comment]
Currently working on multi-view support in GTK3, which seems like it won't require the migration to GTK4 as we previously though.

**Pull request closed without merging**
