### PR TITLE
Roll Dart to 32396138ff733cbe8d9ac32178e6cffccdf80644

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by cbracken** [comment]
So close...

LGTM, but fails Travis.

**Comment by aam** [comment]
Have you considered updating Dart deps (tools/dart/create_updated_flutter_deps.py ) ?

**Comment by jason-simmons** [comment]
Done

**Comment by jason-simmons** [comment]
Reverted the update of the other Dart deps because it still causes the StreamTransformerBase error seen in https://github.com/flutter/engine/pull/4641

@leafpetersen

**Comment by leafpetersen** [comment]
I've been seeing these kind of errors crop up.  Usually it means that you are trying to build code which uses StreamTransformerBase (that is, which relies on post dev.20 or later) with a pre dev.20.  I commented in somewhat more detail on #4641 .

**Pull request merged**
