### PR TITLE
Roll buildroot to pick up disable NSAsserts in release builds

### PR DESCRIPTION
**Pull request by jmagman**
Roll https://github.com/flutter/buildroot/pull/860 "Disable NSAsserts in release builds"

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
From PR review triage: If it's not possible to roll a buildroot change into the engine as a fast follow-on, then the best practice would be to revert the buildroot change in case other changes to the buildroot need to be rolled in.

**Comment by jmagman** [comment]
Roger, will do that next time. 
https://github.com/flutter/engine/pull/53048 just merged so I'll merge on top. If it still doesn't work I'll revert the buildroot PR.

**Comment by jmagman** [comment]
```
 ❌ Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:
 /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:140:38: error: Dictionary value cannot be nil [clang-analyzer-osx.cocoa.NilArg,-warnings-as-errors]
   140 |   NSMutableDictionary* keyMessage = [@{
       |                                      ^
   141 |     @"keymap" : @"macos",
   142 |     @"type" : type,
       |               ~~~~
 /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:114:3: note: 'type' initialized to nil
   114 |   NSString* type;
       |   ^~~~~~~~~~~~~~
 /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:115:3: note: Control jumps to the 'default' case at line 134
   115 |   switch (event.type) {
       |   ^
 /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:135:7: note: Loop condition is false.  Exiting loop
   135 |       NSAssert(false, @"Unexpected key event type (got %lu).", event.type);
       |       ^
 ../../../flutter/prebuilts/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:134:40: note: expanded from macro 'NSAssert'
   134 | #define NSAssert(condition, desc, ...) do {} while (0)
       |                                        ^
 /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm:140:38: note: Dictionary value cannot be nil
   140 |   NSMutableDictionary* keyMessage = [@{
       |                                      ^
   141 |     @"keymap" : @"macos",
   142 |     @"type" : type,
       |               ~~~~
```
Still failing:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8746478531016733745/+/u/test:_test:_lint_host_debug/stdout

**Comment by jmagman** [comment]
Closing for now. https://github.com/flutter/buildroot/pull/864

**Pull request closed without merging**
