### PR TITLE
[macOS] Archive universal gen_snapshot binaries

### PR DESCRIPTION
**Pull request by cbracken**
In #53524, we started producing universal `gen_snapshot_arm64` and `gen_snapshot_x64` binaries. This migrates away from bundling `gen_snapshot` binaries with x64-only host architecture to universal binaries that bundle both x64 and arm64 host architectures.

Also adds a dependency on `flutter/lib/snapshot:create_macos_gen_snapshots` to the profile build, where it was previously missing. Presumably, `gen_snapshot` was being built as a side-effect of one of the other targets.

Issue: https://github.com/flutter/flutter/issues/101138
Issue: https://github.com/flutter/flutter/issues/69157

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I have looked into the abyss of our archive generation tooling, and have developed deep sense of dread.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm

you might run into trouble with this:

https://github.com/flutter/engine/blob/main/ci/builders/mac_ios_engine.json#L518

but I believe it is safe to delete, to so.

**Comment by cbracken** [comment]
I'm fairly convinced that `gen_snapshot` is the unused arm64-only gen_snapshot in the tool cache; I've got a followup that removes this to see if anything explodes, but my sense is that given this would have been unusable on Intel Macs for well over a year now, that we should have had bug reports from Intel Mac users by now if it were used.

**Review by jmagman — APPROVED** [review]

**Comment by christopherfujino** [comment]
> auto label is removed for flutter/engine/53962, due to - The status or check suite [Mac mac_host_engine](https://cr-buildbucket.appspot.com/build/8742147839192596721) has failed. Please fix the issues identified (or deflake) before re-applying this label.

Whoops:

```
Cannot find gen_snapshot at /Volumes/Work/s/w/ir/cache/builder/src/out/ci/mac_profile_arm64/gen_snapshot_arm64
```

**Comment by cbracken** [comment]
Fixed: turns out we never actually depended on the lib/snapshots:create_macos_gen_snapshots target (or the archive target we used to depend on)... but only for profile mode. Therefore it didn't show up in my find-and-replace patch yesterday to swap the dependency to the `create_macos_gen_snapshots` target. The old unsuffixed one is build as a side-effect of one of the other targets being depended on, the new ones aren't.

**Pull request merged**
