### PR TITLE
Remove unused iOS and macOS podspecs

### PR DESCRIPTION
**Pull request by jmagman**
The iOS and macOS podspecs are unused by the framework since https://github.com/flutter/flutter/pull/72020 and https://github.com/flutter/flutter/pull/70224 respectively.  Remove them from the engine.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
The failure looks related. Possibly a recipe update is necessary. But the PR looks good to me!

**Comment by jmagman** [comment]
> The failure looks related. Possibly a recipe update is necessary. But the PR looks good to me!

Yes, I'm on it, I got stuck trying to get the right version of python on my M1 that can run `git cl` to put out a recipe change... Please hold. 🙂

**Comment by jmagman** [comment]
(This is still on my radar, I'll circle back soon)

**Comment by jmagman** [comment]
Recipe change @ https://flutter-review.googlesource.com/c/recipes/+/29840

**Pull request merged**
