### PR TITLE
Add comments to build_and_test_linux_unopt_debug

### PR DESCRIPTION
**Pull request by liyuqian**
Clarify that the test depends on the framework repo. It may fail if the framework repo is broken, so the engine committer don't need to be in panic.

This is inspired by the failure in https://github.com/flutter/engine/pull/17538/checks?check_run_id=565790440 , which was caused by the problem mentioned in https://github.com/flutter/flutter/pull/54176.

### CODE REVIEW

**Comment by liyuqian** [comment]
@fkorotkov : how may I add a custom error info to a Cirrus task so it can be shown when it failed?

**Comment by fkorotkov** [comment]
@liyuqian there is no such option at the moment. Not sure where it can be displayed 🤔 

One thing you can do is to create a separate script after `fetch_framework_script` to validate Cirrus was not failing (passing or building) for the sha:

```yaml
verify_framework_script:
  - echo "Checking framework was passing..."
  - curl -s https://api.cirrus-ci.com/github/flutter/flutter.json | grep -q passing
```

That way `verify_framework_script` will fail if the latest builds on `flutter/flutter` was failing.

**Comment by liyuqian** [comment]
Thanks @fkorotkov ! I'll do that.

BTW, I have a strange issue: I can't access https://cirrus-ci.com/github/flutter/flutter if I'm logged in, but I can read it from Incognito mode:

Screen Shot 2020-04-07 at 11 23 47 AM

**Comment by fkorotkov** [comment]
@liyuqian very weird. I can see that GitHub was reporting that you have `none` permissions for couple of hours for bunch of `flutter` org repositories which doesn't make sense since they are public. 🤔Will add some logic to elevate permissions for such cases. It should start working soon either when I'll add the logic or when caches will expire and GH will return correct permissions.

**Pull request merged**
