### PR TITLE
[Impeller] Fix division by zero for transparent shadows (#41391)

### PR DESCRIPTION
**Pull request by gaaclarke**
cherry-pick of https://github.com/flutter/engine/pull/41391

### CODE REVIEW

**Comment by zanderso** [comment]
It looks like the includes in the test might need some adjustment to build cleanly.

**Comment by XilaiZhang** [comment]
umm friendly ping on this pr, if we can fix the tests early we can make it for the stable hotfix this week

**Comment by XilaiZhang** [comment]
cc @CaseyHillers

**Comment by gaaclarke** [comment]
yep, one sec

**Comment by bdero** [comment]
I think this branch was cut before Jim's large DL refactor. These imports need to be renamed to `display_list_*.h`.

**Comment by gaaclarke** [comment]
My GOMA setup has broken down, pushing speculative fix while I address it locally.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
