### PR TITLE
Only handle refresh intent when the app is marked as debuggable.

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Do we need to update the template or docs here?
https://stackoverflow.com/questions/2952140/android-how-do-i-mark-my-app-as-debuggable

Does `flutter run` need to yell at you if you haven't marked your app as debuggable? (since hot reload will now fail in a strange way?)

**Comment by jason-simmons** [comment]
Debug builds should automatically insert the debuggable attribute into the app's manifest

**Comment by tvolkert** [comment]
> since hot reload will now fail in a strange way

FTR, hot reload doesn't use this code path - it communicates directly over the VM service protocol.  This code path allows developers to use `adb` to trigger a reload (and is also wired up to the initial app start if the user specified `flutter run --route=<route>`)

**Pull request merged**
