### PR TITLE
Fix cursor misplacement problem when text-align is center or right.

### PR DESCRIPTION
**Pull request by alimahdiyar**
fixed issue flutter/flutter#53057

### CODE REVIEW

**Comment by alimahdiyar** [comment]
I couldn't find documentation for running test files on the engine.
I think you should add it to your contribution guide.

**Comment by alimahdiyar** [comment]
@GaryQian @justinmc

**Comment by justinmc** [comment]
I tried running this locally and it improves the situation, but I still see a problem:



To reproduce:

  1. Create a multiline input with `textAlign: TextAlign.right`.
  1. Type some text on the first line.
  1. Hit return to go to the second line and type some text there.
  1. Press the up arrow.
  1. Type more text. The cursor appears on the left but text is inserted on the right.

**Comment by jason-simmons** [comment]
Thank you for the PR, and sorry for taking so long to review it.

I looked at this bug and posted a PR with a solution that I believe will work for all text alignment modes.  See https://github.com/flutter/engine/pull/17744

**Comment by alimahdiyar** [comment]
Thanks for your review.
So I'm closing this one.

**Pull request closed without merging**
