### PR TITLE
Make sure that 'setInitialRoute' works fine for a developer create engine.

### PR DESCRIPTION
**Pull request by kangwang1988**
Make sure that 'setInitialRoute' works fine when a developer creates their own engine and call runWithEntryPoint before pushing a FlutterVC.

This will fix: https://github.com/flutter/flutter/issues/27216

### CODE REVIEW

**Comment by kangwang1988** [comment]
@dnfield 
In fact, now HandleInitialRoutePlatformMessage only affects `platform->flutter` delivery.
The `flutter->platform` will not enter Engine::DispatchPlatformMessage, its callstack is as below:
screen shot 2019-01-30 at 2 13 46 am

So I think it would be better if we can process kNavigationChannel distinguishly, according to if its a setInitialRoute message.

**Comment by dnfield** [comment]
Yes, but calling this method still won't work even with this patch - there's nothing in the framework to notify Flutter that the value has changed.  The `Navigator` class wouldn't check for the updated message.  Right now, the best way to handle this case is to jus timplement a custom message channel.

**Comment by chengge0921** [comment]
hello,  I  creat FlutterEngint in AppDelegate， and use setInitialRoute after {let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine;
    let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)!;} before {self.present(flutterViewController, animated: false, completion: nil)},
but it dosen‘t work， what should I do ?

**Comment by cbracken** [comment]
@kangwang1988 are you planning to update this patch based on review? Let us know what you'd like us to do.

**Comment by dnfield** [comment]
@chengge0921 this isn't quite the right place to get an answer to that question.  Please feel free to post it to the flutter-dev@googlegroups.com mailing list, or to StackOverflow!

**Comment by kangwang1988** [comment]
@cbracken 
Let me determine if there is a better solution for it in this week. If not, I will close it.

**Comment by ungacy** [comment]
请问这个什么时候会合进去, 现在集成到项目时卡在这个bug上了~ @kangwang1988

**Comment by cbracken** [comment]
@kangwang1988 closing this for the time being. Please let us know if you have an alternate design in a new PR.

**Comment by zzjjob** [comment]
1. create FlutterEngine
2. [_engine.get() createShell:nil libraryURI:nil];
    [_engine.navigationChannel invokeMethod:@"setInitialRoute" arguments:route];
3. self.flutterVc = [[FlutterViewController alloc] initWithEngine:engine nibName:nil bundle:nil];
    [engine launchEngine:nil libraryURI:nil];
    [engine setViewController:self.flutterVc];

**Pull request closed without merging**
