### PR TITLE
Run engine unit tests on mac host_debug_unopt_arm64

### PR DESCRIPTION
**Pull request by zanderso**
Related https://github.com/flutter/flutter/issues/142868

### CODE REVIEW

**Comment by zanderso** [comment]
Copying this out before I hit retry:
```
[ RUN      ] Play/BlitPassTest.BlitAcrossDifferentPixelFormatsFails/Metal
-[MTLDebugDevice newTextureWithDescriptor:]:1017: failed assertion `Texture Descriptor Validation
Memoryless texture need to have renderable PixelFormat.
```

**Comment by chinmaygarde** [comment]
Can we file issues for the failing validations?

**Comment by jonahwilliams** [comment]
I'm just going to push fixes to this PR.

**Comment by jonahwilliams** [comment]
@zanderso I think the remaining failure is a builder config problem?

```
Running command "python3 test.py"
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    raise Exception(
Exception: Could not locate font-subset in host_debug or host_debug_unopt - build before running this script.

```

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/143324

**Comment by zanderso** [comment]
> @zanderso I think the remaining failure is a builder config problem?

Yeah, that looks like the font-subset test script is hardcoding some strings that should be arguments instead. I can take a look at that.

**Comment by zanderso** [comment]
I've cleaned up an fixed the font-subset test script. The last remaining failure is `EmbedderTest.CompositorMustBeAbleToRenderKnownSceneWithSoftwareCompositor`, which I'm not sure how to address. It looks like an ad-hoc pixel test.

**Review by jonahwilliams — APPROVED** [review]
LGTM, thanks @zanderso !

**Comment by zanderso** [comment]
Next error:

From
```
impeller_unittests --gtest_repeat=2 --gtest_shuffle --enable_vulkan_validation --gtest_filter=-*OpenGLES
```

```
[ RUN      ] Play/BlitPassTest.BlitAcrossDifferentPixelFormatsFails/Metal
-[MTLDebugDevice newTextureWithDescriptor:]:1017: failed assertion `Texture Descriptor Validation
Memoryless texture need to have renderable PixelFormat.
'
```

**Review by jonahwilliams — COMMENTED** [review]
Actually you blew away my patch to fix the test by force pushing.

**Comment by zanderso** [comment]
> Actually you blew away my patch to fix the test by force pushing.

Ooooops

**Comment by jonahwilliams** [comment]
The fix is to change the failing test to the following:

```
TEST_P(BlitPassTest, BlitAcrossDifferentPixelFormatsFails) {
  ScopedValidationDisable scope;  // avoid noise in output.
  auto context = GetContext();
  auto cmd_buffer = context->CreateCommandBuffer();
  auto blit_pass = cmd_buffer->CreateBlitPass();

  TextureDescriptor src_desc;
  src_desc.format = PixelFormat::kA8UNormInt;
  src_desc.size = {100, 100};
  src_desc.storage_mode = StorageMode::kHostVisible;
  auto src = context->GetResourceAllocator()->CreateTexture(src_desc);

  TextureDescriptor dst_format;
  dst_format.format = PixelFormat::kR8G8B8A8UNormInt;
  dst_format.size = {100, 100};
  dst_format.storage_mode = StorageMode::kHostVisible;
  auto dst = context->GetResourceAllocator()->CreateTexture(dst_format);

  EXPECT_FALSE(blit_pass->AddCopy(src, dst));
}
```

**Pull request merged**
