### PR TITLE
Explicitly make the X connection for EGL.

### PR DESCRIPTION
**Pull request by robert-ancell**
## Description

Explicitly make the X connection for EGL.
EGL can mistakenly choose the GBM backend when using EGL_DEFAULT_DISPLAY.

## Related Issues

https://github.com/flutter/flutter/issues/60429

## Tests

No tests changed.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by wmww — APPROVED** [review]
LGTM and works on my machine

**Review by stuartmorgan — APPROVED** [review]
Just comment nits; LGTM.

**Comment by gaaclarke** [comment]
@stuartmorgan @robert-ancell This PR has turned the tree red: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/7258  The failure sounds apropos so I'm going to revert this for now.

**Comment by stuartmorgan** [comment]
> The failure sounds apropos

Where are you seeing a related failure? I just see `ShellTest.ResubmitFrame` which is below the level of the Linux embedding (where all of these changes are).

**Comment by gaaclarke** [comment]
I didn't debug the issue but a change to X and EGL setup affecting a test related to frames was plausible enough to merit reverting.  If you think the failure was unrelated please file a separate issue for the flake with your evidence.

**Comment by stuartmorgan** [comment]
> If you think the failure was unrelated please file a separate issue for the flake with your evidence.

I've made a PR to re-land; that will give us conclusive evidence one way or the other. If it was indeed flake, I'll file the issue.

**Comment by stuartmorgan** [comment]
(But to be clear, the evidence so far for this not being connected is that no files changed by this PR should be compiled into a the unit test binary that had the failing test.)

**Comment by gaaclarke** [comment]
I've seen this test fail again without this PR.  I think that's a pretty good indicator that it wasn't related to this PR if you want to reland https://github.com/flutter/flutter/issues/68540

**Pull request merged**
