### PR TITLE
Scribble method namespace

### PR DESCRIPTION
**Pull request by justinmc**
In the framework (https://github.com/flutter/flutter/pull/104128), the scribble feature is being moved out of TextInputClient and into its own class.  This PR updates the naming of the platform channel methods to match their new names in the framework.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Depends on https://github.com/flutter/flutter/pull/104128

**Review by cyanglaz — COMMENTED** [review]
Should we do a phased release where both method channel exist so there is no bad commit?

1. Land engine with both channel
2. Land framework
3. Remove old channel from engine.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by justinmc** [comment]
@cyanglaz Good idea about doing this in stages.  I've added back the TextInputClient usages so this PR now has both.  I'll come back and remove them after this and the framework PR land.

**Review by cyanglaz — APPROVED** [review]
LGTM

**Pull request merged**
