### PR TITLE
[macOS] Fixes Crash of cxx destruction when App will terminate

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixes https://github.com/flutter/flutter/issues/90783#issuecomment-955040004. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
This seems like a good change, when the app is terminated it won't `dealloc` the engine, which is the only place it's currently explicitly shut down.

@stuartmorgan do you see any gotchas here? (@chunhtai is OOO)

**Comment by stuartmorgan** [comment]
The obvious downside is that this will slow down quitting the app. Better slow than crashing, but it's unusual to have to do explicit object teardown in the exit flow.

I'm trying to understand from the discussion in the other PR why it's necessary. @chinmaygarde does the engine violate the C++ style guide's prohibition on global objects with non-trivial destructors?

**Comment by chinmaygarde** [comment]
> does the engine violate the C++ style guide's prohibition on global objects with non-trivial destructors?

Oh yeah. All over the place. There used to be an old Clang plugin built on libTooling that could detect such objects in the static storage duration. We had trouble getting it working on the platforms Flutter needs to build for. Maybe there is a built in warning for that now. I am not sure. In any case, there should only be a few cases in the engine that we can fixup. I am not sure about our dependencies though.

> The obvious downside is that this will slow down quitting the app.

This isn't anything new though as the non-trivial destructors are still being called. Its just that they are crashy today because of unstable call order.

**Review by chinmaygarde — APPROVED** [review]

**Review by jmagman — COMMENTED** [review]
Forgot to formally LGTM

**Comment by stuartmorgan** [comment]
> > The obvious downside is that this will slow down quitting the app.
> 
> This isn't anything new though as the non-trivial destructors are still being called. Its just that they are crashy today because of unstable call order.

Well, presumably it'll do more now. But mostly I meant that ideally the fix would be to not have the violations in the first place, rather than to cater to them with more explicit tear-down.

**Comment by zhongwuzw** [comment]
Maybe related contexts of similar crash: [React Native](https://github.com/facebook/react-native/pull/22607) and [ComponentKit](https://github.com/facebook/componentkit/pull/906)

**Pull request merged**
