### PR TITLE
Use flutter in an existing project. And open a new UIViewController through flutter channel, if you switch to the background at this time, or the phone goes out. When the user enters the app again, it triggers the foreground notification of the FlutterViewController, causing the flutter engine to run, which may cause the app to crash.

### PR DESCRIPTION
**Pull request by chundong**
if the last view controller in the array is not FlutterViewController , don't invoke flutter engine when application became active。app may crash

### CODE REVIEW

**Comment by chundong** [comment]
I signed it!

**Comment by chundong** [comment]
I signed it!

**Comment by chundong** [comment]
use flutter in an existing project, flutter opens a UIViewCOntroller and goes back in the background and returns, because the notification is not removed, the flutter engine is turned on.

**Comment by dnfield** [comment]
Can you show a demo of this crash?

**Comment by dnfield** [comment]
Ideally, can you write a test that makes it happen via XCTest or EarlGrey or something like that?

**Comment by cbracken** [comment]
@chundong Thanks for your contribution. Without additional information, we are unfortunately not sure how to proceed with this PR. We are therefore reluctantly going to close the PR for now. Please don't hesitate to comment on the PR if you have any more information for us; we will reopen it right away!

**Pull request closed without merging**
