### PR TITLE
[Impeller] Set resourceOptions/storageMode on MTLTextures created from MTLBuffers.

### PR DESCRIPTION
**Pull request by dnfield**
Fix https://github.com/flutter/flutter/issues/114110

Enable metal validation when running impeller unittests .. or try to anyway.

### CODE REVIEW

**Comment by zanderso** [comment]
It looks like the unit test failures are related.

**Comment by dnfield** [comment]
Yes, and failure means that the updates to run_test are enabling metal validation.

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
Neat, I didn't think to enable this on a per test basis.

**Comment by dnfield** [comment]
These tests are passing on an M1 but not on the CI x64 machines, need to figure out whether we can suppor tthis API in that configuration or not.

**Comment by dnfield** [comment]
Oh goodness Iw as looking at the wrong test.

**Comment by dnfield** [comment]
Unfortunately, the updated env vars to run_tests.py do _not_ trigger failures without this change. However, adding the ones that Xcode uses trigger many other failures that seem not quite right.

**Comment by dnfield** [comment]
I'm going to land this to at least get the existing tests working on development machines. Maybe we can figure out how to make this work across architectures and on CI separate from this patch.

**Pull request merged**
