### PR TITLE
Remove unused code from licenses script

### PR DESCRIPTION
**Pull request by goderbauer**
Code became obsolete with https://github.com/flutter/engine/pull/3627.

Also fixes mix-in syntax and marks class as private. With the latter the anaylser tells us in the future if there are unused classes in the file.

### CODE REVIEW

**Comment by goderbauer** [comment]
The yellow check actually passed, but didn't update on github.

**Comment by aam** [comment]
This broke linux buildbot (and dart flutter head-head-head as well).
```
Got dependencies!
  error • Classes can only extend other classes at flutter/tools/licenses/lib/filesystem.dart:307:33 • extends_non_class
...
168 errors, 18 lints and 11 hints found.
Failed.
```

**Comment by goderbauer** [comment]
Can you please link to the failure?

**Comment by aam** [comment]
https://build.chromium.org/p/client.flutter/builders/Linux%20Engine/builds/4239/steps/analyze%20dart_ui/logs/stdio

**Pull request merged**
