### PR TITLE
[web] Reland: (Add `crossOrigin` property to `<img>` tag used for decoding)++

### PR DESCRIPTION
**Pull request by mdebbar**
Relands https://github.com/flutter/engine/pull/54961 with a few more changes and tests.

Fixes https://github.com/flutter/flutter/issues/160127

### CODE REVIEW

**Comment by yjbanov** [comment]
Let's hotfix this in stable.

**Comment by Reprevise** [comment]
Has the cherry-pick request been created yet?

**Comment by putnokiabel** [comment]
@Reprevise I submitted [#160819](https://github.com/flutter/flutter/issues/160819) but I haven't received a reaction on it yet and not sure I did it correctly (as it's the first time I submit a CP request).

**Comment by Reprevise** [comment]
Maybe @yjbanov can take a look?

**Pull request merged**
