### PR TITLE
[web] Unskip tests that are already passing in Safari

### PR DESCRIPTION
**Pull request by mdebbar**
Partial fix for https://github.com/flutter/flutter/issues/50596

### CODE REVIEW

**Comment by mdebbar** [comment]
@nturgut I noticed you skipped many tests in `paragraph_test`, `text_test` and `measurement_test`. But when I unskip and run them locally, most of the tests are passing (except a few that I kept skipped). Were you seeing the failures on your laptop or on LUCI? Could it be that tests are passing locally but failing on LUCI for some reason?

**Comment by nturgut** [comment]
> @nturgut I noticed you skipped many tests in `paragraph_test`, `text_test` and `measurement_test`. But when I unskip and run them locally, most of the tests are passing (except a few that I kept skipped). Were you seeing the failures on your laptop or on LUCI? Could it be that tests are passing locally but failing on LUCI for some reason?

these are the latest results from LUCI. The initial run was made on my local Mac.

**Comment by mdebbar** [comment]
@nturgut thanks! The results in LUCI match the results on my macbook.

**Comment by mdebbar** [comment]
Landing on red. Fuchsia infra is broken, and my changes have nothing to do with Fuchsia.

**Pull request merged**
