### PR TITLE
Make AccessibilityNodeInfos interactive.

### PR DESCRIPTION
**Pull request by Hixie**
This exposes the actions on AccessibilityNodeInfo nodes.
It also tries to make the code that handles reloads more correct.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @jason-simmons for the runFromBundle changes

**Comment by Hixie** [comment]
Since nobody has reviewed this yet I added another commit. :-)

**Comment by chinmaygarde** [comment]
lgtm

**Comment by jason-simmons** [comment]
LGTM

**Pull request merged**
