### PR TITLE
Sanitize invalid UTF-16 paragraph text instead of throwing

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/84693

### CODE REVIEW

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
Per https://github.com/flutter/flutter/issues/39114, this is WAI. Before the buffer gets to this part of native code, it has numerous opportunities to be sanitized and transformed. To sanitize, [`Utf8Codec::decode`](https://api.dart.dev/stable/1.10.1/dart-convert/Utf8Codec/decode.html) will perform substitution of invalid characters with `U+FFFD` when the `allowMalformed:` option is set. Using [`package:characters`](https://pub.dev/packages/characters) in Dart is also an option.

This layer of typography stack should just reject invalid sequences instead of attempt to fix them on behalf of the application.

cc @Hixie

**Comment by jason-simmons** [comment]
I had previously preferred throwing on invalid input for this API.  But this appears to be causing issues for enough users that I'm wondering if we should be liberal in what we accept here.

I had forgotten about the discussion in https://github.com/flutter/flutter/issues/39114 - if that continues to be the policy then I will close this PR.

**Comment by Hixie** [comment]
There are significant security implications in general to "correcting" invalid string data in this way. We should not do this, IMHO.

**Comment by Hixie** [comment]
(That said, I think we could avoid crashing and instead render nothing, or similar. The issue cited above is right that crashing seems a little overly dramatic of us.)

**Comment by sm2017** [comment]
> There are significant security implications in general to "correcting" invalid string data in this way. We should not do this, IMHO.

@Hixie why other applications like Google Chrome do  "correcting" invalid string data, why it's not security issue for theirs?

**Comment by Hixie** [comment]
It's not especially a security issue for Chrome when rendering (and it wouldn't be really an issue for Flutter either) but the point is that the only way you get to this problem in the first place is if the data was not sanitized. It's just as much an issue for JavaScript apps as for Flutter apps.

**Comment by jason-simmons** [comment]
Changed this PR to log a warning and append a replacement character when `ParagraphBuilder::addText` is given invalid UTF-16.

@Hixie does that seem reasonable?  I'm looking for a way to indicate this error that is noticeable but does not risk terminating the app.

**Comment by Hixie** [comment]
seems reasonable

**Comment by chinmaygarde** [comment]
> I think we could avoid crashing

There is no native crash though. An exception is thrown that may be uncaught. With this change, the developer will not know why their text is not being rendered without looking at the logs. Earlier, there was a clear exception stating that validation was missing. I am not sure this is an improvement in making the error more actionable to the developer.

**Comment by Hixie** [comment]
Ah, I misunderstood the behaviour described in flutter/flutter#84693. I agree that if it's just a Dart exception, that's better.

**Comment by Hixie** [comment]
We could have the TextPainter logic catch the exception and report it (and render a replacement character), to get the best of both worlds?

**Comment by chinmaygarde** [comment]
Yeah, performing replacement in the painter makes sense. I believe the original intent was to give the developer the opportunity to sanitize input only if necessary. But I don't think this aligns with expectations from other frameworks. Always performing validation before display works for me. At the native layer, there wasn't an issue as we'd just throw a Dart exception on invalid input and not bother attempting a replacement.

**Comment by jason-simmons** [comment]
An implementation of this in the framework: https://github.com/flutter/flutter/pull/84887

**Comment by chinmaygarde** [comment]
Thanks. I think we can close this variant of the fix.

**Pull request closed without merging**
