### PR TITLE
Add .mskp file to binary format

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://bugs.chromium.org/p/skia/issues/detail?id=9467

### CODE REVIEW

**Comment by gw280** [comment]
lgtm

**Comment by gw280** [comment]
Test?

**Comment by liyuqian** [comment]
@gw280 : good question. Skia may need to PR to be merged soon to unblock their roller. Hence I created https://github.com/flutter/flutter/issues/41330 to remind us to add tests later :)

**Comment by rmistry** [comment]
Looks like you need to run the license script for those checks to pass.

**Pull request merged**
