### PR TITLE
Fix documentation build for window changes.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This fixes the framework documentation build errors resulting from https://github.com/flutter/engine/pull/20496.

It turns out that dartdoc doesn't like references to `[Window.devicePixelRatio]` if the member is simply inherited from the base class: there needs to be an `@override` for the method.

Once https://github.com/flutter/engine/pull/20496 lands in flutter/flutter, all references to `Window` will be removed, so this is a temporary issue.

Also, fixed a missing template and two other incorrect doc references.

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM :+

**Comment by liyuqian** [comment]
The test failure suggests that the `Window` class should also be added to `web_ui`.

**Comment by gspencergoog** [comment]
`web_ui` doesn't get processed for documentation, only the non-web dart:ui.  My local run of the docs build succeeds when I copy them into the framework and run it.

**Comment by gspencergoog** [comment]
Oh, I see.  It needs all the overrides in web_ui too so that the interface check doesn't fail.

**Comment by gspencergoog** [comment]
Thanks @zanderso: I was just waiting for tests to complete, and didn't notice right away when they did.

**Pull request merged**
