### PR TITLE
Fix windows popup when unit tests have failures

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/66998

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
This won't handle assertions failures in static initializers right? We should probably have a TODO for that but this is great. Thanks!

**Review by stuartmorgan — APPROVED** [review]
Windows changes LGTM. I'm not clear on what the implications are of calling the signal handler part of that code (on all platforms) when we weren't previously though.

**Comment by chinmaygarde** [comment]
> what the implications are of calling the signal handler part of that code...

All the test harnesses are meant to use the common initialization code in `//flutter/testing`. However, the txt unit-tests harness (for whatever reason) does not seem to be using it. Thats why it Dan patched it.

**Comment by dnfield** [comment]
I imagine this won't handle static initialization issues, but hopefully that doesn't impact CI as much?

**Comment by chinmaygarde** [comment]
> but hopefully that doesn't impact CI as much?

Probably not. I was thinking of the issue Jonah was running into. But this is still an improvement.

**Pull request merged**
