### PR TITLE
Revert "Roll Dart SDK from ab417bc74bb1 to c162b4979562 (1 revision)"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#44986

Many new analyzer warnings blocking the roll to the framework: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/62841/overview

cc @kallentu for https://dart.googlesource.com/sdk.git/+/8c2f088481e90949dc04f532af8600b23138ff63
cc @a-siva

### CODE REVIEW

**Review by bdero — APPROVED** [review]
STV

**Comment by zanderso** [comment]
Reverting near tip-of-tree commit without waiting for presubs to finish.

**Comment by a-siva** [comment]
Is it just this one failure or are there more.

`packages/flutter/lib/src/material/tab_controller.dart:316:16: Use &#x27;const&#x27; with the constructor to improve performance (top-level declaration) (prefer_const_constructors)`

Maybe I could fix this code and then restart the dart roller.

**Comment by a-siva** [comment]
Ignore my comment above, I see more failures.

**Comment by kallentu** [comment]
@a-siva I sent in a forward-fix for https://github.com/flutter/flutter/issues/133152 related to this issue.
Do you still see the failures? The `flutter-analyze` tryjob seems to be passing now.

**Comment by a-siva** [comment]
> @a-siva I sent in a forward-fix for [flutter/flutter#133152](https://github.com/flutter/flutter/issues/133152) here [dart-lang/sdk@b3c433c](https://github.com/dart-lang/sdk/commit/b3c433c7614e39d0dedcab2ef130bf6d0e291390). Do you still see the failures? The `flutter-analyze` tryjob seems to be passing now.

Once your forward fix lands in the dev branch I will restart the Dart roller and we can see if we still see failures. If your tryjob did not have errors I don't expect to see errors when we roll.

**Comment by zanderso** [comment]
It looks like that commit is in [3.2.0-101.0.dev](https://github.com/dart-lang/sdk/releases/tag/3.2.0-101.0.dev), so I'll trigger a manual roll to that version.

**Pull request merged**
