### PR TITLE
postTranslate in picture_layer.cc or opacity_layer.cc

### PR DESCRIPTION
**Pull request by kgdev**
Shouldn't it be preTranslate?

### CODE REVIEW

**Comment by kgdev** [comment]
I signed it!

**Comment by liyuqian** [comment]
Thanks @kgdev for the contribution! Can you please tell us what scene triggers you for having this fix? That would be helpful for adding a test to justify this PR, and to guard future regressions. It would be better if you can include that test in this PR!

**Comment by cbracken** [comment]
@kgdev if there's an existing bug you can link against, would you mind doing that? If not, as @liyuqian suggests, please provide more info here.

**Comment by cbracken** [comment]
Closing for now. If you find time to address the comments and propose an updated PR, we'll look forward to reviewing! Thanks for your contribution!

**Pull request closed without merging**
