### PR TITLE
Allow running the YAPF formatter using Python version 3.11

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by gaaclarke** [comment]
I'm guessing you tested this locally and it runs fine?  Does it just print out a deprecation warning?

**Comment by jason-simmons** [comment]
This works locally, and I did not see any deprecation warning.

Prior to https://github.com/flutter/engine/commit/ed40c59d946932c410ea3711dcc9fc292c65650e this script had been running successfully in environments where the default `python3` mapped to Python 3.11

**Review by gaaclarke — APPROVED** [review]
lgtm

**Comment by gaaclarke** [comment]
fyi yapf's stated limit is 3.10, but if it runs fine with our testing sgtm: https://github.com/google/yapf/blob/29db8b7a5a77c156b461eece673b1ee3093f9f86/pyproject.toml#L30

**Pull request merged**
