### PR TITLE
[macOS] Enable offline renderers

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description

This allows the usage of the integrated GPU on a MacBook Pro after
adding the following to `macos/Runner/Info.plist`:

```xml
<key>NSSupportsAutomaticGraphicsSwitching</key>
<true/>
```

https://github.com/flutter/flutter/pull/66185 adds this per default.

## Related Issues
https://github.com/flutter/flutter/issues/47822

## Tests
TBD

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Can you explain what analysis and/or manual testing you have done to establish that the entire Flutter rendering stack can correctly handle a dynamic GPU capability change? (I.e., that it meets all [these requirements](https://developer.apple.com/library/archive/technotes/tn2229/_index.html))

**Comment by cbenhagen** [comment]
I have built a local engine and run the engine tests on the integrated GPU of a MacBook Pro. Then I ran the gallery and some of our apps while switching between integrated and discrete GPU using pmset:

sudo pmset -a gpuswitch 0

where 0 indicates switching to discrete and can be replace with :

0 = switching to integrated
1 = switching to discrete
2 = auto switching

I have not seen any issues so far.

The docs you linked suggest to register to Display Change notifications and adapt to any changes in capabilities (such as max texture size, extensions and hardware capabilities such as the amount of VRAM). I am not familiar enough with the engine to decide if and where we should do that.

There are no PBuffers used on macOS so we can skip that part of the docs.

**Comment by stuartmorgan** [comment]
@chinmaygarde Suggestions on auditing the engine for things that would need refreshing on GPU change (which would presumably require a new embedder.h API)?

**Review by chinmaygarde — DISMISSED** [review]
I think this change is fine (I got a bit confused about `NSOpenGLPixelFormatAttribute` being a null terminated array instead of key value pairs). About @stuartmorgan comments about supporting elegant switches between different GPUs, I think we will need to add an embedder API affordance for resetting the onscreen context (a wrapper around PlatformView::NotifyCreated and NotifyDestroyed).

**Comment by stuartmorgan** [comment]
> I think this change is fine [...] I think we will need to add an embedder API affordance for resetting the onscreen context (a wrapper around PlatformView::NotifyCreated and NotifyDestroyed).

@chinmaygarde If we need an API affordance to notify the engine about changes, then isn't this change incorrect without that? If there are things in the engine that require notification about GPU changes, then we shouldn't turn on the ability for the OS to change GPUs without first plumbing that through, unless I'm missing something.

**Comment by chinmaygarde** [comment]
>  If we need an API affordance to notify the engine about changes, then isn't this change incorrect without that?

`NSOpenGLPFAAllowOfflineRenderers` should only allow selection of an offline renderer. I don't think this patch does anything to enable seamless switching.

**Comment by stuartmorgan** [comment]
> `NSOpenGLPFAAllowOfflineRenderers` should only allow selection of an offline renderer. I don't think this patch does anything to enable seamless switching.

Now I'm confused. What purpose does this flag have other than as part of a change to enable dynamic switching? I'm not understanding why we would want to allow selecting an offline renderer if we don't have the ability to take advantage of that renderer potentially coming online later.

**Comment by cbenhagen** [comment]
As far as I understand it, the best renderer will automatically be chosen in response to `[NSOpenGLView update]` whose default implementation simply calls the `update()` method of `NSOpenGLContext`.  Unless we do any hardware specific things, or user multiple GPUs simultaneously this should be enough.

**Comment by stuartmorgan** [comment]
> Unless we do any hardware specific things, or want to use multiple GPUs simultaneously this should be enough.

And have you verified that the engine doesn't do any hardware-specific checks?

@chinmaygarde said above that we would need an embedder.h affordance for informing the engine about GPU changes. If that's the case, then this patch isn't sufficient to supporting switching. If it's not, then it is, but we need confirmation of that. @chinmaygarde can you confirm one way or the other here?

**Comment by chinmaygarde** [comment]
@stuartmorgan As I said in a https://github.com/flutter/engine/pull/21285#issuecomment-702931111, I think this patch if fine to enable offline renderers. We can work on switching at a later time. I think this patch is an improvement, one I recommend we land.

**Comment by cbenhagen** [comment]
@chinmaygarde does it need tests or can it be merged without? If tests are needed can you give me a hint how they could look?

**Comment by chinmaygarde** [comment]
So, I just re-read https://developer.apple.com/library/archive/technotes/tn2229/_index.html and I had originally missed the section in "Detecting Renderer Changes" that says "... detect functionality changes. If you do not, then your OpenGL drawing may fail in various potentially catastrophic ways.". It further goes on to detail that how the application may detect this change (by querying `currentVirtualScreen` in the case of `NSOpenGLView`). My initial understanding was that the change was not mandatory. With this understanding, I am not sure this patch is resilient to switching the GPU in use.

**Comment by chinmaygarde** [comment]
Can we add the logic that detects changes to the `currentVirtualScreen` to this patch so that we don't fail in the "fail in various potentially catastrophic ways" as listed in the guidance from Apple?

**Comment by stuartmorgan** [comment]
> Can we add the logic that detects changes to the `currentVirtualScreen` to this patch so that we don't fail in the "fail in various potentially catastrophic ways" as listed in the guidance from Apple?

This gets back to my initial question above: what exactly do we need to do/call in the engine when such changes happen?

**Comment by cbenhagen** [comment]
@chinmaygarde What specific functionality (such as max texture size, extensions and hardware capabilities such as the amount of VRAM) does the engine depend on which could not be present on a new renderer?

**Comment by modulovalue** [comment]
@chinmaygarde have you had the chance to plan a followup?

**Comment by knopp** [comment]
This may need another revision. Quite a lot has changed regarding to rendering on macOS. There is now metal renderer (enabled by default) and both metal and OpenGL render into an IOSurface (which is used to back a CALayer).

**Comment by Hixie** [comment]
@cbenhagen is this still on your radar?

**Comment by cbenhagen** [comment]
@Hixie actually no, and I don't really know how to push this further. I will close this PR and hope for some one else to pick this up later.

**Pull request closed without merging**
