### PR TITLE
[Impeller] add example of testing entity with "real" HAL instead of mocking.

### PR DESCRIPTION
**Pull request by jonahwilliams**
As a response to my comments in https://github.com/flutter/engine/pull/47621

### CODE REVIEW

**Comment by jonahwilliams** [comment]
We could probably abstract some of these things a bit better for cases where we want to introspect into what the HAL is actually doing.

**Review by matanlurey — APPROVED** [review]
This is great! I have no idea how to make this more visible for the next person but looks pretty straightforward to me. Aaron WDUT?

**Comment by jonahwilliams** [comment]
seems like there was some gold noise: these aren't golden tests.

**Comment by gaaclarke** [comment]
> This is great! I have no idea how to make this more visible for the next person but looks pretty straightforward to me. Aaron WDUT?

I think this looks good for this case and the tests I've written so far for the `DirectionalGaussianBlurFilterContents`.  You can't get to the "everything is tested" we agreed upon with this approach today though.  If you look at the implementation of `DirectionalGaussianBlurFilterContents::RenderFilter` the behavior of that method changes depending on the capabilities of the hardware, specifically `SupportsDecalSamplerAddressMode`.  @jonahwilliams do you have an idea how to address this sort of issue?  We'd need something like the hardware profile emulation of swiftshader.  Otherwise, mocks are going to be our only option for "everything is tested".

**Comment by jonahwilliams** [comment]
> to the "everything is tested" we agreed upon with this approach today though

We didn't agree that everything needed to be tested as in 100% branch/line coverage, just that everything needs tests.  

In this case the difference between decal and non-decal is the selected shader which is extremely trivial. But the good news is that all backends that were test on for CI support the decal feature. So if you _wanted_ to cover all the branches, you could do so by changing the capabilities interface to allow selectively disabling already supported features.

**Pull request merged**
