### PR TITLE
[ui] hold a strong reference to fragment program objects.

### PR DESCRIPTION
**Pull request by jonahwilliams**
The native engine needs to hold a strong reference to fragment programs. So the dart side holding a weak ref is more or less pointless

### CODE REVIEW

**Comment by jonahwilliams** [comment]
they did not.

**Comment by dnfield** [comment]
This fixes https://github.com/flutter/flutter/issues/141490 right?

**Comment by dnfield** [comment]
I wonder if this also breaks some programs out there? For example, I think the following used to work but now wouldn't:

1. Load a fragment program.
2. Get the shader, set some uniforms using `setFloat`.
3. Render.
4. Drop all references to the fragment program. Load it again.
5. Uniforms are not zeroed out now because of (2).

**Comment by jonahwilliams** [comment]
But the fragmentShader has the uniforms, not the program

**Comment by dnfield** [comment]
Ok. I thought I saw this but we can fix it separately if it's an issue.

I think a test should be possible for this, e.g. load `FragmentProgram.fromAsset` twice and make sure they objects are identical. Although that doesn't encode whether it's weakly or strongly held, and maybe for that we'd need a GC...

**Comment by jonahwilliams** [comment]
I added a test that checks if two loaded programs are identical, which at least verifies there is a cache. It can't verify the GC behavior obvs.

**Review by dnfield — APPROVED** [review]

**Pull request merged**
