### PR TITLE
[Impeller] fix line/polygon depth and GLES scissor state.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Two problems:

1. We were incorrectly clearing scissor state in the GLES render pass. I suspect this is the cause of all of the clipping problems in wonderous.

2. We were incrementing the depth value in drawPoints with line/polygon mode: these actually need to use the same depth values.

Fixed in the same PR because the golden actually demonstrates both problems with GLES, and luckily I found 2. when I noticed 1.

### Metal/Vulkan

image

### GLES

image

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
lgtm! Can you add a screenshot of what the golden test looks like without the change to the PR?

**Comment by jonahwilliams** [comment]
Yeah will grab in a sec. Essentially the lines will draw outside of the clipped circle.

**Comment by jonahwilliams** [comment]
FYI @jason-simmons

**Comment by jonahwilliams** [comment]
Added before screenshots.

**Comment by chinmaygarde** [comment]
This was bisected as causing a regression in a customer test. I'm getting a reduced test case now.

The regression manifested as the application of an obsolete scissor rect. The only thing in this patch that looks related is the removal of the scissor test.

Whats different about MTL/VK and GLES that'd cause this? Direct encode?

**Pull request merged**
