### PR TITLE
test harness for stocks app on iOS

### PR DESCRIPTION
**Pull request by collinjackson**
Authored by @chinmaygarde but I changed the author because the CLA-bot didn't like it

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Feels bad. Why doesn't the bot like me :(

**Comment by abarth** [comment]
@chinmaygarde I think the bot is red on everyone's pull request.  @Hixie mentioned that @jason-simmons is working on fixing it.

**Comment by Hixie** [comment]
@jason-simmons fixed all but one set of issues, relating to dart:ui_internals being imported by the services/ files. I haven't dug into what the issue is there. You removed dart:ui_internals, no? Are these just unused imports now?

**Comment by abarth** [comment]
I haven't removed dart:ui_internals yet.  I removed dart:ui_builtin_natives.  We'll eventually remove dart:ui_internals, but I haven't quite been able to yet.

**Comment by collinjackson** [comment]
Errors are unrelated to this PR, I'm merging this since the iOS instructions use it

**Pull request merged**
