### PR TITLE
[Impeller] write vertices geometry data to host buffer.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Now that host buffer writes go directly to device buffers, there is no advantage to creating dedicated device buffers for the vertices contents.

Fixes https://github.com/flutter/flutter/issues/141202

### CODE REVIEW

**Comment by jonahwilliams** [comment]
hmm, I should remove the extra allocations with the allocate callback too.

**Comment by jonahwilliams** [comment]
oops, broke stuff

**Comment by bdero** [comment]
I'm super ready to smack that approve button as soon as the goldens look good. 😄

**Comment by jonahwilliams** [comment]
I apparently forgot how this code worked, but it should be fixed.

**Comment by bdero** [comment]
It happens to the best of us.

**Review by bdero — APPROVED** [review]
LGTM!

**Pull request merged**
