### PR TITLE
Move the JNI bridge out of dart:ui and into a separate dart:jni library

### PR DESCRIPTION
**Pull request by jason-simmons**
This also extends DartClassLibrary to support multiple DartClassProviders
for different libraries

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by chinmaygarde** [comment]
lgtm

**Comment by jason-simmons** [comment]
Added the library name to the symbol names

**Comment by chinmaygarde** [comment]
Sorry, I commented on the patch instead of the PR. lgtm :+1:

**Pull request merged**
