### PR TITLE
Fix the VM service path so the precompilation snapshotter can find observatory specific entry points

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @tvolkert

**Comment by tvolkert** [comment]
lgtm

**Comment by eseidelGoogle** [comment]
Would the bots making ipa for all of our examples have caught this?  I'm happy to help you set that up.

**Comment by chinmaygarde** [comment]
Yes, they would have definitely caught this.

**Pull request merged**
