### PR TITLE
[Impeller] Add support for specialization constants (III).

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reland of https://github.com/flutter/engine/pull/47432

Also includes:

https://github.com/flutter/engine/pull/47617
https://github.com/flutter/engine/pull/47637

Fixes the performance on iOS by removing blocking on compilation of shaders. From local testing this has identical before/after numbers. Additional, ensures that we don't unecessarily specialize vertex shaders and notes this restriction in the documentation.

Adds support for Specialization constants to Impeller for our usage in the engine. A motivating example has been added in the impeller markdown docs.

Fixes https://github.com/flutter/flutter/issues/136210
Fixes https://github.com/flutter/flutter/issues/119357

Investigating: https://github.com/flutter/flutter/issues/138028

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM

**Comment by bdero** [comment]
Since this didn't fail during presubs the first time it landed, I wonder if the issue only manifests when combined with another recent patch.

**Comment by jonahwilliams** [comment]
This failed because it bumped us over a number of Vulkan context that can be loaded. This should not reland until we can fix this issue.

**Comment by bdero** [comment]
This can go in once https://github.com/flutter/engine/pull/47781 lands

**Pull request merged**
