### PR TITLE
Roll src/third_party/skia/ 52e16d984..ded7a5586 (1 commit)

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
No complains from Travis CI. Running the license script locally fails with:

$ ../../../third_party/dart/tools/sdks/linux/dart-sdk/bin/dart lib/main.dart --release --src ../../.. --out ../../../out/licenses > ../../sky/packages/sky_engine/LICENSE
Finding files...
Collecting licenses...
.../../third_party/skia/src/xps/SkXPSDocument.cpperror searching for copyright in: ../../../third_party/skia/third_party/freetype2/include/freetype-android/ftmodule.h
file has no detectable license and no in-scope default license file


error searching for copyright in: ../../../third_party/skia/third_party/freetype2/include/freetype-android/ftoption.h
failed to find accompanying "LICENSE.TXT" in ../../../third_party/skia/third_party/freetype2/include/freetype-android
block:
---
/*  Copyright 1996-2018 by                                                 */
/*  David Turner, Robert Wilhelm, and Werner Lemberg.                      */
/*                                                                         */
/*  This file is part of the FreeType project, and may only be used,       */
/*  modified, and distributed under the terms of the FreeType project      */
/*  license, LICENSE.TXT.  By continuing to use, modify, or distribute     */
/*  this file you indicate that you have read the license and              */
/*  understand and accept it fully.
---


     11796 of 11797 ██████████ 100% (2 missing licenses)  ../../../topaz/shell/wifi_settings/lib/main.dart failure: Had failures while collecting licenses.
#0      main (file:///usr/local/google/home/rmistry/autoroll_workdir_rmistry/engine/src/flutter/tools/licenses/lib/main.dart:2415:9)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)


aborted.



@Hixie What should the auto-roller do in this case?
Looking at the diff should it run
$ dart lib/main.dart --release --src ../../.. --out ../../../out/licenses > ../../sky/packages/sky_engine/LICENSE
or does green TravisCI mean that everything is good?

**Comment by Hixie** [comment]
If it gets that error it should abort. A human needs to fix the license script.

Separate from that, it should always run that command to fix the license any time the licenses change. Travis does not check that you did that, only that you updated the golden files.

**Comment by rmistry** [comment]
Thank you, I had misunderstood when the 2nd command needed to run.
I will have the roller always run it when licenses_third_party changes.

**Comment by rmistry** [comment]
After the fixes in https://github.com/flutter/engine/pull/4960 I'm getting an error -

```
---
block was:
---
Copyright (C) 2015 THL A29 Limited, a Tencent company, and Milo Yip.  All rights reserved.

If you have downloaded a copy of the RapidJSON binary from Tencent, please note that the RapidJSON binary is licensed under the MIT License.
If you have downloaded a copy of the RapidJSON source code from Tencent, please note that RapidJSON source code is licensed under the MIT License, except for the third-party components listed below which are subject to different license terms.  Your integration of RapidJSON into your own projects may require compliance with the MIT License, as well as the other licenses applicable to the third-party components included within RapidJSON.

A copy of the MIT License is included in this file.

Other dependencies and licenses:

Open Source Software Licensed Under the BSD License:

The msinttypes r29
Copyright (c) 2006-2013 Alexander Chemeris
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* Neither the name of  copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---


      2159 of 11815 █░░░░░░░░░ 18% (1 missing licenses)  .../BoringCrypto-Security-Policy-20170615.docx!/word/footer1.x      2169 of 11815 █░░░░░░░░░ 18% (1 missing licenses)  .../boringssl/src/crypto/fipsmodule/rand/ctrdrbg_test.cc            4209 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/args/lib/src/arg_parser.      4215 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/args/lib/src/usage.dart       4232 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/async/lib/src/result/fut      4242 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/async/lib/src/async_cach      4248 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../packages/async/lib/src/null_stream_sink.dart                    4253 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/async/lib/src/stream_que      4258 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/async/lib/src/stream_zip      4274 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../packages/barback/lib/src/asset/asset_id.dart                    4312 of 11815 ███░░░░░░░ 36% (1 missing licenses)  .../observatory_pub_packages/packages/barback/lib/src/errors.d      4323 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../observatory_pub_packages/packages/charcode/lib/ascii.dart       4380 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../observatory_pub_packages/packages/charted/lib/charts/chart      4386 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../packages/charted/lib/charts/chart_series.dart                   4400 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../observatory_pub_packages/packages/charted/lib/core/utils/c      4409 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../observatory_pub_packages/packages/charted/lib/core/text_me      4415 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../packages/charted/lib/layout/src/treemap_layout.dart             4427 of 11815 ███░░░░░░░ 37% (1 missing licenses)  .../observatory_pub_packages/packages/charted/lib/svg/shapes/a      4439 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../lib/src/combined_wrappers/combined_list.dart                    4445 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/collection/lib/src/equal      4451 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/collection/lib/src/queue      4462 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/collection/lib/wrappers.      4469 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/csslib/lib/src/messages.      4474 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/csslib/lib/src/tokenizer      4477 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/csslib/lib/src/tree.dart      4493 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/html/lib/src/css_class_s      4498 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/html/lib/src/token.dart       4503 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../observatory_pub_packages/packages/html/lib/dom_parsing.dar      4539 of 11815 ███░░░░░░░ 38% (1 missing licenses)  .../packages/intl/lib/src/data/dates/patterns/es_ES.json            4747 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../observatory_pub_packages/packages/intl/lib/src/intl_helper      4753 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../packages/intl/lib/date_symbol_data_local.dart                   4757 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../observatory_pub_packages/packages/intl/lib/intl_browser.da      4764 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../observatory_pub_packages/packages/logging/lib/logging.dart      4777 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../observatory_pub_packages/packages/matcher/lib/src/util.dar      4785 of 11815 ████░░░░░░ 40% (1 missing licenses)  .../packages/observable/lib/src/observable_list.dart                4794 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/path/lib/src/style/windo      4800 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/path/lib/src/style.dart       4848 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/quiver/lib/src/pattern/g      4857 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/quiver/lib/io.dart            4865 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/source_span/lib/src/loca      4875 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../observatory_pub_packages/packages/stack_trace/lib/src/chai      4881 of 11815 ████░░░░░░ 41% (1 missing licenses)  .../packages/stack_trace/lib/src/unparsed_frame.dart                4924 of 11815 ████░░░░░░ 42% (1 missing licenses)  .../observatory_pub_packages/packages/usage/lib/src/usage_impl      4936 of 11815 ████░░░░░░ 42% (1 missing licenses)  .../observatory_pub_packages/packages/utf/lib/src/utf16.dart        4940 of 11815 ████░░░░░░ 42% (1 missing licenses)  .../observatory_pub_packages/packages/utf/lib/src/utf_stream.d      4950 of 11815 ████░░░░░░ 42% (1 missing licenses)  .../third_party/dart/utils/bazel/kernel_summary_worker.dart         8470 of 11815 ███████░░░ 72% (1 missing licenses)  .../Perf-Android-Clang-NexusPlayer-GPU-PowerVR-x86-Debug-All-A      8473 of 11815 ███████░░░ 72% (1 missing licenses)  .../Perf-Chromecast-GCC-Chorizo-CPU-Cortex_A7-arm-Release-All.      8476 of 11815 ███████░░░ 72% (1 missing licenses)  .../Perf-Ubuntu14-Clang-GCE-CPU-AVX2-x86_64-Release-All-CT_BEN      8479 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-Android-Clang-Nexus5x-GPU-Adreno418-arm64-Debug-All-A      8482 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-Android-Clang-Pixel-GPU-Adreno530-arm64-Debug-All-And      8485 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-All-Coverage.      8488 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-Debian9-GCC-GCE-CPU-AVX2-x86_64-Release-All.json           8491 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-Ubuntu17-GCC-Golo-GPU-QuadroP400-x86_64-Release-All-V      8494 of 11815 ███████░░░ 72% (1 missing licenses)  .../Test-iOS-Clang-iPadPro-GPU-GT7800-arm64-Debug-All.json          8545 of 11815 ███████░░░ 72% (1 missing licenses)  .../Perf-Debian9-Clang-GCE-CPU-AVX2-x86_64-Release-All-ASAN.js      8553 of 11815 ███████░░░ 72% (1 missing licenses)  .../bookmaker.expected/nightly_failed_fiddlecli.json                8619 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Android-Clang-NVIDIA_Shield-GPU-TegraX1-arm64-Debug-A      8623 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Android-Clang-Nexus7-GPU-Tegra3-arm-Release-All-Andro      8626 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Android-Clang-PixelC-GPU-TegraX1-arm64-Release-All-An      8629 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Chromecast-GCC-Chorizo-GPU-Cortex_A7-arm-Release-All.      8632 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Mac-Clang-MacMini7.1-CPU-AVX-x86_64-Release-All.json       8635 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Ubuntu16-Clang-NUC5PPYH-GPU-IntelHD405-x86_64-Debug-A      8638 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Ubuntu17-GCC-Golo-GPU-QuadroP400-x86_64-Release-All-V      8641 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Win10-Clang-AlphaR2-GPU-RadeonR9M470X-x86_64-Release-      8644 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Win10-Clang-ShuttleC-GPU-GTX960-x86_64-Release-All-AN      8647 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-iOS-Clang-iPadPro-GPU-GT7800-arm64-Release-All.json        8654 of 11815 ███████░░░ 73% (1 missing licenses)  .../recreate_skps.expected/Housekeeper-Weekly-RecreateSKPs.jso      8657 of 11815 ███████░░░ 73% (1 missing licenses)  .../Perf-Android-Clang-PixelC-GPU-TegraX1-arm64-Release-All-An      8661 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Android-Clang-AndroidOne-GPU-Mali400MP2-arm-Release-A      8664 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Android-Clang-NVIDIA_Shield-GPU-TegraX1-arm64-Debug-A      8668 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Android-Clang-Nexus5x-GPU-Adreno418-arm64-Debug-All-A      8671 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Android-Clang-Nexus7-GPU-Tegra3-arm-Debug-All-Android      8674 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Android-Clang-Pixel-GPU-Adreno530-arm64-Debug-All-And      8677 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-ChromeOS-Clang-AcerChromebookR13Convertible-GPU-Power      8680 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-All-ASAN.json      8683 of 11815 ███████░░░ 73% (1 missing licenses)  .../Test-Debian9-Clang-GCE-CPU-AVX2-x86_64-Debug-shard_00_10-C      8686 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Debian9-GCC-GCE-CPU-AVX2-x86-Debug-All.json                8689 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Mac-Clang-MacBook10.1-GPU-IntelHD615-x86_64-Release-A      8693 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Ubuntu16-Clang-NUC5PPYH-GPU-IntelHD405-x86_64-Debug-A      8697 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Ubuntu17-Clang-Golo-GPU-QuadroP400-x86_64-Debug-All-D      8700 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Ubuntu17-GCC-Golo-GPU-QuadroP400-x86_64-Release-All-V      8703 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Win10-Clang-AlphaR2-GPU-RadeonR9M470X-x86_64-Debug-Al      8707 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Win10-Clang-NUC5i7RYH-CPU-AVX2-x86_64-Debug-All-Nativ      8711 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Win10-Clang-ShuttleA-GPU-GTX660-x86_64-Debug-All-Vulk      8714 of 11815 ███████░░░ 74% (1 missing licenses)  .../Test-Win10-Clang-ZBOX-GPU-GTX1070-x86_64-Debug-All.json        10936 of 11815 █████████░ 93% (1 missing licenses)  .../concert_event_list/lib/modular/event_list_module_model.dar     10942 of 11815 █████████░ 93% (1 missing licenses)  .../last_fm_artist_bio/lib/modular/artist_bio_module_screen.da     10949 of 11815 █████████░ 93% (1 missing licenses)  .../music_playback/lib/modular/playback_module_model.dart          11694 of 11815 █████████░ 99% (1 missing licenses)  .../armadillo_user_shell/lib/context_provider_context_model.da     11702 of 11815 █████████░ 99% (1 missing licenses)  .../armadillo_user_shell/lib/power_manager_power_model.dart        11789 of 11815 ██████████ 100% (1 missing licenses)  .../userpicker_device_shell/lib/soft_keyboard_container_impl.     11793 of 11815 ██████████ 100% (1 missing licenses)  .../userpicker_device_shell/lib/user_picker_screen.dart           11801 of 11815 ██████████ 100% (1 missing licenses)  .../../topaz/shell/widgets/lib/time_stringer.dart      failure: Had failures while collecting licenses.
#0      main (file:///usr/local/google/home/rmistry/autoroll_workdir_rmistry/engine/src/flutter/tools/licenses/lib/main.dart:2416:9)
<asynchronous suspension>
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```


Which makes sense because the change in this roll adds a new license. Where do I manually add the license?

**Pull request closed without merging**
