### PR TITLE
Fix potential crash of "divide by zero" for invalid GIF image source.

### PR DESCRIPTION
**Pull request by wqyfavor**
This pr is to fix https://github.com/flutter/flutter/issues/84701

### CODE REVIEW

**Comment by chinmaygarde** [comment]
This looks good to me but can we have a test for this? Perhaps an instance of an invalid GIF. See `TEST_F(ImageDecoderFixtureTest, ValidImageResultsInSuccess)` for an instance of how to use the test harness.

**Comment by wqyfavor** [comment]
@chinmaygarde 

I tried to write a test like this.
TEST_F(ImageDecoderFixtureTest, BrokenGIFWithZeroFramesWillShortCutOnMultiframCodecGetNextFrame) {
}

But I do not know how to assert that the code goes to the shortcut path of `if (state_->frameCount_ == 0) {` block.

The normal process of ValidImageResultsInSuccess or ValidImageResultsInFailure tests cannot test for my patch for invalid GIF. They do not even instantiate a MultiFrameCodec.

Do you have other suggestions?

**Comment by wqyfavor** [comment]
By the way. The div0 crash only happens on some Android devices in 32bit mode.

**Comment by wqyfavor** [comment]
@chinmaygarde Hi, I have some problems writing test for this patch. Currently Flutter engine is missing tests for MultiFrameCodec.

**Review by chinmaygarde — APPROVED** [review]
This seems fine from a defensive coding perspective.

**Comment by chinmaygarde** [comment]
The presubmits are failing on a formatting issue. Can you update the patch to address the failures please?

**Comment by wqyfavor** [comment]
> The presubmits are failing on a formatting issue. Can you update the patch to address the failures please?

Hi, @chinmaygarde . I can only see these two checks to be failed. Does it matter?
Screen Shot 2021-07-02 at 10 49 26

Can you point out where to find the exact formatting issue? Thanks. I am not familiar to flutter CI checks.

**Comment by jason-simmons** [comment]
If you click on the "Linux Unopt" details link, you can navigate to the results of the "format and dart test" check:
    https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8843819170249166448/+/u/format_and_dart_test/stdout

Please apply the formatting changes suggested by the check and upload a new version of the patch.

**Comment by wqyfavor** [comment]
@chinmaygarde @jason-simmons 

I have updated my commit with code format correction. But some other CI checks failed and should not be related to my patch.

**Comment by jason-simmons** [comment]
To fix the other CI checks, try rebasing the patch on the latest flutter/engine master

**Comment by wqyfavor** [comment]
@jason-simmons @chinmaygarde I think everything is fine.

**Comment by wqyfavor** [comment]
@chinmaygarde @jason-simmons Hi, shall we have this PR merged? I have rebased several times. Hope to be handled soon.

**Comment by jason-simmons** [comment]
Sorry about this, but it looks like this will need another rebase.

The last run of the CI checks failed due to https://github.com/flutter/flutter/issues/86326, which should now be fixed.

**Pull request merged**
