### PR TITLE
Generate a depfile for assets of a flutter_app.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
Related: https://github.com/flutter/flutter/pull/8961

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
This seems to have broken the build, can we please revert?

**Comment by pylaligand** [comment]
Do you have a link with the breakage? Is that the Windows build mentioned in the other PR?

**Comment by Hixie** [comment]
Sorry I misread the waterfall status. Turns out the build was broken before you checked in.

Please don't check in when the build is red. :-) Though in this case the breakage was on the engine side only which means it didn't show up on the dashboard. :-( The waterfall for the engine repo (also shows some stuff from the flutter repo) is at:
https://build.chromium.org/p/client.flutter/waterfall

**Comment by pylaligand** [comment]
Sorry, I'll check the waterfall first next time.

**Pull request merged**
