### PR TITLE
[Impeller] Share LazyGlyphAtlas across EntityPass

### PR DESCRIPTION
**Pull request by luckysmg**
*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/116815

Now, every `EntityPass` will create a single `LazyGlyphAtlas` to use in `Canvas::DrawTextFrame`, but it seems that there is no need for creating a `LazyGlyphAtlas` for per `EntityPass`, and I think maybe we can create a single `LazyGlyphAtlas` to reuse it across `EntityPass`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
I'm not sure that I understand the change that this PR is trying to make.

LazyGlyphAtlas is attached to the entity pass allowing it to be used across multiple text content canvas operations. Moving it to the canvas makes it harder to reuse.

**Comment by luckysmg** [comment]
Hi @jonahwilliams 
Now, per `EntityPass` will create a `LazyGlyphAtlas`. (If there are two `EntityPass`, will create two `LazyGlyphAtlas`)
But if we move it to canvas, multiple `EntityPass` can reuse this single `LazyGlyphAtlas`. LMK if I missed something O(∩_∩)O

**Comment by jonahwilliams** [comment]
Oh I see, sorry I misunderstood. yes that will accomplish reuse. 

We're going to end up with a few more objects that can be shared across entity pass, the tesselator to start with, and at some point some sort of geometry cache too. Is canvas.cc a reasonable place to put these for now, or should we create a separate class to hold them @chinmaygarde ?

**Comment by zanderso** [comment]
From PR review triage: @jonahwilliams Do you have any thoughts about this PR?

**Comment by jonahwilliams** [comment]
Old comment stands:

> We're going to end up with a few more objects that can be shared across entity pass, the tesselator to start with, and at some point some sort of geometry cache too. Is canvas.cc a reasonable place to put these for now, or should we create a separate class to hold them @chinmaygarde ?

**Comment by chinmaygarde** [comment]
I think it was setup this way because we expected to use an atlas per pass with the passes being setup concurrently from multiple threads. This will get in the way of that effort but we can rework that when the time comes.

**Review by chinmaygarde — APPROVED** [review]

**Comment by jonahwilliams** [comment]
That seems like a reason to hold off on this. I think what I'd like to know is if we have multiple passes (due to a platform view), does each pass collect glyphs for only their own pass - or all passes?

If its the former, we might not want to make this change.

**Comment by luckysmg** [comment]
> I think what I'd like to know is if we have multiple passes (due to a platform view), does each pass collect glyphs for only their own pass - or all passes?

Sorry for my poor knowledge about that. Emm but why do platform views need to collect glyphs for only in their pass ?

**Comment by jonahwilliams** [comment]
not the platform view, but when there is a platform view in the tree the scene is divided in two. I'm unsure if each part collects glyphs individually or not

**Comment by luckysmg** [comment]
Got you. I m also not very sure on that........ @chinmaygarde maybe more know about this? Would you mind sharing your thought on that. O(∩_∩)O

**Comment by jonahwilliams** [comment]
I can do some research into that later this week. Either way, I'd be a bit concerned that the different passes would step on each other if they shared a glyph atlas. The only way to make that work would be to collect the glyphs for all passes up front.

**Comment by chinmaygarde** [comment]
Thinking a bit more about this, I don't think this is the model we want to go with for multiple passes. For one, this will make encoding multiple passes concurrently harder. But I am also not sure how this works when we submit one pass but keep adding to the texture atlas referenced by it for subsequent passes.

Closing this but will keep it referenced in the icebox for when we think about improving atlas management.

**Comment by jonahwilliams** [comment]
I think we should revisit this. its true it may not be the ideal behavior when platform views are involved, but actually today we're doing much worse than we should when there are multiple entity passes because we end up re-creating the glyph atlas N times per frame. this is part of the issue in https://github.com/flutter/flutter/issues/121476

So LGTM to me, if @chinmaygarde is OK with it

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
@luckysmg if you're able to update the tests I think we can land this.

**Comment by chinmaygarde** [comment]
sgtm

**Pull request merged**
