### PR TITLE
Rename //flutter/shell/gpu to //flutter/shell/surface.

### PR DESCRIPTION
**Pull request by chinmaygarde**
This component only contains surface subclasses of the abstract surface in flow. It used to be more related to other GPU related configuration but that is now no longer the case.

No change in functionality. Just renames internal TUs.

Attempts to reland https://github.com/flutter/engine/pull/54195

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Can this wait for https://github.com/flutter/engine/pull/54200 ?

**Comment by chinmaygarde** [comment]
Oops. Didn't see that one. Will review that too.

**Comment by jonahwilliams** [comment]
I would suggest waiting until at least https://github.com/flutter/engine/pull/53826 has landed.

**Comment by chinmaygarde** [comment]
Will just do it next week. This stuff is not important.

**Pull request closed without merging**
