### PR TITLE
Fix bounds when painting style is stroke width for image shaders

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/126739

When we're sampling from the texture, we need to sample from its origin regardless of how much offset the stroke width gives to the path.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Need to figure out what's changing in the goldens...

**Review by bdero — APPROVED** [review]
LGTM.

I'd recommend adding a golden that draws a stroke with `TiledTextureContents` as the color source. There are a bunch of combinations not covered by goldens yet.

**Comment by dnfield** [comment]
> LGTM.
> 
> I'd recommend adding a golden that draws a stroke with `TiledTextureContents` as the color source. There are a bunch of combinations not covered by goldens yet.

I updated the goldens to draw both a stroke and a fill over the same area and make sure they match. I'm confused though about why some of them are changing. I'm going to be out today but will try to look tomorrow.

**Comment by dnfield** [comment]
Ok, verified locally the golden updates are because I'm not placing the stroke exactly on top of the fill in some cases. Rather than try to figure that out I'm going to approve them. This would still catch regressions.

**Pull request merged**
