### PR TITLE
Fix profile and release mode isolate spawning

### PR DESCRIPTION
**Pull request by johnmccutchan**
Fixes https://github.com/flutter/flutter/issues/6496

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@abarth @jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Comment by abarth** [comment]
We probably need a driver for this issue so we don't regress it again.

**Comment by johnmccutchan** [comment]
@abarth What do you mean by driver?

**Comment by abarth** [comment]
A test that's run by https://github.com/flutter/flutter/blob/master/dev/devicelab/README.md

I'm not completely sure how to create one, but @yjbanov can help us.

**Comment by johnmccutchan** [comment]
@yjbanov we will need the driver to run in all three build modes (debug, profile, and release)

**Comment by yjbanov** [comment]
Flutter Driver cannot run in release mode because there's no observatory to talk to. We do run various tests in debug and profile mode. You should be able to run tests against a custom build of the engine. I believe there's an environment variable you can set (although I can't find it; I hope we haven't deleted it). For example, `complex_layout_scroll_perf__timeline_summary` runs in profile mode and `hot_mode_dev_cycle__benchmark` runs in debug mode, so from [dev/devicelab](https://github.com/flutter/flutter/tree/master/dev/devicelab) you could run:

```
dart bin/run.dart -t complex_layout_scroll_perf__timeline_summary -t hot_mode_dev_cycle__benchmark
```

**Pull request merged**
