### PR TITLE
Bump Robolectric to 4.7.3

### PR DESCRIPTION
**Pull request by utzcoz**
Bump Robolectric to latest 4.7.3 to support SDK 31.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by utzcoz** [comment]
Looks like there are some failed tests, and I will check it locally.

**Comment by utzcoz** [comment]
Looks like new Robolectic version will change the priority of `getSystemService` result between spy one and real one.

**Comment by utzcoz** [comment]
If I add `@Config(sdk = 30)` to related tests, all tests passed. I have tested `Mockito#spy` for `Context#getSystemService` at Robolectric, it worked. Looks like there are some things changed at SDK 31.

**Comment by utzcoz** [comment]
Looks like commit [Migrate Presentation to WindowContext](https://android.googlesource.com/platform/frameworks/base/+/f3aefb28029f5eb05835a61e86bf660cc72da432%5E%21/core/java/android/app/Presentation.java) added at Android 12 breaks flutter's hook to cache IMM instance, created by https://github.com/flutter/engine/pull/12085. The commit [Migrate Presentation to WindowContext](https://android.googlesource.com/platform/frameworks/base/+/f3aefb28029f5eb05835a61e86bf660cc72da432%5E%21/core/java/android/app/Presentation.java) uses window `Context` created from display `Context` with [`createWindowContext` method](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/ContextImpl.java;l=2647-2705?q=createWindowContext&ss=android%2Fplatform%2Fsuperproject). The cached IMM isn't been passed to new `WindowContext` by `ImmContext` on Android 12. Hi @mklim, could you help to confirm whether this commit causes this problem(`SingleViewPresentationTest` failed on SDK 31)?

**Comment by utzcoz** [comment]
Hi @zanderso , could you help to look at this PR? Thanks.

**Review by blasten — APPROVED** [review]
LGTM

**Review by zanderso — APPROVED** [review]

**Comment by utzcoz** [comment]
> Looks like commit [Migrate Presentation to WindowContext](https://android.googlesource.com/platform/frameworks/base/+/f3aefb28029f5eb05835a61e86bf660cc72da432%5E%21/core/java/android/app/Presentation.java) added at Android 12 breaks flutter's hook to cache IMM instance, created by #12085. The commit [Migrate Presentation to WindowContext](https://android.googlesource.com/platform/frameworks/base/+/f3aefb28029f5eb05835a61e86bf660cc72da432%5E%21/core/java/android/app/Presentation.java) uses window `Context` created from display `Context` with [`createWindowContext` method](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/ContextImpl.java;l=2647-2705?q=createWindowContext&ss=android%2Fplatform%2Fsuperproject). The cached IMM isn't been passed to new `WindowContext` by `ImmContext` on Android 12. Hi @mklim, could you help to confirm whether this commit causes this problem(`SingleViewPresentationTest` failed on SDK 31)?

Hi @chinmaygarde , could you help to find proper folk to check whether this problem still exist? Looks like IMM window context doesn't work on Android 12 still now(inspecting from testing result).

**Comment by zanderso** [comment]
@chinmaygarde isn't the right person to look into that. Maybe @stuartmorgan or @GaryQian know whether this can be answered?

**Pull request merged**
