### PR TITLE
Fix ImageReader may leak images when onDraw() not called.

### PR DESCRIPTION
**Pull request by eggfly**
The onDraw() may not called after invalidate(), this maybe reproduced on some Android devices.
And also ImageReader related logics can be simplified.

image

The `imageQueue` in old implementation may leaves two or more items after `acquireLatestImage()` and occure the native level log: 
"unable to acquire a buffer item, very likely client tried to acquire more than maximages buffers" in https://android.googlesource.com/platform/frameworks/base/+/master/media/jni/android_media_ImageReader.cpp#517
Because there's no guarantee that `onDraw()` must be called after `invalidate()` when device sleeping or on some special devices.

It fixes:
https://github.com/flutter/flutter/issues/63897
https://github.com/flutter/flutter/issues/70290

### CODE REVIEW

**Comment by hssdx** [comment]
牛批，解决了我的难题

**Comment by blasten** [comment]
Thanks for the contribution. A few questions:
1. what devices did you use to test?
2. this change would need some tests
3. the code needs to be formatted

**Comment by chinmaygarde** [comment]
@eggfly Can you clarify @blasten s queries please so we can make progress on this patch?

**Comment by eggfly** [comment]
@chinmaygarde I will soon make a progress.
@blasten I will do the thress things. Thank you for your advises! And also, which code segment lines should be formated and what's the recommend styles and rules to format the java code of flutter?

**Comment by eggfly** [comment]
I made a new pull request here with some new progress on this patch: https://github.com/flutter/engine/pull/24272
So close this old pull request.

**Comment by eggfly** [comment]
I made a new pull request here with some new progress on this patch: #24272
So close this old pull request.

**Pull request closed without merging**
