### PR TITLE
Add libglfw3-dev to linux build deps script

### PR DESCRIPTION
**Pull request by cbracken**
This ensures that the OpenGL headers and GLFW are installed.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
What's the context for this change? We build GLFW from source in `third_party`, so there shouldn't be any dependency on system GLFW headers.

**Comment by cloudwebrtc** [comment]
libglfw3-dev does not seem to have built-in glad.h, https://github.com/flutter/engine/pull/9822 needs to use glad.

**Comment by stuartmorgan** [comment]
> libglfw3-dev does not seem to have built-in glad.h

Glad isn't conceptually part of GLFW, so there's no reason it should. The `deps` folder in GLFW where it lives contains external code, like Flutter's `third_party`.

I'm not sure how that relates to this PR though.

**Comment by cloudwebrtc** [comment]
If this PR is to replace the third_party/glfw dependency with libglfw3-dev, we need to import another glad.h/.c to support the texture, maybe third_party/glad or add to shell/platform/glfw?
Before that I submitted a PR to https://github.com/flutter/buildroot/pull/275

**Comment by cbracken** [comment]
Nope - the issue was that my laptop blew up and I picked up a loaner. It couldn't find some GL (not GLFW) headers until I installed glfw and I expect they showed up in libmesa1-dev or similar. Thinking about it though, I'd have thought we should be pulling that from the buildtools sysroot and not the system, so I wonder if we're not as hermetic as we should be somewhere. Will re-remove the installed packages and see if I can track it down.

**Pull request closed without merging**
