### PR TITLE
Move //buildtools to //flutter/buildtools

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by zanderso** [comment]
Thanks for digging in to this. I suspect it will be tricky to find all the places that need to be updated, but it is something that we need to get done. Please give a shout if you'd like any help tracking down any of the failures.

**Comment by jason-simmons** [comment]
This is passing on CI now.

Are there any other checks that should be run before landing this?

In particular, I'd like to verify that RBE is working as intended.

Some of the CI engine builds took a long time to run (for example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/781285/overview, where a Mac host_debug_unopt build took 40 minutes).  So I'm wondering if the change in build tool paths is affecting RBE.

**Comment by zanderso** [comment]
The rbe configs pulled in the cipd package here https://github.com/flutter/engine/blob/main/DEPS#L982 have paths in them that need to be updated. You can get `gclient sync` to pull that cipd package by setting `use_rbe: True` in your `.gclient` file.

**Comment by jason-simmons** [comment]
Updated the CIPD package and RBE looks like it's working now.

**Review by zanderso — APPROVED** [review]
LGTM

**Pull request merged**
