### PR TITLE
Migrate remaining unittest to cfv2.

### PR DESCRIPTION
**Pull request by chandarrengoog**
Migrate flutter_runner_tests to cfv2.

See https://fxbug.dev/79691.

CC: @chaselatta, @naudzghebre

### CODE REVIEW

**Comment by arbreng** [comment]
Do the tests pass?

engine_unittests is still connecting to the real Scenic:  https://source.corp.google.com/github/flutter/engine/shell/platform/fuchsia/flutter/tests/engine_unittests.cc;l=66

**Comment by chandarrengoog** [comment]
> Do the tests pass?

Yuck, looks like we have false positives which pass all tests whenever FEMU fails to launch 😕

https://flutter-review.googlesource.com/c/recipes/+/15840 should fix this.

**Comment by chinmaygarde** [comment]
The recipe fix has landed. Can we continue progress on this? BTW, the presubmit failure was due an issue on ToT that has since been fixed. Please rebase this PR. Thanks.

**Comment by chinmaygarde** [comment]
Per Kaushik, Darren may be working on higher priority tasks this week. No progress is likely for some time.

**Comment by Hixie** [comment]
Is this PR still being worked on or should we close it?

**Pull request closed without merging**
