### PR TITLE
raster cache Pictures embedded inside other DisplayLists

### PR DESCRIPTION
**Pull request by flar**
Fixes: https://github.com/flutter/flutter/issues/87584

Prepares sub-pictures of DisplayLists during Preroll and then draws them from the cache during Paint.

Needs tests.

Also needs a little more review of the potential to doubly cache the parent and child pictures.

### CODE REVIEW

**Comment by dnfield** [comment]
I figured out what I was reading wrong.

I do think we should move the perspective logic into a separate PR - it'd be fine to land that one before this one if it makes a difference - but it should make it easier to bisect/revert if that causes an unrelated problem.

**Comment by flar** [comment]
> I figured out what I was reading wrong.
> 
> I do think we should move the perspective logic into a separate PR - it'd be fine to land that one before this one if it makes a difference - but it should make it easier to bisect/revert if that causes an unrelated problem.

This is currently a WIP so there is no real rush, but I would want to find a test case that demonstrates the problem with caching under a perspective transform before I move on that.

Also, there is an outstanding issue to fix our transform layers wrt perspective transforms that could change this whole perspective. One of the problems with caching under a perspective transform is that we are currently using broken one-shot versions of perspective transforms that are only valid for leaf operations. If we had a true perspective transform at that point in the logic we might be able to cache. Unfortunately, I don't think our caching math is up to that challenge without a lot more work.

**Comment by flar** [comment]
> How would this interact with [flutter/flutter#91621](https://github.com/flutter/flutter/issues/91621) if we did it?

For parent pictures that are degenerate, such as "record [drawPicture(stable_picture)] end_recording" where the picture doesn't look complex enough to cache, this wouldn't be needed with the fix for nested op counts, but it shouldn't hurt anything as long as we make sure that we don't double cache the parent and the child (that work is TBD while this PR is WIP).

For parent pictures that change on every frame, whether or not they are also degenerate, this would allow a complex-but-stable child to be cached anyway. This is the case that commonly happens with the SVG pictures where they can be included in multi-widget pictures that are changing due to content outside of the SVG picture changing, but the SVG picture is stable and rendered with `drawPicture()`. That specific case is already obsoleted by https://github.com/dnfield/flutter_svg/pull/592, though, so the value depends on how many other such cases we find in other app code.

For parent pictures that are stable and complex, those will be cached themselves and so these child pictures don't need to be cached (modulo this PR needs to address that case and prevent redundant caching).

**Comment by flar** [comment]
This has been on the back burner for a while and is massively obsolete. It might be better to start over after a number of PRs land to improve the raster caching.

**Pull request closed without merging**
