### PR TITLE
Revert "[web] remove obsolete object caches; simplify native object management"

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/engine#40894

This is breaking Google Testing. See b/277004090

### CODE REVIEW

**Review by XilaiZhang — APPROVED** [review]

**Comment by yjbanov** [comment]
All failures are in Firefox 72, which we do not support.

**Review by yjbanov — APPROVED** [review]

**Comment by XilaiZhang** [comment]
just to verify, Yegor is okay with a revert right?

**Comment by yjbanov** [comment]
The golden seems to be another Impeller flake. Let's land this.

**Comment by XilaiZhang** [comment]
Look at Yegor -- so efficient!

**Pull request merged**
