### PR TITLE
Run windows_arm build only on main branch.

### PR DESCRIPTION
**Pull request by godofredoc**
Dart SDK does not exist in beta or stable branches. This PR will limit the execution of this build to main branch only.

Bug: https://github.com/flutter/flutter/issues/123288

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by loic-sharma** [comment]
@godofredoc Could you expand on why this is necessary? Is Dart's support for Windows ARM disabled on stable and beta? Does that mean that Flutter stable and beta won't be able to support Windows ARM? /cc @pbo-linaro

**Comment by godofredoc** [comment]
> @godofredoc Could you expand on why this is necessary? Is Dart's support for Windows ARM disabled on stable and beta? Does that mean that Flutter stable and beta won't be able to support Windows ARM? /cc @pbo-linaro

That is correct, this is the initial bug: https://github.com/flutter/flutter/issues/113931

The TLDR; is that Dart SDK support for windows arm is considered experimental and not currently shipped to beta or stable channels.

**Comment by pbo-linaro** [comment]
And do you think it could be possible to collaborate with Dart team to enable this support, with Flutter dev team support?

**Comment by godofredoc** [comment]
cc'ing @timsneath who can provide more info about the dart sdk windows arm strategy.

**Comment by timsneath** [comment]
We are super-excited for the (Flutter, Windows, ARM) tuple to be checked! (I'm particularly excited -- I have more ARM than Intel machines running Windows...)

As I understand it, the lay of the land is that we're still standing up our test CI infrastructure to fully support ARM: we have an array of Volterra devices that will be up and running in the next couple of months. When we have that enabled, we'll have the infrastructure to be able to consistently run test suites on Windows/ARM, which is a prerequisite to us being able to declare `beta` or `stable`. And yes -- it's of course our goal that Flutter supports Windows/ARM, thanks in large part to your contributions. 

While we get the test labs spun up, we'd be _delighted_ to see you continue to work on proving this out on the `master` channel, so that we're ready as soon as possible. Excited to make some noise about this!

**Comment by pbo-linaro** [comment]
Good to hear you're on track to support Windows on Arm with dedicated machines :+1:. For now, at Flutter level, we can enable it for master channel only, and later, to beta and stable.

**Pull request merged**
