### PR TITLE
Handle case where platform view getView() returns null

### PR DESCRIPTION
**Pull request by blasten**
Fixes http://b/225327795

`PlatformView#getView()` is nullable

### CODE REVIEW

**Review by hamdikahloun — APPROVED** [review]
LGTM
@blasten Can you update the issue link please

**Comment by blasten** [comment]
Thanks for the review. 

The issue is described in the PR description:
`PlatformView#getView()` is nullable, so any code that depends on it must check for null.

**Comment by hamdikahloun** [comment]
Link not working 
> Fixes http://b/225327795

**Comment by blasten** [comment]
This is an internal link, but the issue is what is described in the PR description

**Pull request merged**
