### PR TITLE
Revert "Remove deprecated MOCK_METHODx calls"

### PR DESCRIPTION
**Pull request by dkwingsmt**
Reverts flutter/engine#45307 due to internal breakage. b/298953971

### CODE REVIEW

**Comment by chinmaygarde** [comment]
I couldn't tell what the error was.

**Comment by dkwingsmt** [comment]
I couldn't either. I ran one of the tests and it passed. Let me run them all.

**Comment by chinmaygarde** [comment]
Is this still necessary?

**Comment by dkwingsmt** [comment]
I've close the internal issue with the following note:

I've created a CL for this PR and ran it in a Global TAP train.

There're a few failures, but none of them are the same as the failures in this report (also some of them are SCUBA rasterization errors). I think it's safe to consider all of them flakes.

**Comment by chinmaygarde** [comment]
Thank you!

**Pull request closed without merging**
