### PR TITLE
macOS: Extract framework creation to sky_utils

### PR DESCRIPTION
**Pull request by cbracken**
This refactors `create_mac_framework.py` to extract framework creation to `sky_utils.py`. The only other changes are minor variable renaming and extraction of functions to make the code more readable/easier to work with.

The resulting zip archives have been verified to be identical before and after.

This is refactoring to support embedding dSYM debug information in a follow-up patch.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
Can we run the framework presubs on this too =)

**Comment by cbracken** [comment]
Yep, waiting for it to build first.

**Comment by cbracken** [comment]
Test framework roll is: https://github.com/flutter/flutter/pull/153598

**Comment by cbracken** [comment]
One can see from the logs that the symlinks are correct here:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739412731644140417/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_4/stdout

**Comment by zanderso** [comment]
> Test framework roll is: [flutter/flutter#153598](https://github.com/flutter/flutter/pull/153598)

The framework web presubs are failing because the `runIf` clause in the engine `.ci.yaml` excluded the web build running as a presubmit check on this PR.

**Comment by cbracken** [comment]
Updated the docs to mention this in https://github.com/flutter/engine/pull/54593

**Comment by cbracken** [comment]
All macOS tests are passing on the framework patch. https://github.com/flutter/flutter/pull/153598

**Comment by cbracken** [comment]
I've removed the `.ci.yaml` commit (e519ba6adade49c4c0b6a591ee160c797a7838fa) so we don't inadvertently land it.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
