### PR TITLE
[vm_service] Add vm service port to inspect.

### PR DESCRIPTION
**Pull request by naudzghebre**
fxb/75455

### CODE REVIEW

**Review by chaselatta — APPROVED** [review]
LGTM. Probably need a rebase first to fix the builders.

**Review by chandarrengoog — APPROVED** [review]
LGTM.

**Comment by chinmaygarde** [comment]
This PR needs to be rebased for the presubmits to pass. But otherwise looks good to land.

**Comment by naudzghebre** [comment]
Add the vm service port number to inspect tree.

**Pull request merged**
