### PR TITLE
Respect EXIF information while decompressing images.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Adds a unit-test asserting this behavior.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Re-fixes https://github.com/flutter/flutter/issues/10895

**Comment by chinmaygarde** [comment]
LUCI failure is a red-herring. The last entry is actually a hot-fix patch. Landing.

**Comment by matte5031** [comment]
@chinmaygarde chinmaygarde I have this issue on iOS where most images are rotated 90 degrees, happens in ios simulator aswell as physical device. 
Using flutter beta channel and latest image_picker plugin. Should this be fixed now or why am i seeing this issue? Thanks

**Comment by chinmaygarde** [comment]
If you are on the [latest beta](https://github.com/flutter/flutter/tree/e4ebcdf6f4facee5779c38a04d91d08dc58ea7a4), this commit should be have rolled in there. Can you pull the latest beta and try again? Or, ensure that `bin/internal/engine.version` contains a SHA that is past the commit in the PR. Or, switch to the dev channel and try again. If you still see an issue, please file a bug with a reduced test case. It may be (but is unlikely to be) an unrelated issue.

**Comment by matte5031** [comment]
@chinmaygarde Thanks for reaching out. I tried flutter upgrade and this was the output:

Already up to date.

Upgrading engine...

Flutter 1.8.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e4ebcdf6f4 (13 days ago) • 2019-07-27 11:48:24 -0700
Engine • revision 38ac5f30a7
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

I checked the exif information on the images that are rotated, and they actually say they should be 90 degrees rotated (the ones i checked have been taken in portrait mode). The ones that look fine from my iphone 6 are the screenshots, they miss exif information but are not rotated. 

A bit confused why the exif should say 90 degrees rotated because they should not be rotated. The same happens in the simulator. I tried to take the same image and upload it to facebook and then check the exif information, it turns out that the rotation part has been wiped and that it looks good there.

Sorry for a lot of text just trying to give as much information as possible. From theese testings is seems like I should try to remove the exif data from the image in flutter is possible because it seem to add rotation to it.

**Comment by chinmaygarde** [comment]
If EXIF data says the image should be rotated, then it seems like the engine is working as intended. It is possible that the upload process on Facebook clobbers EXIF information. Even GitHub seems to [ignore EXIF information](https://github.com/flutter/engine/pull/9905/files?short_path=6006375#diff-6006375af22310ac727ca8603a71efdf) while displaying the image.

Beyond fixing the incorrect exif information, I am not sure what to suggest. You could maybe file a feature request that says something like "Add an optional flag on image decoders to ignore EXIF information". You could then apply any transformation you wanted manually. Or not, if you want want bug-for-bug compatibility with certain image handlers.

**Comment by matte5031** [comment]
@chinmaygarde Okay thanks for the info. Out of curiousity, there are some default images in the ios, simulator, have you tried using the image picker to retrieve them and show them? some of them are rotated for me, curious if that is as expected or if all the images are shown correctly for other people.

**Comment by matte5031** [comment]
@chinmaygarde Actually find that many other people still having this issue. Refering to https://github.com/flutter/flutter/issues/35334

**Comment by matte5031** [comment]
@chinmaygarde I would just like to let you know that I found code that someone had created that could be used to handle this. It's not optimal but, this is no longer an issue for me. The code that I use looks like this:

`  Future<File> rotateAndCompressAndSaveImage(File image) async {
    int rotate = 0;
    List<int> imageBytes = await image.readAsBytes();
    Map<String, IfdTag> exifData = await readExifFromBytes(imageBytes);

    if (exifData != null &&
        exifData.isNotEmpty &&
        exifData.containsKey("Image Orientation")) {
      IfdTag orientation = exifData["Image Orientation"];
      int orientationValue = orientation.values[0];

      if (orientationValue == 3) {
        rotate = 180;
      }

      if (orientationValue == 6) {
        rotate = -90;
      }

      if (orientationValue == 8) {
        rotate = 90;
      }
    }

    List<int> result = await FlutterImageCompress.compressWithList(imageBytes,
        quality: 100, rotate: rotate);

    await image.writeAsBytes(result);

    return image;
  }`

**Comment by worawutt** [comment]
> @chinmaygarde I would just like to let you know that I found code that someone had created that could be used to handle this. It's not optimal but, this is no longer an issue for me. The code that I use looks like this:
> 
> ```
> `Future<File> rotateAndCompressAndSaveImage(File image) async {
> int rotate = 0;
> List<int> imageBytes = await image.readAsBytes();
> Map<String, IfdTag> exifData = await readExifFromBytes(imageBytes);
> 
> if (exifData != null &&
>     exifData.isNotEmpty &&
>     exifData.containsKey("Image Orientation")) {
>   IfdTag orientation = exifData["Image Orientation"];
>   int orientationValue = orientation.values[0];
> 
>   if (orientationValue == 3) {
>     rotate = 180;
>   }
> 
>   if (orientationValue == 6) {
>     rotate = -90;
>   }
> 
>   if (orientationValue == 8) {
>     rotate = 90;
>   }
> }
> 
> List<int> result = await FlutterImageCompress.compressWithList(imageBytes,
>     quality: 100, rotate: rotate);
> 
> await image.writeAsBytes(result);
> 
> return image;
> }`
> ```

I test the code and found issue on android that portrait image will rotate -90˚.
I put an 'if' clause for iOS only for orientationValue == 6 and 8, the issue has gone.
// image_picker: 0.6.1+2

```
if (Platform.isIOS) {
  if (orientationValue == 6) {
    rotate = -90;
  }
  if (orientationValue == 8) {
    rotate = 90;
  }
}
```

I did test 0.6.1+3, when use parameters max_width and max_height, the image does not keep aspect ratio. so I back to 0.6.1+2 and use your code with an if condition.

**Pull request merged**
