### PR TITLE
[Impeller] Continue enabling MSAA for OpenGLES Backend

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/130045 (hypothetically).

Continues the work started in https://github.com/flutter/engine/pull/46381.

## Status

Requesting some help from @chinmaygarde, @bdero, @jonahwilliams.

At this PR, the error `GL_INVALID_OPERATION` occurs on `glFramebufferTexture2DMultisampleEXT`, within `TextureGLES::SetAsFramebufferAttachment`:

```cc
case Type::kRenderBufferMultisampled:
  // Assume that when MSAA is enabled, we're using 4x MSAA.
  FML_DCHECK(GetTextureDescriptor().sample_count == SampleCount::kCount4);
  gl.FramebufferTexture2DMultisampleEXT(
      target,                    // target
      ToAttachmentPoint(point),  // attachment
      GL_TEXTURE_2D,             // textarget
      handle.value(),            // texture
      0,                         // level
      4                          // samples
  );
  break;
```

Logs:

```txt
Abort message: '[FATAL:flutter/impeller/renderer/backend/gles/proc_table_gles.h(39)] Fatal GL Error GL_INVALID_OPERATION(1282) encountered on call to glFramebufferTexture2DMultisampleEXT'

(omitted for brevity)

backtrace:
      #00 pc 0000000000051994  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 4e07915368c859b1910c68c84a8de75f)
      #01 pc 0000000002443ee8  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (std::_LIBCPP_ABI_NAMESPACE::__throw_bad_optional_access[abi:v15000]()+8) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
      #02 pc 0000000002512da0  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (fml::LogMessage::~LogMessage()+340) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
      #03 pc 00000000036f3014  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (impeller::AutoErrorCheck::~AutoErrorCheck()+344) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
      #04 pc 00000000037182cc  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (auto impeller::GLProc<void (unsigned int, unsigned int, unsigned int, unsigned int, int, int)>::operator()<unsigned int&, unsigned int, int, unsigned int&, int, int>(unsigned int&, unsigned int&&, int&&, unsigned int&, int&&, int&&) const+328) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
      #05 pc 0000000003717f84  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (impeller::TextureGLES::SetAsFramebufferAttachment(unsigned int, unsigned int, impeller::TextureGLES::AttachmentPoint) const+664) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
      #06 pc 000000000370c19c  /data/app/~~mtbx6oawj05kVt1E4rjNKA==/com.example.circle_opacity_foo-qbrv7ttHHhJ9pjfyUOlVlw==/lib/arm64/libflutter.so (impeller::EncodeCommandsInReactor(impeller::RenderPassData const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Allocator> const&, impeller::ReactorGLES const&, std::_LIBCPP_ABI_NAMESPACE::vector<impeller::Command, std::_LIBCPP_ABI_NAMESPACE::allocator<impeller::Command> > const&)+468) (BuildId: a7e3e0232ee9baf0f6e360882c443623132212aa)
```

@jonahwilliams is convinced we have a format issue/are missing something else.

It's worth noting this is on a Pixel 5, where MSAA is supported, and sample_count is 4.

### CODE REVIEW

**Comment by bdero** [comment]
According to the [spec](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt):

```
The error INVALID_OPERATION is generated if FramebufferTexture2DMultisampleEXT
    is called with <samples> greater than the maximum number of samples supported
    for <target> and its internalformat.
```

So perhaps the target buffer isn't getting constructed correctly.

What does `GetInternalformativ` return for pname SAMPLES with the target/internal format?

**Comment by matanlurey** [comment]
Updated this PR with some help from @jason-simmons that gets us closer, but now reveals some missing format conversion logic. Still investigating.

**Comment by matanlurey** [comment]
```txt
E/flutter ( 6564): [ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(413)] *** void impeller::TextureGLES::InitializeContentsIfNecessary() const size_w=825 h=825 iformat=6408 eformat=6408
E/flutter ( 6564): [ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(413)] *** void impeller::TextureGLES::InitializeContentsIfNecessary() const size_w=825 h=825 iformat=0 eformat=0
F/flutter ( 6564): [FATAL:flutter/impeller/renderer/backend/gles/proc_table_gles.h(39)] Fatal GL Error GL_INVALID_VALUE(1281) encountered on call to glTexImage2D
```

**Comment by jonahwilliams** [comment]
From some discussions today we had trouble mapping what the state of render_pass gles to what is expected in a number of the gles multisample tutorials. We're going to break out the flow chart and try to re-arrange this code to be easier to understand

**Comment by matanlurey** [comment]
Closing in favor of another PR that gets closer: https://github.com/flutter/engine/pull/47030.

**Pull request closed without merging**
