### PR TITLE
[flutter_releases] Flutter Stable 2.0.5 Engine Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
* Dart SDK
  * https://github.com/dart-lang/sdk/commit/7c8c6b3053d0ba91fcf15f81c45650184dc27e88

### CODE REVIEW

**Comment by christopherfujino** [comment]
overrode the clabot because i authored this commit.

**Review by kf6gpe — APPROVED** [review]
LGTM.

**Comment by sroddy** [comment]
hi,
would it be possible to also cherry-pick this fix in upcoming stable?
https://github.com/flutter/engine/commit/4f6462bc631d8f10f8d7a8456a917ca8a524386d
It covers a critical crash and if you take a look at this https://github.com/flutter/engine/pull/25506#issuecomment-816485849, @mkustermann also recommended to do so.

thanks

**Comment by christopherfujino** [comment]
> hi,
> would it be possible to also cherry-pick this fix in upcoming stable?
> [4f6462b](https://github.com/flutter/engine/commit/4f6462bc631d8f10f8d7a8456a917ca8a524386d)
> It covers a critical crash and if you take a look at this [#25506 (comment)](https://github.com/flutter/engine/pull/25506#issuecomment-816485849), @mkustermann also recommended to do so.

I would recommend following up on that issue about getting approved for a cherrypick. My role is to apply approved cherrypicks, I don't make the call :)

**Comment by kf6gpe** [comment]
@sroddy Looking at the original issue (if I'm reading this right) --- https://github.com/flutter/flutter/issues/79335 --- it was already cherrypicked.

**Comment by christopherfujino** [comment]
Failures are the same as the [previous build](https://github.com/flutter/engine/pull/25341)

**Comment by sroddy** [comment]
@kf6gpe I might be be wrong but it looks like it was cherry-picked in beta but not in stable

**Pull request merged**
