### PR TITLE
Move git revision fetching

### PR DESCRIPTION
**Pull request by zanderso**
Avoids GN invoking python scripts that run git commands to determine git hashes. Instead the git hashes are saved in files by `gclient sync`, and then read out of the files into GN arguments by the `gn` script.

Part of https://github.com/flutter/flutter/issues/144430

### CODE REVIEW

**Comment by jason-simmons** [comment]
Would the performance be acceptable if this invoked the `git rev-parse` command from within the `tools/gn` script instead of writing a file during `gclient runhooks`?

When I run `git rev-parse` on a repository locally it takes around 30 milliseconds.  Doing this within `tools/gn` will avoid the overhead of launching Python within the build scripts and also avoid the need to keep these temporary files in sync.

**Comment by zanderso** [comment]
Does `git rev-parse` hit the network?

**Comment by jason-simmons** [comment]
No - it should only read the local repository filesystem

**Comment by zanderso** [comment]
Closing in favor of https://github.com/flutter/engine/pull/51175

**Pull request closed without merging**
