### PR TITLE
Fix AccessibilityFeatures.disableAnimations flag on Android 12+

### PR DESCRIPTION
**Pull request by hakonber**
This PR fixes the problem where Flutter would not respect the "remove animation" accessibility setting on Android 12+.

Please see this issue for details: https://github.com/flutter/flutter/issues/130976

As [mentioned](https://github.com/flutter/flutter/issues/130976#issuecomment-1931388665) by [horsemankukka](https://github.com/horsemankukka), the problem has to do with reading `Settings.Global.TRANSITION_ANIMATION_SCALE` as a string instead of a float. Flutter would compare it to the string "0" to determine if animations should be disabled. Presumably, this worked because the settings app did indeed use the string "0" or "1" for this setting. But as of Android 12 it's instead written using float representation ("0.0" or "1.0"), at least on Samsung devices. [The documentation](https://developer.android.com/reference/android/provider/Settings.Global#TRANSITION_ANIMATION_SCALE) also states that this setting should be read as a float, which is what this PR does.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Review by reidbaker — APPROVED** [review]
Can you check on a pre android 12 device to make sure that this code does not need to branch? 
For example if before it stored `"0"` instead of `0` (and now stores `0.0`)

**Comment by hakonber** [comment]
Thanks for reviewing @jonahwilliams and @reidbaker. I actually discovered there's a second bug in `AccessibilityBridge.java`, which prevents animations from being disabled when the app is launched. `setBoldTextFlag()` contains a bit twiddling bug which causes all the other flags to be cleared. On app launch the following happens, provided the user has set the following accessibility settings: "Remove animations" on, "Bold text" off.

1) `animationScaleObserver.onChange()` sets the `DISABLE_ANIMATION` flag.
2) Immediately after, `setBoldTextFlag()` clears all flags due to the bit twiddling bug (it was obviously meant to only clear the `BOLD_TEXT` flag).

I've pushed a second commit that fixes this as well, and I now believe https://github.com/flutter/flutter/issues/130976 is fully resolved. To verify, I have created a simple Flutter app that displays the value of `MediaQueryData.disableAnimationsOf(context)`, and I have checked that it is correct both on launch, and when changing the accessibility setting while the app is running. I've attached screen recordings from a Pixel 4 API 29 (Android 10), a Pixel 6 API 33 (Android 13) and a Samsung Galaxy S20 API 33 (Android 13). Note that when changing the "Remove animations" setting, it takes a few seconds before the flag updates after switching back to the app. This happens in native apps as well, so I believe it's just Android being Android, and not a problem with the Flutter engine.

[Pixel 4 API 29.webm](https://github.com/flutter/engine/assets/873092/36c32131-bb41-41ee-9ea9-91d47257c3a5)

[Pixel 6 API 33.webm](https://github.com/flutter/engine/assets/873092/bb76daa6-5649-40c8-858d-ebe5116612a4)

https://github.com/flutter/engine/assets/873092/e238e5ce-a22c-4bcf-8f00-c99145d6a10f





Test app:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child:
              Text('MediaQueryData.disableAnimations=${MediaQuery.disableAnimationsOf(context)}'),
        ),
      ),
    );
  }
}
```

**Review by reidbaker — APPROVED** [review]
@hakonber this looks great thanks for the follow up. The last thing I would ask of you is to modify itSetsBoldTextFlagCorrectly (~line 1325) To check another flag value was not cleared.

**Comment by hakonber** [comment]
@reidbaker, I’ve expanded the `itSetsBoldTextFlagCorrectly` test to verify that clearing the bold text flag doesn’t affect other flags. This change was a bit involved because `AccessibilityBridge` only manipulates the bold text flag in its constructor, so I had to recreate the instance using `setUpBridge`.

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
