### PR TITLE
[Impeller] libImpeller: Publish SDK artifacts.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/156358

### CODE REVIEW

**Comment by chinmaygarde** [comment]
I can verify that the zip is being created. Not necessarily sure if the manifest updates to upload the artifacts are good though.

**Review by zanderso — COMMENTED** [review]
Is there any need for a library from a release Android build?

**Comment by chinmaygarde** [comment]
No. Release/profile/debug are all the same. Just added the debug variants on all.

**Review by zanderso — APPROVED** [review]

**Comment by chinmaygarde** [comment]
The presubs are sufficient to check the paths in the manifest right? I didn't know how to test those.

**Comment by zanderso** [comment]
> The presubs are sufficient to check the paths in the manifest right? I didn't know how to test those.

Yes. See step 26 on https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2777090/overview.

**Pull request merged**
