### PR TITLE
Use identical in hashValues instead of operator==

### PR DESCRIPTION
**Pull request by PixelToast**
`identical` is more performant than operator==, especially when it otherwise performs dynamic dispatch and null checking.

Here is the before and after disassembly if you are interested: https://gist.github.com/PixelToast/3961886232a5dc21ca51b574b4678737 (engine d1f3037c4c8950796e4409ddce7c3f1bf387f24f)

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Nice!

**Comment by jonahwilliams** [comment]
I think you need to pull in HEAD to fix the web failure, otherwise this looks great

**Comment by jonahwilliams** [comment]
Linux Web rerun : https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Engine/6577
Mac iOS rerun: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine/5396

**Comment by PixelToast** [comment]
Both reruns green, merging :)

**Comment by jonahwilliams** [comment]
mergeeeee!

**Comment by rakudrama** [comment]
An alternative to changing `==` to `identical` would be to put the constant first, e.g. `_hashEnd == arg03`.
Remember that `==` invokes the `operator==` of the first operand, and if the _receiver_ is a constant, the compiler can tell which `operator==` is called. In this case it is `Object.==`, which is implemented as `identical`, so you will get code as good as using `identical`.

**Pull request merged**
