### PR TITLE
Support 120HZ refresh rate on iOS

### PR DESCRIPTION
**Pull request by luckysmg**
On iOS,we should set the `preferredFrameRateRange` explicitly to make `CADisplayLink` ‘s callback call 120 times per second.

And after we  add `<key>CADisableMinimumFrameDurationOnPhone</key><true/>` in project `Info.plist` file,120HZ is available on flutter.Here is related Apple dev [doc:](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro)

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/90675

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by luckysmg** [comment]
The new API is available On Xocde 13,Xcode 12 don't have the `CAFrameRateRange` API

**Comment by luckysmg** [comment]
Setting `CADisableMinimumFrameDurationOnPhone` value only is not enough,we should also set the `preferredFrameRateRange` property to enable fast refresh rate.

Here is the text in [Apple dev doc](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc)
`Your app must use this key to access higher frame rates (above 60Hz) it sets in the preferredFrameRateRange hint API. The iPad Pro doesn’t require this special configuration.`

So I think set the `preferredFrameRateRange` is also necessary for iPhone.
**But we should do something like [Provide Timing Hints to Core Animation](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc) instead of simply setting the `preferredFrameRateRange` to `CAFrameRateRange(minimum: 60, maximum: 120, preferred: 120)`.** Am I getting this right?

**Comment by luckysmg** [comment]
Got it 😄

**Comment by chinmaygarde** [comment]
From Kaushiks last comment, the way to proceed on this is in collaboration with signals from the framework on when to opt-into render at higher refresh rates.

**Pull request closed without merging**
