### PR TITLE
Update buildtools to Fuchsia HEAD

### PR DESCRIPTION
**Pull request by cbracken**
Updates to Clang 7 toolchain.

### CODE REVIEW

**Comment by jason-simmons** [comment]
Travis is showing a lot of formatting errors.  Does the configuration of clang-format need to be updated?

**Comment by cbracken** [comment]
Yep. Looks like it'll need some tweaking. I'll tweak the config to get us as close as possible to where we were.

**Comment by chinmaygarde** [comment]
`clang-format`s opinion of the correct format is fluid and I doubt it is feasible to update all source files in question with each buildtools roll. However, it is possible to check if only the specific files in a patch are properly formatted. I believe it is better to switch the check to work this way instead of having it fail for formatting errors in any part of the codebase.

**Comment by cbracken** [comment]
That seems reasonable and less work than trying to find all the new settings and reverting them as close to what they previously were with each roll. I'll take a look at updating the check.

**Comment by chinmaygarde** [comment]
The script in question is at `./buildtools/mac-x64/clang/share/clang/clang-format-diff.py`

**Comment by cbracken** [comment]
> The script in question is at ./buildtools/mac-x64/clang/share/clang/clang-format-diff.py

Landed in #4605. Rebased and will wait for a clean Travis run.

**Pull request merged**
