### PR TITLE
[icu] Update icu to 20f8ac695af59b6c830def7d4e95bfeb13dd7be5

### PR DESCRIPTION
**Pull request by filmil**
Brings the ICU library use in Flutter engine to the current ICU ToT.

2nd step into a 2-step update.
See: https://github.com/flutter/engine/pull/36360

Issue: https://github.com/flutter/flutter/issues/112227

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by filmil** [comment]
Please don't merge just yet. I'll let y'all know when.

**Comment by filmil** [comment]
@jason-simmons This is ready for review, would you mind?

**Review by zanderso — APPROVED** [review]

**Comment by filmil** [comment]
Thank you!

**Comment by zanderso** [comment]
@keyonghan The autosubmit bot incorrectly rejected this PR.

**Review by jason-simmons — APPROVED** [review]

**Comment by akbiggs** [comment]
`The autosubmit bot incorrectly rejected this PR.` I don't think that's correct, @filmil is not part of the Flutter org yet.

**Comment by filmil** [comment]
Thank you folks!

**Pull request merged**
