### PR TITLE
feature: add dom canvas drawatlas.

### PR DESCRIPTION
**Pull request by lfkdsk**
- add matrix columns method.
- add flutter-web dom canvas `drawAtlas`.

### CODE REVIEW

**Comment by lfkdsk** [comment]
Hi @jason-simmons

**Comment by jason-simmons** [comment]
@ferhatb @yjbanov

**Comment by ferhatb** [comment]
@lfkdsk thank you for contributing, can you please add a test, please take a look at canvas_arc_golden_test.dart as example.

Once you have a test, you can set matchGoldenFile write:true , then run dev/felt test test/golden_tests/engine/mytest.dart which will generate a file you can commit into github.com/flutter/goldens repo. Then remove write:true and update golden_locks.yaml file with that commit.

**Comment by yjbanov** [comment]
Closing as the PR is not in a mergeable state. I think next steps are to start a new PR with tests.

**Pull request closed without merging**
