### PR TITLE
[iOS text input] do not forward press events to the engine

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
- Fixes https://github.com/flutter/flutter/issues/89378

Now that the input views are no longer direct children of `UIWindow`, press events will be handed to `FlutterInputView` and then`FlutterViewController`. We no longer need to manually forward the event to the engine and let the engine pass that to the view controller, as the super implementation already does that. Plus `nextAction` also forwards the incoming events to the view controller so that call path is essentially sending the same event to `FlutterViewController` twice.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Actually, test failed:
```
Failing tests:
	IosUnitTestsTests:
		-[FlutterTextInputPluginTest testPropagatePressEventsToNextResponder]
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Modulo the test failure.

**Comment by LongCatIsLooong** [comment]
> Actually, test failed:
> 
> ```
> <unknown>:0: error: -[FlutterTextInputPluginTest testPropagatePressEventsToNextResponder] : Did not record an invocation in OCMStub/OCMExpect/OCMReject.
> Possible causes are:
> - The receiver is not a mock object.
> - The selector conflicts with a selector implemented by OCMStubRecorder/OCMExpectationRecorder. (NSInternalInconsistencyException)
> ...
> Failing tests:
> 	IosUnitTestsTests:
> 		-[FlutterTextInputPluginTest testPropagatePressEventsToNextResponder]
> ```

I noticed my tests are not re-compiled after I changed the code (I renamed the test and then recompiled & rerun it, the output still showed the old name of the test). I did recompile the `ios_test_flutter` target before running `./run_tests.py --type=objc`. What am I missing?

**Pull request merged**
