### PR TITLE
WeakPtrFactory should be destroyed before any other members.

### PR DESCRIPTION
**Pull request by 0xZOne**
WeakPtrFactory should remain the last member so it'll be destroyed and invalidate its weak pointers before any other members are destroyed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
We should not move ivars below methods/friend declarations for testing. That goes against the style guide.

There are two "real" instances here where it could matter: `accessibility_bridge.h` and `rasterizer.h`. We're lucky in that neither of those declare an ivar that actually uses the weak pointer that the factory would vend.

Given that, we should definitely take whatever time needed to add analysis/tests for this.

**Comment by 0xZOne** [comment]
> We should not move ivars below methods/friend declarations for testing. That goes against the style guide.
> 
> There are two "real" instances here where it could matter: `accessibility_bridge.h` and `rasterizer.h`. We're lucky in that neither of those declare an ivar that actually uses the weak pointer that the factory would vend.
> 
> Given that, we should definitely take whatever time needed to add analysis/tests for this.

Thank you for your reply. 

As per [Declaration Order](https://google.github.io/styleguide/cppguide.html#Declaration_Order), all data members should be last. Another purpose here is to alleviate the risk of new members being mistakenly inserted after |WeakPtrFactory|.

**Comment by dnfield** [comment]
So I learned! But if we're moving them we should move all of them.

I also see that there are some objc files that are impacted by this but not fixed.

**Comment by 0xZOne** [comment]
> So I learned! But if we're moving them we should move all of them.
> 
> I also see that there are some objc files that are impacted by this but not fixed.


Please have another look at it, Thanks.

**Comment by dnfield** [comment]
This still needs some kind of test (static analysis would be fine) to make sure that these rules are followed.

**Comment by 0xZOne** [comment]
> This still needs some kind of test (static analysis would be fine) to make sure that these rules are followed.

Got it. Are there any examples I can refer to?

**Comment by dnfield** [comment]
I'm not sure. We do run clang-tidy but I don't think that can detect this.

**Comment by 0xZOne** [comment]
> I'm not sure. We do run clang-tidy but I don't think that can detect this.

OK, thanks anyway. :)

**Comment by 0xZOne** [comment]
@dnfield 

I found that chromium has a clang plugin to check the WeakPtrFactory class member order. Maybe we can port the clang plugin to flutter.

See [FindBadConstructsConsumer::CheckWeakPtrFactoryMembers](https://source.chromium.org/chromium/chromium/src/+/main:tools/clang/plugins/FindBadConstructsConsumer.cpp;drc=ead8ffe5105c70fe36b18089b71c46b9055e530b;l=959) for details.

I want to finish it. However, I am not familiar with the build system, nor do I have time to dig into it recently. Any bits of advice? Thanks.

**Comment by dnfield** [comment]
Talked to some Fuchsia Toolchain folks, and they suggested implementing these as clang-tidy checks. Fuchsia already has some at https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clang-tidy/fuchsia

I am not clear on who might be available to do this, if anyone is right now, or if this is something @0xZOne would be interestedin trying, but just trying to leave some more breadcrumbs here.

**Review by dnfield — APPROVED** [review]
This LGTM but will need a test exemption from @hixie to land.

**Comment by dnfield** [comment]
Also, per our updated policy, this needs a review from someone else with commit access to the repo before landing.

**Comment by Hixie** [comment]
test-exempt: only affects analysis

Please document the desired analysis in an issue and link that issue here. Thanks.

**Comment by 0xZOne** [comment]
> test-exempt: only affects analysis
> 
> Please document the desired analysis in an issue and link that issue here. Thanks.

Related issue: [#93039](https://github.com/flutter/flutter/issues/93039#issuecomment-964746215)

**Review by zanderso — APPROVED** [review]

**Pull request merged**
