### PR TITLE
In the scenario game loop test, cancel the results writer task if the activity has been destroyed

### PR DESCRIPTION
**Pull request by jason-simmons**
This test is run on Firebase Test Lab, and crashes have been reported on CI if this task executes when the activity is in a destroyed state.

See https://github.com/flutter/flutter/issues/138451

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

This approach sounds reasonable to me, though I don't have full context into the intention of the test.

**Comment by reidbaker** [comment]
Will this test fail when the code under test has a problem? I havent spent much time in this file but it seems that if the activity was launched then immediately killed this would cause a false positive.

**Comment by jason-simmons** [comment]
Currently the test will crash if Android closes the activity.  The host environment can close any activity at any time, and the activity should be resilient to this.

**Comment by reidbaker** [comment]
> Currently the test will crash if Android closes the activity. The host environment can close any activity at any time, and the activity should be resilient to this.

I think my point is that the test might be marked passing even if the code that the test is supposed to test is failing. That said I dont understand what is happening here and clearly you do so RSLGTM.

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
Do you have a link I can use to monitor these tests so i can know when they should be marked as non flakey?

**Comment by jason-simmons** [comment]
These tests are run as part of the `linux_android_aot_engine` builder, which has been flaking recently.

Watch the history of that builder at:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_android_aot_engine

**Pull request merged**
