### PR TITLE
[web] remove runtime effect check

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/114260

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by feinstein** [comment]
The docs on `InkSparkle` mention it's not supported on CanvasKit and we should look [this issue](https://github.com/flutter/flutter/issues/85238). But the issue is closed, so shouldn't the docs be updated?

**Comment by jonahwilliams** [comment]
yes, this is all done and should work. Thanks for the heads up on the docs, we missed that one.

**Comment by feinstein** [comment]
My pleasure.

**Pull request merged**
