### PR TITLE
[Impeller] Account for the transform in DLVerticesGeometry coverage

### PR DESCRIPTION
**Pull request by bdero**
Happened across this bug while smoke testing Gallery.

Before:
Screenshot 2023-01-19 at 2 36 07 AM

After:
Screenshot 2023-01-19 at 2 34 08 AM

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
D'oh

**Comment by chinmaygarde** [comment]
@zanderso I believe this is a cherry pick candidate as well. How do I kick start the process?

**Comment by zanderso** [comment]
@chinmaygarde I've already filed the request here https://github.com/flutter/flutter/issues/118850 with the CP PR here https://github.com/flutter/engine/pull/39014. If you can lgtm in both places, that will help =)

**Comment by chinmaygarde** [comment]
Ah, I missed it. Thank you so much! 🙏🏽

**Pull request merged**
