### PR TITLE
Wrap strdup to use compliant name on Windows

### PR DESCRIPTION
**Pull request by stuartmorgan**
A number of POSIX methods were renamed on Windows to match standards
requirements, giving deprecation warnings when calling strdup on Windows.
This adds a wrapper, to allow calling _strdup on Windows instead.

Part of https://github.com/flutter/flutter/issues/16256

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Let me know what you think of this approach. The other option is to define `_CRT_NONSTDC_NO_DEPRECATE` and ignore the deprecation, but that seems like a big hammer for just one method. (It's not necessarily a terrible idea though; Microsoft's documentation does suggest that cross-platform code might want to go with that approach for compatibility reasons.)

**Comment by chinmaygarde** [comment]
I'd prefer `_CRT_NONSTDC_NO_DEPRECATE` since authors will typically default to that instead of remember to use the FML variant.

**Comment by chinmaygarde** [comment]
But your call.

**Comment by chinmaygarde** [comment]
The bot is mad at the infinite recursion in your posix implementation. Prepend `::` to make it call the C variant.

**Comment by stuartmorgan** [comment]
> I'd prefer `_CRT_NONSTDC_NO_DEPRECATE` since authors will typically default to that instead of remember to use the FML variant.

Well, since the goal is to switch to using clang on the bots, this will fail, so people won't actually have to remember.

**Comment by chinmaygarde** [comment]
> Well, since the goal is to switch to using clang on the bots, this will fail, so people won't actually have to remember.

It will fail on the bots though instead of the local development environment of someone on a linux workstation right? In any case, either way is fine. This is still an improvement.

**Comment by stuartmorgan** [comment]
I'm going to go with this for now and we can revisit if it becomes a pain point; I'd like to avoid deliberately using deprecated code indefinitely in code we control.

**Pull request merged**
