### PR TITLE
Roll Skia revision to 342977ced701d06df2b3d2eedd8b64aeae1eb5c5

### PR DESCRIPTION
**Pull request by fmalita**
Roll Skia and convert to the new SkVertices factory API (Make & MakeIndexed are no longer supported).

Compile-tested.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM but looks like we need to update the license file.

**Comment by fmalita** [comment]
How do I update the license file?  I found this doc but it appears to be out of date: https://github.com/flutter/engine/blob/master/tools/licenses/README

**Comment by abarth** [comment]
Try rebasing.  The diff to the license file that Travis has looks like it contains a bunch of stuff that's unrelated to your patch (and was fixed recently).  Then Travis should give you the diff to apply to the license file.

**Comment by jason-simmons** [comment]
Yes - the docs are out of date.  I'm updating them at:
    https://github.com/flutter/engine/pull/3525/files

Sync up to the latest tip of tree and run the script at the link above

**Comment by fmalita** [comment]
Thanks, updated following the new procedure.

The LICENSE diff looks pretty scary, but I guess it's passing the checks.

**Comment by jason-simmons** [comment]
LGTM

**Comment by fmalita** [comment]
Thanks Jason.  I don't have commit access, do you mind merging?

**Pull request merged**
