### PR TITLE
Revert "Reland "add non-rendering operation culling to DisplayListBuilder" (#41463)"

### PR DESCRIPTION
**Pull request by bdero**
Reverts flutter/engine#42584. (Thanks to @jonahwilliams for bisecting)

With this change, layers are getting clipped incorrectly when rendering platform views in Wondrous.

Issue: https://github.com/flutter/flutter/issues/129816.

Before revert:

https://github.com/flutter/engine/assets/919017/def28cea-755d-4427-8f65-f7c5e7479e1d

After revert:

https://github.com/flutter/engine/assets/919017/b3ba55f3-8c86-472f-9416-ea4ad3ed5801

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

I think we'll need to file a cp request if this has missed the branch cut off too. We can deal with that later though

**Comment by chinmaygarde** [comment]
@bdero In the videos, the first couple of seconds with the swipe down seem janky. Are those real issues on the latest build or an artifact of how the video was captured? Just a drive by comment on something unrelated :)

**Comment by jonahwilliams** [comment]
on non-release builds the google maps plugin initialization is really slow. Doesn't happen in release mode

**Comment by bdero** [comment]
Yeah, I think this debug-only stutter in Wondrous is a known quantity and has been around for a long time.

**Pull request merged**
