### PR TITLE
Roll dart to 2cbcb175cc1e6d2ed095385a4c48492e1fee8638

### PR DESCRIPTION
**Pull request by aam**

### CODE REVIEW

**Comment by rmacnak-google** [comment]
I get an error in the host build:

```
python ../../third_party/dart/build/gn_run_binary.py compiled_action /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/tools/sdks/linux/dart-sdk/bin/dart --packages=/usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/.packages /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart build-strong /usr/local/google/home/rmacnak/Flutter/engine/src/out/host_debug/gen/strong.sum /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/sdk
Command failed: /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/tools/sdks/linux/dart-sdk/bin/dart --packages=/usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/.packages /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/pkg/analyzer/tool/summary/build_sdk_summaries.dart build-strong /usr/local/google/home/rmacnak/Flutter/engine/src/out/host_debug/gen/strong.sum /usr/local/google/home/rmacnak/Flutter/engine/src/third_party/dart/sdk
output: 'package:watcher/src/utils.dart': malformed type: line 81 pos 43: cannot resolve class 'StreamTransformerBase' from 'BatchedStreamTransformer'
class BatchedStreamTransformer<T> extends StreamTransformerBase<T, List<T>> {
```

**Comment by aam** [comment]
@rmacnak-google wrote 
> I get an error in the host build:Unable to spawn isolate: 

Hmm, somehow it builds fine for me, but it did fail on travis with error similar to yours:
```
'package:async/src/single_subscription_transformer.dart': malformed type: line 16 pos 51: cannot resolve class 'StreamTransformerBase' from 'SingleSubscriptionTransformer'
class SingleSubscriptionTransformer<S, T> extends StreamTransformerBase<S, T> {
```

**Comment by aam** [comment]
Might be caused by https://github.com/dart-lang/sdk/commit/5e87644f1ef2cc6c44ab2ebdc620b8e542d5a319. I reverted changes to pub packages for now.

**Comment by leafpetersen** [comment]
this usually means that you are running code from dev.20 or later with a pre dev.20 version of the dart vm.  I believe that the dart vm has a snapshot of the SDK core libaries.  dev.20 changed the core libraries to include a new StreamTransformerBase class, and pub packages were modified (with a dev.20 sdk constraint) to use the new StreamTransformerBase.  If you try to run code that uses StreamTransformerBase with a pre dev.20 build of the dart vm, it will fail.

**Comment by aam** [comment]
thanks @leafpetersen ! Yes, that is what we are finding out now too. flutter repo had dart pinned to dev.16, which seems to have caused the problems.

**Comment by leafpetersen** [comment]
dev.16 also had a bug in pub which caused it to not respect package lower bound sdk constraints, and so it could pull in packages which required dev.20.  @devoncarew would know more - I thought he rolled flutter to dev.19 to fix this?

**Comment by devoncarew** [comment]
Yup, rolled to dev.19, ~6 days ago: https://github.com/flutter/flutter/blob/master/bin/internal/dart-sdk.version.

**Comment by aam** [comment]
There are two other places where we still had dev.16 hardcoded: engine/src/flutter/.travis.yml and buildroot/src/tools/dart/update.py

**Comment by devoncarew** [comment]
Ah, good to know.

**Comment by aam** [comment]
Obsolete now

**Pull request closed without merging**
