### PR TITLE
Add versions to all the dependencies so they are pinned.

### PR DESCRIPTION
**Pull request by ricardoamador**
## Description of The Issue Being Addressed
The builder config is fragile when dependencies are not pinned to specific versions. Any upstream changes may cause breakage. We should create a test to validate all .ci.yaml dependencies are pinned. This also requires that we pin specific versions for all dependencies.

## Issues Addressed
https://github.com/flutter/flutter/issues/101712

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
Tree is red. Once https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=main goes green, you'll need to rebase this PR with upstream/main.

```
git fetch --all
git rebase upstream/main
```

**Comment by ricardoamador** [comment]
Thank you Casey! I will make those changes.

**Review by keyonghan — APPROVED** [review]
LGTM. You can add the `waiting for tree to go green` label to have the bot auto submit.

**Comment by ricardoamador** [comment]
Oh cool I did not know that. Thanks Keyong!

**Pull request merged**
