### PR TITLE
Remove the Point class.

### PR DESCRIPTION
**Pull request by Hixie**
@abarth 

This is the engine side. Please do not commit until the framework side is ready.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
I've added a commit that adds Size.contains and Rect.translate.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
I had to revert some of the Size/Offset changes because of _DebugSize.
I took the opportunity to inline the Size/Offset super.== calls so that they are infinitesimally faster.

**Pull request merged**
