### PR TITLE
Fix the units for Pointer events

### PR DESCRIPTION
**Pull request by abarth**
The time_stamp is supposed to be in microseconds. Previously we were using
milliseconds.

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by krisgiesing** [comment]
Do velocity calculations still work properly after this change? I remember I had to futz with the time scale a bit when porting to Dart.

**Comment by krisgiesing** [comment]
Ah, I see it was already broken and you're fixing it.

**Comment by abarth** [comment]
Yeah, I'm fixing that in https://github.com/flutter/flutter/pull/435

**Pull request merged**
