### PR TITLE
Reland layer state stack 2

### PR DESCRIPTION
**Pull request by flar**
This reland fixes the cached rendering issues (see https://github.com/flutter/flutter/issues/114359) resulting from doubling up the transform when preparing a state stack for updating a cache entry.

Many of the performance regressions seem to be better now with these recent fixes, but I've been trying to track down a 10-20% regression in some of the peephole benchmarks. Most notably the "grid of opacity" benchmark (see the 2 recent bumps in [this Skia Perf graph](https://flutter-flutter-perf.skia.org/e/?begin=1663036524&end=1667853776&queries=sub_result%3Daverage_frame_rasterizer_time_millis%26test%3Dopacity_peephole_grid_of_opacity_perf__e2e_summary&requestType=0&selected=commit%3D31839%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dopacity_peephole_grid_of_opacity_perf__e2e_summary%252C)). I've tracked this down to the most probable cause being the copies and manipulations of SkM44 matrices that can be reduced or eliminated with more work.

I'm creating this PR now so that some developers can have access to the bug fixes before I fix the last of the performance regressions.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
When I run the sample app with the diff in https://github.com/flutter/flutter/issues/114712 There are some odd rendering artifacts:

flutter_02

**Comment by jonahwilliams** [comment]
Actually nevermind, this is happening on ToT

**Comment by jonahwilliams** [comment]
I did some profiling of this PR vs ToT on the regressed grid of opacity benchmark on an iPhone 6-something.

ToT Trace:
[Pre-Change.trace.zip](https://github.com/flutter/engine/files/10015433/Pre-Change.trace.zip)

With Change:
[WithLSS.trace.zip](https://github.com/flutter/engine/files/10015438/WithLSS.trace.zip)

These profiles can be viewed by unzipping and opening in Instruments. The first few seconds are just navigation to the actual benchmark.

With a little bit of charge to callers, I can see that LayerStateStack::restore_to_count and LayerStateStack::do_save end up surprisingly high in the profile's self time. This may or may not constitute part of the reason for the regression.

LSSTrace

**Comment by flar** [comment]
@jonahwilliams but did you see an actual regression on the iPhone? I see a net gain in performance on a Pixel 6a, so it isn't so much "that method is called a lot" unless there is something about that method that runs faster on a Pixel than on a Moto G4. Zach's guess that this is a case of blowing the smaller CPU caches on the Moto G4 due to code on different cache lines being hit makes sense, especially since much of this logic used to be duplicated into the Preroll/Paint methods. Now those methods are calling into a mechanism which may live on different code pages in memory.

**Comment by jonahwilliams** [comment]
I don't really observe any regression on iOS locally, I'll try on Android in a bit.

ToT:

```
  "average_frame_rasterizer_time_millis": 0.812,
  "90th_percentile_frame_rasterizer_time_millis": 0.897,
  "99th_percentile_frame_rasterizer_time_millis": 1.035,
  "worst_frame_rasterizer_time_millis": 1.121,
```

Patch:
```
  "average_frame_rasterizer_time_millis": 0.828,
  "90th_percentile_frame_rasterizer_time_millis": 0.897,
  "99th_percentile_frame_rasterizer_time_millis": 1.003,
  "worst_frame_rasterizer_time_millis": 1.066,
```

**Review by dnfield — APPROVED** [review]

**Comment by flar** [comment]
I'm holding off on this while I investigate a prototype for a lower-overhead version that uses stack-allocated objects in lieue of the current vector of StateEntry objects...

**Comment by flar** [comment]
The new prototype was less wieldy than the existing design. I think I can retrofit some of the concepts back onto the existing design in a future effort, so I'm removing the WIP label on this PR.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
