### PR TITLE
Disable profiling by default. Allow enabling via --enable-dart-profiling.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/6904

### CODE REVIEW

**Comment by Hixie** [comment]
If you land this please also update all our docs (especially debugging.md on the web site) to explain how to do profiling.

**Comment by chinmaygarde** [comment]
> If you land this please also update all our docs (especially debugging.md on the web site) to explain how to do profiling.

Aye, though the tools should add this flag unconditionally when they launch the application. Because in that case, there is no debugger.

**Comment by chinmaygarde** [comment]
Also, i'll add it when I roll the engine to pull in this patch.

**Comment by Hixie** [comment]
Oh if the tool is always going to set this then I'm far less worried about it. I misunderstood where you were going with this. My apologies.

**Comment by Hixie** [comment]
(You should still make sure this is documented somewhere, but maybe the appropriate place is in our wiki docs rather than the web site, since it's more about our internal APIs than anything public. Do we document our engine flags anywhere yet?)

**Comment by chinmaygarde** [comment]
Yeah, the tools will unconditionally set this flag. Just like they use the `--non-interactive` flag. This should only matter to tool developers. Not users.

I'll document the engine flags. I have to routinely look up `switches.cc` to figure out what they mean.

**Comment by Hixie** [comment]
Fantastic. +1

**Comment by chinmaygarde** [comment]
Bump. LGTM sauce?

**Comment by abarth** [comment]
LGTM

**Pull request merged**
