### PR TITLE
Use MSAA on web to support antialiased vertices

### PR DESCRIPTION
**Pull request by dnfield**
Part of https://github.com/flutter/flutter/issues/77485 - covers CanvasKit web.

This patch turns on MSAA for the surface used by CanvasKit. It means that drawVertices calls get antialiasing. Without this, they cannot (drawVertices does not do any analytical AA).

I've done a few runs of Gallery transitions locally and it seems to improve raster and frame times across the board. My assumption here is that Skia is able to do some better things when it knows MSAA is enabled, but I haven't fully verified that. 

I've tried to add a golden test but haven't run it locally so it may need tweaking.

### CODE REVIEW

**Comment by dnfield** [comment]
Transitions perf in Chrome on my macbook:

```
{
  "average_frame_build_time_millis": 6.041,
  "90th_percentile_frame_build_time_millis": 14.4,
  "99th_percentile_frame_build_time_millis": 54.6,
  "worst_frame_build_time_millis": 113.5,
  "missed_frame_build_budget_count": 20,
  "average_frame_rasterizer_time_millis": 7.414,
  "90th_percentile_frame_rasterizer_time_millis": 6.299,
  "99th_percentile_frame_rasterizer_time_millis": 142,
  "worst_frame_rasterizer_time_millis": 191.5,
  "average_layer_cache_count": 0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0,
  "90th_percentile_layer_cache_memory": 0,
  "99th_percentile_layer_cache_memory": 0,
  "worst_layer_cache_memory": 0,
  "average_picture_cache_count": 0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0,
  "90th_percentile_picture_cache_memory": 0,
  "99th_percentile_picture_cache_memory": 0,
  "worst_picture_cache_memory": 0,
  "missed_frame_rasterizer_budget_count": 20,
  "frame_count": 219
}

{
  "average_frame_build_time_millis": 5.285,
  "90th_percentile_frame_build_time_millis": 12.699,
  "99th_percentile_frame_build_time_millis": 40.701,
  "worst_frame_build_time_millis": 59.4,
  "missed_frame_build_budget_count": 19,
  "average_frame_rasterizer_time_millis": 6.244,
  "90th_percentile_frame_rasterizer_time_millis": 3,
  "99th_percentile_frame_rasterizer_time_millis": 111.7,
  "worst_frame_rasterizer_time_millis": 196.4,
  "average_layer_cache_count": 0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0,
  "90th_percentile_layer_cache_memory": 0,
  "99th_percentile_layer_cache_memory": 0,
  "worst_layer_cache_memory": 0,
  "average_picture_cache_count": 0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0,
  "90th_percentile_picture_cache_memory": 0,
  "99th_percentile_picture_cache_memory": 0,
  "worst_picture_cache_memory": 0,
  "missed_frame_rasterizer_budget_count": 18,
  "frame_count": 222
}
```

AFTER
```
{
  "average_frame_build_time_millis": 5.028,
  "90th_percentile_frame_build_time_millis": 12.601,
  "99th_percentile_frame_build_time_millis": 37.7,
  "worst_frame_build_time_millis": 64.701,
  "missed_frame_build_budget_count": 19,
  "average_frame_rasterizer_time_millis": 6.49,
  "90th_percentile_frame_rasterizer_time_millis": 2.899,
  "99th_percentile_frame_rasterizer_time_millis": 117.8,
  "worst_frame_rasterizer_time_millis": 173.599,
  "average_layer_cache_count": 0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0,
  "90th_percentile_layer_cache_memory": 0,
  "99th_percentile_layer_cache_memory": 0,
  "worst_layer_cache_memory": 0,
  "average_picture_cache_count": 0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0,
  "90th_percentile_picture_cache_memory": 0,
  "99th_percentile_picture_cache_memory": 0,
  "worst_picture_cache_memory": 0,
  "missed_frame_rasterizer_budget_count": 15,
  "frame_count": 204
}

{
  "average_frame_build_time_millis": 5.016,
  "90th_percentile_frame_build_time_millis": 12.9,
  "99th_percentile_frame_build_time_millis": 41.7,
  "worst_frame_build_time_millis": 55.3,
  "missed_frame_build_budget_count": 18,
  "average_frame_rasterizer_time_millis": 6.522,
  "90th_percentile_frame_rasterizer_time_millis": 2.6,
  "99th_percentile_frame_rasterizer_time_millis": 125.7,
  "worst_frame_rasterizer_time_millis": 172.9,
  "average_layer_cache_count": 0,
  "90th_percentile_layer_cache_count": 0,
  "99th_percentile_layer_cache_count": 0,
  "worst_layer_cache_count": 0,
  "average_layer_cache_memory": 0,
  "90th_percentile_layer_cache_memory": 0,
  "99th_percentile_layer_cache_memory": 0,
  "worst_layer_cache_memory": 0,
  "average_picture_cache_count": 0,
  "90th_percentile_picture_cache_count": 0,
  "99th_percentile_picture_cache_count": 0,
  "worst_picture_cache_count": 0,
  "average_picture_cache_memory": 0,
  "90th_percentile_picture_cache_memory": 0,
  "99th_percentile_picture_cache_memory": 0,
  "worst_picture_cache_memory": 0,
  "missed_frame_rasterizer_budget_count": 15,
  "frame_count": 204,
}
```

**Comment by skia-gold** [comment]
Gold has detected about 52 new digest(s) on patchset 4.
View them at https://flutter-engine-gold.skia.org/cl/github/31922

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 6.
View them at https://flutter-engine-gold.skia.org/cl/github/31922

**Comment by dnfield** [comment]
I do not understand the mac failures.

**Comment by dnfield** [comment]
Marking as a draft for now - we need to figure out if there's any way that makes sense to land this and still deal with https://github.com/flutter/flutter/issues/53787

**Comment by dnfield** [comment]
Closing this - I don't think we can move forward with this as-is.

**Pull request closed without merging**
