### PR TITLE
Reland "[web] Avoid returning int from js interop classes."

### PR DESCRIPTION
**Pull request by joshualitt**
Relands #37336

### CODE REVIEW

**Comment by joshualitt** [comment]
@eyebrowsoffire  ptal, this CL is mostly just the reland, but `image_web_codecs.dart` has new logic to handle `repetitionCount`.

**Comment by skia-gold** [comment]
Gold has detected about 71 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/37627

**Comment by joshualitt** [comment]
@eyebrowsoffire  ptal, this CL should be ready to go.

**Review by eyebrowsoffire — APPROVED** [review]
Looks good!

**Pull request merged**
