### PR TITLE
support init engine asynchronous

### PR DESCRIPTION
**Pull request by lybeen**
## Description

*In Engine initialization, we have to wait for all other threads ready, it has an opportunity to improve it, so I make this asynchronous.*

#### Before
4C888FFB-440C-4314-874F-9F9AA6CC7337

#### After
2459FB6E-7F2C-41F7-B5C9-B1BEBDBC1E29

#### Conclusion:
It's clearly show that it makes ui thread asynchronous , platform thread does't have to wait for it in engine initialization.
It may make about *200ms* time for platform thread.

## Related Issues

*[19641](https://github.com/flutter/engine/pull/19641?spm=ata.13261165.0.0.627f4f59iRUf3Z)*

This pr seems a little hackable, my solution seems a bit more sensible.

## Tests

I added the following tests:

*Go through all test cases*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by lybeen** [comment]
@googlebot I fixed it.

**Comment by chinmaygarde** [comment]
cc @jason-simmons @liyuqian

**Comment by liyuqian** [comment]
This approach looks similar to https://github.com/flutter/engine/pull/18047. That PR is very close to pass all the tests but there's some mysterious ["Windows Host Engine" failure][1]. @lybeen : can you please check if that PR is helpful in your case, and whether you're able to revise your PR to pass all tests?

[1]: https://github.com/flutter/engine/pull/18047#issuecomment-656345654

**Comment by gaaclarke** [comment]
I've worked with this issue in the past with another contributor.  There are too many places where we assume we have an initialized Shell.  I don't want to create the opportunity to create bugs by allowing shell to be in yet another state.

I think this is a good goal but the change should use std::future to represent a shell that hasn't been initialized yet so that we can safely migrate the code to using it.  The previous contributor did most of the work but ran into memory problems on windows which they didn't address so it stalled out.

**Comment by chinmaygarde** [comment]
Closing this as we want to go with another approach.

**Pull request closed without merging**
