### PR TITLE
Switch some ERROR logs to WARNING logs

### PR DESCRIPTION
**Pull request by johnmccutchan**

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
You might consider leaving out the log message altogether, if its not directly actionable.

**Comment by johnmccutchan** [comment]
> You might consider leaving out the log message altogether, if its not directly actionable.

It's useful information for someone working on the engine. Is there not a way

**Comment by jonahwilliams** [comment]
In that case an INFO or ERROR seems reasonable, and I would probably update the test to ignore this message

**Comment by johnmccutchan** [comment]
Oops, did not mean to close the pull request.

**Comment by johnmccutchan** [comment]
> In that case an INFO or ERROR seems reasonable, and I would probably update the test to ignore this message

I would do that but I have no idea how to do that nor is there anything printed in the test failure on how one might go about making an exception for some logs.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by johnmccutchan** [comment]
Thanks!

**Pull request merged**
