### PR TITLE
Increase check_roll limit

### PR DESCRIPTION
**Pull request by liyuqian**

### CODE REVIEW

**Comment by liyuqian** [comment]
Shall we first unblock it before the rotation and deletion of this script?

**Comment by chinmaygarde** [comment]
Setting up the rotation and the removal of this script are orthogonal. As far as raising alarm about the drift, this has served its purpose. Let’s get rid of it now. I’ll setup a rotation when I get to my workstation.  Thanks.

**Comment by liyuqian** [comment]
Fine. I'll remove it once I get back to my workstation tomorrow.

**Comment by liyuqian** [comment]
Will replace this with rotation. Hence closed.

**Pull request closed without merging**
