### PR TITLE
Simplify Dart application startup

### PR DESCRIPTION
**Pull request by abarth**
There are now three ways to start Dart applications:

1) From a precompiled snapshot
2) From a snapshot
3) From source

When loading from source, we no longer use the complex data pipe /
dependency catcher mechanism. Instead, we just load the source
synchronously from the file system. This is appropriate because running
from source is used only during development and not during production.

The previous design was built assuming we would want to run from source
over the network, which meant we needed to be able to load source
asynchronously over a high latency channel.

### CODE REVIEW

**Comment by abarth** [comment]
@johnmccutchan @chinmaygarde

**Comment by abarth** [comment]
Travis is mad because this patch depends on https://fuchsia-review.googlesource.com/c/6380/

**Comment by johnmccutchan** [comment]
This looks like a nice cleanup. The tonic patch has an issue that will break reload.

**Comment by abarth** [comment]
Thanks.  Will fix.

**Comment by johnmccutchan** [comment]
LGTM

**Pull request merged**
