### PR TITLE
Manual Dart roll to 0ac840ba1 and update frontend server snapshot filename

### PR DESCRIPTION
**Pull request by jason-simmons**
The Dart SDK is now only building an AOT snapshot for the frontend server (see https://dart-review.googlesource.com/c/sdk/+/359100)

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
cc @a-siva

**Review by zanderso — APPROVED** [review]

**Review by a-siva — COMMENTED** [review]
lgtm

**Comment by a-siva** [comment]
adding @derekxu16 to this PR as he was trying to land a similar PR

**Comment by zanderso** [comment]
Reason for revert: This Dart roll is blocking the roll of the engine to the framework. Unblocking the rolls depends on addressing https://github.com/flutter/flutter/issues/146164.

**Pull request merged**
