### PR TITLE
Re-apply "Log Tonic errors with FML_LOG"

### PR DESCRIPTION
**Pull request by chinmaygarde**
This reverts commit d03897011aa6a88d2c95c0b7f3f47291db8eb2da and updates the tonic SHA.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @tvolkert though I don't this this will affect any other rolls adversely.

**Comment by jason-simmons** [comment]
LGTM

(the license file will probably need to be updated again)

**Comment by chinmaygarde** [comment]
> (the license file will probably need to be updated again)

Really? Why? I did not add new files to tonic.

**Comment by chinmaygarde** [comment]
> I did not add new files to tonic.

I guess the SHA is generated from the contents.

**Pull request merged**
