### PR TITLE
Remove OpenTypeSantizer and brotli

### PR DESCRIPTION
**Pull request by abarth**
We don't need OpenTypeSantizer or brotli because we don't support loading fonts
over the network. Instead, fonts will need to be packaged inside the Flutter
asset bundle.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by Hixie** [comment]
why does it matter if it's in the bundle or over the network?

**Comment by abarth** [comment]
@Hixie OpenTypeSanitizer does two things:

- Network optimization of your font.  For example, using brotli/WOFF/WOFF2.  The way these compression functions work is that the bloat the browser's binary with a giant table of common strings from font files.  Because bloating the browser binary is "cheap" this ends up being a win.  In our case, we pay for both the size of the engine and the font, which means it's not a win to bloat the engine binary to compress the font better.  Instead, it's better to put all the fonts you need into a single FLX archive and let the ZIP compression algorithm find the common substrings just like it does normally.

- Working around security bugs in the OS.  OpenTypeSanitizer also transcodes fonts to attempt to avoid hitting corner cases in your system font decoder.  In the case of Android/iOS, our philosophy is that a Flutter app can do whatever a normal app on those platforms can do, which means we don't need to interpose between the app developer and the system font decoder.  For FNL, we'll need to secure FNL against any Mojo app interacting with the system font decoder, which means putting this transcoding in flutter.mojo is the wrong layer.

**Comment by Hixie** [comment]
LGTM.

**Pull request merged**
