### PR TITLE
[web] ScreenOrientation singleton

### PR DESCRIPTION
**Pull request by mdebbar**
One more piece moving out of `FlutterViewEmbedder`.

`ScreenOrientation` is a singleton class that can be used to control the screen orientation of the browser.

Part of https://github.com/flutter/flutter/issues/134443

### CODE REVIEW

**Review by ditman — APPROVED** [review]
LGTM! There's some extra cleanup that can be done (like making the ScreenOrientation values an enum, or the _deviceOrientationToLockType a Map<String, String>, but that's out of scope for this one!

**Comment by mdebbar** [comment]
> LGTM! There's some extra cleanup that can be done (like making the ScreenOrientation values an enum, or the _deviceOrientationToLockType a Map<String, String>, but that's out of scope for this one!

Yep, I thought about that, then decided to keep the PR simple for now.

**Comment by ditman** [comment]
Goldens? You must be drunk flutter-dashboard!

**Comment by ditman** [comment]
(@mdebbar there was a change wrt dithering a couple of weeks ago, not sure how old this branch is, but maybe it needs a rebase so the dithering algorithm doesn't cause golden changes?)

**Pull request merged**
