### PR TITLE
CP 3.3: Remove context assertion from Android platform views using Virtual Display

### PR DESCRIPTION
**Pull request by stuartmorgan**
Cherry-picks https://github.com/flutter/engine/pull/35997 to the stable branch.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/36046

**Comment by itsjustkevin** [comment]
@stuartmorgan the two tests are still failing on rerun.  I am investigating, can you take a look in parallel?

**Comment by stuartmorgan** [comment]
Neither of those tests look even remotely related to the code I changed, so I think something is wrong with the CP target branch itself.

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/36046

**Review by itsjustkevin — APPROVED** [review]

**Pull request merged**
