### PR TITLE
[WIP] introduce HostComponentAware & HostComponentPluginBinding

### PR DESCRIPTION
**Pull request by MeandNi**
introduce HostComponentAware & HostComponentPluginBinding for user can get HostComponent (Activity / Fragment) in XXXPlugin.

https://github.com/flutter/flutter/issues/117888

### CODE REVIEW

**Comment by chinmaygarde** [comment]
From Triage: Hare to tell how to direct this. Perhaps @GaryQian or @reidbaker may know. In the meantime, can you add tests and address the presubmit failures? Or is this still WIP and you are looking for early feedback?

**Comment by MeandNi** [comment]
> From Triage: Hare to tell how to direct this. Perhaps @GaryQian or @reidbaker may know. In the meantime, can you add tests and address the presubmit failures? Or is this still WIP and you are looking for early feedback?↳

yes, i will add tests.

**Comment by MeandNi** [comment]
Do you think it is appropriate to abstract Activity and Fragment into HostComponent so that users can get them in XXXPlugin. I saw this type of XXXAware before for [Android App components](https://developer.android.com/guide/components/fundamentals). cc @GaryQian @xster .

**Comment by chinmaygarde** [comment]
Closing this as stale. Please re-open once progress can be made (rebase with tests).

**Pull request closed without merging**
