### PR TITLE
Work around an Apple Clang issue where the compiler defines __ARM_FEATURE_CRC32 even though the crc32 instruction is unavailable.

### PR DESCRIPTION
**Pull request by chinmaygarde**
cc @jason-simmons @abarth

### CODE REVIEW

**Comment by chinmaygarde** [comment]
TBR as this is causing crashes on iOS. Fixes https://github.com/flutter/flutter/issues/5754.

**Comment by eseidelGoogle** [comment]
Do we have links to more information about this bug?  is there an openradar or clang bug on this?

**Comment by chinmaygarde** [comment]
@eseidel:

> Do we have links to more information about this bug? is there an openradar or clang bug on this?

Yeah, the [OpenRadar ticket is linked in the comment](https://github.com/lionheart/openradar-mirror/issues/7653) in the GN file. [Skia is also being patched](https://codereview.chromium.org/2322033002) to work around this issue.

**Comment by eseidelGoogle** [comment]
Thanks!

**Pull request merged**
