### PR TITLE
[icu] Update the ICU library to 2b50fa94b07b601293d7c1f791e853bba8ffbb84

### PR DESCRIPTION
**Pull request by filmil**
Please see the linked issue for details.

Fixes: https://github.com/flutter/flutter/issues/90146

Note, originally there was a problem with commit 3f443830bd52d3aa5fab3c1aa2b6d0848bb5039d.  Trying to fix that I discovered a slew of issues in `gn` and `//flutter/third_party`, which are now fixed and the resulting change to `flutter/engine` is below:

- Updates gn to commit 0153d369bbccc908f4da4993b1ba82728055926a to take
      in the fix at https://gn-review.googlesource.com/c/gn/+/12220 which
      prevented the correct treatment of target refactoring.
    
- Updates ICU to commit 2b50fa94b07b601293d7c1f791e853bba8ffbb84 to
      correct the target naming, which should now work thanks to the
      previous update to gn.  See
      https://gn-review.googlesource.com/c/gn/+/12220 for the details of
      that bug.
    
- Fixed the visibility declaration in `//flutter/third_party/accessibility:accessibility_config`
      which used to not be enforced due to a bug in `gn` which was fixed in
      https://gn.googlesource.com/gn/+/46b572ce4ceedfe57f4f84051bd7da624c98bf01,
      a revision which we took in by updating `gn` in the first bullet.
   
Fun times.
    

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by filmil** [comment]
The license checker does not run locally for me, and is anyways not relevant for the merge. I will wait for the presubmit checks to complete and will then amend the license file checksums to match.

**Comment by filmil** [comment]
@jason-simmons @chinmaygarde PTAL when able.

If the licenses checks drift, I'll update the commit.

**Review by jason-simmons — APPROVED** [review]

**Comment by filmil** [comment]
@jason-simmons Thank you!

**Comment by chinmaygarde** [comment]
The failures definitely look related to this patch. Can we fix the presubmits to land this please.

**Comment by filmil** [comment]
Sadly we can't close this just yet.  It turns out that a recent update to the ICU library broke compilation for (at least) Fuchsia, and it's not quite clear how.

I'll need to dig into that and revisit once the air is clear.

**Comment by filmil** [comment]
@chinmaygarde @jason-simmons Hi folks!  I had to fix more things in this pull request, would you mind taking a quick look again to make sure all is still well.

There are now 3 changes here instead of the originally planned 1, due to a 3-layer yakshave which is now described in the pull
request message.

The currently running presubmits will fail on license checks, but I won't push the correct licenses before y'all confirm this looks OK to you.

**Pull request merged**
