### PR TITLE
Bump to OpenJDK 11 (Prerequisite for Android S)

### PR DESCRIPTION
**Pull request by blasten**
Related to https://github.com/flutter/flutter/issues/86377

### CODE REVIEW

**Comment by blasten** [comment]
@CaseyHillers there is a bug somewhere. This is resolving to the java 8 instance: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8839805242579142881/+/u/OpenJDK_dependency/ensure_installed/json.output

**Comment by CaseyHillers** [comment]
See https://github.com/flutter/flutter/issues/86892#issuecomment-892353784

LUCI configs cannot be tested in a live build on presubmit. This requires landing this PR, giving it 30 minutes to apply to the LUCI config, and validating.

If it doesn't work, you'll need to revert this PR and let it roll through again (best to be done outside of work hours).

There's some more work we're doing to improving this process, but it won't be ready this quarter.

**Comment by blasten** [comment]
I was under the impression that engine.py was parsing the yaml file, and then fetching cipd packages by recursing over this list, but that isn't the case?

**Comment by CaseyHillers** [comment]
> I was under the impression that engine.py was parsing the yaml file, and then fetching cipd packages by recursing over this list, but that isn't the case?

That's more aligned with go/flutter-single-recipe-builds which is still in development. With the deps approach, you're going to need to verify this isn't adding a lot of time to the builds. `ci.yaml` hooks directly into LUCI, and supports caching to speed up the builds. I'm not sure that can be supported from the deps.

**Comment by blasten** [comment]
I think in both cases it will download the artifacts from cipd. Is there an additional caching layer that is faster than a fetch from cipd?

**Comment by CaseyHillers** [comment]
Yes, when fetched through the LUCI recipe, there's an existing caching system it hooks in. Explicitly running a cipd fetch in the DEPS does not guarantee it to persist on the bot.

**Comment by blasten** [comment]
https://github.com/flutter/engine/pull/27942 continues this work.

**Pull request closed without merging**
