### PR TITLE
Revert "android platform channels: moved to direct buffers for c <-> java interop"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#26331

Errors on the framework tree

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20channels_integration_test_win/425/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20channels_integration_test/1340/overview

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by jason-simmons** [comment]
If we want to fix forward, this probably just needs a null check on https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/BinaryCodec.java#L57

**Comment by zanderso** [comment]
Let's go by the book and do the revert. The NPE is potentially just the first issue that the framework tree tests hit.

**Comment by zanderso** [comment]
Landing revert over resolved infra failures.

**Comment by gaaclarke** [comment]
Thanks, yea missing null check.  If only we had null safety in java.  I'll reland with a fix/test.

**Pull request merged**
