### PR TITLE
Reland Display Features support (Foldable and Cutout)

### PR DESCRIPTION
**Pull request by andreidiaconu**
* Relands https://github.com/flutter/engine/pull/24756
* Reverts https://github.com/flutter/engine/pull/28447
* Updates WindowManager android library from beta01 to beta03 (publishing a new version of the android dependencies bundle is needed)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by andreidiaconu** [comment]
@blasten Could you please update the `android_embedding_bundle` in cipd? I updated from 1.0.0-beta01 to 1.0.0-beta03, since the bundle created for https://github.com/flutter/engine/pull/24756 was too old anyway.

**Comment by blasten** [comment]
Is it ready to land if all checks are green?

**Comment by andreidiaconu** [comment]
Yes, although gradle lockfiles might need to be updated, and there are also a few gradle files still using 30, both of which should be fixed by https://github.com/flutter/flutter/pull/89511 - I am ready to update it once this gets merged.

**Comment by zanderso** [comment]
@blasten Is there logic that could be added to the autoroller script to update the lockfiles?

**Comment by blasten** [comment]
potentially. does the autoroller script run in a LUCI bot, or some environment that can run Dart code?

**Review by blasten — APPROVED** [review]
LGTM

**Pull request merged**
