### PR TITLE
Reland "[Android Text Input] Remove Samsung restart input workaround for newer Samsung keyboards" #24288

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Reland #24288, reverted in https://github.com/flutter/engine/pull/24486

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
hi @blasten I'd like to verify the PR works on SDK27 and below, for that I need "org.robolectric:android-all:8.0.0_r4-robolectric-r1". Should I proceed to the CIPD step to add the jar to `android_embedding_dependencies`?

**Comment by chinmaygarde** [comment]
Ping @blasten. Can you answer @LongCatIsLooong's please? Looks like this PR is stalled in the meantime.

**Comment by chinmaygarde** [comment]
@LongCatIsLooong: @blasten is on leave for a bit so I don't think we'll be able to get an answer just yet. I think adding the jar to `android_embedding_dependencies` via a CIPD step is fine though. Let's do that if it unblocks you.

**Comment by chinmaygarde** [comment]
@LongCatIsLooong Any progress? If you are blocked on this, what can I do to get this unstuck? If you are working on other things, lets close this in the meantime and reopen when it is ready for review.

**Comment by LongCatIsLooong** [comment]
@chinmaygarde sorry I'm not blocked on this. I'll start

**Comment by LongCatIsLooong** [comment]
This is no longer needed.

**Pull request closed without merging**
