### PR TITLE
Fix AccessibilityBridge crash due to invalid access during ReplaceSemanticsObject

### PR DESCRIPTION
**Pull request by fbcouch**
https://github.com/flutter/flutter/issues/98138

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
I think the tests are failing because you're branched off a pretty old commit, 65dfc9e3bf.  Can you rebase onto top of tree main?

**Comment by fbcouch** [comment]
All right, that is updated. Hopefully the build goes better this time...

**Comment by stuartmorgan** [comment]
Capturing from the Discord discussion that led to this PR: `[objects removeObjectForKey:nodeId];` is removing `oldObject` from its container/owner, which could easily be the last reference to it, and thus cause it to be deallocated. This is applying the (pre-ARC) standard approach of retain+autorelease before removing an object that will continue to be used from the collection that it is coming from.

I don't think there's really a way to test this, because using a deallocated object is undefined behavior; it may crash, but it may not, and the window here for the memory to be stomped to cause a crash is pretty small.

**Comment by Hixie** [comment]
test-exempt: untestable

**Review by jmagman — APPROVED** [review]
Wonder why this wasn't caught with the clang analyzer...
LGTM

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
