### PR TITLE
Log known thread names to the timeline.

### PR DESCRIPTION
**Pull request by chinmaygarde**
@johnmccutchan: From looking at the test cases, I believe the following should be enough to log known thread names to the Dart timeline. However, no metadata events show up in the output trace. I tried debugging the API implementation and the event is successfully marked as completed. But when I stop tracing, the JSON file does not contain the same. Instead, it contains the Dart runtimes' notion of the thread name,

```
   {
      "name": "thread_name",
      "ph": "M",
      "pid": 23978,
      "tid": 7943,
      "args": {
        "name": "Dart_Initialize (7943)"
      }
    },
```

I tried adding different names to see if they show up in the JSON file, they don't.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Also, I am pretty sure I dont have to timestamp metadata events. But the test case did so I added it here. I can get rid of the same.

**Comment by johnmccutchan** [comment]
@chinmaygarde I need to refactor how you report meta-data events. Question- would providing a mapping of thread id to thread name be sufficient?

**Comment by chinmaygarde** [comment]
@johnmccutchan: That can work. Though it is probably not as flexible as the current API. But we dont send any other metadata right now either.

**Comment by chinmaygarde** [comment]
Closing. This for now.

**Pull request closed without merging**
