### PR TITLE
Revert "Display Features support (Foldable and Cutout)"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#24756

Failures when rolling into flutter/flutter: https://github.com/flutter/flutter/pull/89430

### CODE REVIEW

**Comment by zanderso** [comment]
Landing revert eagerly to unblock rolls.

**Comment by andreidiaconu** [comment]
@zanderso I saw the failures and am currently working on separate framework branch to get those fixed. This adds new gradle dependencies and they need to be reflected in the dependency lockfiles. Other things might need to change but for now the gradle dependecy lock files are my focus.

Once I have a working branch, what happens next?

**Comment by zanderso** [comment]
Maybe @blasten can advise here, but my non-expert suggestion would be to try to land the compensating changes in the framework first before re-landing the breaking changes in the engine.

**Comment by blasten** [comment]
@andreidiaconu sorry for the question again, would it be possible to repackage this PR as a plugin?  For example, a plugin could extend `FlutterView`, so the app chooses the FlutterView implementation from the Activity.  Could something like this help?

**Comment by blasten** [comment]
Also, is there a doc or thread about any previous discussion that concluded with the current approach?

**Comment by andreidiaconu** [comment]
There is an initial internal doc which we used to establish how to proceed. The main reason why a plugin would not work is that dialogs, popup menus and other parts of the framework also benefit from knowing where display features are located.

**Comment by blasten** [comment]
Thanks. If you have the framework PR ready, try to patch the engine hash to test the framework PR. Then, get LGTM for the framework PR.

Once all of the checks are passing in the framework, submit the reland in the engine and cc'me. I'll make sure the engine roll patches your framework changes as well.

**Comment by andreidiaconu** [comment]
This is the Framework PR https://github.com/flutter/flutter/pull/89511 but it still has 2 issues I need advice with (the camera issue I can solve on the camera repo, but the other issue related to AGP version 3.3.0 is harder for me to figure out)

**Pull request merged**
