### PR TITLE
Show clearer logs during startup if OpenGL is unavailable

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
I suppose all of the logs could be `FTL_LOG(ERROR)`s instead of the different levels. Otherwise LGTM.

**Comment by jason-simmons** [comment]
Done

**Comment by eseidelGoogle** [comment]
My understanding from https://github.com/flutter/flutter/issues/6135 is that the plan is to add a software backend for the iOS simulator, presumably we could also use one for Android emulators when OpenGL is not available.

**Pull request merged**
