### PR TITLE
[iOS] Fix FlutterViewController retain cycle

### PR DESCRIPTION
**Pull request by LinXunFeng**
Fixes [flutter/flutter#126560](https://github.com/flutter/flutter/issues/126560)

### CODE REVIEW

**Comment by hyiso** [comment]
LGTM

**Review by luckysmg — APPROVED** [review]
LGTM

**Review by cyanglaz — APPROVED** [review]
LGTM

**Comment by MilesYuanCN** [comment]
LGTM

**Comment by zhaoxianxin** [comment]
3.10.6 not fixed?

**Pull request merged**
