### PR TITLE
Expose EngineLayer.uniqueId and Picture ID

### PR DESCRIPTION
**Pull request by moffatman**
Add a way to get the "unique ID" of a layer from dart code.

Also return the unique ID of the inserted `DisplayListLayer` when adding a `Picture` to the scene.

1/2 towards fixing https://github.com/flutter/flutter/issues/125019

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by moffatman** [comment]
Based on test failures it may be more complex than I expected to also apply to the web engine...

**Comment by flar** [comment]
There is also a unique ID associated with DisplayList objects - mainly used in the RasterCache of pictures - that might be of interest as well. I'm not sure if that shows up in the Dev Tools, though. But, DisplayListLayers are not cached by layer - they are cached by the DisplayList uniqueID.

**Comment by moffatman** [comment]
For RasterCache of pictures, I changed `int SceneBuilder::addPicture`. It seemed to work as I expected, but in your comment above sounds like it's maybe not the right value to return?

**Comment by flar** [comment]
> For RasterCache of pictures, I changed `int SceneBuilder::addPicture`. It seemed to work as I expected, but in your comment above sounds like it's maybe not the right value to return?

What did you change in addPicture? It looks like it is returning the ID of the layer.

**Comment by flar** [comment]
At the native level unique IDs are uint64_t. As I recall Dart's int type is infinite precision? Do the right conversions happen for large uint64_t values?

**Comment by moffatman** [comment]
I used Int32 for FFI without much thought... if that works how I expect (always get the low 32 bits), it should solve it, right? I don't think we need precision to track more than 4 billion layers at once 😁.

**Comment by flar** [comment]
> I used Int32 for FFI without much thought... if that works how I expect (always get the low 32 bits), it should solve it, right? I don't think we need precision to track more than 4 billion layers at once 😁.

It's not 4 billion at once, it's 4 billion over the lifetime of the app, but your point stands.

**Comment by moffatman** [comment]
What I meant is, if we cast to Int32, you will be able to tell apart 4 billion simultaneous layers (since my use case here is just to compare the tables between the devtools page and layer tree. I didn't think about a use case where you had to track all the layers over time.

**Comment by dnfield** [comment]
We should do this over a service protocol from the engine.

**Review by dnfield — CHANGES_REQUESTED** [review]
I'm not entirely clear on how this will be used in devtools, but we don't need new dart:ui API for it.

You can expose these IDs and information about the objects via the service protocol directly from the engine. See e.g. `Shell::OnServiceProtocolGetDisplayRefreshRate` for a different example of how we do this.

We should not add public application-facing API for a developer tooling/performance tooling thing.

**Comment by chinmaygarde** [comment]
Closing this per @dnfield recommendation.

**Pull request closed without merging**
