### PR TITLE
Enable/tweak web sdk source maps, take 2

### PR DESCRIPTION
**Pull request by vsmenon**
This is a redo of my earlier reverted request.  I still need to test on windows, but the GN logic is closer to what's in the Dart SDK (which does work on windows).

The traces are also a little nicer than before.  Still need to serve up the actual SDK sources to enable stepping.

```
When the exception was thrown, this was the stack:                      
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49  throw_
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 284:5             [_findOrCreateCanvas]
package:build_web_compilers/lib/_engine/engine/surface/picture.dart 257:21            paintCallback
package:build_web_compilers/lib/_engine/engine/surface/surface.dart 71:14             commitScene
package:build_web_compilers/lib/ui/src/ui/compositing.dart 575:5                      build
package:flutter/src/rendering/layer.dart 727:35                                       buildScene
package:flutter/src/rendering/view.dart 227:36                                        compositeFrame
package:flutter/src/rendering/binding.dart 347:16                                     drawFrame
package:flutter/src/widgets/binding.dart 778:13                                       drawFrame
package:flutter/src/rendering/binding.dart 283:5                                      [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1043:15                                    [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 982:9                                      handleDrawFrame
package:flutter/src/scheduler/binding.dart 791:7                                      <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 46:17       internalCallback
```

### CODE REVIEW

**Comment by vsmenon** [comment]
@jonahwilliams - is there any automated way of testing this on win?

fyi - @ferhatb @yjbanov @jakemac53 @sigmundch

**Comment by jonahwilliams** [comment]
We should be able to enable a windows presubmit test. I can follow up with the engine team tomorrow about turning it on

**Comment by vsmenon** [comment]
@jonahwilliams - re the failure above, I can't seem to locally repro, but I think we need a BUILD dep on the action that copies from `third_party/dart` to `dart-sdk`.  Do you know what the right dep is?

This is the break:

https://cirrus-ci.com/task/5379482453540864?command=compile_host#L1026

**Comment by jonahwilliams** [comment]
I think that rule would be https://github.com/flutter/engine/blob/master/BUILD.gn#L49 

But IIRC, most (all?) of the dartdevc patch files don't end up in the final sdk, they stay in the source tree so I don't think that will work.

**Comment by vsmenon** [comment]
> I think that rule would be https://github.com/flutter/engine/blob/master/BUILD.gn#L49

Thanks!

> But IIRC, most (all?) of the dartdevc patch files don't end up in the final sdk, they stay in the source tree so I don't think that will work.

That was probably the case when this was first wired up.  The patch files moved to the SDK dir a couple months back.

**Comment by vsmenon** [comment]
@jonahwilliams - the dep was sufficient, ptal.

**Comment by yjbanov** [comment]
This change makes a **_huge_** difference to my debugging experience. I just patched in this PR and fixed a bug in 5 minutes that I didn't know where to even begin fixing. Thank you!

**Comment by jonahwilliams** [comment]
Well, that change isn't working so LGTM I guess :)

**Comment by jonahwilliams** [comment]
We're waiting until @ferhatb has a chance to get this running tonight. Will update the PR with progress tomorrow, or find an alternative way to test

**Comment by vsmenon** [comment]
Note, I added one further change to `BUILD.gn` to match the corresponding Dart SDK change here:

https://dart-review.googlesource.com/c/sdk/+/122178/5/utils/dartdevc/BUILD.gn

@nshahan or @sigmundch - do one of you mind sanity checking?

**Comment by jonahwilliams** [comment]
And landed...

**Pull request merged**
