### PR TITLE
Call AwaitVSync directly when Animator.RequestFrame is calling

### PR DESCRIPTION
**Pull request by ColdPaleLight**
fixes https://github.com/flutter/flutter/issues/92258

Currently this new feature is only support on Android and iOS，I have tried to enable this feature on all platforms, but the unit test AnimatorDoesNotNotifyIdleBeforeRender will fail due to timeout.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by dnfield** [comment]
Do you have any results from running this on any of the devicelab tests? You can run those with a locally built engine in the framework tree by doing `dart bin/run.dart -t flutter_gallery__transitions_perf --local-engine=android_profile_arm64` for example.

**Comment by chinmaygarde** [comment]
From our call in person on December 09, we were seeking a benchmark you could share with us so we ensure we don't regress here.

**Comment by chinmaygarde** [comment]
Gentle ping on the benchmark.

**Comment by ColdPaleLight** [comment]
@chinmaygarde 
Since I couldn't provide a suitable benchmark to prove this optimization, I decided to close this PR. I will reopen if I find a suitable benchmark in the future.

**Comment by fzyzcjy** [comment]
Hi, did you have further experiments on this? Related: #36911

**Comment by ColdPaleLight** [comment]
> Hi, did you have further experiments on this? Related: #36911

Sorry, I don't have a benchmark to support it.

**Comment by fzyzcjy** [comment]
@ColdPaleLight Thank you all the same

**Pull request closed without merging**
