### PR TITLE
changed version for testing

### PR DESCRIPTION
**Pull request by gaaclarke**
this is for testing the release process

issue: https://github.com/flutter/flutter/issues/146078

cc @matanlurey 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by XilaiZhang — APPROVED** [review]

**Comment by gaaclarke** [comment]
At this point we would have expected golden file differences.  It doesn't seem to have them.

**Comment by gaaclarke** [comment]
The golden tests were executed:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/812604/overview

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8751098318437749073/+/u/test:_Impeller-golden__dart_and_engine_tests_for_host_release/stdout

There has been a lot of errors printed out in the form of:
```
NOTE: Untriaged image detected in tryjob.
Triage should be required by the "Flutter Gold" check
stdout:
Given image with hash e33c95286930c77153d7ebd6206582d6 for test impeller_Play_AiksTest_VerticesGeometryUVPositionData_Metal_Release_0_1
Fetching most recent positive digest for trace with ID "785125775a7ddd489b1de99c653e5dda".
No recent positive digests for trace with ID "785125775a7ddd489b1de99c653e5dda". This probably means that the test was newly added.
Non-exact image comparison using algorithm "fuzzy" against most recent positive digest "".
Untriaged or negative image: https://flutter-engine-gold.skia.org/detail?grouping=name%3Dimpeller_Play_AiksTest_VerticesGeometryUVPositionData_Metal_Release_0_1%26source_type%3Dflutter-engine&digest=e33c95286930c77153d7ebd6206582d6&changelist_id=52005&crs=github

```

**Comment by gaaclarke** [comment]
Here is a link to all the diffs.  I'm not sure if we can manually go into there an approve them.  We had problems with that in the past when the bot didn't pick them up and then we went into skia gold manually and accepted them: https://flutter-engine-gold.skia.org/search?issue=52005&crs=github&patchsets=3&corpus=flutter-engine

**Comment by gaaclarke** [comment]
This looks to be why skia gold never reported a diff: https://github.com/flutter/cocoon/blob/9dd49cd93309b4d737d244e34d699f448e6ef17b/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L86

**Comment by XilaiZhang** [comment]
To temporarily unblock, we could maybe hard code the branch name, i.e. change the if check from `(pr.base!.ref != defaultBranch)` to `if (pr.base!.ref != defaultBranch && pr.base.ref != flutter-test-golden-1`, like Aaron pointed out.

For a more comprehensive fix Keyong would definitely know more

**Comment by gaaclarke** [comment]
> This looks to be why skia gold never reported a diff: https://github.com/flutter/cocoon/blob/9dd49cd93309b4d737d244e34d699f448e6ef17b/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L86

@keyonghan do you have a recommendation on how best to support release branches at this point in cocoon?  Right now it gets skipped if it isn't destined to the `main` branch.

**Comment by keyonghan** [comment]
> > This looks to be why skia gold never reported a diff: https://github.com/flutter/cocoon/blob/9dd49cd93309b4d737d244e34d699f448e6ef17b/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L86
> 
> @keyonghan do you have a recommendation on how best to support release branches at this point in cocoon? Right now it gets skipped if it isn't destined to the `main` branch.

I guess you are expecting the `flutter-gold` check status from this PR? If yes, then the temporary workaround mentioned above SGTM. I don't see a generic way to support this without affecting the real release branch workflow.

**Comment by gaaclarke** [comment]
The goal is to affect the real release branch workflow.  The purpose of this is to just see what works and what doesn't.  I'll try to come up with a proposal next week, looks like we're going to have to change the cocoon logic.

**Comment by gaaclarke** [comment]
I filed a PR to update cocoon to allow skia gold to run on release branches: https://github.com/flutter/cocoon/pull/3659

Once that lands we'll have to rerun our test with a branch that matches the release naming structure: `flutter-\d?\.\d?-candidate\.\d?`

**Comment by gaaclarke** [comment]
Yay, it works.  The bot is running and all the names of results have the version number in them.

**Pull request closed without merging**
