### PR TITLE
Add average fps info in PerformanceOverlayLayer.

### PR DESCRIPTION
**Pull request by eggfly**
Implements:
* https://github.com/flutter/flutter/issues/96916

Screenshot_2022-01-25-13-56-06-463_com example flutter_performance_layer

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by eggfly** [comment]
> flutter-dashboard

Already modified the golden test files.

**Comment by eggfly** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

flutter-dashboard

**Review by dnfield — COMMENTED** [review]
What period is the average for? How will a user know that?

**Comment by eggfly** [comment]
> What period is the average for? How will a user know that?

Good idea! I added the info like: "%d FPS ( %frames in %d ms)", average duration is 1000.0 ms at most, duration is less than 1000.0 ms at app startup. And I make it two lines with measured left, top, height positions and modified the unittests (because on macOS/Linux platforms, the measured size and positions are different). It's more pretty now.

**Comment by dnfield** [comment]
@jacob314 @kenzieschmoll WDYT?

**Comment by kenzieschmoll** [comment]
Is 1 second enough time for a max in the avg calculation? @dnfield @goderbauer in your recent efforts to reduce UI jank in large apps, would showing the avg fps for the previous 1 sec be useful, or would you like to see an avg fps over a longer duration?

**Comment by dnfield** [comment]
I'm sensing that this is information that's just better surfaced in devtools via the frame timings API, where users can have some toggles and switches (and more room) to get a sense of this. The overlay can be fairly small on some phones, and a 1s period won't be so great if you're in a set of bad frames.

**Comment by eggfly** [comment]
> I'm sensing that this is information that's just better surfaced in devtools via the frame timings API, where users can have some toggles and switches (and more room) to get a sense of this. The overlay can be fairly small on some phones, and a 1s period won't be so great if you're in a set of bad frames.

I have an idea, how about average all the frames recorded by the array ( it stores 120 frames within or without janks) calculate this fps and also displays the total time total count and the janked count? @jacob314 @kenzieschmoll @dnfield

**Comment by eggfly** [comment]
The latest code displays up to 120 frames' FPS and janky/total frames, total time like this image below:

Screenshot_2022-01-25-13-56-06-463_com example flutter_performance_layer


Please have a review~ Thank u! cc @kenzieschmoll @dnfield 😄

**Review by dnfield — CHANGES_REQUESTED** [review]
I don't think we should land this change.

This seems to be cramming too much information into a relatively small area, and it will be difficult/complicated to allow developers to understand what that information is actually conveying or to alter it (i.e. using larger or smaller periods for averages).

This would be better done in DevTools, which already has all the required information and can provide a better UI for viewing average/median/whatever FPS over various durations and making it much clearer what algorithm is actually being used to calculate it. It will also avoid doing more work on the device to calculate these things, which takes away from frame workload time, particularly on lower end devices.

**Comment by goderbauer** [comment]
I would agree with @dnfield here. This seems like too much information without enough context. Probably better suited for devtools where we can give more context (and maybe configurability) on what these numbers mean.

**Comment by eggfly** [comment]
OK, I know it. Let's follow the "Keep It Simple and Stupid" principle.

**Pull request closed without merging**
