### PR TITLE
[Impeller] add missing barrier to compute tessellator.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes the flake on ToT

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757792078669575121/+/u/test:_Host_Tests_for_host_debug_unopt/stdout

### CODE REVIEW

**Review by gaaclarke — COMMENTED** [review]
LGTM, I take it there is a test for it and it's just flakey.  So the proof that this works will be in it not being flakey.  Can you reliably reproduce this flake with gtest_repeat to know that this fixes it?

**Comment by jonahwilliams** [comment]
I haven't tried yet but I obviously should. Will do while this is building.

**Comment by jonahwilliams** [comment]
I ran this 100 times locally with / without the patch and confirmed this fixes the flake for me.

**Review by gaaclarke — APPROVED** [review]
LGTM, has existing test.  thanks!

**Comment by jonahwilliams** [comment]
Landing on red to fix tree.

**Pull request merged**
