### PR TITLE
Add asset bundle support on Fuchsia

### PR DESCRIPTION
**Pull request by abarth**
After this patch, Flutter apps on Fuchsia can access their asset
bundles. Unlike other platforms, the asset bundles are stored in memory
rather than in the file system.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by abarth** [comment]
friendly ping in case you missed this last night :)

**Comment by chinmaygarde** [comment]
lgtm. Sorry I missed it.

**Comment by abarth** [comment]
Thanks!

**Pull request merged**
