### PR TITLE
Reland "[Impeller] Fail if software backend is chosen and Impeller is enabled on iOS."

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/engine#46217

cl/568091248 makes this safe to land again.

fyi @jonahwilliams @chinmaygarde

### CODE REVIEW

**Comment by dnfield** [comment]
Is that cl/567703381?

**Review by chinmaygarde — APPROVED** [review]

**Comment by dnfield** [comment]
I think this is waiting for cl/567703381

**Comment by dnfield** [comment]
I believe the ask was for @jiahaog to take al ook at the ios_test related build rules to make sure this wouldn't be too disruptive.

Something will need to be done here, because internal authors want to run tests that initialize a FlutterViewController even if they don't render anything, but this change will make that fail if it's not possible to get a MTLDevice

**Comment by chinmaygarde** [comment]
> because internal authors want to run tests that initialize a FlutterViewController even if they don't render anything

I don't think we should support this broken configuration. Can they mock it instead?

**Comment by zanderso** [comment]
From PR review triage: This is waiting on b/301315893 (maybe among others? cc @jiahaog)

**Comment by jiahaog** [comment]
Yes, I've sent out changes to all affected clients and we're pending reviews from them.

**Review by jiahaog — APPROVED** [review]
Those clients should no longer be using a "real" Flutter Engine in the unsupported test configuration. We should be able to land this now.

**Comment by zanderso** [comment]
This PR likely needs a rebase before landing.

**Comment by dnfield** [comment]
@jiahaog is this ok to land now?

**Comment by zanderso** [comment]
@dnfield The mac_unopt tests appear to have failures that might be related to this PR: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/510350/overview

**Comment by jiahaog** [comment]
@dnfield yes, have already migrated the breaking clients away.

**Comment by dnfield** [comment]
Many tests were providing a `nil` gpu sync switch, which was now crashing after https://github.com/flutter/engine/pull/46840. Updated the tests to provide a valid sync switch pointer.

**Pull request merged**
