### PR TITLE
[Impeller] implemented golden image tests for opengles

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/142354

This sets up impeller_golden_tests to run with ANGLE.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
This fails now currently when shaders are attempted to be compiled because they are being compiled for OpenGL, not opengles.  They have `#version 120` in them, not `#version 100`.

**Comment by gaaclarke** [comment]
> This fails now currently when shaders are attempted to be compiled because they are being compiled for OpenGL, not opengles. They have `#version 120` in them, not `#version 100`.

Fixed with impellerc flags.

**Comment by gaaclarke** [comment]
@jonahwilliams I added the flip in on the CPU side that respects `Texture::GetYCoordScale`.  Thanks for pointing that out.  I briefly looked into doing the flip on the GPU but it was more involved.  We can do that later.

**Comment by jonahwilliams** [comment]
Thanks! it looks like there is a remaining color format issue BGRA vs RGBA?

**Comment by gaaclarke** [comment]
> Thanks! it looks like there is a remaining color format issue BGRA vs RGBA?

Yep, looks like it.  Is there something in Texture I can used to decide that?  Maybe the `TextureDescriptor`?

**Comment by gaaclarke** [comment]
The conventional wisdom has been that BGRA is faster on some hardware.  We should look to make sure we are taking advantage of that in our renderers.

**Comment by gaaclarke** [comment]
> > Thanks! it looks like there is a remaining color format issue BGRA vs RGBA?
> 
> Yep, looks like it. Is there something in Texture I can used to decide that? Maybe the `TextureDescriptor`?

Yep, the texture descriptor `format` has the info we want.

> The conventional wisdom has been that BGRA is faster on some hardware. We should look to make sure we are taking advantage of that in our renderers.

OpenGLES is the one using RGBA, we should fix that.

**Comment by gaaclarke** [comment]
> Thanks! it looks like there is a remaining color format issue BGRA vs RGBA?

Done.

**Comment by gaaclarke** [comment]
> The conventional wisdom has been that BGRA is faster on some hardware. We should look to make sure we are taking advantage of that in our renderers.

I've looked into this a bit.  For Android RGBA may be better.  It's not clear there is a need to change this considering who is using OpenGLES.

**Review by jonahwilliams — APPROVED** [review]
LGTM

It looks like there are a number of goldens on page 3-4 that aren't showing up at all, you should file a tracking issue to investigate if that is specific to the golden harness.

**Comment by jonahwilliams** [comment]
SGTM

**Pull request merged**
