### PR TITLE
Engine 1.20.2 cherrypicks

### PR DESCRIPTION
**Pull request by pcsosinski**
- iOS platform view cancels gesture while a new clip layer is added during the gesture. · Issue #46167 · flutter/flutter
    - 02d71d60effa31131d7b135eac7a7930cbc9e95c
  - Dart 2.9.1
    - https://github.com/dart-lang/sdk/commit/e940ff7819053ed8a4c04a4dfcda7df12e969331

### CODE REVIEW

**Comment by pcsosinski** [comment]
format_and_dart_test failure is expected on 1.20 (still)

**Comment by cyanglaz** [comment]
The Mac iOS engine screenshot test failure looks suspicious. I'm going to give it a try locally.

**Comment by pcsosinski** [comment]
@cyanglaz any update?

**Comment by cyanglaz** [comment]
The image comparison logic failed in this PR because https://github.com/flutter/engine/commit/91f80efd397089607197877125cac3607d67e083 is not in 1.20, which fixes the image diff logic in the scenario app. 
@pcsosinski 
To land this cp with passing CI we will need to include https://github.com/flutter/engine/commit/91f80efd397089607197877125cac3607d67e083

**Pull request merged**
