### PR TITLE
[web] Adds Noto Music fallback font

### PR DESCRIPTION
**Pull request by CoderDake**
Adds `Noto Music` font as a fallback font, and updates DEPS and font definitions after running the font roller script.

### Issues

Fixes: https://github.com/flutter/devtools/issues/6149

----

I used [the developer API](https://developers.google.com/fonts/docs/developer_api?apix_params=%7B%22family%22%3A%5B%22Noto%20Music%22%5D%7D) to make sure the api works with this font.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ditman** [comment]
This should be good to go, PTAL web team!

**Review by harryterkelsen — APPROVED** [review]
LGTM

**Comment by ditman** [comment]
`info - test/ui/fallback_fonts_golden_test.dart:172:18 - The local variable '_checkDownloadedFamiliesForString' starts with an underscore. Try renaming the variable to not start with an underscore. - no_leading_underscores_for_local_identifiers`

Khaaaaannnn!

**Review by mdebbar — APPROVED** [review]

**Comment by CoderDake** [comment]
Fixes https://github.com/flutter/devtools/issues/6149

**Pull request merged**
