### PR TITLE
Reland 3: Display Features support

### PR DESCRIPTION
**Pull request by andreidiaconu**
This reverts commit df686d2638b35ce6ea771586b374fae800d0624c.

List which issues are fixed by this PR:
- https://github.com/flutter/flutter/issues/49411
- Initial PR: https://github.com/flutter/engine/pull/24756

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by andreidiaconu** [comment]
@blasten As per request from https://github.com/flutter/flutter/pull/93204, we should wait until Engine backlog is cleared. @zanderso Could you please let us know when it's ok to try to reland this? Leaving this in Draft until then.

**Comment by andreidiaconu** [comment]
@blasten I think we are ready to reland this (with https://github.com/flutter/flutter/pull/93240)

**Review by blasten — APPROVED** [review]
lgtm

**Comment by blasten** [comment]
We need to wait until https://github.com/flutter/plugins/pull/4502 lands before landing this change since it breaks the plugins repo.

**Pull request merged**
