### PR TITLE
[nnbd] un-fork sky engine

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Copy the nnbd SDK so that the analyzer works and can migrate

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Not sure If I understand the errors here:

```
Analyzing 3 directories...                                      

  error • Missing concrete implementations of 'getter IOSink.Encoding' and 'setter IOSink.Encoding' • packages/flutter_test/lib/src/_binding_io.dart:208:7 • non_abstract_class_inherits_abstract_member
  error • '_MockHttpRequest.encoding=' ('void Function(Encoding)') isn't a valid override of 'IOSink.encoding=' ('void Function(dynamic)') • packages/flutter_test/lib/src/_binding_io.dart:210:12 • invalid_override
  error • '_MockHttpHeaders.add' ('void Function(String, Object, {bool preserveHeaderCase})') isn't a valid override of 'HttpHeaders.add' ('void Function(String, Object, {dynamic preserveHeaderCase})') • packages/flutter_test/lib/src/_binding_io.dart:518:8 • invalid_override
  error • '_MockHttpHeaders.set' ('void Function(String, Object, {bool preserveHeaderCase})') isn't a valid override of 'HttpHeaders.set' ('void Function(String, Object, {dynamic preserveHeaderCase})') • packages/flutter_test/lib/src/_binding_io.dart:536:8 • invalid_override

4 issues found. (ran in 149.0s)
������������������������
```

will take a look at _binding_io.dart

**Comment by scheglov** [comment]
It looks that Dart SDK is analyzed without NNBD enabled.

**Comment by jonahwilliams** [comment]
Do we need to start passing --enable-experiment to flutter analyze? I wouldn't think so right?

**Comment by jonahwilliams** [comment]
Ahh, saw your edit - sounds like there needs to be a fix in the Dart SDK first then?

**Comment by scheglov** [comment]
No, you should not enable any experiments on the command line.
SDK should be supported automatically.
Well, when all the supporting machinery is there.

**Comment by jonahwilliams** [comment]
SG, I'll take care of that now

**Comment by jonahwilliams** [comment]
experiments added

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/150169 will add support to analyzer.

**Comment by scheglov** [comment]
The analyzer CL landed.
https://github.com/dart-lang/sdk/commit/a12fd560b7341fc55ee71ab3d25d583f554fe771

**Comment by jonahwilliams** [comment]
Waiting for https://github.com/flutter/engine/pull/18843 to be merged

**Comment by jonahwilliams** [comment]
@scheglov I'm still getting the same errors with the allowed_experiments.json present in sky_engine

**Comment by MichaelRFairhurst** [comment]
@jonahwilliams How can I reproduce this locally to debug?

**Comment by jonahwilliams** [comment]
The actual command to be run is `bin/flutter analyze --dartdocs --flutter-repo --local-engine=host_debug_unopt`

However, that requires a checkout of the flutter/engine and build of the flutter engine host_debug_unopt variant. The setup instructions are here: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment (you don't need most of the dependencies to only build host.)

The specific gn command is `flutter/tools/gn --unopt` then `ninja -C out/host_debug_unopt`

**Comment by jonahwilliams** [comment]
I have this setup locally so if there is anything I could check/run to make debugging this easier I'm happy to help out

**Comment by scheglov** [comment]
I tried it locally.
I replaced SDK libraries in `sky_engine` with un-forked libraries from Dart SDK.
I used just `analyzer`, not `flutter analyze` that runs Analysis Server.

Without `_internal/allowed_experiments.json` I get the same errors.
With this file, no errors.

My current theory is that it might be because of persistent caching that Analysis Server does.
So, once summaries of SDK libraries were built, DAS continues reusing them.
This is probably my mistake, I should have incremented the `DATA_VERSION` in analyzer in the same CL as the one that updated `EmbedderSdk.`

Of course if it is not because of such persistent cache, then there might be something else.

**Comment by jonahwilliams** [comment]
Do we risk triggering analysis errors in user projects if we land this as is without changing DATA_VERSION ? Or do we need to clear out the caches on CI (I didn't think this was caching anything)

**Comment by MichaelRFairhurst** [comment]
@jonahwilliams Konstantin would know better than me, but I'm going to say "yes," this could cause analysis errors in users projects.

Analyzing the core sdk sources as if NNBD is not enabled when those sources in fact are written for NNBD opens up all kinds of potential discrepancies between what the SDK is supposed to define and what it actually does define. In this case, for instance, it looks like the dart analyzer things that "late" is the type of "encoding," and doesn't find "late," so it infers "dynamic" instead. This is just one example of how the SDK can be misinterpreted in unexpected ways. Those issues could then cause incorrect analysis errors for users.

It also won't unblock the migration tool until the whole thing works.

**Comment by scheglov** [comment]
Actually, we include the language feature set into the keys that we use for caching. So, once you have `_internal/allowed_experiments.json` in SDK, this changes keys for both unlinked and linked summaries for SDK libraries.

I tried locally again.
I ran `flutter upgrade`, then replaced libraries in `sky_engine`.
I ran `bin/flutter analyze --dartdocs --flutter-repo --local-engine=host_debug_unopt` without `_internal/allowed_experiments.json` - got errors; and with it - no errors.

I'm not sure how this is different from what this PR does.

**Comment by jonahwilliams** [comment]
Looks like flutter analyze isn't using the right snapshot/paths for local-engine:


Fix is here:  https://github.com/jonahwilliams/flutter/pull/new/unbreak_analysis_test

**Comment by jonahwilliams** [comment]
Okay, well - looks like all it took was that engine roll hitting flutter, we're good to go!

**Pull request merged**
