### PR TITLE
do not print in _computePixelDensity

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Remove debug print statements in `_computePixelDensity`.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by nturgut — APPROVED** [review]
LGTM. Is there any other print statements we should consider removing?

**Review by ferhatb — APPROVED** [review]

**Comment by yjbanov** [comment]
@nturgut 

> LGTM. Is there any other print statements we should consider removing?

I searched the code and didn't find anything too suspicious. There are a couple places that could be implemented a little more idiomatically, but that's a separate issue.

**Comment by yjbanov** [comment]
Merging on red to unblock the engine roll.

**Pull request merged**
