### PR TITLE
Add comments to include command to run libtxt unittests

### PR DESCRIPTION
**Pull request by GaryQian**
Have been asked this multiple times, going to include this in the comments!

### CODE REVIEW

**Comment by chinmaygarde** [comment]
We now have a fixtures mechanism. The test can specify assets to be made available at a known runtime path. Lets try to use the same and get rid of the need to specify flags at all.

**Comment by chinmaygarde** [comment]
As an example, see how the `embedder_unittests` setup a [`fixtures`](https://github.com/flutter/engine/blob/dfd281bcaefe79bed77fc0aa42c5bb2632f64941/shell/platform/embedder/BUILD.gn#L84) target and depend on the same. In the unit-test, you can access the [fixtures path or open the directory directly](https://github.com/flutter/engine/blob/dfd281bcaefe79bed77fc0aa42c5bb2632f64941/testing/testing.h#L22). Getting into the habit of explicity depending on the assets needed by a test will also allow us to prune unused fixtures.

**Comment by GaryQian** [comment]
Ok, sounds good, will start to make the transition and will abandon this then.

**Comment by chinmaygarde** [comment]
Thanks. Ideally, we'd want to be able to run all test targets as standalone invocations.

**Pull request closed without merging**
