### PR TITLE
Add an option '--depfile' to produce ninja-style depfile for the generated kernel.

### PR DESCRIPTION
**Pull request by aam**
This is needed to fix dependency handling in builds which involve kernel compilation.

### CODE REVIEW

**Comment by aam** [comment]
cc @rmacnak-google who wrote this depfile generation once

**Comment by mraleph** [comment]
I am not completely sure this is the right way. I think Fasta has some internal methods that can be used to compute dependencies (e.g. we use that to generate dependencies file during `platform.dill` compilationk, search for `writeDepsFile` in `pkg/front_end` sources.). Maybe we should ask Peter for help to expose these APIs.

**Comment by aam** [comment]
@peter-ahe-google, can you please share your thoughts on this?

**Comment by peter-ahe-google** [comment]
I think we can share the implementation of writing dependencies.

Here is the basic method that writes out the dependencies in a way that we know works with ninja AND Flutter: https://github.com/dart-lang/sdk/blob/a369b8849707862d8a876b2908f00ad8b96e6d5a/pkg/front_end/tool/_fasta/compile_platform.dart#L91

The way you compute dependencies should work except for patch files. Patch files may be a problem because I've sometimes seen Flutter compile everything from source and not using platform.dill. So you're probably better off getting the dependencies from `program.uriToSource.keys`.

If you also want to recompile when Fasta has changed, you need something more complicated.

I'd like to see if we can do a better job at supporting front-end server, perhaps we can do a GVC next week and discuss this?

**Comment by aam** [comment]
Thanks Peter! I switched to using `program.uriToSource` now.
Let me know what would be the best way to share implementation of `writeDepsFile`, if I can help with that.

GVC sounds good!

**Comment by mraleph** [comment]
I found that dependencies can be loaded in `getSourceFiles()` in `flutter.gradle` so we should check before committing that gradle code also works.

**Comment by aam** [comment]
Yes, it works. When I edit $FH/flutter/packages/flutter/lib/src/widgets/focus_manager.dart and rerun gradle:
```
$FH/flutter/examples/flutter_gallery/android  $  $FH/flutter/examples/flutter_gallery/android/gradlew -PlocalEngineOut=$FH/engine/src/out/android_debug_unopt_x86 -Ptarget=$FH/flutter/examples/flutter_gallery/lib/main.dart -Ppreview-dart-2=true -Pstrong=true assembleDebug --info
...
> Task :app:flutterBuildDebug
Putting task artifact state for task ':app:flutterBuildDebug' into context took 0.001 secs.
Executing task ':app:flutterBuildDebug' (up-to-date check took 0.098 secs) due to:
  Input property 'sourceFiles' file $FH/flutter/packages/flutter/lib/src/widgets/focus_manager.dart has changed.
```

With this PR, editing `focus_manager.dart` is not picked up by gradew.

**Pull request merged**
