### PR TITLE
Add basic --deploy mode

### PR DESCRIPTION
**Pull request by eseidelGoogle**
Not clear what configs are needed.  Release is probably the wrong name now.  Probably want --develop and --deploy instead?  Not sure.

As written the bots will need to pass --release --deploy, which seems a bit silly.

@jason-simmons @devoncarew @abarth @johnmccutchan

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

It might make sense to have two different GN flags for:
  * standard versus deployment configuration
  * debug versus release compiler settings

**Comment by eseidelGoogle** [comment]
It may make most sense to leave this for you to decide how you'd like it done. :D

**Comment by eseidelGoogle** [comment]
I made --deploy real.  Sets dart_product=true

**Comment by eseidelGoogle** [comment]
Closing in lieu of https://github.com/flutter/engine/pull/2598

**Pull request closed without merging**
