### PR TITLE
Remove use of base::CommandLine in favor of ftl::CommandLine.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Had to disable base trace logging because it implicitly depended on a base command line being initialized. So this cant land unless I replace trace logging without base. Coming up next.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

Where did the logging::InitLogging calls go?

**Comment by chinmaygarde** [comment]
> Where did the logging::InitLogging calls go?

All we used `base::logging` for was to enable the callbacks that we used to directly pipe trace events to the Dart timeline. In an upcoming patch, I am going to write the macros that tie to the Dart timeline directly instead of going through the base machinery. Based on https://gist.github.com/chinmaygarde/e6323a61930ba659c83a5e8ad0920fdb I though logging and command line handling were orthogonal. But logging ends up requiring an initialized command line. So I disabled it for now (I mentioned this in the initial patch notes). I will land this after I wire up trace events separately.

**Comment by abarth** [comment]
I would expect that the base JNI code will also end up depending on logging.  We might need to continue initializing it until we get rid of the last other base dependency.

**Comment by chinmaygarde** [comment]
> I would expect that the base JNI code will also end up depending on logging.

I don't think this is the case. Accessing the command line without initializing the same trips an assertion. And I was able to run the engine in unopt on Android.

**Comment by abarth** [comment]
I mean if you trip a `DCHECK`, that goes through the logging subsystem.

**Comment by chinmaygarde** [comment]
Ah. I see. I guess I will have to move to FTL assertions first too then.

**Comment by chinmaygarde** [comment]
Everything is tied together in base in one way or another. I am closing this patch for now. Working on replacing everything related in one go.

**Pull request closed without merging**
