### PR TITLE
Revert "[Impeller] DlAiksCanvas as a DlCanvas wrapper for impeller::Canvas"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/engine#45131

This is failing the Impeller variants of the unobstructed platform views tests:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/132249/overview

```
Failing tests:
	-[UnobstructedPlatformViewTests testPlatformViewsMaxOverlays]
	-[UnobstructedPlatformViewTests testOneOverlay]
	-[UnobstructedPlatformViewTests testOneOverlayPartialIntersection]
	-[UnobstructedPlatformViewTests testTwoIntersectingOverlays]
	-[UnobstructedPlatformViewTests testOneOverlayAndTwoIntersectingOverlays]

** TEST FAILED **
```

We've retried it a few times so I suspect this isn't a flake.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by dnfield** [comment]
It is building an RTree,b ut whether the RTree is correct or not is another question. I'll look into this.

**Comment by dnfield** [comment]
I'm confused about why this didn't fail on presubmit, but I think it's probably because of some changes that @zanderso made that I might not have sync'd to. I'll double check that.

**Comment by zanderso** [comment]
> I'm confused about why this didn't fail on presubmit, but I think it's probably because of some changes that @zanderso made that I might not have sync'd to. I'll double check that.

Yeah, I recently re-enabled these tests.

**Comment by dnfield** [comment]
Ok. There's some sadness fo rme though since they're passing locally.

**Pull request merged**
