### PR TITLE
Move <1m web_engine builds to 8 core machines.

### PR DESCRIPTION
**Pull request by godofredoc**
There are several build steps taking less than 1 minute to execute in a 32 core machine. To mitigate the problem of limited 32 core machine resources we are moving those builds to 8 core machines.

Bug: https://github.com/flutter/flutter/issues/127336

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by eyebrowsoffire** [comment]
This file is generated via `felt generate-builder-json` so this will be reverted if anyone needs to generate this file again. We should update the generator to put these values in instead. See `generate_builder_json.dart`

**Comment by godofredoc** [comment]
> This file is generated via `felt generate-builder-json` so this will be reverted if anyone needs to generate this file again. We should update the generator to put these values in instead. See `generate_builder_json.dart`

@eyebrowsoffire would it be possible to help us with the change? I'm landing a couple of releases today and won't be able to take a look during the day.

**Comment by eyebrowsoffire** [comment]
Yes I can help

**Comment by eyebrowsoffire** [comment]
Whoops, I did not mean to close the PR, sorry.

**Comment by eyebrowsoffire** [comment]
I opened an alternative PR here that updates the code generator: https://github.com/flutter/engine/pull/42321/files

**Comment by godofredoc** [comment]
> I opened an alternative PR here that updates the code generator: https://github.com/flutter/engine/pull/42321/files

Thank you. Closing this one.

**Pull request closed without merging**
