### PR TITLE
[macOS] Fix test fixture identifier style

### PR DESCRIPTION
**Pull request by cbracken**
Rename the C++ style can_composite_platform_views and native_callback
functions to the Dart-style identifiers canCompositePlatformViews and
nativeCallback in the macOS desktop test fixtures.

Also corrects the helper method identifier from CreateSimplePicture to
_createSimplePicture, thus making it library-private to help readers
understand it's a local helper.

Ref: [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#naming)
Ref: [Effective Dart](https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]
LGTM!

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
Spotted a couple more and pushed an update.

**Review by goderbauer — APPROVED** [review]
Still LGTM

**Review by loic-sharma — APPROVED** [review]
Updates LGTM 🚀

**Pull request merged**
