### PR TITLE
Rename FlBackingStoreProvider to FlFramebuffer

### PR DESCRIPTION
**Pull request by robert-ancell**
The name was confusing, as it only provided one type of backing store. FlBackingStoreProvider sounds more like an interface that the FlFramebuffer would implement if we had multiple backing stores.

Use OpenGL types for values.

Fix cases where this was sometimes called a texture.

Improve documentation.

Remove the use of GdkRectangle for dimensions - the framebuffer only has a width and a height. There was code that was using the x,y values which would always have been zero - this has now been removed.

This should be test exempt as it is only a renaming and will be covered by existing tests.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by cbracken** [comment]
A bit puzzled because the failure here is a mac host build failure:
```
[8555/10607] ACTION //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/mac:clang_arm64)
FAILED: gen/flutter/lib/snapshot/vm_isolate_snapshot.bin gen/flutter/lib/snapshot/vm_snapshot_instructions.bin gen/flutter/lib/snapshot/isolate_snapshot.bin gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin 
vpython3 ../../build/gn_run_binary.py clang_x64/gen_snapshot --snapshot_kind=core --enable_mirrors=false --vm_snapshot_data=/Volumes/Work/s/w/ir/cache/builder/src/out/host_release_arm64/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin --vm_snapshot_instructions=/Volumes/Work/s/w/ir/cache/builder/src/out/host_release_arm64/gen/flutter/lib/snapshot/vm_snapshot_instructions.bin --isolate_snapshot_data=/Volumes/Work/s/w/ir/cache/builder/src/out/host_release_arm64/gen/flutter/lib/snapshot/isolate_snapshot.bin --isolate_snapshot_instructions=/Volumes/Work/s/w/ir/cache/builder/src/out/host_release_arm64/gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin /Volumes/Work/s/w/ir/cache/builder/src/out/host_release_arm64/flutter_patched_sdk/platform_strong.dill
```

**Comment by robert-ancell** [comment]
> A bit puzzled because the failure here is a mac host build failure. 

A number of builds today have had mac failures. I guess we ignore them?

**Comment by cbracken** [comment]
I would try rebasing to tip of tree in case this was a bad commit that was reverted. This looks nearby to code I changed a week ago, but would be strange if it only started breaking as a delayed time bomb. The engine tree seems green right now. I'll kick off a re-run on that test to see what happens. The error doesn't seem like it would be a flake though.

**Pull request merged**
