### PR TITLE
Flip the switch on enabling the interpreter by default in debug runtime mode.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM but we probably don't want this in the codelab branch that's being cut today.

**Comment by abarth** [comment]
@collinjackson

**Comment by collinjackson** [comment]
OK, I'll keep that in mind when I'm cutting the codelab branch.

**Comment by chinmaygarde** [comment]
> OK, I'll keep that in mind when I'm cutting the codelab branch.

Is a that a go/no-go on landing this?

**Comment by collinjackson** [comment]
LGTM on landing this, I can always cut a release branch from earlier in the day and cherry-pick any fixes I need that came later

**Comment by chinmaygarde** [comment]
> LGTM on landing this, I can cut a release branch from earlier in the day and cherry-pick any fixes I need that came later

Sounds good. Landing this.

**Pull request merged**
