### PR TITLE
revert path volatility tracker

### PR DESCRIPTION
**Pull request by dnfield**
This appears to have caused a regression in memory usage observed in an internal project.

I've reproduced that locally and will try to create a test to capture it and reland this.

@zanderso @chinmaygarde @jason-simmons

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
Will this affect `customer: money` at all?

**Comment by dnfield** [comment]
It will increase memory usage for rive animations.  Unfortunately in its current state it causes increasing memory usage for some animations.

**Comment by dnfield** [comment]
I'll add the bug for reference when I'm at my laptop

**Comment by dnfield** [comment]
Internal bug: b/176871072

I have a reproduction, going to work on trying to reduce it a bit further and will try to add it as a test here or in devicelab.

Then I'll try to reland.

**Comment by dnfield** [comment]
I may have misdiagnosed this. Need to look into it a bit more.

**Comment by dnfield** [comment]
Ok, I think I have a clear, small reproduction now. This did in fact cause ap roblem for some paths.

**Pull request merged**
