### PR TITLE
Actually use Impeller in scenario_app tests

### PR DESCRIPTION
**Pull request by dnfield**
Right now, the scenario_app tests that claim to use Impeller are not actually using Impeller. This is for a few reasons:

- The arguments passed via instrumentation do not end up by default on the `Intent` for the `Activity` that is under test.
- The arguments passed via instrumentation were in the wrong order and not getting sent to instrumentation at all.

~~This patch updates existing tests to use a new `@Rule` that reads the arguments from the instrumentation's argument `Bundle` and injects them into the `Intent` that we actually pass to the `Activity` under test.~~ This patch updates the test runner to force initialization of the shell arguments for all tests once and early. It also updates the argument order in the script and adds a verification that Impeller prints that it is being used at least once.

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by matanlurey** [comment]
@dnfield I am going to hit "Update branch" so we can get my logging improvements and Jonah's crash improvements.

**Comment by dnfield** [comment]
Something is going wrong in the general case - Impeller is getting used when I run a single test, but not when I run them all.

**Comment by dnfield** [comment]
I've modified this patch to be a bit simpler and remove a test that does not work with Impeller currently - the test tries to construct a Flutter Engine in an unusual way and ends up hanging when we try to initialize Vulkan for reasons that are not entirely clear to me. I don't think we need to do that though, we have coverage already elsewhere around initializing FlutterEngine objects.

**Review by matanlurey — APPROVED** [review]

**Comment by matanlurey** [comment]
I took a quick look at the gold digests and they look WAI, the texture tests that are rendering blank are waiting for a combination of https://github.com/flutter/engine/pull/50730 (h/t @chinmaygarde) and https://github.com/flutter/flutter/issues/144199 (h/t @johnmccutchan).

**Comment by dnfield** [comment]
I'm going to approve the goldens. Chinmay can merge this into his PR and that should give him the test coverage he needs.

**Pull request merged**
