### PR TITLE
Make the context current before accessing GL in MakeSkiaGpuImage

### PR DESCRIPTION
**Pull request by dnfield**
The unconditional `MakeBitmapImage` is no longer necessary on Linux, with or without this context switch change. That fixes https://github.com/flutter/flutter/issues/108835
Might help https://github.com/flutter/flutter/issues/121485

Context switch fixes https://github.com/flutter/flutter/issues/120815. This was figured out by @jason-simmons - without the switch, we might be piggybacking on GDK's GL context/FBO and causing the problems seen in that bug.

I'm not quite sure what to do about the MakeBitmapImage path. It's not entirely safe, for example if you went to background on iOS and have a display_list that contains an SkImage_gpu. We have this problem elsewhere too AFAICT (e.g. in the regular `toImage` path).

~~I'm not sure how to test this. Will try to think on that a bit.~~

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by dnfield** [comment]
I think I know how to test this. Will take a stab at it later today.

**Comment by dnfield** [comment]
Added a test.

It doesn't cover the exact same scenario as the bug, but basically forces the context on the raster (platform) thread to get trampled. If the rasterizer fails to make it curent again the test fails.

**Comment by alexmercerind** [comment]
It seems this broke whole external texture API on Linux: https://github.com/flutter/engine/pull/24916. :pray: 
And... essentially video rendering offered by [`package:media_kit`](https://github.com/alexmercerind/media_kit) on Flutter Linux's `master` channel.

You may try running this minimal application for testing:
https://github.com/lattice0/external_texture_flutter_linux/tree/master/external_texture/example

No GL content draws to the UI.

**Comment by dayron9110** [comment]
@dnfield  so this change was returned?

**Comment by dnfield** [comment]
> @dnfield so this change was returned?

I don't think I understand the question. This patch was not reverted in Flutter, but it looks like it was reverted in a fork of Flutter somewhere else.

**Pull request merged**
