### PR TITLE
Protect LanguageRange behind Android O. That's when it was added.

### PR DESCRIPTION
**Pull request by mehmetf**

### CODE REVIEW

**Comment by GaryQian** [comment]
Looks like the build is requiring non-nullable to be enabled?

**Comment by mehmetf** [comment]
How do I retry these tests?

It would also be good to give me permission to merge despite failures as the failures have nothing to do with my PR which is patched in google3 and will create complication when it rolls.

**Comment by GaryQian** [comment]
I believe LUCI has a UI option to "retry" but I don't think github is able to connect the rerun to the webhook as far as I can tell. A simple but reliable way to rerun all is to just push an empty commit.

I didn't realize you can't manually merge on red, I'm sure @Hixie can resolve that for you!

**Comment by GaryQian** [comment]
Landing manually, reruns passed and luci failure is an infra flake.

**Pull request merged**
