### PR TITLE
[WIP] [web] locale / onLocaleChanged implementation

### PR DESCRIPTION
**Pull request by slightfoot**
*Work In Progress*
PR still requires tests.

Details: flutter/flutter#48886

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@yjbanov @mdebbar perhaps you could suggest a testing strategy here?

**Comment by yjbanov** [comment]
Testing-wise I think artificially dispatching a "languagechange" event and checking that `Windows.onLocaleChanged` receives it should be sufficient. I just checked in Chrome and it happily dispatched the event via `window.dispatchEvent(new Event('languagechange'));`.

**Comment by yjbanov** [comment]
What's the status of this PR? @slightfoot are you still interested in finishing it up? I've been looking at locales recently, so I can take it over if you are busy with other stuff.

**Comment by slightfoot** [comment]
@yjbanov I can never find time for everything I want to contribute. Happy for you to take over. The only reason I put it on hold is to test anything with Flutter Web is a pain with the way its setup right now. I wonder how the team dev it. It can't be the way I have to do it at the moment, what Jonah said here: https://github.com/flutter/flutter/issues/48886#issuecomment-574749766

**Comment by yjbanov** [comment]
> @yjbanov I can never find time for everything I want to contribute. Happy for you to take over. The only reason I put it on hold is to test anything with Flutter Web is a pain with the way its setup right now. I wonder how the team dev it. It can't be the way I have to do it at the moment, what Jonah said here: [flutter/flutter#48886 (comment)](https://github.com/flutter/flutter/issues/48886#issuecomment-574749766)

Yeah, it's way more complicated than it should be. I'll take over. Are you OK with me branching off of your PR?

**Comment by slightfoot** [comment]
> Yeah, it's way more complicated than it should be. I'll take over. Are you OK with me branching off of your PR?

Sure. All yours.

**Comment by yjbanov** [comment]
New PR is here: https://github.com/flutter/engine/pull/18137

**Pull request closed without merging**
