### PR TITLE
Roll Skia to 14f8f6d984ff

### PR DESCRIPTION
**Pull request by bdero**
Resolves https://github.com/flutter/engine/pull/57068.

Set args `skia_use_libpng_decode=true` and `skia_use_rust_png_decode=false`.

https://skia.googlesource.com/skia.git/+log/e78dd0265002..14f8f6d984ff

2024-12-09 kjlubick@google.com Update GN build to allow for rust PNG decoding only
2024-12-09 lukasza@chromium.org [rust png] Update Skia => `png` dependency to version 0.17.15.
2024-12-09 kjlubick@google.com Add placeholder files for jsonreader

### CODE REVIEW

**Comment by bdero** [comment]
I ported the build rules and `ImageDecoderNoGLTest.ImpellerUnmultipliedAlphaPng` is now passing locally, so hopefully we're good to go.

**Comment by zanderso** [comment]
FYI @kjlubick

**Comment by kjlubick** [comment]
I had thought I set things up to land and roll cleanly.

I'm guessing Flutter is (somewhere) still dependent on the legacy registration of codecs (https://skia-review.googlesource.com/c/skia/+/926096/14/src/codec/SkCodec.cpp). We should fix that to prevent issues like this from happening (and making the dependencies more explicit).

**Comment by kjlubick** [comment]
Ah, I think it's simply this: https://github.com/flutter/engine/blob/a8c08bc9b909291464320ce0584c83b9950bb76c/lib/ui/painting/image_decoder_no_gl_unittests.cc#L205

That should probably use `SkPngDecoder::Decode` explicitly and directly.

**Pull request merged**
