### PR TITLE
Add a new AppDelegate method for registering plugins for background Isolate

### PR DESCRIPTION
**Pull request by xtelinco**
https://github.com/flutter/flutter/issues/21925

At the moment plugins are registered in the AppDelegate didFinishLaunchingWithOptions. However they are only registered within the FlutterViewController and hence the main UI isolate. So the plugin method channels are only known by the UI isolate.

My idea is to provide a new registerHeadlessPlugins method on the AppDelegate to register plugins for the FlutterHeadlessDartRunner (Background Isolate). You could then register any plugins you need for the background isolate. I think that you may well have differing requirements for the plugins required for the Background tasks, and using the same list as the UI isolate seems a little inflexible.

(void)registerHeadlessPlugins:(NSObject*)registry {
[FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
}

It would be really good if we can get this working. I don't know if this is the best approach, but it seems reasonable to me.

### CODE REVIEW

**Comment by jamesderlin** [comment]
CC @bkonyi @dnfield

**Comment by dnfield** [comment]
I have some work in progress that would make the Headless exeuction model use a FlutterEngine class that is a plugin registry.  I'm not sure this would really be necessary after that, and I think it would conflict.

**Comment by dnfield** [comment]
(If it's not clear - I think this is a good idea and this needs to happen, but I think the approach taken here will end up conflicting with the approach I'm taking to make executing Engine instances survive as headless or with a viewcontroller)

**Comment by xtelinco** [comment]
OK happy to keep this as an internal branch and migrate back into master at a later date. 

When are you likely to be ready with your solution?

**Comment by dnfield** [comment]
Shooting for in the next few days.

**Comment by dnfield** [comment]
If you don't mind taking a look at #6447 I'd appreciate it!  It'd be great to know if that really does solve your use case or not.

**Comment by xtelinco** [comment]
Yes I like your refactoring to separate the Isolate interface from the viewcontroller. Very much needed.

However I don't fully understand how the plugins get initialised for background isolate, which is my problem.

From what I understand. In normal foreground operation, the app is launched with the the viewcontroller created and hence the calls to registerWithRegistrar cals called in didFinishLaunchingWithOptions, call against the AppDelegate registrar which in turn delegates to the viewcontroller registrar.

In background operation there is no viewcontroller. The background FlutterEngine (Isolate), is created after didFinishLaunchingWithOptions has finished. So the calls to registerWithRegistrar cannot register with plugins with the Background Isolate.

I can see how your solution fixes this? We don't know when a new FlutterEngine may be created, and hence once a new background isolate is created, we need some way to register any plugins the developer needs for the background task.

**Comment by dnfield** [comment]
It's possible I'm missing something, but `FlutterEngine` now handles all plugin registration, and the `FlutterHeadlessDartRunner` is a subclass of `FlutterEngine` - so FlutterHeadlessDartRunner no longer needs to be modified to support the registrar interface.

I think I'm missing something you're doing here though because I'm working more in an Add2App space where I can manually register plugins however I need to in the application code wherever I'm creating my FlutterEngine instance - however, I assume you're working in a generated host app which isn't doing that.  Can you provide a simple sample app that doesn't work without your patch but does work now so I can test it with my patches?  I suspect I may need something else in the FlutterAppDelegate like you're doing, but I'm not entirely sure what.

**Comment by dnfield** [comment]
I've been toying around with this a bit - I think what you'r doing makes some sense, but with a couple modifications.  

The main thing I'm wondering about is whether we really want to register _all_ plugins with the Headless isolate. But I can't think of a way to avoid that that doesn't involve expecting developers to do a lot of convoluted tracking and context switching to make sure things run on the right isolate.

**Comment by dnfield** [comment]
We also can't assume that the AppDelegate will actually be a `FlutterAppDelegate` - someone might choose to not do that for Add2App (or even in a "regular" FlutterApp that they've otherwise messed with.

However, if we want to make developers manually register plugins for this case, I'm not sure what else needs to be done besides make the HeadlessCodeRunner implement PluginRegistry (which it will now), and suggest a good place to do that.  It might be nice if there was some way to tell the HeadlessRunner to register a plugin from the Dart side...  /cc @bkonyi similar to how you're passing in a callback location at runtime.

**Comment by xtelinco** [comment]
Maybe we are attacking this the wrong way round. The real problem is that we don't know if the plugin can support background operation (register/intialise multiple times). So maybe we should put the responsibility onto the plugin developer. Maybe we provide a way for the plugin to register a delegate to auto register itself for background operation. 

Then when a background engine is started, we call all the delegates that have registered for background operation to initialise themselves for the new engine.

It means that every plugin would need to be extended, but it removes the responsibility from the app developer.

So the process would be:

1) Plugin is registered in didFinishLaunchingWithOptions.
2) Plugin calls a method on the registrar providing a delegate to initialise a new background engine/isolate.
3) We have to assume that the plugin registration will initialise the UI isolate (for backward compatibility). Or we could assume if they register an initialisation delegate, this will be used for the UI engine/isolate as well??? [Not sure UI bit works however in all cases..]
4) When the new background engine is created all the registered initialisation delegates are called for them to do their stuff.

**Comment by radvansky-tomas** [comment]
Can somebody advice my how I can register plugins after background callback has been called from dispatcher? 

I have simple callback (which was successfully used in other projects)

void callback(FirebaseMessage m, MessageEvent e) async {
  print('Message $m Event: $e');
  final SendPort send =
  IsolateNameServer.lookupPortByName('messaging_send_port');
  send?.send(e.toString());
  var msg = Message.fromJson(m.data);
  new NotificationCore()._displayMessage(msg);
}

But in this moment, there are no plugins available to use :( ...so in my case I am trying to issue local notification, but plugin I want to use is not present and i got:

Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)

Whats the reason for such execution and pattern if there is no access to the plugins ?! So unless I made my custom plugin combining plugins already existing, there is no way for me to complete the task...

In my case to combine firebase_messaging and local_notifications...which really does not make any sense

**Comment by xtelinco** [comment]
Yes put simply it doesn't work. The fix isn't simple unfortunately. Channels in flutter currently only communicate between a single isolate and the plugins. This means that the background isolate can't communicate with the plugins. The solution here isn't ideal and has issues and is no longer current.

There are multiple issues open for this. The most current at the moment is here, with further ideas on how to fix it. There seems to be quite a bit of work to do to fix it.

https://github.com/flutter/flutter/issues/23904

**Comment by radvansky-tomas** [comment]
@xtelinco thank you for answer, however this is truly ridiculous...Can you tell me how I can call same plugin from headless code than...as I expect that that one which invoked headless callback should be available...

So firebase_messaging invokes this callback after remote notification -> 

void callback(FirebaseMessage m, MessageEvent e) async {
print('Message $m Event: $e');
final SendPort send =
IsolateNameServer.lookupPortByName('messaging_send_port');
send?.send(e.toString());
//HOW TO INVOKE PLUGIN METHOD HERE ?! (in this case my firebase_messaging) 
}

**Comment by xtelinco** [comment]
At the moment you can't! I am in exactly the same situation. I am only an App developer. My PR is working for me at the moment, but I am stuck on a old flutter revision until this can be resolved.

This PR does resolve the issue for me, but as you can see it no longer merges.

**Comment by radvansky-tomas** [comment]
According to https://github.com/transistorsoft/flutter_background_fetch/issues/1#issuecomment-438223808 you can...I am in the process of replicating it in my project...to find out how is it possible.

**Comment by dnfield** [comment]
@xtelinco  - I've gone ahead and fixed up the merge conflicts so you can try to keep using this patch.  I don't think this is the direction we'll end up taking, but I don't want to see you broken in the mean time.

**Comment by xtelinco** [comment]
@radvansky-tomas I think the problem with transistorsoft/flutter_background_fetch is that it uses the UI isolate. This is fine if you don't mind starting up the rest of your app's functionality by calling the dart main(), but I have quite a lot of stuff going on in the background (within the UI isolate); Things that I don't want to start unless I need to support the UI.

**Comment by christocracy** [comment]
@xtelinco I may be naïve, I'm rather new to Flutter, but if I insert a log message [here in the background_fetch example](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/lib/main.dart#L13)

```dart
void main() {
  print('*** BackgroundFetch main ***');

  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.io/testing/ for more info.
  runApp(new MyApp());

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

When the `background_fetch` headless process is first launched, shouldn't I see the log message:
```
*** BackgroundFetch main ***
```
I don't.

**Comment by christocracy** [comment]
>how does your plugin work then?

I followed [this tutorial](https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124)

> if you were to start your app, setup a background fetch. Then hard unload your app and then view your console logs, you will see the your *** BackgroundFetch main *** as the background fetch starts.

I do not, and I wouldn't expect to.

Why don't you play around with my [background_fetch example](https://github.com/transistorsoft/flutter_background_fetch#large_blue_diamond-demo-application), it's very simple.

- Boot the example.
- Simulate a fetch:  
```
$ adb shell cmd jobscheduler run -f com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample 999
```
- Terminate the app.
- Simulate a fetch once again.  This will re-launch the app process *without calling `main()`*.
```
$ adb shell cmd jobscheduler run -f com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample 999
```

>The real problem occurs when you are taking geo location updates

Have you tried my [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation)?   It too has a Headless implementation.

**Comment by xtelinco** [comment]
Arh the problem is with ios not android. I don't have the problems with android. Is this the same on ios?

**Comment by christocracy** [comment]
There's no such thing as "Headless" iOS, as far as I'm concerned.  When iOS re-launches your app in the background to service an event (eg: Geofence transition, Significant location change, Background-fetch, push notification, etc), iOS launches the entire app in the background.

**Comment by xtelinco** [comment]
Well not yet anyway!  It partially works in the flutter_background_geolocation for iOS, apart from plugins. This PR allows you to use plugins within the "new" headless operation in iOS, and it in fact doesn't launch the entire app in the background. However there are numerous limitations and issues with doing this, mainly to do with plugin incompatibility. The flutter team are rethinking the headless operation in iOS, and there are a few options on the table.

**Comment by christocracy** [comment]
From my point-of-view, the headless-ness of an IOS app are these internal OS services that *allow* one to subscribe to events that are *capable* of re-launching an app in the background.

If one subscribes to an iOS geofence, for example, that geofence is monitored forever until one explicitly stops monitoring it (even after device reboot).  If iOS detects a geofence transition, it will launch the *entire* app in the background to service that event.

So what is it that Flutter is considering then?  To choose not to render the UI when the app is launched in the background?  This doesn't seem valuable to me.

I think it's best to just assume the entire iOS app is rendered when the OS re-launches your app in the background to service some event (significant location change, geofence, push notification), just as if the user launched it from their home-screen.

**Comment by christocracy** [comment]
After all, iOS is very aggressive in terminating apps in the background to free up memory.  If your app is launched to service a push notification, the OS is going to terminate it a few minutes later after lying dormant in the suspended.

**Comment by xtelinco** [comment]
True Android has a better solution overall.

The current Flutter solution for headless uses a completely separate isolate to run in the background. So the UI isolate isn't started for background operation. This is nice but might be overkill, and does cause several issues, namely plugins and the fact that flutter developers aren't used to the isolation that  Isolates provide.

What I want to avoid is starting requests etc until they are needed. For instance I may create a websocket connection to service updates to the UI, when the UI starts. Also I want to reduce the power/memory consumption by doing less on a processing a background update. The headless isolate method does this but it may be more trouble than it is worth.

Maybe a messaging solution would be better. Start the UI isolate, but then listen for a message before creating the MainApp object. The message is only sent when the App moves to the active state for the first time. Then we can handle background tasks like geo updates also via a message, like you are doing in your plugin, all within the UI isolate.

**Comment by christocracy** [comment]
I really don't think it's worth worrying about.

An iOS app in the background is *suspended* unless you've engaged a background-mode, such location-updates with [`CLLocationManager startUpdatingLocation`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423750-startupdatinglocation?language=objc) or started a music player.

If your app is simply launched in the background to service a background-fetch or push-notification event, iOS is going to *suspend* your app after *exactly* 30 seconds.

It doesn't matter if you've set up a WebSocket, your app is going to be suspended and consuming 0 energy (unless, as I said above, you engaged location-services or started background-audio, etc).

**Comment by xtelinco** [comment]
But I have setup location updates!

**Comment by xtelinco** [comment]
Yes, I beginning to agree with you.

The official plugin https://github.com/flutter/plugins/tree/master/packages/location_background
uses the headless isolate method. But i suppose the question is, is it worth it?

If the current framework can handle all use cases, the usage of the framework for those use cases just needs documenting.

**Comment by christocracy** [comment]
>The official plugin

Have you tried my [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation)?  I've been working on this plugin for **over 5 years**.  it was originally developed for Cordova.  It's very advanced.  It was originally designed for tracking first-responders in disaster zones.  It's well suited to "fleet tracking" type use-cases.

**Comment by xtelinco** [comment]
I'll take a look. Thanks.

I do think that geo location is so important to lots of apps, it needs to be part of the core plugins. The official version should work for most use cases. Your plugin looks to add the extra functionality beyond the basics where it is required.

@bkonyi What's your view on all this? Was plugin/location_background meant to be a demo on how to do things in the background on iOS, or more a useable location plugin? As Chris suggests, we could handle the background updates on iOS within the UI isolate but limit the UI startup until a resume message is received. Your plugin is missing quite a few components most notably Android support, are you thinking about extending it, or taking PRs on it?

**Comment by xtelinco** [comment]
Yes, otherwise life would be easy :-)

**Comment by christocracy** [comment]
What do you mean “geofences don’t really work”.  I been field-testing geofence in my neighborhood almost daily for nearly 3 years.  I find them incredibly consistent.

**Comment by radvansky-tomas** [comment]
@christocracy I've checked your solution deeper, but as @xtelinco said, thats not background execution. I was always talking about iOS. 

So, push notification is received, and your app is executed, but not its not in foreground, there is not flutter accessible...your eventsink is null and there is no way for me to contact flutter dart code or any other plugins.

So this is really not a solution to generic problem, no background execution support for flutter !

Yes I tried some other examples with headless execution, but plugins are not available.

**Comment by christocracy** [comment]
>there is not flutter accessible

When an iOS launches an app in the background to service some event (push, geofence, etc) the state of the app should be the same as if the user launched it themselves from the home-screen.

**Comment by radvansky-tomas** [comment]
@christocracy Ok then try simple thing...schedule location tracking on your app, only significant location trigger. Then start tracker and KILL app. Normal native iOS app, will launch app again, but not from normal entry point, but from location ones if I remember it correctly. 

So tell me, how you run + register other flutter plugins, if those method are not even called ?!

**Comment by christocracy** [comment]
>Normal native iOS app, will launch app again, but not from normal entry point, but from location ones if I remember it correctly.

I'm not sure I understand.  Yes, [locationManager:didUpdateLocations:](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/1423615-locationmanager?language=objc) will fire, but not before [application:didFinishLaunchingWithOptions:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application?language=objc).

**Comment by radvansky-tomas** [comment]
Yes @christocracy just checked links and Yes, in your case: 

`If you start this service and your app is subsequently terminated, the system automatically relaunches the app into the background if a new event arrives. In such a case, the options dictionary passed to the application(_:willFinishLaunchingWithOptions:) and application(_:didFinishLaunchingWithOptions:) methods of your app delegate contains the key location to indicate that your app was launched because of a location event. Upon relaunch, you must still configure a location manager object and call this method to continue receiving location events.`

Which is however not the case for silent remote notifications:
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application

if you enabled the remote notifications background mode, the system launches your app (or wakes it from the suspended state) and puts it in the **background state** when a remote notification arrives.

ie. its like background task (not UI thread)...and method application:didFinishLaunchingWithOptions: will be triggered ONLY if user click on notification (ie alert has to be present)

Good explanation: 
https://medium.com/fantageek/push-notification-in-ios-46d979e5f7ec

application:didReceiveRemoteNotification:fetchCompletionHandler: is called. If app was not killed by user, it is woke up and state changed to UIApplicationStateInactive.

**Comment by radvansky-tomas** [comment]
So for real background execution we need to have standard option to call flutter dart code, perform init (main function or headless task) ...register and load plugins and provide callback back to background native task to finish it

**Comment by christocracy** [comment]
You're aware of the `content-available` flag for iOS push notifications?

**Comment by radvansky-tomas** [comment]
Yes this is what I am using

**Comment by cbracken** [comment]
@dnfield can you take a look at the latest round of work on this?

/cc @amirh for further thoughts from the plugins side

**Comment by dnfield** [comment]
@xtelinco I had been leaving this open to make sure we didn't break you while we work on a full fix.  However, I don't think this approach is the one we're going to end up taking.  @bkonyi is working on a solution for that.  Do you still want to keep this open, or is it ok to close to remove from our review queues?

**Comment by xtelinco** [comment]
Yes, I'm happy to close it. I am working on moving my code stream to use the main UI isolate for everything in iOS. It means a bit of a split as now android and iOS work differently, but I think it is better than maintaining this fork. 

Cheers for your help.

**Pull request closed without merging**
