### PR TITLE
[web] Fix trivial type issue.

### PR DESCRIPTION
**Pull request by joshualitt**

### CODE REVIEW

**Comment by joshualitt** [comment]
@eyebrowsoffire ptal, just a trivial fix to the type here.

**Comment by osa1** [comment]
The changed line here causes problems with https://dart-review.googlesource.com/c/sdk/+/292881, right?

Assuming the CL is correct, how did this line work on other web backends before? Shouldn't this line cause runtime type errors in other backends that implement runtime type tests correctly?

**Comment by joshualitt** [comment]
I think what might be happening here is that `_jsElements` is initialized with `<Object>[]`, and JS backends are able to pass `List` by reference to JS. Interestingly, we could probably do something like this on Dart2Wasm as well, because I don't think this `List` is used in JS at all, it's just being stored in JS temporarily. That is for a future CL though.

**Review by eyebrowsoffire — APPROVED** [review]

**Comment by Hixie** [comment]
test-exempt: current code doesn't pass tests

**Pull request merged**
