### PR TITLE
[flutter_releases] Fix build error 

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

Fix build error https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20stable%20iOS%20Engine/16/overview

Follow-up fix to https://github.com/flutter/engine/pull/22930

### CODE REVIEW

**Comment by christopherfujino** [comment]
led build of mac ios engine with the correct recipe: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/fujino_google.com/3de29676009abd851fd7bbedd68a2f237768d0156f62ec397c47c60dcb586d9d/+/annotations

**Comment by cyanglaz** [comment]
@christopherfujino it was a wrong fix, pushed again.

**Comment by christopherfujino** [comment]
I triggered another LED build https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/fujino_google.com/342a1f37debe81e0f1ee1bcf32c10620f08bb403abcf267ebe145f55cb3a6424/+/annotations, and I'm seeing a different failure, this time in "Scenario App Integration Tests". I will follow up tomorrow.

**Comment by cyanglaz** [comment]
@christopherfujino The test didn't fail locally, It is possibly a flake. Could you trigger another build and check?

**Comment by christopherfujino** [comment]
> @christopherfujino The test didn't fail locally, It is possibly a flake. Could you trigger another build and check?

Will do. cc @blasten in case this is expected to fail.

**Comment by christopherfujino** [comment]
re-run: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/fujino_google.com/e62b6a7574eea5ec97fc180050fd40770725b8fff9d91a90b1caafdd1761a694/+/annotations

**Comment by christopherfujino** [comment]
Ok, it passed on a re-run.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
has the same CI failures as the previous PR on branch https://github.com/flutter/engine/pull/22930, thus I am merging this to fix the Linux Android AOT Engine build.

**Comment by christopherfujino** [comment]
Mac Stable iOS Engine flaked post-submit, to fix, cherrypick https://github.com/flutter/engine/pull/22247/files

**Pull request merged**
