### PR TITLE
Mention Goma for Googlers in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by goderbauer**

### CODE REVIEW

**Comment by Hixie** [comment]
you don't strictly _need_ it, but ok. :-) LGTM.

**Comment by goderbauer** [comment]
Ok, I changed it slightly to point out that it is just recommended. I just want it to be mentioned at al so the next new guy doesn't take 7 month to learn about it :expressionless:.

**Comment by Hixie** [comment]
Seems legit. :-)

Maybe put it on our on-boarding documentation internally too?

**Comment by goderbauer** [comment]
Good point. I updated the internal on-boarding doc as well.

**Pull request merged**
