### PR TITLE
Remove obsolete discovery mechanism from FlutterView

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde @matthew-carroll

**Comment by cbracken** [comment]
lgtm

**Comment by matthew-carroll** [comment]
Can we get some historical context for the record?  What was this used for previously and why is it no longer needed?

PS - I just removed the same thing from my refactor work to match this PR.

**Comment by jason-simmons** [comment]
This was added to provide a way for IDE users to attach the debugger to a running Flutter app that wasn't launched through the IDE.

The tooling would issue a broadcast intent via adb, and all Flutter apps running on the device in debug mode would respond by writing an observatory endpoint to the Android log.  The IDE could then ask the user to select an app and then establish a debug connection.

I had implemented this flow as an experiment in the old Flutter Atom plugin, but I don't think it got much use.  The current tools do not make use of this.

**Pull request merged**
