### PR TITLE
Add unwrap to JSONUtil

### PR DESCRIPTION
**Pull request by mehmetf**
We have a use for this for the internal messaging plugin. Instead of rolling our own, it made sense to add it here especially since it has the mirror functionality (wrap).

### CODE REVIEW

**Comment by mehmetf** [comment]
Did not find any tests for JSONUtil anywhere. If you point me to it, happy to add tests for this.

**Comment by Hixie** [comment]
@mehmetf You may have to blaze new trails in testing to test this code.

**Comment by mehmetf** [comment]
@Hixie I do want to test this code; unfortunately I don't have much time to spend on it. Do you have a rough sketch in your mind on how the infra should look like? I can attempt to do it.

Having said that I don't think all that setup should be part of this PR so I will submit this as is and file a PR to create a testing harness for platform code in engine. Feel free to do a brain dump there.

**Comment by aam** [comment]
This broke the Linux and Mac builds https://build.chromium.org/p/client.flutter/console :
```
../../flutter/shell/platform/android/io/flutter/plugin/common/JSONUtil.java:47: error: cannot find symbol
                Iterator<String> keyIterator = jsonObject.keys();
                ^
  symbol:   class Iterator
  location: class JSONUtil
1 error
```

**Comment by Hixie** [comment]
@mehmetf I'm not familiar with how Java normally gets unit-tested, but I would expect it to follow a pattern similar to the C++ or Dart testing for the engine, which is in https://github.com/flutter/engine/tree/master/testing, driven from `run_tests.sh`.

**Pull request merged**
