### PR TITLE
Add test for external textures on Android

### PR DESCRIPTION
**Pull request by ds84182**
This PR (originally #26109) adds three tiers of tests for external texture rendering, along with comparisons for Android's SurfaceView.

* Identity transforms
* Surface rotations. This requires decoding a video through MediaCodec with the rotation parameter set. Android framework source basically passes through the rotation parameter to the underlying Surface.
* Surface crops, and surface rotations + crops. This requires the use of ImageReader (21+) and ImageWriter (23+). MediaCodec presents directly into the ImageReader, the crop rect is set on the acquired Images, and then the images are sent to ImageWriter which presents to the screen. The crop rect (which we now control) and rotation (passed from MediaCodec) are applied directly to the underlying Surface. Note that "Image" is a bit of a misnomer, they're actually just presentable hardware buffers.

Current screenshots show how Flutter's rendering is incorrect, which is what #24888 is supposed to address.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM - This tests are currently not triggered though: https://github.com/flutter/flutter/issues/90401

**Comment by ds84182** [comment]
Hm alright. Hopefully these tests can run in the future, since having some verification for this is very useful.

**Comment by chinmaygarde** [comment]
I believe this needs a rebase for the tests.

**Comment by chinmaygarde** [comment]
Any update on the rebase?

**Comment by ds84182** [comment]
Rebased, sorry for the delay.

**Pull request merged**
