### PR TITLE
Force GTK IM context to initialize at start

### PR DESCRIPTION
**Pull request by wmww**
Fixes https://github.com/flutter/flutter/issues/100385

A bit hacky. There might be a better way.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by wmww** [comment]
I can't find a better way to do this. GTK doesn't seem to expose any information on if a call to `gtk_im_context_set_client_window()` worked, so re-trying until it works isn't viable.

It appears native GTK apps may only work by accident, because GTK widgets make calls into the IM context on setup before they `enable` the context, and there is a Wayland roundtrip in-between.

**Comment by robert-ancell** [comment]
There seems to be a crash occurring in the tests:
```
[----------] 6 tests from FlKeyboardManagerTest
[ RUN      ] FlKeyboardManagerTest.SingleDelegateWithAsyncResponds
[       OK ] FlKeyboardManagerTest.SingleDelegateWithAsyncResponds (0 ms)
[ RUN      ] FlKeyboardManagerTest.WithTwoAsyncDelegates
[       OK ] FlKeyboardManagerTest.WithTwoAsyncDelegates (0 ms)
[ RUN      ] FlKeyboardManagerTest.DisposeWithUnresolvedPends
[       OK ] FlKeyboardManagerTest.DisposeWithUnresolvedPends (0 ms)
[ RUN      ] FlKeyboardManagerTest.TextInputPluginReturnsTrue
(process:41450): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
(process:41450): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed
*** Error in `/tmp/clean_engine/src/out/host_debug_unopt/exe.unstripped/flutter_linux_unittests': double free or corruption (out): 0x00007ffd86de3080 ***
```

I'm not sure how this change could introduce that, but perhaps run it through valgrind and see if it's causing any issues?

**Comment by robert-ancell** [comment]
Is this ultimately a GTK bug that should be filed upstream? Otherwise the change looks hacky, but appropriate if required and the comment is there to indicate why it's done.

**Comment by wmww** [comment]
Sorry for the delay. I can repro the test failure locally, will investigate it. It's unclear to me if it would be considered a bug in GTK or not. It's definitely a quark, but the effects are minor and it doesn't seem other projects are effected by it so if we can work around the problem that will probably be easier than trying to get it fixed.

**Comment by wmww** [comment]
I'm not sure why setting `GTK_IM_MODULE` is needed in the tests. Perhaps because there's no X11 or Wayland display? That seems to fix things through.

**Comment by cbracken** [comment]
> I'm not sure why setting GTK_IM_MODULE is needed in the tests. Perhaps because there's no X11 or Wayland display? That seems to fix things through.

@wmww Also not sure, but I use IMEs pretty heavily and have had multiple issues with crashes (in non-Flutter apps) when GTK_IM_MODULE is not set. I don't remember the full details, but for example, in some troubleshooting notes-to-self I keep, I have a note that `dmenu` will crash if `XMODIFIERS` is set but not `GTK_IM_MODULE` or `QT_IM_MODULE`. This seems to be the case on both Linux and FreeBSD, at least.

**Review by cbracken — COMMENTED** [review]
This seems reasonable. Is there an easy way to add a test to check if the onscreen keyboard comes up? 

If not (e.g. requires dependencies to be installed on our bots), it's probably a good candidate to add here https://github.com/flutter/flutter/issues/102101.

**Comment by cbracken** [comment]
@wmww did you determine whether this is an upstream issue, or whether this patch is something you'd like to move forward with as-is? 

Looks like this might need a rebase to tip of tree, but like @robert-ancell mentioned, while the workaround is a bit unfortunate, you've documented it in the comment. If not, shall we close out the PR?

**Comment by wmww** [comment]
I think trying to get the problem recognized and fixed upstream would be challenging and probably not worth it. I'm not sure how it would be tested.

**Review by cbracken — APPROVED** [review]
lgtm!

**Pull request merged**
