### PR TITLE
Move subprocess.run to popen.

### PR DESCRIPTION
**Pull request by godofredoc**
Turns out subprocess.run is available only after 3.5 and it is failing in our bots.

Bug: https://github.com/flutter/flutter/issues/81855

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ricardoamador** [comment]
Is this necessary if we are still waiting for Popen to finish? If I understand correctly the benefit of Popen would be that we could do other work asynchronously instead vs waiting for run to finish.

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by godofredoc** [comment]
> g for Popen to finish? If I understand correctly the benefit of Popen would be that we could do other work asynchronously instead vs waiting for run to finish.

This command used to use check_call but I updated it to subprocess.run to be able to print stdout and stderr but it turns out that the python version used in the bots is <3.5.

In this case we are using popen only to be able to capture stderr and stdout in a way that is compatible with different versions of python.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Pull request merged**
