### PR TITLE
Reland "ensure we do not double publish to CIPD #19724"

### PR DESCRIPTION
**Pull request by christopherfujino**
This was originally landed in #19724 but was reverted because I forgot to `import re` in the `tools/fuchsia/merge_and_upload_debug_symbols.py` script.

### CODE REVIEW

**Comment by christopherfujino** [comment]
> LGTM, I will attempt to write a test that dry runs this script.

That would be great :). I can wait on landing this, as I already landed a recipe change that should safeguard this script from being run twice. I only wanted to land this as a backup, in case later someone copy & pastes this code.

**Comment by chinmaygarde** [comment]
> I will attempt to write a test that dry runs this script.

@iskakaushik Can we do this in another patch and land this now? Lets rebase and re-run the presubmits.

**Comment by christopherfujino** [comment]
> > I will attempt to write a test that dry runs this script.
> 
> @iskakaushik Can we do this in another patch and land this now? Lets rebase and re-run the presubmits.

I'll rebase now.

**Comment by zanderso** [comment]
@christopherfujino What is the status of this PR?

**Comment by christopherfujino** [comment]
> @christopherfujino What is the status of this PR?

thanks for the ping, merged.

**Pull request merged**
