### PR TITLE
[web] Change canvas sibling transforms to 3d with z=0 to get around canvas rendering bug.

### PR DESCRIPTION
**Pull request by ferhatb**
Reproducable in pie chart of gallery/rally example.

### CODE REVIEW

**Comment by tbodt** [comment]
This makes text rendering look much much worse on non-HiDPI displays. flutter/flutter#47443

**Comment by yjbanov** [comment]
@tbodt I think the pixelation issue predates this change. I deduplicated some of the reported issues into https://github.com/flutter/flutter/issues/32274.

**Comment by tbodt** [comment]
I assumed it was this commit that caused the problem since `git blame` points to this as the source of the only instance of `translate3d` in the codebase. In fairness, there are more causes of blurry text than `translate3d`.

**Comment by yjbanov** [comment]
Ah yeah, I wouldn't be surprised if `translate3d` had such an effect. My current working theory is that it's canvas pixel to device pixel misalignment, but I'll keep your suggestion in mind if that doesn't work.

**Pull request merged**
