### PR TITLE
load default splash screen when not init with engine

### PR DESCRIPTION
**Pull request by dnfield**
This fixes a regression for regular flutter apps caused by #6883.

Fixes https://github.com/flutter/flutter/issues/24563

### CODE REVIEW

**Comment by xster** [comment]
LGTM

**Comment by Hixie** [comment]
test?

**Comment by dnfield** [comment]
I'm not really sure how we could best test this.  We don't have any facilities for running Objective C tests in the engine right now.  I started some in https://github.com/flutter/ios_add2app - been talking with @cbracken about how we might be able to get those into the engine repo.

**Comment by dnfield** [comment]
If we could run XCTests, for example, we could assert that a FlutterViewController has a non-nil splash screen for a flutter tool created project.

**Comment by jamesderlin** [comment]
This change looks fine to me, but I thought that #6883 was intentionally a breaking change; you wanted people to opt-in to using the default splash screen.

**Comment by dnfield** [comment]
@jamesderlin it was only intended to be breaking for add2app cases, not for "regular" flutter apps.

**Pull request merged**
