### PR TITLE
Roll Skia verson to c10ebe60d464cc2eec3b58bf8cedb4fe0be05d0e

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
@chinmaygarde @brianosman @Hixie 
This is what a pull request for https://bugs.chromium.org/p/skia/issues/detail?id=7730 would look like.

**Comment by rmistry** [comment]
I can't seem to add any reviewers though.

**Comment by Hixie** [comment]
We don't generally use the "reviewers" feature anyway, don't worry. :-)

**Comment by Hixie** [comment]
LGTM

**Pull request closed without merging**
