### PR TITLE
[web] Migrate EventListener's to JS types.

### PR DESCRIPTION
**Pull request by joshualitt**

### CODE REVIEW

**Comment by joshualitt** [comment]
@eyebrowsoffire ptal, @mdebbar @ditman please feel free to review if you like.

This one is kind of a fun one, and I think this is the best pattern for functions moving forward. It gives us the best of both worlds, type safety and sane JS semantics.

**Comment by joshualitt** [comment]
Oh please diff against commit 1, I still need to land the canvaskit changes.

**Comment by joshualitt** [comment]
@eyebrowsoffire okay, ptal. this is ready to go.

**Review by eyebrowsoffire — APPROVED** [review]
LGTM!

**Comment by jonahwilliams** [comment]
Not sure why exactly,  but it looks like a CK benchmark improved with this change:

https://flutter-flutter-perf.skia.org/e/?begin=1680623005&end=1680647804&keys=X06a06e2bf07a15a2943be1b7a5201a6c&selected=commit%3D34176%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Ddraw_rect.canvaskit.drawFrameDuration.outlierRatio%252Ctest%253Dweb_benchmarks_canvaskit%252C&xbaroffset=34176

**Comment by mdebbar** [comment]
@jonahwilliams I know this is confusing, but the chart you linked to is `.outlierRatio`. We run each web benchmark many times and exclude outliers before calculating the real `.average`.

Here's the real average for the benchmark, and it remained stable before and after this PR:

https://flutter-flutter-perf.skia.org/e/?begin=1680630613&end=1680717013&queries=sub_result%3Ddraw_rect.canvaskit.drawFrameDuration.average&requestType=0&selected=commit%3D34176%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Ddraw_rect.canvaskit.drawFrameDuration.average%252Ctest%253Dweb_benchmarks_canvaskit%252C

**Pull request merged**
