### PR TITLE
[Impeller] Fix alpha management issues for advanced blends.

### PR DESCRIPTION
**Pull request by bdero**
Resolves https://github.com/flutter/flutter/issues/140970.

The issue is easy to miss in the goldens if you don't know what to look for, but it was always present in one way or another. In the "before" image below, we end up removing some of the backdrop alpha as a result of the blend, which should never happen with an advanced blend:

image

This was happening because we were lerping towards the original source alpha from the destination alpha. So in the sad smiley case, the RGB getting written to the framebuffer was exactly correct, but the alpha would end up being less than 1, which the window manager then blends against the black-initialized framebuffer.

Blending with the black background just so happened to perfectly match the appearance of the color being double-premultiplied, which is why increasing the source color's vibrancy by unpremultiplying also looks correct. But again, that only works iff the pass texture winds up being drawn to a black background, which is a rare case for offscreen passes.

Skia (Flutter documentation):
image

Impeller before:
image

Impeller after:
image

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Review by jason-simmons — APPROVED** [review]

**Comment by bdero** [comment]
This is close but the composite still isn't quite right, a subset of the advanced blends look like the output color is getting doubled up. Working on fixing it.

**Comment by bdero** [comment]
Fixed that issue and discovered a few new ones while combing through:

- **ColorDodge:** CPU difference.
- **ColorBurn:** CPU & Skia diffference, weird artifacts, src drawing over white.
- **Saturation:** Skia difference, vertical strips look more pronounced, bird tail outline yellow instead of pink.
- **Color:** Skia difference, vertical strips look more pronounced.
- **Luminosity:** Skia difference, vertical strips are leaking through color from the source image.

Investigating those now. The CPU mismatches need to be fixed now because they need to exactly match up otherwise there may be color jumps when the clear color optimization kicks in. But I think the saturation/color/luminosity differences with Skia are preexisting. Pretty sure I know what's going on there though.

**Comment by bdero** [comment]
Okay figured out the cause of the CPU differences for ColorDodge/ColorBurn. Problem was CPU-side.

**Comment by bdero** [comment]
The remaining issues w.r.t. the appearance of the source image vertical strips are fixed!

**Pull request merged**
