### PR TITLE
[Impeller] one aiks context per app.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Hoist the content context up to the ios_surface so that overlay layers don't recreate a bunch of expensive machinery. 

Fixes https://github.com/flutter/flutter/issues/154836

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I'm expecting a test to fail and then I'll update that test.

**Review by gaaclarke — COMMENTED** [review]
This seems to make avoiding making a content context easier but it doesn't stop someone from doing it, right?

Shouldn't we be doing something like making the AiksContext constructor private (with friend access to the one spot we want to make them)?  Or having a debug runtime check to make sure we don't make AiksContexts?

**Comment by jonahwilliams** [comment]
Who do we need to stop from doing it? its our own internal API.

**Comment by gaaclarke** [comment]
> Who do we need to stop from doing it? its our own internal API.

The linked issue doesn't mention under what pretenses we were creating the extra content context.  If it was our only option this should be fine, if we were erroneously doing it we'd need something like I mentioned with visibility changes and/or runtime checks.  The wording of the issue makes it sound like we were making an error and we need to "ensure" we don't do it: "Today, it is easy to create context on demand and there are are few API guardrails that prevent one from being created."

**Review by chinmaygarde — APPROVED** [review]

**Comment by matanlurey** [comment]
Reason for revert: Postsubmit turned red (clang tidy and build).

**Pull request merged**
