### PR TITLE
Format all c-like sources with clang-format

### PR DESCRIPTION
**Pull request by goderbauer**
This is in preparation of enforcing proper formatting as a presubmit check on Travis (https://github.com/flutter/engine/pull/4089).

### CODE REVIEW

**Comment by cbracken** [comment]
LGTM for the ObjC world where, we've generally been applying `clang-format` manually. 

No objection for the rest, so long as the people most affected are in favour. 
/cc @chinmaygarde, @jason-simmons, @abarth.

**Comment by jason-simmons** [comment]
LGTM

**Comment by goderbauer** [comment]
> Probably worth updating CONTRIBUTING.md.

Good idea, I added that to https://github.com/flutter/engine/pull/4089.

**Comment by goderbauer** [comment]
@Hixie Can you take a quick look at the last two commits (https://github.com/flutter/engine/pull/4088/commits/d629fa84333b439b2ab3bf62c2a38f2e136ae71b and https://github.com/flutter/engine/pull/4088/commits/248e3816c49857bcd32a5f5c6d3184122c70ad30)? Thanks!

**Pull request merged**
