### PR TITLE
Fix memory leak in FlutterDarwinExternalTextureMetal

### PR DESCRIPTION
**Pull request by xzeroplus**
Fixes:https://github.com/flutter/flutter/issues/140503

### CODE REVIEW

**Comment by knopp** [comment]
Wouldn't flushing the cache with [CVMetalTextureCacheFlush](https://developer.apple.com/documentation/corevideo/1457001-cvmetaltexturecacheflush?language=objc) work?

**Comment by xzeroplus** [comment]
@knopp It doesn't work. See issue [140503](https://github.com/flutter/flutter/issues/140503).
I found IOSurface can be released only the CVMetalTextureCache is destroyed.

**Comment by chinmaygarde** [comment]
Creating a cache per external texture is not the same as using the same cache for all textures. This would reduce cache efficiency. Not sure if the reported leak is the cache operating as expected vs. us losing a reference to the texture (thereby being unable to ever release the texture).

**Comment by xzeroplus** [comment]
@chinmaygarde There is little documentation about CVMetalTextureCache. So how to fix it?

**Comment by chinmaygarde** [comment]
I am not sure there is an issue. With enough memory pressure, the cache should perform eviction.

**Comment by jonahwilliams** [comment]
We do not think that this patch is the correct fix for the issue you've filled and so we're closing. Please feel free to continue discussion in the issue.

**Pull request closed without merging**
