### PR TITLE
[iOS][Keyboard] Reland wait vsync on UI thread and update viewport inset to avoid jitter

### PR DESCRIPTION
**Pull request by luckysmg**
*List which issues are fixed by this PR. You must list at least one issue.*
- https://github.com/flutter/flutter/issues/120555
- https://github.com/flutter/flutter/issues/130028

### New test for crash case: 
`testKeyboardAnimationWillNotCrashWhenEngineDestroyed`

### The diff with original PR:

Use `dispatch_async(dispatch_get_main_queue()` to switch to platform thread.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by luckysmg** [comment]
The diff with original PR: 

https://github.com/flutter/engine/pull/43463/commits/f515bf70ac847d4a636c25877433a5d1751a8afd

**Comment by cyanglaz** [comment]
This PR relands: https://github.com/flutter/engine/pull/42312

**Comment by delfme** [comment]
Hello @cyanglaz and @luckysmg .
It seems that we have a regression with latest master. See vid below.

https://github.com/flutter/engine/assets/53510751/a844199f-e300-44e3-b061-0e59f15aeb8d

**Comment by delfme** [comment]
I upgraded just yesterday after a few months, so I cant say when regression occurred. It was pretty smooth before.

**Pull request merged**
