### PR TITLE
Snapshots: Don't use an empty array where a NULL array is expected.

### PR DESCRIPTION
**Pull request by rmacnak-google**
Fixes dart-lang/sdk#28504

### CODE REVIEW

**Comment by rmacnak-google** [comment]
@Hixie @jason-simmons

**Comment by eseidelGoogle** [comment]
Do we have a test which covers this?  Unclear to me if this was caught by a test or reports from the wild.

**Comment by rmacnak-google** [comment]
This was discovered manually. The error occurred when using hot reload (and likely would have occurred using some of Observatory's heap tools as well).

**Comment by eseidelGoogle** [comment]
Would love to figure out if we can catch this class of error in some way in the future to best ensure confidence in our releases. :)  Thanks again for the fix!

**Comment by abarth** [comment]
We would need to test hot-reload in an unoptimized build

**Pull request merged**
