### PR TITLE
Made opaque wide gamut images take up 32 bits per pixel

### PR DESCRIPTION
**Pull request by gaaclarke**
issue: https://github.com/flutter/flutter/issues/117182

Required skia cls: 
 * https://skia-review.googlesource.com/c/skia/+/645637
 * https://skia-review.googlesource.com/c/skia/+/647196

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
The following patch was still needed in skia to make this work:
```diff
--- a/src/codec/SkCodec.cpp
+++ b/src/codec/SkCodec.cpp
@@ -243,6 +243,7 @@ bool SkCodec::conversionSupported(const SkImageInfo& dst, bool srcIsOpaque, bool
         case kBGRA_8888_SkColorType:
         case kRGBA_F16_SkColorType:
             return true;
+        case kBGR_101010x_XR_SkColorType:
         case kRGB_565_SkColorType:
             return srcIsOpaque;
         case kGray_8_SkColorType:
```

**Comment by gaaclarke** [comment]
https://skia-review.googlesource.com/c/skia/+/647196 added to make last change

**Review by jonahwilliams — APPROVED** [review]
LGTM

Seems fine to me but I would defer to @chinmaygarde on reviewing this too?

**Comment by gaaclarke** [comment]
> LGTM
> 
> Seems fine to me but I would defer to @chinmaygarde on reviewing this too?

Brandon or Dan would have more context on this PR if you have a specific concern.   I chose you to review it since it seemed straight forward and to give them a break.  Let me know what you are thinking, I'd rather not bug Chinmay unless we have a good reason since he has a lot on his plate.

**Review by chinmaygarde — APPROVED** [review]

**Pull request merged**
