### PR TITLE
[icu] Upgrade the ICU library to the same commit used by Chromium latest

### PR DESCRIPTION
**Pull request by filmil**
## Use case

This change is similar to https://github.com/flutter/flutter/issues/82728.  We are using a more recent Chromium ICU fork commit.

See for reference: https://chromium.googlesource.com/chromium/deps/icu

Flutter needs to use a reasonably recent version of the ICU library. The Chromium's fork of ICU, which is in use in Flutter as well, has taken in a few updates since the initial 69.1 release.  This is a request to bring them in by updating ICU library version in the `DEPS` file to https://chromium.googlesource.com/chromium/deps/icu/+/2a822c5626ab1ed40366758e4740b4f0ea40237d, which is the current HEAD of the `main` branch in Chromium's ICU library fork.

## Proposal

Update the DEPS file in github.com/flutter/engine to use the commit ID `2a822c5626ab1ed40366758e4740b4f0ea40237d`.

This is the same commit ID as used by Chromium M93, making it easier to share the ICU data on systems where it is possible to deduplicate identical libraries, such as Fuchsia.

Fixes: #flutter/flutter/87073

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by filmil** [comment]
@jason-simmons Please take a look when able; or delegate to someone who can.

If approved, I would appreciate help to merge - I do not have commit rights.

**Comment by filmil** [comment]
Also I usually need to run the checks first, and wait for the license checks to give me a report in order to update.
Running license checks locally was a confusing process, so I try to use the existing "official" infra for results.

**Comment by filmil** [comment]
@jason-simmons The "Linux Unopt" builder failed, but I am not allowed to see the logs: https://github.com/flutter/engine/pull/27717/checks?check_run_id=3166226584

Is this expected?  On prior changes I was able to see the failure logs.

**Comment by jason-simmons** [comment]
"Linux Unopt" failed because of the license script.

The CI check logs should be publicly accessible (I can see them from an incognito browser).

Try this direct link to the license script output on LUCI:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8840607588780875904/+/u/licenses_check/stdout

**Comment by filmil** [comment]
@jason-simmons Thank you, I found the link.  It was the greyed-out text which wasn't an obvious hyperlink.

**Comment by filmil** [comment]
@jason-simmons This is now all passing, can you review / approve / merge as appropriate, please?

**Comment by jason-simmons** [comment]
LGTM, but this needs to be rebased again on the latest `ci/licenses_golden/licenses_third_party`

licenses_third_party is a moving target because Dart->Flutter rolls are always happening.

**Comment by filmil** [comment]
Noted - I'll try to make the update in a tight loop so as to get the change in before Dart rolls mess things up.
Will need to happen tomorrow, though.

**Comment by filmil** [comment]
@jason-simmons Would you be able to merge on short notice when/if this presubmit check run completes, please? I'll ping you when/if that happens.

**Comment by filmil** [comment]
FYI this is now rebased at whatever HEAD was ~15 mins ago...

**Pull request merged**
