### PR TITLE
Update ICU from 0.9.40 to 1.3.0 from the Fuchsia repository.

### PR DESCRIPTION
**Pull request by chinmaygarde**
The size of icudtl.dat has grown from 10.2 megs to 13.8.

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Needs https://github.com/flutter/buildroot/pull/65

**Comment by eseidelGoogle** [comment]
@chinmaygarde mentioned before that it would be trivial to cut the size of our ICU by generating it with different flags.  Given that this is adding 3.5 MB to our uncompressed size, seems like it might be worth considering that at this time?

**Comment by Hixie** [comment]
@chinmay Please reopen this PR when you are ready to land it. Thanks! (I'm just cleaning out our review queue and this one has been open with no activity for more than a week.)

**Pull request closed without merging**
