### PR TITLE
Cherry-picks for 1.9.1

### PR DESCRIPTION
**Pull request by tvolkert**
1ef83b8 Upgrade to tflite_native@0.2.2 by Ari Aye
e9bad9b Upgrade tflite_native to v0.2.1 for silent tflite dynamic library by Ari Aye
7c7d369 Check for null tokens while walking backward from cursor by lambdabaa

### CODE REVIEW

**Comment by tvolkert** [comment]
@athomas

**Comment by dnfield** [comment]
Uh - looks like Cirrus is missing some packages?

**Comment by tvolkert** [comment]
> Uh - looks like Cirrus is missing some packages?

I saw that in the last cherry-pick on a branch as well (e.g. https://cirrus-ci.com/task/5946788843880448).  I don't see anything in the Cirrus config for those jobs that should be susceptible to differences in building on a branch vs master.  Thoughts?

**Comment by dnfield** [comment]
Not sure - it's probably fine to just land it, the LUCI builders are the ones that really matter for these things anyway.

**Pull request merged**
