### PR TITLE
[CP][Android] Fix the issue of blank or frozen pages in shared engine scenarios #50947

### PR DESCRIPTION
**Pull request by mdnht**
Cherry picked https://github.com/flutter/engine/commit/f9a34ae0b14f4dfd6a8cf9181ab5db3c14c0246d
From [[Android] Fix the issue of blank or frozen pages in shared engine scenarios](https://github.com/flutter/engine/pull/50947)

### CODE REVIEW

**Comment by mdnht** [comment]
I have fixed CI check failure.
It was because of importing `io.flutter.Build.API_LEVELS` that is not yet implemented in flutter 3.19.
https://github.com/flutter/engine/pull/52387#:~:text=%E2%80%A6-,3097bd3,-%E2%80%A6tly.

**Comment by reidbaker** [comment]
It might be too late to CP into 3.19. I am double checking with the release manager now. 
Also this will need a CP bug. https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Comment by mdnht** [comment]
@reidbaker @itsjustkevin 
If it's too late for 3.19, do I need to wait next release for this bug to be fixed? (3.20?)

We have a product using add2App app using shared engine for both android and ios, and because of Apple Privacy Manifest requirement  Flutter needs to be 3.19 and above.
But when we upgrade Flutter to 3.19, android users will face this issue. 
As Apple's requirement is already effective, we would like to resolve this issue as soon as possible.

**Comment by reidbaker** [comment]
I talked to the release manager and it is too late to accepts 3.19 cherry picks but I do appreciate you trying to land this. 
Your options are to build your app with a custom engine that contains this cherry pick or to wait for the 3.22 release which is the next stable and is scheduled to be released in the next week or 2.

**Pull request closed without merging**
