### PR TITLE
[Win32, Keyboard] Fix text input after pressing Enter or Ctrl-Digit 

### PR DESCRIPTION
**Pull request by dkwingsmt**
Fix https://github.com/flutter/flutter/issues/97706.

This problem happened because the keyboard manager now pushes all text into a queue, and only dispatches texts that are ready from the front, which means if any text is left un-ready, no text will ever be dispatched any more. However, enter and Ctrl-digit key presses insert some non-printable texts, which are skipped but not removed during the `OnKey`'s response callback. 

This PR fixes this issue by moving the filtering to before `OnKey`, therefore these non-printable texts will never be pushed into the queue.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by selvam920** [comment]
hi, due to this after press enter key other keys not working in textfield, pls revert this

**Comment by dkwingsmt** [comment]
@selvam920 Are you talking about https://github.com/flutter/flutter/issues/97706? I'm aware and this PR was supposed to fix that issue. This fix has not been rolled into the master branch of framework yet. Unless you're compiling the latest main branch of the engine by yourself, please wait until the roll is done (https://github.com/flutter/flutter/pull/97757 is merged) and try again.

**Comment by selvam920** [comment]
ok, i will wait

**Comment by selvam920** [comment]
it's working now

**Comment by dkwingsmt** [comment]
@selvam920 Glad to know, thank you for the update!

**Comment by selvam920** [comment]
Will this resolve barcode scanner problem?

**Comment by dkwingsmt** [comment]
I would assume the barcode scanner problem has been resolved (I've closed the issue.) Let me know it persists or has any other problems.

**Comment by vinicios-cervantes** [comment]
@dkwingsmt I made some tests, and barcode scanner is working, thanks.
Any chance of this going to stable soon?

**Comment by dkwingsmt** [comment]
Likely in a few months since this is based on some major changes and can not be cherrypicked.

**Comment by vinicios-cervantes** [comment]
Ok, thanks again

**Comment by selvam920** [comment]
When can we except this changes to beta or stable?

**Comment by dkwingsmt** [comment]
Please check out https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta .

**Pull request merged**
