### PR TITLE
Start of refactor of Android for pbuffer

### PR DESCRIPTION
**Pull request by dnfield**
This is a minor cleanup of the constructors in `PlatformViewAndroid` in preparation for a fix for https://github.com/flutter/flutter/issues/73675. For that fix, the Android platform view will need to keep a pbuffer surface around so that Skia will be able to use it when rasterizing cross context images in the background.

This PR does not introduce any changes at runtime, and should be covered as long as existing tests pass and it compiles :)

I mainly want to split it out from what will be a slightly larger PR that adds a pbuffer to avoid confusion.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by chinmaygarde** [comment]
@dnfield Are you still working on this or is this ready for review?

**Comment by dnfield** [comment]
This is ready for review - it's just a small refactor so the constructors all end up flowing through one path.

**Review by chinmaygarde — APPROVED** [review]

**Review by blasten — APPROVED** [review]
sorry for the wait. LGTM

**Pull request merged**
