### PR TITLE
Teach web_sdk/sdk_rewritter.dart how to write a stamp file.

### PR DESCRIPTION
**Pull request by eseidel**
## Description

Previously BUILD.gn expected a stamp, but one was never generated.
This meant that the null build for the engine was always
rebuilding the 7 targets for the web_sdk.

This adds a --stamp option to sdk_rewritter and changes the
BUILD.gn file to use it, following the pattern for --stamp
options seen throughout the chromium codebase.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/59720

## Tests

There were no existing tests for sdk_rewritter.dart, and I didn't write any. :(

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [X] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation.
- [X] All existing and new tests are passing.
- [X] I am willing to follow-up on review comments in a timely manner.
(Realistically, please just revert if this breaks.)

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by eseidel** [comment]
I welcome pointers on how scripts like this should be tests (happy to write them).  @jonahwilliams @nturgut

**Comment by jonahwilliams** [comment]
If it builds...

**Comment by eseidel** [comment]
I thought we had a fancy commit queue now?  https://github.com/flutter/flutter/wiki/Tree-hygiene#landing-a-patch doesn't mention such.

Is there a button I have to press to get it into the landing queue (assuming such exists)?  Thanks!

**Comment by jonahwilliams** [comment]
I think it is automatic now - the github status now include LUCI checks automagically!

**Comment by eseidel** [comment]
Is there more I need to do?

**Comment by jonahwilliams** [comment]
you gotta press submit :)

**Comment by eseidel** [comment]
This normal-human account doesn't have any privileges (which is part of the point).  Is there no way to get into the submission queue without them (e.g. for someone else to put this in the queue)?

I just see a "Only those with write access to this repository can merge pull requests".

**Comment by jonahwilliams** [comment]
I guess I gotta put the label on it! It should get merged whenever the bot feels like it

**Pull request merged**
