### PR TITLE
Keep ActivityPluginBinding.getLifecycle()

### PR DESCRIPTION
**Pull request by blasten**
Fixes https://github.com/flutter/flutter/issues/48622

cc @amirh

### CODE REVIEW

**Comment by dnfield** [comment]
I'm curious about how tests missed this - do the plugin build tests not cover building the plugin into an app?

**Comment by dnfield** [comment]
Ahh I figured it out. It's because it isn't a compile time issue, it's a runtime issue - because reflection.

We should probably avoid reflection in plugins... :\

**Comment by blasten** [comment]
+1.  Since this is affecting folks on stable, we probably need to remove the reflection.

**Comment by dnfield** [comment]
Do we still need this given the change upstream in android_lifecycle_plugin?

**Comment by amirh** [comment]
> We should probably avoid reflection in plugins... :\

+1

In this specific case folks wanted to publish a plugin using this method before it it made it to the stable version so we had no way but using reflection.

I do think we avoid this change now that the plugin is using this method statically.

**Comment by dnfield** [comment]
Closing this as fixed in plugins - if we need to reopen it we certainly can.

**Pull request closed without merging**
