### PR TITLE
Default `--enable-impeller-*` to `True`.

### PR DESCRIPTION
**Pull request by matanlurey**
Suggested by @chinmaygarde as a first-step towards https://github.com/flutter/flutter/issues/142725.

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
lgtm!  i'll keep my fingers crossed it gets through CI

**Review by chinmaygarde — APPROVED** [review]

**Comment by gaaclarke** [comment]
I mean if it doesn't go through it's going to be something like `impeller_enable_vulkan = !is_win()`.

**Comment by chinmaygarde** [comment]
Oh second thought, this might be more inclusive than we want. Won't this enable Vulkan and OpenGL ES on stuff like Fuchsia because [this check is overriden](https://github.com/flutter/engine/blob/abb51c48e26110060d591ed8341bf8bf7987e7ea/impeller/tools/impeller.gni#L21)? It might be safer to get rid of the ./tools/gn flags and add `is_mac` to the conditionals.

**Comment by matanlurey** [comment]
Want me to see what CI does, or should I make the changes suggested? :)

**Comment by matanlurey** [comment]
There is at least one failing validation layer:

```txt
[ RUN      ] Play/RuntimeStageTest.CanCreatePipelineFromRuntimeStage/Vulkan
[INFO:flutter/impeller/renderer/backend/vulkan/capabilities_vk.cc(51)] Vulkan validations are enabled.
[INFO:flutter/impeller/renderer/backend/vulkan/capabilities_vk.cc(51)] Vulkan validations are enabled.
[FATAL:flutter/impeller/base/validation.cc(47)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
--- Vulkan Debug Report  ----------------------------------------
|                Severity: Error
|                    Type: { Validation }
|                 ID Name: VUID-VkGraphicsPipelineCreateInfo-layout-07988
|               ID Number: 559874765
|       Queue Breadcrumbs: [NONE]
|  CMD Buffer Breadcrumbs: [NONE]
|         Related Objects: ShaderModule [120946279055470] [Shader ink_sparkle_fragment_main], PipelineLayout [124244813938801] [UNNAMED]
|                 Trigger: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-07988 ] Object 0: handle = 0x6e000000006e, name = Shader ink_sparkle_fragment_main, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x710000000071, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x215f02cd | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1] SPIR-V (VK_SHADER_STAGE_FRAGMENT_BIT) uses descriptor slot [Set 0 Binding 64] (type `VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER`) but was not declared in the pipeline layout. The Vulkan spec states: If a resource variables is declared in a shader, a descriptor slot in layout must match the shader stage (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-07988)
-----------------------------------------------------------------
```

@chinmaygarde or @gaaclarke were either of you looking into this one already?

**Comment by chinmaygarde** [comment]
No. But this one looks easy to fix. Can you file a bug for it with a skip here so you are unblocked? I'll patch it.

**Comment by matanlurey** [comment]
Abandoning this change.

**Comment by gaaclarke** [comment]
> Abandoning this change.

Because getting CI happy is a longer commitment than we expected?  Looks like turning this on for mac by default was causing some validation errors?

**Comment by matanlurey** [comment]
> > Abandoning this change.
> 
> Because getting CI happy is a longer commitment than we expected? Looks like turning this on for mac by default was causing some validation errors?

It's not just validation errors, it's a problem of the Mac builds assuming backends exist that don't.

**Pull request closed without merging**
