### PR TITLE
Update invocation of create_snapshot_bin.py

### PR DESCRIPTION
**Pull request by jamesr**
This applies commit 88441bfc0f712ad451784851bfcf0b0cc418ad75 from the
skia_rev_130a118cc68f8f9973e9572356011de378463fea branch to master so
master works in the Fuchsia build again.

### CODE REVIEW

**Comment by jamesr** [comment]
@abarth @rmacnak-google

**Comment by rmacnak-google** [comment]
The Dart revision in DEPS needs to be updated for the non-Fuchsia builds to compatibility with this change.

**Comment by jamesr** [comment]
Hmm, so Fuchsia builds are using a newer rev of Dart than non-Fuchsia Flutter builds, and there's an incompatible API change in the Dart scripting between the two revisions?  That seems bad.

**Comment by abarth** [comment]
Correct.  Fuchsia surfs head.  Standalone Flutter uses pinned depedencies.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
