### PR TITLE
Make git diff range more robust in format.sh

### PR DESCRIPTION
**Pull request by liyuqian**
The new approach follows https://github.com/flutter/flutter/pull/19412 which is suggested by Cirrus in https://github.com/cirruslabs/cirrus-ci-docs/issues/17

### CODE REVIEW

**Comment by liyuqian** [comment]
@Hixie : this should fix your Travis problem in https://github.com/flutter/engine/pull/5810 and I think that this modification is useful no matter whether we use Travis or Cirrus.

**Comment by liyuqian** [comment]
@gspencergoog : I want to drop the `--fork-point` as it seems to be unnecessary, and sometimes causing some troubles. What's your opinion?

**Comment by gspencergoog** [comment]
In what cases does it cause problems?

**Comment by liyuqian** [comment]
@gspencergoog : when my local branch HEAD is based on a commit earlier than FETCH_HEAD, `git merge-base --forkpoint FETCH_HEAD HEAD` returns empty while `git merge-base FETCH_HEAD HEAD` returns the correct common ancestor.

**Comment by gspencergoog** [comment]
Oh, I see.  Maybe we should try with --fork-point first, and fall back to plain merge-base if it fails.

Only because --fork-point seems to be more conservative about getting the "right" commit.

We could try just leaving it off and see if we get any odd failures...

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
