### PR TITLE
Unify timer implementation between Flutter and Mojo embedders

### PR DESCRIPTION
**Pull request by johnmccutchan**
- Use the same timer implementation as Mojo
- Remove old timer implementation

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@abarth

**Comment by abarth** [comment]
LGTM

**Comment by johnmccutchan** [comment]
@abarth PTAL- I had to add some new suppressions to the travis analyze script (suppressing warnings around symbols from dart:mojo.internal and dart:_internal) and I removed the unused 'dart:async' import in dart_ui.dart.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
