### PR TITLE
[Linux] fix and test light vs. dark theme detection

### PR DESCRIPTION
**Pull request by jpnurmi**
This PR replaces the unreliable (and untestable) window text color
-based theme detection with the simpler alternative proposed in
flutter/engine#25535 to check for a "-dark" suffix in the theme name,
which is used by convention in dark GTK theme names (Yaru vs. Yaru-dark,
Adwaita vs. Adwaita-dark, Pop vs. Pop-dark, ...).

Partial fix to: flutter/flutter#101438

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

# Before

Personally, I was able to reproduce the issue in a Pop!_OS 20.04 VM
- Detects correct theme on startup
- First theme change does nothing
- Consequent theme changes detect the opposite theme

https://user-images.githubusercontent.com/140617/163995599-b37326f4-4f81-4bbb-b869-273e9b88afbe.mp4

# After

Same VM with the fix applied

https://user-images.githubusercontent.com/140617/163995689-58664e09-d952-4183-a2f3-5deae8f48e38.mp4

### CODE REVIEW

**Comment by jpnurmi** [comment]
@robert-ancell and @cbracken, this is a spin-off of #32456 that I had trouble adding tests for. I have done some refactoring around `FlSettingsPlugin` to make it possible to test these fixes against the different GSettings desktop schemas in Ubuntu 20.04 vs. Ubuntu 22.04. The latter has GNOME 42 that includes the new [dark style preference](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference).

P.S. I have included it all here for now for feedback but if you think the changes look good in principle, I can start splitting this into smaller PRs.

**Comment by jpnurmi** [comment]
These changes would also lay the foundations for implementing [accessibility features](https://github.com/flutter/engine/blob/6e9953c743365c676289e605dda4e1ddcdf07f24/shell/platform/embedder/embedder.h#L82-L101) for Linux, to make Flutter respect the high-contrast and disabled animations accessibility settings in GNOME.

**Comment by robert-ancell** [comment]
Changes make sense to me - let's split into smaller PRs.

**Comment by jpnurmi** [comment]
I started splitting off some changes but I didn't realize the bot would get mad at me for not including tests when adding code to testing/.

- https://github.com/flutter/engine/pull/32649
- https://github.com/flutter/engine/pull/32650
- https://github.com/flutter/engine/pull/32652

**Comment by jpnurmi** [comment]
I've rebased the remaining commits and left out the GNOME 42 color-scheme changes from this. Let's fix and test the "legacy" theme detection first.

**Review by robert-ancell — APPROVED** [review]
LGTM!

**Review by cbracken — APPROVED** [review]

**Pull request merged**
