### PR TITLE
Fix Flaky crash issue.

### PR DESCRIPTION
**Pull request by guoguo338**
This PR is to fix issue https://github.com/flutter/flutter/issues/113468. 

Engine crashed here: https://github.com/flutter/engine/blob/f6aef9b30f92f67ffd31e88793fbcc6e692530c5/flow/raster_cache.cc#L173

for normal case, the Life cycle of RasterCache methods is like 1. Preroll stage->2. Paint stage->3. RasterCache:EndFrame, 
in platform-view case, as the 2. Paint stage is bypassed, the action for evict cache images in Paint Stage is also bypassed. Such logic leads the code for "FML_DCHECK(entry.encountered_this_frame)" check failed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by flar** [comment]
The change looks harmless for the regular flow and I suppose it avoids the case where we don't end up calling Paint, but we do end up updating the metrics. The only issue I have, and I don't have a deep understanding of why we sometimes call Preroll without Paint, is whether or not there are cases where we might call Preroll and not call Paint, but in a situation where we'd like the cache to not be evicted.

Looking for comments from @iskakaushik and @dnfield

**Comment by dnfield** [comment]
I think this makes sense -  we can end up returning early in cases where the platform view embedder told us to retry or resubmit.

**Comment by dnfield** [comment]
Is there some way we can test this? For example, write a test where you inject a view embedder that says to resubmit and make sure we do the right thing?

**Comment by flar** [comment]
> I think this makes sense - we can end up returning early in cases where the platform view embedder told us to retry or resubmit.

But is that a case where we want to dump the cache, or do we want to just back out of all of the cache operations we had set up and try them again? In the suggested fix it will clean up the cache based on a layer tree that might never be rendered...?

**Comment by dnfield** [comment]
> But is that a case where we want to dump the cache, or do we want to just back out of all of the cache operations we had set up and try them again? In the suggested fix it will clean up the cache based on a layer tree that might never be rendered...?

kResubmitFrame and kSkipAndRetryFrame are documented as saying that the thread configuration has changed. I don't think the images we use in the raster cache are thread safe. I'm not clear on whether the "dump the cache" bits here dump those images or just dump statistics.

**Comment by flar** [comment]
> > But is that a case where we want to dump the cache, or do we want to just back out of all of the cache operations we had set up and try them again? In the suggested fix it will clean up the cache based on a layer tree that might never be rendered...?
> 
> kResubmitFrame and kSkipAndRetryFrame are documented as saying that the thread configuration has changed. I don't think the images we use in the raster cache are thread safe. I'm not clear on whether the "dump the cache" bits here dump those images or just dump statistics.

In that case we'd need something quite a bit stronger than EvictUnused. We'd need EvictAllWithExtremePrejudice.

Perhaps those conditions result in a new cache being created and the old one is cleared?

**Comment by guoguo338** [comment]
> 

Is there any reference test case? I was trying to write some but don't know how.

**Comment by guoguo338** [comment]
> Is there some way we can test this? For example, write a test where you inject a view embedder that says to resubmit and make sure we do the right thing?

Is there any existing reference test case? I tried write some test cases but failed.

**Comment by flar** [comment]
> > Is there some way we can test this? For example, write a test where you inject a view embedder that says to resubmit and make sure we do the right thing?
> 
> Is there any existing reference test case? I tried write some test cases but failed.

I don't know how to construct a use case that triggers the various kDoSomethingWithTheFrame return codes. Perhaps @dnfield knows what underlying mechanisms trigger them?

**Comment by chinmaygarde** [comment]
Dan is OOO for a bit. If we cannot make progress on the test, perhaps we should mark this WIP?

**Comment by flar** [comment]
@dnfield I think we were waiting on some input from you on how to write a test case that can catch this?

**Comment by chinmaygarde** [comment]
Ping @dnfield

**Comment by dnfield** [comment]
At the end of the day, we just want a test case that would fail without this change and pass with it. The change itself makes sense.

It would be good enough to have a test layer that somehow causes cache entries to become invalid after preroll and make sure they get evicted there. We don't necessarily need a whole simulated embedder for that.

**Comment by dnfield** [comment]
(we can set aside questions about thread safety in various embedder configurations for this PR for right now is my point)

**Comment by chinmaygarde** [comment]
Closing due to lack of test and no guidance on how to write one. We can revisit this if the linked issue rises in priority.

**Pull request closed without merging**
