### PR TITLE
dart analysis of tests, cleanup

### PR DESCRIPTION
**Pull request by dnfield**
Adds analysis of Dart files in the testing/ directory to the CI script

Cleans up issues so this should pass CI.

It excludes window_hooks becuase that test pulls in a bunch of stuff from dart:ui the analyze has no idea how to handle. Really we should rework all of that so that test is not accessing private details of dart:ui (https://github.com/flutter/flutter/issues/27628)

### CODE REVIEW

**Comment by liyuqian** [comment]
Would this change be able to catch breakages to framework? Say I accidentally make a lib/ui class deprecated, and that class is only used in the framework?

**Comment by dnfield** [comment]
Not until we roll right?

**Comment by liyuqian** [comment]
Since we've already pulled all framework dart code for https://github.com/flutter/engine/blob/master/.cirrus.yml#L59 , I wonder if we can analyze those Dart code with respect to the changed engine.

**Comment by dnfield** [comment]
@liyuqian that should be possible - sorry I thought you were asking about something else.

I'm not quite addressing your bug, but it's still worth landing this.

**Comment by dnfield** [comment]
I'm not clear on why the framework tests are fialing here...

**Comment by liyuqian** [comment]
@dnfield : I believe the failure is due to a breaking change https://github.com/flutter/engine/commit/77252d2371f3341f9f3a7e3ec2eb64bfa29bf975 that needs a manual engine roll. Please rerun the test after the manual roll.

**Pull request merged**
