### PR TITLE
Additional instrumentation for tracing engine performance

### PR DESCRIPTION
**Pull request by mmclenna**
Added reporting for Paint() calls to event tracing in all layer types.  This gives better visibility into what's happening within RasterizerDirect::Draw().

### CODE REVIEW

**Comment by mmclenna** [comment]
I'm a Googler, so the CLA should be covered.

**Comment by chinmaygarde** [comment]
lgtm. @mmclenna I think the bot wants you to type in `I signed it!`.

**Comment by mmclenna** [comment]
I signed it!

**Comment by jamesr** [comment]
The CLA bot is upset because the email address in your commit does not match the address in its database.  The author in the commit is "mmclenna <mmclennan@ieee.org>" and the bot is expecting your contributions as a Googler to be made from your @google.com account.

**Comment by eseidelGoogle** [comment]
git config --global user.email nefario@google.com

You can also omit the --global if you just want to set it for the one repo.

**Pull request merged**
