### PR TITLE
Use `SkTextBlob::bounds` instead of `TextFrame::getBounds()`.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/133157.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

If our text frame bounds computation is wrong, that is going to bubble up to more places too.
Can we either 1) make impeller::TextFrame use the bounds data from the SkTextFrame 2) fix the impeller::TextFrame computation?

**Comment by matanlurey** [comment]
I'm still learning the words, so I'm not sure what difference between a `TextBlob` and a `TextFrame` is, but I'm not sure the `TextFrame` bounds are _wrong_, just potentially not appropriate in this case? Note that `blob->bounds()` is probably not the same thing as `frame->bounds()`?

**Comment by jonahwilliams** [comment]
The impeller::TextFrame is the analog of the SkTextBlob

**Comment by jonahwilliams** [comment]
(Not necessarily in this PR, FWIW)

**Comment by jonahwilliams** [comment]
Actually in general TextFrame::GetBounds is super hot, so we might want to take the SkiaBounds in the constructor and use them cached, see https://github.com/flutter/engine/pull/45131#discussion_r1306202240

**Comment by matanlurey** [comment]
Ah, sure! Filed https://github.com/flutter/flutter/issues/133388.

**Pull request merged**
