### PR TITLE
Add resetTransform in Canvas

### PR DESCRIPTION
**Pull request by yuanyan**
Fixes flutter/flutter#79859

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by yuanyan** [comment]
> @googlebot I signed it!

**Comment by chinmaygarde** [comment]
cc @Hixie @goderbauer for the new feature implementation.

**Comment by Hixie** [comment]
This would be the first API we add that lets you set state in a non-incremental fashion. Are we sure we want to do this? It's a bridge we can't uncross.

**Comment by Hixie** [comment]
I think we should carefully consider the use case before we do this. I looked at the issue but it doesn't explain why we would want to add this.

**Comment by chinmaygarde** [comment]
I want to note that `resetTransform` will not only nuke the transformation stack that may have been modified by the framework prior to the canvas being made available to the render object, it may also interfere with transformations added to the canvas by the engine to elide unnecessary render target switches. We have [been careful to render to an intermediate picture in the past](https://github.com/flutter/engine/blob/0d07e1b90b26a75b25fbe67becc3d91caffabe17/shell/platform/embedder/embedder_external_view.cc#L99) to sidestep such potential issues. But, I cannot guarantee that all the places where the engine modifies the CTM has accounted for this potential issue. That's because, prior to this patch, non-engine callers nuking the transformation stack was not possible. Exposing this to callers may lead to extremely unexpected results because the transformation being reset is not only that added by the user, but also the framework and the engine.

An alternative could be for the user to render to an intermediate picture using a picture builder. There, the default transformation is identity and the user may push and pop transformation onto the CTM as necessary for complete control over the transformation at any level. This is similar to the technique used in the engine I linked earlier to be resilient to callers potentially resetting the transformation stack.

Given the unexpected behavior possible, unexplored edge cases, and the presence of an alternative; I am against exposing this method as-is. If there are use cases that are not possible today because of the lack of the reset call, we'll need to explore alternatives.

**Comment by yuanyan** [comment]
> I want to note that `resetTransform` will not only nuke the transformation stack that may have been modified by the framework prior to the canvas being made available to the render object, it may also interfere with transformations added to the canvas by the engine to elide unnecessary render target switches. We have [been careful to render to an intermediate picture in the past](https://github.com/flutter/engine/blob/0d07e1b90b26a75b25fbe67becc3d91caffabe17/shell/platform/embedder/embedder_external_view.cc#L99) to sidestep such potential issues. But, I cannot guarantee that all the places where the engine modifies the CTM has accounted for this potential issue. That's because, prior to this patch, non-engine callers nuking the transformation stack was not possible. Exposing this to callers may lead to extremely unexpected results because the transformation being reset is not only that added by the user, but also the framework and the engine.
> 
> An alternative could be for the user to render to an intermediate picture using a picture builder. There, the default transformation is identity and the user may push and pop transformation onto the CTM as necessary for complete control over the transformation at any level. This is similar to the technique used in the engine I linked earlier to be resilient to callers potentially resetting the transformation stack.
> 
> Given the unexpected behavior possible, unexplored edge cases, and the presence of an alternative; I am against exposing this method as-is. If there are use cases that are not possible today because of the lack of the reset call, we'll need to explore alternatives.

Got it, looks export resetTransform hard to current flutter rendering pipeline.

**Comment by zanderso** [comment]
From triaging: Assuming this is stale.

**Pull request closed without merging**
