### PR TITLE
[android] Fix black and blank screen issues on the platform view page.

### PR DESCRIPTION
**Pull request by 0xZOne**
Fix issues:
[#88558](https://github.com/flutter/flutter/issues/88558)
[#88845](https://github.com/flutter/flutter/issues/88845)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making.
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by eggfly** [comment]
Maybe a solution is not setting flutterImageView and previousRenderSurface to null in `detachFromFlutterEngine()`?
```java
public void detachFromFlutterEngine() {
    Log.v(TAG, "Detaching from a FlutterEngine: " + flutterEngine);

    // ... 

    // flutterImageView = null;
    // previousRenderSurface = null;
    flutterEngine = null;
}
```
@0xZOne

**Comment by 0xZOne** [comment]
> Maybe a solution is not setting flutterImageView and previousRenderSurface to null in `detachFromFlutterEngine()`?
> 
> ```java
> public void detachFromFlutterEngine() {
>     Log.v(TAG, "Detaching from a FlutterEngine: " + flutterEngine);
> 
>     // ... 
> 
>     // flutterImageView = null;
>     // previousRenderSurface = null;
>     flutterEngine = null;
> }
> ```
> 
> @0xZOne

We need to revert |renderSurface| to |previousRenderSurface| here to avoid a black screen due to the surface missing when it attaches to the engine again.

**Review by blasten — COMMENTED** [review]
This is a good fix. However, can we add a test to `FlutterViewTest`?

One possible test is:
1. Make `renderSurface` visible for testing. (Remove private modifier).
1. Construct `FlutterView`
1. Call `convertToImageView()`
1. Verify `renderSurface` is a `FlutterImageView`
1. Call `detachFromFlutterEngine()`
1. Verify `renderSurface` is not a `FlutterImageView`

**Comment by 0xZOne** [comment]
> This is a good fix. However, can we add a test to `FlutterViewTest`?
> 
> One possible test is:
> 
> 1. Make `renderSurface` visible for testing. (Remove private modifier).
> 2. Construct `FlutterView`
> 3. Call `convertToImageView()`
> 4. Verify `renderSurface` is a `FlutterImageView`
> 5. Call `detachFromFlutterEngine()`
> 6. Verify `renderSurface` is not a `FlutterImageView`

done.

**Comment by 0xZOne** [comment]
Those tests seem interrupted by user for some reason. Can anyone help rebuild, please? thanks.

**Comment by ColdPaleLight** [comment]
> Those tests seem interrupted by user for some reason. Can anyone help rebuild, please? thanks.

Done

**Comment by 0xZOne** [comment]
Linux flutter_plugins failure is unrelated to my changes. See [#28535](https://github.com/flutter/engine/pull/28535) for details.

**Comment by chinmaygarde** [comment]
This patch needs to be rebased on ToT for the presubmits to run again please? And CC @blasten for the re-review.

**Review by blasten — APPROVED** [review]
LGTM - nicely done

**Pull request merged**
