### PR TITLE
Subtree import txt into //third_party.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I defer to others.  I approve of the idea.

**Comment by Hixie** [comment]
LGTM
LGTM
LGTM

**Comment by chinmaygarde** [comment]
@abarth: Do you have an opinion on the merge strategy for this? We definitely don't want to squash because that will nuke the history in the subdirectory. But I am not sure whether we need to merge via a merge commit or a rebase.

**Comment by abarth** [comment]
> But I am not sure whether we need to merge via a merge commit or a rebase.

I usually use merge because it's a closer model to what is happening in reality, but either works.

**Pull request merged**
