### PR TITLE
Provide a way to redo a frame.

### PR DESCRIPTION
**Pull request by Hixie**
This is a really expensive API, but some times you just need to spin the
entire frame loop twice in a frame.

There's no runaway protection here. One can come up with contrived
examples where it can legitimately run three or four times in a row, but
abuse of this API will just cripple performance...

### CODE REVIEW

**Comment by j9brown** [comment]
Whoa.  Why do we need this?

**Comment by abarth** [comment]
Let's talk this through on Monday.  Seems like a really big hammer.

**Comment by Hixie** [comment]
@j9brown Well for example some applications want to size one widget to be the size of another widget that comes later in the build tree. Which means they have to wait for layout to have run before they can configure themselves. Without this patch, the only real way to do this is to wait an entire frame before sizing that first widget. If they're trying to track each other, that means there's a whole frame's latency between the two sizes.

I'm not at all convinced this is the solution, by the way. There's better ways to do some things, for example, the mimic example could be done with a CustomPaint with a paint-time transform that looks up the other widget's layout position, and for most of the other cases, one frame latency is not actually noticeable.

The thing that made me look into this is hero animations. I need to collect up all the heroes in the new route, then animate them. But I can't do that without first building the tree. So the naïve approach would paint a frame of the final layout (maybe made invisible by putting it in a "non-painting subtree" widget or something), then find all the heroes, then rebuild the whole thing with the transitions configured to go from the old positions to the new positions. This would add a frame's latency to every transition, which is probably not hugely noticeable, but wouldn't be any less work than this patch would imply (we still rebuild everything, we just do it in two frames instead of one frame).

This is indeed a sledge hammer. I'm sure everyone would abuse the heck out of it and performance would drop like a stone in such apps.

**Comment by abarth** [comment]
One thing we could do with heros is make use of the fact that animations always put up a frame at t=0.0.  They do this to sync their clocks to the vsync timestamp.  We could collect the heros on the second frame of the animation, when t > 0.0, and not introduce any additional latency.

**Comment by Hixie** [comment]
I'm not sure I understand.

**Comment by abarth** [comment]
We should talk on Monday with a whiteboard.

**Comment by krisgiesing** [comment]
I'd like to be in that discussion, please.

**Comment by j9brown** [comment]
Curious where we landed on this.

**Comment by Hixie** [comment]
We didn't.

**Pull request closed without merging**
