### PR TITLE
Tool that audits GitHub for checks that appear to fail at a high rate

### PR DESCRIPTION
**Pull request by matanlurey**
This is just for showing my work/data exploration.

If we think this is useful enough to check-in, I'm happy to merge it (though I'm not going to bother writing tests for something that we won't use on CI).

## Example Usage

```shell
# See https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
GITHUB_TOKEN="..." \
  ./prebuilts/macos-arm64/dart-sdk/bin/dart tools/github_commit_audit/bin/main.dart \
  --repo flutter/engine \
  --max 100 \
  --exclude-label platform-web
```

... produces output such as:

```txt
...

Summary:
  - Linux Framework Smoke Tests: 56/126 (0.44)
  - Linux linux_license: 53/126 (0.42)
  - Linux linux_host_engine: 41/126 (0.33)
  - Linux Fuchsia FEMU: 41/126 (0.33)
  - Linux Web Framework tests: 23/71 (0.32)
  - Linux linux_web_engine: 39/126 (0.31)
  - Linux linux_fuchsia: 37/122 (0.30)
  - Linux linux_unopt: 38/126 (0.30)
  - Linux linux_android_emulator_tests: 20/67 (0.30)
  - Linux mac_unopt: 37/126 (0.29)
  - Mac mac_host_engine: 37/126 (0.29)
  - Windows windows_unopt: 31/126 (0.25)
  - Linux linux_android_debug_engine: 27/126 (0.21)
  - Linux linux_clang_tidy: 21/99 (0.21)
  - Windows windows_host_engine: 26/126 (0.21)
  - Mac mac_ios_engine: 20/126 (0.16)
  - Mac mac_clang_tidy: 15/103 (0.15)
  - Linux linux_android_aot_engine: 16/126 (0.13)
  - Windows windows_android_aot_engine: 15/126 (0.12)
  - Windows windows_arm_host_engine: 13/126 (0.10)
  - Linux linux_host_desktop_engine: 11/126 (0.09)
  - Linux mac_android_aot_engine: 10/126 (0.08)
  - Linux linux_arm_host_engine: 9/126 (0.07)
  - Vulnerability scanning: 0/110 (0.00)
  - triage: 0/127 (0.00)
  - Extract Dependencies: 0/110 (0.00)
  - cla/google: 0/117 (0.00)
  - ci.yaml validation: 0/118 (0.00)
```

This suggests, but is not authoritative, that ~30% of `Linux linux_web_engine` builds fail on PRs that aren't labeled `platform-web`. Compare that with, say, `Linux linux_arm_host_engine` (7%).

I'm happy to make minor changes to the script to make it more useful, or can also accept PRs.

### CODE REVIEW

**Comment by zanderso** [comment]
Does GitHub count cancelled LUCI jobs as cancelled or failures? Same question about timeouts, I guess. Does @keyonghan know?

**Comment by keyonghan** [comment]
> Does GitHub count cancelled LUCI jobs as cancelled or failures? Same question about timeouts, I guess. Does @keyonghan know?

The canceled ones are treated same as failed ones. We should filter those out. Example:

Check run: [Linux Framework Smoke Tests](https://github.com/flutter/engine/pull/50356/checks?check_run_id=21239297622)
Canceld as infra failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Framework%20Smoke%20Tests/45087/overview
But the conclusion is `failure`: https://api.github.com/repos/flutter/engine/check-runs/21239297622

**Comment by keyonghan** [comment]
Take `Linux linux_web_engine` from example, based on the history build list, there are only 3 out of 100 test failures: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_web_engine?limit=100

Seems the script needs to be fined a bit more. Another common infra failure is `Pull request closed`.

**Comment by matanlurey** [comment]
Thanks! Tweaked to ignore any failure that includes the string `(canceled)`.

That does further lower to `Linux linux_web_engine: 7/116 (0.06)`, or 6%. 6% is 6x higher than the reported 1% flakes though.

---

With `--skip-failed-intentional-failures` (default):

```txt
Summary:
  - Linux linux_license: 72/116 (0.62)
  - Mac mac_host_engine: 26/116 (0.22)
  - Windows windows_host_engine: 22/116 (0.19)
  - Windows windows_unopt: 21/116 (0.18)
  - Linux linux_unopt: 20/116 (0.17)
  - Linux Framework Smoke Tests: 19/116 (0.16)
  - Linux mac_unopt: 18/116 (0.16)
  - Linux linux_host_engine: 18/116 (0.16)
  - Linux Fuchsia FEMU: 17/116 (0.15)
  - Linux linux_web_engine: 7/116 (0.06)
  - Linux linux_fuchsia: 4/112 (0.04)
  - Linux linux_clang_tidy: 3/111 (0.03)
  - Linux linux_android_emulator_tests: 2/83 (0.02)
  - Mac mac_clang_tidy: 2/115 (0.02)
  - Linux linux_android_debug_engine: 2/116 (0.02)
  - Linux linux_android_aot_engine: 2/116 (0.02)
  - Linux linux_host_desktop_engine: 2/116 (0.02)
  - Linux linux_arm_host_engine: 2/116 (0.02)
  - Windows windows_arm_host_engine: 2/116 (0.02)
  - Linux Web Framework tests: 1/94 (0.01)
  - Windows windows_android_aot_engine: 1/116 (0.01)
  - Mac mac_ios_engine: 1/116 (0.01)
  - Linux mac_android_aot_engine: 1/116 (0.01)
  - Vulnerability scanning: 0/163 (0.00)
  - Extract Dependencies: 0/163 (0.00)
  - triage: 0/117 (0.00)
  - cla/google: 0/84 (0.00)
  - ci.yaml validation: 0/85 (0.00)
```

Without:

```txt
Summary:
  - Linux linux_license: 78/116 (0.67)
  - Linux Fuchsia FEMU: 44/116 (0.38)
  - Linux mac_unopt: 43/116 (0.37)
  - Linux linux_host_engine: 43/116 (0.37)
  - Linux linux_unopt: 41/116 (0.35)
  - Linux Framework Smoke Tests: 41/116 (0.35)
  - Windows windows_unopt: 37/116 (0.32)
  - Mac mac_host_engine: 37/116 (0.32)
  - Windows windows_host_engine: 31/116 (0.27)
  - Linux linux_web_engine: 30/116 (0.26)
  - Linux linux_fuchsia: 24/112 (0.21)
  - Linux linux_clang_tidy: 23/111 (0.21)
  - Linux Web Framework tests: 19/94 (0.20)
  - Linux linux_android_emulator_tests: 16/83 (0.19)
  - Linux linux_android_debug_engine: 20/116 (0.17)
  - Mac mac_clang_tidy: 16/115 (0.14)
  - Mac mac_ios_engine: 12/116 (0.10)
  - Linux linux_android_aot_engine: 10/116 (0.09)
  - Windows windows_android_aot_engine: 9/116 (0.08)
  - Windows windows_arm_host_engine: 9/116 (0.08)
  - Linux linux_host_desktop_engine: 5/116 (0.04)
  - Linux mac_android_aot_engine: 4/116 (0.03)
  - Linux linux_arm_host_engine: 4/116 (0.03)
  - Vulnerability scanning: 0/163 (0.00)
  - Extract Dependencies: 0/163 (0.00)
  - triage: 0/117 (0.00)
  - cla/google: 0/84 (0.00)
  - ci.yaml validation: 0/85 (0.00)
```

**Comment by matanlurey** [comment]
Closing as something we'll likely not pursue.

**Pull request closed without merging**
