### PR TITLE
[web] Fix regression of pointer events on mobile browsers

### PR DESCRIPTION
**Pull request by mdebbar**
The regression was caused by https://github.com/flutter/engine/pull/17495

Fixes https://github.com/flutter/flutter/issues/54269

### CODE REVIEW

**Comment by ferhatb** [comment]
also fixes https://github.com/flutter/flutter/issues/54325

**Comment by hemantsavkar** [comment]
I’m still facing the same issue . We deployed Flutter app as PWA; it works well on Android and windows devices however page not loading on any iOS delvice

**Comment by mdebbar** [comment]
@hemantsavkar please file an issue and include reproduction steps.

**Comment by hemantsavkar** [comment]
> @hemantsavkar please file an issue and include reproduction steps.

Hi @mdebbar ; Raised issue https://github.com/flutter/flutter/issues/66128

**Pull request merged**
