### PR TITLE
Update AGP and Kotlin for scenario app 

### PR DESCRIPTION
**Pull request by reidbaker**
flutter/flutter/#134220

Command required to update lock files required not using the custom task and required matching the version of gradle in ci and passing a custom version of java. 
`~/.gradle/wrapper/dists/gradle-7.5.1-bin/7jzzequgds1hbszbhq3npc5ng/gradle-7.5.1/bin/gradle -D=org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home  app:dependencies --write-locks` for app:dependencies and dependencies. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by reidbaker** [comment]
Draft to get ci to build since I cant get it to work locally.

**Comment by reidbaker** [comment]
Error: The attribute android:allowBackup is deprecated from Android 12
https://developer.android.com/guide/topics/data/autobackup#xml-syntax-android-12

**Comment by reidbaker** [comment]
test exempt because I am modifying the build of a test.

**Comment by stuartmorgan** [comment]
test-exempt: is a test

**Review by zanderso — APPROVED** [review]

**Pull request merged**
