### PR TITLE
Remove suprious warning

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/45928

At some point, this was only called on paths where that was valid.  That seems to no longer be the case.

### CODE REVIEW

**Comment by goderbauer** [comment]
If it is ok to send a11y events with the root node ID to the parent, should we remove this code path as well?

https://github.com/flutter/engine/blob/54e2f2b8265aaf9c5aec2fb39e6209be638219e5/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1485-L1489

This code path was the main reason why the assert was introduced.

**Comment by dnfield** [comment]
@goderbauer maybe we should just make `sendAccessibilityEvent` do that logic internally?  

I'm not 100% clear on which code paths are resulting in this and I'm reluctant to remove the code that's working.

**Comment by dnfield** [comment]
Looking a little more closely:

`obtainAccessibilityEvent` just sets some properties on the event so that we end up with it being owned by the root accessibility view.  We don't need to do that if we're sending an event that's already meant to be on the root.

But we do now call the method in several other places - so maybe we should update the method to just return the event itself if the virtualViewId is the root?

**Comment by matthew-carroll** [comment]
FYI - it looks like this PR is missing tests.

Also, @amirh would you mind confirming that this logic was not related to platform views?

**Comment by dnfield** [comment]
This method predates platform views.

We need unit tests for the a11y bridge in general.  I can try to add some at some point - filed https://github.com/flutter/flutter/issues/46032 for that.

**Pull request merged**
