### PR TITLE
Revert "dart:ui conversion from native to FfiNative"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#29607

Possibly tickling a bug in dartdoc:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20docs_test/10286/overview

### CODE REVIEW

**Comment by zanderso** [comment]
cc @chinmaygarde

**Review by jason-simmons — APPROVED** [review]

**Comment by jason-simmons** [comment]
See https://github.com/dart-lang/sdk/issues/48962

**Comment by zanderso** [comment]
Did this reland?

**Comment by dnfield** [comment]
It was blocked for a while on https://github.com/dart-lang/dartdoc/pull/3033, which has landed and looks like published.

We need to rev dartdoc in the framework to reland this.

**Pull request merged**
