### PR TITLE
Fold the calls for FlutterMain into the FlutterEngine constructor

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/32946
Fixes https://github.com/flutter/flutter/issues/33145
Fixes https://github.com/flutter/flutter/issues/37195

Partially alleviates https://github.com/flutter/flutter/issues/32987

Remove the call mainly because the extra granularity is error-prone boilerplate (https://github.com/flutter/flutter/issues/39675, https://github.com/flutter/flutter/issues/39384, https://github.com/flutter/flutter/issues/39108, https://github.com/flutter/flutter/issues/30332, https://github.com/flutter/flutter/issues/28439) and doesn't really add any degree of control. 

On a low end Android device, this means merging in the 40ms call to load the native library with the already 290ms call to create the VM. Controlling when that 40ms call happens isn't useful. 

Redundant calls will still work, as will the old embedding. This just allows new code using the new embedding to omit the FlutterMain calls. 

Add an AndroidJUnit in-process test in the scenario_app project. It makes sure the real engine boots on a device. Didn't hook into firebase in this PR yet. One step at a time. 

Also added some supplemental docs while going through this.

### CODE REVIEW

**Comment by xster** [comment]
Any more thoughts on this one?

**Comment by xster** [comment]
Discussion offline, try to create a lightweight dependency injector to make it possible to test the FlutterEngine without a real JNI backing while doing this refactor. 

Also move the logic to a FlutterLoader in the new embedding package and reverse shim back into the FlutterMain APIs.

**Comment by xster** [comment]
Ok, altered this PR a bit more. 

Now there's a FlutterInjector lightweight dependency injector at the top level. Added some tests. 

FlutterMain is hollowed out and loading and loading related utility classes are moved to io.flutter.embedding.engine.loader. Let the other existing tests use the injector mechanism to override static.

**Comment by matthew-carroll** [comment]
Took over the PR here:
https://github.com/flutter/engine/pull/12806

**Pull request closed without merging**
