### PR TITLE
Prefer C++ standard headers to their C counterpart

### PR DESCRIPTION
**Pull request by cbracken**
We currently use a mix of C standard includes (e.g. limits.h) and their
C++ variants (e.g. climits) in //flutter/third_party/accessibility. This
migrates to a consistent style for all cases where the C++ variants are
acceptable. C equivalents remain in place only where they are required,
such as in the embedder API and other headers that may be used from C.

This commit is analogous to 16b900b63e27e4f876bfbaf88140d2d0521fe692.

This also removes a few leftover commented-out #includes.

No new tests since this is purely a formatting change.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for cleaning this up!

**Comment by gw280** [comment]
I'm not convinced that changes like this are valuable. It doesn't functionally change the code and increases the delta we have from upstream, making it more difficult to cherry-pick upstream changes.

**Comment by gw280** [comment]
That being said, this patch only touches the headers and not any uses of the C APIs so this one is fine but in future I think we need to be cognizant of the tradeoff.

**Comment by cbracken** [comment]
Missed these comments before but it seems unlikely we'll ever pull changes from upstream chromium in the future; the goal was to fork, strip away everything we don't need and then continue from there as a reasonable starting point for our own work.

**Pull request merged**
