### PR TITLE
Fixup Fuchsia content handler post shell refactor.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
You're sure nothing else was lost in the merge?

**Comment by chinmaygarde** [comment]
> You're sure nothing else was lost in the merge?

Pretty sure. I was merging manually to keep up with the changes on ToT as the content handler was being rewritten. The final few commits had to be reapplied manually since none of the files looked the same. I attempted rewriting the content handler last after the shell refactor so I only missed a few commits. The biggest one was the switch away from `f1dl` which is why this commit contains a lot of mostly trivial name changes. I am attempting to run the shell unit tests target on the device now. The device boots and runs in both JIT and AOT mode. Beyond that don't know if there are other test targets or workflows.

**Comment by chinmaygarde** [comment]
> You're sure nothing else was lost in the merge?

Now I am paranoid. Checking again.

**Comment by chinmaygarde** [comment]
As it turns out I had missed two patches. They have been applied in https://github.com/flutter/engine/pull/5072/commits/fabcdb12c9c7d03c1008e460a7a9fdc0a1127e89. I verified all patches to content_handler made in the past 6 months manually now. I think this is good.

**Comment by abarth** [comment]
Great.  Thanks for double-checking.

**Pull request merged**
