### PR TITLE
Remove confusing logs

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/62468

### CODE REVIEW

**Comment by liyuqian** [comment]
@godofredoc @digiter : is the "Windows Web Engine" test stuck in LUCI? Nothing seems to be actively running in https://ci.chromium.org/p/flutter/builders/try/Windows%20Web%20Engine/7358? after 11 minutes but the test is still not finished after 1 hour.

**Comment by godofredoc** [comment]
> @godofredoc @digiter : is the "Windows Web Engine" test stuck in LUCI? Nothing seems to be actively running in https://ci.chromium.org/p/flutter/builders/try/Windows%20Web%20Engine/7358? after 11 minutes but the test is still not finished after 1 hour.

\cc @nturgut seems like we are leaking processes in windows do we need kill dart processes at the end?

**Comment by nturgut** [comment]
thanks for letting me know. we can remove that step for now, since we are already blocked on a dart issue: https://github.com/dart-lang/build/issues/2765

**Comment by nturgut** [comment]
> \cc @nturgut seems like we are leaking processes in windows do we need kill dart processes at the end?

Thanks for the suggestion, I'll add an extra step for cleaning up processes.

**Pull request merged**
