### PR TITLE
[Impeller] Fix runtime effect pipeline depth/stencil.

### PR DESCRIPTION
**Pull request by bdero**
- Setup depth and stencil attachments for RuntimeEffect.
- Add validation check in `EntityPass` to force backends to set things up the root pass correctly.
- Add checks in `ContentContextOptions::ApplyToPipelineDescriptor` to validate that callers are holding it right.

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
test?

**Comment by bdero** [comment]
Yeah that's what I'm working on. Need to repro the validation error somehow to come up with a test case.

**Comment by jonahwilliams** [comment]
I'm not sure if its related, but I'm also getting a Vulkan validation error with runtime effect now

```
E/flutter (24423): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (24423): --- Vulkan Debug Report  ----------------------------------------
E/flutter (24423): |                Severity: Error
E/flutter (24423): |                    Type: { Validation }
E/flutter (24423): |                 ID Name: VUID-vkCmdDraw-renderPass-02684
E/flutter (24423): |               ID Number: 1349015333
E/flutter (24423): |       Queue Breadcrumbs: [NONE]
E/flutter (24423): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (24423): |         Related Objects: RenderPass [31269011182350103] [EntityPass Render Pass: Depth=0 Count=0], RenderPass [31307494089322298] [Compat Render Pass: Runtime Stage]
E/flutter (24423): |                 Trigger: Validation Error: [ VUID-vkCmdDraw-renderPass-02684 ] Object 0: handle = 0x6f170000006f17, name = EntityPass Render Pass: Depth=0 Count=0, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0x6f3a0000006f3a, name = Compat Render Pass: Runtime Stage, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x50685725 | vkCmdDraw: RenderPasses incompatible between active render pass w/ VkRenderPass 0x6f170000006f17[EntityPass Render Pass: Depth=0 Count=0] and pipeline state object w/ VkRenderPass 0x6f3a0000006f3a[Compat Render Pass: Runtime Stage] Attachment 3 is not compatible with 1: They have different formats.. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-renderPass-02684)
E/flutter (24423): -----------------------------------------------------------------
E/flutter (24423): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (24423): --- Vulkan Debug Report  ----------------------------------------
E/flutter (24423): |                Severity: Error
E/flutter (24423): |                    Type: { Validation }
E/flutter (24423): |                 ID Name: VUID-vkCmdDraw-renderPass-02684
E/flutter (24423): |               ID Number: 1349015333
E/flutter (24423): |       Queue Breadcrumbs: [NONE]
E/flutter (24423): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (24423): |         Related Objects: RenderPass [31343777973038939] [EntityPass Render Pass: Depth=0 Count=0], RenderPass [31307494089322298] [Compat Render Pass: Runtime Stage]
E/flutter (24423): |                 Trigger: Validation Error: [ VUID-vkCmdDraw-renderPass-02684 ] Object 0: handle = 0x6f5b0000006f5b, name = EntityPass Render Pass: Depth=0 Count=0, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0x6f3a0000006f3a, name = Compat Render Pass: Runtime Stage, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x50685725 | vkCmdDraw: RenderPasses incompatible between active render pass w/ VkRenderPass 0x6f5b0000006f5b[EntityPass Render Pass: Depth=0 Count=0] and pipeline state object w/ VkRenderPass 0x6f3a0000006f3a[Compat Render Pass: Runtime Stage] Attachment 3 is not compatible with 1: They have different formats.. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-renderPass-02684)
E/flutter (24423): -----------------------------------------------------------------
```

**Comment by bdero** [comment]
Yup that's for sure the same problem.

**Comment by bdero** [comment]
I added a test to verify the attachments end up being correct.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Haven't verified this locally yet but seems good.

**Pull request merged**
