### PR TITLE
Implement GetAllocationSize for Vertices

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Without this, the GC thinks that Vertices are super cheap. Allocating a lot of them (e.g. new ones each frame) uses tons of memory - on smaller devices, enough memory to OOM die.

Including this in the total picture memory (like in https://github.com/flutter/engine/pull/18706) makes this further use less memory. Doing that fixes part of https://github.com/flutter/flutter/issues/58438

/cc @mehmetf  - this may help customer: money with some of their Rive/Flare concerns, since Flare uses this API.
/cc @luigi-rosso  @cmkweber

## Related Issues

Fixes flutter/flutter#54762
Possibly helps https://github.com/2d-inc/Flare-Flutter/issues/249

## Tests

TODO

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
The only failure for this is fixed on master. I'd rather not rebase and find out another test flaked. Merging on red.

**Comment by luigi-rosso** [comment]
Sorry for commenting on this so late, but I'm curious if there's an opportunity here to re-use existing TypedData arrays (like the Float32List for the vertex positions) by allowing changing the contents of the buffer instead of allocating new ones each frame. Perhaps some way to notify the Vertices that the buffer has changed and it needs to internally resync with Skia? @dnfield Let me know if you think it's worth opening an issue for this.

**Comment by dnfield** [comment]
Do the arrays resize per frame? If so then it's probably better to just allocate new ones and let the GC do its thing, because resizing the buffers would cause a lot of thrash anyway. If not then it's probably worth exploring.

**Comment by dnfield** [comment]
Alternatively, if the array has a (reasonable) upperbound, it could make sense to have an array and a length parameter for how much of the array you actually want to use.

**Comment by luigi-rosso** [comment]
That's a good idea, but they currently do not resize. We only update the vertices when the animation animates them which currently involves moving them. It'd also only be the position buffer that updates, the UV and index buffers are static throughout.

**Comment by cmkweber** [comment]
I believe Skia is working on per vertex data (SkVertices::Attribute) that can be exposed to shaders.
This functionality would be great to see in flutter once it's completed.
This would allow for a constant size buffer but dynamic contents.

**Pull request merged**
