### PR TITLE
Present Metal drawable with a transaction only when on the Main thread.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/55784

### CODE REVIEW

**Comment by chinmaygarde** [comment]
This is just a subset of the patch at https://github.com/flutter/engine/pull/18076 without any of the changes that cannot be cherry picked into the candidate.

**Comment by pcsosinski** [comment]
lgtm based on #18076

**Comment by pcsosinski** [comment]
web_engine_integration_test_linux failure is a known issue on the 1.17 branch (#18089)

**Comment by cbracken** [comment]
Thanks!

**Pull request merged**
