### PR TITLE
Android linter prints to the console by default

### PR DESCRIPTION
**Pull request by mklim**
The HTML report can still be generated by passing in an `--html` flag
to the tool.

This will make errors easier to debug in CI.

/cc @matthew-carroll

### CODE REVIEW

**Comment by mklim** [comment]
Example output: https://cirrus-ci.com/task/4804205398196224

**Comment by matthew-carroll** [comment]
Thanks for the improvement.

**Comment by dnfield** [comment]
While you're in here, could you make the Java part check the `stderr` instead of `stdout`?  Otherwise I can do it in another PR.

**Comment by mklim** [comment]
> While you're in here, could you make the Java part check the `stderr` instead of `stdout`? Otherwise I can do it in another PR.

Talked offline, going to keep this PR as is to avoid another round of CI.

**Pull request merged**
