### PR TITLE
Remove usage of NaN values in canvas_test that caused a Skia assert failure

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
Was the assertion failure in debug only?

**Comment by jason-simmons** [comment]
yes - the buildbots run the engine Dart tests using a flutter_tester built in host_debug_unopt mode with assertions turned on

**Comment by chinmaygarde** [comment]
As long as the engine does not crash on the mobile shells.

**Comment by Hixie** [comment]
Can we instead fix tonic to fail when trying to convert a NaN?

This code is trying to make sure we don't crash when we pass a NaN, so removing the NaN isn't really a long-term fix. :-)

**Comment by jason-simmons** [comment]
Skia's SkRect can represent NaN coordinates, but the API doesn't support drawing an object with NaN coordinates.  The engine's Canvas Dart wrappers could check whether a rect is finite before passing it onward to Skia.

**Pull request merged**
