### PR TITLE
roll Dart to 21eddc429e9c7260de00a9af7cad94baba830f59

### PR DESCRIPTION
**Pull request by yjbanov**
This contains the fix for the critical HTTP bug.

/cc @jason-simmons @zanderso

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Needs licenses update.

**Comment by yjbanov** [comment]
Yep, working on it.

**Comment by Hixie** [comment]
This seems to have regressed microbenchmarks stock_layout_iteration and hot reload benchmarks.

**Comment by Hixie** [comment]
(As seen in benchmarks since https://github.com/flutter/flutter/pull/11553.)

**Comment by Hixie** [comment]
Filed https://github.com/dart-lang/sdk/issues/30388 to track regressions.

**Pull request merged**
