### PR TITLE
Roll ICU

### PR DESCRIPTION
**Pull request by stuartmorgan**
## Description

Picks up a fix that prevents passing -fvisibility=hidden in Windows
clang compilations, which causes hundreds of warnings.

## Related Issues

Part of https://github.com/flutter/flutter/issues/59199

## Tests

I added the following tests: None: no intended change in functionality.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
(We'll see how this does on the bots; I haven't tried building it locally.)

**Review by cbracken — COMMENTED** [review]
RSLGTM. Looks fuchsia seems to be upset about a few duplicate symbols.

**Review by cbracken — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Hrm. The fix changed replaced `is_clang` with a platform list, so presumably it turned off `visibility=hidden` for fuchsia. I'm not sure how we handle platform checks in upstream dependencies where we need to cover fuchsia.

**Comment by stuartmorgan** [comment]
Looks like there are a couple of `is_fuchsia` conditions in `third_party/icu` already, so maybe it's as simple as adding `is_fuchsia` to that condition upstream, and then rolling further forward.

**Comment by chinmaygarde** [comment]
Is this blocked on an ICU roll? If so, I am going to have to attempt one to roll to the latest Fuchsia toolchain. Happy to carry that to completion if you haven't already started on it.

**Comment by stuartmorgan** [comment]
It's blocked on https://chromium-review.googlesource.com/c/chromium/deps/icu/+/2427043, which fixes that conditional for fuchsia (and thus will hopefully fix the errors surfaced here).

**Comment by stuartmorgan** [comment]
Trying 3c77cb51021da9c4df4966d02a24454801608c7e which is the revision where that fix landed...

**Comment by stuartmorgan** [comment]
Hm, that doesn't seem to have fixed it. It's still giving:
```
ld.lld: error: duplicate symbol: icu_67::BucketList::~BucketList()
>>> defined in obj/third_party/icu/source/i18n/icui18n_cr.alphaindex.o
>>> defined in obj/third_party/icu/source/i18n/icui18n_hidden_visibility_cr_hidden_visibility.alphaindex.o
```

@chinmaygarde If you can take over the ICU roll that would be great, since I don't have a Fuchsia build set up to debug why it's not working.

**Comment by chinmaygarde** [comment]
> If you can take over the ICU roll that would be great.

Sure. I'll handle this as part of the Fuchsia toolchain roll that is blocked by the ICU roll too.

**Pull request closed without merging**
