### PR TITLE
Transfer ownership of the buffer in the image decoder bitmap fallback path

### PR DESCRIPTION
**Pull request by jason-simmons**
Previously we had passed a local generator to flow::BitmapImageCreate /
SkImage::MakeFromGenerator, which takes ownership of the generator.
That generator in turn referenced an SkData backed by a local vector.
The result was an SkImage backed by a deleted buffer.

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde @tvolkert

**Comment by eseidelGoogle** [comment]
Do we have any way to test this?

**Comment by jason-simmons** [comment]
We noticed this when test/services/image_decoder_test on the framework side was segfaulting, causing Travis failures.

("flutter test --coverage" was hanging while trying to gather stats from the crashed test, which is a separate issue: https://github.com/flutter/flutter/issues/8202)

**Comment by tvolkert** [comment]
LGTM

Fixes #8200

**Comment by chinmaygarde** [comment]
To clarify: The semantics are clearer because the new constructor takes a shared pointer to the data making it extremely clear to the caller that the data may outlive the scope they control.

**Comment by jamesr** [comment]
Cool!  I'll patch this into a Fuchsia build and see how it goes.

**Comment by jamesr** [comment]
device_runner no longer segfaults in Fuchsia with this patch.

**Pull request merged**
