### PR TITLE
A fix for the platform view dismiss crash related to gl

### PR DESCRIPTION
**Pull request by cyanglaz**
Issue: https://github.com/flutter/flutter/issues/31152 https://github.com/flutter/flutter/issues/34509
The crash is probably happened after dismissing the overlay, at some point we are doing gl operation on the wrong context.
I am still investigating the exact place where we did that.

This patch can temporarily fix the crash without the memory leak regression.

Edit: We think the crash happened because GoogleMap polluted our context after IOSGLRenderTarget's destruction.

### CODE REVIEW

**Comment by Dominic12** [comment]
Hi guys,

Can we expect this to be rolled out to master within the next 24 Hours?

**Comment by yasargil** [comment]
My guess why it was crashing bevor this fix is, that the embedded GMSMapView is making OpenGL calls after the destruction of IOSGLRenderTarget using the FlutterGLContext instead of its own context, polluting the FlutterGLContext with some incompatible instructions.

**Comment by darkmarthur** [comment]
@cyanglaz I see the issue 31152 has been fixed, what I need to do on my project to receive the fix? is there something that I need to update or select another branch? the issue still happening on my project

**Comment by Dominic12** [comment]
"flutter channel master" should do the trick.

**Comment by darkmarthur** [comment]
I have executed `flutter channel master`  but when I try `flutter run` it throws a bunch of errors. Do I'm skipping a step or something?

image (1)

**Comment by tareq594** [comment]
I can still reproduce the same issue even after flutter channel master.

**Comment by Quanhua-Guan** [comment]
I can still reproduce the same issue even after flutter channel master. (+1)

like this:
1. In iOS, navigate to a native page from flutter page, 
2. then invoke some opengles commands, including changing current context (` [EAGLContext setCurrentContext:mycontext];`). 
3. go back to flutter page, try tapping, scrolling...etc, 
THEN, crash.

**Comment by Quanhua-Guan** [comment]
> I can still reproduce the same issue even after flutter channel master. (+1)
> 
> like this:
> 
> 1. In iOS, navigate to a native page from flutter page,
> 2. then invoke some opengles commands, including changing current context (` [EAGLContext setCurrentContext:mycontext];`).
> 3. go back to flutter page, try tapping, scrolling...etc,
>    THEN, crash.

MY Problem is solved! I when UIViewController disappear, i set current context of eagl to nil, as follow: (add this catogory to you project)
```
#pragma mark - 适配 FLBFlutterViewContainer

@interface FLBFlutterViewContainer (Gaoding)

@end

@implementation FLBFlutterViewContainer (Gaoding)

+ (void)load {
    /* 避免flutter gpu崩溃 */
    NSError *error = nil;
    [self jr_swizzleMethod:@selector(viewDidAppear:) withMethod:@selector(gd_viewDidAppear:) error:&error];
    if (error != nil) {
        NSAssert(error == nil, @"FLBFlutterViewContainer -viewDidDisappear:方法替换失败!");
    }
    [self jr_swizzleMethod:@selector(viewDidDisappear:) withMethod:@selector(gd_viewDidDisappear:) error:&error];
    if (error != nil) {
        NSAssert(error == nil, @"FLBFlutterViewContainer -viewDidAppear:方法替换失败!");
    }
}

- (void)gd_viewDidAppear:(BOOL)animated {
    [EAGLContext setCurrentContext:nil];
    [self gd_viewDidAppear:animated];
}

- (void)gd_viewDidDisappear:(BOOL)animated {
    [self gd_viewDidDisappear:animated];
    [EAGLContext setCurrentContext:nil];
}

@end
```

**Comment by Quanhua-Guan** [comment]
https://github.com/Quanhua-Guan/GDFlutterFix/blob/master/GDFlutterFix/Classes/FLBFlutterViewContainer%2BGaoding.m

**Comment by Quanhua-Guan** [comment]
The crash is still happened in production env. But I cant reproduce it. sad-_-

**Comment by darren-f5s** [comment]
https://github.com/flutter/flutter/issues/40650

Im somehow reproducing this, but can't get an example that's 100% replicable.

**Comment by amirh** [comment]
@darren-f5s sounds like https://github.com/flutter/flutter/issues/41620

**Pull request merged**
