### PR TITLE
Reland _embedder.yaml support to Flutter engine

### PR DESCRIPTION
**Pull request by johnmccutchan**
Fixes https://github.com/flutter/flutter/issues/523

### CODE REVIEW

**Comment by johnmccutchan** [comment]
This pairs with https://github.com/flutter/flutter/pull/2265

@Hixie @abarth

**Comment by abarth** [comment]
LGTM

**Comment by johnmccutchan** [comment]
Will hold off on landing this until Wednesday.

**Comment by abarth** [comment]
The new analyzer from the new Dart SDK crashes https://github.com/dart-lang/sdk/issues/25903

I'm going to revert this change and roll back the Dart SDK to get back to a non-crashing state.  Hopefully we can then fix the analyzer issue and roll forward again.

**Comment by abarth** [comment]
It looks like rolling forward to 1.15.0-dev.5.0 might resolve the issue.

**Comment by abarth** [comment]
Yep, I was able to resolve by rolling the SDK forward.  Sorry for the noise.

**Pull request merged**
