### PR TITLE
Remove reference to non-existent directory

### PR DESCRIPTION
**Pull request by abarth**
This was breaking the build with gcm enabled.

### CODE REVIEW

**Comment by abarth** [comment]
TBR @mpcomplete

**Comment by chinmaygarde** [comment]
lgtm

**Comment by mpcomplete** [comment]
This was behind a flag. Was it causing a problem somewhere?

I left it in because my planned build instructions were:
1. Check out flutter_gcm into your engine/src dir.
2. Run sky/tools/gn --enable-gcm

**Comment by abarth** [comment]
> Was it causing a problem somewhere?

Yes, it was breaking the build on the bots, which build with --enable-gcm and were unable to build.

**Comment by mpcomplete** [comment]
> Yes, it was breaking the build on the bots, which build with --enable-gcm and were unable to build.

I thought you removed that flag from the bots.

**Comment by abarth** [comment]
@mpcomplete Yes, I think I did that as well (probably after this patch).  Let's talk after the standup today about the path forward here.  I feel like there's some communication issue that's probably easy to resolve over VC.

**Pull request merged**
