### PR TITLE
Remove `--enable-impeller-{backend}` flags (always `True`).

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/142725.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Something seems up with CI

**Comment by matanlurey** [comment]
I guess I broke the YAML format. Will fix it tomorrow 🙂

**Comment by matanlurey** [comment]
> I guess I broke the YAML format. Will fix it tomorrow 🙂

Or not, it was easy

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
Awesome!

**Pull request merged**
