### PR TITLE
Remove duplicated _ from Android's test methods' name

### PR DESCRIPTION
**Pull request by utzcoz**
Remove duplicated _ from Android's test methods' name. It's a minor cleanup PR.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @zanderso , could you help to assign folks to help review this simple PR? Thanks.

**Comment by stuartmorgan** [comment]
@GaryQian Do you know if there's a historical reason for this naming? It does seem unusual.

**Comment by GaryQian** [comment]
I've noticed this but I never found out why. There are many instances so it seems unlikely it was an accident.

I know we have (had?) Double underscores in shard names, I wonder if this was imitating that format.

**Review by stuartmorgan — APPROVED** [review]
Since I wouldn't expect this to actually impact anything (and all the tests still pass so it doesn't seem to be a workaround for something), let's just standardize on something more common. LGTM.

**Review by GaryQian — APPROVED** [review]
Yeah agree, let's go ahead with this.

**Comment by utzcoz** [comment]
Thanks.

**Pull request merged**
