### PR TITLE
[ci.yaml] Add xcode property to ci.yaml

### PR DESCRIPTION
**Pull request by CaseyHillers**
https://github.com/flutter/flutter/issues/84998
https://github.com/flutter/flutter/issues/85491

In the future, it would allow changes like https://flutter-review.googlesource.com/c/infra/+/15101 to be tracked in the engine repo.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Is this actually used yet? Or is it still respecting engine_config.star?  I need to coordinate this Xcode version change with the engine team.

**Comment by jmagman** [comment]
> Is this actually used yet? Or is it still respecting engine_config.star? I need to coordinate this Xcode version change with the engine team.

@christopherfujino says this property is currently ignored.

**Review by jmagman — APPROVED** [review]
LGTM

**Review by jmagman — CHANGES_REQUESTED** [review]
I had to roll back 13a5155e, can you make this `12a7209`?

**Review by jmagman — APPROVED** [review]
LGTM, sorry for the thrash!

**Pull request merged**
