### PR TITLE
Only build full sdk on release to speed up bots

### PR DESCRIPTION
**Pull request by jonahwilliams**
We don't need the dart2js or dartdevc snapshots in the engine, and we only ship the release sdk variants.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Something like this?

https://chromium-review.googlesource.com/c/chromium/tools/build/+/1509858

**Comment by jonahwilliams** [comment]
Accidentally published more changes here instead: https://chromium-review.googlesource.com/c/chromium/tools/build/+/1512753

Are there any ordering concerns here? Can I submit the bot change before landing the flag change in the engine? I would like to ensure we don't accidentally do a release with the snapshots removed

**Comment by chinmaygarde** [comment]
Landing the bot change first then this one should work. Orthogonally, are there presubmits that check we don't release stuff without the snapshots?

**Comment by jonahwilliams** [comment]
Its currently disabled, but I have a dart2js compile test in the framework that will fail if dart2js is missing or if the stub_ui and ui implementations differ too much

**Comment by jonahwilliams** [comment]
I've merged the bot change, LMK when it is safe to merge this one too

**Comment by chinmaygarde** [comment]
This needs to be merged now as it is blocking linux bots.

**Comment by jonahwilliams** [comment]
Updated this PR to default to true, when this lands I will reland the bot change, and then follow up to switch the flag to False

**Pull request merged**
