### PR TITLE
Reland: Ignore armv7 in ios framework script

### PR DESCRIPTION
**Pull request by zanderso**
Reland of https://github.com/flutter/engine/pull/32638

Related https://github.com/flutter/flutter/issues/97327

### CODE REVIEW

**Comment by zanderso** [comment]
Putting this back up just in case it becomes safe to land while I'm OOO.

**Comment by jmagman** [comment]
Thanks Zach.  Blocked on https://github.com/flutter/flutter/issues/101793 do not merge until that is fixed.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/101793 merged so this should be ready to try.  

I'll test locally tomorrow and LGTM then.  I expect this may cause some unexpected issues in the framework, so I'll escort this through the roll.

**Review by jmagman — APPROVED** [review]
LGTM, let's try it

**Pull request merged**
