### PR TITLE
Make the color filter layer use the paint specified by the framework.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by jonahwilliams** [comment]
LGTM!

**Comment by chinmaygarde** [comment]
Regressed in https://github.com/flutter/engine/pull/3685

**Comment by Hixie** [comment]
d'oh!

Is this something we can test somehow?

**Comment by jonahwilliams** [comment]
@Hixie well, we will soon have a ColorFilter widget which would break without this...

**Comment by chinmaygarde** [comment]
@Hixie: Pixel tests that @tvolkert keeps made deterministic recently.

**Comment by tvolkert** [comment]
@chinmaygarde right now almost all our pixel tests are in customer apps.  We should by all means be writing our own as well within the Google infra, and when we update our testing infra to allow those to run on Travis or in the devicelab, we can port them to the public landscape.  tldr: feel empowered to send me a CL.

**Pull request merged**
