### PR TITLE
Roll to CanvasKit 0.31.0

### PR DESCRIPTION
**Pull request by yjbanov**
Roll to CanvasKit 0.31.0

### CODE REVIEW

**Review by hterkelsen — APPROVED** [review]
LGTM

**Comment by skia-gold** [comment]
Gold has detected about 160 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/29772

**Comment by skia-gold** [comment]
Gold has detected about 80 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/29772

**Comment by yjbanov** [comment]
LUCI engine status is incorrect right now due to https://github.com/flutter/flutter/issues/90569. Merging.

**Pull request merged**
