### PR TITLE
[fuchsia][sysmem2] move to sysmem2 protocols

### PR DESCRIPTION
**Pull request by dustingreen**
Switch flutter from sysmem(1) protocols to sysmem2 protocols.

This is part of the overall sysmem(1) to sysmem2 migration.

fixes flutter/flutter#151154

### CODE REVIEW

**Comment by dustingreen** [comment]
The fuchsia_target_api_level will need to be >= 19 (probably 20) before this PR. For now, just verifying that PR checks pass.

**Comment by dustingreen** [comment]
cl/638860508 per go/flutter-fuchsia-pr-policy (placeholder failures are ignore-able)

**Comment by dustingreen** [comment]
fuchsia_target_api_level is 19 now, so this is unblocked

**Review by jrwang — APPROVED** [review]
LGTM

**Pull request merged**
