### PR TITLE
Add scenario_app target to iOS scenario test README

### PR DESCRIPTION
**Pull request by jmagman**
Just building the `ios_debug_sim_unopt` does not generate the `scenario_app`.  Add instructions to the README to also build the `scenario_app` target.

See https://github.com/flutter/engine/pull/27302

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
Just building `ios_debug_sim_unopt ` didn't generate `out/ios_debug_sim_unopt/scenario_app`.
@dnfield I don't see where this is done on the recipe side, am I missing something here?

https://flutter-review.googlesource.com/c/recipes/+/15820

**Comment by dnfield** [comment]
It should have - when I test a local build it's working fine, and it should get pulled in by default from the root BUILD.gn here: https://github.com/flutter/engine/blob/5f4c2374f1cfdc1081e2ef9fe006b36bc67a83ac/BUILD.gn#L133-L136

**Comment by dnfield** [comment]
_explicitly_ building that target may not be a bad idea because in theory it'll be faster by excluding other targets you may not need, but in practice I doubt it's much different. 

So these instructions should not be necessary but they're not wrong either...

**Comment by jmagman** [comment]
I see what happened, locally I was running the target `ios_test_flutter`, which doesn't add the `scenario_app` dep.  Just building `ios_debug_sim_unopt` on its own (as the README says now) did work.
```
$ ninja -C out/ios_debug_sim_unopt ios_test_flutter
$ ll out/ios_debug_sim_unopt/scenario_app
ls: out/ios_debug_sim_unopt/scenario_app: No such file or directory
$ ninja -C out/ios_debug_sim_unopt
$ ll out/ios_debug_sim_unopt/scenario_app
total 24
...
```
Thanks for the sanity check @dnfield.

**Pull request closed without merging**
