### PR TITLE
Correct the return type of addRetained

### PR DESCRIPTION
**Pull request by liyuqian**
It should return void as SceneBuilder::addRetained is returning void.
Thanks yjbanov@ for finding this typo!

### CODE REVIEW

**Comment by yjbanov** [comment]
Is it worth sending a breaking change announcement? /cc @Hixie

**Comment by yjbanov** [comment]
LGTM otherwise.

**Comment by liyuqian** [comment]
A little clarification about what may be broken:

Since the native method was returning void, no developers were able to use the returned value any way. So I guess this won't break any existing app using SceneBuilder. However, this may break someone who's creating a custom SceneBuilder (e.g., Flutter for Web).

**Comment by Hixie** [comment]
I wouldn't bother announcing this.

**Comment by yjbanov** [comment]
> However, this may break someone who's creating a custom SceneBuilder (e.g., Flutter for Web).

Ironically, the Web version [returns void](https://github.com/flutter/flutter_web/blob/master/packages/flutter_web_ui/lib/src/ui/compositing.dart#L281) :)

**Pull request merged**
