### PR TITLE
[Impeller] remove shared_ptr copy/release in main rendering loop.

### PR DESCRIPTION
**Pull request by jonahwilliams**
image

### CODE REVIEW

**Comment by matanlurey** [comment]
test-exempt: non-semantic refactor.

**Review by matanlurey — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Added some more PTAL

**Comment by matanlurey** [comment]
> Added some more PTAL

LGTM!

Psst, next time use this feature:

Screenshot 2024-01-16 at 12 55 18 PM

**Review by matanlurey — APPROVED** [review]

**Review by Sopheap-cloud — COMMENTED** [review]
Download

**Pull request merged**
