### PR TITLE
Fix regression - configure asset bundle

### PR DESCRIPTION
**Pull request by aam**
Fixes https://github.com/flutter/flutter/issues/12739

### CODE REVIEW

**Comment by xster** [comment]
LGTM

Can you test locally to confirm that it fixes the issue?

**Comment by aam** [comment]
> Can you test locally to confirm that it fixes the issue?

Verified the fix on iOS simulator on sample app ('+' instead of lock).

**Comment by xster** [comment]
Woohoo, thanks!

**Comment by aam** [comment]
Thank you for finding the cause of the regression and sorry for the breakage!

**Pull request merged**
