### PR TITLE
Change how OpenGL textures are flipped in the Android embedder.

### PR DESCRIPTION
**Pull request by matanlurey**
h/t @bdero for [writing the actual code](https://github.com/flutter/flutter/issues/141636#issuecomment-1903677360) (I just wrote comments).

Manual test[^1] of `cd packages/packages/video_player/video_player/example && flutter run`:

## Skia

Screenshot 2024-01-22 at 3 21 20 PM

## Impeller + OpenGL

Screenshot 2024-01-22 at 9 41 59 AM

```xml
<meta-data
      android:name="io.flutter.embedding.android.EnableImpeller"
      android:value="true" />
<meta-data
      android:name="io.flutter.embedding.android.ImpellerBackend"
      android:value="opengles" />
```

Closes https://github.com/flutter/flutter/issues/141636.

[^1]: I can't write a test worth writing at the same time of this PR, so I've filed https://github.com/flutter/flutter/issues/141973 to do it after.

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM

**Comment by johnmccutchan** [comment]
test-exempt: Test will live in another repo

**Comment by bdero** [comment]
@matanlurey This patch is correct, but it turns out there's also a bug in `surface_texture_external_texture_gl.cc` for Skia's mapping that we need to patch in here: https://github.com/flutter/flutter/issues/141636#issuecomment-1904930742

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
