### PR TITLE
[ios] fix rasterizer thread crash when several views are created and attached quickly.

### PR DESCRIPTION
**Pull request by toneyzeng**
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by toneyzeng** [comment]
Can somebody/anybody help me retry the Mac iOS Engine check?

**Comment by chinmaygarde** [comment]
Its hard to review this without a more detailed description of the issue you are solving. Can you post a reduced test case that exhibits this crash?

**Comment by toneyzeng** [comment]
You can see how PlatformViewIOS::SetOwnerViewController() do and think why PlatformViewIOS::attachView() not? 

The RASTER SURFACE (actually it's a |GPUSurfaceMetal| object in ios platform) has member named |delegate_| points to |ios_surface_|.
So we must construct and destruct them in the order below:

1, create ios_surface_
2, create |GPUSurfaceMetal| (with delegate_ points to ios_surface_)
3, destroy |GPUSurfaceMetal| 
4, destroy ios_surface_

See logs from my flutter-boost demo below:

----------------------------------------------------------------------- logs in xcode -------------------------------------------

// Create a flutter view as normal. That is ok.

2021-01-29 15:54:31.756138+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(122)] PlatformViewIOS::SetOwnerViewController(): create RASTERIZER SURFACE.
2021-01-29 15:54:31.759126+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(125)] PlatformViewIOS::SetOwnerViewController(): destroy ios_surface_: 0x2807f5bc0
2021-01-29 15:54:31.762679+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(158)] PlatformViewIOS::attachView(): destroy ios_surface_: 0x0
2021-01-29 15:54:31.762894+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(169)] PlatformViewIOS::attachView(): create ios_surface_: 0x2807fa140
2021-01-29 15:54:31.778862+0800 Runner[1651:529669] [VERBOSE-2:platform_view_ios.mm(199)] PlatformViewIOS::CreateRenderingSurface(): create RASTERIZER SURFACE with ios_surface_: 0x2807fa140


// Create 3 flutter view quickly. It is a trap there.

2021-01-29 15:55:04.696449+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(122)] PlatformViewIOS::SetOwnerViewController(): destroy RASTERIZER SURFACE.
2021-01-29 15:55:04.698390+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(125)] PlatformViewIOS::SetOwnerViewController(): destroy ios_surface_: 0x2807fa140
2021-01-29 15:55:04.702835+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(158)] PlatformViewIOS::attachView(): destroy ios_surface_: 0x0
2021-01-29 15:55:04.703121+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(169)] PlatformViewIOS::attachView(): create ios_surface_: 0x28073ae80
2021-01-29 15:55:04.719494+0800 Runner[1651:529669] [VERBOSE-2:platform_view_ios.mm(199)] PlatformViewIOS::CreateRenderingSurface(): create RASTERIZER SURFACE with ios_surface_: 0x28073ae80
2021-01-29 15:55:04.887815+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(122)] PlatformViewIOS::SetOwnerViewController(): destroy RASTERIZER SURFACE.
2021-01-29 15:55:04.888917+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(125)] PlatformViewIOS::SetOwnerViewController(): destroy ios_surface_: 0x28073ae80
2021-01-29 15:55:05.264349+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(158)] PlatformViewIOS::attachView(): destroy ios_surface_: 0x0
2021-01-29 15:55:05.264587+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(169)] PlatformViewIOS::attachView(): create ios_surface_: 0x2807244c0
2021-01-29 15:55:05.266501+0800 Runner[1651:529669] [VERBOSE-2:platform_view_ios.mm(199)] PlatformViewIOS::CreateRenderingSurface(): create RASTERIZER SURFACE with ios_surface_: 0x2807244c0
2021-01-29 15:55:05.271550+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(158)] PlatformViewIOS::attachView(): destroy ios_surface_: 0x2807244c0
2021-01-29 15:55:05.271755+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(169)] PlatformViewIOS::attachView(): create ios_surface_: 0x280721f00

// NOTE: The raster thread(529669) may scheduled any animate frame with Rasterizer::DoDraw() called HERE. At this moment RASTERIZER SURFACE will access wild pointer delegate_ to a destructed object ios_surface_: 0x2807244c0

2021-01-29 15:55:05.272719+0800 Runner[1651:529349] [VERBOSE-2:platform_view_ios.mm(122)] PlatformViewIOS::SetOwnerViewController(): destroy RASTERIZER SURFACE.  

// I M CRSHED NOW BECAUSE I ACCESS ｜delegate_｜ in ~GPUSurfaceMetal()

(lldb)

**Comment by toneyzeng** [comment]
> Its hard to review this without a more detailed description of the issue you are solving. Can you post a reduced test case that exhibits this crash?

Can you please review it again? Thaks.

**Comment by ColdPaleLight** [comment]
@toneyzeng  is my colleague, he make this patch to resolve the issue：https://github.com/flutter/flutter/issues/86353. Currently this issue has been resolved. I have communicated with him offline, we confirmed that we can close this PR.

**Pull request closed without merging**
