### PR TITLE
[Impeller] 🔥 Cast fireball on `host-debug-impeller-vulkan` and see what breaks.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/134675.

This is based off @chinmaygarde's suggestion in https://github.com/flutter/flutter/issues/134675#issuecomment-1724146011.

@bdero could you review as current engine on-duty? Thanks!

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
The readme updates seem valuable regardless of what this attempt at removing the variant reveals. If we do back it out, we should perhaps split this patch up?

**Comment by matanlurey** [comment]
I actually didn't intend to reformat the markdown, but agreed the changes are good.

**Review by bdero — APPROVED** [review]
LGTM

**Comment by matanlurey** [comment]
Converting back to a draft PR. I want to try something else.

**Pull request closed without merging**
