### PR TITLE
[CP-stable][Impeller] revert glyph atlas texture recycling.

### PR DESCRIPTION
**Pull request by flutteractionsbot**
This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

https://github.com/flutter/flutter/issues/144331

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/wiki/Hotfix-Documentation-Best-Practices) for examples

* Fix rendering bugs in the Cupertino Picker when using the Impeller rendering engine. 

### Impact Description:

iOS scrolling picker/cupertino picker glitches on Impeller.

### Workaround:
Is there a workaround for this issue?

No

### Risk:
What is the risk level of this cherry-pick?

  - [x] Low
  - [ ] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [x] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

< Replace with validation steps here >

### CODE REVIEW

**Comment by XilaiZhang** [comment]
(btw one of the tests failed on post submit)

**Comment by jonahwilliams** [comment]
That test failure doesn't look related to this change? is there some other change I need to patch into this branch?

**Comment by XilaiZhang** [comment]
yeah it might be a flake. triggered a rerun on it

**Comment by jonahwilliams** [comment]
linux host engine appears stuck

**Comment by XilaiZhang** [comment]
Umm maybe infra TL @keyonghan could help take a look?

**Comment by keyonghan** [comment]
Some GitHub related issues happened on 04/05. The hanging build did finish and failed. If a retry is needed, please follow [`Rerun GitHub presubmit test using command line`](https://github.com/flutter/flutter/wiki/Flutter-Self-Service-Index). If builds kept hanging, an infra ticket will be helpful.

**Comment by jonahwilliams** [comment]
Why do I need to install the gcloud SDK to rerun a github task? Can we change the ACLs so I can click rerun in the UI?

**Comment by keyonghan** [comment]
> Why do I need to install the gcloud SDK to rerun a github task? Can we change the ACLs so I can click rerun in the UI?

We need a way to authenticate the request.

The UI retry surfaces only when a final state was reported back to the check run. Here it's not due to a missing status. The UI retry is authenticated via github app through webhook event.

As for the API reset, it needs gcloud SDK to authenticate the request.

**Comment by godofredoc** [comment]
> Why do I need to install the gcloud SDK to rerun a github task? Can we change the ACLs so I can click rerun in the UI?

Clicking re-run button in the LUCI UI won't update the task in Github. The task needs to be triggered from the cocoon backend to provide the metadata required for LUCI to communicate correctly to Github.

**Comment by godofredoc** [comment]
Task has been retried.

**Comment by zanderso** [comment]
The `linux_host_engine` failure is an issue we were discussing in chat last week(?) related to the move of the buildtools directory from // to //flutter.

**Pull request merged**
