### PR TITLE
Drop unneded kotlin dep

### PR DESCRIPTION
**Pull request by dnfield**
This was added to avoid warnings given about the wrong kotlin runtime version - upstream dependencies have again changed and it's no longer needed.

I think ideally we'd be passing the right `-language-version` argument, but I really don't know how to do that properly for gradle. Maybe @blasten knows.

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by jason-simmons** [comment]
Actually it looks like the "Runtime JAR files in the classpath have the version 1.4" warnings are still happening in the presubmit LUCI builders:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8837435015190428721/+/u/build_android_debug/stdout

**Comment by dnfield** [comment]
@blasten do you know any Gradle voodoo for this?

**Comment by blasten** [comment]
is this https://kotlinlang.org/docs/compiler-reference.html#language-version-version ? There's a config object provided the Kotlin plugin: https://kotlinlang.org/docs/gradle.html#attributes-specific-for-jvm

**Comment by dnfield** [comment]
@blasten yes, but those seem to be JVM parameters rather than parameters to pass to the Kotlin compiler.

**Comment by blasten** [comment]
@dnfield what about this ?:

```groovy
compileKotlin {
    kotlinOptions {
        languageVersion = '<version>' 
    }
}
```

**Comment by dnfield** [comment]
That didn't quite work, trying something based on https://stackoverflow.com/questions/44141076/compilekotlin-block-in-build-gradle-file-throws-error-could-not-find-method-com

**Comment by dnfield** [comment]
Unfortunately this means we have to use the kotlin plugin which means we have to take more dependencies, but this is now passing locally with no warnings.

@blasten - do we get much value from using leakcanary?

**Comment by blasten** [comment]
Ideally, we keep leakcanary. We don't use it a lot, but it's worth doing more memory-leak tests in the future.

**Review by blasten — APPROVED** [review]
LGTM

**Pull request merged**
