### PR TITLE
[impeller] use greater equal rather than greater depth compare.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Marking ready for review for golden testing

Fixes https://github.com/flutter/flutter/issues/153504
Fixes some other ones too?

It seems like metal and vulkan are already behaving like they are using greater equal depth compare. GL behaves correctly like greater compare, but that leads to rendering bugs. Just switch it to greater equal

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I think the new golden diffs look better but I'm not familiar with them. FYI @flar maybe?

**Review by chinmaygarde — APPROVED** [review]
This fixes https://github.com/flutter/flutter/issues/157885 as well. I left some notes on the differences I see your linked issue. I also don't see the golden diffs though.

**Comment by gaaclarke** [comment]
note: here's the golden results https://flutter-engine-gold.skia.org/search?crs=github&issue=56310&negative=true&patchsets=4&positive=true

**Review by gaaclarke — APPROVED** [review]

**Comment by chinmaygarde** [comment]
The eye still isn't quite right though.
Screenshot 2024-11-01 at 1 14 43 PM

**Comment by jonahwilliams** [comment]
That looks correct to me?

**Comment by gaaclarke** [comment]
I didn't see a cap, I saw it more like one of these situations:
giphyhomer

**Pull request merged**
