### PR TITLE
Clang-tidy: Fixed math on shard-id validator.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798099822610209889/+/u/test:_lint_host_debug/stdout

That resulted in revert: https://flutter-review.git.corp.google.com/c/recipes/+/35742

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
Here is recipe reland: https://flutter-review.git.corp.google.com/c/recipes/+/35781

**Review by cyanglaz — APPROVED** [review]
LGTM

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
One of the new tests is failing.

**Comment by gaaclarke** [comment]
> One of the new tests is failing.

Great, works locally.  Digging in...

**Comment by gaaclarke** [comment]
Looks like the test is being run on the bot with a non existent path for compile_commands.json:
```
Test "shard-id valid": Failed
In test "shard-id valid" Expect.isNull(actual: <ERROR: Build commands path /Volumes/Work/s/w/ir/cache/builder/src/out/host_debug/compile_commands.json doesn't exist.>) fails.
#0      Expect._fail (package:expect/expect.dart:698:5)
#1      Expect.isNull (package:expect/expect.dart:143:5)
#2      isNull (package:async_helper/async_minitest.dart:215:10)
#3      expect (package:async_helper/async_minitest.dart:70:4)
#4      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/tools/clang_tidy/test/clang_tidy_test.dart:125:5)
#5      Test.run.<anonymous closure>.<anonymous closure> (package:litetest/src/test.dart:69:21)
#6      new Future.<anonymous closure> (dart:async/future.dart:253:37)
#7      _rootRun (dart:async/zone.dart:1390:47)
#8      _CustomZone.run (dart:async/zone.dart:1300:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#11     _rootRun (dart:async/zone.dart:1398:13)
#12     _CustomZone.run (dart:async/zone.dart:1300:19)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:26)
```

I'm going for a walk and I'll come back to figure something out.

**Comment by gaaclarke** [comment]
Turns out the CI bot runs the tests differently than how it is documented they should be run locally.  I've removed the x factor from the test and should pass in both places now.

**Comment by gaaclarke** [comment]
oh my god, how many walls am I going to run into... fixed the format error

**Comment by gaaclarke** [comment]
I'm landing, ignoring the flutter-gold check.  There is no way the changes are related.  I've notified the team and flutter gold expert.

**Pull request merged**
