### PR TITLE
Add Rect.fromCenter() constructor

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by tvolkert** [comment]
> Is there a reason why it can't be const?

Because they refer to `dx` and `dy` of the offset, which excludes them from being const since those fields are getters.

I updated `Rect.fromCircle` to delegate to `Rect.fromCenter`.

PTAL

**Comment by jamesderlin** [comment]
> > Is there a reason why it can't be const?
> 
> Because they refer to `dx` and `dy` of the offset, which excludes them from being const since those fields are getters.

Ah. It is unintuitive that getters on an immutable object that has a const constructor can't propagate const-ness. =( (Do you know why are Offset.dx/dy are getters instead of just being `final` members?)

LGTM.

**Comment by jonahwilliams** [comment]
Both fields and getters are virtual in Dart, it would make no difference anyway

**Comment by tvolkert** [comment]
> Tests?

Done

**Comment by cbracken** [comment]
Please wait until internal embedders have been updated before making use of this in framework code.

**Pull request merged**
