### PR TITLE
Roll src/third_party/dart 1bd36d694d..674fd0e060 (48 commits)

### PR DESCRIPTION
**Pull request by a-siva**
674fd0e060 [vm runtime] Dynamically disable dual mapping of code on some platforms
0bd674c374 [VM-Runtime] set environment when creating detached process
578fdb0408 Call becomeMap/becomeSet() in AstCloner.
382cd59388 Update completion target tests for new map syntax
1db664764a Revert "Copy abi dills in create_sdk build rule"
a39833d957 Reland "Reland "[VM runtime] Dual mapping of executable pages.""
49a0502f49 Copy abi dills in create_sdk build rule
23eb57c2bf Revert "[vm/ffi] Support Windows 64 bit"
22c2c7ffd8 Sort declarations in build_mode.dart
e2b5559c77 [infra] Use gclient.py to apply patches to bypass update_depot_tools
f4b524cdf1 [vm] Extract reading of parameter covariance attributes
16e40cef2f Generate a diagnostic when a set or map literal is ambiguous
b89d08355b [infra] Only move coredump files on shards
7f812dea1a [vm/ffi] Support Windows 64 bit
469da726d6 [vm] Put covariance attributes into Field flags
09087490e2 update hasFix lookup table
bb7b5fcd37 add missing fix tests
48a5c3825a assist to convert to absolute imports
b3927f66df [gardening] Mark tests that crash as crashing
2d6ddf2aff Remove unnecessary override from PartialResolverVisitor
ba3b9b3b65 Sort static_type_analyzer_test.dart
1edc6d4b4d [infra] Fix approve_results not erroring properly if tryjobs lack results.
1a196d43a7 [VM/AOT] Execute catch-entry moves in parallel (our AOT doesn't generate non-cyclic moves)
6a2aa920cd Support pragma annotations through ir constants
d3d077090d [VM/FrontendServer] Add 3head patch to frontend server after breaking API changes
016e3172d1 Default parameters, more metadata, import dart:core.
853d38896e [VM/AOT] Fixes incorrect deserialization of catch entry moves
3cf7d6a9c7 [tests] Changing expected cast errors to type errors for collections tests
b87c44d6b3 Generate diagnostic for non-bool conditions in if elements
74395d940f Comment out test_import_short_absolute that fails on Windows.
7c1544898d [vm] Decouple flow graph building of implicit getters and setters from kernel reading
57f4da318c [vm, gc] The mutator's TLAB and the interpreter's lookup cache must be visited even if the mutator is unscheduled.
15842d4583 Build more import scopes, support for enums.
f2029f54cd Fix type inference of map/set literals when the context is a type parameter.
11b9481403 [vm/frontend] Fix frontend_server_test on Windows.
bfb30bffe0 Fix a bug in the ConstantVerifier so that conditional elements are lazily verified
ed1f956991 Fix the abi dills download script
8f03ae05ff [infra] Add --list-configurations option to test.dart.
9faca2fa68 [vm] Document lifetime requirements of arguments to Dart_TimelineEvent.
295ea59385 [vm] Give functions compiled through Dart_LoadCompilationTrace a non-zero usage counter.
def0b21225 [infra] Fix test.dart saying untested configurations don't exist.
abd1854176 Fix recording of map/literal context type.
a8b3461f2e New summaries work snapshot.
9e7627b6a1 Re-land "Eliminate uses of old AST node types from pkg/analyzer/lib/src/summary"
210361ae63 Move IgnoreInfo out of the task model code base
440b4cd84e Insert implicit casts when setting interface targets
567d552de8 [infra] Add versionchecker and debianpackage to test matrix
576c4c71d9 [CFE] Always clone subexpressions of unevaluated constants.

### CODE REVIEW

**Comment by aam** [comment]
I think the changelist for this PR is actually:
```
1bd36d694d [vm runtime] Dynamically disable dual mapping of code on some platforms.
0bd674c374 [VM-Runtime] set environment when creating detached process
578fdb0408 Call becomeMap/becomeSet() in AstCloner.
382cd59388 Update completion target tests for new map syntax
1db664764a Revert "Copy abi dills in create_sdk build rule"
a39833d957 Reland "Reland "[VM runtime] Dual mapping of executable pages.""
49a0502f49 Copy abi dills in create_sdk build rule
23eb57c2bf Revert "[vm/ffi] Support Windows 64 bit"
22c2c7ffd8 Sort declarations in build_mode.dart
e2b5559c77 [infra] Use gclient.py to apply patches to bypass update_depot_tools
f4b524cdf1 [vm] Extract reading of parameter covariance attributes
16e40cef2f Generate a diagnostic when a set or map literal is ambiguous
b89d08355b [infra] Only move coredump files on shards
7f812dea1a [vm/ffi] Support Windows 64 bit
469da726d6 [vm] Put covariance attributes into Field flags
09087490e2 update hasFix lookup table
bb7b5fcd37 add missing fix tests
48a5c3825a assist to convert to absolute imports
b3927f66df [gardening] Mark tests that crash as crashing
2d6ddf2aff Remove unnecessary override from PartialResolverVisitor
ba3b9b3b65 Sort static_type_analyzer_test.dart
1edc6d4b4d [infra] Fix approve_results not erroring properly if tryjobs lack results.
1a196d43a7 [VM/AOT] Execute catch-entry moves in parallel (our AOT doesn't generate non-cyclic moves)
6a2aa920cd Support pragma annotations through ir constants
d3d077090d [VM/FrontendServer] Add 3head patch to frontend server after breaking API changes
016e3172d1 Default parameters, more metadata, import dart:core.
853d38896e [VM/AOT] Fixes incorrect deserialization of catch entry moves
3cf7d6a9c7 [tests] Changing expected cast errors to type errors for collections tests
b87c44d6b3 Generate diagnostic for non-bool conditions in if elements
74395d940f Comment out test_import_short_absolute that fails on Windows.
7c1544898d [vm] Decouple flow graph building of implicit getters and setters from kernel reading
57f4da318c [vm, gc] The mutator's TLAB and the interpreter's lookup cache must be visited even if the mutator is unscheduled.
15842d4583 Build more import scopes, support for enums.
f2029f54cd Fix type inference of map/set literals when the context is a type parameter.
11b9481403 [vm/frontend] Fix frontend_server_test on Windows.
bfb30bffe0 Fix a bug in the ConstantVerifier so that conditional elements are lazily verified
ed1f956991 Fix the abi dills download script
8f03ae05ff [infra] Add --list-configurations option to test.dart.
9faca2fa68 [vm] Document lifetime requirements of arguments to Dart_TimelineEvent.
295ea59385 [vm] Give functions compiled through Dart_LoadCompilationTrace a non-zero usage counter.
def0b21225 [infra] Fix test.dart saying untested configurations don't exist.
abd1854176 Fix recording of map/literal context type.
a8b3461f2e New summaries work snapshot.
9e7627b6a1 Re-land "Eliminate uses of old AST node types from pkg/analyzer/lib/src/summary"
210361ae63 Move IgnoreInfo out of the task model code base
440b4cd84e Insert implicit casts when setting interface targets
567d552de8 [infra] Add versionchecker and debianpackage to test matrix
576c4c71d9 [CFE] Always clone subexpressions of unevaluated constants.
```

That is based on the change of dart_rev:
```
-  'dart_revision': '674fd0e060a33deeedbc2f8fae7c32c7e3f0d8d5',
+  'dart_revision': '1bd36d694dba00d92651fcd2340e91d5a74efb03',
```

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/commit/9faca2fa68 seems to be the culprit of out of memory errors on flutter gallery benchmark:
```
[flutter_gallery__start_up] [STDOUT] stdout: [        ] Sending to VM service: _getVMTimeline({})
[flutter_gallery__start_up] [STDOUT] stdout: [+53930 ms] E/DartVM  (12543): ../../third_party/dart/runtime/platform/text_buffer.cc: 141: error: Out of memory.
[flutter_gallery__start_up] [STDOUT] stdout: [        ] E/DartVM  (12543): version=2.2.1-dev.1.0.flutter-None (Mon Mar 11 18:04:59 2019 +0000) on "android_arm"
[flutter_gallery__start_up] [STDOUT] stdout: [        ] E/DartVM  (12543): thread=12560, isolate=(null)(0x0)
[flutter_gallery__start_up] [STDOUT] stdout: [        ] E/DartVM  (12543):   [0x95fcc217] Unknown symbol
[flutter_gallery__start_up] [STDOUT] stdout: [   +2 ms] E/DartVM  (12543):   [0x95fcc217] Unknown symbol
[flutter_gallery__start_up] [STDOUT] stdout: [        ] E/DartVM  (12543): -- End of DumpStackTrace
[flutter_gallery__start_up] [STDOUT] stdout: [        ] F/libc    (12543): Fatal signal 6 (SIGABRT), code -6 in tid 12560 (1.gpu)
[flutter_gallery__start_up] [STDOUT] stdout: [  +87 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[flutter_gallery__start_up] [STDOUT] stdout: [        ] Build fingerprint: 'motorola/athene/athene:7.0/NPJS25.93-14.7-8/6:user/release-keys'
[flutter_gallery__start_up] [STDOUT] stdout: [        ] Revision: 'p2a0'
[flutter_gallery__start_up] [STDOUT] stdout: [        ] ABI: 'arm'
[flutter_gallery__start_up] [STDOUT] stdout: [        ] pid: 12543, tid: 12560, name: 1.gpu  >>> io.flutter.demo.gallery <<<
[flutter_gallery__start_up] [STDOUT] stdout: [        ] signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     r0 00000000  r1 00003110  r2 00000006  r3 00000008
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     r4 95600978  r5 00000006  r6 95600920  r7 0000010c
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     r8 955feabc  r9 918fda60  sl 955feac0  fp 00000004
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     ip 0000000c  sp 955fe958  lr af94e3e7  pc af950c44  cpsr 200e0010
[flutter_gallery__start_up] [STDOUT] stdout: [  +27 ms] backtrace:
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #00 pc 00049c44  /system/lib/libc.so (tgkill+12)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #01 pc 000473e3  /system/lib/libc.so (pthread_kill+34)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #02 pc 0001d535  /system/lib/libc.so (raise+10)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #03 pc 00019081  /system/lib/libc.so (__libc_android_abort+34)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #04 pc 000170e4  /system/lib/libc.so (abort+4)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #05 pc 004afe1b  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #06 pc 008a6995  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #07 pc 008a6f45  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #08 pc 0074de91  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #09 pc 0074c36d  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #10 pc 007f9195  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #11 pc 007f39a9  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #12 pc 00809fad  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #13 pc 0084200f  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #14 pc 004b8a7f  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #15 pc 004b4c13  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #16 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #17 pc 004b4c55  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #18 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #19 pc 004b34f3  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #20 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #21 pc 004b34f3  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #22 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #23 pc 004b4c55  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #24 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #25 pc 004b4c55  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #26 pc 004b2993  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #27 pc 004b4c55  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #28 pc 004b2b91  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #29 pc 004b1ac7  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #30 pc 004da7c3  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #31 pc 004daac5  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #32 pc 004dac51  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #33 pc 004da9c9  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #34 pc 004dab95  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #35 pc 004b84e1  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #36 pc 004b99e5  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #37 pc 00011f47  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+610)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #38 pc 00011c57  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #39 pc 0000b6af  /system/lib/libandroid.so (ALooper_pollOnce+50)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #40 pc 004b9a7f  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #41 pc 004b767f  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #42 pc 004b88b1  /data/app/io.flutter.demo.gallery-1/lib/arm/libflutter.so (offset 0x48b000)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #43 pc 00046eb3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
[flutter_gallery__start_up] [STDOUT] stdout: [        ]     #44 pc 00019acd  /system/lib/libc.so (__start_thread+6)
```

cc @rmacnak-google

**Comment by rmacnak-google** [comment]
@chinmaygarde Could the engine be dynamically allocating a trace label?

**Comment by jason-simmons** [comment]
@GaryQian https://github.com/dart-lang/sdk/commit/9faca2fa68 is also responsible for the timeouts in devicelab tests seen during the recent engine roll

Flutter's scoped trace begin/end wrappers are passing a buffer from a std::string into Dart_TimelineEvent:
https://github.com/flutter/engine/blob/master/fml/trace_event.h#L210

This will be unsafe if Dart_TimelineEvent is no longer making a copy of the label.

**Pull request merged**
