### PR TITLE
Rename the blink namespace to flutter.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Some components in the Flutter engine were derived from the forked blink codebase. While the forked components have either been removed or rewritten, the use of the blink namespace has mostly (and inconsistently) remained. This renames the blink namesapce to flutter for consistency. There are no functional changes in this patch.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
I am deciding whether to move the shell namespace into flutter or just rename that namespace to flutter too. Thoughts?

**Comment by jason-simmons** [comment]
LGTM

I'd vote for removing the `shell` namespace and moving everything to `flutter`

**Comment by chinmaygarde** [comment]
> I'd vote for removing the `shell` namespace and moving everything to `flutter`.

Roger. And `fml`?

**Comment by liyuqian** [comment]
> > I'd vote for removing the `shell` namespace and moving everything to `flutter`.
> 
> Roger. And `fml`?

Yes! `fml` too please

**Comment by zanderso** [comment]
This is a breaking change. Do you have compensating updates to Fuchsia's flutter_runner prepared?

**Pull request merged**
