### PR TITLE
Use the tonic::HandleTable

### PR DESCRIPTION
**Pull request by ianloic**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
What is the state of this PR?

**Comment by ianloic** [comment]
Derailed by my vacation and Adam's leave. I hope to get back to this this
week-ish.

**Comment by Hixie** [comment]
@ianloic I'm going to close this PR in the meantime, please don't hesitate to reopen it when you're ready to do whatever needs to be done with it.

**Pull request closed without merging**
