### PR TITLE
Update Dart

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by Hixie** [comment]
This may have caused a regression. It appears the _sdkext file in the sky_engine package now points to a directory that doesn't match where the dart_ui_internals library is actually placed.

**Comment by abarth** [comment]
Thanks, will look.

**Comment by Hixie** [comment]
Actually, looking closer the output matches what i think `sky_engine/BUILD.gn` is trying to generate, so it might not be related to this.

It says in part:
```
...
  sdk_ext_directory = "$root_gen_dir/sky/bindings"
  sdk_ext_files = [
    "//sky/engine/bindings/internals.dart",
...
```

...and indeed the output ends up being that `sky_engine/lib/_sdkext` points to `sky_engine/sky/bindings` but the file is actually in `sky_engine/sdk_ext/sky/engine/bindings/internals.dart`.

**Comment by abarth** [comment]
I should probably just delete internals.dart.  That bug has been assigned to me for a while anyway.

**Comment by Hixie** [comment]
That works too.

**Comment by abarth** [comment]
Removal in https://github.com/flutter/engine/pull/2397

**Pull request merged**
