### PR TITLE
Roll to mojo_sdk 0.2.9.

### PR DESCRIPTION
**Pull request by tonygentilcore**

### CODE REVIEW

**Comment by abarth** [comment]
RSLGTM

**Comment by Hixie** [comment]
This broke Flutter's framework.

**Comment by tonygentilcore** [comment]
Do you have repro steps? All the tests seemed happy.

**Comment by Hixie** [comment]
Just "flutter analyze --flutter-repo --debug" should catch the problems.

**Comment by Hixie** [comment]
Oh, you also have to update your flutter package pubspec.yaml to point to the local sky_services.

**Comment by tonygentilcore** [comment]
Updating the `pubspec.yaml` is the step I missed. I'll look into the errors now, fix them up and also mention this in https://github.com/flutter/engine/wiki/Rolling-Mojo-and-Chromium.

If this is blocking anything we can revert.

**Comment by Hixie** [comment]
It's not blocking anything. I only noticed because I happen to be testing my own sky_services changes. I don't think anyone else is doing that today.

**Comment by tonygentilcore** [comment]
BTW, does that pubspec change just look like this:

```diff
diff --git a/packages/flutter/pubspec.yaml b/packages/flutter/pubspec.yaml
index 44a6af9..ef66cca 100644
--- a/packages/flutter/pubspec.yaml
+++ b/packages/flutter/pubspec.yaml
@@ -8,8 +8,10 @@ dependencies:
   collection: '>=1.1.3 <2.0.0'
   intl: '>=0.12.4+2 <0.13.0'
   material_design_icons: '>=0.0.3 <0.1.0'
-  sky_engine: 0.0.83
-  sky_services: 0.0.83
+  sky_engine:
+    path: ../../../engine/src/sky/packages/sky_engine
+  sky_services:
+    path: ../../../engine/sky/packages/sky_services
   vector_math: '>=1.4.5 <2.0.0'
   quiver: '>=0.21.4 <0.22.0'
```

**Comment by Hixie** [comment]
Yes. Actually for `flutter analyze` these might not be necessary, I think `--debug` forces both of these. You should only need these to actually run the code. I think.

**Comment by Hixie** [comment]
Turns out you need:
```diff
diff --git a/packages/flutter/pubspec.yaml b/packages/flutter/pubspec.yaml
index 771a454..d79f36f 100644
--- a/packages/flutter/pubspec.yaml
+++ b/packages/flutter/pubspec.yaml
@@ -8,12 +8,10 @@ dependencies:
   collection: '>=1.1.3 <2.0.0'
   intl: '>=0.12.4+2 <0.13.0'
   material_design_icons: '>=0.0.3 <0.1.0'
-#  sky_engine: 0.0.83
+  sky_engine: 0.0.83
 #  sky_services: 0.0.83
-  sky_engine:
-    path: ../../../engine/src/
   sky_services:
-    path: ../../../engine/src/
+    path: ../../../engine/src/out/Debug/gen/dart-pkg/sky_services
   vector_math: '>=1.4.5 <2.0.0'
   quiver: '>=0.21.4 <0.22.0'
```
...then run `dev/update_packages.dart`, then fix the problems, then revert the pubspec.yaml change. You need this because otherwise it doesn't pick up the mojo_sdk version requirement change from the engine repo's services pubspec.yaml.

**Pull request merged**
