### PR TITLE
Delete and create iOS simulator before running Scenario app test

### PR DESCRIPTION
**Pull request by vashworth**
Make iOS Scenario app tests create the simulator it needs before the tests. Also, delete any existing matching simulators to prevent duplicates.

Fixes https://github.com/flutter/flutter/issues/143870.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — COMMENTED** [review]
DBC: Not for this PR. My sense is that the logic in this script is outgrowing what we'd normally like to maintain in a bash script. We should consider porting this to Python, or ideally Dart if possible.

**Comment by zanderso** [comment]
> @zanderso What does DBC mean?

Drive-by comment.

**Review by zanderso — APPROVED** [review]

**Comment by vashworth** [comment]
> My sense is that the logic in this script is outgrowing what we'd normally like to maintain in a bash script. We should consider porting this to Python, or ideally Dart if possible.

I filed a new issue: https://github.com/flutter/flutter/issues/143953

**Review by hellohuanlin — APPROVED** [review]
Does it incur additional time (how much) when running on CI

**Comment by vashworth** [comment]
> Does it incur additional time (how much) when running on CI

We do something similar in packages and it takes ~3.9 seconds
Example: See step 12.15 (which attempts to delete and then creates simulator):
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20custom_package_tests%20master/10823/overview

**Pull request merged**
