### PR TITLE
[Impeller] make strokes slightly lighter.

### PR DESCRIPTION
**Pull request by jonahwilliams**
We can set the minimum stroke width to 0.5 to guarantee at least one hit of 4x MSAA coverage. This doesn't fix stroke fidelity issues but it does make it a bit better.

https://github.com/flutter/flutter/issues/144313

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Tested via goldens.

**Review by gaaclarke — COMMENTED** [review]
Is there a test that just draws a stroke?  I'm not seeing one that shows up in the golden diffs.  Considering this change I think we should have that.  Otherwise the justification and the code lgtm.

edit: I think the test should draw a line at rotation 0, 30, 45, 60, 90.

**Review by bdero — APPROVED** [review]

**Comment by jonahwilliams** [comment]
@gaaclarke how about a circle?

**Comment by gaaclarke** [comment]
> @gaaclarke how about a circle?

Yea, sounds good.

**Comment by gaaclarke** [comment]
The circle in the golden image seems kind of patchy.  Do we have to scale this stroke width by the content scale (screen dpi)?

**Comment by jonahwilliams** [comment]
Yeah these actually look wrong. needs to investigate what is happening here.

**Comment by jonahwilliams** [comment]
I wonder if the GLES goldens don't have MSAA enabled

**Comment by jonahwilliams** [comment]
Yeah, GLES has no MSAA. I made the min size conditional based on the sample count.

**Review by gaaclarke — APPROVED** [review]
lgtm!

**Pull request merged**
