### PR TITLE
Manually revert TLHC optimizations, holding on to width/height changes.

### PR DESCRIPTION
**Pull request by matanlurey**
Reverts https://github.com/flutter/engine/pull/50065 due to https://github.com/flutter/flutter/issues/142459.

[Discord](https://discord.com/channels/608014603317936148/608020293944082452/1201589744690270338):

> It looks like the failing tests are the resize tests for webview_flutter and google_maps_flutter
I can reproduce the failure locally for: https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart#L296

I manually merged this to keep https://github.com/flutter/engine/pull/50066.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
> /cc also @zanderso @dnfield, to add as an example of "the engine [CI] doesn't catch engine bugs".

In this case the framework CI didn't catch it either; we may want to create a simple flutter/flutter integration test for that can repro it and add it there (sounds like probably an integration test with a trivial app containing a platform view that it resizes).

**Comment by matanlurey** [comment]
> In this case the framework CI didn't catch it either; we may want to create a simple flutter/flutter integration test for that

Totally. I've added it as a check item here: https://github.com/flutter/flutter/issues/142006.

**Pull request merged**
