### PR TITLE
Default the CanvasKit base URL to local artifacts.

### PR DESCRIPTION
**Pull request by hterkelsen**
Reverts flutter/engine#40700

A fix for the g3 bug b/275455289 is out for review. We should be able to safely reland the original change.

### CODE REVIEW

**Comment by yjbanov** [comment]
Renamed the PR according to https://github.com/flutter/flutter/wiki/Tree-hygiene#avoid-revert-revert-revert-revert-fix-foo-commit-messages

**Review by yjbanov — APPROVED** [review]
lgtm

**Review by itsjustkevin — APPROVED** [review]
Thank you for the quick fix!  

Is there a possible test that could cover this case in the future?

**Comment by hterkelsen** [comment]
> Thank you for the quick fix!
> 
> Is there a possible test that could cover this case in the future?

Good idea. I'll see if I can add one to my PR in google3

**Pull request merged**
