### PR TITLE
[CP][Impeller] Improve accuracy of glyph spacing (#41101)

### PR DESCRIPTION
**Pull request by bdero**
CP for https://github.com/flutter/engine/pull/41101

### CODE REVIEW

**Comment by zanderso** [comment]
I believe the correct branch is `3.10-candidate.1`. cc @CaseyHillers to confirm.

**Comment by CaseyHillers** [comment]
Correct, the beta is based on 3.10-candidate.1. If you're aiming for a Google CP, please file a bug with more context.

**Comment by zanderso** [comment]
Ooooh. I tried just changing the target branch, but I think the branch for the pull request has to be rebased on candidate.1 as well.

**Comment by bdero** [comment]
Alrighty, fixed this up to point to candidate.1

**Comment by zanderso** [comment]
@CaseyHillers do you know why the `ci.yaml` check is failing?

**Comment by bdero** [comment]
Looks like this is good to go

**Review by zanderso — APPROVED** [review]
lgtm

release team will handle merging.

**Pull request merged**
