### PR TITLE
[Impeller] Fix the issue that 'coverage_coords' is incorrectly calculated in 'FillPathGeometry::GetPositionUVBuffer'

### PR DESCRIPTION
**Pull request by ColdPaleLight**
fix https://github.com/flutter/flutter/issues/127183

## without patch
3Q7pxQTjei
## whti patch
LRG6o1t9mm

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM. Should we cherry pick this like the other one?

**Review by dnfield — APPROVED** [review]
LGTM. Should we cherry pick this like the other one?

**Comment by jonahwilliams** [comment]
Throw in on the pile!

**Comment by dnfield** [comment]
@ColdPaleLight do you feel comfortable creating the CP PR and issue? See https://github.com/flutter/flutter/issues/new?assignees=itsjustkevin%2Ccaseyhillers&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight do you feel comfortable creating the CP PR and issue? See https://github.com/flutter/flutter/issues/new?assignees=itsjustkevin%2Ccaseyhillers&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E

Sure, here is the cp https://github.com/flutter/flutter/issues/127250

**Pull request merged**
