### PR TITLE
Android: Made sure we get the initial route from the intent.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes b/271100292

Edit: Fixes https://github.com/flutter/flutter/issues/121244.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
attn @math1man

**Comment by camsim99** [comment]
Oh I was working on this here but I did something different I think because I thought the cause was different: https://github.com/flutter/engine/pull/40119. Does this fix it? There's a repro here https://github.com/flutter/flutter/issues/121244

**Comment by math1man** [comment]
This LGTM. I think this is a more consistent and efficient fix than https://github.com/flutter/flutter/issues/121244

**Comment by gaaclarke** [comment]
This fix was based off of the debugging that @math1man did.  His analysis makes sense to me although @camsim99 will probably have a better sense than me about the different flows through this code.

Assuming that this works, this fix seems preferable.  @math1man made a good point that there are some temporal dependencies about when you an access the activity so making sure our scenario apps pass on ci will be important.  It would be nice if he could test the fix in his app just to make sure.

**Comment by math1man** [comment]
I've verified this fix locally in my app and confirmed it resolves the issue.

I would say that my biggest reason to prefer this over https://github.com/flutter/flutter/issues/121244 is that it is closer to what the behavior was before https://github.com/flutter/engine/pull/38367 introduced this regression.

**Comment by camsim99** [comment]
cc @reidbaker

**Review by camsim99 — APPROVED** [review]
Lgtm!

**Pull request merged**
