### PR TITLE
[Impeller] libImpeller: Initialize the base paragraph style lazily.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Thanks to the @lyceel for the failing test case.
Screenshot 2024-10-15 at 4 01 27 PM

### CODE REVIEW

**Comment by chinmaygarde** [comment]
@flar says @jason-simmons might also be a good reviewer.

**Comment by chinmaygarde** [comment]
The distinction between the paragraph and text styles isn't super clear in txt. But I suppose it makes sense that you can't match text styles with different alignments and directions within a single text frame. This makes it so that the first opinion holds.

**Comment by whiskeyPeak** [comment]
@chinmaygarde Would there be any chance of adding a custom glyph layout system here instead of relying on `ImpellerParagraphBuilderBuildParagraphNew`? There are a couple of flutter text layout performance issues that this could help with here.

https://github.com/flutter/flutter/issues/132421
https://github.com/flutter/flutter/issues/114158
https://github.com/flutter/flutter/issues/92173

**Review by zanderso — APPROVED** [review]

**Comment by chinmaygarde** [comment]
That'd be a pretty involved undertaking. This API for external standalone Impeller users initially didn't even have typography but that was a pretty common ask and building a full-featured text stack was a heavy lift. So we are pretty much only exposing what we already have in `impeller.h` instead of building new capabilities.

**Pull request merged**
