### PR TITLE
Roll Dart for FIDL2

### PR DESCRIPTION
**Pull request by ianloic**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by zanderso** [comment]
Was this an emergency of some sort? Otherwise, we like to follow the roll procedure here: https://github.com/flutter/engine/wiki/Rolling-Dart

**Comment by aam** [comment]
Hm, there was(is) another roll in the progress https://github.com/flutter/engine/pull/4905

**Comment by aam** [comment]
Let me revert this PR(it would have failed travis check since it didn't have license file updates)  and follow-up with #4905 which should pick dart changes.

**Pull request merged**
