### PR TITLE
[wip]  Move Fuchsia to Embedder API

### PR DESCRIPTION
**Pull request by arbreng**
This allows removing *all* Fuchsia-specific code from flow/, and
removing all non-embedder dependencies from the flutter_runner.

It also decouples the compositor's scene graph from Flutter's scene
graph, massively reducing render workload and memory allocations.

As a bonus, we get to delete thousands of lines of old code that
was only around for Fuchsia :)

### CODE REVIEW

**Comment by gw280** [comment]
Can we figure out a way to break this patch up into isolated chunks? Right now the size of this makes me very very uneasy from a risk perspective.

**Comment by mikejurka** [comment]
George— this is still WIP

**Comment by arbreng** [comment]
Still WIP:  Currently based off of commit 0e8ed2715

**Comment by arbreng** [comment]
Still WIP but with this PR things are rendering now

**Comment by cbracken** [comment]
@arbreng I know a ton of progress has been made here in the last few months. I'm assuming that this PR is pretty stale at this point and going to close. If that's a mistake, please let me know and re-open.

**Pull request closed without merging**
