### PR TITLE
Fix DOM-based ParagraphRuler.hitTest()

### PR DESCRIPTION
**Pull request by photon3108**
## Description
If you tap the **nested** `TextSpan`, it doesn't received the tap event by `TapGestureRecognizer`. That's because `DOM-based` implementation of `ParagraphRuler.hitTest()` doesn't pick the **inner-most** `TextSpan` up. I fixed it by arranging the search path with breadth-first traversal. There are more explanations in the comments of test-case.

## Issues
Fixed: flutter/flutter#46975
Related: flutter/flutter#33523

## Tests
I added a test-case for general implementation and that covers both cases of `DOM-based` and `Canvas-based` implementation.

### CODE REVIEW

**Comment by photon3108** [comment]
@googlebot I signed it!

**Comment by photon3108** [comment]
@jason-simmons Hi Jason. You were assigned to the default reviewer by Github. Are there anything I can improve this PR?

**Comment by mdebbar** [comment]
@photon3108 I don't think @jason-simmons will be reviewing this PR as it's a web-only change. @ferhatb and my approvals should be good enough. Please wait until all the checkmarks become green then merge the PR.

Thanks again for helping us improve Flutter for web!

**Comment by photon3108** [comment]
@mdebbar Github doesn't authorize me to merge this issue. All are green but there is no merge button. I thought you were waiting for @jason-simmons' review. Could you help me merge it? Thanks.

**Comment by jlubeck** [comment]
This is still broken on `Flutter v1.17.0-3.4.pre`

**Comment by jlubeck** [comment]
On further investigating, looks like it breaks when the TextAlign used is something other than left. 
If you actually tap on the area where the text WOULD be located if left was used, it detects it there. So in my specific case, I need to tap on an empty area next to the centered paragraph to have it detect it. 

@photon3108 I'm tagging you since you are the contributor.

**Pull request merged**
