### PR TITLE
Use Dart_ListGetRange instead of multiple calls to Dart_ListGetAt

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

Can you add information about the perf impact to the commit description?

**Comment by krisgiesing** [comment]
Nice. Maybe we can look for other uses of Dart_ListGetAt and do a similar optimization?

**Comment by jason-simmons** [comment]
Added benchmark results.

Dart_ListGetAt is also used by DartConverter<Vector>, as well as some Mojo glue functions.

I can take a look at the DartConverter<Vector> case.  This is used by some of the more complex Canvas APIs that might be used by games.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
