### PR TITLE
[Impeller] sorted commonly used default pipelines first

### PR DESCRIPTION
**Pull request by gaaclarke**
A minor optimization that places default pipelines that are synchronized upon in the `InitializeCommonlyUsedShadersIfNeeded` first in the queue to be created.

issue: https://github.com/flutter/flutter/issues/145843

sequence diagram of the synchronization:
pipeline-seq

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
I think we can do more to fix the linked issue.  This was just an easy tweak in the meantime while we look into more invasive solutions.

**Review by jonahwilliams — APPROVED** [review]
LGTM, good idea!

**Comment by chinmaygarde** [comment]
Its hard to gauge if this just kicks the can down the road and blocks on the first frame instead. Also, and though I have no qualms about landing this as-is, I bet this is hard to tune and harder still to test.

How about about giving these the compilation jobs to the job scheduler that maintains a std::priority_queue of procs ordered by the last time they were requested and pops from that queue to the concurrent task runner. The get of the future (if no already fulfilled) can bump the place of the proc in the priority queue. That way, the jobs that are most eagerly needed will skip to the front of the job queue automatically.

**Comment by jonahwilliams** [comment]
I don't know if I would invest that much effort in this kind of change. We may need to completely rethink how we bootstrap pipelines to be fast on Vulkan

**Comment by chinmaygarde** [comment]
Yeah, and the 2s was on old devices too and only on first launch. If this is the end of the line on investigating perf wins in this area, then great. If we keep spending time tinkering on this order, perhaps our time is better spent bringing down the counts, etc..

**Comment by jonahwilliams** [comment]
I think its still like 500ms on a Pixel 4/5 :(

**Comment by gaaclarke** [comment]
Yea, I think we can do more.  I'm actively looking into it.  This is just an easy tweak that relies on the worker queue being fifo.

**Pull request merged**
