### PR TITLE
Roll update to harfbuzz to 2.1.0

### PR DESCRIPTION
**Pull request by GaryQian**
This will require a 1px golden files update in the framework to roll.

### CODE REVIEW

**Comment by GaryQian** [comment]
Goldens diff: (1 white pixel middle-bottom-left)
diff

**Comment by GaryQian** [comment]
I re-ran tests this morning and it seems that the goldens diff is gone...

**Comment by liyuqian** [comment]
@GaryQian Patch failed because recently Github somehow removed all lines with only white spaces in its web UI... But those lines are important for patch. Click the `DOWNLOAD FULL LOGS` button and copy the diff there there. That should fix the problem. It's probably worthwhile to add this information to the wiki https://github.com/flutter/engine/tree/master/tools/licenses . @Hixie : are we deprecating all engine wikis? Is there a corresponding wiki in flutter/flutter?

**Comment by goderbauer** [comment]
I believe you forgot to run the second step of the license script on this change: https://github.com/flutter/engine/tree/master/tools/licenses#regenerate-license-files-only-works-on-linux

Since there were changes to lines other than the FILE lines you also needs to run the license script in release mode!

**Comment by GaryQian** [comment]
Ahh, my bad, I ran it, but then while trying to work around github removing whitespace-only lines, I must have reset my branch back, and removed it.

**Comment by goderbauer** [comment]
No worries, I am running it for you in my PR.

**Pull request merged**
