### PR TITLE
Add _embedder.yaml to sky_engine

### PR DESCRIPTION
**Pull request by johnmccutchan**
- Add dart:jni sources to sky_engine
- Add _embedder.yaml which defines all dart: libraries provided by sky_engine.
- Stop including _sdkext in sky_engine.

### CODE REVIEW

**Comment by johnmccutchan** [comment]
Fixes https://github.com/flutter/flutter/issues/1712

**Comment by johnmccutchan** [comment]
@abarth

**Comment by abarth** [comment]
LGTM!

**Comment by Hixie** [comment]
This seems to have broken the analyzer's ability to find the SDK. Am I holding it wrong?

**Comment by Hixie** [comment]
Based on chatting with @johnmccutchan, I think the key is that this didn't update the SDK we use (in the engine or in flutter). I'm reverting this for now in https://github.com/flutter/engine/pull/2432.

**Pull request merged**
