### PR TITLE
Revert "[ios_platform_view] only recycle maskView when the view is applying mutators #41573"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/engine#42115

Failing on the framework tree as in https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_views_scroll_perf_ios__timeline_summary/11103/overview

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
Eagerly landing revert to get rolls to the framework restarted.

**Comment by hellohuanlin** [comment]
thanks for the revert. curious how did you identify the root cause? did you repro on local machine?

**Comment by zanderso** [comment]
In the logs linked above, there is a native crash due to what looks like an error in managing the mask view lifetime:
```
[2023-05-22 19:08:51.304448] [STDOUT] stdout: [  +67 ms] * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
[2023-05-22 19:08:51.304508] [STDOUT] stdout: [        ]   * frame #0: 0x00000001835aaee4 libobjc.A.dylib`objc_retain_x2 + 16
[2023-05-22 19:08:51.304574] [STDOUT] stdout: [        ]     frame #1: 0x000000018c5fa6d0 UIKitCore`-[UIView _setMaskView:] + 36
[2023-05-22 19:08:51.304625] [STDOUT] stdout: [        ]     frame #2: 0x0000000104394ab0 Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView(long long) + 1096
[2023-05-22 19:08:51.304673] [STDOUT] stdout: [        ]     frame #3: 0x00000001047dbbd0 Flutter`flutter::PlatformViewLayer::Paint(flutter::PaintContext&) const + 48
[2023-05-22 19:08:51.304768] [STDOUT] stdout: [        ]     frame #4: 0x00000001047d274c Flutter`flutter::ContainerLayer::PaintChildren(flutter::PaintContext&) const + 88
[2023-05-22 19:08:51.304868] [STDOUT] stdout: [        ]     frame #5: 0x00000001047dcd90 Flutter`flutter::TransformLayer::Paint(flutter::PaintContext&) const + 84
...
```

**Pull request merged**
