### PR TITLE
[Impeller] Try replacing `*desc` with value/is_valid checks.

### PR DESCRIPTION
**Pull request by matanlurey**
Some discussion here: https://discord.com/channels/608014603317936148/1175215129135153202.

In short, `*<std::optional>` is [undefined behavior](https://en.cppreference.com/w/cpp/utility/optional/operator*). After talking to @bdero we are considering that this should never happen.

I thought of a few different approaches here, none of them are great. However given that this class is used quite minimally, this seems to jive with similar patterns we're using in scene/scene_context.

---

Feel free to push back or suggest alternatives, mostly proposing this to get brain juices flowing.

### CODE REVIEW

**Comment by matanlurey** [comment]
@bdero @jonahwilliams Friendly ping :)

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by bdero — APPROVED** [review]
Also LGTM :) Thanks.

**Comment by Hixie** [comment]
test-exempt: fixing a disabled lint so that we can enable it

**Pull request merged**
