### PR TITLE
Analysis cleanup of the Dart in the Engine repo

### PR DESCRIPTION
**Pull request by Hixie**
Includes some notable new documentation for BlendMode.

### CODE REVIEW

**Comment by aam** [comment]
This failed on engine buildbots with following error:
```
[141/144] ACTION //flutter/frontend_server:frontend_server(//build/toolchain/mac:clang_x64)
FAILED: gen/frontend_server.dart.snapshot 
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart --deterministic --packages=/b/build/slave/Mac_Engine/build/src/flutter/frontend_server/.packages --snapshot=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --snapshot-depfile=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot.d --snapshot-kind=app-jit /b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart --train --sdk-root=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/flutter_patched_sdk
Command failed: ./dart --deterministic --packages=/b/build/slave/Mac_Engine/build/src/flutter/frontend_server/.packages --snapshot=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --snapshot-depfile=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot.d --snapshot-kind=app-jit /b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart --train --sdk-root=/b/build/slave/Mac_Engine/build/src/out/host_debug_unopt/flutter_patched_sdk
output: Unhandled exception:
Could not import "package:frontend_server/server.dart" from "file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart": Packages file 'file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/.packages' not found.
null
```

**Comment by Hixie** [comment]
Odd. Do we not run `pub get` before that step? I wonder why it compiled locally.

**Comment by aam** [comment]
> Odd. Do we not run pub get before that step? I wonder why it compiled locally.

No, we don't. See https://github.com/flutter/engine/pull/3982#issuecomment-323213199

**Comment by Hixie** [comment]
See https://github.com/flutter/engine/pull/4562

**Comment by aam** [comment]
Would it be reasonable to roll this back while #4562 is being sorted out to unblock engine commits/rolls?

**Comment by Hixie** [comment]
It's landed now.

**Comment by aam** [comment]
Seems that engine buildbots still are not happy.

**Comment by Hixie** [comment]
New failure is just that the analyzer we're using is too old. When the Dart roll lands it'll fix it.

**Pull request merged**
