### PR TITLE
Ensure the destructor is called since it destroys the `EGLSurface` before creating a new onscreen surface.

### PR DESCRIPTION
**Pull request by Guokai-Cheng**
## Description

Detach from engine((FlutterView.detachFromFlutterEngine)) but FlutterTextureView / FlutterSurfaceView surface is not destroyed, then reattach to the engine(FlutterView.attachToFlutterEngine), it will crash !!!

## Related Issues

None.

## Tests

None.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Guokai-Cheng** [comment]
> @googlebot I signed it!

**Comment by Guokai-Cheng** [comment]
@googlebot I signed it!

**Comment by Guokai-Cheng** [comment]
@googlebot I signed it!

**Comment by Guokai-Cheng** [comment]
@googlebot I signed it!

**Comment by scutlight** [comment]
@liyuqian : Seems there is a bug of github, no reviewer is assigned, would you please have a look? Thanks!

**Comment by liyuqian** [comment]
Thanks for the PR! Would it be possible to add a unit test that would fail without this fix?

**Comment by Guokai-Cheng** [comment]
> Thanks for the PR! Would it be possible to add a unit test that would fail without this fix?

I have tried to add some case for this case, but I found that this problem only appeared on Android platform, and there is no any test suite that can run on Android platform, so i give up ...

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
