### PR TITLE
Fix the initialization of AndroidSurfaceFactoryImpl

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/68446

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
lgtm

**Review by gaaclarke — COMMENTED** [review]
What was causing the crash?  I read through this a few times and it looks good.  I don't understand what was broken though.

**Review by gaaclarke — COMMENTED** [review]
Could is the fact the argument is a shared_ptr instead of a weak_ptr all that was needed for a fix instead of pulling it into a setter?

**Comment by jason-simmons** [comment]
The crash happened because `surface_factory_` is null when `AndroidExternalViewEmbedder` is constructed.

Due to the cyclic dependency between `AndroidSurfaceFactoryImpl` and `AndroidExternalViewEmbedder` it's not possible to initialize both with constructor arguments.  One of the objects will need to acquire the pointer to the other after both objects have been constructed.

**Comment by flutter-github-sync** [comment]
To trigger Google-testing, contact a Google developer and ask them to review and approve http://CL/337941691

**Review by gaaclarke — APPROVED** [review]
Ahh yea there it is, thanks.  Sorry I missed that.  I would have thought our current tests would have caught that.

**Comment by iskakaushik** [comment]
Thanks for the fix @jason-simmons . This was the reason for having the `SetExternalViewEmbedder` in the [first place](https://github.com/flutter/engine/pull/21839#discussion_r504912011). I plan on refactoring the surface api to remove this cyclic dependency.

**Pull request merged**
