### PR TITLE
ios: Fixed the callback for the first frame so that it isn't predicated on having a splash screen.

### PR DESCRIPTION
**Pull request by gaaclarke**
Implemented by tweaking splash screen logic.

Relevant issue: https://github.com/flutter/flutter/issues/24519

### CODE REVIEW

**Comment by xster** [comment]
LGTM % tests

Either solution is ok. Though we probably have to answer a few questions about consistent indirections or not in the other PR.

**Comment by gaaclarke** [comment]
> LGTM % tests

I've tried to get automated testing for this but it is not trivial.  The library wasn't setup well for tests.  I tried using a mock FlutterEngine, but that runs into problems where it eventually has to return C++ objects like the flutter::PlatformView.

If you use a real FlutterEngine I can get the callback installed in the rasterizer, but there is no way to introspect into it.  Also nothing gets rendered without an actual Flutter project so I don't get the callback called.

Our best bet might be to create an integration test in framework, maybe in iosAdd2App tests.

**Comment by gaaclarke** [comment]
I talked offline to @xster.  We decided to look into added this to Dan's integration tests at  testing/scenario_app.  I realized that isn't going to work good for this case because those tests always launch the FlutterViewController before the tests run, which doesn't give us the opportunity to set the callback.  The best place for testing this is in the add2app integration tests.

**Comment by xster** [comment]
I think what it would be though is rather than using the same iOS project itself, it would be a new iOS project where the default vc is a normal vc, it has a button or some such that makes a Flutter VC, sets the callback and presents it. Press the button in earl grey, check that the callback is called.

**Comment by gaaclarke** [comment]
Going to commit this now to make sure I didn't break full screen apps.  I'm working on getting an integration working in Engine based off of Dan's Scenario work.

**Pull request merged**
