### PR TITLE
added python version note to the luci script

### PR DESCRIPTION
**Pull request by gaaclarke**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by iskakaushik — APPROVED** [review]

**Comment by chinmaygarde** [comment]
Can we just try to patch the script to not fail on Python 3.9? If that is not trivial, can we document the issue in a bug for followup?

**Comment by chinmaygarde** [comment]
From triage, another data point from Zach: He is running 3.9.2 and that seems to be fine. We should definitely dig a bit deeper to figure out why newer versions might be no good.

**Comment by gaaclarke** [comment]
@zanderso @chinmaygarde  Okay, I removed the note about 3.9.  We still need a note about 3.7.  We'll consider anything that doesn't work beyond 3.7 a bug.

I'll see if I can reproduce the 3.9 bug.  The problem would only arise for me if a rebuild was actually triggered fwiw, it's a runtime error.

**Comment by chinmaygarde** [comment]
sgtm. I checked my python version and it was 3.8.2. I'll update it an be on the lookout for this issue as well.

**Pull request merged**
