### PR TITLE
Fix pylint errors

### PR DESCRIPTION
**Pull request by bdero**
Greens the tree.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
thanks for the fix! Umm i did run `yapf -i` on the file this time, umm is there some formatting beyond yapf?

**Review by XilaiZhang — APPROVED** [review]

**Comment by bdero** [comment]
I will force land this to green the tree once `Linux Android clang-tidy` passes (the test is indeed running in presubmits now; it's failing in https://github.com/flutter/engine/pull/39933).

**Comment by zanderso** [comment]
You need to run both the lint and format scripts the same way that CI runs them.

**Comment by XilaiZhang** [comment]
Thanks for explaining!

**Pull request merged**
