### PR TITLE
Remove unnecessary assert in drawAtlas

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/12513

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
I am assuming that the rect gets converted into a `Float32List` in `tonic` as it passed to the engine. I am not sure if this being null is handled correctly. But if you are, then lgtm!

**Comment by jason-simmons** [comment]
Tonic will convert a null Dart_Handle into an empty Float32List argument value

**Comment by chinmaygarde** [comment]
Thanks for confirming!

**Pull request merged**
