### PR TITLE
Reduce pipeline depth when GPU and Platform are same thread

### PR DESCRIPTION
**Pull request by dnfield**
Ameliorates https://github.com/flutter/flutter/issues/31138

_This is a work around which should eventually be removed._ Users have reported that since splitting the UI and IO threads when platform views are enabled, it is easy to lock up the entire application when typing while an animation (e.g. the blinking cursor or a spinner) is running.  This issue most reliably reproduces in profile or release mode, but can be noticed less significantly in debug mode. This change __must__ be reverted if we go to dynamic thread merging and unmerging, as we don't currently handle restoring the pipeline depth when the threads split (only when the animator is constructed).

This patch makes it harder to stall the platform thread on the GPU when the threads are merged by reducing parallelization in rendering/rasterization. In a single threaded configuration, the pipeline never gets a chance to get above 1, whereas when the UI thread is split out it gets a chance to schedule additional frames while the rasterizer is going. In this case, the merged GPU/Platform thread (which is really just the Platform thread), tries to 

The problem can be seen in flutter tracing as in the linked bug - a `glClear` call ends up taking much longer than normal, which blocks the platform thread for one or more frames.  In Xcode tracing, this can be observed as a 1 second pause with "Thread blocked while waiting for next drawable" (the large purple boxes in the screen shot below):

image

I have three ideas for other, larger scale improvements that may fix this:

1. Move to Metal, which would allow us some more levers to play with around the GPU fencing and allow us to have more control over which layer(s) are accessing the GPU at a given instant.
2. Minimize the amount of time the GPU and Platform threads are merged.  This problem is either difficult or impossible to manifest when the threads are split.
3. Avoid mergint the threads at all, and let the GPU thread interrupt the platform thread in this configuration (e.g. let it hand the platform thread a task to execute immediately rather than at the end of its queue).

### CODE REVIEW

**Comment by amirh** [comment]
To add some more context:
We've been spending a lot of time investigating the issue, which we still do not understand. Some **speculations** we have are around a potential bug a in the GL driver, or around synchronization issues in the GL driver code which we do not have access to.

As we have reached a dead end with the investigation, we've decide to try and reduce exposure to the issue, as a first step by reducing the pipeline depth to 1(which makes it equivalent to the single threaded case as in that case the UI thread never has a chance to submit a frame while the GPU thread is rasterizing). Another potential way to reduce exposure to the problem will be a thread merging strategy that keeps the threads unmerged for as long as possible(once dynamic thread configuraiton lands). We also believe it's likely that we will stop seeing the issue once we move to metal.

For anyone coming back to investigate this, to make it easier to reproduce you should set the pipeline depth to 2, make sure you're running with just the gpu and platform threads merged, have some animation ongoing, and type really fast in a Flutter TextField.

**Comment by dnfield** [comment]
(Updated PR description to add more context)

**Comment by dnfield** [comment]
Only other note here - part of the goal of this patch is to have something that is attainable for the next beta to help people who are currently broken. The suggested improvements here are believed to take more time than the next beta.

**Comment by dnfield** [comment]
The temporary improvement for this should be available in v1.6.7, which I think is either beta or the tag right after beta.

Are you still seeing this issue at that version?

**Pull request merged**
