### PR TITLE
Clear the EGL context only if our context is currently active

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/19566

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
How is user code getting to the GPU thread to make other context current? If anything, shouldn't this be an assertion?

**Comment by jason-simmons** [comment]
This is happening on the platform thread

**Comment by chinmaygarde** [comment]
Thanks for clearing that up.

**Pull request merged**
