### PR TITLE
Make sure the secondary vsync callback is called after the vsync callback

### PR DESCRIPTION
**Pull request by ColdPaleLight**
fix https://github.com/flutter/flutter/issues/95986
https://github.com/flutter/flutter/issues/95838
https://github.com/flutter/flutter/issues/97998

We need to make sure that the secondary callback is called after the vsync callback, otherwise frames may drop in the scenarios mentioned in the Issue.

The issue was introduced in https://github.com/flutter/engine/pull/28817

/cc @iskakaushik @chinmaygarde @jason-simmons 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by AlexSmirnov9107** [comment]
any updates?

**Comment by jiabin87428** [comment]
any updates?

**Comment by ColdPaleLight** [comment]
friendly ping

**Review by jason-simmons — APPROVED** [review]

**Review by chinmaygarde — APPROVED** [review]

**Comment by CLK123654** [comment]
any updates?

**Comment by 0xleung** [comment]
the frame still drop

**Comment by ColdPaleLight** [comment]
> the frame still drop

Would you mind filing an new issue and providing reproducible code?

**Pull request merged**
