### PR TITLE
Track clip in preroll and quick reject with clipped paint bounds

### PR DESCRIPTION
**Pull request by liyuqian**
This should improve the performance of https://fuchsia.atlassian.net/browse/FL-53 by ~40% because there are 20 small physical layers but only 12 are within the device clip. Without this change, we create 20 Vulkan surfaces and render into all of them. With this change, we only created 12.

By having this for all layers, we get a ~20% speedup for complex_layout_scroll_perf test.

### CODE REVIEW

**Comment by Hixie** [comment]
might be worth pushing back on the app itself, it may well be misdesigned if it is sending data outside of clip.

**Comment by chinmaygarde** [comment]
> might be worth pushing back on the app itself, it may well be misdesigned if it is sending data outside of clip.

Yeah, even if we were to optimize this in the engine on the GPU thread (which we should), the UI thread is still doing a lot of ultimately unnecessary work to construct the picture.

**Comment by liyuqian** [comment]
Is there any investigation in progress on why the framework send us those out-of-sight widgets?

Meanwhile, as I refractored the code, I found https://github.com/flutter/flutter/issues/18382 . Should I include the fix in this PR, or create a different one for that?

**Comment by Hixie** [comment]
I'm not aware of anyone looking at the widget side. Feel free to do so. :-)

**Comment by liyuqian** [comment]
@jonahwilliams told me during the stand up that those out-of-clip widgets might be necessary for iOS accessibility. I'm going to ask @goderbauer whether I should be able to drop them in the LayerTree. I feel that I can definitely just not paint them because Skia is going to drop them anyway.

**Comment by Hixie** [comment]
If these are the "cached" nodes on either side of a list, then they shouldn't be painted at all, let alone end up in the layer tree.

**Comment by liyuqian** [comment]
@chinmaygarde : I've simplified the PR by removing the needs_system_composite fix. Please let me know if it's good to land.

**Comment by Hixie** [comment]
@liyuqian Do you intend to land this?

**Comment by liyuqian** [comment]
@Hixie Not until that I can find a reliable way to test the benefit of this because somehow I cannot reproduce the speedup in the initial comment. I plan to improve metrics and measurement tools first.

**Comment by Hixie** [comment]
ah ok. should we close it in the meantime?

**Comment by liyuqian** [comment]
Sure, close it for now.

**Pull request closed without merging**
