### PR TITLE
[Impeller] Revert support for multi-arch shader archives.

### PR DESCRIPTION
**Pull request by chinmaygarde**
This was never fully wired up and we never ended up needing this as there is only still on backend per platform. Earlier, we expected to have both GLES and Vulkan on Android.

Reverts 2251b8789940e21516f1a4722140cb4996166bb4 and 502755d68e714ca2a2f6dd3a0f33ca8e30c5e0e0 with fixups.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
We'll still need this when/if we do GLES on Android. Does backing it out save us any work?

**Comment by chinmaygarde** [comment]
When we do GLES on Android, we can package the shaders in separately like we do for Vulkan. For instance, `impeller_entity_shaders_gles_data` as well as `impeller_entity_shaders_vk_data`. For the runtime stages, we have a separate separate format. There isn't a need to have a single blob be delivered... ever. So I don't think this is going to save us anything. Just a bad idea that didn't pan out.

**Comment by jonahwilliams** [comment]
but this is for RuntimeEffect, where the shader is bundled in a framework asset. This is definitely getting used right now, in fact.

**Comment by chinmaygarde** [comment]
Are you thinking of the [runtime stage types](https://github.com/flutter/engine/blob/40b868efcc46bdcfa84a03632bb5f61a5d6b04f4/impeller/runtime_stage/runtime_stage_types.fbs#L82)?

**Comment by chinmaygarde** [comment]
[Dan wired it up to make that multi-arch instead](https://github.com/flutter/engine/commit/c53fd4b1d7139e2451ae678e6740a32ecffd83ca).

**Comment by jonahwilliams** [comment]
Ahh okay, got those wires crossed in my head.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
