### PR TITLE
Remove dependency on memfs

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

### CODE REVIEW

**Comment by eyebrowsoffire** [comment]
Looks like some of the sources in flutter actually link on memfs:

```
[737/9537] CXX obj/flutter/shell/platform/fuchsia/runtime/dart/utils/utils.tempfs.o
FAILED: obj/flutter/shell/platform/fuchsia/runtime/dart/utils/utils.tempfs.o 
/b/s/w/ir/cache/goma/client/gomacc  ../../buildtools/linux-x64/clang/bin/clang++ -MD -MF obj/flutter/shell/platform/fuchsia/runtime/dart/utils/utils.tempfs.o.d --target=x86_64-fuchsia --sysroot ../../fuchsia/sdk/linux/arch/x64/sysroot  -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../flutter/shell/platform/fuchsia -Igen/build/fuchsia/fidl -I../../fuchsia/sdk/linux/pkg/fidl_cpp/include -I../../fuchsia/sdk/linux/pkg/async/include -I../../fuchsia/sdk/linux/pkg/fit/include -I../../fuchsia/sdk/linux/pkg/stdcompat/include -I../../fuchsia/sdk/linux/pkg/fit-promise/include -I../../fuchsia/sdk/linux/pkg/async-default/include -I../../fuchsia/sdk/linux/pkg/fidl/include -I../../fuchsia/sdk/linux/pkg/fidl_base/include -I../../fuchsia/sdk/linux/pkg/utf-utils/include -I../../fuchsia/sdk/linux/pkg/zx/include -I../../fuchsia/sdk/linux/pkg/fidl_cpp_sync/include -I../../fuchsia/sdk/linux/pkg/fidl_cpp_base/include -I../../fuchsia/sdk/linux/pkg/async-loop/include -I../../fuchsia/sdk/linux/pkg/async-loop-cpp/include -I../../fuchsia/sdk/linux/pkg/async-loop-default/include -I../../fuchsia/sdk/linux/pkg/fdio/include -I../../fuchsia/sdk/linux/pkg/sys_cpp/include -I../../fuchsia/sdk/linux/pkg/sys_service_cpp/include -I../../fuchsia/sdk/linux/pkg/async-cpp/include -I../../fuchsia/sdk/linux/pkg/vfs_cpp/include -I../../fuchsia/sdk/linux/pkg/sys_inspect_cpp/include -I../../fuchsia/sdk/linux/pkg/inspect/include -I../../fuchsia/sdk/linux/pkg/inspect_service_cpp/include -I../../fuchsia/sdk/linux/pkg/syslog/include -I../../fuchsia/sdk/linux/pkg/trace-engine/include -I../../fuchsia/sdk/linux/pkg/trace/include -I../../flutter/third_party -I../../flutter -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -fno-strict-aliasing -m64 -march=x86-64 -fcolor-diagnostics -ffuchsia-api-level=12 -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -fvisibility=hidden -Wstring-conversion -Wnewline-eof -Oz -fno-ident -fdata-sections -ffunction-sections -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -fno-exceptions -c ../../flutter/shell/platform/fuchsia/runtime/dart/utils/tempfs.cc -o obj/flutter/shell/platform/fuchsia/runtime/dart/utils/utils.tempfs.o
../../flutter/shell/platform/fuchsia/runtime/dart/utils/tempfs.cc:16:10: fatal error: 'lib/vfs/cpp/pseudor_dir.h' file not found
   16 | #include <lib/vfs/cpp/pseudor_dir.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by eyebrowsoffire** [comment]
Oh, that's the replacement dependency. Doesn't look like the build is able to source it though.

**Comment by tamird** [comment]
Just a typo.

**Comment by tamird** [comment]
This is green on fuchsia - PTAL.

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Pull request merged**
