### PR TITLE
Reland "remove surface dependance on external view embedder (#22468)"

### PR DESCRIPTION
**Pull request by iskakaushik**
Also adds a test for the failure seen in https://github.com/flutter/flutter/issues/70384

This reverts commit 021ff04336d90383a056eb33ddd61ed5ea4130fa.

### CODE REVIEW

**Comment by liyuqian** [comment]
The added test is failing:
```
[ RUN      ] ShellTest.ExternalEmbedderNoThreadMerger
[FATAL:flutter/testing/test_timeout_listener.cc(45)] Check failed: delay < timeout_. Test ShellTest.ExternalEmbedderNoThreadMerger did not complete in 30 seconds and is assumed to be hung. Killing the test harness.
```

**Comment by iskakaushik** [comment]
@jason-simmons looks like `raster_thread_merger_` can be null when we call `EndFrame`, iOS implementation just clears the composition order, and on Android when surface is set, raster_thread_merger_ is always set. So just checking for `surface` is the right call here I think.

**Review by jason-simmons — APPROVED** [review]

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
I've filed a flake report and re-run the presubmit.

**Pull request merged**
