### PR TITLE
Set shell as Rasterizer::Delegate in Fuchsia

### PR DESCRIPTION
**Pull request by liyuqian**

### CODE REVIEW

**Comment by dnfield** [comment]
Doesn't this need to be in the topaz repo at this point?  Are we building out of flutter/engine yet?

**Comment by liyuqian** [comment]
Good point. @nathanrogersgoogle : try to apply this change to topaz/runtime/flutter_runner/engine.cc if this patch doesn't solve your problem.

**Comment by liyuqian** [comment]
@chinmaygarde : is this already replacing topaz/runtime/flutter_runner/engine.cc ?

**Comment by nathanrogersgoogle** [comment]
@liyuqian I locally patched this into "//topaz/runtime/flutter_runner/engine.cc" and can confirm that it fixes the issue discussed in #8970.  Thanks!

@chinmaygarde how should we land this patch in topaz and Flutter engine w.r.t. Flutter runner's current migration status?

**Comment by liyuqian** [comment]
Ping @chinmaygarde on the Nathan's question above: how should we land this patch in topaz and Flutter engine w.r.t. Flutter runner's current migration status?

**Comment by dnfield** [comment]
AFAIK we still have to land these in Topaz.  If that's not the case, I have other work that needs to be ported over.

**Comment by dnfield** [comment]
I think we should close this - this needs to be upstreamed to topaz.  WDYT @liyuqian ?

**Comment by liyuqian** [comment]
Sure, let's close this until the `flutter_runner` migration is done. @nathanrogersgoogle : are you doing this change on the topaz repo?

**Pull request closed without merging**
