### PR TITLE
libtxt: use Helvetica as a fallback font on iOS 8 and earlier

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/16055

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by Hixie** [comment]
Why is this necessary? We should be automatically falling back on all the fonts on the system anyway, so changing the ultimate backstop shouldn't make a difference.

**Comment by jason-simmons** [comment]
Minikin expects to be given a collection of all relevant fonts for a given text block before doing layout.  The libtxt font subsystem builds the collection by asking the Skia font managers to supply fonts for the requested font family.  If no font manager can match the family, then libtxt asks the font managers to match the platform's default font family.  If that also fails, then layout can't proceed.

Later we added a patch to Minikin that queries Skia to find a font matching any character that isn't covered by the font collection.  If Skia can't find a font family, then we could try experimenting with a model where we provide an empty font collection and rely on per character fallback to find some usable font.  

Note that Minikin currently requires that font collections be nonempty:
    https://github.com/flutter/engine/blob/master/third_party/txt/src/minikin/FontCollection.cpp#L87

I'm not sure how deeply embedded this assumption is in Minikin.

**Comment by Hixie** [comment]
Ah, interesting.

**Pull request merged**
