### PR TITLE
Wait for Vulkan display driver on Fuchsia

### PR DESCRIPTION
**Pull request by abarth**
We now wait for 1 second for the display driver to appear on Fuchsia. This
approach is a stopgap until Vulkan is required for graphics.

### CODE REVIEW

**Comment by Hixie** [comment]
Is there a bug tracking (a) having this timeout in the system somewhere rather than in each app, and (b) having the ability to switch from software back to vulkan if it takes even longer than 1000ms for vulkan to come up?

**Comment by abarth** [comment]
I believe SY-88 has all that information, yes.

**Comment by Hixie** [comment]
Great!

**Pull request merged**
