### PR TITLE
Expose activity service through the embedder on Mojo/Android

### PR DESCRIPTION
**Pull request by krisgiesing**
@abarth, @qsr can you take a look?

FYI @ukode

### CODE REVIEW

**Comment by abarth** [comment]
I don't think this is the right approach.  We shouldn't be hard-coding Android-specific services into flutter.mojo.

**Comment by krisgiesing** [comment]
Aren't we already doing the equivalent with Sky shell? The client code expects to access the activity service through the embedder.

I agree the story here isn't very clean but I don't see an immediate solution that's any more attractive.

**Comment by krisgiesing** [comment]
I suppose the code could go into sky_application rather than platform_view_mojo, since the connection doesn't rely on view information the way the keyboard service stuff does, but I don't think that addresses your concern.

**Comment by abarth** [comment]
> Aren't we already doing the equivalent with Sky shell?

Yes, but if we head down this path, flutter.mojo will become a hub of services, which isn't it's role in the larger system.  It's role is to be a UI renderer.  MojoShell is the hub of services.

> The client code expects to access the activity service through the embedder.

Then we should change the client code.  It would be helpful to understand the motivation and use cases for this change to understand what the best solution might be.

> I don't think that addresses your concern.

That's right.  My concern is that flutter.mojo remain ignorant of what services exist in the Mojo ecosystem in which it is embedded.  Some services, like Mozart, we won't be able to remain ignorant about because we need to interact with them directly, but we should be able to remain ignorant of the vast majority, including Activity, which doesn't even exist in the FNL ecosystem.

**Comment by krisgiesing** [comment]
So I just changed the activity service to use an explicit name instead of null for the service name, and that appears to work both on Flutter+Sky and Flutter+Mojo.  I'm honestly not sure why it works on Sky but it's a much simpler change, so abandoning this one.

**Comment by abarth** [comment]
\o/  That sounds great.  Thanks!

It works in SkyShell because if we don't have a shell, we ignore the name and look in the embedder services.

**Pull request closed without merging**
