### PR TITLE
 VulkanSurface and GPUSurfaceGL no longer use GrPixelConfig

### PR DESCRIPTION
**Pull request by bsalomon**

### CODE REVIEW

**Comment by bsalomon** [comment]
@jason-simmons, I think this is actually ready now. Would you mind landing it?

**Comment by bsalomon** [comment]
Thanks!

**Comment by cbracken** [comment]
This appears to have broken the Mac build: [logs](https://build.chromium.org/p/client.flutter/builders/Mac%20Engine/builds/2479/steps/build%20host_debug_unopt/logs/stdio)

**Comment by cbracken** [comment]
Should have a patch momentarily

**Pull request merged**
