### PR TITLE
Color matrix doc

### PR DESCRIPTION
**Pull request by dnfield**
These docs were a bit sparse, and based on questions coming up in chat needed some more love.

/cc @escamoteur

@jonahwilliams  - am I supposed to be updating the web file too? Did we come up with a solution for keeping docs in sync there?

### CODE REVIEW

**Comment by escamoteur** [comment]
You are making my planed blog post superfluous ;-)  what does *in unnormalized, 0...255,* mean?*

**Comment by dnfield** [comment]
That doc was part of the existing docs and I'm not 100% sure I understand it well enough to explain it better.  @bsalomon  - could you comment on that? It'd probably be good to clarify in this.

**Comment by dnfield** [comment]
I'm going to land this on red to kick infra to use a new recipe change that should make things green.

I'll still try to circle back and clarify the unnormalized 0...255

**Comment by escamoteur** [comment]
@dnfield did you get any further with the unnormalized  I'm working on a blog post on this

**Comment by bsalomon** [comment]
Sorry, I was out for two weeks and missed this. The color filter matrix stuff was created when all working colors in Skia were byte-per-component. The translation column is in this space, so if you want to add "half" to say red you'd put 128 in the upper right entry not 0.5. Maybe that's not the right API to expose through Flutter, though.

**Comment by escamoteur** [comment]
@bsalomon But 0.5 works only the fith column is 0..255

**Comment by bsalomon** [comment]
Oh, maybe the comment is just out of date. I don't seem to be able to find the equivalent comment in the Skia code any longer. I think @reed-at-google had a series of changes in the last year that made all the matrices use floats.

**Comment by dnfield** [comment]
Yes, flutter converts it internally by dividing by 255.

I'm not 100% clear on the unnormalized part

**Comment by bsalomon** [comment]
Ah.... unnormalized just meant that the value wasn't "normalized" to the 0 to 1 range. Maybe not the clearest nomenclature.

You might consider deprecating the current Flutter API if it expects 0..255 for the translates and adding one that takes floats. The 0..255 thing is historic baggage.

**Pull request merged**
