### PR TITLE
[iOS] remove clear color hack.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/125640

This doesn't actually do anything, instead it forces opaque to false. If developers want opaque to be false, they can just set it directly.

### CODE REVIEW

**Review by jmagman — CHANGES_REQUESTED** [review]
> This doesn't actually do anything, instead it forces opaque to false. If developers want opaque to be false, they can just set it directly.

I recall this hack fixing a whole lot of measurable jank issues listed in https://github.com/flutter/engine/pull/39359, and we had confirmation from customers who could reliably reproduce jank that it fixed their issue (https://github.com/flutter/flutter/issues/103847).  I would prefer us not to remove it speculatively though indeed it looks unnecessary and crazy.

**Comment by chinmaygarde** [comment]
Breaking direct-to-display is pretty severe and if we can't measure the improvement in any benchmark, I think we should go ahead with this.

**Comment by jmagman** [comment]
> we were never able to repro anything in our devicelab

It was pretty reliably manually reproducible (check out the video) https://github.com/flutter/engine/pull/39359.  I agree it would be better if we had benchmark that definitely showed hitching went down, and removing it made hitching go up.  But given the issue was widely seen in the wild, and this weird hack was widely confirmed to fix it, I'd value that over our incomplete benchmarks.

I agree though we don't need to keep weird hacks around forever as superstition, but given the number of 👍  in the issues this closed, I think it's worth investigating whether it's still needed.

cc @luckysmg who found the hack, as well as some investigated some alternatives.

**Comment by jmagman** [comment]
> developers can opt into the existing mode by setting opaque = false.

Can we opt them into it?  The weird hack improved the hitching by a lot, without needing to change anything themselves.

**Comment by luckysmg** [comment]
I m not sure whether the junk will regress if this hack removed now. Engine code has change a lot since I last seen haha
I think we need to test this change on local device. Especially using high fps device like iPhone15Pro

**Comment by jonahwilliams** [comment]
Absent specific evidence that something is an improvement, we should follow apple guidelines which specifically call out this property in the metal developer tools:

https://user-images.githubusercontent.com/8975114/234942519-fba0982a-e2c3-4bee-b838-c564ca1cc9b8.png

> but given the number of 👍 in the issues this closed, I think it's worth investigating whether it's still needed.

People will thumbs up anything that claims to make performance faster, that doesn't mean that many people individually verified it.

**Comment by jonahwilliams** [comment]
Now if I land this and a benchmark regresses (which It might), then I at least have something to investigate.

**Comment by jmagman** [comment]
> I think we need to test this change on local device. Especially using high fps device like iPhone15Pro

@jonahwilliams would you be able to run through the manual test @luckysmg reproduced this with on a high fps device and confirm this doesn't seriously regress hitching?  I'm not sure if there is a benchmark test that would fail, but it was really obvious irl with manual testing.

> we should follow apple guidelines which specifically call out this property in the metal developer tools:

Since the egregious color hack essentially "fixed" the performance issues without app devs needing to do anything, is there something more explicit we can do that doesn't require app devs needing to know they should set the opaque property?  Can we default it to something with similar performance characteristics?

**Comment by chinmaygarde** [comment]
@jmagman @luckysmg What is the manual test?

**Comment by jmagman** [comment]
> @jmagman @luckysmg What is the manual test?

I think it was just scrolling a list view on a Pro device like this?
https://github.com/flutter/flutter/issues/103847#issuecomment-1298437603

Additional data, here's an internal bug that reported performance improving when the color hack rolled in b/263817100#comment17

**Comment by chinmaygarde** [comment]
What are the next steps here? Do we need a reproduce this on devices we have? Perhaps @jmagman and @jonahwilliams should chat?

**Comment by jonahwilliams** [comment]
I think this change is valid as is and I'm waiting for actionable feedback.

**Comment by jmagman** [comment]
I started trying to reproduce this to see if I can profile a simple scrolling list clearly with and without the color hack, but I was hitting the dreaded `Can't load kernel binary` (I `gclient sync`d, my flutter engine SHA matches where I branched this change from, I'm `run --profile`ing, can't think what I'm missing here).  I'm going to try with clean out directories.

Once I get this working:
If I can't reproduce it locally, I think we should land this and see what the benchmarks do.
If I can reproduce it locally then presumably this weird hack is still doing something. I think we should still land this to see what the benchmarks do, then immediately revert it.  If the benchmarks moved, then yay benchmarks and we move on.  If nothing moved, then we should add a benchmark that would have caught the regression.

What do you think, @jonahwilliams?

**Comment by jonahwilliams** [comment]
SGTM!

**Comment by jtmcdole** [comment]
Any updates?

**Comment by jmagman** [comment]
> Any updates?

Yes, I have the repro case running at home, but I left my promotion display phone at work and I wanted to test at a higher frame rate. I already have a note to myself to bring it home next time I'm in the office.

**Comment by chinmaygarde** [comment]
@jonahwilliams has a high-framerate device and can confirm this patch makes no difference to performance. We would like to move ahead with this unless there are any objections.

**Comment by jonahwilliams** [comment]
This needs an approval to land.

**Review by jmagman — APPROVED** [review]

**Comment by jmagman** [comment]
> This needs an approval to land.

Sorry, done.

**Comment by jonahwilliams** [comment]
Thanks!

**Pull request merged**
