### PR TITLE
Move Surface and friends to flow/

### PR DESCRIPTION
**Pull request by arbreng**
Circular dependencies are cropping up between shell/common/ and flow/,
so just move all of this stuff down into flow itself.  These classes are
all rasterization-related anyways.

shell/common/ has Dart dependenices, and a future CL will create
non-product and product permutations of any target with Dart
dependencies.  Moving all of the rasterization-related code to its own
library with no Dart dependencies means no permutations need to be made
of it.

Tested: Just compile, this is a mechanical change

### CODE REVIEW

**Comment by dnfield** [comment]
This broke iOS builds.

For some reason, the mac presubmits didn't run on this at all.  @godofredoc

**Comment by dnfield** [comment]
(Fixed forward in https://github.com/flutter/engine/pull/18950)

**Comment by godofredoc** [comment]
This is because mac builds have a very long queue time and the status are updated only after they are scheduled to run. https://github.com/flutter/flutter/issues/56421

**Comment by godofredoc** [comment]
This is the one for the long queue time: https://github.com/flutter/flutter/issues/59036

**Pull request merged**
