### PR TITLE
[Impeller] Fixed TypographerTest.MaybeHasOverlapping

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/127714

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

Why do we get away with this on iOS? relying on some internal state somewhere?

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

Why do we get away with this on iOS? relying on some internal state somewhere?

**Comment by gaaclarke** [comment]
> Why do we get away with this on iOS? relying on some internal state somewhere?

Well, at first I thought it was because the default font was different per operating system.  But I just looked and this still passes on macos with arial 12, where on linux I needed arial 0.5 to get them to overlap.

Here are the first 2 glyph rects:
```
(x:0.000000 y:-10.000000 w:6.000000 h:11.000000)
(x:5.673828 y:-10.000000 w:9.000000 h:11.000000)
```

I don't know why they overlap.  I could guess the ttf files are different or there is some ifdef code or skia is using different libraries for typesetting?  If you have an optimization that requires that the glyphs aren't overlapping, I don't think it's getting hit as much as you had hoped.

**Comment by jonahwilliams** [comment]
Yeah I think its making some assumptions based on what the font will do. Perhaps instead we should hardcode the font?

Its entirely reasonable that they would overlap, and this test might just be poorly written to assume they wont

**Comment by jonahwilliams** [comment]
but at any rate, this fix is still fine if using a different font stabilizes it

**Comment by gaaclarke** [comment]
@jonahwilliams I tried switching the test to use a specific font:
```c++
TEST_P(TypographerTest, MaybeHasOverlapping) {
  static constexpr const char* kTestFontFixture = "Roboto-Regular.ttf";
  auto mapping = OpenFixtureAsSkData(kTestFontFixture);
  FML_CHECK(mapping);
  SkFont sk_font(SkTypeface::MakeFromData(mapping), 12.0);

  auto frame = TextFrameFromTextBlob(SkTextBlob::MakeFromString("1", sk_font));
  // Single character has no overlapping
  ASSERT_FALSE(frame.MaybeHasOverlapping());

  auto frame_2 =
      TextFrameFromTextBlob(SkTextBlob::MakeFromString("123456789", sk_font));
  // Characters probably have overlap due to low fidelity text metrics, but this
  // could be fixed.
  ASSERT_TRUE(frame_2.MaybeHasOverlapping());
}
```

This still passes on macos but fails on linux.

**Pull request merged**
