### PR TITLE
Add tflite_native to DEPS

### PR DESCRIPTION
**Pull request by bkonyi**
Unblocks Dart SDK rolls

### CODE REVIEW

**Comment by aam** [comment]
Don't you want to include this change into actual dart sdk roll that requires this new dependency?

**Comment by bkonyi** [comment]
> Don't you want to include this change into actual dart sdk roll that requires this new dependency?

I'm going to start a roll immediately after this lands. It's easier than me trying to fiddle with the script remotely.

**Comment by aam** [comment]
> > Don't you want to include this change into actual dart sdk roll that requires this new dependency?
> 
> I'm going to start a roll immediately after this lands. It's easier than me trying to fiddle with the script remotely.

I would rather land this DEPS change as part of the dart roll - makes it clear where it came from, makes it easy to revert and bisect if needed.
If you need help doing the roll, let me know - should not be too much problem doing it here.

**Comment by aam** [comment]
> > > Don't you want to include this change into actual dart sdk roll that requires this new dependency?
> > 
> > 
> > I'm going to start a roll immediately after this lands. It's easier than me trying to fiddle with the script remotely.
> 
> I would rather land this DEPS change as part of the dart roll - makes it clear where it came from, makes it easy to revert and bisect if needed.
> If you need help doing the roll, let me know - should not be too much problem doing it here.

Created https://github.com/flutter/engine/pull/10265

**Pull request closed without merging**
