### PR TITLE
[monorepo] split out build-only web engine into its own builder

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/160211

### CODE REVIEW

**Comment by jtmcdole** [comment]
This and some ET problems? 
```
00:00 [32m+0[0m[31m -1[0m: test smoke test -- this test SHOULD FAIL [1m[31m[E][0m[0m

  Expected: true
    Actual: <false>


  Expected: true
    Actual: <false>
```

```
Invalid argument (name): Expected to start with a valid platform name (i.e. linux/) or "ci/": "web_build/artifacts"
#0      mangleConfigName (package:engine_tool/src/build_utils.dart:57:3)
```

**Comment by eyebrowsoffire** [comment]
I'm confused by this change. Does this mean we are going to actually build all the artifacts *twice* in every presubmit?

**Comment by yjbanov** [comment]
@eyebrowsoffire 

> I'm confused by this change. Does this mean we are going to actually build all the artifacts _twice_ in every presubmit?

Unfortunately for now, yes. The good news is that it shouldn't be too much overhead. Currently, `linux_web_engine` performs the following work:

* Build:
  * The engine build itself - 13 min (but due to drone overhead it currently costs 20 min).
  * Engine tests - 8 x 7 min = 56 min
* Test:
  * Chrome: 2 x 25 min = 50 min
  * Safari: 12 min
  * Firefox: 12 min

So that's 20 + 56 + 50 + 12 + 12 = 150 min worth of work total.

The new `linux_web_engine_build` builder duplicates just the 13 min (we don't need drones, so there's no extra 7 min overhead), and it moves the artifact upload work to itself so there's no duplication there.

So overall, I do not expect more than 15% overhead total. However, it will remove massive amounts of overhead from the merge queue by reducing the amount of work from 150 min to something <20min.

**Review by jtmcdole — APPROVED** [review]
If we think we can safely land this before the repo; then lets get a win.

**Comment by yjbanov** [comment]
Superseded by https://github.com/flutter/engine/pull/57232

**Pull request closed without merging**
