### PR TITLE
fix: mask disappeared when having nested mask filter on Flutter web HTML

### PR DESCRIPTION
**Pull request by Kingtous**
Hi from [Dora team](https://www.dora.run/), which powers web developers to build their 3d websites in just a few seconds.

This PR fixes: https://github.com/flutter/flutter/issues/133443, related: https://github.com/flutter/flutter/issues/58546

The original codes attempts to cache the css string but it causes bugs when encountering nested the same mask filter blur. We should also set `filter` properties when currentFilter == incoming mask filter using the cached css string, not just ignore it. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Kingtous** [comment]
Any updates here? :)

**Comment by harryterkelsen** [comment]
Hi, just seeing this now. I am looking into image filters right now and will look into this tomorrow.

**Review by harryterkelsen — APPROVED** [review]
LGTM. Sorry for the delay in review, I am making it a priority going forward to review third-party contributions.

Please rebase on top of main so the golden tests aren't polluted with all the new goldens that have been added since this PR was created.

Again, thanks so much! External contributors like you make Flutter great!

**Comment by harryterkelsen** [comment]
Hello @Kingtous, do you plan to rebase this PR on the latest `main` commit to fix the goldens? Thanks

**Comment by Kingtous** [comment]
> Hello @Kingtous, do you plan to rebase this PR on the latest `main` commit to fix the goldens? Thanks

Sure, I'll rebase this PR to the latest `main` commit these days. Thanks for reviewing this PR :)

**Comment by harryterkelsen** [comment]
I'm updating the branch to determine up-to-date golden file changes

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by jiahaog** [comment]
Reason for revert: This commit seems to cause the debug banner of a material app to be unnecessarily blurred. For example, one of the tests runs the following flutter app:

<details>

<summary>Code</summary>


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: Center(
        child: Text(
          'Button tapped $_counter time${_counter == 1 ? '' : 's'}.',
          key: Key('CountText'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

Screenshots:

<details>
<summary>Before this change</summary>

image

</details>

<details>
<summary>After this change</summary>

image

</details>

Observe that the debug banner on the top right is now blurred. This test runs on Chrome Linux v126, and the unexpected blurs can be seen in both DDC and Dart2js mode **with the html renderer**.

This can also be reproduced with a fresh flutter app in chrome v126 with the following command on linux (didn't check other platforms), with a Flutter checkout at https://github.com/flutter/flutter/commit/fa70e610cc244750b07321c466385d821533ee68. It does not reproduce with the parent commit, nor with the `--web-renderer` argument ommited.

```
flutter run web -d chrome --web-renderer html
```

Googlers, see b/351082848 for more details.

**Pull request merged**
