### PR TITLE
Add Dear ImGui as a test only dependency

### PR DESCRIPTION
**Pull request by bdero**
Buildroot PR: https://github.com/flutter/buildroot/pull/549

Wired this up against my in-progress [imgui backend for impeller](https://github.com/bdero/impeller/commit/b4c3ce758b2b2dc76063965e9dbe9f03f85ae3cc).

### CODE REVIEW

**Comment by bdero** [comment]
Here's how I sorted out the licenses:
* `imgui.cpp` has a license mention that was getting detected as a full license, so I added a unique signature to the license mentions list, which seems to be for this purpose.
* There's a generated opengl loader in the examples (generated by [this](https://github.com/dearimgui/gl3w_stripped)) which contains the [Unlicense](https://unlicense.org/) statement and no copyright claim, so I added this text to the "csNoCopyrights" list.
* The examples contain a copy of the Synergy [micro client](https://github.com/symless/synergy-core/tree/790d108a56ada9caad8e56ff777d444485a69da9/src/micro), which contain zlib copyright headers. The text wraps differently than the other zlib variations, so I appended it a new variation below the others.

**Comment by chinmaygarde** [comment]
The dependency is test-only. This may be ignored by the script.

**Comment by bdero** [comment]
Ah I totally missed that. Well at least I know how the license script works now. :)

**Comment by bdero** [comment]
Alrighty, I excluded imgui from the license script.

**Review by chinmaygarde — APPROVED** [review]

**Pull request merged**
