### PR TITLE
Made the thread checker print out the thread names on Apple platforms.

### PR DESCRIPTION
**Pull request by gaaclarke**
related PR: https://github.com/flutter/engine/pull/13908

### CODE REVIEW

**Comment by dnfield** [comment]
Can't we use https://linux.die.net/man/3/pthread_getname_np on Linux as well?  I'm not sure if there's anything on Fuchsia but maybe we could abstract this into FML for at least Linux and Mac as Chinmay was suggesting?

**Comment by chinmaygarde** [comment]
Looked up all the platform specific implementations and they all look straightforward. Again, I understand if you'd rather tackle this in another patch (with a TODO and issue filed in the meantime).

* Linux: [pthread_getname_np](https://linux.die.net/man/3/pthread_getname_np)
* Darwin: Done.
* Windows: [GetThreadDescription](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription?redirectedfrom=MSDN)
* Fuchsia: `zx::thread::self()->get_property` with `ZX_PROP_NAME`.

**Comment by gaaclarke** [comment]
Spawned issue: https://github.com/flutter/flutter/issues/45272

It's not that it's hard to implement, just a pain to test on all the platforms.  FWIW I had problems using `pthread_getname_np` on Android.  I didn't look into it but I was getting compilation errors with CI.

**Comment by gaaclarke** [comment]
Landing on red.  Broken LUCI is an infra problem with fuchsia that is being investigated.

**Pull request merged**
