### PR TITLE
[flutter_releases] Flutter 1.22.4 engine cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
[previous build](https://github.com/flutter/engine/pull/22171)

## Scheduled Cherrypicks

* Dart 2.10.4
  * https://github.com/dart-lang/sdk/commit/7c148d029de32590a8d0d332bf807d25929f080e
* [iOS] adding autoFillHint to TextFormField breaks FocusScope.of(context).nextFocus() #66144
  * https://github.com/flutter/flutter/issues/66144
  * https://github.com/flutter/engine/commit/3f27800f5b4917e9a312f39c29dc20e705b8b822
  * Original author: @LongCatIsLooong, original approver: @justinmc 
* platform views on by default introduced a race condition #69449
  * https://github.com/flutter/flutter/issues/69449
  * https://github.com/flutter/engine/commit/122f242588e832b067ebd9c6cb73968075e4de08
    * Original author: @gaaclarke, original approver @cyanglaz 
  * https://github.com/flutter/engine/commit/fb72023d38c752367840247d379bf1fe43a31712 (had a merge conflict)
    * Original author: @cyanglaz, original approver @cbracken 

## Known Presubmit Failures

* Linux/Mac Web Engine
  * flutter/flutter#53371
* Mac iOS Engine
  * This is due to running the master channel recipe flutter/flutter#53371
  * The upstream change that broke this was https://flutter-review.googlesource.com/c/recipes/+/6960

## Known Postsubmit Failures

### CODE REVIEW

**Review by pcsosinski — APPROVED** [review]
approved for branch

**Review by cyanglaz — COMMENTED** [review]
LGTM on https://github.com/flutter/engine/commit/fb72023d38c752367840247d379bf1fe43a31712 and https://github.com/flutter/engine/commit/122f242588e832b067ebd9c6cb73968075e4de08

**Comment by LongCatIsLooong** [comment]
3f27800 LGTM

**Comment by christopherfujino** [comment]
All outstanding CI failures accounted for in description (and they're the same as the previous build), so merging this.

**Comment by christopherfujino** [comment]
This PR required a follow-up fix, github.com/flutter/engine/pull/22478

**Pull request merged**
