### PR TITLE
Convert the enable-dart-profiling to a shell argument in SkyActivity.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by johnmccutchan** [comment]
LGTM

**Comment by johnmccutchan** [comment]
@chinmaygarde is there a CL rolling this into Flutter?

**Comment by chinmaygarde** [comment]
Yes, https://github.com/flutter/flutter/pull/7163. Sorry, was waiting for the bots to finish but got distracted.

**Pull request merged**
