### PR TITLE
Roll ANGLE

### PR DESCRIPTION
**Pull request by stuartmorgan**
Updates to the latest version of ANGLE. Needed for Windows UWP work.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'll re-sync and regenerate licenses once it's reviewed, since it constantly has new collisions.

**Comment by cbracken** [comment]
Interesting -- looks like this hit the pure virtual function flake again.

**Review by cbracken — APPROVED** [review]
RSLGTM

**Review by clarkezone — APPROVED** [review]
LGTM, look forward to this landing ;-)

**Pull request merged**
