### PR TITLE
iOS cleanup IOSurfaces when not visible

### PR DESCRIPTION
**Pull request by ColdPaleLight**
Fix https://github.com/flutter/flutter/issues/77621
based on this PR https://github.com/flutter/engine/pull/25400 and this comment https://github.com/flutter/flutter/issues/77621#issuecomment-836342415

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by Hixie** [comment]
@ColdPaleLight Is this still on your radar? (I think it's been ignored by reviewers because it's marked as a draft.)

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight Is this still on your radar? (I think it's been ignored by reviewers because it's marked as a draft.)

Yes, it is. I will finish it soon.

**Comment by Hixie** [comment]
@ColdPaleLight Friendly ping again. :-)

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight Friendly ping again. :-)

I've tried fixing those failing tests, but it didn't work. Maybe I need to reimplement this patch.

Closing it since it need more work to do.

**Pull request closed without merging**
