### PR TITLE
Drop GCM

### PR DESCRIPTION
**Pull request by Hixie**
This primarily removes GCM. It also removes a tiny bit of the cruft I found while doing this. There's probably a lot, lot more we could clean up here.

cc @jason-simmons

### CODE REVIEW

**Comment by collinjackson** [comment]
lgtm

**Comment by jason-simmons** [comment]
LGTM

You'll also need to remove the GCM flags from the engine build recipe on the buildbot

**Comment by Hixie** [comment]
@jason-simmons like this?
```diff
diff --git a/scripts/slave/recipes/flutter/engine.py b/scripts/slave/recipes/flutter/engine.py
index 5a3096d..ad6de16 100644
--- a/scripts/slave/recipes/flutter/engine.py
+++ b/scripts/slave/recipes/flutter/engine.py
@@ -124,8 +124,8 @@ def BuildLinuxAndroidArm(api):
     'icudtl.dat',
     'gen/sky/shell/shell/classes.dex.jar',
   ]
-  RunGN(api, '--android', '--enable-gcm')
-  Build(api, 'android_debug', ':dist', 'gcm')
+  RunGN(api, '--android')
+  Build(api, 'android_debug', ':dist')
   UploadArtifacts(api, 'android-arm', [
     'build/android/ant/chromium-debug.keystore',
   ] + AddPathPrefix(api, 'out/android_debug', out_paths))
@@ -173,8 +173,6 @@ def BuildLinuxAndroidArm(api):
     Upload(ServicesOut(dex_jar), dex_jar)
     Upload(ServicesOut(interfaces_jar), interfaces_jar)

-  UploadService('gcm', 'out/android_debug/gen/third_party')
-

 def BuildLinux(api):
   RunGN(api)
```

**Comment by jason-simmons** [comment]
Yes.  You can also remove the UploadService function

**Comment by Hixie** [comment]
https://codereview.chromium.org/2148563002 (cc @eseidel)

**Pull request merged**
