### PR TITLE
Move `third_party/root_certificates`.

### PR DESCRIPTION
**Pull request by matanlurey**

### CODE REVIEW

**Comment by matanlurey** [comment]
It looks like the path might be built-in somewhere lower in the ecosystem (i.e. the Dart SDK):

```txt
ninja: error: '../../third_party/root_certificates/root_certificates.cc', needed by 'obj/third_party/root_certificates/dart_io_api.root_certificates.obj', missing and no known rule to make it
ninja: Entering directory `C:\b\s\w\ir\cache\builder\src\out/host_debug_unopt'
```

Reference is [here](https://github.com/dart-lang/sdk/blob/706d105007976ec2a32cca837d36b9ddecec75c7/runtime/bin/BUILD.gn#L491):

```gn
sources += [ "//third_party/root_certificates/root_certificates.cc" ]
```

I didn't see this as the error only appears to occur on a Windows host.

@jason-simmons or @zanderso do you have any creative solutions?

**Comment by zanderso** [comment]
Off the top of my head, an option I can think of is similar to some other deps that you encountered recently, the code can be moved to `//flutter/third_party`, with a `BUILD.gn` file added to `//flutter/build/secondary/third_party` that manually forwards to the new location.

**Comment by matanlurey** [comment]
> Off the top of my head, an option I can think of is similar to some other deps that you encountered recently, the code can be moved to `//flutter/third_party`, with a `BUILD.gn` file added to `//flutter/build/secondary/third_party` that manually forwards to the new location.

I think the problem is this is purely an `#include` problem, and isn't related to GN resolution (maybe related?)

**Comment by jason-simmons** [comment]
This component is a source file that is built into the Dart SDK but was factored out into a separate repository.  I'd recommend deferring moving this until there is a plan for moving the rest of `third_party/dart`.

The Ninja error above is an issue at the GN level.  One of Dart's GN scripts is adding `//third_party/root_certificates/root_certificates.cc` to a `sources` list, and GN/Ninja can not find that file because it was moved to `//flutter/third_party/root_certificates`.

I tried this as an experiment:
* adding a `BUILD.gn` file to https://dart.googlesource.com/root_certificates/+/refs/heads/master that defines a `source_set` containing `root_certificates.cc`
* patching the Dart component to depend on the source set instead of directly adding the source file.
* adding a secondary `BUILD.gn` that defines the same `source_set` using a file path in `//flutter/third_party/root_certificates``

This built, but I don't know if it's the best way to handle this.

Ideally the secondary `BUILD.gn` file could just depend on the `source_set` defined in the original `BUILD.gn` that was added to the `root_certificates` repository.  But `root_certificates.cc` has an `#include "platform/globals.h"` that is relative to Dart's `runtime/bin` directory.  I was not able to get a redirect of the source_set to work without violating GN rules around include paths and component dependencies.

**Comment by zanderso** [comment]
I asked in the chat room with Dart folks if the `root_certificates` repo could just be merged into the Dart SDK repo, which I think would mean that we could just delete the dep from the engine DEPS file.

**Comment by zanderso** [comment]
Closing as obsolete. The repo is no longer in the engine DEPS file.

**Pull request closed without merging**
