### PR TITLE
[flutter_releases] Flutter 2.0.2 Stable Engine Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

* Dart SDK 2.12.1
  * https://github.com/dart-lang/sdk/commit/d6e7aacfe6d19c8d478dcf3e315b76720813a417
* [web] Canvas Kit issue when using dart:ui/Path.from - BindingError: Tried to invoke ctor of Path with invalid number of parameters (1) - expected (0) parameters instead! [#75473](https://github.com/flutter/flutter/issues/75473)
  * https://github.com/flutter/engine/commit/48cf2b9378d2c3718d11bde2c638ae4044a4d8b6
  * Original author @yjbanov 
* Multiple Flutter Engine: destroy flutter engine making live flutter stop response user interaction #76597
  * https://github.com/flutter/engine/commit/95cb19f9b1ccfc8ae11b8719e3144bb2dcddceed
  * Original author @gaaclarke 

## Known Failures

* Linux Web Engine - same as [previous build](https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Engine/14683?)
* Mac Web Engine - same as [previous build](https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/14376?)

### CODE REVIEW

**Review by kf6gpe — APPROVED** [review]
LGTM. Do we need a separate eng LGTM?

**Comment by gaaclarke** [comment]
my patch looks good

**Comment by christopherfujino** [comment]
Linux & Mac Web Engine are known failures (documented in description), luci-engine is irrelevant, and cirrus `build_and_test_linux_unopt_debug` failed on a timeout. I triggered a retry, but I will merge this now to keep the release rolling (the equivalent LUCI build is green).

**Comment by christopherfujino** [comment]
Ran into https://github.com/flutter/flutter/issues/77659 post-submit for Windows Host Engine.

**Pull request merged**
