### PR TITLE
Cherrypick #29783 to flutter-2.8-candidate.6

### PR DESCRIPTION
**Pull request by xster**
Request: b/206892337

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm

**Comment by jmagman** [comment]
The luci link is missing but the Mac Unopt failure is https://ci.chromium.org/p/flutter/builders/try/Mac%20Unopt/6226.
Rebase onto https://github.com/flutter/engine/pull/29668

**Comment by jmagman** [comment]
> Rebase onto #29668

Oh never mind, this is a cherry-pick.

**Comment by xster** [comment]
I'm not cherry picking that bigger change into this cherry pick. It's a lint that failed and `Mac iOS Engine` has reasonable coverage. I'm merging this

**Pull request merged**
