### PR TITLE
Extract WideToUTF16String/UTF16StringToWide to FML

### PR DESCRIPTION
**Pull request by cbracken**
In third_party/accessibility, for string conversion, we use a mix of:
* FML
* third_party/accessibility base string utility functions
* static functions local to the translation unit itself

This moves all conversions between UTF16 and wide strings to FML. Note that this implementation is only safe on platforms where:
  * the size of wchar_t and char16_t are the same
  * the encoding of wchar_t and char16_t are both UTF-16 which is the case for Windows, hence why these functions are implemented in a Windows-specific translation unit (wstring_conversion).

Issue: https://github.com/flutter/flutter/issues/118811

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]
Nice!

**Review by loic-sharma — APPROVED** [review]
Still LGTM :)

**Review by yaakovschectman — APPROVED** [review]
LGTM. I was thinking about this too

**Comment by chinmaygarde** [comment]
The windows failures do look related.

**Comment by cbracken** [comment]
Yep - two of the tests were wrong; serves me right for adding em from a Mac.

**Comment by cbracken** [comment]
Looking good now :)

**Comment by godofredoc** [comment]
Reverting as it broke the tree https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/19925

**Comment by cbracken** [comment]
Oh wow. I'm curious how that wasn't caught in presubmit! 

We should definitely not be using //third_party/accessibility:base outside of the accessibility tree. I'll fix that code and see if I can add a visibility restriction so people don't re-add code like that in future.

**Comment by cbracken** [comment]
Ah I see why it wasn't caught - a new usage was introduced between the time presubmits ran and the patch landed.

**Pull request merged**
