### PR TITLE
Move channel and codec related files to common

### PR DESCRIPTION
**Pull request by krisgiesing**
This is in preparation for implementing channel and plugin support
for macOS desktop builds.

### CODE REVIEW

**Comment by krisgiesing** [comment]
Note, this is somewhat different from Greg Simon's approach in his branch. It seems better to me to move the common files than reference them across platforms, but please let me know if you'd prefer a different approach.

**Comment by krisgiesing** [comment]
Also, it seems like the capitalization scheme should be reconciled, but I'm not entirely sure I understand when to use camel case vs. underscores.

**Comment by chinmaygarde** [comment]
There are likely gaps in my understanding of some of the decisions made around supporting custom embedders as I was OOO for a few weeks. So I apologize in advance if I am missing some key piece of context in making the following statements.

Flutter would like to support custom embedders in a way that:
* Allows embedders to have maximum flexibility over their message loops, threading, rendering, etc..
* Makes it easy for Flutter engine developers to guarantee API and ABI stability for users of the Flutter engine while still making rapid changes to the mobile and Fuchsia shells.

Towards this end, it was decided that the Flutter engine would be vended as a single dynamic library on supported platforms with an extremely thin API (introduced in https://github.com/flutter/engine/pull/3987). The entirity of the API is descibed in a single header file with no external dependencies. This file is available at https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h. This C API has a stable ABI. Clients are expected to check in this dynamic library and header into their source tree and integrate the same into their build system.

The embedder API is window toolkit and renderer agnostic. There is an example provided here https://gist.github.com/chinmaygarde/8abf44921f7d87f6da7bf026267c4792 that uses the embedder API on Mac to draw the contents of the Flutter application in a window using the GLFW library. The use of GLFW was to prove a point, but one can just as easily use the Cocoa APIs on Mac. There are provisions made for platform specific events (window metrics, pointers, etc..) as well as the more generic platform channels mechanism. For reference, this is how the Sparklight project consumes the engine.

I want to make it clear that the embedder API in its current form is probably insufficiently expressive to handle the use cases of all embedders. But, we do want to work towards evolving it to make it so. And, eventually switch the mobile as well as Fuchsia shells over to using the same.

With this bit of background out of the way, I want to make you successful in using the embedder API to implement the desktop Mac embedder. For this purpose, I am suspicious you need this channels machinery on the other side of the embedder boundary. This pulls in a lot of dependencies you probably can do without for your use case. All the platform specific events can be dispatched into the embedder using the current embedder APIs. And, if the API is not sufficient, I would be happy to augment it to fit your needs. Since your particular use case requires only a Mac build, I would be delighted to help setup a Mac desktop build (using Cocoa APIs) of the embedder using this scheme. One that handles handles platform key events. For reference, the GLFW implementation is only about a 100 lines of code this will give me the opportunity to document some of the internal platform channels APIs.

The contents of this PR in isolation look good to me. But please consider using the embedder API. I promise it will make using the engine easier.

PS: Travis is mad about the licenses file. If you used the embedder API and built things yourself, you wouldn't have to deal with the licenses script either.

PPS: Objective-C files use camel casing according to the style guide. I must admit following the style guide diligently for the few objc files in the source tree has been more trouble than it is worth.

**Comment by krisgiesing** [comment]
@chinmaygarde - thanks for the clear and detailed explanation! I apologize for adding you as a code reviewer without discussing in person first; as you might guess, I talked to @cbracken about this while you were out, and am attempting to follow up on the work we outlined there.

I'm aware of the C embedder API and the plan to provide the engine to macOS consumers as a framework. This PR is actually intended to help achieve the latter; the idea is that the current shell app target would become a framework target instead, and that this framework target would include files from the desktop and the common areas of the tree (but not from the iOS area of the tree). It's the framework, rather than the client app of the framework, that would need the channel support files I'm moving in this pass. Specifically, I'd like to add text input support to the engine (framework) on macOS, modeling that support on the existing iOS implementation; the iOS implementation uses system channels, so I was intending to wire that up on macOS in a similar way. (See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/text_input.dart#L372.)

The text input support could be added by the native client of the engine framework instead. It seemed cleaner to me to port the existing iOS behavior, but I could be missing some context on the intended scope of the embedded framework. Let's find some time to discuss.

**Comment by chinmaygarde** [comment]
Any updates on this PR?

**Comment by krisgiesing** [comment]
The travis failure seems unrelated to the change, seems like a temporary connectivity issue reaching pub? I can either land the change as is or tickle travis again; not sure what the team's best practice is there.

**Comment by chinmaygarde** [comment]
I didn't realize it was a temporary issue. I restarted the builds. They should be done in a few mins.

**Comment by krisgiesing** [comment]
I don't really understand why this git history here is so screwed up. I'll create another PR and abandon this one.

**Comment by krisgiesing** [comment]
Wait, it actually merged successfully? googlebot's message suggested otherwise. Well I guess it's OK.

**Comment by Hixie** [comment]
This looks like it broke Mac.

**Comment by chinmaygarde** [comment]
@amirh is reverting this to fix builds. I'll re-land after fixing the iOS targets.

**Pull request merged**
