### PR TITLE
[fuchsia] Stop unimplemented TextInput from log spamming.

### PR DESCRIPTION
**Pull request by akbiggs**
We see a lot of complaints about log
spam related to this specific platform
message, and we haven't implemented it for a while,
so I'm turning off this specific error for
now.

### CODE REVIEW

**Comment by akbiggs** [comment]
Requesting test exemption since the only observable behavior currently is logging which I don't think we should test against.

**Comment by akbiggs** [comment]
@filmil @sanjayc77 FYI

**Comment by filmil** [comment]
LGTM

**Comment by Hixie** [comment]
In general we _do_ want to test that there is no log spam, so if there's a way to verify that it would be good to do so.
We have many tests in general that verify that the output is free of log spam for many specific cases, FWIW.

**Review by naudzghebre — APPROVED** [review]
LGTM

**Comment by akbiggs** [comment]
"We have many tests in general that verify that the output is free of log spam for many specific cases, FWIW."

Sorry @Hixie I'm having trouble finding these tests. :( Do you have an example I can follow?

**Comment by Hixie** [comment]
I think mostly they're in flutter/flutter, especially tool tests. But in general anywhere you have a test that can generate log spam, it's usually relatively easy to filter the logs through some code that can then check that only acceptable lines are being output.

**Comment by akbiggs** [comment]
I can't come up with a strategy to test this so I'm going to land it. I accept that the spammy logs may reappear in the future.

**Pull request merged**
