### PR TITLE
NNBD migration for scenario_app

### PR DESCRIPTION
**Pull request by dnfield**
Migrate scenario app to NNBD

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by dnfield** [comment]
@godofredoc @keyonghan - I'm not sure what's controlling the filtering here, but this should have triggered some Android and/or iOS builds. I think we probably don't do the iOS build on presubmit, but I'm pretty sure the Android one would have run. I'll see if I can find where the filter is...

**Comment by dnfield** [comment]
Errr... I'm not sure what that bot message means and I just hit the land button.

**Comment by keyonghan** [comment]
> @godofredoc @keyonghan - I'm not sure what's controlling the filtering here, but this should have triggered some Android and/or iOS builds. I think we probably don't do the iOS build on presubmit, but I'm pretty sure the Android one would have run. I'll see if I can find where the filter is...

It is controlled by `run_if` in .ci.yaml. Here no LUCI builders are scheduled, I guess some delay, or cocoon backend error when triggering/scheduling. /cc @yusufm Do you mind helping take a look?

**Comment by dnfield** [comment]
Ahh ok - it wasn't a `runIf` issue, it looks like they just didn't get scheduled.

**Pull request merged**
