### PR TITLE
Use explicit ndk version instead of ndk-bundle.

### PR DESCRIPTION
**Pull request by GaryQian**
`ndk-bundle` tends to be a few versions behind state-of-the-art.

In order to support building android engine on m1 mac, we need NDK 24+.

This does some path renaming to massage the downloaded ndk into the format we expect.

Additional changes are needed to support building on M1, this is a first step to obtain necessary dependencies.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
lgtm but @blasten should also probably take a look at this. He is OOO this week though.

**Comment by chinmaygarde** [comment]
Can you address the presubmit failures please? If @blasten doesn't have the cycles to review this, let's land this after presub fixes.

**Comment by GaryQian** [comment]
I'm working on getting M1 android engine building first. I'd like to make this change in sync with that as the NDK-bundle change is not needed for other reasons.

**Comment by chinmaygarde** [comment]
Marking this as WIP till then. Thanks!

**Comment by GaryQian** [comment]
I believe this is no longer necessary as `ndk-bundle` syncs up with latest versions.

**Pull request closed without merging**
