### PR TITLE
Flush image textures before they are bound by the UI thread

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth @chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm. Thanks for the investigation!

**Comment by eseidelGoogle** [comment]
How does this manifest?  Does this fix a bug?  Can it be tested? :)

**Comment by chinmaygarde** [comment]
Manifests as corrupted textures. Jason was seeing this on the Android emulator. This is my fault. I did not realize the flush was necessary when I first wrote the resource context upload routine. It is.

**Pull request merged**
