### PR TITLE
Adds bugprone-unchecked-optional-access to .clang-tidy

### PR DESCRIPTION
**Pull request by zanderso**
WIP

### CODE REVIEW

**Comment by chinmaygarde** [comment]
This is going to be so useful. We've run into this a few times in the past. cc @bdero

**Comment by zanderso** [comment]
There are more violations that I was expecting so I'll set us up to enable this incrementally.

**Comment by chinmaygarde** [comment]
Roger. It might be a good idea to just enable this in Impeller first. Since all Impeller components have their own GN template, you can add this flag [just for Impeller here](https://github.com/flutter/engine/blob/eed12f36f5956a37fb4ba13f1b670a5d41c37edb/impeller/tools/impeller.gni#L84).

**Comment by bdero** [comment]
> This is going to be so useful. We've run into this a few times in the past.

Yup, this is by far the most common way I push crashers. :)

**Pull request closed without merging**
