### PR TITLE
Added support for lerpDuration().

### PR DESCRIPTION
**Pull request by matthew-carroll**
Adds the ability to linearly interpolate `Duration`s.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@cbracken @Hixie I have a question on testing for this PR. I did a search through the `testing/dart` directory in the engine repo and didn't find any existing tests for `lerpDouble`, which is where I planned to add tests for `lerpDuration`. Any idea if those tests are located somewhere else, or if we simply don't have any such tests?

**Comment by cbracken** [comment]
Nice catch. Thanks for spotting this! Just sent https://github.com/flutter/engine/pull/20778 which adds tests for `lerpDouble`.

**Comment by Hixie** [comment]
Would it make more sense to put this in the foundation library of the flutter framework? Generally we try to keep dart:ui as small as possible and so we only put things here that we need to have here. (If there's a reason to have it here of course that's fine.)

**Comment by matthew-carroll** [comment]
@Hixie sure, I can move it. I just went immediately to where `lerpDouble` was located, but I'll move it to foundation.

**Comment by matthew-carroll** [comment]
Closing in favor of an implementation in Foundation instead of dart:ui:
https://github.com/flutter/flutter/pull/64668

**Pull request closed without merging**
