### PR TITLE
[Impeller] Absorb DrawPaints at the beginning of EntityPasses

### PR DESCRIPTION
**Pull request by bdero**

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
This could probably do with a unit test. Can we detect that nothing has been drawn on an aiks canvas?

**Comment by chinmaygarde** [comment]
I don' think this is quite right. It depends on the pass load action being something specific (Color::BlackTransparent). Which I suppose is true now for Aiks. We should be able to handle all clears (multiple redundant clears or calls before clears) one level below this.

**Comment by bdero** [comment]
I don't think this PR will produce incorrect rendering results, but I'm refactoring it to make it more aggressive and set the clear color.

**Comment by bdero** [comment]
Alright, I fixed this up to absorb back-to-back clears regardless of their color. Also managed to sneak in a test.

**Comment by zanderso** [comment]
SkiaPerf is showing this was a nice improvement:

https://flutter-flutter-perf.skia.org/e/?begin=1680019824&end=1680068938&keys=Xb61f60087363c82f825669970a96f51d&num_commits=50&request_type=1&xbaroffset=34046

https://flutter-flutter-perf.skia.org/e/?begin=1680019824&end=1680068938&keys=Xf0f0f379a989b7b62fec6f5b22baf3ee&num_commits=50&request_type=1&xbaroffset=34046

**Pull request merged**
