### PR TITLE
Make fl_method_call constructor public

### PR DESCRIPTION
**Pull request by stuartmorgan**
There is nothing about creating an FlMethodCall instance that requires
private knowledge, and it can be useful (e.g., in plugin tests) for
clients of the library to be able to do so.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by robert-ancell — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]
lgtm

**Comment by stuartmorgan** [comment]
It's actually a missing include, but the bigger issue is that the include would create a circular reference.

@robert-ancell How would I forward declare a GObject type? (In this case, forward declaring `FlMethodChannel` in the `FlMethodCall` header.)

**Comment by robert-ancell** [comment]
> It's actually a missing include, but the bigger issue is that the include would create a circular reference.
> 
> @robert-ancell How would I forward declare a GObject type? (In this case, forward declaring `FlMethodChannel` in the `FlMethodCall` header.)

Perhaps it would be easiest to work around the issue by keeping this in a separate header file, i.e. make something like `fl_method_call_unittest.h`? The other method that seems to be in use is to put typedefs in header `fl_types.h`, like in [glib](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gtypes.h) and [gtk](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtktypes.h).

**Comment by chinmaygarde** [comment]
Stuart, are you able to continue on this PR with Roberts suggestion.

**Comment by stuartmorgan** [comment]
Yes, I just need to find time to get back to it to look into make a types header.

**Comment by chinmaygarde** [comment]
Marking as WIP so it doesn't get flagged in issue triage.

**Comment by stuartmorgan** [comment]
Closing until I can revisit.

**Pull request closed without merging**
