### PR TITLE
Enable physical keyboard support for FNL

### PR DESCRIPTION
**Pull request by shinykitten**

### CODE REVIEW

**Comment by shinykitten** [comment]
@krisgiesing @abarth

**Comment by krisgiesing** [comment]
LGTM but then I helped you author it :)

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
I'm surprised we don't defined OS(LINUX) on FNL.

**Comment by krisgiesing** [comment]
Actually, Chris, can you try without this change? We might have been fooled by the missing block of code in the ozone platform viewport implementation.

**Comment by shinykitten** [comment]
This does not appear to be necessary.

**Pull request closed without merging**
