### PR TITLE
Roll Skia

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
TBR @chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

**Comment by chinmaygarde** [comment]
This roll is causing instability in the iOS builds. Investigating. Is this safe to revert till I figure out a fix?

**Comment by abarth** [comment]
Should be.  The roll was just for housekeeping.

**Comment by chinmaygarde** [comment]
I am reverting this. Skia seems to be using the `kBGRA_8888_GrPixelConfig` format for creating the color attachments of the framebuffer used for rendering into the texture atlas. This is unavailable without extensions. Will track a fix upstream and update after verifying one is in place.

**Comment by eseidelGoogle** [comment]
Do you have a Skia bug on file?  lgtm

**Comment by chinmaygarde** [comment]
I am following up on this in chat. Will file a bug too.

**Pull request merged**
