### PR TITLE
include nested Picture stats in DisplayList byte and op counts

### PR DESCRIPTION
**Pull request by flar**
SkPicture.approximateBytes() will automatically included nested pictures and the size of the SkPicture object, but the analogous method on DisplayList was not doing so.

SkPicture.approximateOps() has a boolean to optionally include nested op counts, but the analogous DisplayList method had no option.

This PR introduces options on the DisplayList::op_count() and DisplayList::byte_count() accessors to include or exclude nested stats (defaults to true for bytes, false for ops)

### CODE REVIEW

**Comment by flar** [comment]
The only place the byte_count is used is in a native method from the Dart Picture object. It does not impact caching or memory reporting in the timeline traces or FrameTimings.

The op_counts are not changed by this PR and so the caching decisions should remain the same. The caching decisions will not be affected by this change.

**Review by chinmaygarde — APPROVED** [review]

**Comment by flar** [comment]
@chinmaygarde one line update, not sure if you want to re-review...

**Comment by flar** [comment]
(Make that 2 one-line updates, sorry...)

**Comment by chinmaygarde** [comment]
Still lgtm.

**Pull request merged**
