### PR TITLE
Utilities for creating texture backed SkImages.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Out of curiosity: Is there a bug we should relate this to?

**Comment by chinmaygarde** [comment]
@eseidelGoogle: Its part of a series of patches that will eventually give us the asynchronous texture upload. So maybe https://github.com/flutter/flutter/issues/3805 and a couple of others.

**Comment by chinmaygarde** [comment]
I can also just wait till I am done with the whole thing and send a larger PR.

**Comment by abarth** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Thanks. :)  Just curious for context, that's all.

**Pull request merged**
