### PR TITLE
Make `lib/ui/painting/...` compatible with `.clang_tidy`.

### PR DESCRIPTION
**Pull request by matanlurey**
Work towards https://github.com/flutter/flutter/issues/134969.

All changes were made automatically (i.e. with `--fix`).

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM.

This will be tested when we enable the lint, but should still get a test exemption.

**Comment by matanlurey** [comment]
Ack. I've asked Stuart and am waiting patiently :)

**Comment by jonahwilliams** [comment]
This change might have slightly improved hot reload performance: https://flutter-flutter-perf.skia.org/e/?keys=X36d378e38a849bab05770ed6f82542cc&selected=commit%3D38007%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DhotReloadMillisecondsToFrame%252Ctest%253Dhot_mode_dev_cycle__benchmark%252C&xbaroffset=38007

**Comment by matanlurey** [comment]
> This change might have slightly improved hot reload performance: https://flutter-flutter-perf.skia.org/e/?keys=X36d378e38a849bab05770ed6f82542cc&selected=commit%3D38007%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DhotReloadMillisecondsToFrame%252Ctest%253Dhot_mode_dev_cycle__benchmark%252C&xbaroffset=38007

Neat, thanks for sharing!

**Pull request merged**
