### PR TITLE
Added FunctionRef to fml.

### PR DESCRIPTION
**Pull request by gaaclarke**
Added absl::FunctionRef equivalent from WebRTC.  Added unit test and found a nice place where it can be used.

### CODE REVIEW

**Comment by gaaclarke** [comment]
This isn't going to fly with legal as-is.  I have to put it in third_party or write my own version.  Let me give it another stab.

**Comment by chinmaygarde** [comment]
This extra component does not solve any current problem in the engine. In the absence of justification for its inclusion in terms of code cleanliness and/or demonstrable performance improvements, I consider this unnecessary code bloat and maintenance overhead. In fact, the restrictions of this relative to std::function (like not being able to use it as a return value) make it harder to decide when std::function should be used vs this new type.

**Comment by gaaclarke** [comment]
@chinmaygarde https://vittorioromeo.info/index/blog/passing_functions_to_functions.html#function_view

In clang, at worst, it's 2x faster.  It also documents the semantics of the function.  I'm going to see if i can get it going quickly.  It's starting to make sense to me how the black magic works.

**Comment by chinmaygarde** [comment]
> it's 2x faster

Is the workflow being made faster an existing bottleneck? Is the improvement possible to see in frame times? If not, I am confident the 309 extra lines of code to add and maintain is not a worthy tradeoff.

**Comment by gaaclarke** [comment]
It's such a dead simple drop-in replacement that has a positive effect on cpu and battery and clears up semantics, similar to `@Nullable` in java.  It would almost be a sin to turn our backs on such a simple savings of battery usage when multiplied across all users of flutter.

I gave up eating beef and lamb for the carbon footprint, this could undo all that!

**Pull request closed without merging**
