### PR TITLE
Added dependency on CppWinRT for UWP builds

### PR DESCRIPTION
**Pull request by cbracken**
CppWinRT is a tool that generates standard C++17 header-file libraries
for Windows Runtime (WinRT) APIs. A more detailed introduction to
C++/WinRT can be found in the Microsoft documentation at
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/.

The source code is available under an MIT license, from
https://github.com/microsoft/cppwinrt.

Bug: https://github.com/flutter/flutter/issues/70205

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Review by clarkezone — APPROVED** [review]
LGTM.  Confirmed that the tool binaries work as expected.  There is one caveat: there is a potential bug in the generated output of the tool that I thought had been fixed.  Need to confirm that it is still a problem (`std::terminate()` not working as expected; fixed using `abort()` instead); if that is the case we'll need to re-ingest tool once the fix is in.

**Comment by cbracken** [comment]
Sounds good. This was a build released on 2021-03-01. If it's been fixed more recently it'll be easy to re-bundle as soon as the new build is up on nuget.

**Comment by clarkezone** [comment]
The clang issues are now fixed in https://github.com/microsoft/cppwinrt/releases/tag/2.0.210304.5 @cbracken clear to update the package.

**Comment by clarkezone** [comment]
Consuming this with:

https://github.com/flutter/buildroot/pull/442
https://github.com/flutter/engine/pull/24861

**Pull request merged**
