### PR TITLE
Manual merge of Dart  a3815b6590...24c7666def

### PR DESCRIPTION
**Pull request by a-siva**
Manual merge of Dart  a3815b6590...24c7666def

dart-lang/sdk@24c7666def Update tests that have the current version number hardcoded
dart-lang/sdk@f88ce7aef5 Increase Dart version to 2.10

### CODE REVIEW

**Comment by jason-simmons** [comment]
The web SDK build is failing.  Does this need the `lib/web_ui` changes from https://github.com/flutter/engine/pull/19941?

**Comment by a-siva** [comment]
> The web SDK build is failing. Does this need the `lib/web_ui` changes from #19941?

I have updated it.

**Comment by jason-simmons** [comment]
I'm also seeing errors because the web SDK build depends on the `package_config.json` file in `third_party/dart/.dart_tool`.

It looks like the Dart SDK needs to be rolled to include https://github.com/dart-lang/sdk/commit/f88ce7aef5f8a41fddfab8e26f8b2c6e0e950236

**Comment by a-siva** [comment]
> I'm also seeing errors because the web SDK build depends on the `package_config.json` file in `third_party/dart/.dart_tool`.
> 
> It looks like the Dart SDK needs to be rolled to include [dart-lang/sdk@f88ce7a](https://github.com/dart-lang/sdk/commit/f88ce7aef5f8a41fddfab8e26f8b2c6e0e950236)

I believe the package_config.json files in packages/flutter/.dart_tool and packages/flutter_tools/.dart_toolneeds to be updated,  will that happen only when the engine version rolls into the framework ?

**Comment by jason-simmons** [comment]
The `package_config.json` files in the framework tree should be generated on demand.  Possibly the user might need to do a `git clean` and `flutter update-packages` to force a rebuild.

**Comment by a-siva** [comment]
> The `package_config.json` files in the framework tree should be generated on demand. Possibly the user might need to do a `git clean` and `flutter update-packages` to force a rebuild.

Does that happen in these PR checks ? For instance see the errors in
https://github.com/flutter/engine/pull/19967/checks?check_run_id=900797340

**Comment by jason-simmons** [comment]
I was able to get the framework test suite to run with an engine built with this PR by:
* configuring the framework to use the `2.10.0-0.2-preview` Dart SDK version specified by this PR
* patching flutter_tools to hardcode the `nullsafety.2` versions of packages where required (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L35)
* running `flutter update-packages --force-upgrade`

The web integration tests are trying to run framework tests using the results of the roll, but that will not work without the corresponding patches to the framework.  We may need to land this roll in its current state, temporarily close the tree, and then manually land a framework roll that updates the framework's dependencies.

**Comment by zanderso** [comment]
The engine -> framework roll is backed up already: https://github.com/flutter/flutter/pull/62080

I'm not sure we'll be doing ourselves any favors by piling this on as well.

**Comment by zanderso** [comment]
https://github.com/flutter/flutter/issues/62139

**Comment by zanderso** [comment]
Somehow, cirrus at head of flutter/flutter is already seeing 2.10: https://cirrus-ci.com/task/5369465632194560?command=setup#L337 and this is causing breakage. I'm not sure how cirrus could have skipped ahead.

**Comment by a-siva** [comment]
Can this PR land now? Can somebody give me an LGTM.

**Comment by zanderso** [comment]
After @jason-simmons manual rolls, we are hitting a Dart VM OOM in the device lab: https://github.com/flutter/flutter/issues/62206

**Comment by zanderso** [comment]
We need to land this to pick up a fix for https://github.com/flutter/flutter/issues/62206

**Comment by dnfield** [comment]
This may have broken `//flutter/tools/run_third_party_dart.py`, which expects ot be able to run `//third_party/dart/tools/sdks/dart-sdk/bin/dart pub global activate`.  The binary is complaining that `pub` is not a file or directory.

**Comment by jason-simmons** [comment]
I can reproduce the `dart pub` failure on Mac but not Linux.  Changing `run_third_party_dart.py` to use `dart-sdk/bin/pub` instead of `dart-sdk/bin/dart pub` should work.

**Comment by dnfield** [comment]
According to @whesse CIPD may have a bad version of Dart for mac.

**Comment by dnfield** [comment]
This is going to make LUCI red once the builds finish. We'll need another Dart roll to at least https://github.com/dart-lang/sdk/commit/36614642973dd0fa7594839fdb42d50ae6663e34

**Comment by jason-simmons** [comment]
Yeah - the Dart SDK in `third_party/dart/tools/sdks/dart-sdk/bin` on Mac is version `2.10.0-edge.9969bc6b3d56080ba1d1024feec2e51545de854c`.  It looks like it contains a commit that disabled the DartDev-style `dart` subcommands.  So `dart` is using the `pub` argument as a Dart script filename.

On Linux that Dart SDK is version `2.10.0-edge.b61f57bcca1e1abf02216ced35d781e81d145451`

**Pull request merged**
