### PR TITLE
Roll Skia to 45a00cee88c0ea8ea175694cb94b26748713fe36 and update licenses.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @mikejurka who is waiting on this.

**Comment by chinmaygarde** [comment]
@jason-simmons: The license script behavior seems odd to me. It updated a bunch of files in the Android NDK but it seems to be that the only changes were to the case sensitivity of the file names. Can't explain this behavior other than this time I ran the license script from the laptop rather than my workstation.

**Comment by abarth** [comment]
LGTM

**Comment by jason-simmons** [comment]
I'm guessing that this is some sort of Mac vs. Linux issue given that we download different NDK tarballs for each host platform.

We don't have a solution for this - the golden files are typically generated on Linux, and comparing them to output from a Mac will yield a bunch of unnecessary diffs

**Comment by chinmaygarde** [comment]
On the Mac laptop, I am on a case insensitive filesystem. Meanwhile, on my workstation, all repositories are on a disk image I created that happens to be case sensitive (to be better compatible with everyone else working on Linux).

I tried tooling around with the script to account for the case sensitivity but there are also a few files in shader tools that are different on Mac vs Linux. Giving up for now. Will regenerate on a Linux machine.

**Comment by chinmaygarde** [comment]
Another oddity I just ran into. Turns out some of the NDK files do not seem to count towards the SHA generated. So when I took my patch that I initially generated on a Mac and applied it on Linux, it seemed to think that there were no changes to any of the //third_party files. Had to apply the patch minus the incorrect changes spewed by the license script on Mac. This is a bit of a mess.

In any case, the licenses are fine now.

**Pull request merged**
