### PR TITLE
Roll ANGLE to latest version

### PR DESCRIPTION
**Pull request by stuartmorgan**
## Description

Rolls ANGLE to the latest master. This will help support upcoming UWP work.

## Related Issues

https://github.com/flutter/flutter/issues/14967

## Tests

I added the following tests: None; no intended behavioral changes. This is just to allow future patches to work from a newer base.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by clarkezone — APPROVED** [review]
LGTM.. thx

**Review by cbracken — APPROVED** [review]
lgtm!

**Comment by chinmaygarde** [comment]
This needs to be rebased for the presubmits to pass as the issue was fixed by Jonah. Lets land this ASAP.

**Comment by stuartmorgan** [comment]
> This needs to be rebased for the presubmits to pass as the issue was fixed by Jonah. Lets land this ASAP.

I was waiting for you to approve https://github.com/flutter/buildroot/pull/407, which I just discovered I never requested your review on :(

**Comment by stuartmorgan** [comment]
I've fixed one license issue upstream in ANGLE (I'll update this PR to pull that version of ANGLE), and have a fix out to abseil to fix a couple of license issues there. That will resolve the three license issues that remain after the license script updates I've added here.

**Pull request merged**
