### PR TITLE
Roll dart to ee15c8eb689791f6777eb3f6b0a1e9c58ff0671b.

### PR DESCRIPTION
**Pull request by aam**

### CODE REVIEW

**Comment by aam** [comment]
@a-siva @zanderso looks like boringssl upgrade made flutter license check unhappy:
```
+flutter/travis/licenses.sh
Verifying license script is still happy...
Resolving dependencies... 
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.31.0 for the following packages:
archive, args, charcode, collection, convert, crypto, path, typed_data
To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
Downloading archive 1.0.33...
Downloading args 0.13.7...
Downloading crypto 2.0.2+1...
Downloading collection 1.14.5...
Downloading convert 2.0.1...
Downloading charcode 1.1.1...
Downloading path 1.5.1...
Downloading typed_data 1.1.5...
Got dependencies!
Precompiling executables... 
Precompiled archive:tar.
Finding files...
../../../third_party/boringssl/src/crypto/fipsmodule/policydocs/BoringCrypto-Security-Policy-20170615.docx!/docProps/thumbnail.emf
failed to handle ../../../third_party/boringssl/src/crypto/fipsmodule/policydocs/BoringCrypto-Security-Policy-20170615.docx!/docProps/thumbnail.emf: FormatException: Bad UTF-8 encoding 0xb (at offset 21)
failure: FormatException: Bad UTF-8 encoding 0xb (at offset 21)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      Utf8Decoder.convert (dart:convert/utf.dart:350)
#2      Utf8Codec.decode (dart:convert/utf.dart:72)
```

**Comment by a-siva** [comment]
The license checker script does have  a set of regular expressions of file name patterns that are excluded, I am wondering if we should add this file to the list of patterns to exclude or maybe have a generic check that the file should be a text file.

**Comment by aam** [comment]
Yes, we could add those to ignored list. I primarily wanted to confirm that we do indeed want to include all those Microsoft document(docx) artifacts.

**Comment by aam** [comment]
@Hixie , did we have to deal with MS Word docs before?

**Comment by aam** [comment]
I thought real license file is `sky/packages/sky_engine/LICENSE`, which was changed as part of this PR.

**Pull request merged**
