### PR TITLE
Clear the surface to transparent black when creating a PlatformViewWrapper

### PR DESCRIPTION
**Pull request by jason-simmons**
Without this, an opaque black surface may briefly flash onscreen when the platform view is shown (see internal issue b/332379081)

This matches the behavior used before to the introduction of PlatformViewRenderTarget in https://github.com/flutter/engine/commit/204625490ca1b8a3a9fd939d9399a8b0242ca207

That commit moved the clearing of the surface into SurfaceTexturePlatformViewRenderTarget.  But that caused surface clearing to happen in scenarios where there was no PlatformViewWrapper, resulting in the issue seen in https://github.com/flutter/flutter/issues/141068

Later the surface clearing was removed from SurfaceTexturePlatformViewRenderTarget, causing the flashing black screen.

### CODE REVIEW

**Comment by tugorez** [comment]
nit: Is there a test that can be added to prevent issues like this from happening in the future?

**Comment by johnmccutchan** [comment]
test-exempton: not testable with our current testing story.

**Review by johnmccutchan — APPROVED** [review]
Thanks!

**Comment by johnmccutchan** [comment]
@tugorez There is no programmatic way to get at the pixels in the render target. We need to support screenshots of platform views in order to test this, this is planned for Q2.

**Pull request merged**
