### PR TITLE
Flutter 1.22.0-12.2.pre engine cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

- [x] Dart 2.10.0-110.5.beta
  * https://github.com/dart-lang/sdk/commit/4215dca724fb80de592f51a6cdba51e7638d1723
- [x] Dark mode friendly ios debugging
  * https://github.com/flutter/flutter/issues/66161
  * https://github.com/flutter/engine/commit/8360b134717d386e32e82e309972e107258c8653
  * Author @jmagman, original approvers @xster and @chinmaygarde 
- [x] Update error text for iOS 14 launch
  * https://github.com/flutter/flutter/issues/66491
  * https://github.com/flutter/engine/commit/dd35b5b65917c30b0e0a37d5cbee36043fb8f40c
  * Author @timsneath, original approver @jmagman 
- [x] Platform views in Add2App (iOS only) are broken
  * https://github.com/flutter/flutter/issues/66026
  * https://github.com/flutter/engine/commit/678653bfb68838db40364ab64ce9a3ba80b296d2
  * Author @cyanglaz, original approver @blasten 
- [x] [Add2App] Android leaks the FlutterView
  * https://github.com/flutter/flutter/issues/65941
  * https://github.com/flutter/engine/commit/11befe419e3c3bcb83c52de1a6570ec6ef10d8dc
  * Author @jason-simmons, original approver @GaryQian 
- [ ] Bottom insets are not stable when keyboard shows on screen on Android 11
  * https://github.com/flutter/flutter/issues/65821
  * https://github.com/flutter/engine/commit/933f811d94ab84e60174b8395b6f87b3633ff97d
  * Author @GaryQian, original approver @xster 
- [x] App crashes when on tapping on TextFormField in a release APK on Android 11
  - https://github.com/flutter/flutter/issues/66232
  - https://github.com/flutter/engine/commit/034ab2e18e3872ab986475dc529ef2f2bb7a8e81
  - Author @jason-simmons, original approver @GaryQian

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
flutter/flutter#66161 and flutter/flutter#66491 LGTM

**Review by pcsosinski — APPROVED** [review]
approved for branch

**Comment by christopherfujino** [comment]
Everything green except a "Mac iOS Engine" failure during "Scenario App Integration Test":

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8868329632012433952/+/steps/Scenario_App_Integration_Tests/0/stdout

Investigating...

**Comment by christopherfujino** [comment]
Passed on re-run.

**Comment by cyanglaz** [comment]
flutter/flutter#66026 LGTM

**Comment by christopherfujino** [comment]
@chinmaygarde @xster @timsneath @jason-simmons @blasten could you PTAL at the relevant cherrypicks?

**Review by blasten — APPROVED** [review]

**Review by jason-simmons — APPROVED** [review]

**Comment by xster** [comment]
LGTM. Thank you Chris

**Review by timsneath — APPROVED** [review]

**Pull request merged**
