### PR TITLE
Switch the renderer to impeller based on the presence of a command line flag.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Specifying the `--enable-impeller` flag will switch the renderer to using
Impeller instead of Skia. On platforms where Impeller is not supported, this
flag is ignored.

The notion of the `flutter::SurfaceFrame` has been augmented. Now, in the
absence of a Skia surface to render to, the surface frame will render into a
display list instead.

Impeller variants of the context and surface variants have been added to
`shell/gpu` and `shell/platform`. The variants prepare surface frames that
don’t/can’t specify a Skia surface thus forcing the surface frame to render to a
display list instead. Then, in the submit callback, they forward the display
list ops to the Impeller display list dispatcher.

This scheme has been chosen as it requires the fewest updates to engine
internals which all depend on Skia data structures. Instead of updating all
call-sites to be Skia neutral, the display list interface itself is being made
graphics package agnostic.

### CODE REVIEW

**Comment by zanderso** [comment]
Looks like two differently configured Dart VMs are included in the link somehow.

**Comment by chinmaygarde** [comment]
> Looks like two differently configured Dart VMs are included in the link somehow.

I'm submitting an Impeller patch to fix those. Think those were caused by https://github.com/flutter/impeller/commit/3310f85aef188af17304ce269dfa1d3c267c477d

**Review by dnfield — APPROVED** [review]
LGTM as long as CI is happy

**Comment by dnfield** [comment]
Looks like licenses are still off and clang doesn't like using std::abs in a constexpr

**Review by bdero — APPROVED** [review]

**Review by zanderso — APPROVED** [review]

**Pull request merged**
