### PR TITLE
Roll Dart to 4b64a835b9c10480063739d1e73847dcc4d8bfb6.

### PR DESCRIPTION
**Pull request by rmacnak-google**

### CODE REVIEW

**Comment by aam** [comment]
dart buildbot go/darto looks reddish on that version. is that a concert?

**Comment by rmacnak-google** [comment]
The analyzer redness is an issue with some standalone tests, which doesn't concern me for an engine roll. Might be wise to wait on the rest of the VM bots to cycle though.

**Comment by aam** [comment]
Okay, but analyzer failures seems to be relevant as analyzer seems to be unhappy about crypto.dart move to _http:
```
FAILED: dart2analyzer-none release_x64 standalone/io/web_socket_error_test
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_WARNING|PART_OF_DIFFERENT_LIBRARY|/b/build/slave/azr-be/build/sdk/tests/standalone/io/web_socket_error_test.dart|23|6|36|Expected this library to be part of 'dart.io', not 'dart._http'.
```

**Comment by rmacnak-google** [comment]
It's unhappy about that the tests' library names aren't consistent with their cheaty use of `part`. Fixed in https://dart-review.googlesource.com/c/sdk/+/10582. Doesn't affect other users of dart:io or dart:_http.

**Comment by aam** [comment]
@rmacnak-google sorry, forgot about changes to sky/packages/sky_engine/BUILD.gn, _embedder.yaml that are needed to accommodate _http move: see https://github.com/flutter/engine/commit/f97e974e8cd58da75c699295384cd439a7369b13.

**Pull request merged**
