### PR TITLE
Fix embedder glfw examples cmake subdirectory path error

### PR DESCRIPTION
**Pull request by hongeSunCoder**
Fix just a cmake glfw subdirectory path error in embedder examples.

Fix: https://github.com/flutter/flutter/issues/138340

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM!

**Review by chinmaygarde — APPROVED** [review]

**Review by zanderso — APPROVED** [review]
lgtm, but as the message says, this PR will need a test exemption requested in the Discord room.

**Comment by bdero** [comment]
Whoops, slipped my mind. Asked for one in Discord.

**Comment by Hixie** [comment]
test-exempt: build script

**Pull request merged**
