### PR TITLE
[iOS] Make keyboard animation have higher refresh rate when available

### PR DESCRIPTION
**Pull request by luckysmg**
According to https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=swift#:~:text=High-impact%20animations,minimize%20power%20consumption

and here is the video that indicates the **refresh rates when iOS native switch the keyboard:**

https://user-images.githubusercontent.com/49340347/140853265-02aba049-3c9e-40f2-bbf4-b05fd4e268cb.MOV

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by luckysmg** [comment]
The `CAFrameRateRange` is available on Xcode13. Xcode12 doesn't have `CAFrameRateRange` API

**Comment by luckysmg** [comment]
Ready for review @gaaclarke

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
cc @iskakaushik is looking into a more generic solution for this. I don't think we should land this.

**Comment by luckysmg** [comment]
This displayLink is not the same as the display link in `vsync_waiter_ios`

**Comment by chinmaygarde** [comment]
We probably want to do the same thing for all display links instead of having of making this one-of change.

**Comment by luckysmg** [comment]
Got it 😁

**Pull request closed without merging**
