### PR TITLE
Account for removed elements in surface movement check. [web]

### PR DESCRIPTION
**Pull request by muhleder**
Several people have reported the widgets using HtmlElementView widgets losing the state of the actual html elements when apparently unrelated buttons are hovered. 

https://github.com/flutter/flutter/issues/53253
https://github.com/flutter/flutter/issues/39980
https://github.com/flutter/flutter/issues/51865

The state of the html elements is getting lost when the actual html elements are detached and reattached to the DOM. For iframes this loses the browser context https://stackoverflow.com/questions/8318264/how-to-move-an-iframe-in-the-dom-without-losing-its-state whilst for other element types more state is retained but some is still lost (e.g. I'm seeing scroll position being lost when detaching and reattaching an element)

Here's an example of an app that loses scroll position.

```
// ignore: avoid_web_libraries_in_flutter
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  // ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory('someViewType', (int viewId) {
    final wrapper = DivElement();
    final div = DivElement()
      ..contentEditable = 'true'
      ..style.width = '100%'
      ..style.height = '100%';
    wrapper.append(div);
    return wrapper;
  });
  runApp(MaterialApp(home: HomeScreen()));
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(),
      body: HtmlWidget(),
      floatingActionButton: Builder(builder: (context) {
        return FloatingActionButton(
          child: Icon(Icons.menu, color: Colors.white),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      }),
    );
  }
}

class HtmlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'someViewType');
  }
}
```

You can paste a large bunch of text into the content editable, then arrow down (scroll doesn't work - separate issue), open the drawer with the FAB, and then on closing the drawer the html view is moved in the DOM resulting in the scroll resetting to zero.

The point at which that element is detached is here https://github.com/flutter/engine/blob/bcc144d0d138cf1f2abe198c1108367c114e8da4/lib/web_ui/lib/src/engine/surface/surface.dart#L1210-L1227

I believe what is happening is that _children is a list of the surfaces that should be present after the update, and that newChild.rootElement is the actual DOM element representing one of those surfaces.

The code checks to see that the next sibling in the DOM of newChild.rootElement matches what is expected by the _children surfaces. What it doesn't account for in this example is that one of the DOM elements (the drawer in this case) is due to be removed but still exists in the DOM at this point.

So _children is

Surface representing FLT-OFFSET (contains HtmlElementView)
Surface representing FLT-TRANSFORM (contains FAB button)

But the DOM at the point of comparison is

FLT-OFFSET (contains HtmlElementView)
FLT-OFFSET (contains Drawer)
FLT-TRANSFORM (contains FAB button)

insertDomNodeIfMoved sees that the next sibling of the HtmlElementView in the DOM is not the FLT-TRANSFORM, so runs `containerElement.insertBefore(newChild.rootElement, nextSibling.rootElement);` to move the HtmlElementView to just before FLT-TRANSFORM and the state is lost.

What I believe it should do is check for the next element in the DOM that is actually present in the _children surfaces and compare against that instead.

The fix in this PR is working for me in this example with an HtmlElementView in the scaffold body, and also for the app bar button hovers that others have also been seeing. There may be other cases that this doesn't fix.

As an aside, you can use this little snippet pasted into the console window to give you a sync breakpoint you can stop on which should have the actual DOM removal code further up the call stack. (Don't use these DOM Mutation events in actual code https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events)

```
document.body.addEventListener('DOMNodeRemoved', (e) => {
        if (e.target.innerHTML && e.target.innerHTML.search(/flt-platform-view/)) {
            console.log('platform view removed');
        }
    }
);
```

### CODE REVIEW

**Comment by yjbanov** [comment]
@muhleder I have briefly checked your PR, and I like it in spirit. I will dig into it in more detail as soon as I respond to reviewer comments on my other PR.

My current hunch is that you are right, it probably won't fix all the issues related to state reset. We'll need a longer-term solution for that. Having said that, we should make this change (or similar) anyway for efficiency. We shouldn't move nodes around unnecessarily.

**Comment by olgeni** [comment]
Is this good to go? We are badly stuck with iframes 😅

**Comment by muhleder** [comment]
@olgeni It should stop iframes reloading when they shouldn't, it won't help with iframes swallowing pointer events in widgets that cover them (e.g. a drawer covering an iframe widget).

**Comment by yjbanov** [comment]
Sorry, that took longer than I expected.

I think the most efficient implementation would be to find all elements that did not move after we matched them (by computing the longest increasing subsequence), then insert them while walking backwards keeping track of the last stationary element. 

We use this algorithm in the [semantics tree](https://github.com/flutter/engine/blob/deef2663aca452dcd692c8b1b4ecf5a09239a0fc/lib/web_ui/lib/src/engine/semantics/semantics.dart#L901). It shouldn't be too hard to adapt it for this case but it will require some careful testing.

WDYT?

@muhleder I'm available to help with both coding and testing. Please let me know what your plan is so we can coordinate.

Next steps:

- [ ] Agree on the best algorithm to use.
- [ ] Add tests.

(unfortunately Github notifications UI is not showing this PR to me; I pinned the tab so I remember to check back in, but also don't hesitate to reach out on Flutter Discord over [hackers-web](https://discordapp.com/channels/608014603317936148/608022171637252115) or DM)

**Comment by muhleder** [comment]
@yjbanov Something that occurred to me that I haven't had a chance to investigate yet, would it be possible to remove the items from the DOM that are due to be removed before this reparented check is run? Then we could just keep the current implementation.

**Comment by yjbanov** [comment]
> @yjbanov Something that occurred to me that I haven't had a chance to investigate yet, would it be possible to remove the items from the DOM that are due to be removed before this reparented check is run? Then we could just keep the current implementation.

We could. We can walk `_children` twice. Once before calling `_discardActiveChildren`, where we call `retain`/`update`/`build`. Then again after calling `_discardActiveChildren`, where we call `insertDomNodeIfMoved`. We can even inline `insertDomNodeIfMoved` into the second loop since that's all it does.

I'm open this idea. It's a simpler change. OK with postponing the computation of minimal node movement to a future improvement.

**Comment by muhleder** [comment]
@yjbanov Ok, I should have some time this week to look at it. I'm in the middle of something else right now but happy to do this next.

**Comment by yjbanov** [comment]
@muhleder Sounds like a plan!

**Comment by yjbanov** [comment]
Just checking in. I see some new commits. Is this PR ready for review?

One thing I'll quickly mention is that I'm not convinced we should have the `html_element_state` e2e test like that. The test attempts to guarantee that we do not move the DOM node around the tree. However, with the current design we cannot make such a guarantee. This test can fail on seemingly subtle changes in the widgets, in the framework, or in the engine. This makes it too brittle.

Having said that, we should eventually have this test once we have a complete solution to platform view reparenting in the DOM.

**Comment by muhleder** [comment]
@yjbanov There is actually a bit more work to do on this, looking into it again this morning and whilst the current change does stop the scaffold body repaint when the drawer is closed, the first change actually covers more cases. Specifically the following case fails with the current change https://github.com/muhleder/engine/commit/044ef9de9e9e8424f9f37b802cdf3dd13c60a806 but worked with the original https://github.com/muhleder/engine/commit/f723f9f2dca0e1145c11eb535fde0d7569ae52c5. 


```
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  ui.platformViewRegistry.registerViewFactory('ScrollableElement', (int viewId) {
    final DivElement wrapperDiv = DivElement()
      ..id = 'wrapper'
      ..style.overflowY = 'auto';
    final DivElement scrollableDiv = DivElement()
      ..id = 'scrollable'
      ..style.width = '100px'
      ..style.height = '500px'
      ..style.backgroundImage = 'linear-gradient(red, orange, yellow, green, blue, indigo, violet)';
    wrapperDiv.append(scrollableDiv);
    return wrapperDiv;
  });
  runApp(MyHomePage());
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool removed = false;

  _toggleContainer() {
    removed = !removed;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        GestureDetector(
          onTap: _toggleContainer,
          key: Key('toggle'),
          child: Container(
            height: 100,
            width: 100,
            color: Colors.red,
          ),
        ),
        Container(
          height: 100,
          width: 100,
          child: HtmlWidget(),
        ),
        if (!removed)
          Container(
            height: 100,
            width: 100,
            color: Colors.green,
          ),
      ],
    );
  }
}

class HtmlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'ScrollableElement');
  }
}

```



What would be your suggestions in terms of tests?

**Comment by muhleder** [comment]
Some CI tests are failing, but they're also failing for me locally when I run a build without the changes from this PR in so I'm guessing maybe not caused by it.

**Comment by muhleder** [comment]
@yjbanov I've made a few extra changes to handle more cases here. Should be ready for initial review.

As discussed previously, children are walked and built, any children due for removal have their DOM nodes discarded, and then the DOM nodes are moved into the correct position. 

The only difference now is that children which were marked as pendingRetention due to having an engine layer https://github.com/flutter/flutter/blob/9a99403ad262cc4ead21e01d130d77f3a49f3de4/packages/flutter/lib/src/rendering/layer.dart#L439 (which I am assuming the HtmlELementView is an example of, are moved after all other nodes. 

This makes it more likely that the DOM nodes containing an HtmlELementView will not need to be moved and lose state. In fact I think that they would only need to be moved if there were multiple HtmlElementView siblings and their order had changed.

**Comment by muhleder** [comment]
Some more stuff I noticed which is probably worth mentioning, I've got a feeling this is why the web engine performs so many repaints.

I'm still seeing unnecessary movement of DOM nodes in some cases, specifically where there are multiple siblings of the same surface type. This is because _matchChildren https://github.com/flutter/engine/blob/33d2367950154e7f8daf9ce9992a450016289a5f/lib/web_ui/lib/src/engine/surface/surface.dart#L985 doesn't work properly in matching children of the same surface type, which is because as far as I can tell the engine does not receive enough data from the framework to differentiate between children of the same type at the same level of the element tree, for instance it doesn't look as if widget keys end up in the RenderView which the engine composites the scene from?

_matchChildren sorts children for matching from the old surface to the new surface by _PersistedSurfaceMatch.matchQuality https://github.com/flutter/engine/blob/33d2367950154e7f8daf9ce9992a450016289a5f/lib/web_ui/lib/src/engine/surface/surface.dart#L1131, which is calculated from PersistedSurface.matchForUpdate. For example in PersistedStandardPicture.matchForUpdate always returns 1.0 when DomCanvas is used https://github.com/flutter/engine/blob/33d2367950154e7f8daf9ce9992a450016289a5f/lib/web_ui/lib/src/engine/surface/picture.dart#L177

Which leads to the following behaviour in the [Container<ONE>, Container<HtmlWidget>, Container<THREE>] app above

**1. Initial DOM State**

div(ONE)
div(HtmlWidget)
div(THREE)

**2. Click is registered and a new surface is generated with just the first two containers.**

**3. Children are walked and built.**

**4. At this point due to _matchChildren not working the state of the DOM is** 

div(ONE)
div(HtmlWidget)
div(ONE)

**5. Children are discarded, as luck would have it in this case the wrong DOM node is discarded leaving a state of**

div(HtmlWidget)
div(ONE)

**7. The DOM nodes are then moved into their correct positions, which now requires moving a DOM node and a repaint.**

**Comment by muhleder** [comment]
Nope, still more to do here. Looks like maybe child.isPendingRetention maybe doesn't pick up HtmlElementViews which are some levels deeper.

**Comment by yjbanov** [comment]
> I'm still seeing unnecessary movement of DOM nodes in some cases, specifically where there are multiple siblings of the same surface type. This is because _matchChildren doesn't work properly in matching children of the same surface type, which is because as far as I can tell the engine does not receive enough data from the framework to differentiate between children of the same type at the same level of the element tree, for instance it doesn't look as if widget keys end up in the RenderView which the engine composites the scene from?

The framework communicates "the layer is updated" by passing a non-null `oldLayer`. You see in the `_updateManyToMany` a special code path for the `newChild.oldLayer != null` case, as well as `newChild.isPendingRetention`. When we have that we ignore `matches` entirely (there's won't be any matches anyway since we only match children that are `newChild.isCreated` to those that are `oldChild.isActive`).

IOW, if we are trying to match children we already know that the framework did not give us enough information. We resort to fuzzy matching based on picture contents and node types. We could boost the `matchForUpdate` score for children that share the same platform view. This way even if child types are the same, matching on platform view would take precedence.

Having said that, I will likely start working on a permanent solution for platform views soon. So relying on render tree stability as a solution for platform views could be short-lived. I still like that this change makes DOM updates more efficient though, so I think we should still do it.

**Comment by muhleder** [comment]
@yjbanov Sorry for the delay, I was ill last week. So, of the three alternate approaches I've tried so far, the first https://github.com/muhleder/engine/commit/f723f9f2dca0e1145c11eb535fde0d7569ae52c5 still seems like the best to me.

Second approach just doesn't work because of the _matchChildren issue, and the third approach of trying to detect an engine layer by looking at layer.isPendingRetention works in simple cases but fails for me when I use it in an actual app. That approach might work with a bit more digging but it feels a little fragile.

Also, the first approach makes the least changes to the current code paths, so should have less chance of unintended side effects.

> We could boost the matchForUpdate score for children that share the same platform view.

FWIW I don't think this would help as children with a platform view seem to come in as layer.isPendingRetention so don't participate in _matchChildren.

**Comment by yjbanov** [comment]
> @yjbanov Sorry for the delay, I was ill last week. So, of the three alternate approaches I've tried so far, the first [muhleder@f723f9f](https://github.com/muhleder/engine/commit/f723f9f2dca0e1145c11eb535fde0d7569ae52c5) still seems like the best to me.

Good to have you back! Ok, let's revert to your initial implementation and go from there. I think I saw a couple of mico-optimization opportunities, but other than that it should be fine.

**Comment by muhleder** [comment]
@yjbanov Done, back to the first implementation now.

**Comment by yjbanov** [comment]
Let me see if I can restart them. Looks like infrastructure failure and not related to code changes

**Comment by yjbanov** [comment]
@muhleder I'd love to know your opinion on https://github.com/flutter/engine/pull/18648. As I was investigating https://github.com/flutter/flutter/issues/55922 it led me to the `_updateManyToMany` method. Turns out when we scroll backwards we unnecessarily move DOM elements because the current implementation always scans the child list from top to bottom. If anything changes at the top of the list, the heuristic falls over. So I implemented an algorithm that looks for the longest sub-sequence of children that haven't moved relative to each other and keep them stationary. That gives me the absolute minimum number of children that need to move. In my testing, this improved backwards scrolling by 15%-25%.

Separately, in https://github.com/flutter/flutter/pull/58140, I added a benchmark that measures the performance of backwards scrolling.

I think we should run all the benchmarks we have and see which approach fixes what, or whether we need a 3rd approach :)

**Comment by yjbanov** [comment]
BTW, to follow-up about the bot failures. I restarted them but they still show as failing. Maybe if you rebase the PR on top of the latest master will fix it? I'm not sure what's going on.

**Comment by muhleder** [comment]
@yjbanov https://github.com/flutter/engine/pull/18648 looks pretty good to me, it looks like it would fix quite a few of the typical cases where HtmlElementView is losing state - specifically the ones with Scaffold which I think is the main pain point for a lot of people. 

It still leaves one case in my app broken, but using a RepaintBoundary I can fix that too.

I can make a breaking case that you're probably aware of. If sibling widgets [A, B, C, D] goes to [A, C, D] in the next frame then it looks like C is moved in the DOM as it's index goes from 2 to 1. (I think D doesn't get moved as it's the final element?)

**Comment by yjbanov** [comment]
> @yjbanov #18648 looks pretty good to me, it looks like it would fix quite a few of the typical cases where HtmlElementView is losing state - specifically the ones with Scaffold which I think is the main pain point for a lot of people.
> 
> It still leaves one case in my app broken, but using a RepaintBoundary I can fix that too.
> 
> I can make a breaking case that you're probably aware of. If sibling widgets [A, B, C, D] goes to [A, C, D] in the next frame then it looks like C is moved in the DOM as it's index goes from 2 to 1. (I think D doesn't get moved as it's the final element?)

Good point. I think it should work because I'm only looking at old indices, not new, this example should result in [0, 1, 2, 3] => [0, 2, 3], which and the longest increasing sub-sequence using the new indices will be [0, 1, 2], i.e. no moves. At least, this is how I _want_ it work, but I'll write a test making sure that it does :)

**Comment by halloway** [comment]
Is there any update on this matter or timelines?

**Comment by muhleder** [comment]
@halloway This PR is superseded by https://github.com/flutter/engine/pull/18648, which I notice has just been merged. https://github.com/flutter/engine/pull/18648 fixed most of the cases I was looking at straight away, and the use of RepaintBoundary on HtmlElementView siblings fixed the one remaining case that I was seeing in my app.

**Comment by muhleder** [comment]
Closing as issues should be fixed and this PR no longer applies to the current codebase.

**Comment by griotdonation** [comment]
> document.body.addEventListener('DOMNodeRemoved', (e) => {
>         if (e.target.innerHTML && e.target.innerHTML.search(/flt-platform-view/)) {
>             console.log('platform view removed');
>         }
>     }
> );

thanks for this amazing fix regarding iFrames. Exactly where do put this in my code?

**Comment by tihhmachado** [comment]
Hello Everyone! 

I did not understand the solution, I am relatively new to web flutter and I am facing the same problem. How do I apply this solution?

**Comment by ditman** [comment]
I've been working on a more permanent fix for the issue of iframes losing state. Please check it out here: https://github.com/flutter/flutter/issues/80524

**Pull request closed without merging**
