### PR TITLE
Allow `Path` and its siblings to be serialized

### PR DESCRIPTION
**Pull request by fzyzcjy**
As usual, I will add tests if you think this looks roughly OK :)

This is a part of https://github.com/flutter/flutter/issues/129098

### Why

In order to record the current frame, the `Path` has to be dumped and restored.

### Will it work for Impeller?

Yes. Currently it uses the `SkPath`'s built-in serialization. However, in the future, if we use `impeller::geometry::Path`, we can still write a simple serialize/deserialize function for it, since the impeller `Path` is nothing but a struct with the following fields:

```c++
class Path {
  FillType fill_ = FillType::kNonZero;
  Convexity convexity_ = Convexity::kUnknown;
  std::vector<ComponentIndexPair> components_;
  std::vector<LinearPathComponent> linears_;
  std::vector<QuadraticPathComponent> quads_;
  std::vector<CubicPathComponent> cubics_;
  std::vector<ContourComponent> contours_;
...
}
```

And all those fields IMHO looks well serializable.

I can make a PR when `SkPath` is removed and impeller Path is used instead, just ping me then :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
We must not expose a specific serialization structure for path, especially an entirely undocumented one. 

See https://api.skia.org/classSkPath.html#ab34720f80c02d5854cc6b09675b5d907

> the format used for [SkPath](https://api.skia.org/classSkPath.html) in memory is not guaranteed.

**Comment by fzyzcjy** [comment]
@jonahwilliams Thanks for the reply. However, IMHO it is reasonable, because it should be treated as a blackbox. In other words, users never understand what are those bytes, and the only usage of the bytes is to be passed to `Path.deserialize()`. Just like the skia doc says:

> Use only be used in concert with readFromMemory()

Thinking in another view: If the new API (Path.serialize/Path.deserialize) is unreasonable, why does Skia expose writeToMemory/readFromMemory?

**Comment by dnfield** [comment]
See prior discussion at https://github.com/flutter/engine/pull/5632

**Comment by dnfield** [comment]
High level summary: exposing internals of these intentionally opaque objects will make it more difficult to optimize them. Clients will break when we find better ways e.g. to decompose arcs to cubics or cubics to quads or lines and when we do that. We don't want that.

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by fzyzcjy** [comment]
Ah I see even you (hey you guys are definitely expert Flutter engineers in Google!) got rejected for this (similar) proposal as me...

**Pull request closed without merging**
