### PR TITLE
[Impeller] Reland: Compute UVs in vertex stage.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Compute texture UVs in the vertex stage. Reland of https://github.com/flutter/engine/pull/52106 which was reverted to investigate golden failures during the x64 to arm64 mac switch.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Goldens have revealed that the vertices changes were incorrect

**Comment by jonahwilliams** [comment]
Reverted the changes to vertices_contents, expecting a clean bill of golden health.

**Review by chinmaygarde — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Ahh OK - one more problem. We can optimize vertices contents into regular contents, will need to untangle that too.

**Comment by jonahwilliams** [comment]
Ahh, but the vertices UV assumes that is handled...

Looks like I'm going to have to pull forward some refactors I had planned on doing later. Basically we need to separate out drawVertices and drawAtlas since they work differently from our regular drawing (or they should).

**Comment by jonahwilliams** [comment]
There are still some golden diffs but these are now rendering correctly instead of incorrectly!

**Pull request merged**
