### PR TITLE
[Impeller] remove unused includes.

### PR DESCRIPTION
**Pull request by jonahwilliams**
mostly removing unused fml/macros, but a few others that clangd surfaced. This compiled locally,hope it works on CI!

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Review by matanlurey — APPROVED** [review]
Neat, gets us closer to IWYU.

You might want to add `test: all` and push a dummy commit to run the full clangd on pre-sub.

**Review by chinmaygarde — APPROVED** [review]

**Review by gaaclarke — COMMENTED** [review]
Are these removed because they aren't used or because they are brought in transitively?    The former is good, the latter would be a violation of iwuy.  The `iwuy` tool can be used to identify these as well.

**Comment by jonahwilliams** [comment]
fml/macros are unused everywhere. For everything else, if clangd highlighted it as unused I removed it, unless I knew it was special like build config.h or other macros

> The former is good, the latter would be a violation of iwyu. The iwyu tool can be used to identify these as well.

This isn't an attempt to guess what IWYU would do. We can't use IWYU anyway, unless we fix all of our forward declares.

**Comment by jonahwilliams** [comment]
In general though, clangd seems to have some similar logic? If you are including a header to get to a transitive header, it will tell you the first header is unused. Then when you remove it and get an include error, the suggested include is often the non-transitive header

**Comment by gaaclarke** [comment]
> This isn't an attempt to guess what IWYU would do. We can't use IWYU anyway, unless we fix all of our forward declares.

FWIW I've had success using it locally when splitting up the aiks tests.  It may not be easy to setup on ci but for local cleanups it was helpful.

**Comment by matanlurey** [comment]
Just a clarification:

> @jonahwilliams: We can't use IWYU anyway, unless we fix all of our forward declares.

We can, https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-keep.

**Comment by jonahwilliams** [comment]
oh TIL!

**Pull request merged**
