### PR TITLE
fix the bounds of nested save layers with a mix of clips and transforms

### PR DESCRIPTION
**Pull request by flar**
Cherry pick of https://github.com/flutter/engine/pull/31437 to the flutter-2.8-candidate.16 base.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/31440

**Comment by flar** [comment]
One of the failures was fixed by a re-run, but the MHE continues to fail getting some sort of stream path.

**Comment by godofredoc** [comment]
> One of the failures was fixed by a re-run, but the MHE continues to fail getting some sort of stream path.

Seems like we need an additional cherry-pick that includes `sky/tools/create_macos_framework.py`

**Comment by flar** [comment]
> > > One of the failures was fixed by a re-run, but the MHE continues to fail getting some sort of stream path.
> > 
> > 
> > Seems like we need an additional cherry-pick that includes `sky/tools/create_macos_framework.py`
> 
> Do the 2.8 recipe versions refer to that script? I'm confused, I think. Why would this cherry-pick have triggered the need for `sky/tools/create_macos_framework.py` when previous Engine cherry-picks didn't?

I agree. I don't see how my changes should have induced any dependency changes.

**Comment by godofredoc** [comment]
> n't see how my changes should have induced any dependency changes.

I think I found the issue, sending a PR in the recipes branch to fix it.

**Comment by flar** [comment]
Do I need to rebase, or will the rerun pick up the new scripts?

**Comment by zanderso** [comment]
I believe the re-run will pick up the new recipe.

**Comment by flar** [comment]
I'm not sure when the re-run was started, but it failed again with the same error.

**Comment by zanderso** [comment]
Whoops. The last re-run started at 3:30pm, but the recipe change didn't actually land until 3:40pm.

**Comment by godofredoc** [comment]
> Whoops. The last re-run started at 3:30pm, but the recipe change didn't actually land until 3:40pm.

Running on half capacity has increased mac latency to ~1H

**Comment by flar** [comment]
The run started at 5:22 also failed.

**Comment by zanderso** [comment]
> The run started at 5:22 also failed.

It appears that the presubmit check is not using the branched recipe. /cc @godofredoc

**Comment by godofredoc** [comment]
> > The run started at 5:22 also failed.
> 
> It appears that the presubmit check is not using the branched recipe. /cc @godofredoc

Yeah this is actually an error in the retry logic. I'll open a bug to track.

**Comment by itsjustkevin** [comment]
@zanderso am I missing a reason why we are trying to do a PR directly to the release branch?  This is not the typical flow, please let me know if I am missing something.

**Comment by zanderso** [comment]
The PR against master does not merge cleanly against the branch, so @flar prepared this PR against the branch to try to make the cherry-pick easier.

**Pull request merged**
