### PR TITLE
Add Android Emulator dependencies as "test_dependencies" to Android tests

### PR DESCRIPTION
**Pull request by ricardoamador**
# Description

Emulator dependencies were not getting picked up correctly when running the Recipes through engine_v2. The fix was to allow the context it runs through to be passed the version via the flutter_deps module. That change can be found here: https://flutter-review.googlesource.com/c/recipes/+/51869.

Do not land until above cl has been merged.

## Related Issue
*List which issues are fixed by this PR. You must list at least one issue.*
Fixes https://github.com/flutter/flutter/issues/137350

## Validation
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ricardoamador** [comment]
@godofredoc I looked at the docs and this is what I would assume @gmackall needs to add in order to specify the version of the emulator. This change (here)[https://flutter-review.googlesource.com/c/recipes/+/51869] allows this to pick up the required version.

**Review by gmackall — COMMENTED** [review]
Thanks for this PR and the linked fix! This LGTM, but can we try running it once in presubmit by [changing `presubmit` to true here](https://github.com/flutter/engine/blob/main/.ci.yaml#L89) temporarily (given that this PR not only adds the configuration, but also actually changes the version to 34).

**Comment by ricardoamador** [comment]
@gmackall Yeah no problem. Here is a successful run on prod: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/ricardoamador_google.com/aef0a5e0460f39de6935d45dd12b797fba9b2d15d29d95662d34d9e466c39584/+/build.proto.

I'll run some tests on try and update the PR to run in presubmit. Do you want it to run in presubmit always or just for a test?

**Review by gmackall — APPROVED** [review]
> @gmackall Yeah no problem. Here is a successful run on prod: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/ricardoamador_google.com/aef0a5e0460f39de6935d45dd12b797fba9b2d15d29d95662d34d9e466c39584/+/build.proto.
> 
> I'll run some tests on try and update the PR to run in presubmit. Do you want it to run in presubmit always or just for a test?

Oh nevermind, I just wanted to see one run succeed to be sure it wouldn't end up just failing in postsubmit. If you've already tested a successful run then this LGTM!

Separately, I know this test used to run in presubmit and was changed to only postsubmit ~4 months ago, and I want to look into why that is/see if it should be changed back to running in presubmit. But thats a different issue!

**Comment by ricardoamador** [comment]
Here you go: https://chromium-swarm.appspot.com/task?id=658bf0608be42710 in the try pool. 

Also note that the recipe change will need to land first then I can merge this and you should be good to go.

**Review by keyonghan — APPROVED** [review]
LGTM

**Pull request merged**
