### PR TITLE
[Impeller] Add docs to enable Vulkan validation layers on Android

### PR DESCRIPTION
**Pull request by iskakaushik**

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

We should add support in the tool for this if we can. @christopherfujino @jonahwilliams WDYT?

**Comment by jonahwilliams** [comment]
Why would end users need to know about validation layers?

**Comment by jonahwilliams** [comment]
or I guess not end-users, but flutter developers?

**Comment by iskakaushik** [comment]
@jonahwilliams yeah, flutter developers and also potentially when we want bug-reports to be submitted it might be useful for us to have additional context.

**Pull request merged**
