### PR TITLE
Update switches to use StringView.

### PR DESCRIPTION
**Pull request by pylaligand**
See https://fuchsia-review.googlesource.com/#/c/31931/.

### CODE REVIEW

**Comment by Hixie** [comment]
This broke Mac and Linux.

**Comment by pylaligand** [comment]
Not cool. Where can I see the breakage?

**Comment by pylaligand** [comment]
https://uberchromegw.corp.google.com/i/client.dart.internal/builders/flutter-engine-linux/builds/4997/steps/build%20host_debug_unopt/logs/stdio

I see what the problem is: I need to update the version of the FTL Flutter uses.

**Comment by pylaligand** [comment]
I don't quite understand why Travis did not have a problem with this PR though.

**Comment by Hixie** [comment]
Travis doesn't build the engine.

**Pull request merged**
