### PR TITLE
Windows: Add SystemSound support

### PR DESCRIPTION
**Pull request by moko256**
This PR adds `SystemSound.play` support.

On win32, it calls `MessageBeep`.

On winuwp, it is not implemented because Windows App Cert Kit warns the usage of `MessageBeep` and winrt seems not to have its equivalent API.
I tried `ElementSoundPlayer`, but it seems to work on xbox and can be called only on xaml's thread.

This PR will fix flutter/flutter#62143.

No changes in `flutter/tests`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
This looks great! Thank you for your contribution!

LGTM stamp from a Japanese personal seal

**Comment by dkwingsmt** [comment]
The general code is fine. But I have questions about the design, because it is only able to play `MB_OK`, while Win32 supports [10 different sounds](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebeep).

I would say to have a parameter of an enum to support all of them, but then comes portability for other platforms.

Shall we name it "Win32Beep.play", and support a parameter that is the literal value of the beep kind?

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
@dkwingsmt I was wondering the same thing. We do already use the `SystemSound.alert` value on other platforms (e.g. Android). This PR is consistent with how we model channel values in other parts of the embedders, so I think that sort of refactor is probably beyond the scope of this change.

I do think it's worth some thought how we might do this -- especially as I just spent a couple days on testing for similar code with regards to semantics to resolve https://github.com/flutter/flutter/issues/101217.

I think we can investigate that separately from this change though.

**Comment by dkwingsmt** [comment]
Yeah I didn't realize it's implementing a feature that already exists in the Framework.

**Pull request merged**
