### PR TITLE
115574 android selection haptics feedback should respect android settings

### PR DESCRIPTION
**Pull request by reidbaker**
Expose haptic feedback setting from android to the platform channel. 

Part of a multi pr fix for [Android] selection haptics feedback should respect android settings #115574

Value defaults to true because the setting indicates the user has explicitly turned off haptic feedback and because in practice the use of the value is an indication for if we should call for haptics to be engaged. On android api 30+ the setting is automatically applied by the system so defaulting to send is the right action. 

A follow up pr will be made to use this value in text selection as indicated in the linked issue. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
It looks like there are some unrelated formatting changes in this PR. I suspect that these might be the result of using the Dart formatter. In the Flutter repos, we don't use the Dart formatter, but rather do hand formatting following the guide in https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting.

**Comment by reidbaker** [comment]
> 

Thank you I will walk through and remove any unrelated changes. Part of my problem is that I accidentally turned on auto formatting on save.

**Comment by reidbaker** [comment]
https://github.com/flutter/flutter/issues/115574

**Comment by Hixie** [comment]
Closing, @reidbaker is not going to get to this in the near future.

**Pull request closed without merging**
