### PR TITLE
Merge the engine and buildroot repos.

### PR DESCRIPTION
**Pull request by chinmaygarde**
The reasons for the original split and this merge are outlined in the issue this patch set purports to fix [https://github.com/flutter/flutter/issues/67373](https://github.com/flutter/flutter/issues/67373).

After spending an inordinate amount of time this morning patching and cross referencing buildroot hashes in DEPS on what was supposed to be a drive-by commit (https://github.com/flutter/engine/pull/27354), I decided to kill the buildroot for good.

## Steps
To preserve history, the contents of this patch aren't squashed. The steps taken were:

* `git mv` all contents at the base of the engine repo into the `flutter` subdirectory.
* Using a `git subtree import` to import the buildroot at a directory named `buildoot`. The provenance of all patches in the buildroot is maintained. A separate directory is needed because subtrees cannot be imported at the source root.
* `git mv` all contents from the `buildroot` directory to the base of the repository.
* Move the `flutter/DEPS` to the base of the repository. This is where the autorollers expect the file to reside.
* Move back sundry Github and CI files that need to be at a certain known location in the repo. These were moved in step one into the subdirectory.
* Run tests locally.

To preserve history, this patch must not be squashed and merge commit used instead. @Hixie might have permission to do this. Otherwise, squashing changes will reauthor the imported buildroot patches under my name. We lost history during the split and I am ambivalent about preserving it during the merge. But it may potentially be useful.

## FAQ

Some common questions that engine developers may have:

* **What will happen to the buildroot repository?**
    * It will be archived and made read-only. The buildroot entry in DEPS is gone and there is no more need to update the buildroot and cross reference the patch in DEPS manually.
* **After an engine checkout, how will the location of source files in my checkout change?**
    * They won't.
* **How will this patch affect my current checkouts?**
    * The `.gclient` file you initially authored to checkout the engine has an entry named `"name": "src/flutter",`. This must be changed to `"name": "flutter/src"`, and a `gclient sync -D` must be performed. This is a one time change.
    * The one time change is necessary because preserving the structure of the .gclient file would have meant breaking all DEPS autorollers. Those bots are more intractable than us humans.
* **Will this break existing autorollers?**
    * No.
* **Will this break existing builders?**
    * Possibly. These probably stamp the `.gclient` that now has the outdated path. This patch must pass all CI checks to land.
    * Cirrus gclient checkouts should not break because Cirrus stamps the `.gclient` using the contents of `.cirrus.yml` which is in this repo and has been patched.
* **Will this break existing scripts that have hardcoded paths?**
    * No. Existing scripts assume the engine resides within the buildroot. The final directory structure remains identical.
* **Will I be able to use `git blame` to follow updates to existing source files across the buildroot and engine?**
    * Yes. But, the location of files in the engine has changed to be one level up. This was done via a rename. Git tracks content and not file names. Use the `--follow` option to commands such as `git log` to track changes across renames. Files in the buildroot are in their original locations.

Fixes [https://github.com/flutter/flutter/issues/67373](https://github.com/flutter/flutter/issues/67373).

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Ok, as expected the LUCI recipe is mad that the DEPS file location in this repo changed. I'll see if the presubmits can be pointed to a patched recipe.

The conflicts are inevitable as commits landing after this patch was submitted for review will not be auto-mergeable. But those can be resolved manually.

The CLA bot is mad that there are multiple authors. But that is kind of the point of preserving history in buildroot files.

**Comment by chinmaygarde** [comment]
Looking into patching the LUCI recipe.

**Comment by chinmaygarde** [comment]
The recipe updates are straightforward (I am verifying them using LED runs). Per @zanderso, there is no way to land recipe updates in lockstep with the engine. His suggestion is to land the recipe change after @christopherfujino forks for the beta. The tree will effectively be closed till this patch lands. At this point, we should also figure out one of has the permissions to bypass the squash requirement on GitHub so we aren't blocked. The steps to incorporate any patches from now till that point are easy to incorporate so the conflicts shouldn't be an issue. Does this checklist sound good?

**Comment by zanderso** [comment]
plan sgtm. seeing the conflict on `ci/licenses_golden/licenses_third_party`, I'm wondering if any updates to the license checker script are needed. I'm guessing not since the layout is the same, right?

**Comment by Hixie** [comment]
This is great.

I'll enable merge commits briefly, let me know when you no longer need that enabled.

Please, once this lands, audit all the wiki pages for references to the buildroot and make sure all the instructions are up to date.

**Comment by Hixie** [comment]
Actually looks like we already allow rebase merging; that should be sufficient, right?

**Comment by chinmaygarde** [comment]
> I'm wondering if any updates to the license checker script are needed.

There are no updates necessary since the directory structure is the same. I believe any updates made to the tree from here on in will show up as conflicts because the files have moved. I'll follow the steps outlined in the original comment again before committing. The tree will be blocked then anyway.

> Please, once this lands, audit all the wiki pages for references to the buildroot and make sure all the instructions are up to date.

Roger. We were discussing adding a bespoke fetch configuration in depot_tools for the engine. After https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3026128 lands, developers (and the recipes) should be be able to just say `fetch flutter` and have their environment ready instead of having to mess with .gclient files. I'll update the wiki.

> Actually looks like we already allow rebase merging; that should be sufficient, right?

You are correct. For some reason, I thought only squashed commits were allowed. I don't think I have ever used anything else. Rebased commits should be fine as well.

Since the plan sounds fine, I'll submit the recipe patch for review, verify with LED runs and commit both once the beta branch cut is done (perhaps over the weekend to minimize disruption).

**Comment by chinmaygarde** [comment]
@christopherfujino says go.

**Comment by chinmaygarde** [comment]
I am going to table this till I have spare cycles to work on landing and following up on this.

**Comment by Hixie** [comment]
@chinmaygarde I'm going to close this for now, but I have great hopes that we will one day do this. :-)

**Pull request closed without merging**
