### PR TITLE
Have PictureRecorder keep a reference to the associated Canvas object.

### PR DESCRIPTION
**Pull request by jacob314**
This fixes:
https://github.com/flutter/flutter/issues/29108

If there is a better way to make the Dart object references stay alive I'm fine with that as well.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Can you reword the commit message to describe the issue you addressed please. Thanks.

**Comment by jacob314** [comment]
> Upon further investigation, I am not sure this is required or indeed does anything. As soon as the canvas is created from the picture recorder, we make the recorder reference the same on the native side
> 
> [engine/lib/ui/painting/canvas.cc](https://github.com/flutter/engine/blob/fa435385b6b9f80080997dd38ad66bbe4bb0a152/lib/ui/painting/canvas.cc#L84)
> 
> Line 84 in [fa43538](/flutter/engine/commit/fa435385b6b9f80080997dd38ad66bbe4bb0a152)
> 
>  recorder->set_canvas(canvas); 
> . Should this not prevent the object from being collected.

I haven't worked much on Dart/C++ binding code for 5 years so I may be out of date but here is my expectation of what is happening:

The issue is not that the C++ object is being deleted too soon. The issue is that the associated Dart object is GCed but the C++ object is still alive (kept alive by the ref counting set_canvas call you mentioned). The problem is when endRecording is called, a call is made that references the Dart handle vs the C++ Canvas object and this is the one that leads to the failure in Dart_SetNativeInstanceField call.

Looking at the base class these wrappers use:
https://fuchsia.googlesource.com/tonic/+/2de0ba78507e764f908b195885f53592048b7c45/dart_wrappable.cc#33
it appears that the dart handle is a weak handle which is good as it avoids C++ objects keeping Dart objects alive and the associated memory leaks. The downside is the C++ objects can't keep dart objects alive thus we hit bugs like this if this if we assume that Dart objects are still alive in cases when they have been GCCed.

Does this make sense?
I've run the test that flaked 1 out of 50 times, 500 times without a flake with this fix. It is always possible I am missing something and it is now just leaking memory covering up some other underlying bug so do check my logic.

An alternate fix would be if there is a way to check whether a dart weak persistent handle has been GCed. In this case, it would also be sufficient to have void DartWrappable::ClearDartWrapper() 
just be a no-op if the Dart wrapper is already GCed.

**Comment by jason-simmons** [comment]
Perhaps Tonic's `DartWrappable::ClearDartWrapper` should check if `dart_wrapper_` is null?

If the Dart peer object was GCed, then the `DartWrappable::FinalizeDartWrapper` callback should be invoked.  `FinalizeDartWrapper` will null out the `dart_wrapper_` Dart weak reference and release the `fml::RefPtr` reference count that is held on behalf of the Dart peer.

If `ClearDartWrapper` is later called on the same object and the `dart_wrapper_` peer no longer exists, then `ClearDartWrapper` should do nothing.

**Comment by cbracken** [comment]
@jacob314 any luck with the investigation on the tonic side? Should we hold this PR open?

**Comment by jacob314** [comment]
Unfortunately something more subtle is going on here. I applied the fix to tonic and that fixes the issue some of the time but does not fix it all the time while this CL fixes the issue 100% of the time. I'm at a loss at why this is the case. It seems like we are sometimes getting a deleted C++ object or something similar. Perhaps I'm missing something about how reference counting is being done in tonic that could cause this. For example, is the VM ever deleting references on a different thread?

**Comment by cbracken** [comment]
Can you verify whether this is still a problem at `HEAD`. If so, we should figure out the root cause and apply a patch that fixes that. Closing this PR for now; once we've got a root cause, let's discuss in a new PR.

**Pull request closed without merging**
