### PR TITLE
[android] Use existing FlutterJNI in FlutterInjector by default

### PR DESCRIPTION
**Pull request by 0xZOne**
Fixes flutter/flutter#92479

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
What is this trying to accomplish? What are the advantages?

**Review by ColdPaleLight — CHANGES_REQUESTED** [review]
I don't know whether we should make `FlutterJNI` a singleton or let multiple FlutterEngines share a `FlutterJNI` instance. I guess before that, we need to make sure that `FlutterJNI` is stateless. However, the `FlutterJNI` holds `nativeShellHolderId` which represents a native shell instance currently.

https://github.com/flutter/engine/blob/df686d2638b35ce6ea771586b374fae800d0624c/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L271

**Comment by 0xZOne** [comment]
> What is this trying to accomplish? What are the advantages?

Here I want to avoid unnecessarily multiple instances of FlutterJNI. If the user does not provide FlutterJNI, we should use the existing one in *FlutterInjector* instead of re-creating, otherwise, FlutterInjector will lose its meaning.

**Comment by 0xZOne** [comment]
> I don't know whether we should make `FlutterJNI` a singleton or let multiple FlutterEngines share a `FlutterJNI` instance. I guess before that, we need to make sure that `FlutterJNI` is stateless. However, the `FlutterJNI` holds `nativeShellHolderId` which represents a native shell instance currently.
> 
> https://github.com/flutter/engine/blob/df686d2638b35ce6ea771586b374fae800d0624c/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L271

Thanks for replying. 

Maybe you are right, but this PR just wants to fix the [issue](https://github.com/flutter/flutter/issues/92479), not consider FlutterJNI refactoring.

**Comment by 0xZOne** [comment]
> > I don't know whether we should make `FlutterJNI` a singleton or let multiple FlutterEngines share a `FlutterJNI` instance. I guess before that, we need to make sure that `FlutterJNI` is stateless. However, the `FlutterJNI` holds `nativeShellHolderId` which represents a native shell instance currently.
> > https://github.com/flutter/engine/blob/df686d2638b35ce6ea771586b374fae800d0624c/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L271
> 
> Thanks for replying.
> 
> Maybe you are right, but this PR just wants to fix the [issue](https://github.com/flutter/flutter/issues/92479), not consider FlutterJNI refactoring.

Yes, you are right. I forget multiple engine cases.

**Comment by dnfield** [comment]
I don't think this PR is correct, for reasons noted above.

An application that wants to use a single instance of FlutterJNI (perhaps because it knows it will only ever use one engine?) can override the provider in FlutterInjector already. I'm going to close this PR.

I think there is probably still some work worth doing to avoid having any public static members on `FlutterJNI`, but that's separate from this.


I'm going to close this for now - if we're missing something let's discuss further on Discord.

**Pull request closed without merging**
