### PR TITLE
Remove support for the —enable-checked-mode flag from the engine.

### PR DESCRIPTION
**Pull request by chinmaygarde**
See discussion in https://github.com/flutter/engine/pull/2986

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @jason-simmons @abarth @eseidelGoogle

**Comment by abarth** [comment]
LGTM

**Comment by jason-simmons** [comment]
LGTM

This will also have to be removed from SkyActivity and flutter_tools

**Comment by chinmaygarde** [comment]
> This will also have to be removed from SkyActivity.

Oh, I didn't realize there was flag specific code in the platform specific shells. Will fix.

Was planning on removing the flutter_tools stuff when I did the roll next.

**Comment by chinmaygarde** [comment]
Removed the flag from SkyActivity.java in https://github.com/flutter/engine/pull/2988

**Pull request merged**
