### PR TITLE
Moves from vector_math to vector_math_64

### PR DESCRIPTION
**Pull request by vlidholt**
- Moves from vector_math to vector_math_64
- Adds support for Float64List in Dart bindings

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

Please hold off a bit before landing this patch because its going to break Travis until we push another binary and there's another issue in the tree we probably want to resolve before pushing a new binary.

**Comment by Hixie** [comment]
viktor, did you by any chance measure what the perf impact of this is? (I'm assuming an improvement, but it's always good to see that in the data...)

**Comment by vlidholt** [comment]
I did run a test and there seem to be a significant difference (20% faster in my test)

**Comment by vlidholt** [comment]
Actually, maybe more as the test does more than just matrix multiplications.

**Comment by Hixie** [comment]
nice

**Comment by abarth** [comment]
Rebased (and will land) this patch as #1444

**Pull request closed without merging**
