### PR TITLE
Move pictures from deleted canvases to second-to-last canvas instead of last.

### PR DESCRIPTION
**Pull request by harryterkelsen**
Previously, when the number of display canvases exceeded the maximum amount, we would augment the rendering to reduce the number of canvases to the maximum amount, and move the pictures from the deleted canvases to the last canvas. However, this would cause ugly rendering in cases where pictures would render on top of the platform views they were supposed to be underneath.

This is especially noticeable when reproducing this bug: https://github.com/flutter/flutter/issues/144854

This changes things slightly so that the pictures are moved to the second-to-last remaining canvas, so that platform views always render over the pictures they are supposed to.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jezell** [comment]
@harryterkelsen can this result in the opposite effect where too much is put on top of the platform view? and won't it make the platform view no longer able to receive events?

A while back I experimented with a PR that cut holes out of the canvas with a clear operation when their layer was rendered instead of paint operations and then placed the views behind the canvas. Maybe that could be a useful strategy here so that whatever is on top of that last one that should be behind gets erased and you don't get reverse artifacts.

On that subject,If now it is going to be possible to end up with views below the canvas (which I always thought was probably the better default as it has zero problems with overlay groups at the cost of disabling a few things that aren't usually used with overlay groups), it could maybe be useful to support that general concept for HtmlElementView to support this to allow users to control what happens with the platform views. Right now isVisible is a little confusing and misleading because it doesn't actually make anything invisible, it just puts it always on top of the canvas. It would probably make more sense to have:

```dart
enum HtmlElementViewPosition {
   above,
   below,
   alwaysOnTop /// replacement for isVisible, which is a lie
}

HtmlElementView.fromTagName(String tagName, position = HtmlElementViewPosition.auto);
```

And then you wouldn't burn platform layers by default, and you could use one of the other options when you need the element to be clickable

**Comment by jezell** [comment]
@harryterkelsen I get what it's supposed to be, I also get what it actually is :). While it may supposed to be something you use when stuff is invisible, it doesn't make anything invisible, so it's confusing. If it was alwaysOnTop, it would say exactly what it actually does and would also be more clear that you can use this to avoid creating platform layers. This came up for us recently using the HtmlElementView to embed iframes that we want invisible because they are only used for cross domain communication. Because it says isVisible, everyone expected the iframes wouldn't be displayed, but of course that's not what it does, it just renders them on top. 

When this change gets merged, the engine will have three places it can put a view relative to the other canvases: 

on top
between
beneath

While all three are valid places you might want to put them, one of them is misnamed as isInvisible, and one of them randomly happens only if you run out of platform views because the engine is trying to be smart and introduces undesirable side effects when it happens, so it's not clear it totally solves the problem.

I think it would probably be better if all of these options were surfaced directly by the HtmlElementView. If beneath was the default, it has less side effects than other two options (if only a couple of lines of code are added for the clear op during the rendering). Then, if you manually opted into between and ran out of layers it could work more like the overflow indicators, where instead of rendering the platform view at all, it renders a shape with an error indicating that you've run out of platform layers.

The problem right now is that this continual desire to insert the views between everything as the default keeps causing unpredictable behavior because it's a fundamentally problematic default. There is no real perfect solution to the problem, but the least problematic default would be something other than putting them between. None of these overlay group issues would be a big deal if they were something you opted into instead of being forced upon you by a problematic default.

**Comment by yjbanov** [comment]
@jezell I tried to capture your feature request (and we've been thinking about similar ideas that are documented in the issue too) here: https://github.com/flutter/flutter/issues/145360

**Comment by yjbanov** [comment]
I think this change should still go in. We're essentially choosing the least bad option for the case where we already know that we ran out of overlays and will render incorrectly. We're trying to minimize the damage. Seems like the strategy @harryterkelsen picked would be best for the common case, no?

**Comment by jezell** [comment]
@yjbanov I agree it's better than the current behavior until https://github.com/flutter/flutter/issues/145360 lands

**Review by yjbanov — APPROVED** [review]
lgtm

**Pull request merged**
