### PR TITLE
Add engine group constructor in FlutterViewConrtroller

### PR DESCRIPTION
**Pull request by luckysmg**
*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/72742

The Android solution is here:
https://github.com/flutter/engine/pull/29293

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Ping @gaaclarke. Do you have the cycles to review this?

**Comment by gaaclarke** [comment]
I'm not a fan of this change.  It doesn't add any new functionality, just adds some convenience.  That doesn't scale, users are able to implement convenience functions on their own side, there's no need to add them to the API.

**Comment by xster** [comment]
I think a sensible argument for this one is that the owner of the FlutterEngineGroup lifecycle is outside of the vc lifecycle. That's expected. But the owner of the FlutterEngine (if it were to be manually injected) must also both 1- sit outside of the vc lifecycle and 2- monitor the vc lifecycle to destroy the engine when it's no longer needed. This could be cumbersome to maintain separately.

**Comment by gaaclarke** [comment]
It's not really cumbersome, you just have to write
```objc
[[FlutterViewController alloc] initWithEngine:[_engineGroup makeEngine]]
```

versus

```objc
[[FlutterViewController alloc] initWithEngineGroup:_engineGroup]
```

I like that this advertises the feature a bit more, but I'd rather error on the side of a smaller combinatorial API since that's the only sane way forward.  Unless of course the boilerplate becomes a burden.  I don't see evidence that it is here.

**Comment by xster** [comment]
ya, this SG. I was initially concerned about the manual burden of having to also keep track of the destruction of the VC to match to the destruction of the engine. But it seems like that's not the case since the group only holds pointers that will be removed when the owning VC deallocates the engine https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterEngineGroup.mm#L88.

**Pull request closed without merging**
