### PR TITLE
[Impeller] Dart GPU: Add dart:gpu package.

### PR DESCRIPTION
**Pull request by bdero**
Part of: https://github.com/flutter/flutter/issues/131346

Sets up the `dart:gpu` in the engine.

After this lands, we can add it to the library list in: https://github.com/dart-lang/sdk/blob/main/pkg/vm/lib/target/flutter.dart

### CODE REVIEW

**Comment by bdero** [comment]
This is a revival of my attempt at making the new Dart GPU API available through the `dart:gpu` package that I mentioned to you some time ago. The API itself has old stub code and needs to be updated, but it's enough to at least demonstrate problems.

This currently errors out when compiling dart fixtures that import `dart:gpu` because the library still can't be found (for example, `dart_tests.dart` in this PR):

```
[1/4] ACTION //flutter/impeller/renderer:_dsk__ds_renderer_dart_fixtures(//build/toolchain/mac:clang_x64)
FAILED: gen/flutter/impeller/renderer/assets/kernel_blob.bin
vpython3 ../../build/gn_run_binary.py ../../flutter/prebuilts/macos-x64/dart-sdk/bin/dart /Users/bdero/projects/flutter/engine/src/flutter/prebuilts/macos-x64/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /Users/bdero/projects/flutter/engine/src/out/host_debug_unopt/flutter_patched_sdk --target flutter --sound-null-safety --output-dill gen/flutter/impeller/renderer/assets/kernel_blob.bin --depfile /Users/bdero/projects/flutter/engine/src/out/host_debug_unopt/gen/flutter/impeller/renderer/snapshot__dsk__ds_renderer_dart_fixtures.depfile.d /Users/bdero/projects/flutter/engine/src/flutter/impeller/fixtures/dart_tests.dart
result 24f9280c-6fe1-476a-a188-dc7591d7298f
../../flutter/impeller/fixtures/dart_tests.dart:6:8: Error: Dart library 'dart:gpu' is not available on this platform.
import 'dart:gpu' as gpu;
       ^
Context: The unavailable library 'dart:gpu' is imported through these paths:

    dart_tests.dart => dart:gpu

24f9280c-6fe1-476a-a188-dc7591d7298f
+file:///Users/bdero/projects/flutter/engine/src/flutter/impeller/fixtures/dart_tests.dart
24f9280c-6fe1-476a-a188-dc7591d7298f gen/flutter/impeller/renderer/assets/kernel_blob.bin 2
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Agpu; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:721:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:861:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:669:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:102:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

ninja: build stopped: subcommand failed.
```

After some spelunking in frontend_server and the Dart compiler, I set it to the side and started landing parts of the API under `lib/ui/experiments`.

FYI @jonahwilliams, in case you have ideas/know what I'm missing. :)

**Comment by jonahwilliams** [comment]
You will need to update the Dart compiler to be aware of this target:

https://github.com/dart-lang/sdk/blob/main/pkg/vm/lib/target/flutter.dart#L12

There may be additional steps. I would verify changing this locally fixes things (and you'll need to opt out of the prebuilt dart SDK to do that)

If that is the fix, I would plan on conditionally adding dart GPU to that set that we can only enable it in experimental builds.

**Comment by bdero** [comment]
That seems to be the only bit that was missing, thanks! :)

> I would plan on conditionally adding dart GPU to that set that we can only enable it in experimental builds.

What about adding it to the upstream package list unconditionally, but just expose nothing through the non-experimental stub for now? I updated this PR to set things up with this in mind.

I should be able to move over everything from `dart:ui` and get tests going on CI as soon as:
1. This lands
2. The library addition lands upstream

**Comment by jonahwilliams** [comment]
I'll be honest I don't really know what the implications of that would be. I think there _might_ be issues if you try to build with `dart:gpu` in that set of required libs if its not actually available. But I would ask someone on the dart team...

**Comment by jonahwilliams** [comment]
You could also look at how we conditionally enable the widget inspector via TargetFlags

**Comment by bdero** [comment]
> I think there might be issues if you try to build with dart:gpu in that set of required libs if its not actually available.

What I'm proposing is something that would make this situation never occur. We'd start with this engine patch that adds `dart:gpu` to the SDK library spec in all cases (sometimes an empty stub file). And then after this patch lands, we'd patch in the Dart compiler upstream and add it to exposed libraries set. So there should never be a moment where `dart:gpu` is in the upstream library set without it being built into the SDK.

I went ahead and started a chat in the Flutter & Dart room as well. :)

**Comment by bdero** [comment]
Corresponding Dart SDK PR: https://dart-review.googlesource.com/c/sdk/+/316486

**Comment by chinmaygarde** [comment]
We went with another solution.

**Pull request closed without merging**
