### PR TITLE
Revert "Disable build_ios task due to lack of credits."

### PR DESCRIPTION
**Pull request by kf6gpe**
Reverts flutter/engine#8150; Cirrus CI should not be the issue here.

### CODE REVIEW

**Comment by kf6gpe** [comment]
This should also address #29265

**Comment by chinmaygarde** [comment]
Wait. If Cirrus & the credits [were not the issue](https://github.com/flutter/engine/pull/8150#issuecomment-472475329), why did the builds take that long? I don't think the root cause was identified.

**Comment by chinmaygarde** [comment]
Just saw the [added clarification](https://github.com/flutter/engine/pull/8150#issuecomment-472556505).

**Comment by chinmaygarde** [comment]
The issue seems to be back again. [This job](https://cirrus-ci.com/build/5087902919819264) took about an hour to be scheduled and it still seems to be running 20 mins later.

**Pull request merged**
