### PR TITLE
Exclude a generated .pyc file from the Dart licenses file tree

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/8115

### CODE REVIEW

**Comment by jason-simmons** [comment]
@Hixie

**Comment by abarth** [comment]
Can we exclude all pyc files?

**Comment by chinmaygarde** [comment]
Shouldn't we be excluding all .pyc files?

**Comment by jason-simmons** [comment]
For files identified as text/source the licensing script has a list of filename patterns that are not expected to affect the build output.  But for binary files the script assumes any file could be in the build product.

However, it seems safe to exclude .pyc files

**Comment by Hixie** [comment]
The script is already trying to exclude all pyc files. If it doesn't then there's a bug that we should track down.

**Comment by Hixie** [comment]
See line 64. It's trying to exclude all files that end in `.py` or `.pyc`.

**Comment by Hixie** [comment]
Ah, I see. We should just move RepositorySourceFile's isIncludedInBuildProducts to RepositoryLicensedFile.

**Comment by jason-simmons** [comment]
That filter applies to source (text) files.  .pyc is classified as a binary file

**Comment by jason-simmons** [comment]
Moved the filter up to RepositoryLicensedFile

**Comment by Hixie** [comment]
Travis skipped running the license checks because the hashes didn't change... we should probably add in a hash of the script itself to the hashes of each subsection.

If you checked locally that this results in no changes to the output then LGTM. Bonus points for just making the script itself be part of the hash as sugggested above.

**Pull request merged**
