### PR TITLE
[Impeller] remove capability to read from onscreen.

### PR DESCRIPTION
**Pull request by jonahwilliams**
As discovered by @knopp in https://github.com/flutter/flutter/issues/131567#issuecomment-1678210475, this is actually reducing performance substantially when there are multiple blurs. In the case of https://github.com/flutter/flutter/issues/132735 , removing this capbility improves GPU performance from 400ms per frame to ~100 ms per frame.

Fixes https://github.com/flutter/flutter/issues/131567#issuecomment-1678210475

-----

  | Macrobench | Example App
-- | -- | --
TOT | 250 | 450
W/Out OnScreen | 203-187 | 125-109
W/Out Onscreen and Resolve | 203 | 125

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM!

**Comment by flar** [comment]
These 2 lines are telling the layer tree that the surface can read from the backdrop. The layer tree will automatically do offscreen rendering as needed if these 2 flags are simply set correctly.

https://github.com/flutter/engine/blob/9f4af5df9a2f222305f48bc5e1248906f95bd1cc/shell/gpu/gpu_surface_metal_impeller.mm#L171

https://github.com/flutter/engine/blob/9f4af5df9a2f222305f48bc5e1248906f95bd1cc/shell/gpu/gpu_surface_metal_impeller.mm#L275

**Comment by jonahwilliams** [comment]
Those flags are ignored by Impeller

**Comment by flar** [comment]
> Those flags are ignored by Impeller

Those flags are info supplied *TO* the layer tree. Impeller isn't supposed to look at them, it is telling the layer_tree what it can do - and it is lying here. If it had set these flags to false the layer tree would have enforced off-screen rendering already. This whole PR could be replaced by setting those 2 flags to false...

**Pull request merged**
