### PR TITLE
[profiling] Handle thread_info to account for killed threads

### PR DESCRIPTION
**Pull request by iskakaushik**
Fixes: https://github.com/flutter/flutter/issues/63025

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Review by liyuqian — APPROVED** [review]
Testing this might be difficult (especially with an iOS integration test) so it's fine to merge this as is. Just pointing out the test for thoughts.

**Comment by rahulvyas** [comment]
Still not able to run on iOS Simulator. 

Switched to master branch and run flutter upgrade command. 
After this tried to run on iPhone 11 Pro simulator but nothing works. It hangs on "waiting for iPhone 11 Pro to report it's views"

**Comment by iskakaushik** [comment]
@rahulvyas could you please open a new issue? This fix was specifically for the spurious error messages being seen when mach kernel reports an unavailable destination port. I doubt that this is the reason for your app not working on a simulator.

**Comment by bhanuka96** [comment]
still not able to run on real ios devices https://github.com/rekab-app/background_locator/issues/166#issue-748451296

**Pull request merged**
