### PR TITLE
Revert "[macOS] Refactor rendering infrastructure"

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/engine#37789

Google internal bug at b/262764490

This is causing breakages as the std calls aren't explicitly called. Relanding requires ensuring things like `#include <vector` are in the culprit files.

Sample of errors:

```
shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm:11:33: error: implicit instantiation of undefined template 'std::vector<void (^)()>'
  std::vector<dispatch_block_t> _scheduledBlocks;

shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm:36:37: error: unknown type name '_mutex'; did you mean 'std::mutex'?
  std::unique_lock<std::mutex> lock(_mutex);

shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm:38:3: error: use of undeclared identifier '_beginResizeWaiting'
  _beginResizeWaiting = YES;
```

### CODE REVIEW

**Review by itsjustkevin — APPROVED** [review]

**Comment by CaseyHillers** [comment]
@cbracken can you help with the reland to prevent future breakages? Issue seems to be with differences in how the compilers are configured.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
Yep - thanks for catching this!

**Comment by cbracken** [comment]
@CaseyHillers Can you attach the compiler error output to help with the fix?

**Comment by CaseyHillers** [comment]
@cbracken I've gone ahead and added the unique errors to the description. Some of its been redacted, but I think I got the main errors included.

**Comment by knopp** [comment]
Looks like a missing std::vector import? I am a bit curious why it compiles at all. Precompiled headers seem to be disabled in buildroot.

**Comment by cbracken** [comment]
Thanks. Probably faster for me to quick iterate on the internal roll patch to get it to compiling state. @knopp If you want to put together a reland patch I can add the changes or just paste the patch and you can apply it and reland.

**Comment by knopp** [comment]
Does your internal build use different libcxx version? The one included in third_party/libcxx includes vector implicitly (functional -> boyer_moore_searcher -> vector), that's why I missed it. I'll create a reland PR.

**Comment by CaseyHillers** [comment]
@cbracken has a one line fix he's going to send

**Comment by cbracken** [comment]
Fixed by @knopp in https://github.com/flutter/engine/pull/38337

**Pull request closed without merging**
