### PR TITLE
[dart:ui] remove expensive index assertion in Vertices.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Iterating through every index value is really, really expensive. Especially if users are suppllying hundreds of thousands of vertices.

### CODE REVIEW

**Comment by flar** [comment]
Where are we expecting this validation to occur then? At some point we have to protect against reading past the ends of the data arrays.

**Comment by jonahwilliams** [comment]
We don't read the indices though, we pass it to the gpu driver. I suppose we should validate that reasonable things happen there.

**Comment by jonahwilliams** [comment]
verifying on GLES/Vulkan/Metal backend, no crashes. We don't ever read the index data on the CPU

**Comment by flar** [comment]
We should add a test case that using out of range index values works fine if that is the expected behavior.

We may not currently read them on the CPU, but might in the future. One example is the computation of the bounds of the vertices. Currently their bounds are the bounds of all vertices, but if we have 100k vertices and only 100 indices then there is wasted effort there - so we might in the future switch to using the indices for bounds (possibly with a quick test as to whether there are more vertices than indices or vice versa) - at which point we want to make sure that there is a test case that would remind us that OOB indices are specifically allowed...

**Comment by jonahwilliams** [comment]
I can add a test at the DL-impeller level and produces a golden. SG?

**Comment by flar** [comment]
For rendering - as long as it goes through DlBuilder. ui.Canvas is basically a pass through, but starting at Builder we have increasing reasons to inspect the data.

Another thing to verify is constructing the Dart Vertices object itself - the constructor might decide to prune the data at some point if indices is small?

**Review by jtmcdole — APPROVED** [review]
lgtm

**Comment by jonahwilliams** [comment]
PTAL @flar

**Comment by jonahwilliams** [comment]
Jim is out this week. maybe @jtmcdole PTAL?

**Review by flar — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
@jonahwilliams Can we land this?

**Comment by jonahwilliams** [comment]
@chinmaygarde did you mean to close this? We should be able to land it, didn't realize it got reviewed.

**Comment by chinmaygarde** [comment]
Oh, yeah. Definitely a mistake. Sorry.

**Comment by jonahwilliams** [comment]
no worries!

**Pull request merged**
