### PR TITLE
[Impeller] ensure precision matches for buggy vulkan drivers.

### PR DESCRIPTION
**Pull request by jonahwilliams**
This is another precision mismatch bug - WHICH IS NOT AN ERROR AT ALL BUT THE PowerVR Drivers ARE BUGGY BUGGY BUGGY

Fixes https://github.com/flutter/flutter/issues/152951

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
This should be the same fix as https://github.com/flutter/engine/pull/51974 and fixing https://github.com/flutter/flutter/issues/147078 should allow us to catch further issues like these at build time.

**Comment by chinmaygarde** [comment]
This was another PowerVR device right?

**Comment by jonahwilliams** [comment]
This is Imagination. I'm thinking about ordering the device, but in the meantime it might be easier to land this safe change and ask the reporter to try again.

**Comment by chinmaygarde** [comment]
Google says they are the same.

Screenshot 2024-08-06 at 1 37 55 PM

I thought we already had a device.

**Comment by jonahwilliams** [comment]
Ahh the OLD SWITCHERO. Yeah I've got one ... somewhere. its almost certainly the same issue then

**Comment by chinmaygarde** [comment]
Let me see how difficult it would be to wire up the static checks. IIRC @gaaclarke did most of the work already.

**Pull request merged**
