### PR TITLE
Reland: Re-enable scenario tests on Android

### PR DESCRIPTION
**Pull request by blasten**
Relands https://github.com/flutter/engine/pull/33574

346adc08c5941bee04443b50852c73ed973ec72f addresses the comment in https://github.com/flutter/engine/pull/33809

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by skia-gold** [comment]
Gold has detected about 105 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/34048

**Comment by skia-gold** [comment]
Gold has detected about 102 new digest(s) on patchset 4.
View them at https://flutter-engine-gold.skia.org/cl/github/34048

**Comment by skia-gold** [comment]
Gold has detected about 220 new digest(s) on patchset 5.
View them at https://flutter-engine-gold.skia.org/cl/github/34048

**Pull request merged**
