### PR TITLE
Add dependency on Windows SDK CIPD package

### PR DESCRIPTION
**Pull request by cbracken**
We now build against a specific Windows SDK rather than whatever happens
to be installed on the host machine.

This also rolls the buildroot to include change
flutter/buildroot#448, which generates the WinRT
headers from the CIPD Windows SDK.

This also re-enables the UWP builder.

Fixes https://github.com/flutter/flutter/issues/81994
Fixes https://github.com/flutter/flutter/issues/82009

Covered by existing tests.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]

**Review by clarkezone — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
The cppwinrt failure here is that cppwinrt can't handle paths that are longer than the [Windows maximum path length](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) of 260 characters. I was able to repro this locally by renaming a parent directory to something really long. Looking at how we can work around that. One option appears to be setting a particular registry key

**Comment by kennykerr** [comment]
> The cppwinrt failure here is that cppwinrt can't handle paths that are longer than ...

This should be supported with recent builds. https://github.com/microsoft/cppwinrt/blob/master/cppwinrt/app.manifest

**Comment by cbracken** [comment]
@kennykerr Thanks! I was able to repro the path failures on my desktop with version `2.0.210304.5`. Last night, I was poking through commits since March and saw one that looked promising -- I verified that updating to version `2.0.210505.3` resolved the path length issue for me on my desktop. Thanks for fixing!

Still seeing a failure on the bot. I've added some logging to see if I can diagnose what's up.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847867838126420048/+/u/Checkout_source_code/gclient_runhooks/stdout

**Comment by cbracken** [comment]
Ah interesting; in local testing the paths on the subst'ed drive are still canonicalised back to their original drive paths -- which I suppose makes sense :)

**Comment by kennykerr** [comment]
@asklar has more experience with the long path support.

**Comment by asklar** [comment]
@cbracken Glad to hear long paths support in cppwinrt is working locally for you! 

In order for cppwinrt to work with long paths, you have to enable long paths system-wide:
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later
(this will work on Windows 10 1607 and later)
The regkey might already be set on your local machine but not in the CI agent.

**Comment by cbracken** [comment]
@asklar thanks! Verified the long paths registry key is set on my machine; taking a wiring up a command in our build recipe to flip that value on the bot, which seems like something we should be doing in 2021 regardless :)

**Comment by cbracken** [comment]
I've landed an update to the Windows engine recipe that enables long paths in https://flutter-review.googlesource.com/c/recipes/+/13300.

**Comment by cbracken** [comment]
Similar change for the web engine shards, which also need long path support since cppwinrt is run as part of gclient runhooks, which happens in all engine shards. https://flutter-review.googlesource.com/c/recipes/+/13301. Barring the web engine shard, which should be fixed by that patch, presubmits are looking good. 

Thanks @clarkezone @kennykerr and @asklar for your help debugging this!

**Pull request merged**
