### PR TITLE
Add fuchsia.net.name.Lookup

### PR DESCRIPTION
**Pull request by tamird**
fuchsia.net.NameLookup is transitioning to fuchsia.net.name.Lookup.

@zanderso

### CODE REVIEW

**Review by arbreng — COMMENTED** [review]
There is a lot of formatting noise.  How did you format these files?

I'd prefer to keep the formatting to its own change

**Comment by tamird** [comment]
Using the standard formatter from the fuchsia tree https://cs.opensource.google/fuchsia/fuchsia/+/main:tools/devshell/contrib/format-code;l=105;drc=857c31638b5f31395b23bca085a6b20e7930933f.

**Comment by tamird** [comment]
Moved to https://github.com/flutter/engine/pull/27603.

**Comment by tamird** [comment]
Rebased.

**Review by arbreng — APPROVED** [review]

**Pull request merged**
