### PR TITLE
[Impeller] remove scene3d support.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Now that Flutter GPU is a preview, the technical debt from having an ifdef controlled additional rendering mode can be removed.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
cc @bdero if he can think of any reason we should keep this around still.

**Comment by jonahwilliams** [comment]
We can revert if there are issues.

**Comment by bdero** [comment]
Not quite ready to remove this yet because I'm still porting the animation stuff to flutter_scene.

**Comment by bdero** [comment]
reason for revert: Not quite ready to remove this yet because I'm still porting the animation stuff to flutter_scene.

**Pull request merged**
