### PR TITLE
Make a mock messenger that can easily mock channels

### PR DESCRIPTION
**Pull request by robert-ancell**
The previous mock required knowing the specific functions used in the binary messenger, this method instead allows test code to provide complete platform channel implementation for testing and make simulated platform channel calls into embedder code.

### CODE REVIEW

**Comment by robert-ancell** [comment]
This PR includes both https://github.com/flutter/engine/pull/56856 and https://github.com/flutter/engine/pull/56866 which were discovered when making this branch.

**Comment by robert-ancell** [comment]
This branch was motivated by refactoring the platform channel code and the tests often breaking. It will hopefully be easier to write and maintain tests using this new mocking infrastructure.

**Review by hbatagelo — APPROVED** [review]
The changes look great overall! One minor suggestion is to reduce code duplication in files like `fl_key_channel_responder_test.cc` where the non-capturing lambdas used as callbacks are repeated and could be refactored.

Also, some checks are failing: `linux_unopt` seems to have failed due to formatting.

**Comment by robert-ancell** [comment]
> The changes look great overall! One minor suggestion is to reduce code duplication in files like `fl_key_channel_responder_test.cc` where the non-capturing lambdas used as callbacks are repeated and could be refactored.

The issue I had was if you added captures they no longer matched the function pointers, which meant I couldn't cleanly make them share code. In the end, I accepted the duplication, but would be interested if there is a clean way to update these in the future.

**Pull request merged**
