### PR TITLE
Update Dart to 2e55f22810980b289f4d6403ba33440dafd9985d

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by rmacnak-google** [comment]
@aam I believe top-of-tree still has a known failure in flutter_gallery?

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/issues/30003 is opened to track regression introduced in Dart that results in flutter gallery crash on 8378b8fdbf332c9bf2166abb960354bb92492480 dart commit. So roll of the engine dart dependency should wait until that is rolled back(https://codereview.chromium.org/2962543002/)

**Comment by abarth** [comment]
Revert has landed.

**Pull request merged**
