### PR TITLE
Prepare and restore DisplayListBuilder attributes across a DisplayList::RenderTo(Builder) operation

### PR DESCRIPTION
**Pull request by flar**
Fixes https://github.com/flutter/flutter/issues/100983

Each DisplayList is built assuming that all attributes are at default values when it builds its stream of records. This PR sets all of the attributes in the target builder to defaults before dumping the DisplayList into it.

Currently the only way we put data into a DLBuilder is either via canvas.cc or via this one call to DisplayList::RenderTo() and each of these entry points currently will set all indicated attributes before any rendering call, so the state of the attributes after a RenderTo() isn't necessarily depended on. But, just to present a consistent interface to anyone using these methods in a more manual manner, the RenderTo call will restore all attributes that were present before it pushed the DL data - so that the ending attributes have a consistent state that matches their values before the call.

To facilitate these changes, I created a small structure to encapsulate all rendering attributes and use it internally in DisplayListBuilder and now provide new methods to grab that state and set it back - utility methods for the RenderTo method. Eventually, the DisplayListBuilder could be rearchitected to provide these values in each rendering call, as in `drawRect(rect, attributes)` instead of individual get/set calls, but the currently simple structure should be made a little more formal before that happens and it becomes a first class object (rather than an "inner" class of DLBuilder).

Currently the struct is named "DlAttributes" which might be slightly confused with "DlAttribute" which is the base class for all complex rendering attributes (DlMaskFilter, DlColorFilter, etc.). It is also thematically similar to SkPaint, but I went with DlAttributes instead of DlPaint because the name "Paint" does not really match the data it holds. Discussion on this naming shouldn't be too critical until and unless we expose it more formally as in the architectural changes to the Builder draw methods - at which point developers would be exposed to the naming.

Tests include:
- basic tests on the new DlAttributes struct and the methods that use it.
- tests that confirm the undisturbed state before and after a call to RenderTo(builder)
- tests that demonstrate that the proper DisplayList is recorded in the DisplayListLayer (in a simulated impeller mode)

### CODE REVIEW

**Comment by zanderso** [comment]
Is this needed to help solve a correctness issue, or implement an optimization?

**Comment by flar** [comment]
> Is this needed to help solve a correctness issue, or implement an optimization?

I thought I addressed that in the description. The display lists may not render correctly because the initial attributes they render with will be unexpectedly not the default values. This fix normalizes the environment into which their recorded records are being transferred.

**Comment by bdero** [comment]
This change fixes issues with Cupertino widgets in gallery (context menu and date/time pickers) caused by the previous color source state leaking into path draws for the widgets.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Needs to have the unit tests merged up to head.

**Comment by flar** [comment]
I am going to try a new approach to this issue for a couple of reasons:

- This PR is based on the existing code to render a DL to a DL by replaying it, which requires copying all of its contents
- The save/restore state can be managed much better in the dispatcher rather than here.

**Comment by flar** [comment]
Also, I'm developing a DlPaint object to encapsulate state so this mechanism may have a very short shelf life.

**Comment by flar** [comment]
Superseded by https://github.com/flutter/engine/pull/32880 and https://github.com/flutter/impeller/pull/153

**Pull request closed without merging**
