### PR TITLE
Adds Dark Mode support to new Android embedding (this was accidentally missed previously).

### PR DESCRIPTION
**Pull request by matthew-carroll**
Adds Dark Mode support to new Android embedding (this was accidentally missed previously).

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@mklim what kind of integration test were you thinking? which testing infrastructure would we use?

**Comment by mklim** [comment]
@matthew-carroll I was thinking a flutter driver test that made sure the UI was at a particular brightness when the system was in Dark mode. But I was genuinely asking whether or not you thought that was feasible. That test would depend on the device the test was ran on being set to the right mode in its system settings. From a brief cursory look it's possible to toggle dark mode on and off with ADB, `adb shell settings put secure ui_night_mode (1 or 2)`. So I'm thinking a test could run that first using `Process#run`, then launch the Flutter app and check the UI. I think that's theoretically possible but I'm not totally sure, the details of getting that adb command working may be tricky.

**Comment by matthew-carroll** [comment]
Any idea how we verify brightness in that test? I guess we would need to setup a channel on the Dart side in the test app and then let the Driver know as the brightness changes?

**Comment by mklim** [comment]
System brightness or Flutter UI brightness?

For system brightness, I was assuming we would start the test after setting the brightness with ADB so there's no need to know. Similar to how the [camera package tests](https://github.com/flutter/plugins/tree/master/packages/camera/example/test_driver) don't call `final FlutterDriver driver = await FlutterDriver.connect();` until after granting permissions with ADB.

For Flutter UI brightness, I was assuming we could grab the color or theme of a Widget in the UI and assert that it was expected.

**Comment by matthew-carroll** [comment]
Hm, I'm not sure I follow...isn't the thing that we're trying to test the signal from Android to Flutter, reporting the system brightness? So even if we turn on dark mode before launching the app, we still need to verify that Flutter thinks we're in dark mode, right?

**Comment by mklim** [comment]
Right. I may be missing something. I'm assuming that there's an existing hook in the framework that responds to the system being in Dark mode and changes the Flutter UI to match, and that this method is hit on start as well as on change.

Here's my thinking:

We want to test that Flutter changes its UI in response to the system UI being set to dark mode with the new embedding. (The actual portion of this change is just that Flutter receives a notification that the system has been set to Dark mode, so there is probably some much smaller more targeted test that focuses on that. This would be checking the entire feature.)

So for the test:

#### Arrange
- Create a sample Flutter app that uses the v2 embedding and MaterialApp with a light and dark theme
- Use `Process#run` ADB to set the system into Dark mode
- Launch a Flutter driver test

#### Act
- Get the Flutter app material theme

#### Assert
- Assert that the app is actively using the dark theme

It may be possible to use `Process#run` mid-test to verify that Flutter gets changes after the app runs too. I think that's likely to be flaky though because it will take time after the ADB command finishes to actually update the app's UI.

There's probably multiple ways to test this, that was just what came to mind. I do think this could be JUnit tested too, I just think it would be painful to write since it's dealing with so much internal state and silent side effects within FlutterView.

**Comment by matthew-carroll** [comment]
Given that this is blocking the internal app migration, how about I make this method public for testing and file an issue to come back and do the ideal test that you've described?

**Comment by matthew-carroll** [comment]
I made the channel method public for testing and added a unit test for light mode and a unit test for dark mode. I also filed the following ticket to create an e2e test when we can make the time: https://github.com/flutter/flutter/issues/42990

**Pull request merged**
