### PR TITLE
Roll the Dart runtime forward

### PR DESCRIPTION
**Pull request by johnmccutchan**
This is not ready to be landed until I land a fixup CL to the Dart VM. This will happen tomorrow.

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@jamesr @chinmaygarde FYI

**Comment by chinmaygarde** [comment]
lgtm

**Comment by johnmccutchan** [comment]
This is ready to be pulled but I don't have permissions to merge it

**Comment by chinmaygarde** [comment]
@johnmccutchan Thanks. You also now have push access.

**Pull request merged**
