### PR TITLE
Add //garnet

### PR DESCRIPTION
**Pull request by abarth**
This repository contains FTL now in the Fuchsia build.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
This commit caused Travis to be mad at the licenses https://travis-ci.org/flutter/engine/builds/270606222#L531.

**Comment by abarth** [comment]
Why wasn't it mad on the PR?

**Comment by abarth** [comment]
I see, it passed but had an exception.

**Comment by jason-simmons** [comment]
travis/licenses.sh needs a "set -e" that will return failure from the script if the dart command fails.

Looks like leaktest1.fidl is a test file that is not valid UTF-8.  I can patch the license script to exclude it.

**Comment by chinmaygarde** [comment]
> I can patch the license script to exclude it.

Thanks!

**Pull request merged**
