### PR TITLE
Introduce IO thread for background tasks

### PR DESCRIPTION
**Pull request by abarth**
Currently we run some tasks on the UI thread that shouldn't block the frame,
such as decoding images. This patch introduces a background thread on which we
can run these tasks.

### CODE REVIEW

**Comment by abarth** [comment]
@collinjackson

**Comment by Hixie** [comment]
LGTM

**Comment by jamesr** [comment]
The "IO" thread terminology in chromium never worked well as it's the thread you weren't supposed to do I/O on.  Is there a better name we could use here?

**Comment by abarth** [comment]
Sure!  The current use cases for this thread are to drain data pipes asynchronously and to run image decoders.  I'm not sure what other use cases we'll have for it in the future.  I would guess other non-blocking tasks that don't need to complete by a given animation deadline.

Maybe the ui_thread should be the rt_thread and this thread should be the ts_thread?  ;)

**Comment by Hixie** [comment]
"Foreground thread" and "Background thread"?

**Comment by j9brown** [comment]
"Worker" thread?  Though I like the fg vs. bg thread characterization too.

**Comment by abarth** [comment]
Worker sounds to me like an anonymous thread that I'm likely to have many of (e.g., a worker pool).

**Comment by sethladd** [comment]
+1 for background thread, fwiw.

**Comment by j9brown** [comment]
Ah that's quite true.  It may also lead clients to believe it's a good
place to do lots of heavy compute intensive work which might harm
responsiveness of other tasks happening on the same thread, much like the
IO thread naming.

Actually with that in mind, we'll want to have clear guidelines on what
kind of work we want these threads to be doing if they will be shared.
Imaging decoding tasks in particular could take hundreds of milliseconds to
complete so if you get a bunch of them queued up back to back other things
also scheduled on the thread might be delayed in ways that would indirectly
impact the UI.

So it may be we actually do want to punt those tasks to a thread pool to
limit contention.  We might even want to prioritize them in some cases.

Should Flutter offer a single distinguished "non-UI" thread or something
else?

**Comment by abarth** [comment]
> It may also lead clients to believe

We're not exposing this thread to authors.  It's just something that the engine uses internally.

> We'll want to have clear guidelines on what kind of work we want these threads to be doing if they will be shared

I agree that will make sense once we have more engineers working in this area, but at the moment, I'm pretty much the only person writing C++ code inside the Flutter engine so it seems a bit early to write up guidelines for myself.  Instead, I think it would be better to see what sorts of use cases emerge for this sort of thing and then iterate/refactor as needed once we have a better understanding of the problems we need it to solve.

> Imaging decoding tasks in particular could take hundreds of milliseconds to complete

Keep in mind that we have incremental image decoders, so we can time-share the image decoding at whatever granularity we want (and we can pipeline the decoding with the network transfer).

> Should Flutter offer a single distinguished "non-UI" thread or something else?

I don't think we should offer anything of that sort yet.  Currently the author is restricted to running Dart code on a single thread.  We'll probably need something more than that in the end, but we're waiting to see what folks need before building out a multithreading mechanism speculatively.

**Comment by j9brown** [comment]
Ah gotcha.  I thought this was going to be visible to developers as an
API.  (Guess I should have looked at the patch.). As it is I agree we
should keep it simple.  :)

**Pull request merged**
