### PR TITLE
Expose `vsync` information to developer

### PR DESCRIPTION
**Pull request by fzyzcjy**
This PR tries to expose vsync information to the developer, so they can know when it is proper to call the more un-restricted `window.render` proposed in #36438.

Currently only the API is shown, because IMHO the implementation details is unrelated to thoughts about #36438, and the API (and therefore implementations) are subject to changes. I will continue working on it, once the API is approved.

For detailed design about this API and its implementation, please have a look at "Get last vsync time information" section of https://docs.google.com/document/d/1FuNcBvAPghUyjeqQCOYxSt6lGDAQ1YxsNlOvrUx0Gko/edit.

Sample usage:

```dart
final info = SchedulerBinding.instance.lastVsyncInfo();
```

List of work:

- [x] code the (draft) Dart API
- [ ] discuss whether the API is acceptable
- [ ] implement the C++ part on SDK<=29 Android
- [ ] implement the C++ part on new android, ios, and other platforms
- [ ] create a wrapper function in `flutter/flutter` repo, probably in `SchedulerBinding`

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
It's not clear to me how this is any different from observing the Duration you get in `onBeginFrame`.

Also, we would not want this kind of "pull" model that applications or packages would have to call every frame or multiple times per frame, especially since this data will definitely change every frame.

**Comment by dnfield** [comment]
I'm going to close this to remove it from review queues. As I'm mentioning in some other PRs, let's discuss further on discord.

**Comment by fzyzcjy** [comment]
Thanks, I will discuss on discord about this

**Comment by fzyzcjy** [comment]
> It's not clear to me how this is any different from observing the Duration you get in onBeginFrame.

In flutter_smooth, one janky frame can be (e.g.) 100ms, and we need to submit window.render per vsync interval. When is the next vsync interval? This question is answered by this PR.

In other words, in the 100ms janky frame, onBeginFrame only provides first vsync target time, while we need to know the rest.

> As I'm mentioning in some other PRs, let's discuss further on discord.

Sure, will discuss when you have time (guess you are on weekends so reply here firstly)

**Pull request closed without merging**
