### PR TITLE
Force anti-aliasing on clipRRect calls.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Per recommendation from the Skia team. Benefits from optimizations applied in Skia for Chrome.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @abarth @jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Comment by abarth** [comment]
We should probably do the same for the RRect clips that we record in Dart.  See PaintingContext.pushRRectClip.

**Comment by chinmaygarde** [comment]
On it.

**Pull request merged**
