### PR TITLE
Reland: [Impeller] Turned on new blur. (#48472)

### PR DESCRIPTION
**Pull request by gaaclarke**
This is a reland of the new gaussian blur.

Changes since revert:
1) Textures are now recycled with ping ponging to reduce memory usage
1) Mipmaps are generated to diminish the shimmering that happens with animated blurs (in metal)

---

This new blur should perform faster since it scales down the image before blurring it. Jonah did early testing of it and found it to be faster. Scrolling around with the blur perf bug it seems faster. It also has a wider test bed and is hopefully easier to maintain since it contains all of its logic for both directions.

testing: There are existing blur tests and we've backfilled more as we've added features to this blur.

fixes https://github.com/flutter/flutter/issues/131580 fixes https://github.com/flutter/flutter/issues/138259

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]:
https://github.com/flutter/flutter/wiki/Tree-hygiene#overview [Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene [test-exempt]:
https://github.com/flutter/flutter/wiki/Tree-hygiene#tests [Flutter Style Guide]:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo [C++, Objective-C, Java style guides]:
https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style [testing the engine]:
https://github.com/flutter/flutter/wiki/Testing-the-engine [CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]:
https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes [Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
This looks like no one is ever setting `TextureVK::mipmap_generated_`.  I tried to make that set and there was still a validation error.  There seems to be some problems with vulkan mipmap generation that need to get sorted out.

**Comment by gaaclarke** [comment]
Looks like this is failing on vulkan still.  Jonah suggested just turning it on for iOS.

**Comment by gaaclarke** [comment]
After https://github.com/flutter/engine/pull/49836 this should be good to go.

**Comment by gaaclarke** [comment]
This depends on https://github.com/flutter/engine/pull/49836, but that is approved and will be landing shortly so I'm putting this into review now.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by gaaclarke** [comment]
Golden images are looking good, no need to approve them since this will just get rebased after the vulkan goldens tests pr lands.

**Review by bdero — APPROVED** [review]
LET'S GO!

**Comment by gaaclarke** [comment]
Benchmarks for the new blur (about 2x faster): https://flutter-flutter-perf.skia.org/e/?keys=X01fc3d52ebd6fbf38afef91d82ab8d2b&xbaroffset=38815

**Pull request merged**
