### PR TITLE
[Impeller] Apply some recent color filter fixes to BlendFilterContents::CreateForegroundAdvancedBlend

### PR DESCRIPTION
**Pull request by jason-simmons**
Some recent changes affecting color filters (https://github.com/flutter/engine/pull/55411, https://github.com/flutter/engine/pull/55448) need to be done for both Porter-Duff and advanced blend modes

### CODE REVIEW

**Review by gaaclarke — CHANGES_REQUESTED** [review]
The code looks good to me and are reasonable.  The changes to the tests haven't produced any golden changes though so I don't think we are accurately reproducing the problem that this fixes.  Did you see any difference locally?

**Comment by jason-simmons** [comment]
This issue reproduces locally on a Moto G4 using the GLES back end, and the fix has been verified on that platform.

This code path only applies to devices that do not support framebuffer fetch, causing `BlendFilterContents::RenderFilter` to call `CreateForegroundAdvancedBlend`.  I don't know whether any of the test environments produce goldens without framebuffer fetch.

**Comment by gaaclarke** [comment]
> This code path only applies to devices that do not support framebuffer fetch, causing

Ahh okay.  Thanks for remembering that.  We can artificially fall back to non-freambuffer fetch support by mocking out the capabilities.  We've done it in the past in another test.  I'll see if I can find it.  So, you'd just duplicate this test, then force it to do the fallback by mocking out the capabilites.

**Comment by gaaclarke** [comment]
Here's how we did it in the past to force non-decal sampling support: https://github.com/flutter/engine/blob/3dfb4622de88abb48ce65be56ff29422ab43805f/impeller/display_list/aiks_dl_blur_unittests.cc#L1060

**Comment by jason-simmons** [comment]
Added the suggested test - PTAL

**Review by gaaclarke — APPROVED** [review]
lgtm, thanks jason

**Pull request merged**
