### PR TITLE
[Impeller] Do not use clear color optimization if the subpass is being collapsed into its parent

### PR DESCRIPTION
**Pull request by jason-simmons**
The InlinePassContext will not apply the clear color within a parent pass that is already in progress.

Fixes https://github.com/flutter/flutter/issues/130824

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
DBC: it would be preferable from a performance perspective to still collapse the parent pass and instead undo the clear color optimization. The pass collapse avoids an expensive allocation and texture fill while the clear color optimization only removes a draw call.

**Comment by jason-simmons** [comment]
Changed this to disable the clear color optimization for subpasses that are collapsed into the parent

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by bdero — APPROVED** [review]
LGTM!

**Pull request merged**
