### PR TITLE
Manual roll of ICU

### PR DESCRIPTION
**Pull request by filmil**
Updates the version in use in ICU.

* https://github.com/flutter/flutter/issues/97412

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/issues/97412

**Comment by chinmaygarde** [comment]
This needs to be rebased and update licenses. @filmil If you are not going to continue on this @jason-simmons could also perform the roll.

**Comment by filmil** [comment]
@chinmaygarde I am happy to see this through, no need to rope anyone else in.

I may need to update the commit ID based on an ongoing discussion with Chromium folks.
I want to settle on a commit ID that's currently in use by Chromium.

**Comment by filmil** [comment]
For the time being, feel free to set this aside until I let you know it's ready again.

**Comment by filmil** [comment]
@chinmaygarde Feel free to assign me to this PR.

**Comment by filmil** [comment]
I updated the roll commit ID to https://chromium.googlesource.com/chromium/deps/icu/+/2e0f2989441ec2f55abec30f48e89981dbac2c34.
This is the latest version of ICU as of this writing.

**Comment by filmil** [comment]
@chinmaygarde I think this is now ready to go.

**Pull request merged**
