### PR TITLE
Update Linux embedder to latest semantics API

### PR DESCRIPTION
**Pull request by robert-ancell**
Change to the latest semantics API and remove an unused class.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

Nice! Looks like you just need to run the formatter and you're set.

**Comment by robert-ancell** [comment]
I'm confused by the formatting failure - it's in files not changed by this PR and it doesn't match the output of clang-format here.

**Comment by cbracken** [comment]
> it's in files not changed by this PR 

Odd... I wonder if something changed in the way we do the presubmits; we definitely used to intentionally exclude unmodified files. I've kicked off a re-run in the desperate hope that somehow it rights itself.

> it doesn't match the output of clang-format here

You're using the clang-format from the toolchain in our buildroot as opposed to a locally-installed version?

**Comment by robert-ancell** [comment]
I have been using the locally installed version which used to match, perhaps it doesn't anymore.

**Comment by robert-ancell** [comment]
Seems to be fixed on main already.

**Comment by robert-ancell** [comment]
Ah, I did include formatting changes by accident, I've stripped them out now.

**Pull request merged**
