### PR TITLE
[wip] Fuchsia external view embedder

### PR DESCRIPTION
**Pull request by arbreng**
This allows removing *all* Fuchsia-specific code from flow/, as well as
decoupling the compositor's scene graph from Flutter's scene graph.

As a bonus, we get to delete thousands of lines of old Fuchsia-specific
code :)

### CODE REVIEW

**Comment by iskakaushik** [comment]
Very excited for this PR!

**Comment by arbreng** [comment]
This builds on Fuchsia now, but still some crashes to deal with and platform views aren't hooked back up yet

**Comment by gw280** [comment]
I just noticed that this branch is currently living on the main Flutter engine repository. This really ought to be developed on a branch on a fork of the engine repo under your own account.

**Comment by arbreng** [comment]
Ooops! I didn't realize.  Will close this PR and make a new one from my fork

**Pull request closed without merging**
