### PR TITLE
[Impeller] Sample the gaussian function once per texture sample

### PR DESCRIPTION
**Pull request by bdero**
Follow-up to remove the second gaussian sample, which isn't really improving quality.

For both before and after, I don't think we're sampling from the center of texels, and this is causing textures with high frequency info to "ripple" a bit when slowly increasing the blur radius (another issue might be that our texture downsizing is, again, too aggressive too early). I'm currently working out the best way to fix this and may follow-up with something.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM.

I have seen the rippling, but thats in both the before and after versions. But my change assumes that we were sampling the from the center before. Should we just back that out entirely?

**Comment by bdero** [comment]
Yeah just like with the text UV mapping, I don't think we were doing it properly to begin with. I tested out before/after your change and it doesn't seem to make the problem any worse than it already was, so I think we should keep it.

**Comment by jonahwilliams** [comment]
SGTM, ship it

**Comment by jonahwilliams** [comment]
Continued drop in GPU utilization from this patch:

https://flutter-flutter-perf.skia.org/e/?begin=1680818463&end=1680882758&keys=Xf6333a58002b9f41439f0cd9572dadd1&selected=commit%3D34245%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Danimated_blur_backdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=34245

**Pull request merged**
