### PR TITLE
Remove unused generate_dart_ui target

### PR DESCRIPTION
**Pull request by dnfield**
https://flutter-review.googlesource.com/c/recipes/+/15420 has landed

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by dnfield** [comment]
@CaseyHillers @keyonghan @yusufm - this is failing to run LUCI presubmits for some reason. Saw this last week too at some point..

**Comment by keyonghan** [comment]
> @CaseyHillers @keyonghan @yusufm - this is failing to run LUCI presubmits for some reason. Saw this last week too at some point..

Reopen https://github.com/flutter/flutter/issues/86383
At the same time, manually triggered the tests.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
I missed a spot in linux_unopt.py - fixing that in https://flutter-review.googlesource.com/c/recipes/+/15620

**Pull request merged**
