### PR TITLE
Remove obsolete usage of the fuchsia tracing macros.

### PR DESCRIPTION
**Pull request by qsr**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by chinmaygarde** [comment]
@qsr Do you have write access? If not, I can merge this.

**Comment by qsr** [comment]
@chinmaygarde  I do not have write access.

Thanks.

**Comment by abarth** [comment]
@qsr I've invited you to join the flutter org, which should give you write access.  Thanks for the patches!

**Pull request merged**
