### PR TITLE
[Impeller] keep imgui hostbuffer alive.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/158275

We are now counting on the content context to keep the host buffer alive. the imgui overlay does not use a content context, so it has to manage the lifetime of the host buffer correctly, keeping it alive for as many frames as needed and destroying it in the correct order (before context destruction).

### CODE REVIEW

**Review by gaaclarke — COMMENTED** [review]
Code looks good and the fix is reasonable.  I would like us to have an automated test for this.  Can we just run a playgrounds test for N frames on CI?

**Comment by flar** [comment]
+1 to trying to make an automated test

**Comment by gaaclarke** [comment]
I remember chinmay at some point implemented a flag for impeller_unittest that would run for N milliseconds. I thought we wired that up to be run on ci, but I guess not.

**Comment by gaaclarke** [comment]
I mean as long as we use interactive playground tests we should try to make sure they don't break since it costs developer time when they do break.  If we don't want to try to assert they stay functional we should just delete them and rely on impeller_golden_tests.

**Comment by jonahwilliams** [comment]
Expanded the interactive playground test suite to cover GLES and Metal.

**Review by gaaclarke — APPROVED** [review]
awesome, thanks jonah

**Comment by flar** [comment]
+1 to the thanks!

**Review by flar — APPROVED** [review]

**Comment by jonahwilliams** [comment]
The failure in 1DThreadgroupSizingIsCorrect looks real, investigating...

**Pull request merged**
