### PR TITLE
Retain VM snapshot data

### PR DESCRIPTION
**Pull request by knopp**
Possible fix for https://github.com/flutter/flutter/issues/84908

It lets Dart VM retain VM snapshot data.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
Retaining this data is embedder should be responsibility. The documentation for `FlutterEngineCreateAOTData` states the following (emphasis mine):

"Creates the necessary data structures to launch a Flutter Dart application in AOT mode. **The data may only be collected after all FlutterEngine instances launched using this data have been terminated.**".

As documented, this is working as intended. Also, if if we do this and the caller calls `FlutterEngineCollectAOTData`, the AOT mappings will become invalid. So, I think we are working around an error in a specific embedder here.

**Comment by stuartmorgan** [comment]
I'm not clear on what exactly the issue is here. Is the problem that calling `FlutterEngineCreateAOTData` multiple times with the same path doesn't give you fully distinct data instances?

If it is that, I think we should absolutely handle that subtle case at this layer rather than push the (undocumented) need to track that to every embedder.

**Comment by knopp** [comment]
@stuartmorgan, FlutterEngineCreateAOTData multiple times with same path does create fully distinct data instances. The issue here that first time FlutterEngineCreateAOTData is created, this data is used to initialize dart VM. So the first AOT data must be kept alive as long as dart VM is kept alive. Other AOT Data instances can be released.

**Comment by knopp** [comment]
@chinmaygarde

> The data may only be collected after all FlutterEngine instances launched using this data have been terminated.

The problem is, that first embedder AOT data is used by all embeders, because it is used to initialize DART VM. But the embedder has no way of knowing that the AOT data was used to initialize DART VM. So how does it know that it can not collect that particular AOT data?

**Comment by knopp** [comment]
Btw. This crash also happens on Windows. So I don't think this can be considered an embedder bug. On desktop only macOS is unaffected, possibly because it doesn't use the ELF loader.

**Comment by stuartmorgan** [comment]
> FlutterEngineCreateAOTData multiple times with same path does create fully distinct data instances. The issue here is that first time FlutterEngineCreateAOTData is created, this data is used to initialize dart VM.

Ah, that's even worse then. That is definitely not consistent with the documented lifetime requirement. And even if it were documented, that would be awful behavior to force every embedder to track.

**Comment by chinmaygarde** [comment]
Ok, I am convinced this is a bug that is hard to reason about for the embedder as currently implemented. We might need to expose a way to tell the embedder when the AOT mappings are no longer in use.

**Comment by knopp** [comment]
What are the benefits of having embedder being responsible for this compared to transparently refcounting the data if used  for the VM? The PR solves the problem without needing any changes in the embedder.

**Comment by chinmaygarde** [comment]
The original intent was that it was hard for the engine to know how to get rid of the data mapping. If the AOT data is part of a shared library, then a `dlclose` would be required. It it's from a file mapping with `PROT_EXEC`, then an `munmap` would be necessary. On Fuchsia, its a VMO that needs to be closed using a separate call. So, it's not that the engine can't reference count, it's about what to do when the engine loses its last reference. So, it was decided that the embedder could just explicitly control it.

> The PR solves the problem without needing any changes in the embedder.

Well, only for embedders that never call `FlutterEngineCollectAOTData` right?

**Comment by knopp** [comment]
> The original intent was that it was hard for the engine to know how to get rid of the data mapping. If the AOT data is part of a shared library, then a `dlclose` would be required. It it's from a file mapping with `PROT_EXEC`, then an `munmap` would be necessary. On Fuchsia, its a VMO that needs to be closed using a separate call. So, it's not that the engine can't reference count, it's about what to do when the engine loses its last reference. So, it was decided that the embedder could just explicitly control it.
> 
> > The PR solves the problem without needing any changes in the embedder.
> 
> Well, only for embedders that never call `FlutterEngineCollectAOTData` right?

Not sure what you mean. Both embedders that suffer from this (Windows and Linux) call `FlutterEngineCollectAOTData`. What changes is that instead of deleting data in `FlutterEngineCollectAOTData`, in the PR the data is unreffed unreffed. Normally it is the same (as only one reference exists), but for the initial data the VM will hold another reference.

**Comment by knopp** [comment]
This got closed by accident. Reopening as it is still relevant.

**Comment by knopp** [comment]
@chinmaygarde, any chance to re-review this? In current state the embedder gets raw pointer to AOT Data (which is a `unique_ptr`) which is destroyed in `FlutterEngineCreateAOTData`. The PR changes this so that the AOT data is intrusively ref counted. The embedder gets one reference, unreffed in`FlutterEngineCreateAOTData`, and the VM will keep another reference (but only to first isolate AOT data, used to create the VM). This change should be completely transparent to the embedder, need to API change and should take care of the issue.

**Comment by Hixie** [comment]
Spoke with @chinmaygarde about this and I think the conclusion is that while the problem here is real, this is not the way to fix it. I recommend discussing this on #hackers-engine in the Discord.

I'm going to close this PR for now since we're not likely to land this specific fix. Feel free to reach out to me if this is the wrong thing to do. Thanks!

**Pull request closed without merging**
