### PR TITLE
Improve performance of Locale.toString

### PR DESCRIPTION
**Pull request by jason-simmons**
Use a map instead of a switch to replace deprecated language and country codes.
Also cache the result for the most recently used locale.

### CODE REVIEW

**Comment by Hixie** [comment]
What's the measured improvement? Can we create a benchmark to make sure we don't regress it?

**Comment by jason-simmons** [comment]
This showed up in some application profiler traces because `Locale.toString` is called by `ParagraphBuilder._pushStyle` during construction of any text object.  The overall effect on performance is minor, but the switch statement in the old implementation and the repeated recomputation of `toString` on the same locale are unnecessary overhead.

**Comment by Hixie** [comment]
@jason-simmons did we confirm that the new design is actually faster? (I've been bitten before on this project by cases where code I added to make things faster actually made things slower.)

**Comment by jason-simmons** [comment]
Yes - I've measured this on Android devices as well as an embedded device

**Pull request merged**
