### PR TITLE
Add bcrypt.lib as a lib dependency to unbreak dart roller.

### PR DESCRIPTION
**Pull request by aam**
bcrypt.lib dependency was added in https://dart.googlesource.com/sdk/+/1731050b29097b7b40d208ec1658f6f20737d276

### CODE REVIEW

**Comment by a-siva** [comment]
Why not add it to build/config/BUILD.gn in flutter/buildroot instead of having to repeat it at so many places.

**Comment by a-siva** [comment]
see https://github.com/flutter/buildroot/pull/458

**Comment by aam** [comment]
> Why not add it to build/config/BUILD.gn in flutter/buildroot instead of having to repeat it at so many places.

They asked to not to do that there: `# Please don't add more stuff here.`

**Comment by a-siva** [comment]
> > Why not add it to build/config/BUILD.gn in flutter/buildroot instead of having to repeat it at so many places.
> 
> They asked to not to do that there: `# Please don't add more stuff here.`

Since the Dart VM is a base unit that is almost always linked into every executable built I would probably make an exception to that comment for this case.

**Comment by chinmaygarde** [comment]
I agree with @a-siva that this can probably go into the buildroot. But, adding to the `libs` directly or via a public config from that target in `//third_party/dart` that uses this library should make it so that no GN rules in Flutter need to be updated right?

**Comment by aam** [comment]
Yeah, you're right @chinmaygarde. https://dart-review.googlesource.com/c/sdk/+/201580 might be a better fix that won't require changes to the engine.

**Pull request closed without merging**
