### PR TITLE
Impeller: Another quick removal of implicit conversions.

### PR DESCRIPTION
**Pull request by gaaclarke**
Was working with the gradient code and noticed this as well, might as well update it for better performance.

issue: https://github.com/flutter/flutter/issues/122324

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jonahwilliams** [comment]
According to https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Literals

> A numeric literal that uses a decimal is by default of type float. To create a float literal from an integer value, use the suffix f or F as in C/C++.

So i don't think you need the `f` specifier. Does malioc show a diff on this?

**Comment by gaaclarke** [comment]
> According to https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Literals
> 
> > A numeric literal that uses a decimal is by default of type float. To create a float literal from an integer value, use the suffix f or F as in C/C++.
> 
> So i don't think you need the `f` specifier. Does malioc show a diff on this?

Nope, there's no difference with the `f`, just force of habit.  The changes are in the int->float in them mirroring branch.

**Comment by jonahwilliams** [comment]
If there was a malioc diff the linux shard would have failed - but it passing indicates to me that we aren't doing any conversions in this code - at least not in the compiled version.

**Comment by gaaclarke** [comment]
Hmm, I find that hard to believe.  CI can't retrieve the output from the malioc diff: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/26307/overview

Shouldn't it only fail if there is a regression?

**Comment by jonahwilliams** [comment]
No, it uses a golden checked in file. So if anything changed it would fail. What happens when you run it locally?

**Comment by jonahwilliams** [comment]
I mean I'm fine with the PR as is, but I don't think we should be spending time worrying about whether we're using decimals everywhere if its not improving performance

**Comment by gaaclarke** [comment]
Yep, looks like the compiler can do the optimization from int literal to float in this case.  I'm fine dropping this until we get the compilation flag.  Since I changed it I was thinking I'm submit it.

**Pull request closed without merging**
