### PR TITLE
Run Flutter on iOS and Android with color correct Skia

### PR DESCRIPTION
**Pull request by mattsarett**
***Turns on color correct rendering for Android and iOS
    ***Communicates dst color space to raster cache
    ***Turns on color space aware image decoding
    
    Test:
    ***color_testing_demo on Pixel XL
    ***flutter_gallery on iPad Mini and iPad Pro (haven't figured out how to run manual_tests on iOS)
    
    TODO:
    I needed to split up this CL somewhere. These are follow-up tasks.
    ***Make desktop backends color correct
    ***Make debugging tools (ex: encoding frames to png) preserve color space
    ***Investigate using UIKit API to allow iOS to fine tune color space of rendered content

### CODE REVIEW

**Comment by mattsarett** [comment]
Alright let's try this again :).

I've added a null check for canvas in layer_tree, I think this should fix the crash in the software rasterizer.

@brianosman @liyuqian

**Comment by mattsarett** [comment]
@chinmaygarde

**Comment by mattsarett** [comment]
Ahh ok, thanks for the update.

**Comment by mattsarett** [comment]
I've prepared another branch that handles some of cases I left as TODOs:
*Color correct Android software backend
*Color correct mac desktop backend
*Respecting color space when converting frames to PNG
*Minor Vulkan change

I think it makes sense to consider this as a follow-up (since this CL is already not small), but we also have the option to include it in this PR.
https://github.com/mattsarett/engine/tree/srgb2

**Comment by chinmaygarde** [comment]
Just an update. Steady progress is being on https://github.com/flutter/flutter/issues/10510 to enable this patch to be built by our buildbots.

**Comment by mattsarett** [comment]
Thanks!  I appreciate your and Chris' help with this.

**Comment by cbracken** [comment]
FYI flutter/flutter#10510 is now resolved. Engine builds. Framework with the new engine builds and passes. We should be good to go here. Thanks for your patience! :)

**Comment by Hixie** [comment]
This patch is being reverted in #3775.

It caused a device hard crash on the flutter_gallery_ios__transition_perf benchmark on certain iOS devices (notably iPod Touch 6th gen with iOS 10.3.1 and iPhone 6 with iOS 10.3.2). We suspect it also caused a high-profile regression with Android emulators (https://github.com/flutter/flutter/issues/10617).

**Pull request merged**
