### PR TITLE
Include internal Dart libraries in sky_engine.

### PR DESCRIPTION
**Pull request by pylaligand**
This allows analysis to succeed. Otherwise we're seeing errors on List which does not appear as Iterable in core/list.dart unless one has knownledge of EfficientLengthIterable which is defined in internal/internal.dart.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
We faced a similar issue that was caused by a mismatch between the Dart SDK version used on the host for the analysis and the Dart VM version used by the engine (these are not updated in lockstep). My guess is that you need to update the Dart SDK version you are using. So this change should not be necessary.

@johnmccutchan might have more insights however. I am trying to find the ticket that detailed the issue we ran into earlier.

**Comment by johnmccutchan** [comment]
This change treats 'dart:_internal' like all the other 'dart:' libraries. LGTM.

**Comment by pylaligand** [comment]
I tried to remove the "dart:_internal" line, but as expected there was no fallback to the Dart SDK's version.

Note that this is only becoming a problem now because part of the internals are now bleeding into the public API (List being an Iterable). Here's the change that caused the issue: https://github.com/dart-lang/sdk/commit/7957a1c2562ae4398ac05e5b36b3df06fff423a9

**Comment by pylaligand** [comment]
Added some comments @Hixie.

**Comment by pylaligand** [comment]
LG for everybody?

**Comment by abarth** [comment]
LGTM

**Pull request merged**
