### PR TITLE
Bump Robolectric to 4.8.1

### PR DESCRIPTION
**Pull request by utzcoz**
1. Bump sdk to 32.
2. Remove icu4j from testImplementation because Robolectric has a higher icu4j dependency.
3. Fix `PlatformViewsControllerTest#disposeNullAndroidView` with Robolectric 4.8.x.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by utzcoz** [comment]
Before Robolectric 4.8, Surface#lockHardwareCanvas will throw
exception at PlatformViewWrapper#setTexture, because Robolectric
doesn't support to shadow Surface#lockHardwareCanvas, and it
uses real Android logic with native pointer address is 0.
This failure will ensure embeddedView's parent is null, because
PlatformViewsController#createForTextureLayer will fail because
of previous mentioned error, and PlatformViewsController#createForTextureLayer
will not add embeddedView to wrapperView. So this test can pass.
From Robolectric 4.8, it supports to shadow Surface#lockHardwareCanvas
and it can pass with default true valid value, and
PlatformViewsController#createForTextureLayer will run correctly
and add embeddedView to wrapperView, and initializePlatformViewIfNeeded
will fail because embeddedView's parent is not null. So adding a new shadow
class called ShadowReleasedSurface to simulate previous
Surface#lockHardwareCanvas failure to ensure this test can work with
Robolectric 4.8 and later versions. But it is just a workaround,
the root cause is this test case depends on just-failure behavior of
Surface#lockHardwareCanvas in old Robolectric.

**Comment by utzcoz** [comment]
Hi @blasten , @jason-simmons , could you help to review this PR? Thanks.

**Review by chinmaygarde — APPROVED** [review]

**Comment by utzcoz** [comment]
Hi @jason-simmons , I saw you added a new commit to revert it, does it cause new problem? I can try to fix it.

**Comment by jason-simmons** [comment]
The Robolectric tests were failing in the CI environment

Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/16477/overview

**Comment by utzcoz** [comment]
Thanks. I will test it locally, and try to re-land it again.

**Comment by utzcoz** [comment]
@jason-simmons The failed tests are added at e986f43abf1 after my PR. I will try to resolve it compatibility on Robolectric 4.8.1.

**Pull request merged**
