### PR TITLE
Rename first frame method and notify FlutterActivity when full drawn (#38714 #36796).

### PR DESCRIPTION
**Pull request by matthew-carroll**
#38714: Rename first frame method

#36796: Notify FlutterActivity when fully rendered 

#36889: Reset `isDisplayingFlutterUi` when a FlutterEngine is detached from a FlutterView 

I also took this opportunity to refactor some of the rendering listener configuration and how `FlutterRenderer` interacts with its `RenderSurface`. 

I removed the rendering listeners from `FlutterSurfaceView` and `FlutterTextureView` because whoever is using them must also have a reference to a `FlutterRenderer`, which is the source of truth for when rendering starts/stops.

Previously, a convoluted two-way relationship existed between `FlutterRenderer` and `RenderSurface` without any apparent benefit. I've simplified that relationship.

**DO NOT MERGE UNTIL AFTER 1.9 IS CUT**

### CODE REVIEW

**Comment by matthew-carroll** [comment]
> the FireBase Testlab test you updated will exercise this on post submits to the engine. 

The unit test suite is running post submit and not pre submit?

> It's good to have a more focused test too though so that we know exactly where things went wrong if they do go wrong :)

Can you describe the kind of test that would be more focused than the unit tests I added?

**Comment by dnfield** [comment]
Yes, firebase is poatsubmit only.

My comment was intended to point out the value of your tests.  They're great!

**Comment by matthew-carroll** [comment]
Oh ok, so @dnfield just to make sure I understood, that wasn't a request for a change, just a note?

I think maybe I also misunderstood the firebase part. Are the unit tests run in the firebase testlab and that's why they're post submit? Or were you saying that other tests (like e2e tests) are run in firebase, therefore these unit tests are valuable from as a presubmit check?

**Comment by dnfield** [comment]
haha sorry, rereading what I wrote and I can see the confusion.

I'm not requesting any changes.  The Firebase test only runs post submit - we could probably make it run presubmit again at some point though.  Either way, the unit test is really good because it will help identify regressions around this more precisely, whereas the firebase test could fail for any number of reasons.

**Comment by matthew-carroll** [comment]
Ok, sounds good. Glad we got it sorted out. Thanks for the input :)

**Comment by xster** [comment]
cc @RedBrogdon since you wanted to follow along

**Comment by xster** [comment]
LGTM

**Comment by matthew-carroll** [comment]
CC @adazh This API change will probably require Espresso updates for being notified of when rendering starts. It should just be a name change for the Espresso side.

**Comment by matthew-carroll** [comment]
Merging with LUCI red because infra says that's a mistake.

**Pull request merged**
