### PR TITLE
Make `flow/...` compatible with `.clang_tidy`.

### PR DESCRIPTION
**Pull request by matanlurey**
Work towards https://github.com/flutter/flutter/issues/134969.

All changes were made automatically (i.e. with `--fix`).

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM!

**Comment by bdero** [comment]
Looks like the tool may have missed a few spots

**Comment by matanlurey** [comment]
@bdero Please re-review after a few changes :)

**Review by bdero — APPROVED** [review]
LGTM!

**Comment by stuartmorgan** [comment]
test-exempt: helps unblock turning on a check that will automatically enforce the change

**Pull request merged**
