### PR TITLE
Add //flutter/content_handler

### PR DESCRIPTION
**Pull request by abarth**
We're now producing a flutter_content_handler binary for Fuchsia that
builds and links.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by abarth** [comment]
There's no GL on Fuchsia yet, so we need to be careful to isolate the GL dependencies.

**Comment by chinmaygarde** [comment]
lgtm. Will be more vigilant about OpenGL in flow.

**Comment by abarth** [comment]
We might want to create a directory in flow to hold the code that depends on GL.  That's a good practice anyway if we want to eventually support vulkan.

**Comment by abarth** [comment]
Thanks for the reviews.

**Comment by chinmaygarde** [comment]
> We might want to create a directory in flow to hold the code that depends on GL.

Will do. So far, its been limited to the IO thread resource loading.

**Pull request merged**
