### PR TITLE
Remove obsolete fl_keyboard_view_delegate_get_messenger

### PR DESCRIPTION
**Pull request by robert-ancell**
This is unnecessary - we already have the messenger.

### CODE REVIEW

**Review by cbracken — COMMENTED** [review]
Seems like the tests are unhappy.

Animated GIF of a delivery truck approaching a highway overpass, then failing to meet the height clearance requirement and crashing into it

**Comment by robert-ancell** [comment]
Yes, investigating this failure... Thought this would be the easy part of a larger patch..

**Comment by robert-ancell** [comment]
Ugh, it because the tests have two different binary messengers in them, this change made it into one. I'm trying to simplify the test code and remove the mixed C++/GObject style that makes it really hard to understand. First part in https://github.com/flutter/engine/pull/54883

**Comment by robert-ancell** [comment]
Now built on top of https://github.com/flutter/engine/pull/55892 this should work (only the last commit should be reviewed).

**Review by cbracken — APPROVED** [review]
Last commit lgtm!

LGTM stamp from a Japanese personal seal

**Pull request merged**
