### PR TITLE
Reland "Run Flutter on iOS and Android with color correct Skia"

### PR DESCRIPTION
**Pull request by mattsarett**
https://github.com/flutter/flutter/issues/10710
https://github.com/flutter/flutter/issues/10617
https://github.com/flutter/flutter/issues/8152

@brianosman

### CODE REVIEW

**Comment by mattsarett** [comment]
Still some things to work out before landing this...

**Comment by Hixie** [comment]
We should really make sure to find a way to automatically test emulators (e.g. in our devicelab) before we land this patch again, so that we can make sure we can catch any problems that we missed last time.

**Comment by Hixie** [comment]
(@yjbanov is the right person to speak to about how to do that.)

**Comment by yjbanov** [comment]
Well, the devicelab caught the iPhone reboots. It's just that it took us some time to realize those were reboots. For emulator testing the tracking issue is https://github.com/flutter/flutter/issues/10718.

**Comment by mattsarett** [comment]
@brianosman will be taking ownership of this, but I've uploaded a third commit per a conversation with @chinmaygarde - in case it is a useful test to look at when setting up instrumented builds.

The iOS reboots (https://github.com/flutter/flutter/issues/10710) occur with the first two commits, but are strangely fixed by the third one "Use bare ptr to SkColorSpace on PrerollContext struct".

**Comment by yjbanov** [comment]
@mattsarett what was the original motivation behind switching to bare pointers?

**Comment by mattsarett** [comment]
Nothing in particular.  In chasing this bug around, Brian and I noticed that it seemed to be triggered by the changes to flow/, in particular by plumbing the SkColorSpace through to the raster cache.  We currently don't have a logical explanation for why this helps.

**Comment by brianosman** [comment]
With @mattsarett leaving, I'm planning to take over this PR. I've got my own version that includes the first two commits from this, plus another bugfix at #3818.

**Pull request closed without merging**
