### PR TITLE
Copy canvaskit files directly into `flutter_web_sdk`

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
Since the flutter tool now always looks inside the `flutter_web_sdk` artifact for canvaskit/skwasm files, we should copy them to their expected location inside the flutter_web_sdk, so that `--local-web-sdk` works correctly when targeting a local build.

### CODE REVIEW

**Review by hterkelsen — APPROVED** [review]
LGTM

**Review by yjbanov — APPROVED** [review]
lgtm

**Review by mdebbar — APPROVED** [review]

**Comment by alexmarkov** [comment]
This change broke Dart/Flutter HEAD-HEAD-HEAD bot.

It caused the following GN errors during "gn --full-dart-sdk --no-prebuilt-dart-sdk" step:

```
Generating GN files in: out/host_debug
ERROR Input to target not generated by a dependency.
The file:
  //out/host_debug/skwasm.wasm
is listed as an input or source for the target:
  //flutter/third_party/canvaskit:skwasm_group
but no targets in the build generate that file.

ERROR Input to target not generated by a dependency.
The file:
  //out/host_debug/skwasm.worker.js
is listed as an input or source for the target:
  //flutter/third_party/canvaskit:skwasm_group
but no targets in the build generate that file.

If you have generated inputs, there needs to be a dependency path between the
two targets in addition to just listing the files. For indirect dependencies,
the intermediate ones must be public_deps. data_deps don't count since they're
only runtime dependencies. If you think a dependency chain exists, it might be
because the chain is private. Try "gn path" to analyze.

2 generated input errors found.
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8784588539471655729/+/u/gn_--full-dart-sdk_--no-prebuilt-dart-sdk/stdout

https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux/19512

**Comment by eyebrowsoffire** [comment]
@alexmarkov Fix for that issue is here: https://github.com/flutter/engine/pull/40967

**Pull request merged**
