### PR TITLE
Move constant definitions out embedder.h

### PR DESCRIPTION
**Pull request by stuartmorgan**
Constant values should generally not be defined in headers. As currently written, multiple files including this header will cause link errors as the symbols are redeclared in each file with external linkage.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
(If for some reason the value absolutely must be in the header, we probably want a `#define`; declaring them `static` would address the link error, but is potentially dangerous in some edge cases.)

**Comment by jamesderlin** [comment]
> (If for some reason the value absolutely must be in the header, we probably want a `#define`; declaring them `static` would address the link error, but is potentially dangerous in some edge cases.)

Or use `enum`.

**Comment by GeertJohan** [comment]
Since the value itself is part of the API "contract", it may make sense to use enum like other `kValues` in the header file. If that's possible, since the enum value must still be declared `-1` to be compatible?

This would then make it easy to use the value while only including the embedder.h file.

**Comment by stuartmorgan** [comment]
> Since the value itself is part of the API "contract"

Chris will need to weigh in on that; it's not clear to me that it is.

**Comment by cbracken** [comment]
There's no reason at all the value needs to be in the header; these should definitely have been declared `extern` initially.

**Comment by chinmaygarde** [comment]
Can you add a check so that this sort of thing gets caught at build time? We have an `embedder_include.c` that acts as a sanity check to make sure the header can be included in a C context. I suggest adding an `embedder_include2.c` and preparing an executable target that gets built in the default rules. The linker will trip on errors like this.

**Pull request merged**
