### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by mit-mit**
Synchronize with https://github.com/flutter/flutter/pull/26285

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like the license script is not happy with this change. After you re-generated `sky/packages/sky_engine/LICENSE` can you check that this change doesn't increase its size?

**Comment by chinmaygarde** [comment]
Is this still being worked on? Can we update or close the PR? Trying to clear the PR queue. Thanks.

**Comment by mit-mit** [comment]
Yes, this PR is still relevant.

@goderbauer I don't know what the license script is, or how it works. Where can I learn more?

**Comment by goderbauer** [comment]
https://github.com/flutter/engine/blob/master/tools/licenses/README.md should have all the information you need.

**Comment by mit-mit** [comment]
Abandoned, new attempts in https://github.com/flutter/engine/pull/7611

**Pull request closed without merging**
