### PR TITLE
Some cleanups enabled by removing support for Dart 1.

### PR DESCRIPTION
**Pull request by rmacnak-google**
- Switch core snapshot to Dart 2 and remove support for loading platform.dill.
 - Remove support for loading script snapshots.
 - Remove settings and fix names to reflect the above.
 - Remove support for loading the service isolate from source.

### CODE REVIEW

**Comment by rmacnak-google** [comment]
FYI @cbracken

**Comment by jason-simmons** [comment]
LGTM

The commit message should say "removing support for Dart 1"

**Comment by a-siva** [comment]
Is this PR still active?

**Comment by rmacnak-google** [comment]
Yes. Chris is working on removing some lingering use of Dart 1 in some host side tool (IIRC) and the engine's unit tests. This can land after that work is done.

**Comment by cbracken** [comment]
De-dart-1-ification is pending a fix to get Fuchsia tests working in kernel mode [FL-66](https://fuchsia.atlassian.net/browse/FL-66), which requires a series of fixes to get the frontend server available as part the SDK.

**Comment by chinmaygarde** [comment]
Can we land/close this? Just clearing the queue.

**Comment by cbracken** [comment]
As of this morning, all the blockers for this are cleared. I've got a flutter_tools PR to land first, then will rebase and re-land.

**Comment by rmacnak-google** [comment]
Waiting on removal of use of Dart 1 by engine unit tests.

**Comment by chinmaygarde** [comment]
> Waiting on removal of use of Dart 1 by engine unit tests.

Oh wait. I added these. @cbracken: Is this the only remaining blocker? I can work on migrating the unit tests.

**Comment by rmacnak-google** [comment]
Ping. PTAL.

**Comment by cbracken** [comment]
lgtm

**Comment by cbracken** [comment]
This is the final nail in the coffin of flutter/flutter#17051.

**Pull request merged**
