### PR TITLE
[Impeller] Assign subpass depth on restore rather than creation.

### PR DESCRIPTION
**Pull request by bdero**
The subpass depth is used for drawing the texture to the parent pass. So it needs a depth > all of the clips contained within the subpass.

Also correct the way we're assigning the depth value in shaders.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by bdero** [comment]
This is a bit wacky, but the pipelines seem to be getting an alternative depth write compare options on all the backends on just CI somehow. It's happening for all 3 backends so the issue is going to be a high level thing. I'll probably figure it out after a couple more print debugging iterations.

Might scatter around a few more sensible debug time checks while I'm at it as well since there's some potential for subtle mistakes that are hard to debug.

**Comment by bdero** [comment]
(errors on CI right now are just due to my print debugging)

**Comment by bdero** [comment]
I had missed a couple of spots when initially distributing the depth to the shaders, and the previous behavior of passing the depth through the ortho projection was covering it up.

**Review by jonahwilliams — APPROVED** [review]
Still LGTM

**Pull request merged**
