### PR TITLE
Fix the encoding of TextStyle and ParagraphStyle

### PR DESCRIPTION
**Pull request by Hixie**
We were off by one on, uh, everything.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
hold on

**Comment by abarth** [comment]
I think this was right before your patch.

**Comment by Hixie** [comment]
PTAL. I got confused by the toStrings, which are what was actually wrong.

**Comment by abarth** [comment]
Ah, LGTM

**Pull request merged**
