### PR TITLE
Roll to branched dart sdk with two more hotfixes for flutter 1.5.4.

### PR DESCRIPTION
**Pull request by aam**
Cherry-picks for https://github.com/flutter/flutter/issues/29007 and VERSION file bump.

### CODE REVIEW

**Comment by aam** [comment]
cc @athomas

**Comment by tvolkert** [comment]
Looks like this needs a license signature update

**Comment by aam** [comment]
> Looks like this needs a license signature update

Done

**Comment by tvolkert** [comment]
The Dart version bump to `2.3.0` could be problematic because it'll mean that Flutter `v1.5.4-hotfix.[n]` will report a newer Dart version than `v1.5.5`-`v1.y.z` (where `y` and `z` are probably already bounded, but I didn't take the time to look them up).  If any of those versions ever make it to stable, it'll potentially mess with the SDK constraints of pub packages.

**Comment by aam** [comment]
> The Dart version bump to `2.3.0` could be problematic because it'll mean that Flutter `v1.5.4-hotfix.[n]` will report a newer Dart version than `v1.5.5`-`v1.y.z`

VERSION update should not change version dart sdk that flutter reports(has been reporting). dart sdk built in flutter doesn't use VERSION file - instead it looks up value from the tag.

**Comment by tvolkert** [comment]
Gotcha - what's the significance of the `VERSION` file bump?

**Comment by aam** [comment]
> Gotcha - what's the significance of the `VERSION` file bump?

Hm, not sure... @Hixie requested it, need to check with him.

**Pull request merged**
