### PR TITLE
Allow EdgeDims to be scaled via multiply operator (for AnimatedValue compatibility)

### PR DESCRIPTION
**Pull request by apwilson**

### CODE REVIEW

**Comment by Hixie** [comment]
If you implement operator* you should also implement operator/, operator~/, and operator%.
Might also be good to implement `static EdgeDims lerp(EdgeDims a, EdgeDims b, double t)` while we're at it.
Also we should probably add some tests... 

Happy to take this PR over if you don't want to do all that.

**Comment by apwilson** [comment]
Yeah you can take it over.  I'm not sure what it would mean to ~ or % an EdgeDims.  In reality if we implement lerp we don't need to implement the * operator anymore as that was  required by the original AnimatedValue lerp.

**Comment by Hixie** [comment]
k, will do

**Comment by Hixie** [comment]
moving to #1445

**Pull request closed without merging**
