### PR TITLE
Fix detection of Mac target specification as a host build.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/108485

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @zanderso since you authored the patch.

**Review by gaaclarke — APPROVED** [review]
This is an improvement over the status quo.  I think there is other work we should do that makes the host and the `--mac` build different though.  That can be addressed in the future.

**Comment by chinmaygarde** [comment]
Can you file an issue for that? I was thinking of the opposite of just having --mac be the default with no host variant.

**Comment by zanderso** [comment]
Does building on an arm64 mac still work with this patch?

**Comment by chinmaygarde** [comment]
> Does building on an arm64 mac still work with this patch?

Really can't say without access to a device right now or on CI. I expect so since this patch fixes just the build with the `--mac` flag. And, if I am reading that code correctly, we need emulation on Mac still right?

But yeah, we should wire this up on CI to be sure. I have an M2 device on order to test by my desk too.

**Pull request merged**
