### PR TITLE
Fix broken ci/format -f

### PR DESCRIPTION
**Pull request by mtolmacs**
[Previous PR of mine](https://github.com/flutter/engine/pull/34374) broke the in-place fixing for the format checker.

### Issues
* Fixes flutter/flutter#107920

### Changes in the [flutter/tests] repo
No changes.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gspencergoog** [comment]
We really need some tests here. Could you add a small Dart test that applies a formatting fix? It should go into a new `test` directory, and mock out the ProcessManager, to avoid interactions with the CI environment. There's an example of faking out the ProcessManager in [the Flutter repo](https://github.com/flutter/flutter/blob/6abd3691c364bbe5580696d4c0407188eb710d97/dev/devicelab/test/running_processes_test.dart#L88). I realize that's a bigger ask than the code change here, but If we'd had a test for that before, your previous PR wouldn't have broken things.

**Review by chinmaygarde — APPROVED** [review]
This is breaking development on head. Let's land this now and file an issue for a test harness.

**Review by jason-simmons — APPROVED** [review]

**Comment by mtolmacs** [comment]
Note to self: On Windows switching a target file to LF line endings breaks the `git apply` command, but without it the `git diff` in non -f mode wants to replace the whole file.

**Comment by mtolmacs** [comment]
flutter/engine#34884 will contain this patch

**Pull request closed without merging**
