### PR TITLE
Fix --no-prebuilt-dart-sdk build

### PR DESCRIPTION
**Pull request by zanderso**
Fix for previous commit https://github.com/flutter/engine/pull/46440

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Comment by jason-simmons** [comment]
I had started looking at this, and IIUC the `packages` parameter in `dart_action` will add a `--packages` flag to the Dart command line (making it redundant with `packages_args`.

So I'd suggest:
* remove `packages_args`
* for the prebuilt Dart SDK case, add the packages file to `inputs` and the `--packages` flag to `args` if `package_config` is defined
* for the non-prebuilt case, set the `packages` parameter in `dart_action`

**Comment by jason-simmons** [comment]
Also, after applying the fix I'm still seeing errors when configuring an Android build with `--no-prebuilt-dart-sdk`:

```
ERROR Unresolved dependencies.
//flutter/flutter_frontend_server:frontend_server(//build/toolchain/android:clang_arm)
  needs //flutter/build/dart:dart_sdk(//build/toolchain/android:clang_arm)
```

**Comment by zanderso** [comment]
@jason-simmons Good catch. I've updated the PR.

**Comment by jason-simmons** [comment]
With this patch I'm still seeing errors when building a 32-bit `android_debug_unopt` target on an x64 host.

When it builds the scenario app snapshot, the frontend server fails with:
```
output: VM initialization failed: JIT cannot simulate target architecture with different word size than host
```

**Comment by zanderso** [comment]
It turns out that when not using the prebuilt Dart SDK, we were previously running the frontend server from source. I've updated this patch to go back to that behavior. Thanks, Jason!

**Comment by zanderso** [comment]
Will merge this into the reland of https://github.com/flutter/engine/pull/46863

**Pull request closed without merging**
