### PR TITLE
Enabled hiding the home indicator with SystemChrome.setEnabledSystemUIOverlays

### PR DESCRIPTION
**Pull request by gaaclarke**
relevant issue: https://github.com/flutter/flutter/issues/20965

### CODE REVIEW

**Comment by gaaclarke** [comment]
> Implementation LG. Can we add a test? I think this will work in scenario. Mock dart sends a channel message, sets expectation on view controller.

added a unit test

**Comment by xster** [comment]
LGTM, thanks

**Comment by gaaclarke** [comment]
Landing, Github says there are tasks pending, but if you click on the details they have succeeded.

**Comment by jockebq** [comment]
Is this active on the latest flutter release? (1.18.0-dev.5.0) Or how do I make use of this? Having the same issue.

**Comment by gaaclarke** [comment]
@jockebq it's available in 1.18.0-dev.5.0 and later.

**Comment by jockebq** [comment]
@gaaclarke I just tested it out, and it seems to work in landscape, but not in portrait. And I am having issues with filling the screen with the content on my flutter_webview_plugin.
bild
bild

**Comment by gaaclarke** [comment]
@jockebq if you think you've found a bug can you file a new bug please with reproduction steps and expected / versus observed results?

Heads up, iOS doesn't provide a definitive way to hide the home indicator.  You can request it to hide and it will take that preference into consideration.  See https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden?language=objc for more info.

**Pull request merged**
