### PR TITLE
switch the dart sdk used for lib/web_ui analysis

### PR DESCRIPTION
**Pull request by devoncarew**
- switch the dart sdk used for lib/web_ui analysis

This PR switch the Dart SDK used for web_ui analysis from the one in `out/host_debug_unopt/dart-sdk` to the one brought in via deps (`third_party/dart/tools/sdks/dart-sdk`). This matches the sdk used in https://github.com/flutter/engine/blob/master/ci/analyze.sh, but more importantly it means that we can analyze the repo without having to run a build step - this will let us perform presubmit checks of this repo in the dart-lang/sdk CI.

I'm not 100% who the best reviewer is here; I'm the most recent person on the blame list.

### CODE REVIEW

**Comment by zanderso** [comment]
I think I'm not sure I understand all the implications of this change, but we also use the checked-in Dart SDK to analyze `lib/ui`. Thinking about it now, I'm wondering if that's the right thing to do. It means that we're analyzing one side of the `dart:ui` boundary with the (older) checked-in SDK, but then `dart:ui` clients like in `flutter/flutter` are being analyzed with the Dart SDK vended by the engine repo, which is usually much more recent.

It is maybe a question for @devoncarew what the pros/cons are of analyzing two sides of an API boundary with different versions of the analyzer.

**Comment by devoncarew** [comment]
> I think I'm not sure I understand all the implications of this change, but we also use the checked-in Dart SDK to analyze `lib/ui`. Thinking about it now, I'm wondering if that's the right thing to do. It means that we're analyzing one side of the `dart:ui` boundary with the (older) checked-in SDK, but then `dart:ui` clients like in `flutter/flutter` are being analyzed with the Dart SDK vended by the engine repo, which is usually much more recent.
> 
> It is maybe a question for @devoncarew what the pros/cons are of analyzing two sides of an API boundary with different versions of the analyzer.

Ah, good question. With this PR I was more focused on removing built steps we need to do before analysis - so the presubmits I'm working on for dart-lang/sdk have less to do - and, bringing web_ui and ci/analyze.sh into agreement.

But thinking about it, it's much less useful to know about failures from analysis changes a few weeks ago (from the checked in SDK) and much more useful to know about ones just introduced. We should likely switch both here and ci/analyze.sh to using 
`out/host_debug_unopt/dart-sdk`.

**Comment by devoncarew** [comment]
From the failure on the bot, it looks like `out/host_debug_unopt/dart-sdk` does not yet exist when calling ci/analyze.sh. I assume I'll need to do some build recipe changes to ensure the sdk is built before we try and analyze?

**Comment by dnfield** [comment]
I was talking with @zanderso about this yesterday - I think we could make this work a little better if we moved analysis/linting to build rules rather than as one-off shell scripts invoked by CI. That way we could properly depend on whatever targets are needed.

It would probably be good to introduce new GN args for that like `lint` or something, so that CI can selectively avoid running linting on every build though.

**Comment by dnfield** [comment]
To get you unblocked for now I'll update the recipe ordering so you can use the unopt build.

**Comment by dnfield** [comment]
Scratch that, @zanderso is working on using the prebuilt Dart SDK in the recipe which would also unblock this in a better way. I think we should probably just wait for that.

**Comment by devoncarew** [comment]
> if we moved analysis/linting to build rules rather than as one-off shell scripts invoked by CI

OK. Just to clarify - now that I know what's going on wrt analyzing w/ the pre-built SDK, my main goals are:
- making sure that we analyze with the latest analyzer / sdk code, not the checked in sdk, and
- generally setting up analysis in this repo in a way such that we can drive it from the dart-lang/sdk repo, and having it run fast enough that we can have it as a pre-submit (cycling in 10-20 mins)

**Comment by zanderso** [comment]
I'm working on re-landing this change https://flutter-review.googlesource.com/c/recipes/+/15541, which will pull in a prebuilt Dart SDK at the same version that the DEPS file pulls. That will let us analyze the Dart code in the engine repo with an up-to-date Dart SDK without needing to build one first.

After that, if analyze.sh is looking for the analyzer in `out/host_debug_unopt/dart-sdk`, it doesn't have to be populated by the engine build. Rather, it could be populated in the Dart presubmit by copying from a tip-of-tree dart-lang/sdk build.

We could update the recipe now, and then I can make it faster later when I reland my prebuilt SDK CL.

**Comment by devoncarew** [comment]
> That will let us analyze the Dart code in the engine repo with an up-to-date Dart SDK without needing to build one first.

OK, that sounds great.

> After that, if analyze.sh is looking for the analyzer in out/host_debug_unopt/dart-sdk, it doesn't have to be populated by the engine build. Rather, it could be populated in the Dart presubmit by copying from a tip-of-tree dart-lang/sdk build.

Yup, we can patch things up enough for the pre-submit to work.

> We could update the recipe now, and then I can make it faster later when I reland my prebuilt SDK CL.

Update the recipe to build `host_debug_unopt`? That sounds fine, but I'm happy to wait as well, if we have a solution that'll land in the near term.

**Comment by devoncarew** [comment]
Closing this, but can you ping me when related recipe changes land?

**Pull request closed without merging**
