### PR TITLE
Expose approximateBytesUsed for Picture

### PR DESCRIPTION
**Pull request by dnfield**
I'd like to cache pictures, and want to be able to have it be memory-aware.

The comment(s) about refed objects would apply to things like `canvas.drawImage()` recorded into the picture.

The method already exists in the C++, just isn't exposed to the Dart side (yet).

### CODE REVIEW

**Comment by chinmaygarde** [comment]
I like it. Maybe we should put this on the base Dart wrappable itself. Having this on the picture itself isn't very useful right now because the bulk of the allocation will be in the images referenced by the picture.

cc @abarth, @cbracken: WDYT?

**Comment by dnfield** [comment]
By wrappable you mean on NativeFieldWrapperClass*?

I imagine that would be pretty unreliable - even for this case in a Picture where you might want the size of the vector data + images (+ fonts?), you'd still need to add some kind of plumbing to track that.  But if it can be done it'd be really nice to have.

**Comment by Hixie** [comment]
Having this information for Image would be useful for https://github.com/flutter/flutter/pull/17614.

**Comment by jonahwilliams** [comment]
@dnfield if you are looking into image caching, you should take a look at https://github.com/flutter/flutter/pull/17614.  I have a fairly complete design of the changes needed on the framework side, and I would appreciate any comments, concerns, or criticism.

Anyway, It would probably be a better estimate then width * height * 4.

**Comment by dnfield** [comment]
This is for Picture, not Image

**Comment by jonahwilliams** [comment]
ahh ... my bad

**Comment by dnfield** [comment]
The work you're doing on image is definitely relevant though.  It'd be nice to ultimately have a unified way of dealing with these similarly

**Comment by dnfield** [comment]
@chinmaygarde are you looking for more on this?

If you'd want to somehow include images in this, I don't think there's a way to do that with any public members of Skia today - if you're looking for a more generic solution for getting the size of native objects, that might also have some issues.

I'd still have use for this even without images to manage caching of SVG pictures - if they use images, I'd be able to at least roughly track the size of those separately during processing.  I know that might not help a more general case for the framework, but a similar approach could be taken there (e.g. if you ever rasterize a picture or include rasterized data, you track that rasterized data using `w * h * 4`).

**Pull request merged**
