### PR TITLE
Drop android_sdk_downloader in favor of cipd

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/27967

CIPD was actually much easier to implement for this than I initially thought.  I've created the packages for Linux and Mac here: https://chrome-infra-packages.appspot.com/p/flutter/android

I've also added bash scripts to help with creating new ones in the future.

### CODE REVIEW

**Comment by dnfield** [comment]
This will fail until we either rebuild the GKE container or land #8098

**Comment by jdunn010** [comment]
ran into a problem trying to fetch the ndk dependency. not sure what i am doing wrong, any suggestion much appreciated!

`ubuntu-18.04@ip:~/engine$ gclient sync
Syncing projects: 100% (90/90), done.                                           

________ running 'cipd ensure -log-level error -root /home/ubuntu/engine -ensure-file /tmp/tmpzxvmWX.ensure' in '.'
[P18934 01:31:27.259 client.go:1375 E] cipd: failed to fetch flutter/android/ndk/linux-amd64:4PIz5-1td4npawLNyYi6H15qa0WjEVeY5dBDS68c_SAC - failed to download the package file after multiple attempts
[P18934 01:31:27.290 client.go:1560 E] Failed to install flutter/android/ndk/linux-amd64:4PIz5-1td4npawLNyYi6H15qa0WjEVeY5dBDS68c_SAC - failed to download the package file after multiple attempts
Error: failed to update packages, see the log.
Error: Command 'cipd ensure -log-level error -root /home/ubuntu/engine -ensure-file /tmp/tmpzxvmWX.ensure' returned non-zero exit status 1
`

**Comment by dnfield** [comment]
I've seen that when Google cloud had an issue last week.  Do you have the full logs?

**Comment by jdunn010** [comment]
i think it may actually have been some sort of "user error". I deleted the .cipd directory and re-ran to pull logs for you and it seems to have worked fine! Thanks a lot for such quick response and fixing it! 
This is where it ended up, so I think it is all ok:

`----------------------------------------
________ running '/usr/bin/python src/build/landmines.py' in '/home/ubuntu/engine'
________ running '/usr/bin/python src/tools/dart/update.py' in '/home/ubuntu/engine'
________ running '/usr/bin/python src/flutter/tools/android_support/download_android_support.py' in '/home/ubuntu/engine'
________ running '/usr/bin/python src/tools/buildtools/update.py' in '/home/ubuntu/engine'
Bootstrapping cipd client for linux-amd64...
######################################################################### 100.0%######################################################################### 100.0%
Hook '/usr/bin/python src/tools/buildtools/update.py' took 63.13 secs
________ running '/usr/bin/python flutter/tools/generate_package_files.py' in '/home/ubuntu/engine/src/'
________ running '/usr/bin/python src/tools/remove_stale_pyc_files.py src/tools' in '/home/ubuntu/engine'`

**Comment by dnfield** [comment]
It may have just been a temporary service failure too.  Glad it's working now

**Pull request merged**
