### PR TITLE
[Impeller] Turned on wide gamut support by default.

### PR DESCRIPTION
**Pull request by gaaclarke**
After having run a memory audit on Flutter Gallery I believe we can turn on wide gamut support by default for impeller.  Here are the ramifications of this change:
1) If an opaque surface is used and no transparent wide gamut images are used, there should be no change in performance or memory usage.
1) If a transparent surface is used; the surface will take up 2x memory (ex 4MB on iPhone 7) and will have a runtime performance cost.
1) If wide gamut **transparent** images are used, they will take up 2x memory.  Opaque wide-gamut images will take up the same amount of memory.

### Test 1

Steps:
* Tap "Material"
* Scroll down and back to "Cards"
* Tap "Cards"
* Scroll to bottom of "Cards" example

Notice that the card images are wide gamut, AdobeRGB.

**Memory increase:** 10.401 MB (+8.7%)

### Test 2

Steps:
* Just launch the gallery

Notice that there shouldn't be any wide gamut images.

**Memory Increase:** 1.22 MB (+1%, this is probably a fluke of measurement)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
We're getting to the point where we'll get better testing if we just turn this on.  Anyone that runs into problems can just use the flag to turn it off.

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
I'd want to hold on this. In the last go/impeller-weekly, this was slated for iOS Preview Exit + 1 release. We just landed the Impeller flag flip test run towards the end of last week and are reasoning about the benchmark updates. I don't want to add another variable to those numbers right now. After the branch cut though, this lgtm.

**Comment by chinmaygarde** [comment]
Closing this and putting it in the icebox so its off the triage queue. But we can re-open once the release train leaves.

**Comment by gaaclarke** [comment]
Can I switch it back to a reopen it and switch it back to a draft so it is out of your review queue?  I don't keep track of my closed PRs but drafts I do.

**Comment by gaaclarke** [comment]
I think this is ready now, no?

**Comment by chinmaygarde** [comment]
> I think this is ready now, no?

Yup yup. We discussed this in the last weekly and were waiting for you to be back. Let's land this ASAP. Can you give a heads up in go/flutter-chat when you do so we watch out for memory bench updates?

**Review by chinmaygarde — APPROVED** [review]

**Comment by bernaferrari** [comment]
I'm kind of lost, but does this mean we should have a Color.p3() soon? Not sure what happens to current hex colors, or if this is "images only".

**Comment by gaaclarke** [comment]
> I'm kind of lost, but does this mean we should have a Color.p3() soon? Not sure what happens to current hex colors, or if this is "images only".

There is no plan to make any change to the Color class.  This just effects loading wide gamut images, gradients and reading/writing pixels to `ui.Image`.  You can't specify them when selecting the color of a widget, for example.  We should make an issue for that if people are interested.

**Comment by bernaferrari** [comment]
Oh, ok. Thanks!

**Pull request merged**
