### PR TITLE
Support sendKeyEvent for arrow keys

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/11352

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by Hixie** [comment]
test?

**Comment by jason-simmons** [comment]
We don't currently have a testing environment for Android Java code

**Comment by eseidelGoogle** [comment]
Do we need up and down for multi-line text?  (or any other directions?) :)

**Comment by Hixie** [comment]
Can we add a testing environment for Android Java code? I feel like "we don't have a test environment" should not be an excuse for not writing tests, it should be a reason for us to block further development until we have a test environment.

**Comment by jason-simmons** [comment]
I don't know if any IMEs expose up or down soft keys.  Up and down will be trickier because the text plugin can't just increment/decrement the selection - it will need to calculate the position of the text above or below the current cursor.

**Comment by Hixie** [comment]
Are these APIs async? If so, we might want to just do all the work in Dart, so we can re-use the same logic for iOS and Android, and minimize the work we have to do (and test) in Dart.

**Comment by ds84182** [comment]
GBoard for Android supports up and down navigation. Hit the G at the top left and tap \<I\>.

Currently Up, Down, Home, End, and Selection are unimplemented. See flutter/flutter#9419

**Pull request merged**
