### PR TITLE
Rename SkiaGPUObject::get() to skia_object()

### PR DESCRIPTION
**Pull request by jason-simmons**
This will reduce confusion with sk_sp::get() which returns a raw pointer

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
How about `get_skia_object` just to make it even more explicit?

**Comment by flar** [comment]
> How about `get_skia_object` just to make it even more explicit?

Something that implies that it is still a shared pointer?

**Comment by flar** [comment]
get_sk_sp()?

**Comment by jason-simmons** [comment]
Changed it to `SkiaGPUObject::skia_object()`

Ref counted Skia objects are generally passed around as `sk_sp` smart pointers.

**Comment by flar** [comment]
> Changed it to `SkiaGPUObject::skia_object()`
> 
> Ref counted Skia objects are generally passed around as `sk_sp` smart pointers.

Not always, which was what led to the original mistake - not realizing that the return code was an sk_sp  instead of a raw pointer.

**Comment by chinmaygarde** [comment]
One of the flow unit-tests failed and the error does look related.

**Comment by flar** [comment]
Yes, the layer tests attempt to trigger a known DCHECK and verify that they got the exact string output they were expecting. The assert in the picture layer unit tests used to be for `.get()` but now the assert is for `.skia_object()` so the assert message changed.

**Comment by flar** [comment]
This looks good to go if the unit test is just adjusted to expect `skia_object` instead of `get`

**Review by flar — APPROVED** [review]
LGTM (with fix to unit test)

**Comment by chinmaygarde** [comment]
The failure looks real.

**Comment by flar** [comment]
The failure is real, but it doesn't demonstrate a real problem. The test is just expecting a specific exception by the content of its error message which changed when the assert was modified, so the test's reference string needs to be updated to match the new assert contents.

**Pull request merged**
