### PR TITLE
Roll Dart VM to cfe5e5f075431641642a8e3be2fbd4414eaca1fd.

### PR DESCRIPTION
**Pull request by rmacnak-google**
Picks up changes to include inlined frames and line numbers in AOT stack traces.

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by rmacnak-google** [comment]
@cbracken Updated license expectations

**Comment by cbracken** [comment]
Out with the old, in with the new! Did you run:
```shell
dart lib/main.dart ../../.. > ../../sky/packages/sky_engine/LICENSE
```
as well? It looks like there *might* be updates that remove some old 2012 licences.

**Comment by rmacnak-google** [comment]
Yes. The "removed" 2012 license is because I fixed a typo upstream so it isn't mistaken as a separate license; notice the spurious bracket in the deleted chunk.

**Comment by cbracken** [comment]
Awesome! LGTM.

**Pull request merged**
