### PR TITLE
Roll Skia

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

**Comment by abarth** [comment]
LGTM

We need to update Skia in Fuchsia at the same time.

**Comment by chinmaygarde** [comment]
It seems like @jason-simmons was having issues with `SkSurface_Gpu` not liking a pixel config that was not SRGB. It may be just that one of the non-SRGB formats listed [here](https://github.com/flutter/engine/blob/master/vulkan/vulkan_device.cc#L294) is being returned and surface creation trips on an assert. Will look into this further.

**Comment by chinmaygarde** [comment]
We can close this. Completed in https://github.com/flutter/engine/pull/3667.

**Pull request closed without merging**
