### PR TITLE
[engine] more consistently flush dart event loop, run vsync callback immediately

### PR DESCRIPTION
**Pull request by jonahwilliams**
Changes the following shell callbacks to flush the dart event loop:

* OnPlatformViewSetViewportMetrics
* OnPlatformViewDispatchPointerDataPacket
* OnPlatformViewDispatchPlatformMessage
* OnPlatformViewSetSemanticsEnabled
* OnPlatformViewSetAccessibilityFeatures

Using a new TaskRunner API RunNowAndFlushMessages. If the task runner can run tasks on the current thread, this will immediately invoke a callback and then post an empty task to the event loop to ensure dart listeners fire.

This also updates the vsync waiter to use RunNowOrPostTask, so that we start vsync events as early as possible.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
WDUT @jason-simmons @LongCatIsLooong ?

**Comment by jason-simmons** [comment]
LGTM

**Comment by jonahwilliams** [comment]
Those goldens are concerning. if they aren't stable I need to roll back the MSAA patch

**Review by jason-simmons — APPROVED** [review]

**Comment by jonahwilliams** [comment]
reason for revert: speculative revert for framework failures.

**Pull request merged**
