### PR TITLE
Add a golden scenario test for fallback font rendering on iOS

### PR DESCRIPTION
**Pull request by xster**
Somewhat related to https://github.com/flutter/flutter/issues/60013. If user specifies a font that doesn't exist, it should properly fallback to the SF font and render it correctly. Needs https://github.com/flutter/engine/pull/20557 to render the right font.

@blasten I'm removing those iPhone SE images as previously discussed. Pull a modular golden test part out of the platform view stuff.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
@xster Are you making progress on this? Can you fix the remaining presub and land this?

**Comment by xster** [comment]
Sorry, had to push 1.22 stuff first. I'll loop back to this next week.

**Comment by chinmaygarde** [comment]
Can this land now?

**Comment by chinmaygarde** [comment]
Some presubmits are still failing. Kicked them again.

**Comment by chinmaygarde** [comment]
Closing this stale PR. Feel free to reopen when progress can be made. Thanks.

**Pull request closed without merging**
