### PR TITLE
Pub workspace-ify most of `testing/` and parts of `tools/`

### PR DESCRIPTION
**Pull request by matanlurey**
Replaces and closes https://github.com/flutter/engine/pull/53997.

This PR migrates the following packages to the pub workspace:
  - testing/benchmark
  - testing/dart
  - testing/litetest
  - testing/pkg_test_demo
  - testing/scenario_app
  - testing/skia_gold_client
  - testing/symbols
  - tools/golden_tests_harvester
  - tools/pkg/process_fakes

It also makes minor changes to the Dart build rules in order to resolve the root package_config, instead of per-package.

I am _not_ totally confident of the `_embedder.yaml` change, but I also can't explain what is needed to continue analyzing `lib/ui` without analysis failures that all of the symbols in `dart:nativewrappers` are missing.

### CODE REVIEW

**Comment by jason-simmons** [comment]
The `_embedder.yaml` change LGTM.

With the workspace, the analyzer will resolve `dart:nativewrappers` using `_embedder.yaml`.  So `_embedder.yaml` now needs a path to a usable implementation of `dart:nativewrappers`.

(Without the workspace the analyzer was obtaining the path for `dart:nativewrappers` from a Dart SDK internal metadata library)

CI is having issues analyzing the `web_sdk` packages.  Do they also need to be added to the workspace in this PR?

**Comment by matanlurey** [comment]
> The `_embedder.yaml` change LGTM.
> 
> With the workspace, the analyzer will resolve `dart:nativewrappers` using `_embedder.yaml`. So `_embedder.yaml` now needs a path to a usable implementation of `dart:nativewrappers`.
> 
> (Without the workspace the analyzer was obtaining the path for `dart:nativewrappers` from a Dart SDK internal metadata library)
> 
> CI is having issues analyzing the `web_sdk` packages. Do they also need to be added to the workspace in this PR?

Not quite, I think I just need to tweak dependency overrides.

**Comment by matanlurey** [comment]
Ok looks fine locally, PTAL @jason-simmons.

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Pull request merged**
