### PR TITLE
Remove GetField calls from compositing upload

### PR DESCRIPTION
**Pull request by abarth**
Now we grab the underlying primative values before exiting the VM.

### CODE REVIEW

**Comment by abarth** [comment]
@eseidelGoogle

**Comment by Hixie** [comment]
Should we make `DartConverter<Rect>::FromDart` assert so that we can't put these back? (I'm assuming this is what's being avoided here.)

**Comment by abarth** [comment]
> Should we make DartConverter<Rect>::FromDart assert so that we can't put these back? (I'm assuming this is what's being avoided here.)

We use it in other places.  We should probably remove it everywhere and then remove the converter entirely.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
@sethladd This will remove the GetField calls which were all over the trace for the weather demo bug. Once this lands (and the engine is revved) we should retrace it and see why Paint is taking so long.

**Pull request merged**
