### PR TITLE
Cherry pick 3d104f43649d333492dfa792968c8a09af93a84c

### PR DESCRIPTION
**Pull request by dnfield**
Remove obsolete check on FlutterPlatformViewsController::OnCreate (#19819)

### CODE REVIEW

**Comment by dnfield** [comment]
Web engine was infra failure - retry here: https://ci.chromium.org/p/flutter/builders/try/Linux%20Web%20Engine/7024

**Comment by dnfield** [comment]
Also picking da8defdc5f2eb90ab28b59525fda5e88732c3b22 to get a new script the web builders want.

This will fail the framework analysis because framework master has been updated for a rev of dart not contained in this branch.

**Comment by nturgut** [comment]
> Also picking [da8defd](https://github.com/flutter/engine/commit/da8defdc5f2eb90ab28b59525fda5e88732c3b22) to get a new script the web builders want (/cc @nturgut )
> 
> This will fail the framework analysis because framework master has been updated for a rev of dart not contained in this branch.

Thanks a lot for the cherrypick.

**Comment by christopherfujino** [comment]
updated cirrus.yml to checkout the right framework branch

**Comment by dnfield** [comment]
This is  all green. LGTY @christopherfujino or do you still have to update the CIPD stuff?

**Comment by dnfield** [comment]
I'm going to merge assuming this is all ok. We can retag CIPD if needed.

**Comment by christopherfujino** [comment]
sorry, just saw this now. it's good to go, though :+1:

**Pull request merged**
