### PR TITLE
Add 'explicit' to header files

### PR DESCRIPTION
**Pull request by zanderso**
This PR adds `explicit` to constructor declarations that are asked for in a `host_debug` build on Linux using the following `.clang-tidy` file:

```
Checks: '-*,google-explicit-constructor'
WarningsAsErrors: '-*,google-explicit-constructor'
HeaderFilterRegex: '.*/flutter/.*h$'
```

For https://github.com/flutter/flutter/issues/93576

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Review by jmagman — APPROVED** [review]

**Comment by zanderso** [comment]
@CaseyHillers why is this PR still blocked?

**Comment by CaseyHillers** [comment]
@zanderso there's a tree failure now. The status is reporting correctly.

**Comment by zanderso** [comment]
@CaseyHillers GitHub is telling me that merging is blocked. I should be able to land an lgtm'd PR even when the tree is red. (This one doesn't need to, but I should be able to.)

**Comment by jmagman** [comment]
> @CaseyHillers changed the base to main, but it still says the base is master...?

Switching back to `main` unblocked it again.  Not sure how it got back to being based on `master`.

**Pull request merged**
