### PR TITLE
Enable raster cache in compositor

### PR DESCRIPTION
**Pull request by abarth**
The raster cache show some significant speedups in some situations.
Let's turn it on by default and learn more.

In this patch, I've also switched us away from using the
SkPictureImageGenerator because the preroll patches haven't landed in
Skia yet. Once those have landed, we might want to switch back.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @chinmaygarde

**Comment by Hixie** [comment]
lgtm. Filed https://github.com/flutter/flutter/issues/1219 on removing the #define.

**Comment by chinmaygarde** [comment]
Currently, the only cache eviction strategy is based on the use count of the entry in the frame. This makes the raster cache insensitive to memory pressure from other parts of the system. I am slightly nervous about crashes because of running out of device memory between the last attempt to populate a cache entry (in which case `SkSurface::NewRenderTarget` returns null) and performing other operations that require more allocations.

**Comment by abarth** [comment]
Yes, we're using Skia's resource budgeting system.  I'm not sure how skia tells us that it wants to evict us.

**Comment by abarth** [comment]
We can also do our own accounting of how many resources we're using.  That's what Chrome does.  However, it seems better if we can have a common resource budget with Skia.

**Pull request merged**
