### PR TITLE
Remove unnecessary buffer collection image constraints.

### PR DESCRIPTION
**Pull request by dreveman**
These constraints are not needed and result in usage of
images with linear layout. That's a significant
performance regression on most devices, and also not
guaranteed to work as color attachments.

Also, use GetBufferCollectionPropertiesFUCHSIA to improve
correctness of memory import.

### CODE REVIEW

**Review by dragostis — APPROVED** [review]
LGTM.

**Review by dragostis — APPROVED** [review]
LGTM.

**Review by arbreng — APPROVED** [review]

**Comment by gnoliyil** [comment]
Verified Fuchsia workstation.x64 works well after applying the flutter change.

**Comment by chinmaygarde** [comment]
I've filed flake reports for the failing presubmits and restarted them.

**Pull request merged**
