### PR TITLE
Adds python3_action GN target

### PR DESCRIPTION
**Pull request by richkadel**
Ninja runs `action` scripts using the default python interpretter, and
most flutter build scripts that use python currently require python2. In
order to support python3 scripts as well, the `python3_action` invokes a
wrapper python2-based script via GN `action` target, and the wrapper
invokes the python3 interpretter with the given script.

This new target is required to support flutter/engine#26880, but is
broken out to a separate PR (by request) to support other more immediate
use cases.

*List which issues are fixed by this PR. You must list at least one issue.*

Regarding flutter/flutter#53002: Note that this is a *temporary workaround* for python3 scripts, while python2 is still required. Once python3 is the default, the `python3_action` targets can be changed to simply `action`, and the files in this PR will no longer be needed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by richkadel** [comment]
@chaselatta - You asked me to break out this change and move it outside of the `flutter/tools/fuchsia` subdirectory. This should be ready for review.

**Review by chaselatta — APPROVED** [review]

**Comment by chinmaygarde** [comment]
This needs to be rebased for the presubmits to pass.

**Comment by richkadel** [comment]
> This needs to be rebased for the presubmits to pass.

Ah, now I understand the `cannot lock ref` message. Thanks! 

(That error message is very cryptic!)

**Comment by richkadel** [comment]
@chinmaygarde - This finally passes. OK to merge?

**Comment by chinmaygarde** [comment]
Go for it!

**Comment by richkadel** [comment]
Thanks. I don't have merge privs, and Chase is OOO. Can you help?

**Comment by richkadel** [comment]
Thank you @jason-simmons !

**Pull request merged**
