### PR TITLE
Start sketching out the Dart/Objective-C bridge

### PR DESCRIPTION
**Pull request by abarth**
This patch includes the start of a Dart/Objective-C bridge by exposing
(some of) the Objective-C ABI through a dart:objc built-in library.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde @jason-simmons @collinjackson

**Comment by Hixie** [comment]
Why is Objective C special? Should we have a `dart:python` and a `dart:win64` and a `dart:android`, etc, too?

Why not use Mojo?

**Comment by abarth** [comment]
> Why is Objective C special?

The reason I'm interested in creating an Objective-C bridge is because third-party SDKs for iOS expose Objective-C interfaces.  It's the same reason Swift has an Objective-C bridge and Dart-for-web has a JavaScript bridge.

> Should we have a `dart:python` and a `dart:win64` and a `dart:android`, etc, too?

The idea is to have a `dart:jni` for Android because third-party SDKs for Android expose Java interfaces.  We shouldn't need a `dart:android` that knows about the Android APIs.  Instead, `dart:jni` and `dart:objc` just provide interop with the target language, not any knowledge of the APIs that exist in that language.  Knowledge of the APIs can be layer on top of the language bridge using Dart packages.

> Why not use Mojo?

We should use Mojo to expose platform-independent services.  As we built out Mojo services for FNL, we'll want to provide implementations of those interfaces for iOS and Android as well.  However, it's going to take us a long time to build out those services (and even longer to provide coverage for all the third-party SDKs).  Using Mojo exclusively would be a barrier to developers adopting Flutter because they'll have difficulty using third-party SDKs.

**Comment by Hixie** [comment]
The way I imagined that third-party SDKs would be exposed (by the second party) is that they'd write a mojo wrapper which we'd load at startup. So for example, if the SDK is exposed as Java code, they write some Java code that bridges the Java-based API to a Mojo-based API, and put that code in a well-known location in their package. At startup, we look in that well-known location and start up all the packages there, telling them to register whatever services they have, and the Dart code then talks to that. It's not clear to me that this would be more work for authors than writing the bridge using a `dart:jni` interface.

This works for other languages too. C++ SDK? Drop a .so in a well-defined place, and at startup we dlopen the library, jump to a well-defined symbol to get it to register its services. Python SDK? Have a .so that loads the Python interpreter and when the engine jumps into that .so, the .so calls the relevant well-known python function. Java is special in this world only because it's a runtime we're already using. On a platform where Java isn't a native aspect of the platform, you can still expose the Java SDK, you just need to add a little bit more code to first embed a Java runtime and forward the registration calls.

With a first-class-in-the-engine per-language bridge-to-dart approach, how do you expose SDKs written in languages for which we haven't provided a bridge?

**Comment by abarth** [comment]
> It's not clear to me that this would be more work for authors than writing the bridge using a `dart:jni` interface.

The goal is to make the `dart:jni` bridge much less work.  For example, you might be able to write code similar to https://github.com/kivy/pyjnius#quick-overview

> This works for other languages too.

In practice, people providing third-party SDKs use expose Objective-C APIs on iOS and Java interfaces on Android.

> How do you expose SDKs written in languages for which we haven't provided a bridge?

1. That's a much less important problem because the bridges will be to the correct language for the vast majority of third-party SDKs.  (Even if the SDKs are written in some other language, to make them useful on iOS or Android, the developers providing the SDKs typically wrap them in Objective-C or Java interfaces.)
2. You can use Mojo to solve this problem if you want.

**Comment by Hixie** [comment]
I guess my concern is that the opportunity cost is high. All the time we'll spend supporting the dedicated objc/jni bridges could be spent making the Mojo bridge as trivial to use, but the latter has more long term value.

**Comment by abarth** [comment]
> I guess my concern is that the opportunity cost is high.

Yes, the trade-off isn't obvious.  It's probably worth more discussion.

**Comment by eseidelGoogle** [comment]
Also note that our use of Mojo IPC currently solves 2 problems:
1.  Language bridging (java/objc -> dart)
2.  Thread bridging (any thread, typically platform UI thread -> flutter UI thread) (part of keeping pauses off the flutter UI thread).

And comes with 2 obvious costs:
a.  Difficult to use/generate/maintain custom interface format (mojom).
b.  Requiring developers to think async (and wrap existing sync apis as async).

jni/obj-c bindings only solves problem 1.  Lessons cost a, and eliminates cost b.  It of course comes with its own set of costs including object lifetime management, object marshaling, etc.

As @abarth says, it's a complex issue.  This is exploring one possible alternate tool.

**Comment by chinmaygarde** [comment]
I was wondering if you had considered this alternative way of bridging to Objective-C.

* Give the `dart:objc` library its own native resolver.
* The only responsibility of the resolver callback is to delegate the SEL to IMP resolution to the actual Objective-C runtime.
  * If IMP resolution fails, we return NULL for resolution and the Dart runtime fails as usual (which I think is a crash, so we better provide a stub)
  * If SEL to IMP resolution succeeds however, the symbol we provide knows how to marshall and unmarshall the Dart arguments/return types and eventually call `objc_msgSend*`
  * During resolution, we have enough information from the Objective-C runtime about method names, arities, etc. to successfully manage this call.
* We can stick the class and selector in the string specified after the native declaration in Dart. As for the target for the invocation, that can be an argument on the dart call.

If all we need is a way to call arbitrary Objective-C code, the need to have the entire Objective-C runtime API at your disposal in Dart seems a tad excessive.

**Comment by Hixie** [comment]
Upon further discussion, I think this approach is valuable if framed as a medium-term bootstrapping band-aid to be removed in due course. This implies that the design goals are pragmatic (support common cases) rather than comprehensive (it's ok if some features can't be exposed). The biggest cost is that it probably requires putting the Dart VM on the Java/ObjC thread on the medium term (while this feature is supported, on platforms where it's supported), with all the performance risks that that implies (bad SDKs will hurt performance).

**Comment by abarth** [comment]
> We can stick the class and selector in the string specified after the native declaration in Dart.

The problem with this approach is that we'd need the `dart:objc` library to know the class and selector of everything we want the developer to be able to access.  With the approach in this patch, we can bridge to arbitrary classes and selectors.

**Comment by j9brown** [comment]
Is there a way to wrap/unwrap a foreign object (Java, ObjC, or other
environment) into a Mojo platform handle for opaque transfer across service
boundaries?

In any case, an efficient foreign function call interface is likely to be
an essential building block for interoperability.  The surface area of
foreign APIs of potential interest is huge, far more than a reasonable
person would feel comfortable wrapping up by hand one at a time.

To mitigate jank, we could introduce constraints whereby foreign function
calls are only allowed (or recommended) on "worker isolates" which run on
separate threads from the Flutter UI.  Such a compromise would enable
bridging code to be written in Dart, including Mojo IPC based wrappers,
which may feel more natural to Dart developers.

ie. I expect many developers will be asking for ways to invoke foreign APIs
without writing any Java / ObjC / C code themselves or even needing to have
those compilers installed.  That would also work well will the pub workflow
since developers could share wrappers for common APIs of interest as pure
Dart packages.

**Comment by abarth** [comment]
> Is there a way to wrap/unwrap a foreign object (Java, ObjC, or other environment) into a Mojo platform handle for opaque transfer across service boundaries?

This mechanism doesn't have that feature.

>  I expect many developers will be asking for ways to invoke foreign APIs without writing any Java / ObjC / C code themselves or even needing to have those compilers installed.

Yes, exactly.  The Java and Objective-C cases are easier than C because Java and Objective-C have sufficient runtime reflection to generate most of the ffi on the fly.

**Comment by j9brown** [comment]
Sounds good.

I noticed that the implementation seems to drive most of the reflection
from Dart land.  If this mechanism ends up being used a lot, it may be
worth comparing the performance cost of this approach with one that does
most marshaling in native code.

For JNI on Android, it's orders of magnitude more efficient to cache object
layouts in native code and marshal objects all at once than to peek or poke
every field one at a time in Java and it can generate much less garbage
(ideally none).

**Comment by chinmaygarde** [comment]
> The problem with this approach is that we'd need the dart:objc library to know the class and selector of everything we want the developer to be able to access. With the approach in this patch, we can bridge to arbitrary classes and selectors.

Presumably, users of the Objective-C API would want to program against an interface in Dart. So wouldn't you need to have this anyway? I guess I was thinking that the bindings would be generated for the entire library that that user would import (Foundation, GameKit, etc.). Maybe my mental model of this is a bit off.

**Comment by abarth** [comment]
> Presumably, users of the Objective-C API would want to program against an interface in Dart. So wouldn't you need to have this anyway?

The question is whether it's compiled into the engine or whether it's something that you can do just by adding Dart code.

> I guess I was thinking that the bindings would be generated for the entire library that that user would import (Foundation, GameKit, etc.).

How do you know the entire set of libraries that the user wants?  Only the end-developer knows the total set of libraries, which implies that you'd need to run this code generation step on the end-developers machine.  I guess I was hoping to avoid that...

**Comment by j9brown** [comment]
After writing this, I remembered that since you're a client of a foreign
API you might not actually be able to marshal whole objects since you're
constrained by the interface (and there tend to be relatively few pure data
objects around).

Carry on.  :)

**Comment by chinmaygarde** [comment]
> The question is whether it's compiled into the engine or whether it's something that you can do just by adding Dart code.

You would just need to add Dart code. The SEL to IMP resolution is dynamic and handled by the ObjC runtime. We only need a way to specify the mapping between the Dart name of the method to the name of the selector. The engine does not need to be recompiled.

> How do you know the entire set of libraries that the user wants? Only the end-developer knows the total set of libraries, which implies that you'd need to run this code generation step on the end-developers machine.

Right. This does require a (Dart only) code generation step on the users machine (unless we ship bindings to only a few "blessed" libraries). The alternative would be to have the user specify the name, arity and types of each of the methods before a call is made to the same. I was dismissing the size of the generated bindings based on the fact that most of it would be tree shaken away.

**Pull request closed without merging**
