### PR TITLE
[CP] [Impeller] Retain embolden/skew font properties when rendering text g…

### PR DESCRIPTION
**Pull request by zanderso**
CP of https://github.com/flutter/engine/commit/4fdbb0a366e76920f62d23ce220456e1c5a255ab to fix https://github.com/flutter/flutter/issues/119489 for `flutter-3.7-candidate.1`

### CODE REVIEW

**Comment by zanderso** [comment]
Presubs are affected by https://github.com/flutter/flutter/issues/120093

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by godofredoc** [comment]
@zanderso  can you please rebase this change? it will help to pass all the presubmit checks.

**Comment by zanderso** [comment]
> @zanderso can you please rebase this change? it will help to pass all the presubmit checks.

Done

**Review by bdero — APPROVED** [review]

**Pull request merged**
