### PR TITLE
Allow Flutter apps on Fuchsia to shut down cleanly

### PR DESCRIPTION
**Pull request by ianloic**
The UIDartState is now always owned by the isolate and always freed in
the isolate cleanup callback.

In the isolate shutdown callback, if the isolate being shut down is the
main isolate, the RuntimeController is informed which in turn notifies
the RuntimeHolder and thus the ApplicationControllerImpl. The
ApplicationControllerImpl tears down the whole Flutter application.

This fixes Fuchsia bug: MI4-328

### CODE REVIEW

**Comment by zanderso** [comment]
Note that the engine is pinned in Fuchsia at the moment while I'm working on rolling the Dart/engine/framework triforce.

**Comment by ianloic** [comment]
@zanderso I think that's okay - the changes here and in the topaz repo are somewhat independent. When do you expect to roll this forward?

**Comment by zanderso** [comment]
Hopefully today.

**Comment by zanderso** [comment]
The roll is blocked on updating a slew of deprecated symbols introduced by https://github.com/dart-lang/sdk/commit/0b58c4bd10df3f41baa19b1dc2aa25c76137b09c#diff-e89dc4b6daa301fab6a22269eb01c35b

**Comment by ianloic** [comment]
Looks like that deprecation was rolled back. Any idea when this will roll?

**Comment by zanderso** [comment]
It's safe to roll the engine forward independently of Dart by simply bumping the commit hash here: https://fuchsia.googlesource.com/topaz/+/master/manifest/flutter#11. I'm planning to roll Dart/Engine/Framework on Monday.

**Comment by zanderso** [comment]
Dart, the engine, and framework all finally rolled forward in Fuchsia today.

**Pull request merged**
