### PR TITLE
MacOS framework was simplified to remove an internal zip.

### PR DESCRIPTION
**Pull request by godofredoc**
This PR is removing the nested zip file and removing all the boilerplate
GN used to generate the zip within the zip.

Bug: https://github.com/flutter/flutter/issues/81855

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by jmagman** [comment]
This isn't correct and will break
https://github.com/flutter/flutter/blob/7f1a8f79489412ff992b8ba0aaecc386fe628557/packages/flutter_tools/lib/src/commands/build_macos_framework.dart#L167 and similar.

@godofredoc there are framework tests for this that I would have expected to fail on the roll, is the recipe still zipping the zip?

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/110034 to track the tool, recipe, and roll script work.

**Comment by zanderso** [comment]
@godofredoc My understanding was that this change only affects the engine_v2 artifacts, and all of the engine_v2 artifacts will require some tooling migration. Is that correct, or does this affect our current artifacts, as well?

**Comment by jmagman** [comment]
@godofredoc confirmed this only changes the `engine_v2`.  We can either ship both zipped and unzip for incremental adoption as proposed in https://github.com/flutter/flutter/issues/110034, or I can prep the tool work needed to be used when `engine_v2` goes into effect, and the rollers can make the script changes when the `engine_v2` roll in.

**Pull request merged**
