### PR TITLE
Revert "[Impeller] Adds wide gamut support for iOS."

### PR DESCRIPTION
**Pull request by itsjustkevin**
Reverts flutter/engine#39111 as it is causing failures.

issue: b/268818076

### CODE REVIEW

**Comment by gaaclarke** [comment]
@itsjustkevin can you link the failures please so I can verify that they are related?

**Comment by itsjustkevin** [comment]
@gaaclarke Original comment updated with the bug link.

**Review by gaaclarke — APPROVED** [review]
Changing the signature of the FlutterView's init method was a breaking change.

**Comment by gaaclarke** [comment]
I rebased this so it should be good to go if you want to go this route.

**Comment by CaseyHillers** [comment]
This is still blocking the roll. Can we land the revert @gaaclarke ?

**Comment by gaaclarke** [comment]
> This is still blocking the roll. Can we land the revert @gaaclarke ?

I don't believe you should have a need to revert this anymore.  The problem that was causing the roll failure was that internal tests were looking for the specific selector that I changed.  b/269181523 fixed that issue.  (I also provided a cl that fixed it if you can't grab that version of the code).  The problem you linked in the chat seems to be some failed application of the original patch (where the signature was updated but the callers wasn't).

**Comment by chinmaygarde** [comment]
Closing per @gaaclarke s last comment. Please reopen and address the conflicts if we need a revert.

**Pull request closed without merging**
