### PR TITLE
Guard impeller references in platform_view_android.cc for google build

### PR DESCRIPTION
**Pull request by dnfield**
@CaseyHillers @zanderso @chinmaygarde 

For b/233045685

### CODE REVIEW

**Comment by CaseyHillers** [comment]
Can we use Google Testing to verify this change?

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
@CaseyHillers can you point to instructions on how to do that?

**Comment by dnfield** [comment]
I started a TGP on cl/449791593, which contains this change.

**Comment by dnfield** [comment]
Arrrgh. It wasn't synced properly and now I'm trying to fix that.

**Comment by dnfield** [comment]
http://test/OCL:449791593:BASE:449792015:1652984736690:c41778cb

**Comment by dnfield** [comment]
@CaseyHillers FWIW, engine contributors are not likely to go through the exercise of testing this. I don't know what we can do about avoiding this short of:

- Building impeller internally
- Adding FRoB support to the engine repo

Running a test on this was pretty trivial since I had a bad CL I could quickly clone and patch with this change. If I was working on some random impeller or Android change I would not think to do that and it may be much more difficult.

**Comment by Hixie** [comment]
test-exempt: build configuration will be tested by target build environment

**Comment by dnfield** [comment]
@CaseyHillers there are a bunch of failures on my TGP but they all seem to be related to other problems with web or a different engine patch than the impeller one.

**Comment by CaseyHillers** [comment]
By Google Testing, I meant the presubmit frob status. It looks like that doesn't run on the engine.

**Pull request merged**
