### PR TITLE
Handle Unicode surrogates in FlutterTextInputView

### PR DESCRIPTION
**Pull request by cbracken**
Fixes a bug introduced in 38664ac32223228476166b9050ab400c102fda05.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Is there any way to unit test this?

**Comment by cbracken** [comment]
I'm not aware of any unit testing infra in the engine on the ObjC side, but this is something I'd be more than happy to look at. In particular, utility code seems like really low-hanging fruit for testing.

**Comment by chinmaygarde** [comment]
The bots run unit tests of the various libraries that have platform agnostic interfaces on the host (FML, FTL, WTF, etc.). Since this is specific to the framework that gets linked in on the device, we have no unit test runners currently. We will have to come up with a custom harness that is packaged as an iOS/Android application. Even then, we will need devices connected to the bot. I have been able to push the unit test executables on Android and run them directly from `adb shell` however. Though this you can only do locally.

**Pull request merged**
