### PR TITLE
Update Xcode to 14.3.1

### PR DESCRIPTION
**Pull request by vashworth**
Engine part of https://github.com/flutter/flutter/issues/129019.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by vashworth** [comment]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/236711/overview

`Mac mac_clang_tidy` is failing with hundreds of errors involving missing headers, such as:

```
❌ Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/display_list/benchmarking/dl_region_benchmarks.cc:
../../third_party/libcxx/include/string.h:60:15: error: 'string.h' file not found [clang-diagnostic-error]
#include_next <string.h>
              ^~~~~~~~~~
Jobs:   0% done,   0/653 completed,  7 in progress, 644 pending,   2 failed.    
❌ Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/benchmarking/benchmarking.cc:
../../third_party/libcxx/include/string.h:60:15: error: 'string.h' file not found [clang-diagnostic-error]
#include_next <string.h>
              ^~~~~~~~~~
Suppressed 1582 warnings (1579 in non-user code, 3 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
Jobs:   0% done,   0/653 completed,  7 in progress, 643 pending,   3 failed.    
❌ Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/display_list/dl_color_unittests.cc:
../../third_party/skia/include/private/base/SkFeatures.h:15:18: error: 'TargetConditionals.h' file not found [clang-diagnostic-error]
        #include <TargetConditionals.h>
                 ^~~~~~~~~~~~~~~~~~~~~~
Suppressed 1442 warnings (1417 in non-user code, 25 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
```

**Comment by vashworth** [comment]
I've tried rerunning and it's still erroring on the `Mac mac_clang_tidy` errors. @keyonghan Do you have any ideas what could be wrong?

**Comment by zanderso** [comment]
I pushed a commit to this PR to pass `--verbose` to the clang_tidy script. That may not be sufficient for the script to print the `clang-tidy` commands that it's running, but that's what would probably help debug this. If the commands aren't printed, I'll push another commit or two to the PR until we can see those.

**Comment by vashworth** [comment]
The verbose helped, it now has this error:

```
error: no such sysroot directory: '/Volumes/Work/s/w/ir/cache/osx_sdk/xcode_14e300c/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk' [clang-diagnostic-missing-sysroot]
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_clang_tidy/1350/overview

However, looks like the `ios_debug_sim` version does not have the same problem, even though it looks like it uses the same path for the sysroot

From `lint ios_debug_sim`
```
Running "../../buildtools/mac-x64/clang/bin/clang-tidy /Volumes/Work/s/w/ir/cache/builder/src/flutter/fml/memory/weak_ptr_internal.cc --warnings-as-errors=* -- /Volumes/Work/s/w/ir/cache/goma/client/gomacc  ++ -MD  clang_arm64/obj/flutter/fml/memory/fml.weak_ptr_internal.o.d  -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 "-DDART_LEGACY_API=[[deprecated]]" -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1  -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../third_party/abseil-cpp -isysroot /Volumes/Work/s/w/ir/cache/osx_sdk/xcode_14e300c/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.14.0  -fno-strict-aliasing -fstack-protector-all -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g2  -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions -stdlib=libc++ -Wno-unknown-warning-option -Wno-deprecated-builtins  -c ../../flutter/fml/memory/weak_ptr_internal.cc -o  clang_arm64/obj/flutter/fml/memory/fml.weak_ptr_internal.o" in /Volumes/Work/s/w/ir/cache/builder/src/out/ios_debug_sim.
```

From `lint host_debug`
```
Running "../../buildtools/mac-x64/clang/bin/clang-tidy /Volumes/Work/s/w/ir/cache/builder/src/flutter/fml/memory/weak_ptr_internal.cc --warnings-as-errors=* -- /Volumes/Work/s/w/ir/cache/goma/client/gomacc  ++ -MD  clang_arm64/obj/flutter/fml/memory/fml.weak_ptr_internal.o.d  -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 "-DDART_LEGACY_API=[[deprecated]]" -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1  -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -isysroot /Volumes/Work/s/w/ir/cache/osx_sdk/xcode_14e300c/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.14.0  -fno-strict-aliasing -fstack-protector-all -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -Wstring-conversion -Wnewline-eof -O2 -fno-ident -fdata-sections -ffunction-sections -g2  -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions -stdlib=libc++  -c ../../flutter/fml/memory/weak_ptr_internal.cc -o  clang_arm64/obj/flutter/fml/memory/fml.weak_ptr_internal.o" in /Volumes/Work/s/w/ir/cache/builder/src/out/host_debug.
```

Maybe it's an issue with the caching?

**Comment by zanderso** [comment]
Maybe @keyonghan can advise on the caching and/or the missing sysroot osx_sdk. Is it possible to inspect the filesystem on a machine to see whether it's there?

**Comment by keyonghan** [comment]
Does that mean we need xcode installed to run the test? Currently the test is not enforcing xcode pre-installed: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/241583/overview

`ios_debug_sim` passed with a high chance it picked a bot which has already installed the new xcode.

**Comment by keyonghan** [comment]
@vashworth : An update here: recipes CL is blocked on the CQ which fails on a gradle related error (I will give it another try in case of a flake). Once that CL lands, rebasing on top of https://github.com/flutter/engine/pull/43115 should unblock here.

**Comment by keyonghan** [comment]
The recipes CL landed. @vashworth could you give it a try?

**Pull request merged**
