### PR TITLE
Renamed plugin classes to handler

### PR DESCRIPTION
**Pull request by robert-ancell**
The Linux embedder had a number of handlers for Flutter channels that were named plugin/handler/manager. Rename these all to handler to be consistent and reduce confusion with Flutter plugins (which these don't use the infrastructure for).

Handler seemed to be the more common term looking at other embedders like Windows, but even there it's not used consistently. Open to other terms.

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

Thanks! This reads a lot better. We should consider similar renamings in other embedders as well.

**Comment by robert-ancell** [comment]
Still looking into the test failure. It's an ASAN issue, i.e. a leak.

**Comment by jason-simmons** [comment]
For the LSAN issue: this line in the suppression file needs to be updated to `fl_keyboard_handler_test.cc`:
  
  https://github.com/flutter/engine/blob/main/testing/lsan_suppressions.txt#L54

**Pull request merged**
