### PR TITLE
[cp:beta][web] Work around wrong pointerId in coalesced events in iOS Safari 18.2 (#56719)

### PR DESCRIPTION
**Pull request by mdebbar**
Manual cherry pick for https://github.com/flutter/engine/pull/56719

Cherrypick request: https://github.com/flutter/flutter/issues/159692

### CODE REVIEW

**Review by ditman — APPROVED** [review]
LGTM, thanks for cherry-picking!

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by givip** [comment]
Is there any chance to get these changes merged soon?

**Comment by christopherfujino** [comment]
@mdebbar there are failing tests in `Mac mac_unopt`:

```
 [3074/3074] SaturatedMath.CastingFiniteDoubleToFloatStaysFinite (59 ms)
 FAILED TESTS (9/3074):
      589 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/AiksTest.GaussianBlurSolidColorTinyMipMap/Metal (try #1)
      497 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverageTranslate/Metal (try #1)
      552 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.TextureContentsWithEffectTransform/Metal (try #1)
      447 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.TextureContentsWithDestinationRectScaled/Metal (try #1)
      582 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/AiksTest.CanRenderInvertedImageWithColorFilter/Metal (try #2)
      568 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverage/Metal (try #2)
      422 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/MatrixFilterContentsTest.RenderCoverageMatchesGetCoverageScale/Metal (try #2)
      431 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverageRotated/Metal (try #1)
      524 ms: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/EntityTest.RuntimeEffectCanPrecache/Metal (try #1)
 SUMMARY:
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/AiksTest.CanRenderInvertedImageWithColorFilter/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/AiksTest.GaussianBlurSolidColorTinyMipMap/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/EntityTest.RuntimeEffectCanPrecache/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverage/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverageRotated/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.RenderCoverageMatchesGetCoverageTranslate/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.TextureContentsWithDestinationRectScaled/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/GaussianBlurFilterContentsTest.TextureContentsWithEffectTransform/Metal passed 1 / 2 times.
   /Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_debug_tests/impeller_unittests Play/MatrixFilterContentsTest.RenderCoverageMatchesGetCoverageScale/Metal passed 1 / 2 times.
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8729553482934559489/+/u/test:_Host_Tests_for_host_debug/stdout

**Comment by mdebbar** [comment]
@christopherfujino I'm not sure how my web-only change could cause a failure for Mac.

I rebased the PR and also trying an empty commit [here](https://github.com/flutter/engine/pull/57064) to see if this failure is happening on the beta branch already.

**Comment by givip** [comment]
> @christopherfujino I'm not sure how my web-only change could cause a failure for Mac.
> 
> I rebased the PR and also trying an empty commit [here](https://github.com/flutter/engine/pull/57064) to see if this failure is happening on the beta branch already.

Can we merge?

**Pull request merged**
