### PR TITLE
Make TextInputModel::selection_start/end const

### PR DESCRIPTION
**Pull request by cbracken**
Neither of these methods mutate the state of the model.

No tests added since no behaviour was changed. The existing tests cover the change.

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Fuchsia failure is an infra failure flake. Tree is currently red on a flake. Going to land this to try to kick the tree so hopefully the rollers can get restarted.

**Comment by cbracken** [comment]
Thanks!

**Comment by cbracken** [comment]
Related Issues:

* Full IME support for Windows (flutter/flutter#65574)
* Full IME support for Linux (flutter/flutter#66880)

**Pull request merged**
