### PR TITLE
Fix multi-font ttc rendering for iOS

### PR DESCRIPTION
**Pull request by xster**
Remove iOS specific font fallback mechanism.
Push logic into Skia

Fixes https://github.com/flutter/flutter/issues/6939

### CODE REVIEW

**Comment by xster** [comment]
For the record, I also pulled https://chromium.googlesource.com/chromium/blink.git/+/506e08f0624f565885f7cbe511f0a849b4c707be in

**Comment by chinmaygarde** [comment]
This looks great! Please re-gen licenses and land.

**Comment by xster** [comment]
The script is going to have some issues on mac. https://github.com/flutter/flutter/issues/8165

I'll just hand craft the output to match travis's

**Comment by xster** [comment]
Had to take it and run while travis was happy :)
Tested caching again. Everything's working as expected.

**Pull request merged**
