### PR TITLE
Build engine for iOS on presubmit

### PR DESCRIPTION
**Pull request by dnfield**
We don't currently test building for ios as part of our presubmits.  We should.

### CODE REVIEW

**Comment by dnfield** [comment]
The checks say yellow but they've actually passed.. landing this.

**Comment by liyuqian** [comment]
Cool, thanks Dan!

It seems that the newly added test needs about 20 minutes to finish, which is much longer than other engine presubmit checks. I wonder if in the future we can cache the `gclient sync` and `ninja` result in the image to accelerate the test.

**Comment by dnfield** [comment]
That should be possible

**Comment by dnfield** [comment]
Actually I'm not sure it would save us much time here.  The Mac machines cache things via upload.  I could try it but it may not save much time.  I'd also like to avoid caching the build out put because that leads to false positive and negatives sometimes

**Comment by liyuqian** [comment]
No worries. It's not a critical issue. We have much infra work to do that's probably more important. Feel free to leave it as is if you think the benefit over cost/risk ratio isn't high enough.

**Pull request merged**
