### PR TITLE
Use X11 display to create EGL display

### PR DESCRIPTION
**Pull request by wmww**
## Description
Use the X11 display to create the EGL display. This brings the implementation in line with the Wayland renderer, and maybe fixes https://github.com/flutter/flutter/issues/60429 (I can't reproduce that, so I do not know for sure). I don't *think* this raises any thread safety problems, as the display is used with different contexts on each thread.

## Related Issues

https://github.com/flutter/flutter/issues/60429

## Tests

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by robert-ancell** [comment]
This used to cause Flutter to crash do to multiple threads accessing xlib. I don't know if there have been changes in Flutter that ensure that can't happen anymore.

**Comment by wmww** [comment]
I thought we'd be fine because we make our own context and you can use a single EGL display from multiple threads as long as you use multiple contexts. What does the EGL display have to do with xlib? Was it the call to `gdk_x11_get_default_xdisplay()` itself that was being made on the wrong thread?

**Comment by robert-ancell** [comment]
> I thought we'd be fine because we make our own context and you can use a single EGL display from multiple threads as long as you use multiple contexts. What does the EGL display have to do with xlib? Was it the call to `gdk_x11_get_default_xdisplay()` itself that was being made on the wrong thread?

EGL is using the `Display` object from XLib (DRI3 calls?) and GTK is also using the same object for its operations. That's where the collision was occurring.

**Comment by robert-ancell** [comment]
Based on the [EGL X11 extension](https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_platform_x11.txt), perhaps we should be using:
```c
eglGetPlatformDisplayEXT(EGL_PLATFORM_X11_EXT, NULL, NULL);
```

**Comment by wmww** [comment]
That looks like it would work, but I can't find what I need to include to get `eglGetPlatformDisplayEXT()` and `EGL_PLATFORM_X11_EXT`.

**Comment by robert-ancell** [comment]
Confirmed the current code crashes. I ran the demo app created by `flutter create`, then wildly resized the window to get:

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
test2: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Lost connection to device.
```

**Comment by robert-ancell** [comment]
Found a solution in https://github.com/flutter/engine/pull/21831

**Pull request closed without merging**
