### PR TITLE
Fix deleting Thai vowel bug on iOS

### PR DESCRIPTION
**Pull request by HelloCore**
It seems the issue about deleting Thai vowel appeared again, and It also happens in other languages that have combined characters as well.
https://github.com/flutter/flutter/issues/39399
https://github.com/flutter/flutter/issues/39169

This PR attempts to skip "string range sanitization" logic because we wanted to delete only a part of the grapheme cluster.

Result https://youtu.be/D-yLuRG7pyE
Related PR https://github.com/flutter/engine/pull/7982

### CODE REVIEW

**Comment by HelloCore** [comment]
CC @cbracken @GaryQian

**Comment by GaryQian** [comment]
Let me verify this with some more obscure languages/scripts and I'll get back to you shortly! Thanks for the PR!

**Comment by GaryQian** [comment]
This change LGTM, Verified it is functional with most keyboards. We don't yet have proper testing in the ios embedder, but in the future we should test for changes like this to prevent regression.

**Comment by GaryQian** [comment]
Thanks a lot for your contribution! This is very important for lots of languages, and I greatly appreciate this as I am not familiar with Thai at all.

**Comment by HelloCore** [comment]
Thank you for reviewing my PR. 

I think the root cause of this problem was `rangeOfComposedCharacterSequenceAtIndex` and `rangeOfComposedCharacterSequencesForRange` didn't split the text based on UAX#29.

I found that there's a function `minikin::GraphemeBreak::isGraphemeBreak` could do this, but I couldn't find the way to import it 😥

**Pull request merged**
