### PR TITLE
[ios] Ensure that the picture recorder is active before finishing it

### PR DESCRIPTION
**Pull request by iskakaushik**
Fixes: https://github.com/flutter/flutter/issues/70577

### CODE REVIEW

**Review by cyanglaz — COMMENTED** [review]
Do you know in what case `->getRecordingCanvas()` is null?
The picture_recorder should start recording in https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L301 which is called before `SubmitFrame` during every frame.


CC @blasten

**Comment by blasten** [comment]
I had a similar question. Based on https://github.com/google/skia/blob/52a4379f03f7cd4e1c67eb69a756abc5838a658f/src/core/SkPictureRecorder.cpp#L55, it appears like something else is misbehaving.

**Comment by iskakaushik** [comment]
> Do you know in what case `->getRecordingCanvas()` is null?

I think when `SurfaceFrame` goes out-of-scope, the destructor calls `SubmitFrame`, which is a recent addition I think cc: @blasten. This in conjunction with thread-merging where we might have to re-submit the frame, we must ensure that the dtor doesn't call submit frame already. My theory is that we are calling Submit twice on the same frame.

**Comment by blasten** [comment]
@iskakaushik do you want to continue debugging this further or should we take it from here?  I'd like to understand the root cause.

**Pull request closed without merging**
