### PR TITLE
Revert "Accessibility number formatting improvements for Windows (#29773)"

### PR DESCRIPTION
**Pull request by gspencergoog**
This reverts commit f4da7bf05aafa65cbd15fd3e0fba84234aa4f965 until https://github.com/flutter/flutter/issues/94822 is fixed.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
lgtm

**Review by cbracken — CHANGES_REQUESTED** [review]
Sorry I misread this -- I thought we were reverting the double->string patch?

**Comment by gspencergoog** [comment]
Whoops, wrong ref.  Switched it to the right one.

**Review by cbracken — APPROVED** [review]
re-lgtm!

**Pull request merged**
