### PR TITLE
Roll Wuffs to 0.3.0-beta.8

### PR DESCRIPTION
**Pull request by nigeltao**
This tracks upstream Skia:
https://skia.googlesource.com/skia/+/9dcbdbdb5e19584ab70c5d57c9f5dd6702eccd69

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
cc @jason-simmons who is going add regenerating licenses to his TODO list.

**Comment by nigeltao** [comment]
Should I sync the `ci/licenses_golden/licenses_third_party` file to latest or should I leave that to one of you?

**Comment by nigeltao** [comment]
> Perhaps we should add bug to put updating this dependency using an autoroller.

FYI there's a follow-up commit (again mimicking Skia, this time it's https://github.com/google/skia/commit/55ca4e692d8fa709e0a1b4d835461beddba8f194) to check only the subset of third_party/wuffs that Skia (and hence Flutter) actually needs, which should cut out a lot of the `ci/licenses_golden/licenses_third_party` churn on every Wuffs roll. But I'd like to keep that as a separate, follow-up commit.

**Comment by jason-simmons** [comment]
I will get a version of this landed with the updated licenses.

**Comment by jason-simmons** [comment]
Landed https://github.com/flutter/engine/pull/28234

**Pull request closed without merging**
