### PR TITLE
Roll buildroot to 92a8d2eb7aad592068f808e39b8330fd2bce25e3, Clang to 12.0.0

### PR DESCRIPTION
**Pull request by dnfield**
Rolls buildroot to flutter/buildroot@92a8d2eb7aad592068f808e39b8330fd2bce25e3

Rolls clang to Clang 12.0.0 for all platforms.

I've tested this locally on iOS, Android, and mac host. 

Fixes flutter/flutter#73757

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Review by zanderso — APPROVED** [review]

**Comment by chinmaygarde** [comment]
There are two classes of failures in the presubmits:
* The pixel test expectations are failing. If this roll includes a toolchain update, I'd just update the expectations. Its possible that the new toolchain has compiler intrinsics that our OpenGL emulation (via SwiftShader) is opting into.
* The AOT data for fixtures in our test harnesses is not being generated. Our tests operate in AOT mode in profile and release runtime variants.

**Comment by dnfield** [comment]
Update from chat: it looks like the new toolchain is messing up the re-encoding of some PNG images used for the test. It's not clear why yet.

**Comment by dnfield** [comment]
This appears to be a compiler bug. I've bisected that down to a particular Fuchsia Clang package version and filed https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=67851.  Trying to roll to the last known good v12.0.0 package.

**Comment by dnfield** [comment]
Tree needs a kick. Redness is because this is missing a buildrule change on master. If this fails post submit I will immediately revert.

**Pull request merged**
