### PR TITLE
[web] make addView/removeView functions sync

### PR DESCRIPTION
**Pull request by p-mazhnik**
Related to https://github.com/flutter/flutter/issues/138930

### CODE REVIEW

**Comment by p-mazhnik** [comment]
@ditman While this PR is a subject for discussion, do you think the engine will benefit if I extract the test into a separate PR, adapting it for the async case? I didn't find other tests in the repo for addView JS function when I was working on these changes

**Comment by ditman** [comment]
@p-mazhnik it's likely that I'll land this, either in this PR or in a separate one cherry-picking this change + some stuff, I've been convinced to:

* make these methods sync
* rename them to `mount(config)`/`unmount(id)`
  * this way, if we ever add a `view` object usable from JS, we have `addView(config)`/`view.remove()` available.

**Comment by ditman** [comment]
@p-mazhnik the test is indeed very useful, thanks for that, and that will land FOR SURE regardless of what happens with the synchronicity of the views. I take back what I said about renaming stuff above, let's do one change at a time, and figure out if this being sync hurts or helps :)

**Comment by ditman** [comment]
@p-mazhnik that's fantastic, thanks for both the implementations of the test!

**Review by ditman — APPROVED** [review]
Thanks for the change, let's make those methods sync!

**Comment by ditman** [comment]
Please @mdebbar, can you PTAL? We need 2 approvals!

**Review by yjbanov — APPROVED** [review]

**Comment by ditman** [comment]
Thansk @p-mazhnik!!

**Pull request merged**
