### PR TITLE
Reland "Delete io.flutter.app android v1 embedding" (#32232)

### PR DESCRIPTION
**Pull request by GaryQian**
This reverts commit 0522b486a0bd219ed5fedff639556d2bc0279764.

Based off of https://github.com/flutter/engine/pull/29248

go/flutter-delete-android-v1-embedding

Deletes the non-plugin related parts of io.flutter.app/* of the v1 android embedding.

This is the first and safest phase of the v1 embedding removal. There is already a build warning that warns against using v1 embedding which can be modified to remove the override option after this as apps will no longer compile without migration.

v1 plugin registry is left intact for now.

### CODE REVIEW

**Comment by GaryQian** [comment]
google3 failures need to be patched first: https://fusion2.corp.google.com/presubmit/tap/436911147/OCL:436911147:BASE:436912137:1648104490959:5c96d64e/targets

Mostly involves removing the io.flutter.app.FlutterApplication usages in the AndroidManifests.

**Comment by chinmaygarde** [comment]
@GaryQian Any updates after your last comment in March? If we are not going to land this, can we close it?

**Comment by chinmaygarde** [comment]
cc @blasten

**Comment by GaryQian** [comment]
I'm currently landing large scale changes that remove v1 embedding from google3. I may try this change again soon as most of the first round of rosie changes have landed.

**Comment by chinmaygarde** [comment]
Any updates on trying to get rid of this code anytime soon? Closing it for now but feel free to re-open once progress can be made.

**Pull request closed without merging**
