### PR TITLE
Started waiting for the frame to complete before rasterizing the SkPicture.

### PR DESCRIPTION
**Pull request by gaaclarke**
relevant issue: https://github.com/flutter/flutter/issues/43085

This works because the SkPicture appears to be referencing items that aren't rendered yet.  By bouncing the capture task to the GPU thread before the IO thread we can guarantee that the SkPicture has rendered before capturing it.

### CODE REVIEW

**Comment by gaaclarke** [comment]
I talked to @jason-simmons.  It's not certain that this is safe.  My assumption was that the texture we were reading the data from was created solely as part of the toImage call.  It may be that the texture is the one backing the RepaintBoundary.  If the latter is the case we run the risk of the GPU and IO threads colliding still since the RepaintBoundary.  This PR would make the collision less likely but not guarantee no collision.

If that is the case we can move the logic back to the GPU thread or block the GPU thread until the capture is complete.  Since we would be waiting for a frame to execute before capturing on the io thread blocking the GPU thread might have no performance cost in most cases.

**Comment by brianosman** [comment]
I think the safest option may be to switch back to the old behavior, where the rendering happens on the GPU thread. Rendering on the IO thread's could have other side effects (creation of extra resources, additional shader compiles, etc...). Doing all the rendering work on the GPU thread's context will ensure that budgeting of all resources is accurately tracked, caches are shared/reused as much as possible, etc.

**Comment by gaaclarke** [comment]
> I think the safest option may be to switch back to the old behavior, where the rendering happens on the GPU thread. Rendering on the IO thread's could have other side effects (creation of extra resources, additional shader compiles, etc...). Doing all the rendering work on the GPU thread's context will ensure that budgeting of all resources is accurately tracked, caches are shared/reused as much as possible, etc.

I agree it's safe.  I want to explore this a bit further before we give up on it.  The problem with doing this on the GPU thread is that it interferes with normal rendering.  In particular latency time for first frame since we use ".toImage" as part of the warmup process.  It's particularly bad for high resolution screens where the glReadPixels takes a long time and we just throw out the results anyways.

I've tried to move ShaderWarmUp to a different function that doesn't do glReadPixels but there is resistance to change the API whatsoever.

**Comment by gaaclarke** [comment]
Closing PR.  This is not safe, see comment https://github.com/flutter/flutter/issues/43085#issuecomment-548493890

**Pull request closed without merging**
