### PR TITLE
Add heart beat integration tests for Observatory in sky_shell

### PR DESCRIPTION
**Pull request by johnmccutchan**
- Test accessing service protocol over http
- Test accessing service protocol over ws
- Test accessing an Observatory UI asset.

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@eseidelGoogle

**Comment by eseidelGoogle** [comment]
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter is where the new infra lives.  I need to add instructions on how to edit it. :(

TL;DR:

mkdir infra
cd infra
fetch infra
cd infra/build

Edit to your hearts content.

./scripts/slave/recipes.py run flutter/flutter
to run locally if necessary
./scripts/slave/recipes.py simulation_test train
to update results.

git commit -a -m "make things awesome"
git cl upload --bypass-hooks (their local presubmit is slow and not very useful).

Send me the review and I can CQ it.

https://github.com/luci/recipes-py/blob/master/doc/user_guide.md
can be helpful.  Mostly just searching through other recipes and for foo/api.py to see recipe module apis.

**Comment by eseidelGoogle** [comment]
You can also jsut check this in and I can wire in teh new infra.

@yjbanov FYI re: testing.

lgtm

**Comment by eseidelGoogle** [comment]
I don't think you want to check in the travis bits, they don't look sustainable.

**Comment by johnmccutchan** [comment]
@eseidelGoogle I've landed the bits into engine and am now fetching infra.

**Pull request merged**
