### PR TITLE
[scenario app] Update golden images for android

### PR DESCRIPTION
**Pull request by cyanglaz**
All the screenshots should look different now since https://github.com/flutter/engine/pull/2254
This PR updates them all

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM

**Comment by xster** [comment]
Are you sure this is right? The scenario app's readme seems to say the intended device size is 1680*1080. Or should we update the README?

**Comment by cyanglaz** [comment]
Oh I missed the README change in https://github.com/flutter/engine/pull/22540. @blasten Was the change intentional? Do we want all the screenshots to be 1680 * 1080?

**Comment by xster** [comment]
It doesn't really matter, but we want the thing to be hermetic and reproducible. Since you made the last source of truth, you can either change the goldens or change the README (and maybe the CI .ini)

**Pull request merged**
