### PR TITLE
[CP-stable][web:semantics] fix double click due to long-press

### PR DESCRIPTION
**Pull request by flutteractionsbot**
This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

https://github.com/flutter/flutter/issues/147050

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/blob/main/docs/releases/Hotfix-Documentation-Best-Practices.md) for examples

When semantics are enabled on Web, the `onTap` of various widgets (`GestureDetector`, `InkWell`) are called twice or the callback from one widget is called when another widget is pressed.

### Impact Description:
What is the impact (ex. visual jank on Samsung phones, app crash, cannot ship an iOS app)? Does it impact development (ex. flutter doctor crashes when Android Studio is installed), or the shipping production app (the app crashes on launch)

This causes multiple issues, e.g I have an `InputField` and a `InkWell` within the same page, tapping on the InputField executes the callback of the `InkWell`.

### Workaround:
Is there a workaround for this issue?

The workaround is to go through all clickable components and set `excludeFromSemantics: true`. Note that this is not always feasible when using external packages (those you don't have control over).

### Risk:
What is the risk level of this cherry-pick?

  - [x] Low
  - [ ] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [x] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

#### Steps to validate

1. Run the sample code below
2. Tap ONCE on the button

#### Expected results

The on tap callback is called once and `onTap` is printed once on the console:

```dart
onTap
```

#### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Semantics(
        enabled: true,
        child: Scaffold(
          body: Center(
            child: GestureDetector(
              onTap: () => print('onTap'),
              child: const Text('Click me'),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### CODE REVIEW

**Comment by christopherfujino** [comment]
@yjbanov do you think the impact of this bug/fix warrants a stable branch CP?

**Comment by yjbanov** [comment]
I think this one should be safe to CP. However, let's do our due diligence and clearly justify the CP in the description. @pedromassango Could you please write up a justification for the CP?

**Comment by pedromassango** [comment]
> I think this one should be safe to CP. However, let's do our due diligence and clearly justify the CP in the description. @pedromassango Could you please write up a justification for the CP?

Updated the form, to add more details, internally we've a Flutter web app that strongly depends on semantics and disabling it is not an option, which means we can't apply the workaround mentioned in the OP (and [here](https://github.com/flutter/flutter/issues/153924))

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by pedromassango** [comment]
@yjbanov sorry for pocking, 

Is there an eta for the cherry-pick to land on stable? Had a look at the [Flutter Cherry-pick Process](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request) and couldn't figure that out

**Comment by yjbanov** [comment]
@pedromassango That is a good question for @itsjustkevin. The release schedule is driven not by the web platform, but by the needs of all platforms, and I'm not fully looped into what else is going on. If you need it really really soon, consider patching the version of the engine that you are currently using, and building a custom one.

**Comment by itsjustkevin** [comment]
@pedromassango this cherry-pick has been merged, meaning that is in the queue for the next hotfix release. 

We aim to release hotfixes weekly where possible, but it is not a guarantee.  If you need the fix immediately, I suggest following the callout by @yjbanov.

**Comment by pedromassango** [comment]
> We aim to release hotfixes weekly where possible,

I am glad the week is (almost) over then 🎉 

> If you need it really really soon, consider patching the version of the engine that you are currently using, and building a custom one.

The problem is just that that doesn't seems too trivial to do... is there any doc as a starting point?

**Comment by shannon-rodricks** [comment]
@pedromassango 
Thank you for this!
Been facing an issue where automated tests were failing cause of this and wasnt able to identify the cause.

**Pull request merged**
