### PR TITLE
[Impeller] Only present async on Android.

### PR DESCRIPTION
**Pull request by jonahwilliams**
See https://github.com/flutter/flutter/issues/133506

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@chinmaygarde does this fix your validation issues?

**Comment by gaaclarke** [comment]
Let's combine this with adding the CI test to verify it.  I think we can get away with just running the colorwheel test with the playgrounds enabled.  Give me a sec and I an push a commit to this pr.

**Comment by chinmaygarde** [comment]
I still run into validation errors with this patch applied. @gaaclarke Were you able to work around the errors?

**Comment by gaaclarke** [comment]
> I still run into validation errors with this patch applied. @gaaclarke Were you able to work around the errors?

Haven't gotten a chance to look yet (sheriff duties, running into build differences between ci and locally and github hook issues).  I can check locally.  I was hoping to get it to show up on CI quick.

**Comment by gaaclarke** [comment]
Yay, it worked... as in it failed correctly.  There are still some validation errors showing up.

**Comment by jonahwilliams** [comment]
Task failed successfully?

**Comment by chinmaygarde** [comment]
I don't think this is necessary anymore. At least this didn't seem to help with the validation errors.

**Pull request closed without merging**
