### PR TITLE
Initial import from upstream Chromium of various classes/files for Win32 a11y

### PR DESCRIPTION
**Pull request by gw280**
This pulls in, unmodified, from upstream Chromium the following classes/files, which are required for the Win32 a11y work:

AXActivePopup
AXFragmentRootWin
AXPlatformRelationWin
AXPlatformNodeDelegateUtilsWin
AXPlatformNodeWin
Range
ScopedVariant
ScopedBstr
ScopedSafearray
EnumVariant
UiaRegistrarWin
VariantUtil
VariantVector
atl.h
atl_module.h
base_export.h

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
RSLGTM

**Review by cbracken — COMMENTED** [review]
Haven't reviewed the patch, but is this wired up to Flutter yet, or just a raw import of the code fixed up to compile and tests pass?

**Comment by gw280** [comment]
This is just a straight import of the code without building it or running tests. We've been structuring imports of Chromium code with an initial PR that pulls in the unmodified code as a baseline.

**Review by cbracken — CHANGES_REQUESTED** [review]
Please don't commit unless it's building or has tests running. Otherwise it's a recipe for bit-rot, and we'll have no idea when/if it breaks.

**Comment by cbracken** [comment]
Thanks for clarifying. In fairness, you did write "unmodified" in the PR description; but I'd incorrectly assumed this was the separate gwright-a11y branch.

lgtm

**Review by cbracken — APPROVED** [review]

**Pull request merged**
