### PR TITLE
Roll Skia

### PR DESCRIPTION
**Pull request by brianosman**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

licenses_golden/licenses_third_party needs to be updated

**Comment by brianosman** [comment]
Okay. I'm just going to wait for our infra team to double-check Fuschia.

**Comment by Hixie** [comment]
You'll need to update the licenses again, sorry. I just checked in a change that will invalidate the licenses update you did.

**Comment by tvolkert** [comment]
It looks like this introduced a regression in shadow rendering.  See the following animation of the before and after effects on card shadows:

skia-roll

**Comment by eseidelGoogle** [comment]
I can't tell which of those are better?  @jvanverth

**Comment by tvolkert** [comment]
The corners of the cards look off to me, but I'm by no means an expert :-)

**Comment by jvanverth** [comment]
This might be related to the changes I made to tweak colored shadows. I'll take a look.

**Comment by tvolkert** [comment]
Here's how it affects rounded shadows:

rounded-button

**Comment by cbracken** [comment]
Another example:
img_0415

**Comment by jvanverth** [comment]
Is this running on software or GPU?

**Comment by cbracken** [comment]
My screenshots were running on GPU (iPhone 7 plus device).

**Comment by tvolkert** [comment]
My screenshots are from:

```
GLES: Google (VMware, Inc.), Android Emulator OpenGL ES Translator (Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)), OpenGL ES 2.0 (3.0 Mesa 10.4.2 (git-))
```

**Comment by jvanverth** [comment]
Thanks, that probably means it's not the geometric shadow cache. We made a lot of changes since the last time you've rolled so it's not clear which one could have caused it. I'll do a bisect and see what I can figure out.

**Comment by chinmaygarde** [comment]
This doesn't require a roll back does it? This roll fixed a couple of issues.

**Comment by tvolkert** [comment]
No, the changes are small enough that we can fix forward.

**Comment by jvanverth** [comment]
I plugged in your lighting code into my test app and I'm not seeing any difference between the last roll and the current one. My guess is that this either has something to do with SKP playback (which I'm not sure if you're using or not) and/or the pixel ratio. The lighting code in PhysicalModelLayer doesn't seem to take the pixel ratio into account, which on higher-res displays could cause the sharpening you're seeing.

**Comment by eseidelGoogle** [comment]
Sounds like it's time to move this conversation into a new bug. :)  @tvolkert would you do the honor?

**Comment by tvolkert** [comment]
Filed https://github.com/flutter/flutter/issues/11035

**Pull request merged**
