### PR TITLE
[Impeller] Switched to static linked libc++ in vulkan validation layers.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/138535
test coverage: existing integration tests in flutter repo which look for validation layers

I also verified locally that the `libc++.so` is no longer present and that it runs correctly.

```
$ find lib/arm64-v8a/
lib/arm64-v8a/
lib/arm64-v8a//libflutter.so
lib/arm64-v8a//libVkLayer_khronos_validation.so
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm

IIRC there is a devicelab test that will cover this change. Does it still pass with this change?

**Comment by gaaclarke** [comment]
> IIRC there is a devicelab test that will cover this change. Does it still pass with this change?

Yep, there is.  I ran the equivalent locally.

**Comment by gaaclarke** [comment]
I locally checked the repo listed in the issue:
```
aaclarke-macbookpro3:amazon-chime-sdk-flutter-demo aaclarke$ ~/bin/flutter-android-debug-unopt-arm64 build apk --debug

Running Gradle task 'assembleDebug'...                             35.6s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
```

**Comment by gaaclarke** [comment]
I also validated that in the resulting file there is no external linkage from the validation layers to libc++:
```
aaclarke-macbookpro3:foo aaclarke$ find lib/arm64-v8a
lib/arm64-v8a
lib/arm64-v8a/libflutter.so
lib/arm64-v8a/libamazon-chime-sdk-machine-learning_jni.so
lib/arm64-v8a/libRSSupport.so
lib/arm64-v8a/libVkLayer_khronos_validation.so
lib/arm64-v8a/librsjni_androidx.so
lib/arm64-v8a/libc++_shared.so
lib/arm64-v8a/libamazon_chime_media_client.so
lib/arm64-v8a/librsjni.so
aaclarke-macbookpro3:foo aaclarke$ /opt/homebrew/Cellar/binutils/2.41/bin/greadelf -d lib/arm64-v8a/libVkLayer_khronos_validation.so

Dynamic section at offset 0x1a7b888 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libnativewindow.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x000000000000000e (SONAME)             Library soname: [libVkLayer_khronos_validation.so]
 0x000000000000001e (FLAGS)              SYMBOLIC BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x0000000000000007 (RELA)               0x2be8
 0x0000000000000008 (RELASZ)             2641632 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          110030
 0x0000000000000017 (JMPREL)             0x287ac8
 0x0000000000000002 (PLTRELSZ)           4344 (bytes)
 0x0000000000000003 (PLTGOT)             0x1a9bfc0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000006 (SYMTAB)             0x330
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x21f0
 0x000000000000000a (STRSZ)              2552 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1a70
 0x0000000000000004 (HASH)               0x1ae8
 0x0000000000000019 (INIT_ARRAY)         0x1a9b590
 0x000000000000001b (INIT_ARRAYSZ)       744 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x1a9b878
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffff0 (VERSYM)             0x1830
 0x000000006ffffffe (VERNEED)            0x19f0
 0x000000006fffffff (VERNEEDNUM)         3
 0x0000000000000000 (NULL)               0x0
```

**Comment by Fernandomr88** [comment]
Did this ship with 3.16.1?

**Pull request merged**
