### PR TITLE
Fix generateLockfiles running directory for documentation

### PR DESCRIPTION
**Pull request by utzcoz**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by utzcoz** [comment]
The `generateLockfiles` task is defined in `scenario_app/android/app/build.gradle`.

cc @dnfield @zanderso for reviewing.

**Review by dnfield — COMMENTED** [review]
Gradle knows how to find this task from the directory specified right

**Comment by utzcoz** [comment]
@dnfield Thanks for your reviewing. Yep, the Gradle can find `generateLockfiles` task in the directory contains `build.gradle`. But we need to add extra `--write-locks` to update generated `gradle.lock`. The `generateLockfiles` defined in `android/app` directory adds this command for all submodule that contains `build.gradle`, so it looks like more convinent to update Gradle generated lock files.

**Comment by utzcoz** [comment]
Hi @zanderso, could you help to give an extra reviewing for this PR? Looks like my PR needs at least two people's approvaling.

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
