### PR TITLE
restructure DL sources into sub-directories and new file naming conventions

### PR DESCRIPTION
**Pull request by flar**
The changes here should be 90% moving files around and adjusting #include statements to match, but there were a couple of housekeeping changes made in the name of being more transparent about Skia usage - mainly moving the "include all" types.h header file into the skia directory and forcing all of the other files in the main DL source directories explicitly include any Skia types they still depend on. That should help with finding where we can de-skia-fy in future passes.

### CODE REVIEW

**Comment by flar** [comment]
This will likely fail once the previous reorg of the DL sources is reverted: https://github.com/flutter/engine/pull/40161

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
The conflicts should go away after the Jims revert relands. The presub failures on the licenses are real though.

**Comment by flar** [comment]
This was dependent on another PR that had to be reverted. I'll have to rebase this one when the other relands, but this is otherwise ready to go (modulo some sorting of the license files).

**Comment by chinmaygarde** [comment]
sgtm

**Comment by flar** [comment]
This PR will eventually be landed, but it will need to be rebased on top of the "Sequester all Skia interactions" PR which has been landed and reverted a few times. I'm turning this PR into a draft until that other PR sticks the landing, at which point I'll do hopefully one last rebase of this PR on top of that and submit it for review.

**Pull request merged**
