### PR TITLE
Added application callback

### PR DESCRIPTION
**Pull request by bparrishMines**
This callback is necessary for receiving [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/ios/receive).

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
CC @mravn-google

**Comment by aam** [comment]
This seems to have broken the mac engine build https://build.chromium.org/p/client.flutter/builders/Mac%20Engine/builds/2944/steps/build%20ios_debug/logs/stdio

```
[308/333] OBJCXX obj/flutter/shell/platform/darwin/ios/libFlutter/FlutterAppDelegate.o
FAILED: obj/flutter/shell/platform/darwin/ios/libFlutter/FlutterAppDelegate.o 
/b/build/slave/goma_cache/client/gomacc ../../buildtools/mac-x64/clang/bin/clang++ -MMD -MF obj/flutter/shell/platform/darwin/ios/libFlutter/FlutterAppDelegate.o.d -DFLUTTER_FRAMEWORK -DNO_TCMALLOC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DTOOLCHAIN_VERSION=ae85410691b10aa2469695c2421b1fe751843e64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_HAS_JPEG_LIBRARY -DSK_HAS_PNG_LIBRARY -DSK_USE_SKCMS -DSK_HAS_WEBP_LIBRARY -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_AOT=1 -DSK_DISABLE_EXPLICIT_GPU_RESOURCE_ALLOCATION -DSK_DISABLE_RENDER_TARGET_SORTING -DSK_DONT_OPTIMIZE_SRC_PROFILES_FOR_SPEED -DSK_DONT_OPTIMIZE_DST_PROFILES_FOR_SPEED -I../.. -Igen -I../.. -I../../garnet/public -I../../topaz/public -Igen/garnet/public -Igen/topaz/public -I../../topaz -I../../third_party/dart/runtime -I../../third_party/skia/include/android -I../../third_party/skia/include/c -I../../third_party/skia/include/codec -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/atlastext -I../../third_party/skia/include/pathops -I../../third_party/skia/include/ports -I../../third_party/skia/include/svg -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -isysroot /Applications/Xcode9.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk -miphoneos-version-min=8.0   -fno-strict-aliasing -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wunguarded-availability -fvisibility=hidden -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -Wthread-safety -Os -fno-ident -fdata-sections -ffunction-sections -g2  -fvisibility-inlines-hidden -fobjc-call-cxx-cdtors -std=c++14 -fno-rtti -fno-exceptions -c ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm -o obj/flutter/shell/platform/darwin/ios/libFlutter/FlutterAppDelegate.o
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm:244:36: error: use of undeclared identifier 'userActivty'; did you mean 'userActivity'?
              continueUserActivity:userActivty
                                   ^~~~~~~~~~~
                                   userActivity
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm:239:43: note: 'userActivity' declared here
    continueUserActivity:(NSUserActivity*)userActivity
                                          ^
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm:238:1: error: conflicting return type in implementation of 'application:continueUserActivity:restorationHandler:': 'BOOL' (aka 'bool') vs 'void' [-Werror,-Wmismatched-return-types]
- (void)application:(UIApplication*)application
^  ~~~~
/Applications/Xcode9.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:429:1: note: previous definition is here
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray * __nullable restorableObjects))restorationHandler NS_AVAILABLE_IOS(8_0);
^  ~~~~
2 errors generated.
```

**Comment by aam** [comment]
Would you consider reverting it to unblock engine roll? cc @bkonyi

**Comment by bparrishMines** [comment]
Yea that's fine with me. I created a pull request
https://github.com/flutter/engine/pull/5377

**Pull request merged**
