### PR TITLE
Reland: [Impeller] adds a plus advanced blend for f16 pixel formats

### PR DESCRIPTION
**Pull request by gaaclarke**
Relands https://github.com/flutter/engine/pull/51589

The fix is in 74397bc171c74d2bfb24e82b47f2aa29d70c1711.  I couldn't figure out how to get a test in the engine to cover it.  The test is in the devicelab.

Here's what I attempted:
```c++
TEST_P(AiksTest, BlendModePlusAlphaColorFilterAlphaWideGamut) {
  if (GetParam() != PlaygroundBackend::kMetal) {
    GTEST_SKIP_("This backend doesn't yet support wide gamut.");
  }
  EXPECT_EQ(GetContext()->GetCapabilities()->GetDefaultColorFormat(),
            PixelFormat::kR16G16B16A16Float);

  Canvas canvas;
  canvas.Scale(GetContentScale());
  canvas.DrawPaint({.color = Color(0.1, 0.2, 0.1, 0.5)});
  canvas.SaveLayer({
      .color_filter = ColorFilter::MakeBlend(BlendMode::kPlus,
                                             Color(Vector4{1, 0, 0, 0.5})),
  });
  Paint paint;
  paint.color = Color(1, 0, 0, 0.5);
  canvas.DrawRect(Rect::MakeXYWH(100, 100, 400, 400), paint);
  paint.color = Color::White();
  canvas.Restore();
  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
@jonahwilliams please take a look.  I know you would like to see us use a different pixel format.  I think that sounds promising but it will be a bit of work to test and get 100% hooked up.  That's work we should evaluate against the body of other work we need to do.  It may not be worth pursuing immediately for just the plus blend.  Let me know if you want to try it sort it out over gvc if that doesn't sound good.

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
I do not think this is the correct approach. MTLPixelFormatBGRA10_XR should full solve the problem and only requires an update to skia's image codecs, instead of us maintaning a separate and slower blend mode implementation for wide gamut.

It also fixes alpha problems we haven't found yet.

**Review by jonahwilliams — APPROVED** [review]
LGTM

Discussed offline, summary:

* we're pretty sure this fixes plus, while the extended range fixed point needs more investigation. We may need clamping in shaders anyway with wide gamut wrt other color channels.

**Comment by gaaclarke** [comment]
Hmm the golden bot didn't issue any notice, did the approvals from the first landing follow over?  We can't blame force push this time.

**Comment by gaaclarke** [comment]
looks like it: https://flutter-engine-gold.skia.org/search?issue=51756&crs=github&patchsets=2, we're good

**Comment by gaaclarke** [comment]
I guess reverting prs should technically revoke golden approvals.

**Comment by jonahwilliams** [comment]
This was about a 2ms regression on the draw vertices benchmark GPU frame time: 

https://flutter-flutter-perf.skia.org/e/?keys=X93c991a1fc317e5dcb94d3d2b3a700cb&selected=commit%3D40057%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_frame_time%252Ctest%253Ddraw_vertices_perf_ios__timeline_summary%252C&xbaroffset=40057

**Pull request merged**
