### PR TITLE
Make android more lenient when it comes to out-of-order key event responses

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

Relaxes enforcement of key events being handled in order, to match similar code in the Linux and Windows implementations.

## Related Issues

- related to https://github.com/flutter/flutter/issues/73406

## Tests

- Added a test to make sure that a pending event is removed when handled.
- Added a test to make sure that out-of-order events are handled properly.

## Breaking Change

- [X] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Review by dkwingsmt — COMMENTED** [review]
The code looks great, although it doesn't seem to me that this PR include a test for handling out-of-order key events.

**Comment by gspencergoog** [comment]
OK, I think this is ready for another look.  I added a test that tests out-of-order response delivery.

**Comment by chinmaygarde** [comment]
@dkwingsmt: Can you take another look please?

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Pull request merged**
