### PR TITLE
Fail iOS engine creation if clang version is too new

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Validate that the version of clang used to build the iOS `Flutter.framework` matches the minimum version enforced by the tool on Flutter developers.  Currently, this is Xcode 11.0.

Locally when I build the engine, I see `Fuchsia clang version 11.0.0 (https://fuchsia.googlesource.com/a/third_party/llvm-project 7e9747b50bcb1be28d4a3236571e8050835497a6)`.  On the currently published framework artifacts, it's `Apple clang version 11.0.0 (clang-1100.0.33.8)`.

## Related Issues

See details at https://github.com/flutter/flutter/issues/49787.
Fixes https://github.com/flutter/flutter/issues/50387
https://github.com/flutter/flutter/issues/65901

## Checklist
- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Comment by jmagman** [comment]
Example at https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8867257145492712400/+/steps/Create_iOS_release_Flutter.framework/0/logs/execution_details/0

```

Executing command [
  '/opt/s/w/ir/cache/builder/src/flutter/sky/tools/create_ios_framework.py',
  '--dst',
  '/opt/s/w/ir/cache/builder/src/out/release',
  '--arm64-out-dir',
  '/opt/s/w/ir/cache/builder/src/out/ios_release',
  '--armv7-out-dir',
  '/opt/s/w/ir/cache/builder/src/out/ios_release_arm',
  '--simulator-out-dir',
  '/opt/s/w/ir/cache/builder/src/out/ios_debug_sim',
  '--dsym',
  '--strip',
]
```

**Comment by dnfield** [comment]
I think this is probably too restrictive, and will cause problems when we either roll Clang or roll Xcode (which roll independently of one another).

**Comment by dnfield** [comment]
For example, I think @chinmaygarde and @liyuqian are currently trying to get us on to Clang 12 for other reasons. Apple also can change their version string any which way they please.

Maybe it would make more sense to have this as part of a test on the CI for bitcode enabled uploads?

**Comment by jmagman** [comment]
> Maybe it would make more sense to have this as part of a test on the CI for bitcode enabled uploads?

That was my intention, though I guess I put it in the wrong place? As far as I could tell, this script is only run immediately before uploading the artifacts:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/5213?

Screen Shot 2020-10-05 at 2 24 07 PM

**Comment by jmagman** [comment]
I could only find its usage here, right before cloud storage upload:
https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#1188

**Comment by dnfield** [comment]
Ohh ok.  

You're right. But I'm still not sure string matching against 11.0.0 will be quite right.  It seems like it could easily have false positives or negatives.

**Comment by jmagman** [comment]
> Ohh ok.
> 
> You're right. But I'm still not sure string matching against 11.0.0 will be quite right. It seems like it could easily have false positives or negatives.

Yeah it seems a bit sloppy to just check for "11.0.0" (note it's parsing from the framework's [Info.plist](https://github.com/flutter/engine/blob/8f060b99547944606c9f5a7b1f0daea13b94f86e/build/copy_info_plist.py#L36), not from clang itself) but I'm not sure how else to tell.  I could try checking for `Apple clang version 11.0.0 (clang-1100.0.33.8)` explicitly, though when I built all the frameworks on my own machine the version was `Fuchsia clang version 11.0.0 (https://fuchsia.googlesource.com/a/third_party/llvm-project 7e9747b50bcb1be28d4a3236571e8050835497a6)` since it was using `clang++` version from the `third_party` buildtools.

**Comment by jmagman** [comment]
> Apple also can change their version string any which way they please.

Also, I wouldn't expect this to version change and this script to fail except when the version of clang running on the builder changes, so we don't have to make something super robust.

**Comment by jmagman** [comment]
Definitely open to suggestions as to where to move this and/or how to check the version.

**Comment by dnfield** [comment]
Will this fail if we roll Fuchsia clang to 12.0.0 on local builds?

**Comment by jmagman** [comment]
@dnfield It would only fail locally if you ran that script explicitly, maybe if you were changing the way the fat framework is built before upload. It won't fail you were building the engine locally with ninja and clang 12.  As far as I can tell it's not used in any `BUILD.gn` or any script in the engine repo, it's only used in that recipe. `$ grep -riI "create_ios_framework*"` returns nothing.

**Comment by dnfield** [comment]
Ahh ok, in that case, maybe we can just make the `print` in there give instructionsa bout what to do if you're intentionally upgrading Xcode and what needs to be considered?

**Comment by liyuqian** [comment]
> It won't fail you were building the engine locally with ninja and clang 12. As far as I can tell it's not used in any `BUILD.gn` or any script in the engine repo, it's only used in that recipe. `$ grep -riI "create_ios_framework*"` returns nothing.

Cool! My use case is just using ninja and clang 12 to build the engine locally :)

**Comment by chinmaygarde** [comment]
@jmagman: Is there any progress being made on this front?

**Comment by chinmaygarde** [comment]
Closing this as stale. Please reopen as necessary.

**Pull request closed without merging**
