### PR TITLE
Pylint + License Changes to Prep for Vuln Scan

### PR DESCRIPTION
**Pull request by sealesj**
This change extracts the pylint and associated license changes for OSV Vulnerability Scanning project into a separate change as per feedback on the vulnerability scanning PR.

This wrapper script allows for the "requests" dependency to be injected so that pylint can lint the `deps_parser*` files, which need that dependency.

Vulnerability Scanning PR for context: https://github.com/flutter/engine/pull/36506

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by godofredoc — COMMENTED** [review]
Are we missing the pylint script?

**Comment by godofredoc** [comment]
> @godofredoc I thought the pylint script is pylint_main which references pylint-2.7? I have those files in this PR

Thanks, after reloading I can now see the files.

**Review by zanderso — COMMENTED** [review]
Please comment in the PR description why this is needed.

**Review by zanderso — COMMENTED** [review]
Also, if these wrapper scripts are needed, they shouldn't be at the top level. They should be under `tools/`

**Comment by sealesj** [comment]
> Please comment in the PR description why this is needed.

Updated with explanation

**Comment by sealesj** [comment]
> Sorry, I'm not a python expert, but it looks like the `requests` library usage is for a single call to do an HTTP post to the vulnerability database. Are there any more built-in python libraries that can do an HTTP post request?

Ok, if these efforts are not encouraged then I will explore other approaches.

I have not used a different library myself, but I can research built-in approaches. This is just to use the linter on the two python files, so if another library works I'll be able to completely remove these changes.

**Comment by godofredoc** [comment]
> is ne



> Sorry, I'm not a python expert, but it looks like the `requests` library usage is for a single call to do an HTTP post to the vulnderability database. Are there any more built-in python libraries that can do an HTTP post request?

@zanderso do we foresee the need of adding dependencies to scripts in the future? this script is making it easier to add dependencies in the future although that may be a bad rather a good thing what do you think?

**Comment by zanderso** [comment]
> @zanderso do we foresee the need of adding dependencies to scripts in the future? this script is making it easier to add dependencies in the future although that may be a bad rather a good thing what do you think?

We've gotten pretty far with our existing python scripts without this mechanism for bringing in python dependencies, so I'd like to see a more obvious/pressing need before we do that. Alternately, at the point where we need to bring in non-trivial new python dependencies, we should consider instead writing in Dart.

**Comment by godofredoc** [comment]
> > @zanderso do we foresee the need of adding dependencies to scripts in the future? this script is making it easier to add dependencies in the future although that may be a bad rather a good thing what do you think?
> 
> We've gotten pretty far with our existing python scripts without this mechanism for bringing in python dependencies, so I'd like to see a more obvious/pressing need before we do that. Alternately, at the point where we need to bring in non-trivial new python dependencies, we should consider instead writing in Dart.

Sounds good, thanks for the context!

**Comment by sealesj** [comment]
@zanderso Thank you for the review. I'll go ahead and close this PR, remove the licensing + pylint changes from the vuln scanning PR, and move forward with the built-in http request approach.

**Pull request closed without merging**
