### PR TITLE
Fix build file typo.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by mikejurka** [comment]
LGTM

**Comment by krisgiesing** [comment]
This was my bad. How did this manage to pass my local build? Is the case sensitivity of the file system set incorrectly?

**Comment by chinmaygarde** [comment]
Were you on a case insensitive volume on the Mac? I usually work off of a separately created disk image for all work related repositories but I don’t think that workflow in documented in the contributing guide.

**Comment by krisgiesing** [comment]
I must have been.

Did I also break the Flutter Linux builds?

**Comment by chinmaygarde** [comment]
> Did I also break the Flutter Linux builds?

No. That target is not built on Linux.

**Pull request merged**
