### PR TITLE
Update licenses, and test that licenses are valid

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
Depends on https://github.com/flutter/buildroot/pull/41 and rolling buildroot.

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
@abarth I've merged the license script into this CL (unchanged from what you reviewed). I will tweak it until the tests pass. Let me know if you want to review it further before I check it in.

**Comment by abarth** [comment]
Nope, go for it.

**Comment by chinmaygarde** [comment]
This script cannot be run on Mac.

**Comment by Hixie** [comment]
What happens on Mac?

**Comment by chinmaygarde** [comment]
On a Mac: https://gist.github.com/chinmaygarde/acd824b59317dee7c454541ea69395aa

**Comment by Hixie** [comment]
Ah, you just need to add `.DS_Store` to the filter list of files we shouldn't consider.
https://github.com/flutter/engine/blob/master/tools/licenses/lib/main.dart#L57
Or alternatively, hard-code that file name here to be `metadata`:
https://github.com/flutter/engine/blob/master/tools/licenses/lib/filesystem.dart#L48

**Pull request merged**
