### PR TITLE
Remove the last remnants of CSS

### PR DESCRIPTION
**Pull request by abarth**
This patch also lets us remove FontFamilyNames, which is one of two
remaining clients of jinja2.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @eseidelGoogle

**Comment by eseidel** [comment]
I'm not sure which one of us is on vacation.  lgtm.

**Comment by abarth** [comment]
:)

**Comment by Hixie** [comment]
I don't even understand what most of that removed code does.

**Comment by abarth** [comment]
The removed code is mostly about two things:

1. Integrating SVG fonts with the normal font system (CSSFontSelector/CSSSegmentedFontFace/etc)
2. Batching queries to the font system when resolving CSS (FontBuilder)

We don't need (1) because we don't have SVG fonts.  We don't need (2) because our counterpart to resolving CSS is infinitely simpler and we just do the batching with a single if statement.

**Comment by Hixie** [comment]
Ah, SVG was the link I was missing.

**Pull request merged**
