### PR TITLE
Roll Dart SDK to b43da048c31a16b9993de1536406ed014ef73ffd

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
I verified the licenses.golden file changes and they all look good. However, you're going to have to also update the actual license file in the sky_engine package.

**Comment by abarth** [comment]
Mission accomplished

**Pull request merged**
