### PR TITLE
[Android] choose 24 bit depth buffer.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/158531

Make sure the onscreen framebuffer has a depth attachment that matches the depth24_s8 format expected.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by gaaclarke — APPROVED** [review]
nice!

**Comment by gaaclarke** [comment]
Wait, couldn't we have a golden test for this?

**Review by gaaclarke — CHANGES_REQUESTED** [review]
I'd like a test for this, putting a request change in until we have that answered.

**Comment by gaaclarke** [comment]
> we do not have android devices in the engine repo. I can add a unit test that the config contains depth 24.

Okay, I see how this worked.  That value is just a preference for `eglChooseConfig`:
```
EGL_DEPTH_SIZE
Must be followed by a nonnegative integer that indicates the desired depth buffer size, in bits. The smallest depth buffers of at least the specified size is preferred. If the desired size is zero, frame buffer configurations with no depth buffer are preferred. The default value is zero.
```

Should we instead be specifying a smaller bit depth?  Should we have a validation error if we get a frame buffer that doesn't have depth?

**Comment by gaaclarke** [comment]
A unit test would be nice.  Since we can't get a golden test I think we should at least have a validation error if we don't get a depth buffer since we assume we have one in order for impeller to work.

**Comment by jonahwilliams** [comment]
Part of the problem with golden testing this particular change is that it is just a request. On the mali devices we requested 8 bit stencil and 0 depth, but Mali doesn't support separate depth+stencil so it gives a D24S8. This happens to match what we need to render exactly and so things just work.

Whereas the Adreno support separate depth and stencil, so when we requested S8 it only gives us S8. Then onscreen clipping appears to not work because of the wonderful world of GL.

So we'd need specific hardware hooked up. Even then...

**Comment by gaaclarke** [comment]
> So we'd need specific hardware hooked up. Even then...

I mean we aren't even using the real opengles drivers.  Potentially ANGLE or SwiftShader could duplicate the Adreno behavior.  That's way out of scope though for this.

**Review by jonahwilliams — COMMENTED** [review]
@gaaclarke is this a test? does it run... somewhere?

**Review by gaaclarke — APPROVED** [review]
I don't have a good solution for testing this.  The following things would work but are out of scope:
1) setting up ANGLE to duplicate Adreno behavior (maybe not possible)
1) setting up SwiftShader to duplicate Adreno behavior (probably possible, but we don't use SwiftShader for opengles golden tests today)
1) Mocking out egl (this is a massive gutting that isn't as valuable as a golden test)

Looks like we might have a good log for this anyways via `IMPELLER_LOG_EGL_ERROR`

**Pull request merged**
