### PR TITLE
Preliminary fix for doing lerp properly to and from transparent color

### PR DESCRIPTION
**Pull request by mehmetf**
Fixes https://github.com/flutter/flutter/issues/10464.

### CODE REVIEW

**Comment by mehmetf** [comment]
I am not sure how to test this or whether this is the right way to go about it. Please advise.

**Comment by Hixie** [comment]
To test it we would add tests to:
https://github.com/flutter/engine/blob/master/testing/dart/color_test.dart

However, I am not sure this makes sense. Why would we want a different effect when lerping from fully transparent black than fully transparent green?

**Comment by mehmetf** [comment]
I thought about that as well... Transparent "black" is how we define "transparent" in Flutter/Material: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/colors.dart#L190.  I thought of 3 other approaches:

- Assume an alpha of 0 as lerping a transparent color so ignore its color component (i.e. transparent green, blue, black all behave the same). However, I feel like that might not be what we want to enforce as changing color and opacity down to 0 at the same time might be useful.

- We could massage the start/end values in ColorTween: https://github.com/flutter/flutter/blob/c44aa2665dcc45a524776f8f5c4f911703eb785c/packages/flutter/lib/src/animation/tween.dart#L212 . That feels even more hacky and still treats black transparent as special.

- Define a true transparent color with a possibly invalid value (or even null) and make sure all widgets are OK with this definition. 

The last one feels the most right but it is also fairly expensive. For instance, I did try use null as transparent color and one of the widgets immediately crashed.

How do you prefer to fix this?

**Comment by mehmetf** [comment]
There's a fourth one that you might actually like: Fix the original bug itself instead of going this deep.

In ExpansionTile, don't use ColorTween(start: transparent). Instead use ColorTween() and null-guard the starting color to Color.transparent.

**Comment by mehmetf** [comment]
The alternative is preferred, so closing this request.

**Pull request closed without merging**
