### PR TITLE
Add scenario_app to pub_get_offline.py

### PR DESCRIPTION
**Pull request by dnfield**
The pubspec was updated but not added here.

@godofredoc

### CODE REVIEW

**Comment by dnfield** [comment]
Argh. This doesn't quite work. 

@godofredoc - it's likely that we'll have to do the pub get for this as a build step that has a dependency on building the dart_pkg for sky_engine/sky_services. And we'll have to do it in a gen folder.

**Comment by zanderso** [comment]
@dnfield What's the reason it doesn't work?

**Comment by dnfield** [comment]
the sky_services/sky_engine packages aren't "real" until they're built using the dart_pkg build rule. So they have a pubspec, but they're missing important bits until after a build is run. Once that happens, they can be analyzed/compiled properly. Befor that you get failures. AFAIK, this is because they're taking over all the dart:* libraries.

**Comment by godofredoc** [comment]
Added the following deps["//flutter/sky/dist:sky_engine" and "//flutter/sky/dist:sky_services"] now I got these errors:
```
Command failed: ./clang_x64/dart /usr/local/google/home/godofredoc/flutter/engine/src/out/android_debug_unopt_x64/frontend_server.dart.snapshot --sdk-root /usr/local/google/home/godofredoc/flutter/engine/src/out/android_debug_unopt_x64/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --depfile /usr/local/google/home/godofredoc/flutter/engine/src/out/android_debug_unopt_x64/gen/flutter/testing/scenario_app/snapshot_aot_kernel.depfile.d /usr/local/google/home/godofredoc/flutter/engine/src/flutter/testing/scenario_app/lib/main.dart
output: result c51161a2-a1ce-453f-a1ed-b0415fb51330
Error: SDK root directory not found: flutter_patched_sdk/.
Error: SDK root directory not found: flutter_patched_sdk/.
Error: Error when reading 'flutter_patched_sdk/platform_strong.dill': No such file or directory
Error: Error when reading 'flutter_patched_sdk/platform_strong.dill': No such file or directory
../../flutter/testing/scenario_app/lib/main.dart: Warning: Interpreting this as package URI, 'package:scenario_app/main.dart'.
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:async'
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:collection'
../../flutter/testing/scenario_app/lib/main.dart:1:1: Error: Not found: 'dart:collection'
// Copyright 2013 The Flutter Authors. All rights reserved.
^
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:convert'
../../flutter/testing/scenario_app/lib/main.dart:6:8: Error: Not found: 'dart:convert'
import 'dart:convert';
       ^
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:developer'
../../flutter/testing/scenario_app/lib/main.dart:7:8: Error: Not found: 'dart:developer'
import 'dart:developer' as developer;
       ^
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:ffi'
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:_internal'
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:isolate'
../../flutter/testing/scenario_app/lib/main.dart:9:8: Error: Not found: 'dart:isolate'
import 'dart:isolate';
       ^
org-dartlang-untranslatable-uri:dart%3Acore: Error: Not found: 'dart:math'```

**Pull request closed without merging**
