### PR TITLE
Add package:tar to DEPS to fix broken 3H configurations

### PR DESCRIPTION
**Pull request by bkonyi**
Filed https://github.com/flutter/flutter/issues/135463 to track adding support for auto-updating this dependency as part of the SDK roll.

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Comment by aam** [comment]
nit regarding  "to fix broken roll": it's not the roll that is broken(engine uses prebuilt dart sdk, so missing dependency in engine's DEPS is not noticeable), rather the hhh buildbot on go/darto (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-host_debug_unopt/2855/overview example of the failure)

**Comment by bkonyi** [comment]
> nit regarding "to fix broken roll": it's not the roll that is broken(engine uses prebuilt dart sdk, so missing dependency in engine's DEPS is not noticeable), rather the hhh buildbot on go/darto (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-host_debug_unopt/2855/overview example of the failure)

Good point! I've updated the description.

**Comment by bkonyi** [comment]
@aam I've updated the PR to instead just add the entry to the list of auto-updated Dart pkg DEPS. It looks like `create_updated_flutter_deps.py` does correctly handle this URL once the entry in the DEPS file is present (confirmed locally with a fake revision update).

**Comment by a-siva** [comment]
> @aam I've updated the PR to instead just add the entry to the list of auto-updated Dart pkg DEPS. It looks like `create_updated_flutter_deps.py` does correctly handle this URL once the entry in the DEPS file is present (confirmed locally with a fake revision update).

Then why did the PR from @whesse (https://github.com/flutter/engine/pull/46190) not work ?

**Comment by bkonyi** [comment]
I'm not sure, but I did verify this works locally. There's nothing wrong
with the script as far as I can tell.

**Comment by aam** [comment]
> I'm not sure, but I did verify this works locally. There's nothing wrong with the script as far as I can tell.

I think as @whesse landed DEPS change to flutter/engine, dart sdk roll _without_ this tar dependency was incoming. So the create_updated_flutter_deps.py script that ran for that dart sdk roll(that ran after Bill's change in flutter/engine landed), removed tar dependency from the engine .

**Pull request merged**
