### PR TITLE
Replace arraysize macro with fml::size function

### PR DESCRIPTION
**Pull request by mdempsky**
This is forward compatible with std::size and similar to how Chromium
removed use of the arraysize macro.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Are you able to merge?

**Comment by mdempsky** [comment]
@chinmaygarde I don't believe so. I only see "Close and comment" and "Comment."

**Comment by chinmaygarde** [comment]
I'll merge this one. But, if you follow the guidance in the "Getting Started" section in [go/flutter-onboarding](go/flutter-onboarding), you should be added to the Flutter GitHub organization.

**Comment by mdempsky** [comment]
@chinmaygarde Thanks, didn't know about that doc. Will do.

**Pull request merged**
