### PR TITLE
Add missing focusable testing info

### PR DESCRIPTION
**Pull request by gspencergoog**
This adds a couple of instances of semantic node `isFocusable` info that were missing that the framework testing depends upon.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Can you add a Dart test for this in `//flutter/testing/dart`?

**Comment by chinmaygarde** [comment]
I believe the presubmit failure is the issue you are attempting to fix.

**Comment by gspencergoog** [comment]
Indeed, that is the error I am attempting to fix.

**Comment by gspencergoog** [comment]
Tests added (and I added one for `SemanticsAction` too).

**Pull request merged**
