### PR TITLE
Create scorecards-analysis.yml

### PR DESCRIPTION
**Pull request by godofredoc**
Enables scorecards code scanning for the engine repository. This will allow us to get automated security reports for flutter/engine using "OSSF Scorecards supply-chain security analysis"

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by godofredoc** [comment]
@zanderso this will enable security scans for the engine repo. It will look like this: https://github.com/flutter/flutter/security/code-scanning

**Comment by zanderso** [comment]
Is this the list of checks? https://github.com/ossf/scorecard#checks-1

Some checks won't understand our setup, like:

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
https://github.com/ossf/scorecard/blob/main/docs/checks.md#packaging
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast

Some of these might not ever make sense, like:

https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing

Other checks may also be problematic. I haven't done a full audit.

Is there some way to restrict the security checks to only those that make sense and/or understand our existing mechanisms?

**Review by zanderso — CHANGES_REQUESTED** [review]
I am not sure the full set of checks makes sense for this repo.

**Comment by godofredoc** [comment]
> I am not sure the full set of checks makes sense for this repo.
> https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool

I would categorize the checks in three buckets:

* Checks that do not apply to the repository. These can be disabled in the github UI during a security alert triage.
* Checks that are important but do not work well for a given repo e.g. pinned dependencies. For these we will contribute some checks to `score card` to make them useful for Flutter repos like teaching the tool to understand DEPs files and pubspec.yaml
* Checks that may be useful like sast, fuzz but that given the complexity of the engine build system they can not run from github actions. The idea here is to create LUCI builders that build the code, run the tools and report back to github security APIs.

I believe adding this tool to the flutter repos with the highest criticality scores(flutter, plugins, website, engine, flutter-intelij, etc) will help us create an initial baseline for design our security strategy.

**Comment by zanderso** [comment]
Is there some way to add this with all alerts disabled until we're ready to turn this on?

**Comment by godofredoc** [comment]
> Is there some way to add this with all alerts disabled until we're ready to turn them on one-by-one?
Unfortunately there is no way to turn off individual checks but having all of them enabled does not impact development workflows on any way. They only show up in security settings of the github ui, e.g. these are the results flutter/flutter https://github.com/flutter/flutter/security/code-scanning

**Comment by zanderso** [comment]
I'm worried less about development workflows than I am about:
1. The team being distracted thinking that this dashboard requires action to put into a good state when it isn't ready yet.
2. The community and users getting the wrong impression about e.g. static source code analysis, which we already do a lot of, but which isn't wired up to the dashboard.
3. The presence of failing checks that we will likely not ever be able to make work because they don't make sense, e.g. fuzzing.

Is there some way to restrict the visibility of the dashboard until it's something we can rely on for good information?

**Comment by Hixie** [comment]
The dashboard is already restricted in visibility.

**Comment by godofredoc** [comment]
> The dashboard is already restricted in visibility.
We can definitely contribute the code to enable/disable checks but it will take some time to land it and we would like to collect as much information as possible to guide our security strategy planning.

**Comment by zanderso** [comment]
> > The dashboard is already restricted in visibility.
> 
> We can definitely contribute the code to enable/disable checks but it will take some time to land it and we would like to collect as much information as possible to guide our security strategy planning.

Please keep me in the loop.

**Review by zanderso — APPROVED** [review]

**Comment by godofredoc** [comment]
> > > The dashboard is already restricted in visibility.
> > 
> > 
> > We can definitely contribute the code to enable/disable checks but it will take some time to land it and we would like to collect as much information as possible to guide our security strategy planning.
> 
> Please keep me in the loop.

Yes, I will. Thank you!

**Pull request merged**
