### PR TITLE
[web] force WebGL 1 on iOS

### PR DESCRIPTION
**Pull request by yjbanov**
This is a workaround for the issue described in https://github.com/flutter/flutter/issues/91333.

Fixes https://github.com/flutter/flutter/issues/89655

### CODE REVIEW

**Comment by technolion** [comment]
Is this going to be pulled into a stable 2.5.4 release?

**Comment by aytunch** [comment]
Our web app does not work on iPhone 13 Pro with iOS 15
Will this be added to the stable channel soon?
Also using WebGL 1 is not a real solution right? Is there a PR or issue which works on WebGl2 support?

**Comment by adrianjagielak** [comment]
> Our web app does not work on iPhone 13 Pro with iOS 15
> Will this be added to the stable channel soon?
> Also using WebGL 1 is not a real solution right? Is there a PR or issue which works on WebGl2 support?

Try this: https://github.com/flutter/flutter/issues/89655#issuecomment-936666189

**Comment by technolion** [comment]
I just checked: this PR now part of the current flutter stable (2.10.1) 🎉

**Comment by theAugur** [comment]
Is this on stable? I am still getting this problem with stable 2.10.2... My web app won't work on iOS safari unless I build it with: flutter build web --web-renderer html --release

**Comment by daonb** [comment]
iOS 15.4 fixed the safari bug and WebGL rendering works as it should.

**Pull request merged**
