### PR TITLE
Clarify file sharing flags in FML filesystem APIs on Windows

### PR DESCRIPTION
**Pull request by jason-simmons**
Use shared mode when requesting read access and exclusive mode for write access

### CODE REVIEW

**Comment by jason-simmons** [comment]
This may be related to the errors that ImpellerC is sometimes getting on LUCI when it opens the build output directory (see https://github.com/flutter/flutter/issues/116761)

**Comment by chinmaygarde** [comment]
Not sure how to interpret this TBH. Why should the file be allowed to be written or deleted as we access it? The exclusive access bit makes sense though.

**Comment by jason-simmons** [comment]
Currently the Windows implementation of `FilePermission::kRead` is specifying only `FILE_SHARE_READ`.  This means that Windows will refuse to open the file/directory if some other process has opened it for write access
(see https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea)

This seems too restrictive.  For something like ImpellerC's use of `fml::OpenDirectory` it is unnecessary to require that level of exclusivity just to get a read-only handle to a directory.  I suspect the same applies to other file/directory reading scenarios.

FML is not applying this kind of locking for file access on POSIX platforms.

**Review by chinmaygarde — APPROVED** [review]
LGTM as a speculative fix. Not sure how to test this but lets timebox something?

**Comment by jason-simmons** [comment]
Added a test to verify that `fml::OpenDirectory(FilePermission::kRead)` works if the directory has also been opened for writing on Windows

**Pull request merged**
