### PR TITLE
Make FlutterFragment usable without requiring it to be attached to an Android Activity. (Attempt 2)

### PR DESCRIPTION
**Pull request by ajmalk**
- call getContext instead of getActivity in FlutterActivityAndFragmentDelegate.onCreateView
- reattempt at https://github.com/flutter/engine/pull/27332 after it got reverted: https://github.com/flutter/engine/pull/27382

Fixes: https://github.com/flutter/flutter/issues/85326

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by xster — APPROVED** [review]

**Comment by dnfield** [comment]
This LGTM, but unfortunately we had another unrelated breakage in the build - you'd need to merge this up to head again (the fix just landed moments ago).

Alternatively, we could close this as a duplicate of https://github.com/flutter/engine/pull/27386

**Comment by ajmalk** [comment]
I just pulled and pushed.

**Comment by dnfield** [comment]
Ok, closed the PR I opened.

**Comment by ajmalk** [comment]
Looks like its failing again. I guess it isn't fixed at head?

**Comment by ajmalk** [comment]
Oh nvm it might just still be in progress.

**Review by blasten — APPROVED** [review]

**Pull request merged**
