### PR TITLE
Fix position of BackdropFilter above PlatformView

### PR DESCRIPTION
**Pull request by moffatman**
BackdropFilter above PlatformView was using the `local_cull_rect` as the area to filter. But if there was a transform above the BackdropFilter this doesn't put it in the right place. I changed it to `device_cull_rect` instead. It kind of breaks the stack/push metaphor but the `filter_rect` doesn't really fit within the context of the mutators stack (as it comes from a completely different stack).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by cyanglaz** [comment]
Can we add a concrete test that fails without the fix?

**Comment by moffatman** [comment]
I added a check of the rect pushed as a result of some layer tree with a transform. Without this change, the rect is (0, 0, 30, 30) instead of (1, 1, 31, 31).

**Comment by chinmaygarde** [comment]
@cyanglaz This looks good for a review. PTAL 🙏🏽

**Review by cyanglaz — APPROVED** [review]
LGTM

**Pull request merged**
