### PR TITLE
Install CIPD ninja using DEPS

### PR DESCRIPTION
**Pull request by Jwata**
Install CIPD ninja using DEPS

This is required to deprecate ninja binary in depot_tools. 
See https://crbug.com/1340825 and chromium/src's CL https://crrev.com/c/3869740 for more contexts.

### CODE REVIEW

**Review by zanderso — CHANGES_REQUESTED** [review]
I requested access to the doc since the crbug still had a couple of open discussion points and it sounds like those threads were moved to the doc.

**Comment by Jwata** [comment]
Thank you for the advice. 
I'm trying to pass the license check.

**Comment by Jwata** [comment]
The latest license check passed with the updated signature.  PTAL.

**Review by zanderso — APPROVED** [review]
lgtm

**Review by chinmaygarde — APPROVED** [review]

**Pull request merged**
