### PR TITLE
Makes PlatformViewsController view to use tracked event's action & pointer count

### PR DESCRIPTION
**Pull request by academy3746**
related issue https://github.com/flutter/flutter/issues/111268, https://github.com/flutter/flutter/issues/106190

### Motivation:
- At https://github.com/flutter/flutter/issues/111268, we found that Android PlatformView scrolls slowly after  #34182 commit

### Modification:
- Makes `PlatformViewsController` view to use `tracked event`'s action & pointer count

### Result:
- Now PlatformView scrolls not slowly
- Close https://github.com/flutter/flutter/issues/111268, https://github.com/flutter/flutter/issues/106190

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by toda-bps** [comment]
I have confirmed that this fix resolves flutter/flutter#111268 on [my device (HUAWEI MediaPad M5 SHT-W09)](https://github.com/flutter/flutter/issues/111268#issue-1367946293) 👍

**Comment by reidbaker** [comment]
Hey in our PR template there is a checklist of items that we expect to see. It looks like you have done most of them but I have added them back for you.

**Comment by reidbaker** [comment]
@mengdouer  @johnmccutchan @dnfield FYI this is a partial revert of https://github.com/flutter/engine/pull/34182/files

**Comment by chinmaygarde** [comment]
@academy3746 Are you able to make progress on this?

**Comment by jonahwilliams** [comment]
Friendly ping @dnfield and @johnmccutchan , it looks like this has a test but I can't vouch for it. PTAL

**Comment by camsim99** [comment]
@johnmccutchan can you take a look when you get a chance?

**Review by johnmccutchan — APPROVED** [review]

**Pull request merged**
