### PR TITLE
Roll src/third_party/dart 1402e8e1a42d.e21c4353006d (95 commits)

### PR DESCRIPTION
**Pull request by gaaclarke**
manual roll for: https://github.com/flutter/engine/pull/17383

git log 1402e8e1a42d..e21c4353006d665e7c4378413ad4d237f18437e0 --date=short --first-parent --format='%ad %ae %s'
2020-03-30 jsimmons@google.com [dart:io] Fuchsia version of SocketBase::AvailableDatagram
2020-03-30 jwren@google.com Fix the dart help test output by implementing printUsage() in the test command
2020-03-30 sstrickl@google.com [vm/aot] Drop some Function objects not needed at runtime.
2020-03-30 mit@google.com Roll pub to latest version
2020-03-30 scheglov@google.com Document differences in inheritance tests between CFE and analyzer.
2020-03-30 scheglov@google.com Revert "Fix the result type of binary expression with the left TypeParameter extends num type."
2020-03-30 johnniwinther@google.com [cfe] Handle member signatures from dill in class hierarchy builder
2020-03-30 eernst@google.com [cfe] Add missing .next in endImplicitCreationExpression
2020-03-30 jensj@google.com [CFE] Add api to get language version for uri
2020-03-30 johnniwinther@google.com [cfe] Don't include member signature in id testing by default.
2020-03-30 johnniwinther@google.com [kernel] Make verbose qualified names conditional in toStringInternal
2020-03-30 devoncarew@google.com [dartdev] test the dartdev analyze --fatal-warnings option
2020-03-30 brianwilkerson@google.com Enable omit_local_variable_types in analyzer_plugin
2020-03-30 brianwilkerson@google.com Enable omit_loval_variable_types in analysis_server_client
2020-03-30 brianwilkerson@google.com Enable omit_local_variable_types in analysis_server
2020-03-30 keertip@google.com Add guard code for exceptions from ResourceProvider when reading contents.
2020-03-29 scheglov@google.com Fix the result type of binary expression with the left TypeParameter extends num type.
2020-03-28 scheglov@google.com Fix for creating a setter when the target is in a part without a library.
2020-03-28 brianwilkerson@google.com Remove the need for a --corpus flag from completion_metrics
2020-03-28 brianwilkerson@google.com Remove the need for a --corpus flag from relevance_metrics
2020-03-28 brianwilkerson@google.com Remove an unused variable in AstBuilder
2020-03-28 brianwilkerson@google.com Sort non-generated files in analyis_server and add a test to ensure they stay that way
2020-03-28 scheglov@google.com Add LibraryElement.languageVersionMajor/Minor
2020-03-28 scheglov@google.com Report exceptions with the file content for getResult().
2020-03-28 scheglov@google.com Fix crash in index when the invoked element is multiply defined.
2020-03-28 eernst@google.com Add implementation of several parts of non-function type aliases
2020-03-28 johnniwinther@google.com [cfe] Groups standard tests in update_expectations.dart
2020-03-28 sra@google.com [dart2js] Specialize is- and as- tests for nullable types
2020-03-28 rmacnak@google.com [vm] Do not allocate when evaluating arguments to StorePointer.
2020-03-28 rmacnak@google.com [vm] Fix some data races with profiler samples.
2020-03-28 alexmarkov@google.com Revert "[analyzer] Remove deprecated language version API"
2020-03-27 nshahan@google.com [ddc] Cleanup cast in dart:_runtime lib
2020-03-27 brianwilkerson@google.com New relevance values for UriContributor
2020-03-27 brianwilkerson@google.com New relevance values for KeywordContributor
2020-03-27 brianwilkerson@google.com New relevance values for VariableNameContributor
2020-03-27 paulberry@google.com Migration: don't use union edges for field formal parameters
2020-03-27 rmacnak@google.com [vm] Fix memory leak in profiler when some samples are in native functions without a dynamic symbol.
2020-03-27 bkonyi@google.com [ package:dds ] Fixed smoke_test.dart which was unable to launch smoke.dart due to use of a relative path.
2020-03-27 zichangguo@google.com [dart:io] Fix parsing the response of the HTTP connect method
2020-03-27 mfairhurst@google.com [nnbd_migration] Add confirm dialog to "apply migration" button
2020-03-27 rmacnak@google.com [test] Update use of Null as a bottom type to Never.
2020-03-27 eernst@google.com Added new tests.
2020-03-27 alexmarkov@google.com [vm/nnbd/aot/tfa] Support NNBD strong mode in type flow analysis
2020-03-27 mfairhurst@google.com [analyzer] Remove deprecated language version API
2020-03-27 brianwilkerson@google.com Update relevance computations in LocalReferenceContributor
2020-03-27 brianwilkerson@google.com Update relevance values for LocalLibraryContributor and ImportedReferenceContributor
2020-03-27 sigurdm@google.com Bump pub version
2020-03-27 sigmund@google.com [dart2js] Update test-matrix to specify the libraries.json to dart2js batch runner
2020-03-27 jcollins@google.com Update dartdoc to 0.30.3.
2020-03-27 alexmarkov@google.com [vm/nnbd] Fix marking static fields as late
2020-03-27 scheglov@google.com Fix for completion in formal parameters of GenericFunctionType.
2020-03-27 mfairhurst@google.com [nnbd_migration] Add a "rerun from sources" button.
2020-03-27 mfairhurst@google.com Revert "[analyzer] Copy result of allSupertypes for now."
2020-03-27 scheglov@google.com Merge types during instance member inference.
2020-03-27 scheglov@google.com Catch linking exceptions and include the cycle file contents.
2020-03-27 johnniwinther@google.com [cfe] Handle throw in return type inference
2020-03-27 alexmarkov@google.com [vm/aot/tfa] Fix tracking of parameters in async_op closures
2020-03-27 zichangguo@google.com Reland "[dart:io] Fix hanging on zero-length datagram"
2020-03-27 athom@google.com [infra] Update checked-in SDKs to 2.8.0-dev.18.0
2020-03-27 johnniwinther@google.com [cfe] Add tool for updating all id-tests and expectation tests
2020-03-27 athom@google.com [homebrew] Add support for the beta channel formula
2020-03-27 brianwilkerson@google.com Sort files in analysis_server_client and analyzer_plugin and add tests to keep them that way
2020-03-27 askesc@google.com [benchmark] Benchmark for UTF-8 decoding with typical data.
2020-03-27 jensj@google.com [parser] Change recovery for constructor; report errors in bad constructors
2020-03-27 johnniwinther@google.com [cfe] Use legacy erasure before argument inference
2020-03-27 jensj@google.com [kernel] Polish toString implementation on AST nodes
2020-03-27 sra@google.com [dart2js] Print non-minified init object as multiline
2020-03-27 karlklose@google.com [infra] Handle test steps with no tested configuration
2020-03-27 zichangguo@google.com [dart:io] remove available at _NativeSocket::Read
2020-03-27 nbosch@google.com Remove a stale TODO comment
2020-03-27 rnystrom@google.com Add other breaking changes to CHANGELOG.
2020-03-27 liama@google.com [nnbd/test] Fix tests that are failing in strong mode
2020-03-26 rnystrom@google.com Fix Markdown link in CHANGELOG and remove duplicate entry.
2020-03-26 brianwilkerson@google.com Compute new relevance in LocalConstructorContributor
2020-03-26 kevmoo@google.com DEPS: remove references to pkg:package_resolver
2020-03-26 jcollins@google.com Add a way for analysis_server to open communication via a IsolateChannel.
2020-03-26 scheglov@google.com Use NNBD_TOP_MERGE to combine signatures of the inherited members.
2020-03-26 nshahan@google.com [ddc] Update types in JSArray operations
2020-03-26 srawlins@google.com Migrator: Add an auth token for the preview site
2020-03-26 dacoharkes@google.com [vm] Add Reachability Fence Instruction
2020-03-26 sra@google.com [benchmark] Make BigIntPrintParse be NNBD-agnostic
2020-03-26 rnystrom@google.com Bump the SDK constraint on dart_internal to permit Dart 2.8.0.
2020-03-26 kevmoo@google.com Update changelog with dart2js --package-root removal
2020-03-26 alexmarkov@google.com [vm/corelib] Specify types explicitly in convert_patch.dart
2020-03-26 scheglov@google.com Update checkForWrongTypeParameterVarianceInMethod(), fix NPE.
2020-03-26 mfairhurst@google.com [analyzer] Copy result of allSupertypes for now.
2020-03-26 scheglov@google.com Add  more data to debug crash in buildExportNamespace().
2020-03-26 scheglov@google.com Fix for crash when FieldFormalParameter in a local function has annotations.
2020-03-26 bkonyi@google.com [ VM / DartDev ] Disable DartDev for the 2.8 release
2020-03-26 kevmoo@google.com Remove unused package-root option and configuration from dart2js
2020-03-26 srujzs@google.com [dart:html] Add nullability to EventTarget conversion
2020-03-26 kevmoo@google.com DEPS: Bring in latest pub
2020-03-26 dacoharkes@google.com [vm/ffi] Mark Struct as entrypoint
2020-03-26 jensj@google.com [analyzer] Sort entries in error.dart and syntactic_errors.dart
2020-03-26 karlklose@google.com [infra] pkg/smith: custom test runner steps are test steps

### CODE REVIEW

**Comment by gaaclarke** [comment]
@jensjoha Something in this roll seems to have an unintended break in the dartanalyzer.  It seems to not be doing generics correct and is reporting:
```
A value of type 'num' can't be assigned to a variable of type 
T'. • flutter/testing/scenario_app/lib/src/animated_color_square.dart:102:16 • invalid_assignment`
```
[animated_color_square.dart](https://github.com/gaaclarke/engine/blob/9e984069d67e2df72b2a0ff7d96fcc3e1ecdb2a7/testing/scenario_app/lib/src/animated_color_square.dart#L102:L102).

The code looks fine to me.  I can't reproduce it locally on my machine (I get tons more errors for some reason), otherwise I'd help bisect.  Since you were working on the analyzer here I was hoping you might have some insight into what might have caused this.

**Comment by jensjoha** [comment]
@stereotype441 do you have insight?

**Comment by scheglov** [comment]
According to the language team this works as intended, even if this is a change from what analyzer used to do. The language specification only specializes `int + int/double`, and says nothing about `double + int` or `(T extend num) + int`. So, the result type of `_current + 1` is `num`. And because Flutter disabled implicit downcasts, an explicit cast is required. Update it like this:
```dart
_current = (_up ? _current + 1 : _current - 1) as T;
```

**Comment by gaaclarke** [comment]
This can't land because we need https://dart-review.googlesource.com/c/sdk/+/141662.  I'm going to close this PR and let the autoroller spawn a new one.

**Comment by gaaclarke** [comment]
Landing with luci-engine red.  The breaking change passed on the next commit.  I want to get the dart roller rolling again.

**Pull request merged**
