### PR TITLE
Upgrade all[most] androidx dependencies to latest

### PR DESCRIPTION
**Pull request by gmackall**
Upgrades every `androidx` dependency in the `src/third_party/android_embedding_dependencies` bundle to the latest version, except the `lifecycle` group*. Tested running a couple of apps as well because when updating these dependencies in the past I've been able to build the engine but then flutter run fail when trying to run an app.

Fixes https://github.com/flutter/flutter/issues/129307, also unblocks a feature that will eventually be needed for Scribe.

[*]`2.8.0` is the latest there, but I ran into an issue with dexing when I tried to upgrade, due to b/336164417, an AGP bug that had its fix backported to all >`8.0.0` versions, but we still support less than that so we will have to wait on that upgrade.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
I don't know enough about our build dependencies to truly LGTM this, but it looks good for my needs. The Scribe PR that needs this is https://github.com/flutter/engine/pull/52943, where I'd like to be able to call things like  [EditorInfoCompat#setStylusHandwritingEnabled](https://developer.android.com/reference/androidx/core/view/inputmethod/EditorInfoCompat#setStylusHandwritingEnabled(android.view.inputmethod.EditorInfo,boolean)). Thanks for doing this!

**Comment by yaakovschectman** [comment]
Looks good as far as I can tell, but I don't think I'm in the best position to actually approve it.

**Comment by eyebrowsoffire** [comment]
Revert reason: https://github.com/flutter/flutter/issues/149203

**Comment by gmackall** [comment]
Reason for revert: https://github.com/flutter/flutter/issues/149203

**Comment by eyebrowsoffire** [comment]
I'll make a manual revert

**Pull request merged**
