### PR TITLE
[Impeller] use host image upload path on simulator

### PR DESCRIPTION
**Pull request by jonahwilliams**
This might help with https://github.com/flutter/flutter/issues/126768#issuecomment-1554469333

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
We can probably give this a little more time but if it's not helping we should just revert it.

**Comment by jonahwilliams** [comment]
SGTM

**Pull request merged**
