### PR TITLE
[WIP] Windows DirectComposition PlatformViews

### PR DESCRIPTION
**Pull request by ds84182**
WIP. Lots of commented out code. Does not handle input, just visuals.

- [ ] Land needed buildroot changes for d3dallocator and spirv_cross
- [ ] Update Windows embedder template to disable the redirection bitmap on the root window where nothing is drawn
- [ ] Allow WindowSurface to control the presence of the redirection bitmap, ANGLE and DX12 do not need it but SW renderer does
- [ ] Separate compositor from WindowSurface, reuse with ANGLE
- [ ] Improve somewhat risky DirectComposition Visual reordering code

flutter/flutter#108486

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
Closing for now, @ds84182 is not actively working on this at this time.

**Comment by yaakovschectman** [comment]
@ds84182 We are looking into platform views for Windows at the moment. Would you be able to provide a high-level overview of how these changes could be used, or how we would interface with them from the framework and/or application side?

**Comment by ds84182** [comment]
> @ds84182 We are looking into platform views for Windows at the moment. Would you be able to provide a high-level overview of how these changes could be used, or how we would interface with them from the framework and/or application side?

Unfortunately these changes aren't a good base for implementing Platform Views. While it definitely does function, there are some unsolved issues regarding input. It is also wildly inefficient (high memory usage, memory bandwidth, etc.). Flutter needs better integration with DirectComposition to mitigate this.

See flutter/flutter#108486 and flutter/flutter#124457

**Comment by yaakovschectman** [comment]
For now, I think we need to investigate approaches we can use going forward for platform views on Windows. If we consider using DirectComposition for this, I think this PR would be useful as a resource to demonstrate how to incorporate it. Do you disagree as it may be too misleading toward an inadequate solution? If not, would you be able to explain how we would have been able to use this?

**Comment by ds84182** [comment]
> For now, I think we need to investigate approaches we can use going forward for platform views on Windows. If we consider using DirectComposition for this, I think this PR would be useful as a resource to demonstrate how to incorporate it. Do you disagree as it may be too misleading toward an inadequate solution? If not, would you be able to explain how we would have been able to use this?

Sure, this PR is a decent starting point. The resulting performance is way less than ideal and I would not recommend anyone use this for shipping an application intended to be used on any Windows laptop or tablet.

On the embedder side, the embedder would be responsible for providing a DirectComposition visual for what it wants to draw (this does not have to be a window, it can be a video surface). It may also supply a HWND to position behind the visual to accept input. The HWND can exist in a separate message loop within the same process, or inside another process. The same is true for visuals.

There is a major caveat with this: Win32 windows cannot be transformed. They are restricted to axis-aligned rectangles. Platform Views with an associated HWND will not be interactive when their visual undergoes a non-trivial transform. Translation and scale are fine, and they are pixel snapped.

Another caveat is lack of gesture input disambiguation for touch and pen. This one is described in more detail within the associated Github issue. It is impossible for Windows Platform Views to attain parity with the Android & iOS implementations due to this. Any attempts to workaround this will not go well, at all. I do not recommend even attempting it.

While Windows has an API for pointer routing, but I have not figured out how to make it work yet. See [IDirectManipulationCompositor2::AddContentWithCrossProcessChaining](https://learn.microsoft.com/en-us/windows/win32/api/directmanipulation/nf-directmanipulation-idirectmanipulationcompositor2-addcontentwithcrossprocesschaining).

**Comment by yaakovschectman** [comment]
Am I correct that the plugin would register the visual using `PlatformViewRegistrar::Register`? If so, once the visual is registered, what would be needed in order to display it within the application? I think we would still need to create a new widget type to represent this, in which case, how would the widget need to interact with the `PlatformViewWindows` instance to render it?

**Pull request closed without merging**
