### PR TITLE
Opt in fixtures to nullsafety

### PR DESCRIPTION
**Pull request by dnfield**
This resolves local issues I see compiling fixtures.

I have no idea why this works on CI and not in my local environment.

### CODE REVIEW

**Comment by cbracken** [comment]
Hrm. I'd have thought this shouldn't be necessary if we're passing the correct settings to the Dart runtime. Is there something else going on here, I wonder?

**Comment by dnfield** [comment]
I would have expected that to be the case, but it's consistently failing fo rme locally - I've tried nuking my out dir, and all .dart_tool directories.

**Review by cbracken — APPROVED** [review]
lgtm to get things passing, but we should figure out why things are broken; this shouldn't be necessary.

**Comment by cbracken** [comment]
Can you paste the failures you're seeing on the bug for future archaeologists (and current ones too)?

**Comment by dnfield** [comment]
e.g.

```
[19/82] ACTION //flutter/shell/common:_dsk__ds_shell_unittests_fixtures(//build/toolchain/mac:clang_x64)
FAILED: gen/flutter/shell/common/assets/kernel_blob.bin 
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/frontend_server.dart.snapshot --sdk-root /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/flutter/shell/common/assets/kernel_blob.bin --depfile /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/gen/flutter/shell/common/snapshot__dsk__ds_shell_unittests_fixtures.depfile.d /Users/dnfield/src/flutter/engine/src/flutter/shell/common/fixtures/shell_test.dart
Command failed: ./dart /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/frontend_server.dart.snapshot --sdk-root /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/flutter/shell/common/assets/kernel_blob.bin --depfile /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/gen/flutter/shell/common/snapshot__dsk__ds_shell_unittests_fixtures.depfile.d /Users/dnfield/src/flutter/engine/src/flutter/shell/common/fixtures/shell_test.dart
output: result ce3fb2a2-4c8c-4d25-96e3-29e9ab60cd8f
../../flutter/shell/common/fixtures/shell_test.dart:90:61: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  final PlatformMessageResponseCallback callback = (ByteData? data) {
                                                            ^
../../flutter/shell/common/fixtures/shell_test.dart:138:61: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
      PlatformDispatcher.instance.getPersistentIsolateData()!.buffer.asUint8List(),
                                                            ^
../../flutter/shell/common/fixtures/shell_test.dart:202:14: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    (ByteData? byteData) {
             ^
ce3fb2a2-4c8c-4d25-96e3-29e9ab60cd8f
+file:///Users/dnfield/src/flutter/engine/src/flutter/shell/common/fixtures/shell_test.dart
ce3fb2a2-4c8c-4d25-96e3-29e9ab60cd8f gen/flutter/shell/common/assets/kernel_blob.bin 3

[35/82] CXX obj/flutter/runtime/runtime_unittests.type_conversions_unittests.o^C
```

**Comment by dnfield** [comment]
The other file:

```
ninja: Entering directory `out/host_debug_unopt'
[1/5] ACTION //flutter/shell/platform/embedder:_dsk__ds_fixtures(//build/toolchain/mac:clang_x64)
FAILED: gen/flutter/shell/platform/embedder/assets/kernel_blob.bin 
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/frontend_server.dart.snapshot --sdk-root /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/flutter/shell/platform/embedder/assets/kernel_blob.bin --depfile /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/gen/flutter/shell/platform/embedder/snapshot__dsk__ds_fixtures.depfile.d /Users/dnfield/src/flutter/engine/src/flutter/shell/platform/embedder/fixtures/main.dart
Command failed: ./dart /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/frontend_server.dart.snapshot --sdk-root /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/flutter/shell/platform/embedder/assets/kernel_blob.bin --depfile /Users/dnfield/src/flutter/engine/src/out/host_debug_unopt/gen/flutter/shell/platform/embedder/snapshot__dsk__ds_fixtures.depfile.d /Users/dnfield/src/flutter/engine/src/flutter/shell/platform/embedder/fixtures/main.dart
output: result de07ab27-ebbf-46d7-a614-d757a77e98d2
../../flutter/shell/platform/embedder/fixtures/main.dart:82:17: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  final ByteData? args;
                ^
../../flutter/shell/platform/embedder/fixtures/main.dart:87:92: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  PlatformDispatcher.instance.onSemanticsAction = (int id, SemanticsAction action, ByteData? args) {
                                                                                           ^
../../flutter/shell/platform/embedder/fixtures/main.dart:229:47: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  final List<int> actionArgs = <int>[data.args!.getInt8(0), data.args!.getInt8(1)];
                                              ^
../../flutter/shell/platform/embedder/fixtures/main.dart:229:70: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  final List<int> actionArgs = <int>[data.args!.getInt8(0), data.args!.getInt8(1)];
                                                                     ^
../../flutter/shell/platform/embedder/fixtures/main.dart:240:73: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  PlatformDispatcher.instance.onPlatformMessage = (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                                                                        ^
../../flutter/shell/platform/embedder/fixtures/main.dart:240:112: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  PlatformDispatcher.instance.onPlatformMessage = (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                                                                                                               ^
../../flutter/shell/platform/embedder/fixtures/main.dart:241:13: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    callback!(data);
            ^
../../flutter/shell/platform/embedder/fixtures/main.dart:248:73: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  PlatformDispatcher.instance.onPlatformMessage = (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                                                                        ^
../../flutter/shell/platform/embedder/fixtures/main.dart:248:112: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
  PlatformDispatcher.instance.onPlatformMessage = (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                                                                                                               ^
../../flutter/shell/platform/embedder/fixtures/main.dart:249:20: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    var list = data!.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
                   ^
../../flutter/shell/platform/embedder/fixtures/main.dart:253:13: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    callback!(data);
            ^
../../flutter/shell/platform/embedder/fixtures/main.dart:261:29: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
      (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                            ^
../../flutter/shell/platform/embedder/fixtures/main.dart:261:68: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
      (String name, ByteData? data, PlatformMessageResponseCallback? callback) {
                                                                   ^
../../flutter/shell/platform/embedder/fixtures/main.dart:264:13: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    callback!(data);
            ^
../../flutter/shell/platform/embedder/fixtures/main.dart:588:58: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
    signalNativeCount(PlatformDispatcher.instance.locales!.length);
                                                         ^
de07ab27-ebbf-46d7-a614-d757a77e98d2
+file:///Users/dnfield/src/flutter/engine/src/flutter/shell/platform/embedder/fixtures/main.dart
de07ab27-ebbf-46d7-a614-d757a77e98d2 gen/flutter/shell/platform/embedder/assets/kernel_blob.bin 15
```

**Pull request merged**
