### PR TITLE
Add trace event slices for the duration in which the engine produces a pipeline item.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Matches the PipelineProduce slice.

screen shot 2016-08-30 at 3 14 16 pm

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Patched to now track the entire lifetime of a pipeline resource across multiple threads. @jason-simmons another look?

screen shot 2016-08-30 at 3 39 09 pm

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Thanks!

**Comment by eseidelGoogle** [comment]
There are a bunch of differnet event types supported by tracing in case it's useful.  Originally I thought these maybe shoudl be flow events, but after thinking more probably not:
https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.yr4qxyxotyw

**Comment by chinmaygarde** [comment]
We can't use all event types listed in that document because we eventually pass over all trace events to the Dart timeline. The Dart timeline only supports a small subset of the events listed in that document. The rest will be silently dropped. https://github.com/flutter/engine/blob/cdff6fa306ea014094943fbd5f58a263084a3155/sky/shell/tracing_controller.cc#L65

**Comment by eseidelGoogle** [comment]
It seems like we could easily fix the dart side if we decided one of the event types was useful. :)

**Pull request merged**
