### PR TITLE
Revert 78a8ca0f62b04fa49030ecdd2d91726c0639401f

### PR DESCRIPTION
**Pull request by gaaclarke**
Related issue: https://github.com/flutter/flutter/issues/43085
Reverts: 78a8ca0f62b04fa49030ecdd2d91726c0639401f

I had to hand massage this revert quite a bit.  I threw out the revert for the unit tests since we'll want to keep those.

This puts `toImage` back on the GPU thread.

### CODE REVIEW

**Comment by gaaclarke** [comment]
> LGTM. BTW, in the PR description, can you please also link to the golden test that's going to add to the framework just for reference?

I'm not sure which one you are referring to.  Please feel free to edit the description.

**Comment by liyuqian** [comment]
@gaaclarke : I'm referring to the golden test that we discussed yesterday to prevent the same issue to happen again. That golden test is likely to be running the reproduction app in flutter/flutter#43085 for many times and assert that `toImage` is not empty for all those runs.

**Comment by chinmaygarde** [comment]
Just catching up on the backlog of issues after my vacation. I have added a proposal for what we need from Skia to get back the performance improvement while also remaining thread safe to this issue https://github.com/flutter/flutter/issues/44148. We should figure out if that makes sense and consult the Skia team for guidance.

@liyuqian I thought the goldens were usually generated on a simulator. The simulator uses the software backend and that should never run into the cross context images issue. I may be wrong though. To not be susceptible to the rasterizer on the target, we should just write a ui_unittest for this. That allows for rasterizer selection and the default rasterizer uses OpenGL using SwiftShader.

**Comment by liyuqian** [comment]
@chinmaygarde : you're right, our normal golden test so far is only using Linux software backend so it wouldn't surface such cross-context issue. The `ui_unittest` sounds good to me if SwiftShader can surface that issue, although it's also using CPU in the end so I'm not 100% sure that it can. How about writing a flutter driver test that directly calls `toImage` on a real device, display that image, and take a snapshot? @gaaclarke : what's your preference here: write a `ui_unittest` or a Flutter driver test?

BTW, as we now have Skia golden, we should extend our golden tests to run on real GPUs instead of just running on the software backend. To my understanding, Skia's gold was mainly used to capture the GPU bugs as it doesn't require each pixel to match exactly. CC @Piinks @tvolkert @Hixie to see if we can do something to extend our golden coverage on real GPUs.

**Comment by liyuqian** [comment]
@chinmaygarde : you're right, our normal golden test so far is only using Linux software backend so it wouldn't surface such cross-context issue. The `ui_unittest` sounds good to me if SwiftShader can surface that issue, although it's also using CPU in the end so I'm not 100% sure that it can. How about writing a flutter driver test that directly calls `toImage` on a real device, display that image, and take a snapshot? @gaaclarke : what's your preference here: write a `ui_unittest` or a Flutter driver test?

BTW, as we now have Skia golden, we should extend our golden tests to run on real GPUs instead of just running on the software backend. To my understanding, Skia's gold was mainly used to capture the GPU bugs as it doesn't require each pixel to match exactly. CC @Piinks @tvolkert @Hixie to see if we can do something to extend our golden coverage on real GPUs.

**Comment by tvolkert** [comment]
> see if we can do something to extend our golden coverage on real GPUs

Our golden file tests run against `flutter_tester`, so we're not currently using them on device-based tests.

**Pull request merged**
