### PR TITLE
libtxt: change the host default font family to something more widely available

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by jason-simmons** [comment]
The framework and other callers are often hardcoding font families that may not be recognized by the platform's font manager (e.g. "Roboto") or are passing an empty font family.  The current policy maps these to a default font family defined for each platform.

**Comment by Hixie** [comment]
Can you elaborate on that? Is this default overridden for each platform, or...?

**Comment by jason-simmons** [comment]
Yes - the default is defined for each platform

**Comment by Hixie** [comment]
So why does the value changed in this PR matter?

**Comment by jason-simmons** [comment]
This value is used on platforms other than Android/iOS (in particular, flutter_tester running on host workstations).  The goal is to have a default font family that is more likely to be recognized in that environment.

**Comment by Hixie** [comment]
flutter_tester running on host workstations is typically only going to recognize Ahem, right?

What happens if the given font is not available?

**Comment by jason-simmons** [comment]
flutter_tester will match every font family with Ahem if the --use-test-fonts flag is enabled.

If --use-test-fonts is off, then libtxt will use one of Skia's font managers to resolve the font.  If that fails, libtxt will try the backup font family defined in this PR.  If that also fails, then libtxt layout will signal an error.

**Comment by Hixie** [comment]
How does font fallback fit into this story? e.g. if we use a glyph that isn't in the currently named font.

**Comment by jason-simmons** [comment]
Minikin requires a collection of fonts for each layout operation.  That collection will include the primary match for the requested font family, along with fallback fonts that handle characters that aren't covered by the primary font.  If layout encounters a character that still isn't covered, then libtxt will ask a Skia font manager to find a font that can match that character and add that to the fallback font set.

**Comment by Hixie** [comment]
So the only way this font here will be used is if the font manager failed to find any font that contained the glyph?

**Comment by jason-simmons** [comment]
This font family will be used if none of the font managers could find a match for the family name requested by the application

**Pull request merged**
