### PR TITLE
Allow providing max_cache_entry flag to Dart

### PR DESCRIPTION
**Pull request by jonahwilliams**
This flag is used to increase/decrease the size of the type check cache in native dart applications. This can be used to simulate the impact of running in an application that has many more subtypes of widget than a simple benchmark. This will allow us to determine whether it is worth making element generic to remove additional type checks

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@zanderso I don't believe we ever test these, but I'm unsure of what the usual justification is

**Comment by zanderso** [comment]
I think the test might be here https://github.com/flutter/engine/blob/main/shell%2Fcommon%2Fshell_unittests.cc#L522

**Comment by jonahwilliams** [comment]
even better, thanks!

**Review by zanderso — APPROVED** [review]
lgtm w/ ;

**Pull request merged**
