### PR TITLE
Only run firebase tests on HEAD

### PR DESCRIPTION
**Pull request by CaseyHillers**
https://github.com/flutter/flutter/issues/138835

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@godofredoc should the json files be marked as test exempt? If so, I can send a Cocoon PR. Otherwise, I'll request one after this is reviewed.

**Review by keyonghan — COMMENTED** [review]
Has the recipes CL been CP'ed?

**Comment by CaseyHillers** [comment]
> Has the recipes CL been CP'ed?

No, but this needs to land as well so we can verify at HEAD. We plan to create a new beta this week, so I'd like to be able to CP it in.

**Review by keyonghan — APPROVED** [review]
LGTM

**Pull request merged**
