### PR TITLE
Move //build and //build_overrides into the engine.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Just a test to see how far away we are from moving //build and //build_overrides. This version finishes `gclient sync` and `flutter/tools/gn`. Right now, there are some location collisions that need patches to the GN rules. They seem straightforward.

Each step is its own commit so it likely easier to review patch by patch after the rsync from the buildroot into the engine.

The tricky bit with our current approach is going to be to reconcile the directory structure in the secondary tree. It was a bit weird with glfw and the others we have already migrated.

Perhaps a good next step is to tackle something scarier like //third_party/dart or //third_party/skia.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @cbracken @matanlurey @zanderso @jason-simmons

**Comment by cbracken** [comment]
Skia might be an interesting next one. 

I think Dart is likely to be a lot more complex due to (a) a vague recollection that we reach into the Dart rules maybe to do kernel compiles for fixture tests that I think I added back in 2017 (b) handling both the binary Dart SDK and build-from source Dart SDK that I think @zanderso added.

**Comment by cbracken** [comment]
I could try giving skia a go.

**Comment by chinmaygarde** [comment]
Yeah, either Dart or Skia is fine. I have a feeling any repo where we don't control the GN rules is going to be a no-go unless we move the //build one level up. And that cannot be a gradual operation.

**Pull request closed without merging**
