### PR TITLE
Add libfreetype6-dev to desktop Linux dependencies

### PR DESCRIPTION
**Pull request by cbracken**
Required for Freetype 2.

### CODE REVIEW

**Comment by cbracken** [comment]
Don't we pull freetype2 sources? Maybe this is just because of the use of pkg-config?

**Comment by chinmaygarde** [comment]
> Don't we pull freetype2 sources?

We do. This should not be necessary. Maybe the desktop shell is depending on this somehow?

**Comment by cbracken** [comment]
I suspect these guys: https://github.com/flutter/buildroot/blob/c36bb971b4c11cd9136989ad5052d6f31521723d/build/config/linux/BUILD.gn#L26-L32

**Comment by cbracken** [comment]
Not a real blocker, but I think it's likely helpful until we've got rid of this (and likely the x11 one too).

**Pull request merged**
