### PR TITLE
Add a tip for webkit lldb formatter

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by xster** [comment]
Never mind, this script really doesn't work well. @abarth do you know if there's a an existing helper for this somewhere?

**Comment by abarth** [comment]
I'm not sure what this script is trying to do.  I haven't used lldb very much.

**Comment by xster** [comment]
It's just a helper function so we can just do `p someWtfString` or look at the variable directly in xcode's variable list instead of doing `p someWtfString.utf8().toStdString()` all the time

**Comment by abarth** [comment]
I don't know of any script that helps with that.

**Comment by eseidelGoogle** [comment]
That looks about right.  I would expect both the blink project and the webkit project have lldb scripts like that buried in them.

**Comment by chinmaygarde** [comment]
It seems like @xster is not sold on the utility of this PR. Can we close this?

**Comment by xster** [comment]
Ya, would be a nice utility but this script is a bit dated. Closing.

**Pull request closed without merging**
