### PR TITLE
Enable tracing on Fuchsia

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
With this patch, I'm running in to a build error in `//lib/trace_event` on this line:

```diff
diff --git a/tests/tracing_client_unittest.cc b/tests/tracing_client_unittest.cc
index c60011a..527f3c3 100644
--- a/tests/tracing_client_unittest.cc
+++ b/tests/tracing_client_unittest.cc
@@ -66,10 +66,7 @@ class TestTraceProviderRegistry : public ::tracing::TraceProviderRegistry {
   }
 
   void StartTracing(const mojo::String& categories,
-                    ::tracing::TraceRecorder* recorder) {
-    provider_->StartTracing(categories,
-                            recorder_bindings_.AddBinding(recorder));
-  }
+                    ::tracing::TraceRecorder* recorder) {}
 
   void StopTracing() { provider_->StopTracing(); }
 
```

/cc @j9brown @vosst

**Comment by chinmaygarde** [comment]
Was there a `DEPS` update to pull in `//lib/trace_event`? Otherwise, lgtm.

**Comment by abarth** [comment]
> Was there a DEPS update to pull in //lib/trace_event?

Nope.  This code is only for `is_fuchsia`, so we don't need DEPS.

**Comment by vosst** [comment]
Could reproduce the build issue, my bad. My local tree had https://fuchsia-review.googlesource.com/#/c/7860/ available, which makes the build pass.

Thanks for fixing the issue in https://fuchsia-review.googlesource.com/#/c/12118/1/tests/tracing_client_unittest.cc.

@abarth I added you as a reviewer to the overload CL.

**Pull request merged**
