### PR TITLE
[flutter_release] Fuchsia f5 release branch

### PR DESCRIPTION
**Pull request by CaseyHillers**
* Backported some .ci.yaml fixes
* Removed all non Fuchsia builders

https://github.com/flutter/flutter/issues/87075

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by godofredoc — COMMENTED** [review]
would it be possible to cherry pick the other two changes separately? I'm also curios if this will trigger all the builders in the file or Linux Fuchsia only?

**Comment by CaseyHillers** [comment]
> would it be possible to cherry pick the other two changes separately?

Sorry the diff came out confusing, what's critical is:

```yaml
  - name: Linux Fuchsia
    builder: Linux Fuchsia
    recipe: engine
    properties:
      add_recipes_cq: "true"
      build_fuchsia: "true"
      fuchsia_ctl_version: version:0.0.27
    timeout: 90
    scheduler: luci

  - name: Linux Fuchsia FEMU
    builder: Linux Fuchsia FEMU
    recipe: femu_test
    properties:
      add_recipes_cq: "true"
      build_fuchsia: "true"
      fuchsia_ctl_version: version:0.0.27
    timeout: 60
    scheduler: luci
```

I deleted the other targets to match what was done for F1.

> I'm also curios if this will trigger all the builders in the file or Linux Fuchsia only?

Once this lands, it'll enable presubmit on this branch but only the Fuchsia builders. In post submit, only the Fuchsia builders will run.

**Comment by CaseyHillers** [comment]
@jxson @arbreng is there a specific Flutter version I can pin Fuchsia F5 too? Linux Fuchsia FEMU is failing due to the tip of tree recipes not having the logic in this branch. We currently support [2.4](https://cs.opensource.google/flutter/recipes/+/master:recipes/femu_test_2_4_0.py) and [2.3](https://cs.opensource.google/flutter/recipes/+/master:recipes/femu_test_2_3_0.py)

**Comment by arbreng** [comment]
> @jxson @arbreng is there a specific Flutter version I can pin Fuchsia F5 too? Linux Fuchsia FEMU is failing due to the tip of tree recipes not having the logic in this branch. We currently support [2.4](https://cs.opensource.google/flutter/recipes/+/master:recipes/femu_test_2_4_0.py) and [2.3](https://cs.opensource.google/flutter/recipes/+/master:recipes/femu_test_2_3_0.py)

The F5 build used framework hash b1e1dd68aea2821c19c197bf455fbd4a08a6a4bf.  that is flutter-2.4-candidate.5, so we should pin to 2.4 I guess?

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by CaseyHillers** [comment]
Merging with failing Linux Fuchsia FEMU as tip of tree refactored the tests, and is not related to this PR

**Pull request merged**
