### PR TITLE
Share the GrContext between lightweight engines

### PR DESCRIPTION
**Pull request by gaaclarke**
Reverts https://github.com/flutter/engine/commit/27281c426f22c50e3cd339f62c32511922fa17b0, reenabling sharing of GrContexts.  It also takes advantage of the new test harness to ensure it is safe.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
@chinmaygarde @jason-simmons This PR has explicit unit tests for the AndroidGLContext and has a couple of threading models since we had concerns about merged threads.  There is also the existing test that creates and tears down the whole shell from https://github.com/flutter/engine/commit/20ec34e5288314a4b890d27c5374f278758c4693

If we wanted to go one step further we could tweak the logger to be able to capture the output to make sure no errors are being emitted.  I didn't go that far but checked locally that no errors were emitted.

**Comment by gaaclarke** [comment]
@chinmaygarde @jason-simmons I also forgot to mention that I kept the revert as a separate commit so if you want to look at the changes I made after the revert individually, you can.

**Review by jason-simmons — COMMENTED** [review]
@chinmaygarde Do you have any concerns about the `AndroidContextGL` destructor waiting on a task queued to the raster thread?

The `AndroidContextGL` will be deleted on the platform thread during destruction of the `PlatformView`

**Comment by gaaclarke** [comment]
friendly ping

**Review by chinmaygarde — APPROVED** [review]

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
