### PR TITLE
Convert Safari and Firefox wheel delta to physical pixels.

### PR DESCRIPTION
**Pull request by knopp**
Chrome on macOS seems to be using physical pixels when reporting scroll delta, while Safari and Firefox are reporting logical pixels. This makes scrolling on Safari and Firefox feel much slower even if there isn't any jank.

You can verify this by trying to scroll on non-hdpi screen where all browsers scroll with consistent speed.

This makes PR makes scrolling consistent with Chrome and partially fixes https://github.com/flutter/flutter/issues/75850

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by mdebbar** [comment]
Thanks for the contribution! Could you please add a test for your change so we can move the PR forward? This would be the right file to look at: https://github.com/flutter/engine/blob/main/lib/web_ui/test/engine/pointer_binding_test.dart

**Review by mdebbar — CHANGES_REQUESTED** [review]
Thanks for the contribution! Could you please add a test for your change so we can move the PR forward? This would be the right file to look at: https://github.com/flutter/engine/blob/main/lib/web_ui/test/engine/pointer_binding_test.dart

**Review by mdebbar — APPROVED** [review]

**Comment by knopp** [comment]
Thanks! Apologies, this completely slipped my mind.

**Comment by mdebbar** [comment]
@knopp no problem! We look forward to more of your contributions 🙂

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/35428

**Comment by knopp** [comment]
@mdebbar, seems like this now also needs to be done on Chromium?

**Pull request merged**
