### PR TITLE
[Impeller] demonstrate rendering bug with coverage hint.

### PR DESCRIPTION
**Pull request by jonahwilliams**
The position of this circle actually depends on the computed bounds hint, whereas I believe the semantics of the bdf are such that the position should not change.

By adding an item that changes the bounds hint positon, the rendering offset of the circle changes - whereas it should have alwas been in the changed position.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This doesn't actually fix the bug, i'm just throwing it out there so you can (hopefully) double check my math that this is broken

**Comment by bdero** [comment]
Based on the golden results and the matrix being applied to the BDF, the BDF matrix is being applied to the subpass texture's local space (which is always just a translation to offset the texture relative to the parent pass) rather than the screen space origin.

I don't think this is good behavior, and I agree that the _after_ results are the "consistent" behavior, but I would double-check that this behavior doesn't reproduce with Skia, since we've had a lot of drama with stuff like the Cupertino text magnifier being broken against more consistent behavior (which lead us to this solution).

**Comment by bdero** [comment]
This behavior reproduces as far back as: https://github.com/flutter/engine/pull/43990 (July 2023) when I wrote the original version of this test. Based on the [given BDF matrix](https://github.com/flutter/engine/pull/43990/files#diff-9322c6c147426e7e78989f16f0a142ecb8e603027646f22433b80aeced9d0c67R2922-R2926), the circle shouldn't actually be placed at the edge of the bigger circle.

**Comment by bdero** [comment]
An inverted version of the "global pass offset" that will be given to the subpass would need to be prepended [here](https://github.com/flutter/engine/blob/9b8421662ec98c009c98e4593383552b7d5631b9/impeller/entity/entity_pass.cc#L575) to make it work relative to global space.

Another possibility is that Skia's behavior is to do it relative to the bounds hint origin whenever one is supplied. In which case the inverter bounds hint origin would need to be prepended instead.

**Comment by chinmaygarde** [comment]
This was an attempt to turn on the goldens.

**Pull request closed without merging**
