### PR TITLE
Detect errors encoding method channel responses

### PR DESCRIPTION
**Pull request by robert-ancell**
## Description

Detect errors encoding method channel responses. The previous code didn't check for errors correctly.

## Related Issues

None.

## Tests

Added tests to check failures to encode responses.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
FLMethodChannel has tests; can you cover this with a new test?

**Comment by robert-ancell** [comment]
> FLMethodChannel has tests; can you cover this with a new test?

I don't think it's possible with the current code. The only way this error can be triggered is if the message codec used fails to encode the values passed to it. We only have the JSON and standard codecs and they both support all the possible value types passed to them (we don't yet support any custom types).

I only noticed this mistake when implementing the event channel which has a similar method. I've never actually seen an error like this.

**Comment by stuartmorgan** [comment]
> We only have the JSON and standard codecs and they both support all the possible value types passed to them

It should be easy to make a trivial codec in the test file that has the properties you want (e.g., `FLTerribleBoolCodec` which only accepts bool values, and fails to encode one of them).

**Comment by robert-ancell** [comment]
Oh, wait. We have `FlStringCodec`. I can use that.

**Comment by robert-ancell** [comment]
> FLMethodChannel has tests; can you cover this with a new test?

Tests added.

**Review by stuartmorgan — APPROVED** [review]
Thanks for adding the tests; LGTM!

**Pull request merged**
