### PR TITLE
Fix safe area reporting with transparent FlutterActivitys. (#46060)

### PR DESCRIPTION
**Pull request by matthew-carroll**
Fix safe area reporting with transparent FlutterActivitys. (#46060)

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@mklim please let me know if you have any good ideas for tests for this.

**Comment by matthew-carroll** [comment]
@mklim I think you're right about a framework golden test being the way to go. I filed https://github.com/flutter/flutter/issues/50375

**Comment by krmao** [comment]
please will this bug be fixed by which flutter version?  v1.12.13+hotfix.9 ?

**Comment by mklim** [comment]
@krmao this patch should have landed in Flutter `v1.15.4`. ["Where's my commit?"](https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F) is a general guide on how to figure out where a patch has rolled.

**Comment by krmao** [comment]
thank you very much! @mklim

**Pull request merged**
