### PR TITLE
[iOS] Fixes platform view clipped when FlutterView has non-zero offset

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixes https://github.com/flutter/flutter/issues/66968

cc. @cyanglaz .

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.
- [x] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @xster for review.

**Review by cyanglaz — COMMENTED** [review]
This will not handle when PlatformViews draw outside of the `ChildClippingView`.  

Is the issue (that this PR tries to solve) caused by `flutter_view_` is nil?

**Comment by cyanglaz** [comment]
I think the issue might not be with the maskView, but rather the frame of the platform view.

**Comment by zhongwuzw** [comment]
> I think the issue might not be with the maskView, but rather the frame of the platform view.

@cyanglaz Seems platform view's frame is correct, reverse offset of the `maskView` works for me.

**Review by cyanglaz — COMMENTED** [review]
The change looks good. It seems to be that it should produce the same result as 
`CGRect maskViewFrame = [flutter_view_ convertRect:flutter_view_.get().frame toView:clipView];` 

Could you explain why in this add to app scenario, it is different?

Can we add a test for this? Possibly a scenario test.

**Comment by zhongwuzw** [comment]
> The change looks good. It seems to be that it should produce the same result as
> `CGRect maskViewFrame = [flutter_view_ convertRect:flutter_view_.get().frame toView:clipView];`
> 
> Could you explain why in this add to app scenario, it is different?

I think the difference is we don't have to take flutter_view_'s frame origin x/y into account. 

> 
> Can we add a test for this? Possibly a scenario test.

I saw the scenario test code, seems it should not depend on flutter framework https://github.com/flutter/engine/blob/5d9509ae05/testing/scenario_app/README.md#scenario-app . I may need your help for adding test :)

**Comment by cyanglaz** [comment]
@zhongwuzw Thanks. The fix looks good to me.

As for the test, I don't think we need the framework to change the flutterView's frame. (If changing flutterView's frame is the way to reproduce the bug) Here we have access to the FlutterViewController: https://github.com/flutter/engine/blob/master/testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m#L98-L105

**Comment by zhongwuzw** [comment]
@cyanglaz Ahha, my mistake, I don't clean the Xcode Derived cache, think we should need Flutter framework wrongly, I added the scenario test. :)

**Review by cyanglaz — APPROVED** [review]
LGTM thanks for the PR!

**Pull request merged**
