### PR TITLE
[Impeller] Intel iOS Simulators must block on GPU completion.

### PR DESCRIPTION
**Pull request by jonahwilliams**
See also: https://github.com/flutter/flutter/issues/148660

Intel iOS simulators do not seem to enforce any backpressure on drawable acquisition. Fix this via blocking on completion in the surface_mtl.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
We should also perhaps set `-[CAMetalLayer setAllowsNextDrwabaleTimeout:NO]`. There appears to be a one second timeout today which may be being tripped?

**Comment by zanderso** [comment]
From PR review triage: This fix is waiting on verification on an intel mac.

**Comment by jason-simmons** [comment]
With this patch I'm still seeing flickering when running the `CircularProgressIndicator` app from https://github.com/flutter/flutter/issues/148660 on the Intel Mac Mini iOS simulator

**Comment by jonahwilliams** [comment]
@jason-simmons what if we change the waitUntilScheduled to waitUntilCompleted ?

**Comment by jason-simmons** [comment]
The animation runs smoothly on the simulator when using `waitUntilCompleted`.

`waitUntilCompleted` consistently blocks for at least 1/60th of a second.

**Comment by jonahwilliams** [comment]
Ok sounds like that is our best option. I can update this code to ifdef for intel sims

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
