### PR TITLE
[Impeller] Add polyline benchmark with lots of cubics and quads.

### PR DESCRIPTION
**Pull request by dnfield**
Adds a benchmark for creating polylines.

I have a WIP patch locally that vastly improves quadratics and should be extensible to improve cubics as well. Want to land this first to have some data about how much improvement we're talking about.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/36731

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by chinmaygarde** [comment]
Do the values of the control points of the curves matter to the benchmark? Perhaps you can generate them with something like a [Mersenne twister engine with a set seed](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine). Then have that seed be parameterized in the benchmark.

**Review by chinmaygarde — APPROVED** [review]

**Comment by dnfield** [comment]
The values should be stable from one run to another.

**Comment by dnfield** [comment]
I'm realizing we'll also want a benchmark that includes tessellation, since it may otherwise be hard to tell whether a point reduction will beh elpful or not.

**Comment by chinmaygarde** [comment]
> The values should be stable from one run to another.

With a specific seed, they will be.

**Pull request merged**
