### PR TITLE
Make FlutterFragment usable without requiring it to be attached to an Android Activity.

### PR DESCRIPTION
**Pull request by ajmalk**
- call getContext instead of getActivity in FlutterActivityAndFragmentDelegate.onCreateView

Fixes:  https://github.com/flutter/flutter/issues/85326

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by blasten — COMMENTED** [review]
could we add a test to verify that onCreateView doesn't call getActivity, but instead getContext?

**Comment by ajmalk** [comment]
> could we add a test to verify that onCreateView doesn't call getActivity, but instead getContext?

Yes I was looking into this but I can't seem to get the tests to run locally. Are there any docs to help with that? Currently I'm getting: 

```
There was 1 failure:
1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
java.lang.IllegalArgumentException: Could not find class [FlutterActivityAndFragmentDelegateTest.java]
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
        at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
        at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
Caused by: java.lang.ClassNotFoundException: FlutterActivityAndFragmentDelegateTest.java
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.junit.internal.Classes.getClass(Classes.java:42)
        at org.junit.internal.Classes.getClass(Classes.java:27)
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:98)
        ... 4 more
```

When I try to run `testing/run_tests.py --type=java --java-filter=FlutterActivityAndFragmentDelegateTest.java`

**Comment by blasten** [comment]
what about `io.flutter.embedding.android.FlutterActivityAndFragmentDelegateTest`?

**Comment by blasten** [comment]
actually, I'm seeing the same issue.  cc @dnfield  Is this related to recent changes?

**Comment by dnfield** [comment]
Make sure you build the target(s) first - run_tests.py used to do some of that for you but doesn't anymore because it messed up things on LUCI.

/cc @zanderso fyi

**Comment by ajmalk** [comment]
Do you mean just run `ninja -C out/android_debug_unopt`? I did that and it built fine. Tried running it again and it says "no work to do".

**Comment by dnfield** [comment]
Make sure to also build the `roboletric_tests` target there - `ninja -C out/android_debug_unopt robolectric_tests`.

Since the test script doesn't build that target for you anymore, we should really add it to the default Android build rule, at least for the case of armv7 debug.

**Comment by ajmalk** [comment]
The build ran correctly (I think). But I'm still the same java.lang.IllegalArgumentException when I try to run the test.

**Comment by dnfield** [comment]
That error sounds like there's something missing in the way the test is set up or decorated.

**Comment by ajmalk** [comment]
It's not a test I added fwiw. Are you saying it's broken at head? Are unit test not run by your presubmit? What should I do?

**Comment by dnfield** [comment]
I am able to run these tests at head :/. They run on the Linux android debug shard

**Comment by ajmalk** [comment]
Oh hmm. I'm trying to run on mac. I suppose I could try and run it on linux. Do you think that will help?

**Comment by dnfield** [comment]
I ran it locally on mac.

**Comment by ajmalk** [comment]
Hmm. I think some sort of instructions for setup would be helpful.

**Comment by dnfield** [comment]
This works for me from the `src` directory:

```
git -C flutter fetch upstream
git -C flutter merge upstream/master
gclient sync
./flutter/tools/gn --android --unopt --runtime-mode=debug
ninja -C out/android_debug_unopt
./flutter/testing/run_tests.py --type-java
```

**Comment by dnfield** [comment]
The only thing I can think of - this is all using JDK 1.8. For better or worse we use your system JDK and do not vend a JDK with the engine repo. I _think_ JDK 1.9 should work, but I'm willing to bet JDK 1.10/11/12 will not.

**Comment by dnfield** [comment]
So for me, `javac -version` shows `javac 1.8.0_221`

**Comment by ajmalk** [comment]
ok I changed the java version and that finally worked! Thanks. I'll send over the unit tests soon.

**Comment by ajmalk** [comment]
For reference I ran this from the src dir: 

```
./flutter/tools/gn --android --unopt --runtime-mode=debug
ninja -C out/android_debug_unopt
ninja -C out/android_debug_unopt robolectric_tests
./flutter/testing/run_tests.py --type=java --java-filter=io.flutter.embedding.android.FlutterActivityAndFragmentDelegateTest
```

**Comment by ajmalk** [comment]
And I had to install Java 8 by downloading it from the oracle website and manually editing my PATH.

**Comment by ajmalk** [comment]
Ok. I made sure there's test coverage. I opted to modify an existing test instead of adding a new one since that seemed appropriate in this case. Should I add/modify docs somewhere so people know FlutterFragment can be used without an Activity?  Or is too niche a use case?

**Review by dnfield — APPROVED** [review]
LGTM.

If you want to update docs that's fine, but AFAIK this use case was always intended to be supported and this code just slipped through the cracks.

**Comment by dnfield** [comment]
Waiting to apply the label on review from @blasten

**Review by blasten — APPROVED** [review]
LGTM

**Pull request merged**
