### PR TITLE
Check for a null pressure range for motion events

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/28490

### CODE REVIEW

**Comment by Hixie** [comment]
test?

**Comment by fishyer** [comment]
I still have this problem, my current version is 1.2.1, I already have this modification record, but it doesn't work.

**Comment by matthew-carroll** [comment]
@fishyer would you mind filing another bug, including your Flutter doctor output, along with your current crash log?

**Comment by fishyer** [comment]
@matthew-carroll this is flutter doctor output：

**Comment by fishyer** [comment]
@matthew-carroll this is my flutter doctor output ：
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

this is my crash log 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
        at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)
        at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)
        at android.view.View.dispatchTouchEvent(View.java:11788)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:1014)
        at com.ezbuy.android.publib.widget.refresh.EzRefreshLayout.dispatchTouchEvent(EzRefreshLayout.kt:87)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at com.ezbuy.android.publib.widget.BaseViewPager.dispatchTouchEvent(BaseViewPager.java:68)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3559)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
        at android.view.View.dispatchPointerEvent(View.java:12027)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5278)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5067)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4727)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4784)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4634)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4600)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4608)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4581)
```

this is my layout.xml
```
<com.ezbuy.android.publib.widget.refresh.EzRefreshLayout
        android:id="@+id/refresh_detail"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="visible">

        <androidx.coordinatorlayout.widget.CoordinatorLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.google.android.material.appbar.AppBarLayout
                android:id="@+id/appbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:fadingEdge="none"
                app:elevation="0dp">

                <com.ezbuy.android.home.FlutterContainerView
                    android:id="@+id/fr_flutter"
                    android:layout_width="match_parent"
                    android:layout_height="1000dp"
                    app:layout_scrollFlags="scroll"
                    tools:visibility="gone" />

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="51dp"
                    android:gravity="center_vertical"
                    android:paddingLeft="15dp"
                    android:text="Top Products"
                    android:textColor="@color/color_33"
                    android:textSize="17sp"
                    app:layout_scrollFlags="scroll" />

            </com.google.android.material.appbar.AppBarLayout>

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_detail"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="15dp"
                android:layout_marginRight="15dp"
                android:overScrollMode="never"
                app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        </androidx.coordinatorlayout.widget.CoordinatorLayout>

    </com.ezbuy.android.publib.widget.refresh.EzRefreshLayout>
```

the fr_flutter is my FlutterView's parent

**Comment by fishyer** [comment]
@matthew-carroll When I pull down, hold it down and slide it up for a while, it will definitely crash.

**Comment by matthew-carroll** [comment]
@fishyer Comparing your crash log with the current code in `FlutterView` doesn't seem to match up, which suggests that you're not using the latest version on master:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterView.java#L480

Can you please try this same situation with the latest version of master and report back with an updated crash log, or let us know if the issue is resolved?

**Comment by jkyeo** [comment]
## Same here when start FlutterActivity:
---
### device: Xiaomi5 running Android6.0
---
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.0)
[✓] Connected device (2 available)
```
---
crash log:
```
03-11 18:31:45.053 8566 8566 E AndroidRuntime: FATAL EXCEPTION: main
03-11 18:31:45.053 8566 8566 E AndroidRuntime: Process: com.liou.nettest, PID: 8566
03-11 18:31:45.053 8566 8566 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.View.dispatchTouchEvent(View.java:9955)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.SurfaceView.dispatchTouchEvent(SurfaceView.java:322)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.View.dispatchPointerEvent(View.java:10177)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4501)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4366)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4052)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4109)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3959)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3925)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3933)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3906)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6277)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6251)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6212)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6383)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.os.MessageQueue.nativePollOnce(Native Method)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.os.MessageQueue.next(MessageQueue.java:323)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.os.Looper.loop(Looper.java:142)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6321)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
03-11 18:31:45.053 8566 8566 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

**Pull request merged**
