### PR TITLE
[CP] Starts looking for the bdf fast path in relation to the snapshot_entity's transform (#55890)

### PR DESCRIPTION
**Pull request by gaaclarke**
cherry-picks https://github.com/flutter/engine/pull/55890

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
The target branch should be 3.27 not 3.26

**Comment by gaaclarke** [comment]
> The target branch should be 3.27 not 3.26

That's not the branch pointed to in https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version.  Is that out of date?

**Comment by zanderso** [comment]
> > The target branch should be 3.27 not 3.26
> 
> That's not the branch pointed to in https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version. Is that out of date?

Yes, it's out of date. The correct info is here https://github.com/flutter/flutter/issues/156508.

**Comment by gaaclarke** [comment]
> The target branch should be 3.27 not 3.26

Done.

**Comment by gaaclarke** [comment]
> Yes, it's out of date. The correct info is here [flutter/flutter#156508](https://github.com/flutter/flutter/issues/156508).

FYI the cherry-pick template points to https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version as being the source of truth.

**Review by zanderso — APPROVED** [review]

**Comment by gaaclarke** [comment]
@zanderso What's the protocol for this, do you want me to merge it?  I was expecting someone else to do it as part of the process for reviewing cp request.

**Comment by zanderso** [comment]
No action needed. The release team will manage merging it in time for the next beta hotfix release.

**Pull request merged**
