### PR TITLE
Re-enable the Wuffs GIF decoder

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/23838

### CODE REVIEW

**Comment by LeonScroggins** [comment]
@nigeltao just [updated](https://skia-review.googlesource.com/c/skia/+/226476) the version of Wuffs that Skia uses, which broke the Skia roll, because SkWuffsCodec.cpp has a preprocessor line that enforces using the latest (or at least a recent) version of Wuffs. I've reverted for now, but @jason-simmons, can you update your Wuffs so that we can reland?

(Also, should we learn how to update flutter's Wuffs so we can avoid this issue in the future?)

**Comment by jason-simmons** [comment]
Flutter is taking its version of Wuffs from https://fuchsia.googlesource.com/third_party/wuffs/

Updating it involves doing a merge of the appropriate Wuffs commit into that repository:
    https://fuchsia-review.googlesource.com/c/third_party/wuffs/+/300278

And then updating the Flutter engine's `DEPS` to point at the merge commit.

**Comment by jason-simmons** [comment]
Another option would be moving the Flutter Wuffs `BUILD.gn` file into `build/secondary/third_party` and then having Flutter's `DEPS` use the same Wuffs URL as Skia's `DEPS`.

This would simplify Skia->Flutter rolls.  Would it cause any issues for Flutter->Fuchsia rolls?

@chinmaygarde

**Comment by jason-simmons** [comment]
Moved the build script into `build/secondary` and rolled Wuffs to the version that Skia will be using:
    https://github.com/flutter/engine/commit/bcde838d778eecd39282cfb84ebba1d484bb7515

It should be safe to roll Wuffs forward in the Skia tree now.

**Comment by LeonScroggins** [comment]
Thanks!

**Comment by nigeltao** [comment]
Thanks for fixing.

In the future, what's the recommended process or ordering (for Skia, Flutter, and Fuchsia updates), if I want to once again upgrade the Wuffs version that Skia uses? It's still a manual process, similar to https://github.com/flutter/engine/commit/bcde838d778eecd39282cfb84ebba1d484bb7515, right?

Is the easiest thing just to CC you on Skia CLs like https://skia-review.googlesource.com/c/skia/+/226476

**Comment by jason-simmons** [comment]
The Wuffs commit in Flutter's DEPS will need to be updated to match the commit in Skia's DEPS:
    https://github.com/flutter/engine/blob/master/DEPS#L393

For now, you can CC me on updates.  Eventually it should be possible to automatically apply these changes in the Skia->Flutter roller.

**Comment by nigeltao** [comment]
Making a 1-liner change to Flutter's DEPS sounds easy. Does Flutter use GitHub PRs or does it use some other code review process (e.g. Gerrit)?

**Comment by jason-simmons** [comment]
We use GitHub PRs: https://github.com/flutter/engine/pulls

**Comment by nigeltao** [comment]
A tangential question: https://github.com/flutter/engine/blob/master/DEPS#L393 starts with `Var('skia_git')`. Should we change `skia_git` to `github_git` and cut out the middleman, since the canonical Wuffs repository is on GitHub: https://github.com/google/wuffs

**Comment by jason-simmons** [comment]
Either is fine.  I used `skia_git` so that the URL that Flutter pulls from would exactly match the URL used by Skia.  But if Skia's repository is just a mirror then we could just pull from the original.

**Comment by nigeltao** [comment]
OK, I'll leave it as is.

**Pull request merged**
