### PR TITLE
Revert "Refactor NDK helpers some more, add methods for SurfaceControl/Transaction, tests"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/engine#50540

There's something wrong with this on armeabi_v7a API 24 devices like the moto g4s in the lab.

Will let us restart the roll (https://github.com/flutter/flutter/issues/143342)

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
I don't understand why this is affecting goldens. The original PR did not.

**Comment by zanderso** [comment]
I'm seeing similar issues on other PRs (like on https://github.com/flutter/engine/pull/50571). I'm wondering if the golden tests might be producing slightly different output across runs.

**Comment by jonahwilliams** [comment]
I've marked the fix forward as autosubmit. i'll restart the roller once that lands

**Comment by dnfield** [comment]
Fix forward is looking good

**Pull request closed without merging**
