### PR TITLE
Do not dispatch UI events if they arrive after the FlutterView has been destroyed

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/7234

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde @abarth

**Comment by jason-simmons** [comment]
The call into the null native object is happening inside auto-generated JNI wrappers.

**Comment by chinmaygarde** [comment]
Ah, I see. That makes sense. lgtm.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
