### PR TITLE
Add elevation and thickness to SemanticsNode

### PR DESCRIPTION
**Pull request by goderbauer**
Required for https://github.com/flutter/flutter/pull/25670.

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Can we land this?

**Comment by goderbauer** [comment]
@chinmaygarde The framework-side of this change is not reviewed yet.

**Comment by Hixie** [comment]
tests?

**Comment by goderbauer** [comment]
I don't think we have a sensible way of testing this particular part :(

**Pull request merged**
