### PR TITLE
Use uncompressed image size as the basis for the fuzzy pixel matching threshold in the Skia Gold scenario tests

### PR DESCRIPTION
**Pull request by jason-simmons**
Previously this script was using the size of the compressed PNG file.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
LGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/34431

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/106673#issuecomment-1172650272

**Comment by chinmaygarde** [comment]
This needs to be rebased to run presubs again. But the expectation is that this is good to land.

**Comment by skia-gold** [comment]
Gold has detected about 19 new digest(s) on patchset 1.
View them at https://flutter-engine-gold.skia.org/cl/github/34431

**Pull request merged**
