### PR TITLE
Add system-level routing

### PR DESCRIPTION
**Pull request by abarth**
We now respect the "route" field in Intents to load a route other than '/'.
Also, use popRoute rather than events to indicate that the framework has asked
us to go back.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @chinmaygarde

**Comment by j9brown** [comment]
One thing to keep in mind.  We have had security issues in Android before
where intents were able to launch activities in unintended ways.  For
example, accessing a fragment of the settings activity and passing
dangerous parameters.

You might want to consider which routes should be publicly exported as
opposed to those which should only be accessed internally by the
application pushing them onto the stack itself.

**Comment by abarth** [comment]
Interesting.  There's already a distinction between named and unnamed routes, but maybe we should have another layer that firewalls even named routes.

One of the original goals of this project was to make the world of mobile apps more linkable, which argues for having lots of public routing, but there are clearly security factors we'll need to balance.

**Comment by Hixie** [comment]
Can you elaborate on the security issues?

**Comment by j9brown** [comment]
Here's an example of the problem:
https://securityintelligence.com/new-vulnerability-android-framework-fragment-injection/

Flutter routes could conceivably manipulated in similar ways.  Although
most uses will be harmless we want to think carefully about the potential
entry points into an application.

Jeff.

**Comment by Hixie** [comment]
LGTM minus onPushRoute.

**Pull request merged**
