### PR TITLE
[web] Fix CapsLock keyevent

### PR DESCRIPTION
**Pull request by ferhatb**
## Description
The web engine, to prevent the crash and keep Tab key working no matter what the lock state is, sets metastate for locks during keydown until handling at framework level is clarified.

metaState as part of RawKeyEvent is currently not making a clear distinction between modifiers and lock states. For example the code requires that NumLock state be true when user presses NumLock key (it will crash otherwise). The lock state on the other hand, won't be set in a browser until keyup on some platforms (see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState).

Past issues,PRs related to this:
#45250
#46718
flutter/engine#14165

So if engine interprets metaState as persistent lock state such as NumLock, shortcuts break since the matcher will fail since there is no entry for NumLock+Tab or CapsLock+NumLock+Tab for example. Ideally? shortcuts should only consider lock states if it is explicitly provided to add specificity. The ambiguity of NumLock+key needs to be resolved to either mean Option1: a key is pressed when in NumLock state or Option2: key is pressed in combination with NumLock key at the same time. It should still allow a developer to distinguish between them by tracking keydown/keyup events.

## Related Issues

https://github.com/flutter/flutter/issues/66601

## Tests

Added test case to e2etests/web/regular_integration_tests/test_driver/text_editing_integration.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Comment by nturgut** [comment]
Question: which framework integration test covers this case?

**Comment by ferhatb** [comment]
> Question: which framework integration test covers this case?

Should be added to Tab e2e test after engine PR is in.

**Review by mdebbar — APPROVED** [review]

**Review by nturgut — APPROVED** [review]
As discussed earlier, the e2e test can also go in with this PR.

LGTM.

**Comment by ferhatb** [comment]
> As discussed earlier, the e2e test can also go in with this PR.
> 
> LGTM.

Added test case to e2etests/web/regular_integration_tests/test_driver/text_editing_integration.dart

**Review by nturgut — APPROVED** [review]
Thanks for adding the integration test :)

**Pull request merged**
