### PR TITLE
Grammatical mistake on pull request template

### PR DESCRIPTION
**Pull request by Abhishek01039**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

### CODE REVIEW

**Comment by Hixie** [comment]
I guess it should really be "test-exempt". "tested exempt" would mean that we've tested it in some way, which is the opposite of what this means. :-)

**Comment by Abhishek01039** [comment]
what about this 
```PR  test exempt. ```
@Hixie

**Comment by MrBirb** [comment]
Actually there is no grammatical mistake here.

**Comment by Abhishek01039** [comment]
@Hixie 
I have changed to this ```PR is test-exempt```.
After doing some discussion on discord with @MrBirb.

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
FWIW, this also exists in flutter/flutter, flutter/plugins, and flutter/packages

**Comment by Abhishek01039** [comment]
Ok Then I will do all three repos.

**Comment by Abhishek01039** [comment]
I am not able to find this syntax in flutter/plugins
@Hixie

**Comment by Hixie** [comment]
It's there, sixth checkbox of https://github.com/flutter/plugins/blob/master/.github/PULL_REQUEST_TEMPLATE.md :-)

**Comment by Abhishek01039** [comment]
Ah Thank.

**Comment by stuartmorgan** [comment]
"test exempt" is a compound adjective that is after the noun it is modifying, so this was correct before.

**Pull request merged**
