### PR TITLE
Issue #146080 : Fix for incorrect STB based atlas glyph scaling

### PR DESCRIPTION
**Pull request by johnoneil**
Fixes issue [#146080](https://github.com/flutter/flutter/issues/146080)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bdero** [comment]
Hey @johnoneil, it looks like you just need to apply the formatting listed under the failed builder (`Linux linux_unopt`): https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8751644795522118369/+/u/test:_test:_Check_formatting/stdout

Then, once all the builds pass, flutter-gold should run and show us how the goldens changed!

**Comment by bdero** [comment]
The golden result looks like there's a bounds mismatch happening somewhere.

Before:
image

After:
image

Perhaps the `MakeTextFrameSTB` utility needs to be updated to the new scale method to make the goldens look correct? https://github.com/flutter/engine/blob/bbe63afc7bb65211edfd16b0f65829c3da6413b9/impeller/typographer/backends/stb/text_frame_stb.cc#L20-L22

**Comment by johnoneil** [comment]
@bdero Thanks for looking at this Brandon. I'll see if I can take time to fix this today.

**Comment by bdero** [comment]
Not sure what's going on with the goldens. This is looking pretty good locally.

Low DPI (before on top, after on bottom): 
image

High DPI (before on top, after on bottom):
image

Skia gold seems to sometimes get [confused](https://github.com/flutter/flutter/issues/142244) after a force push. Could you try pushing a new empty commit to your branch? `git commit --allow-empty -m "blank"`

**Comment by johnoneil** [comment]
Thanks for your time on this Brandon. Will try to push a blank commit shortly. We can review next week.
I'm also taking a look at the "Goldens" for the first time. That might be something the team might want to discuss as well next week as we're also planning on building something similar.

**Comment by bdero** [comment]
I pushed a duplicate PR to mess with Skia gold and try to figure out what's going on https://github.com/flutter/engine/pull/52209

**Comment by bdero** [comment]
The golden check is passing on my test PR, and also yours! Skia gold is still showing diffs for this PR, but it seems to be outdated. So I think this is actually good to go.

**Review by bdero — APPROVED** [review]
LGTM

**Comment by bdero** [comment]
The issue where the [Engine golden tests weren't running](https://github.com/flutter/flutter/issues/147180) is fixed, and the golden diffs appear to look correct, so I approved them!

image

Before:
image

After:
image

**Comment by johnoneil** [comment]
@bdero I don't believe I have write access, and am unable to merge this.
Could you merge this when you think it's best?

**Pull request merged**
