### PR TITLE
[g3 roll] Revert "add non-rendering operation culling to DisplayListBuilder"

### PR DESCRIPTION
**Pull request by XilaiZhang**
temporary revert of flutter/engine#41463

context: b/283038609

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
The goldens broken appear to be a divider line is missing, which is a regression.

**Comment by XilaiZhang** [comment]
cc @Jasguerrero 
I am rerunning linux unopt. as a follow up from the handoff, once this revert lands in main, if you would like to continue with your current roll, you can do either one of the two following:
1. roll framework to a more recent commit, which would include the engine commit corresponding to this revert.
2. if you already have a roll branch created, you can cherry pick this revert into your engine roll branch

**Comment by Jasguerrero** [comment]
`linux_unopt` is consistently failing in this PR (after 3 runs) could it be a breakage of the revert? @flar

**Comment by CaseyHillers** [comment]
@XilaiZhang you'll need to run ci/format.sh

```
ERROR: Found 1 C++/ObjC/Shader file which was formatted incorrectly.
To fix, run:

patch -p0 <<DONE
--- display_list/testing/dl_test_snippets.h	2023-05-17 12:55:52.688205554 -0700
+++ -	2023-05-17 13:02:54.641372540 -0700
@@ -91,7 +91,7 @@
```

**Comment by flar** [comment]
I ran into a similar problem with the reland of the original fix where code that was formatted acceptably when the first change went in was suddenly not passing the new formatting rules - in particular the spaces on that one line grabbing the skia image. Running the format command and pushing the 1-line change should enable it to be landed.

**Review by flar — APPROVED** [review]
LGTM once the formatting fix is applied.

**Comment by XilaiZhang** [comment]
umm interesting. I rerun ./ci/format.sh a few times, but it says no formatting problems found

**Comment by XilaiZhang** [comment]
umm if i edit this line manually, the formatting check would reject my change

**Comment by XilaiZhang** [comment]
foregoing command line edits, and using github ui to manully override based on Jesús' insight

**Comment by flar** [comment]
Is there a difference between the commit that your revert is based on and the commit that the PR is being tested against?

**Comment by XilaiZhang** [comment]
> Is there a difference between the commit that your revert is based on and the commit that the PR is being tested against?

umm looking at file history of /[display_list](https://github.com/flutter/engine/commits/main/display_list)/[testing](https://github.com/flutter/engine/commits/main/display_list/testing)/dl_test_snippets.h i don't seem to find a difference.

commit that this revert is based on: umm this revert is a revert for https://github.com/flutter/engine/pull/41463
commit that the PR is being tested against: my understanding is that `linux unopt` would test the current content included in this pr

**Pull request merged**
