### PR TITLE
[null-safety] increase sky engine min sdk

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

To silence pub warning:

```
Running "flutter pub get" in project_root...                       181ms
The package resolution is not fully migrated to null-safety.            
                                                                        
package:sky_engine is not opted into null safety in its pubspec.yaml:   
  ╷                                                                     
8 │   sdk: '>=1.11.0 <3.0.0'                                            
  │        ^^^^^^^^^^^^^^^^^                                            
  ╵                                                                     
                                                                        
Either downgrade your sdk constraint, or invoke dart/flutter with       
`--no-sound-null-safety`.                                               
                                                                        
To learn more about available versions of your dependencies try running 
`pub outdated --mode=null-safety`.                                      
                                                                        
See more at https://dart.dev/null-safety/migration-guide.    
```

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
Uh oh:
```
Using analyzer from /b/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dartanalyzer
dartanalyzer version 2.11.0-190.0.dev
```

**Comment by jonahwilliams** [comment]
I guess we're using the checked-in Dart SDK to analyze things?

**Comment by zanderso** [comment]
Hmm. On further thought, that might be the right thing to do here. But then this PR would have to wait on the roll of Dart's prebuilt dev SDK to 2.12. @mit-mit

**Comment by jonahwilliams** [comment]
Looks like its working now, will land on green

**Pull request merged**
