### PR TITLE
[CP] Fixed visibility of embedded views in safari (google map, video, camera preview etc)

### PR DESCRIPTION
**Pull request by zanderso**
This is the CP PR for https://github.com/flutter/flutter/issues/116574 into 3.3 stable

### CODE REVIEW

**Comment by zanderso** [comment]
I initially had the target branch set wrong, and now I can't get the ci.yaml validation check to re-run. @CaseyHillers

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by CaseyHillers** [comment]
@zanderso can you push an empty commit?

\cc @nehalvpatel (oncall) as FYI for the ci.yaml failure

**Comment by nehalvpatel** [comment]
Looks like the empty commit worked. 🙂

**Pull request merged**
