### PR TITLE
Roll vulkan-deps

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/112248

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by loic-sharma** [comment]
FYI I'm working on rolling to the latest ANGLE version in this WIP PR: https://github.com/flutter/engine/pull/36389. Here are blockers I'm aware of:

1. ANGLE is affected by an MSVC bug, we need to update to VS 2019 or newer: [angleproject#7693](https://bugs.chromium.org/p/angleproject/issues/detail?id=76930)
2. Updating to VS 2019 exposes a bug in `EventChannel` which causes framework tests to fail, see: https://github.com/flutter/flutter/pull/113135#issue-1401745911
3. The latest version of SPIRV Cross generates invalid shader programs, breaking engine tests. See: https://github.com/KhronosGroup/SPIRV-Cross/issues/2031
4. Lots of smaller miscellaneous things, see: https://github.com/flutter/engine/pull/36389

My recommendation would be to try to roll to the non-latest versions to avoid these issues.

**Comment by dnfield** [comment]
I think I've found the earliest ANGLE commit that has the vulkan-deps commit we needed. I did some searching with `git grep` and `git rev-list`. I _probably_ could have rolled vulkan-deps out of sync with ANGLE, but trying to avoid that if this can pass CI.

@loic-sharma I'm taking a slightly different approach to resolving the unguarded availability -we don't actually use the Metal EXT stuff so I'm just undefining that before including vulkan.h. I'll file something upstream in vulkan headers to see if we can get availability guards to flow through eventually.

**Comment by dnfield** [comment]
Unfortunately this commit is making Windows unhappy. Going to try to just rev vulkan-deps to the earliest commit that has the change that fixes the macOS deprecations when building for Android.

**Comment by dnfield** [comment]
Just revving vulkan-headers a little bit seems to be passing CI. That's enough to fix one of our problems.

**Pull request merged**
