### PR TITLE
Reduce default verbosity of Android embedding

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/48275

### CODE REVIEW

**Comment by xster** [comment]
What does that mean? Did you mean things in "flutter/fml/trace_event.h" via JNI or https://developer.android.com/reference/android/os/Trace?

**Comment by dnfield** [comment]
FML tracing was what I had in mind

I'm just not sure why I would ever want to see these logs. They're not particularly actionable, and they read more like tracing information rather than logging information.  If we piped them through to the tracing in the dart observatory that might be helpful.

**Comment by xster** [comment]
I don't have a strong opinion on their usefulness but I don't think seeing it on a timeline either via observatory or Android's systrace makes it more or less useful. Either way, their verbosity is more or less consistent with the other 136 occurrences of Log.v and I refactor them all to go through JNI.

**Comment by xster** [comment]
ha, I was actually gonna say that we should merge them all into standard NSLogs (behind a flag) instead since observatory timelines are so obscure no one will look at them, especially the events that happen before the Dart VM is even started. 

But then I noticed FlutterViewController uses fml traces in a whole bunch of places. Having the split behavior is a bit awkward but since there are no uses of fml traces through JNI in java either. All things equal, I think normal logs are more digestible (if users want to turn them on) since they're just normal messages. Their timing don't matter.

**Comment by dnfield** [comment]
Normal logs are bad for a few reasons:

1. They can significantly impact timing. A trace is faster than a log - bugs that are due to race conditions are less likely to happen when logging, because logging is slower.
2. They're slower than traces - having a small performance impact.
3. They're harder to correlate to trace data. It's really hard to show that the Dart VM slows down _right after_ or before or whatever some Android event that we care about without proper tracing.
4. They're harder to meaningfully share when a performance issue comes up. Somewhere out there @chinmaygarde has an article explaining how much more likely the engine team is to look at a performance issue if there's a trace attached vs. not.

**Comment by xster** [comment]
I'd agree if our logs were performance related. We're not talking about deprecating the observatory and use console logs to do performance tracing. We're just talking about these non timing related messages in the android embedding like "Using the launch theme as normal theme.".

> They can significantly impact timing. A trace is faster than a log - bugs that are due to race conditions are less likely to happen when logging, because logging is slower.

They're just filtered out for non BuildConfig.DEBUG. 

> They're slower than traces - having a small performance impact.

This is the same thing. Either way, for these short ops, JNI is an order of magnitude slower than JVM calls. 

> They're harder to correlate to trace data. It's really hard to show that the Dart VM slows down right after or before or whatever some Android event that we care about without proper tracing.

This seems really specialized. Again, a lot of these are before the Dart VM even starts.

**Comment by dnfield** [comment]
Going to land this since the failures were flakes/infra related issues.

**Pull request merged**
