### PR TITLE
Remove support for ignore_raster_cache

### PR DESCRIPTION
**Pull request by tvolkert**
https://github.com/flutter/flutter/issues/17448

### CODE REVIEW

**Comment by jason-simmons** [comment]
I'd prefer to keep this flag.

Repeated screenshots will be more consistent if the raster cache is always disabled.  Otherwise, the same layer tree could yield different bits in the screenshot depending on whether a picture has reached the threshold for a cache hit.

**Comment by chinmaygarde** [comment]
> Repeated screenshots will be more consistent if the raster cache is always disabled. Otherwise, the same layer tree could yield different bits in the screenshot depending on whether a picture has reached the threshold for a cache hit.

That indicates a real bug in the raster cache substitution and we should file and fix it separately instead of working around it.

Also, this flag is super confusing and was only ever needed for SKP generation (later co-opted for snapshotting). I think we are better off without it.

**Comment by chinmaygarde** [comment]
Can we commit or close this?

**Comment by tvolkert** [comment]
I'll close it for now.  We can't commit it until https://github.com/flutter/flutter/issues/17731 is fixed and we're confident that raster cache hits during software rendering are both (a) deterministic, and (b) reasonably close to direct rendering results.

**Pull request closed without merging**
