### PR TITLE
Roll goldctl forward

### PR DESCRIPTION
**Pull request by zanderso**
For https://github.com/flutter/flutter/issues/135620

### CODE REVIEW

**Review by kjlubick — APPROVED** [review]
cc @Piinks

**Review by vashworth — COMMENTED** [review]
Ran it on macOS 13 and it appears to have fixed the issue! Thank you @zanderso!

https://chromium-swarm.appspot.com/task?id=6537fecff3544710

Should we also update the goldctl version here?
https://github.com/flutter/engine/blob/ec1d0d69fcf11aa64a271a1fe2f582df37f3f2e9/lib/web_ui/dev/generate_builder_json.dart#L152

**Comment by zanderso** [comment]
> Ran it on macOS 13 and it appears to have fixed the issue! Thank you @zanderso!

Great!

> Should we also update the goldctl version here?

Yes =) Thanks. I had made that change locally and forgot to push it.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!
We should probably create a cadence for rolling this forward more regularly. We pinned it since sometimes goldctl would (rarely) have a bad build and then we would then be broken in the meantime. @godofredoc do we have other systems in place that roll dependencies forward like this?

**Pull request merged**
