### PR TITLE
Add test for profile mode diagnostics

### PR DESCRIPTION
**Pull request by ferhatb**
This PR requires Flutter PR https://github.com/flutter/flutter/pull/53878 to land.

### CODE REVIEW

**Comment by yjbanov** [comment]
I think test should be in flutter/flutter, so that it breaks when the framework regresses again. Our e2e tests do not run on framework changes.

**Comment by ferhatb** [comment]
> I think test should be in flutter/flutter, so that it breaks when the framework regresses again. Our e2e tests do not run on framework changes.

flutter tests run DDC. Not dart2js profile mode.

**Comment by yjbanov** [comment]
> flutter tests run DDC. Not dart2js profile mode.

Sorry, I didn't mean literally `flutter test`. I meant a test similar to https://github.com/flutter/flutter/blob/a8b3d1b74fac5251c61c8a898cf7544fd77ddd16/dev/bots/test.dart#L582. Could also be an `e2e` test, just like this one, or something that cracks open the file and validates that certain symbols do not show up.

The code LGTM, so I'm approving. Leaving it up to you where to put this test, but it definitely won't run when someone breaks it. We'll only find out a breakage on a random engine PR, which could be unrelated to the breakage.

**Comment by nturgut** [comment]
I'll merge this once the other PR is in. Thanks for the heads up.

**Comment by nturgut** [comment]
> I'll merge this once the other PR is in. Thanks for the heads up.

I'm waiting for this one to merge to merge my PR: https://github.com/flutter/flutter/pull/57286

**Pull request merged**
