### PR TITLE
[Impeller] If validations are enabled but not found, still create the VK context.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes https://github.com/flutter/flutter/issues/131714

### CODE REVIEW

**Review by gaaclarke — COMMENTED** [review]
This is still going to report the backend as `Using the Impeller rendering backend (Vulkan with Validation Layers).` It will never report `Using the Impeller rendering backend (Vulkan).`

I'd prefer it to fail, then retry with them turned off so that we get the print statements.  We'll have to clean this up at some point so that it only ever says "using" once for what actually gets used.  These print statements are latches for integration tests, its better to assert something directly than to assert that an error doesn't get printed.

**Comment by chinmaygarde** [comment]
You're right. Did patch that log. Momentido.

**Comment by chinmaygarde** [comment]
@gaaclarke PTAL. I refactored it to report what is actually being used instead of the fail and retry approach though.

**Review by gaaclarke — COMMENTED** [review]
Code looks good to me.  Want to add a simple test in `capabilities_vk_unittests.cc` that shows it falling?  You just have to mock out the `vk::enumerate*` calls, should be easy.

**Comment by chinmaygarde** [comment]
Roger on the test. The test turned out the be even simpler. I just asked for validation and asserted that I got a context. Did see the log being emitted but don't want to parse the log for "Requested Impeller context creation with validations but the validation layers could not be found. Expect no Vulkan validation checks!". Before this patch, we should have gotten no context at all.

**Review by gaaclarke — APPROVED** [review]
thanks, lgtm!

**Pull request merged**
