### PR TITLE
Enable ColorFilterLayer support RasterCache

### PR DESCRIPTION
**Pull request by wangying3426**
Fix https://github.com/flutter/flutter/issues/98866

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by flar — COMMENTED** [review]
Is there a benchmark which shows an improvement with this change? Have you tried running the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1479 or the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490 benchmarks with this change?

Another situation to consider is when the CF is changing, but the children are not. ImageFilterLayer takes that case into account.

**Comment by wangying3426** [comment]
> Is there a benchmark which shows an improvement with this change? Have you tried running the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1479 or the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490 benchmarks with this change?
> 
> Another situation to consider is when the CF is changing, but the children are not. ImageFilterLayer takes that case into account.

OK, I will add some benchmark data and example code later.

**Comment by wangying3426** [comment]
> Is there a benchmark which shows an improvement with this change? Have you tried running the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1479 or the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490 benchmarks with this change?
> 
> Another situation to consider is when the CF is changing, but the children are not. ImageFilterLayer takes that case into account.

@flar  By referring to ImageFilterLayer, I optimized the CF raster cache code.  

For benchmarks, I found  that [color_filter_and_fade_perf__timeline_summary](https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490 )  will not create ColorFilterLayer, so I add some benchmarks as https://github.com/flutter/flutter/pull/99542 shown.
And the test data on a Redmi Note 3 device like this:
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	2.28 (0.00%)	2.10 (0.00%)	1.09x	
worst_frame_build_time_millis	4.96 (0.00%)	4.78 (0.00%)	1.04x	
90th_percentile_frame_build_time_millis	3.08 (0.00%)	2.76 (0.00%)	1.11x	
99th_percentile_frame_build_time_millis	4.07 (0.00%)	3.82 (0.00%)	1.07x	
average_frame_rasterizer_time_millis	5.12 (0.00%)	4.12 (0.00%)	1.24x	
worst_frame_rasterizer_time_millis	37.35 (0.00%)	7.21 (0.00%)	5.18x	
90th_percentile_frame_rasterizer_time_millis	5.87 (0.00%)	4.59 (0.00%)	1.28x	
99th_percentile_frame_rasterizer_time_millis	7.41 (0.00%)	5.61 (0.00%)	1.32x
average_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
90th_percentile_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
99th_percentile_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
worst_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
average_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
90th_percentile_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
99th_percentile_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
worst_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
average_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
average_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
new_gen_gc_count	10.00 (0.00%)	24.00 (0.00%)	0.42x	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_vsync_transitions_missed	1.67 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_vsync_transitions_missed	2.00 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_vsync_transitions_missed	2.00 (0.00%)	0.00 (0.00%)	Infinityx	
```

we can see that the `average_frame_rasterizer_time_millis` reduce 20%~30%.

**Comment by wangying3426** [comment]
> > Is there a benchmark which shows an improvement with this change? Have you tried running the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1479 or the https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490 benchmarks with this change?
> > Another situation to consider is when the CF is changing, but the children are not. ImageFilterLayer takes that case into account.
> 
> @flar Referred to [ImageFilterLayer](https://github.com/flutter/engine/blob/main/flow/layers/image_filter_layer.cc#L61), I have optimized the CF raster cache code.
> 
> For benchmarks, I found that [color_filter_and_fade_perf__timeline_summary](https://github.com/flutter/flutter/blob/48c9bbe18247798d526373be4dcf7a54d8369f9c/.ci.yaml#L1490) will not create a ColorFilterLayer, so I add some benchmarks as [flutter/flutter#99542](https://github.com/flutter/flutter/pull/99542) shown. And the [A/B tests](https://github.com/flutter/flutter/blob/master/dev/devicelab/README.md) data on a Redmi Note 3 device like this:
> 
> ```
> ═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════
> 
> Score	Average A (noise)	Average B (noise)	Speed-up
> average_frame_build_time_millis	2.28 (0.00%)	2.10 (0.00%)	1.09x	
> worst_frame_build_time_millis	4.96 (0.00%)	4.78 (0.00%)	1.04x	
> 90th_percentile_frame_build_time_millis	3.08 (0.00%)	2.76 (0.00%)	1.11x	
> 99th_percentile_frame_build_time_millis	4.07 (0.00%)	3.82 (0.00%)	1.07x	
> average_frame_rasterizer_time_millis	5.12 (0.00%)	4.12 (0.00%)	1.24x	
> worst_frame_rasterizer_time_millis	37.35 (0.00%)	7.21 (0.00%)	5.18x	
> 90th_percentile_frame_rasterizer_time_millis	5.87 (0.00%)	4.59 (0.00%)	1.28x	
> 99th_percentile_frame_rasterizer_time_millis	7.41 (0.00%)	5.61 (0.00%)	1.32x
> average_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
> 90th_percentile_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
> 99th_percentile_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
> worst_layer_cache_count	0.00 (0.00%)	1.00 (0.00%)	0.00x	
> average_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
> 90th_percentile_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
> 99th_percentile_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
> worst_layer_cache_memory	0.00 (0.00%)	3.43 (0.00%)	0.00x	
> average_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
> 90th_percentile_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
> 99th_percentile_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
> worst_picture_cache_count	1.00 (0.00%)	0.00 (0.00%)	Infinityx	
> average_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
> 90th_percentile_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
> 99th_percentile_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
> worst_picture_cache_memory	3.43 (0.00%)	0.00 (0.00%)	Infinityx	
> new_gen_gc_count	10.00 (0.00%)	24.00 (0.00%)	0.42x	
> old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
> average_vsync_transitions_missed	1.67 (0.00%)	0.00 (0.00%)	Infinityx	
> 90th_percentile_vsync_transitions_missed	2.00 (0.00%)	0.00 (0.00%)	Infinityx	
> 99th_percentile_vsync_transitions_missed	2.00 (0.00%)	0.00 (0.00%)	Infinityx	
> ```
> 
> we can see that the `average_frame_rasterizer_time_millis` and `90th_percentile_frame_rasterizer_time_millis ` reduce about 20%~30%.

@flar Could you please review this PR again?

**Review by flar — APPROVED** [review]
LGTM, but you have to fix the licenses before it is ready to merge.

**Review by ColdPaleLight — APPROVED** [review]
LGTM

**Pull request merged**
