### PR TITLE
implemented Size diagonal

### PR DESCRIPTION
**Pull request by iapicca**
## Description

- moved the concrete implementation of [Offset](https://api.flutter.dev/flutter/dart-ui/Offset-class.html) properties [distance](https://api.flutter.dev/flutter/dart-ui/Offset/distance.html) and [distanceSquared](https://api.flutter.dev/flutter/dart-ui/Offset/distanceSquared.html)
  under [OffsetBase](https://api.flutter.dev/flutter/dart-ui/OffsetBase-class.html) new property `_distance` and `_distanceSquared`
- [Offset](https://api.flutter.dev/flutter/dart-ui/Offset-class.html)  gets `distance` and `distanceSquared` respectively from [OffsetBase](https://api.flutter.dev/flutter/dart-ui/OffsetBase-class.html)  `_distance` and  `_distanceSquared`
- added property `diagonal` to [Size](https://api.flutter.dev/flutter/dart-ui/Size-class.html) using [OffsetBase](https://api.flutter.dev/flutter/dart-ui/OffsetBase-class.html) 's `_distance` property

## Related Issues

https://github.com/flutter/flutter/issues/64940

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x ] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x ] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @Hixie: Can you review this please? It seems like a simple alias for an existing method.

**Comment by Hixie** [comment]
Is this a common use case? I would probably shy away from adding this. You can do this already with `size.bottomLeft(Offset.zero).distance`, which is only a little more verbose than `size.diagonal` but avoids a number of potential problems, for example it removes any confusion around how it handles negative widths, and avoids the risk of making Offset.distance more expensive or of increasing the size of the dart:ui code (which in some situations can't be tree-shaken away).

**Comment by iapicca** [comment]
> Is this a common use case? I would probably shy away from adding this. You can do this already with `size.bottomLeft(Offset.zero).distance`, which is only a little more verbose than `size.diagonal` but avoids a number of potential problems

@Hixie honestly I didn't know that the result I was aiming for was that easy to obtain
`size.bottomLeft(Offset.zero).distance`
I don't see the point of keeping this PR open,
thank you both @Hixie and @chinmaygarde for looking into it

**Comment by Hixie** [comment]
np, thanks for the patch!

**Pull request closed without merging**
