### PR TITLE
[Impeller] Turned on new blur.

### PR DESCRIPTION
**Pull request by gaaclarke**
This new blur should perform faster since it scales down the image before blurring it.  Jonah did early testing of it and found it to be faster.  Scrolling around with the blur perf bug it seems faster.  It also has a wider test bed and is hopefully easier to maintain since it contains all of its logic for both directions.

testing: There are existing blur tests and we've backfilled more as we've added features to this blur.

fixes https://github.com/flutter/flutter/issues/131580
fixes https://github.com/flutter/flutter/issues/138259

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
Here are the tests that currently need addressing.  Fixing the clipped blur failures may also help with https://github.com/flutter/flutter/issues/139165. Some of it seems related to clamping the blur sigma too, where the old blur does it, and the new one doesn't.

Screenshot 2023-11-28 at 3 37 45 PM
Screenshot 2023-11-28 at 3 37 57 PM
Screenshot 2023-11-28 at 3 38 06 PM

**Comment by gaaclarke** [comment]
This is looking good now except for the case where we aren't clamping the sigma.

Screenshot 2023-12-07 at 3 47 01 PM

**Comment by gaaclarke** [comment]
We still have a few outstanding optimizations we could do.  I think this is feature complete enough to land.  I did manual testing with the blur perf bug's sample code and wonderous.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Review by bdero — APPROVED** [review]
Also LGTM! Big day for the new blur!

**Comment by gaaclarke** [comment]
giphy (20)

**Comment by gaaclarke** [comment]
It's weird that the 2 latest tests we've added didn't show up any difference, the decal fallback and the smoke test.  They are in this branches history and I would have expected changes.

**Comment by gaaclarke** [comment]
The golden tests don't seem to be resolving.  I'm going to attempt a rebase during lunch to make sure everything is good.  Like I said, I wouldn't be surprised if those other tests created differences.

**Comment by gaaclarke** [comment]
Screenshot 2023-12-14 at 1 07 37 PM

I don't know what's going on.  Clicking on the golden link shows nothing.  I guess I'll land this.  Maybe this is the issue @jason-simmons ran into the other day?

**Comment by mark8044** [comment]
@gaaclarke 
Hi I cannot speak to performance improvement (since old way is fast on my app)

BUT one problem I'm encountering with this is that its causing a weird flicked when it runs over black text on a white background.

In my case I have a backdrop filter'd small Container, hovering over a listview.  The listview consists of black text on white background (native iOS font, no special font face or anything).  As you scroll the listview and the text shows up behind the backdrop filter'd Container, it flickers a bit.    The text flickers that is.  The white areas do not flicker.

Second, I also notice the `amount` of blur, meaning the effect the sigmaX/Y has, appears to be substantially less.  With the old way, you could not make out text per se, the text beecame a vague haze.  Now you can sort of make out letters.

I hope that description makes some kind of sense.   My overall impression is that the blur 'feels' downgraded from what it was.  Before it seemed very slick with a native look/feel.

Hope this helps in some way

**Comment by bdero** [comment]
> In my case I have a backdrop filter'd small Container, hovering over a listview. The listview consists of black text on white background (native iOS font, no special font face or anything). As you scroll the listview and the text shows up behind the backdrop filter'd Container, it flickers a bit. The text flickers that is. The white areas do not flicker.

Hey @mark8044, could you please file a new issue with your reproduction code and tag @gaaclarke and I? This would be very helpful. We just reverted this change to a benchmark issue, so it will no longer be reproducible in the master channel once the revert rolls in (if this is what's causing it).

So when filing the bug, just make sure to mention the commits you were able to reproduce the problem at and we can test your repro against the new blur.

> Second, I also notice the amount of blur, meaning the effect the sigmaX/Y has, appears to be substantially less. With the old way, you could not make out text per se, the text beecame a vague haze (with my sigmaX/Y setting). Now you can sort of make out letters (with the same settings).

With the new blur we remapped how sigma affects the blur to more closely match Skia's original appearance (which is much more accurate). Before, the appearance of the blur was too aggressive and didn't match other software. So when people exported content from other vector graphics programs and attempted to display them in Flutter, the results would be inconsistent. But if you're running into differences between Skia's look and Impeller's look with respect to the aggressiveness or quality of the blur, please let us know by filing an issue!

Thanks!

**Comment by mark8044** [comment]
@bdero No problem, I will do my best.   Thanks for the info about the sigma, its easy to just adjust the code to match the new amount if that's what's considered the proper amount.  Was just making sure this was intended and not a side effect

**Comment by gaaclarke** [comment]
Here are the results from `backdrop_filter_perf_ios__timeline_summary`.  Despite earlier positive early results the new blur seems to be slower too.  We should implement some of our planned optimizations before switching over.

## before
```
    "average_vsync_transitions_missed": 3.861904761904762,
    "90th_percentile_vsync_transitions_missed": 4.0,
    "99th_percentile_vsync_transitions_missed": 4.0,
    "average_vsync_frame_lag": 0.0,
    "90th_percentile_vsync_frame_lag": 0.0,
    "99th_percentile_vsync_frame_lag": 0.0,
    "average_layer_cache_count": 0.0,
    "90th_percentile_layer_cache_count": 0.0,
    "99th_percentile_layer_cache_count": 0.0,
    "average_frame_request_pending_latency": 16648.66,
    "90th_percentile_frame_request_pending_latency": 16720.0,
    "99th_percentile_frame_request_pending_latency": 16783.0,
    "worst_layer_cache_count": 0.0,
    "average_layer_cache_memory": 0.0,
    "90th_percentile_layer_cache_memory": 0.0,
    "99th_percentile_layer_cache_memory": 0.0,
    "worst_layer_cache_memory": 0.0,
    "average_picture_cache_count": 0.0,
    "90th_percentile_picture_cache_count": 0.0,
    "99th_percentile_picture_cache_count": 0.0,
    "worst_picture_cache_count": 0.0,
    "average_picture_cache_memory": 0.0,
    "90th_percentile_picture_cache_memory": 0.0,
    "99th_percentile_picture_cache_memory": 0.0,
    "worst_picture_cache_memory": 0.0,
    "total_ui_gc_time": 0.119,
    "30hz_frame_percentage": 0.0,
    "60hz_frame_percentage": 100.0,
    "80hz_frame_percentage": 0.0,
    "90hz_frame_percentage": 0.0,
    "120hz_frame_percentage": 0.0,
    "illegal_refresh_rate_frame_count": 0,
    "average_gpu_frame_time": 51.48809523809524,
    "90th_percentile_gpu_frame_time": 62.5,
    "99th_percentile_gpu_frame_time": 62.5,
    "worst_gpu_frame_time": 62.5,
    "average_cpu_usage": 97.33600004000002,
    "90th_percentile_cpu_usage": 99.100001,
    "99th_percentile_cpu_usage": 99.400001,
    "average_gpu_usage": 100.0,
    "90th_percentile_gpu_usage": 100.0,
    "99th_percentile_gpu_usage": 100.0,
    "average_memory_usage": 118.8809375,
    "90th_percentile_memory_usage": 139.796875,
    "99th_percentile_memory_usage": 145.390625
  },
```

## after
```
    "average_vsync_transitions_missed": 5.830645161290323,
    "90th_percentile_vsync_transitions_missed": 6.0,
    "99th_percentile_vsync_transitions_missed": 6.0,
    "average_vsync_frame_lag": 0.0,
    "90th_percentile_vsync_frame_lag": 0.0,
    "99th_percentile_vsync_frame_lag": 0.0,
    "average_layer_cache_count": 0.0,
    "90th_percentile_layer_cache_count": 0.0,
    "99th_percentile_layer_cache_count": 0.0,
    "average_frame_request_pending_latency": 16638.835,
    "90th_percentile_frame_request_pending_latency": 16727.0,
    "99th_percentile_frame_request_pending_latency": 16772.0,
    "worst_layer_cache_count": 0.0,
    "average_layer_cache_memory": 0.0,
    "90th_percentile_layer_cache_memory": 0.0,
    "99th_percentile_layer_cache_memory": 0.0,
    "worst_layer_cache_memory": 0.0,
    "average_picture_cache_count": 0.0,
    "90th_percentile_picture_cache_count": 0.0,
    "99th_percentile_picture_cache_count": 0.0,
    "worst_picture_cache_count": 0.0,
    "average_picture_cache_memory": 0.0,
    "90th_percentile_picture_cache_memory": 0.0,
    "99th_percentile_picture_cache_memory": 0.0,
    "worst_picture_cache_memory": 0.0,
    "total_ui_gc_time": 2.286,
    "30hz_frame_percentage": 0.0,
    "60hz_frame_percentage": 100.0,
    "80hz_frame_percentage": 0.0,
    "90hz_frame_percentage": 0.0,
    "120hz_frame_percentage": 0.0,
    "illegal_refresh_rate_frame_count": 0,
    "average_gpu_frame_time": 87.70161290322581,
    "90th_percentile_gpu_frame_time": 125.0,
    "99th_percentile_gpu_frame_time": 125.0,
    "worst_gpu_frame_time": 125.0,
    "average_cpu_usage": 118.07500012500005,
    "90th_percentile_cpu_usage": 126.800002,
    "99th_percentile_cpu_usage": 129.600001,
    "average_gpu_usage": 100.0,
    "90th_percentile_gpu_usage": 100.0,
    "99th_percentile_gpu_usage": 100.0,
    "average_memory_usage": 104.82259114583333,
    "90th_percentile_memory_usage": 119.875,
    "99th_percentile_memory_usage": 123.8125
  },
```

**Comment by bdero** [comment]
I opened the `EntityTest.GaussianBlurFilter` playground in xcode and it's leaking like a firehose. Not sure if it's at all relevant to the reason for revert or if it's just a problem with this playground, but it doesn't seem to be happening for other interactive playgrounds
image

**Comment by gaaclarke** [comment]
> I opened the `EntityTest.GaussianBlurFilter` playground in xcode and it's leaking like a firehose. Not sure if it's at all relevant to the reason for revert or if it's just a problem with this playground, but it doesn't seem to be happening for other interactive playgrounds

I called this out the other week when I left it running when I went to lunch and it almost took down my computer.  I did measurements for the benchmark in https://github.com/flutter/flutter/issues/140189#issuecomment-1861299055.  I didn't post the results but I looked at cpu results too and they looked stable.  So I think this leak is unique to the interactive test.

**Comment by jason-simmons** [comment]
Landed a fix for the leak described in https://github.com/flutter/engine/pull/48472#issuecomment-1864400855

(The issue only affects the playground framework - see https://github.com/flutter/engine/pull/49576)

**Pull request merged**
