### PR TITLE
Simplify painting PictureLayer

### PR DESCRIPTION
**Pull request by abarth**
This patch uses some fancier Skia APIs to simplify how PictureLayer
paints.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @chinmaygarde

**Comment by Hixie** [comment]
lgtm

**Comment by chinmaygarde** [comment]
How does the scale get accounted for?

**Comment by Hixie** [comment]
the image is drawn with the right target rect

**Comment by abarth** [comment]
> How does the scale get accounted for?

The drawImageRect API I'm using implies a source rect of the whole image.  That means all the pixels of the source image are squeezed into the correct destination rect.

**Pull request merged**
