### PR TITLE
Revert "Listen for Vsync callback on the UI thread directly"

### PR DESCRIPTION
**Pull request by GaryQian**
Reverts flutter/engine#29889

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20hybrid_android_views_integration_test/3199/overview

```
[hybrid_android_views_integration_test] [STDOUT] stdout: [ +348 ms] 00:17 [32m+3[0m[31m -1[0m: Flutter surface switch Uses FlutterImageView when Android view is on the screen [1m[31m[E][0m[0m
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]   Expected: '|-FlutterView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterSurfaceView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterImageView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-ViewGroup\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '    |-ViewGroup\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterImageView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               ''
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]     Actual: '|-FlutterView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterSurfaceView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterImageView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               '  |-FlutterImageView\n'
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               ''
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]      Which: is different.
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]             Expected: ... View\n  |-ViewGroup\ ...
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]               Actual: ... View\n  |-FlutterIma ...
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]                                     ^
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]              Differ at offset 65
[hybrid_android_views_integration_test] [STDOUT] stdout: [  +10 ms]   package:test_api/src/expect/expect.dart 137:31    fail
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]   package:test_api/src/expect/expect.dart 132:3     _expect
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]   package:test_api/src/expect/expect.dart 46:3      expect
[hybrid_android_views_integration_test] [STDOUT] stdout: [        ]   test_driver/main_test.dart 76:7                   main.<fn>.<fn>
```

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]
LGTM

**Comment by FelixZhang00** [comment]
After reverting this commit, I pull the latest master of engine code and run test with local engine, the hybrid_android_views tests still fail.

```json
[ +385 ms] F/flutter (27831): [FATAL:flutter/lib/ui/window/pointer_data_packet_converter.cc(176)] Check failed: state.is_down. 
[   +1 ms] F/libc    (27831): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27831 (n.platformviews), pid 27831 (n.platformviews)
[  +91 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[        ] Build fingerprint: 'Xiaomi/sagit/sagit:9/PKQ1.190118.001/9.8.22:user/release-keys'
[        ] Revision: '0'
[        ] ABI: 'arm64'
[        ] pid: 27831, tid: 27831, name: n.platformviews  >>> io.flutter.integration.platformviews <<<
[        ] signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
[        ] Abort message: '[FATAL:flutter/lib/ui/window/pointer_data_packet_converter.cc(176)] Check failed: state.is_down. 
[        ] '
[        ]     x0  0000000000000000  x1  0000000000006cb7  x2  0000000000000006  x3  0000000000000008
[        ]     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0080000000000000
[        ]     x8  0000000000000083  x9  a71f35a90a1a4aa9  x10 0000000000000000  x11 fffffffc7ffffbdf
[        ]     x12 0000000000000001  x13 0000000000000008  x14 ffffffffffffffff  x15 0000d162e7bea8f1
[        ]     x16 000000742d8ef2b0  x17 000000742d80ebd8  x18 0000000000000010  x19 0000000000006cb7
[        ]     x20 0000000000006cb7  x21 00000073ad214c00  x22 0000007ff3c1b1b0  x23 00000073944c9a9c
[        ]     x24 0000000000000014  x25 00000074332085e0  x26 00000073ad214ca0  x27 0000000000000005
[        ]     x28 0000007ff3c1aed0  x29 0000007ff3c18910
[        ]     sp  0000007ff3c188d0  lr  000000742d80204c  pc  000000742d802074
[        ] backtrace:
[        ]     #00 pc 0000000000022074  /system/lib64/libc.so (abort+116)
[        ]     #01 pc 0000000000dc7094  /data/app/io.flutter.integration.platformviews-ICwCbCYr6ragLeM6ku0JxQ==/lib/arm64/libflutter.so (offset 0xdbe000)
[        ]     #02 pc 0000000000e5a7bc  /data/app/io.flutter.integration.platformviews-ICwCbCYr6ragLeM6ku0JxQ==/lib/arm64/libflutter.so (offset 0xdbe000)
[        ]     #03 pc 0000000001dae2d4  /data/app/io.flutter.integration.platformviews-ICwCbCYr6ragLeM6ku0JxQ==/lib/arm64/libflutter.so (offset 0xdbe000)
[        ]     #04 pc 0000000001dad5d0  /data/app/io.flutter.integration.platformviews-ICwCbCYr6ragLeM6ku0JxQ==/lib/arm64/libflutter.so (offset 0xdbe000)
```

**Comment by FelixZhang00** [comment]
I run hybrid_android_views_integration_test on my mac laptop, it's success.

Here is the output log:
[hybrid_android_views_integration_test.log](https://github.com/flutter/engine/files/7606818/hybrid_android_views_integration_test.log)

**Comment by zanderso** [comment]
Can @blasten or @GaryQian answer the question above from @FelixZhang00 ?

**Comment by GaryQian** [comment]
If it is passing, we can try to land it again, the failure may have been a flake then. I opted for revert since it was the only risky change in the roll and it was blocking the tree.

**Comment by mdebbar** [comment]
Based on the failures in the [Flutter Dashboard](https://flutter-dashboard.appspot.com/#/build?taskFilter=hybrid_android_views), this doesn't seem to be flaky. It's consistently passing in all commits without retries, and kept failing consistently on this commit despite retrying multiple times.

image

**Comment by blasten** [comment]
@FelixZhang00 It seems like your change exposed a race in the current implementation of platform views.

The race is more noticeable due to the changes to shell/platform/android/vsync_waiter_android.cc in https://github.com/flutter/engine/pull/29889. 

The issue is that to show a platform view in the first frame, the platform thread needs to wait for a message from framework. Currently, the engine post a task to the platform thread to generate a frame, which may cause the ordering of events to be "just" right.  However, your change posts a frame without going through the queue. 

A potential solution to this problem would require to detect if the current frame has a platform view, and wait for the message (that allows to create the Android view) before producing the actual frame on the screen.

cc @chinmaygarde

**Pull request merged**
