### PR TITLE
Add 'HandleRealTimeEvents' to window.

### PR DESCRIPTION
**Pull request by floitschG**

### CODE REVIEW

**Comment by floitschG** [comment]
Thinking more about it: the name is bad "handleX" is usually the name of something that is called when X happens. That's not the case here...

**Comment by floitschG** [comment]
Renamed to FlushRealTimeEvents

**Comment by Hixie** [comment]
@floitschG, @abarth what's the status here? Is this awaiting review?

**Comment by floitschG** [comment]
Yes. I think this could be merged in.

**Comment by Hixie** [comment]
@abarth I'm not super-familiar with this code, can you review it and merge it in if it's what we want?

**Comment by abarth** [comment]
Yes, this is great.  There's one style issue.  Let's land this an I'll make a separate patch for the style issue.

**Pull request merged**
