### PR TITLE
Remove Thread merging logic in DiscardLayerTreeOnResize test

### PR DESCRIPTION
**Pull request by cyanglaz**
The thread merging logic had some race condition in `DiscardLayerTreeOnResize` test with caused some flakiness. I couldn't reproduce the flakiness with more than 10k runs locally so I decided to remove the thread merging logic in the test. The thread merging logic was unnecessary for the test anyway.

Fixes https://github.com/flutter/flutter/issues/95751

Also remove unnecessary thread merging logic in `DiscardResubmittedLayerTreeOnResize` test.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ColdPaleLight** [comment]
Hi, @cyanglaz , It seems that the test `DiscardResubmittedLayerTreeOnResize` also needs to tweak

**Comment by cyanglaz** [comment]
@ColdPaleLight Is `DiscardResubmittedLayerTreeOnResize` also failing like this? Is there an issue or log that I can refer to?

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight Is `DiscardResubmittedLayerTreeOnResize` also failing like this? Is there an issue or log that I can refer to?

It copies DiscardLayerTreeOnResize and then modifies it, so they both have a lot of the same logic. I'm not sure if it have the same issue though.

**Comment by cyanglaz** [comment]
@ColdPaleLight done, please review it to see if the updated test still makes sense.

**Comment by ColdPaleLight** [comment]
I’m sorry, but I think updated test `DiscardResubmittedLayerTreeOnResize ` is not quite right. This test was introduced in this PR https://github.com/flutter/engine/pull/28474. It ensures that the `discard_callback `is passed to `Rasterizer::Draw` as a param when the frame needs to be resubmitted.

https://github.com/flutter/engine/blob/825c409164c1c78cef1e9e3ee3f47b066c1294e7/shell/common/rasterizer.cc#L206-L218

I tried removing the Thread merging logic at DiscardResubmittedLayerTreeOnResize today, but I didn't succeed.

**Comment by cyanglaz** [comment]
@ColdPaleLight Could you elaborate what needs to be updated for test. It seems to be the current version of the test in this PR makes sure the frame is dropped when the original_size is used, which was the same as the previous version, just without thread merging.

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight Could you elaborate what needs to be updated for test. It seems to me the current version of the test in this PR makes sure the frame is dropped when the original_size is used, which was the same as the previous version, just without thread merging.

Sorry, I didn't express clearly. This test is to ensure that the `discard_callback` here is passed to draw when `consume_result` is `PipelineConsumeResult::MoreAvailable`
https://github.com/flutter/engine/blob/825c409164c1c78cef1e9e3ee3f47b066c1294e7/shell/common/rasterizer.cc#L214-L215

So if someone accidentally makes the following change, the test will fail. You can make the following changes and see if the new version of the test fails, thank you.
``` diff
--- a/shell/common/rasterizer.cc
+++ b/shell/common/rasterizer.cc
@@ -220,8 +220,7 @@ RasterStatus Rasterizer::Draw(
                resubmit_recorder = std::move(resubmit_recorder),
                discard_callback = std::move(discard_callback)]() mutable {
                 if (weak_this) {
-                  weak_this->Draw(std::move(resubmit_recorder), pipeline,
-                                  std::move(discard_callback));
+                  weak_this->Draw(std::move(resubmit_recorder), pipeline);
                 }
               }));
       break;
```

**Comment by cyanglaz** [comment]
@ColdPaleLight Ah I see. I think in the resubmit case, thread merging is required ATM because `raster_thread_merger_` is required for re-sbumit. See: https://github.com/flutter/engine/blob/main/flow/compositor_context.cc#L116-L123

The test looks fine and we didn't have any flake report so I'd like to keep it there for now.

If in the future, we have a case where we need to resubmit the tree in a embedder that doesn't require thread merging, then it makes sense to create a new similar test but without thread merging.

Does it make sense? I'll remove the change in `DiscardResubmittedLayerTreeOnResize` if you agree.

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight Ah I see. I think in the resubmit case, thread merging is required ATM because `raster_thread_merger_` is required for re-sbumit. See: https://github.com/flutter/engine/blob/main/flow/compositor_context.cc#L116-L123
> 
> The test looks fine and we didn't have any flake report so I'd like to keep it there for now.
> 
> If in the future, we have a case where we need to resubmit the tree in a embedder that doesn't require thread merging, then it makes sense to create a new similar test but without thread merging.
> 
> Does it make sense? I'll remove the change in `DiscardResubmittedLayerTreeOnResize` if you agree.

Yeah, It sounds good to me :-)

**Review by ColdPaleLight — APPROVED** [review]
LGTM, nice!

**Comment by cyanglaz** [comment]
@chinmaygarde Friendly ping :)

**Review by chinmaygarde — APPROVED** [review]

**Pull request merged**
