### PR TITLE
Added API guards to flags in PlatformPlugin that were introduced after Flutter's min SDK version.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Added API guards to flags in PlatformPlugin that were introduced after Flutter's min SDK version.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@Hixie I have a testing exemption question here. This PR gates a few existing calls on Android API version. These gates should likely have always existed. Conceivably one could test these gates by building on earlier versions of Android and executing Dart behavior that results in execution of this code. However, I'm not aware of any CI control over the version of Android we test against, and it would still be considerable testing overhead to verify a few very specific gates. Do you think we need tests for this? If so, do you have any recommendation on approach?

**Comment by Hixie** [comment]
We should definitely test this. I agree that doing so is non-trivial but I think it's important that we not regress this. We have for too long been taking on technical debt due to not testing different versions of Android.

cc @tvolkert @godofredoc

**Comment by mklim** [comment]
> However, I'm not aware of any CI control over the version of Android we test against, and it would still be considerable testing overhead to verify a few very specific gates.

Sorry @matthew-carroll, this got lost in my inbox until the latest reply just now. For what it's worth this can be done with Robolectric and is already supported by our testing infra to a  limited extent. The key is the [`@Config.sdk`](http://robolectric.org/configuring#configure-sdk-level) tag, as used [here](https://github.com/flutter/engine/blob/dfa9498360c31991e88f35976f4763f394f004da/shell/platform/android/test/io/flutter/plugin/platform/SingleViewPresentationTest.java#L23) to run that test case on sdk=27. By default the unit tests are run on 16. This tag can be applied to specific test cases so you could run test cases on arbitrary SDK versions within a class, instead of just applying it to the whole class.

The part that makes this tricky is that each SDK needs its own Robolectric SDK artifacts uploaded to CIPD to work. Right now we have artifacts for 16 and 27, visible as `android-all-###-robolectric` jars under `third_party/robolectric`. In addition to that we're blocked on adding support for 29 without a more significant overhaul of how the tests are built and run (see flutter/flutter#38471 for details). That doesn't appear to be an issue for this PR though.

**Comment by matthew-carroll** [comment]
@mklim I added a test that invokes the 2 guarded haptic clauses on API 16, which does not support either one. Please let me know if you think reasonably tests the change.

**Pull request merged**
