### PR TITLE
[CP] Workaround iOS text input crash for emoji+Korean text

### PR DESCRIPTION
**Pull request by cyanglaz**
Hot fixing: https://github.com/flutter/flutter/issues/111494
PR: https://github.com/flutter/engine/pull/34508, https://github.com/flutter/engine/pull/36295

CP issue: https://github.com/flutter/flutter/issues/112963

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
Changes LGTM. Are the tests supposed to pass without infra failures?

**Comment by jmagman** [comment]
https://fuchsia.googlesource.com/third_party clones failed? @CaseyHillers what's up here?

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by CaseyHillers** [comment]
I don't understand either. It looks related to https://github.com/flutter/engine/pull/34720, possibly a corrupted bot cache. I'll retry the linux builds.

**Comment by CaseyHillers** [comment]
nit: Can we update the PR title to be something more desciptive? A common format is `[CP] $originalPrTitle`

**Comment by yoonk-ang** [comment]
@cyanglaz Hello. Thanks a lot for the fix and sorry to bother again 🙏 This issue is getting serious in my country, South Korea. Would there be timeline to merge this and release a hot-fix?

**Comment by zanderso** [comment]
```
src/third_party/libcxx (ERROR)
----------------------------------------
[0:00:02] Started.
_____ src/third_party/libcxx at 7524ef50093a376f334a62a7e5cebf5d238d4c99
running "git cat-file -e 7524ef50093a376f334a62a7e5cebf5d238d4c99^{commit}" in "/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-libcxx"
[0:00:02] fatal: Not a valid object name 7524ef50093a376f334a62a7e5cebf5d238d4c99^{commit}
[0:00:02] Commit with hash "7524ef50093a376f334a62a7e5cebf5d238d4c99" not found
[0:00:02] /b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-libcxx has 0 .pack files, re-bootstrapping if >50 or ==0
[0:00:02] running "git init --bare" in "/b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-libcxx"
[0:00:02] Reinitialized existing Git repository in /b/s/w/ir/cache/git/fuchsia.googlesource.com-third_party-libcxx/
```

**Comment by itsjustkevin** [comment]
@cyanglaz could you push an empty commit to rerun tests.

**Comment by jmagman** [comment]
> @cyanglaz could you push an empty commit to rerun tests.

I re-ran manually 🤞

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-engine-gold.skia.org/cl/github/36621

**Comment by jmagman** [comment]
```
/Volumes/Work/s/w/ir/cache/goma/client/gomacc  ../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/flutter/shell/platform/darwin/ios/framework/Source/flutter_framework_source.FlutterTextInputPlugin.o.d -DFLUTTER_FRAMEWORK=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSHELL_ENABLE_SOFTWARE -DSHELL_ENABLE_GL -DSHELL_ENABLE_METAL -DSK_GL -DSK_METAL -DSK_SUPPORT_GPU=1 -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_CODEC_DECODES_PNG -DSK_ENCODE_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_WEBP -DSK_HAS_WUFFS_LIBRARY -DSK_ENABLE_DUMP_GPU -DSK_DISABLE_AAA -DSK_PARAGRAPH_LIBTXT_SPACES_RESOLUTION -DSK_LEGACY_INNER_JOINS -DSK_LEGACY_IGNORE_DRAW_VERTICES_BLEND_WITH_NO_SHADER -DSK_DISABLE_LEGACY_SHADERCONTEXT -DSK_DISABLE_LOWP_RASTER_PIPELINE -DSK_FORCE_RASTER_PIPELINE_BLITTER -DSK_DISABLE_EFFECT_DESERIALIZATION -DSK_ENABLE_SKSL -DSK_ENABLE_PRECOMPILE -DSK_ASSUME_GL_ES=1 -DSK_ENABLE_API_AVAILABLE -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1 -DVULKAN_HPP_NO_EXCEPTIONS=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_NOEXCEPT -DIMPELLER_SUPPORTS_PLATFORM=1 -DIMPELLER_SUPPORTS_RENDERING=1 -DIMPELLER_ENABLE_METAL=1 -DFLUTTER_API_SYMBOL_PREFIX=Embedder -DFLUTTER_NO_EXPORT -I../.. -Igen -I../../third_party/skia -I../../third_party/vulkan_memory_allocator/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../flutter/third_party -I../../flutter -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../flutter/third_party/txt/src -I../../third_party/harfbuzz/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/rapidjson -I../../third_party/rapidjson/include -Igen/flutter -I../../flutter/shell/platform/darwin/common/framework/Headers -I../../flutter/shell/platform/embedder -isysroot /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk -mios-simulator-version-min=11.0 -fno-strict-aliasing -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -Os -fno-ident -fdata-sections -ffunction-sections -g2  -Werror=overriding-method-mismatch -Werror=undeclared-selector -fvisibility-inlines-hidden -fobjc-call-cxx-cdtors -std=c++17 -fno-rtti -fno-exceptions -nostdinc++ -isystem /Volumes/Work/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1  -c ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm -o obj/flutter/shell/platform/darwin/ios/framework/Source/flutter_framework_source.FlutterTextInputPlugin.o
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:76:3: error: unknown type name 'UChar32'
  UChar32 codePoint;
  ^
../../flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:84:57: error: use of undeclared identifier 'UCHAR_EMOJI'
  return gotCodePoint && u_hasBinaryProperty(codePoint, UCHAR_EMOJI);
```

@cyanglaz this doesn't build, does this also need to cherry-pick #34508?  Can you validate the fix on the candidate branch?

**Comment by jmagman** [comment]
> does this also need to cherry-pick #34508?

Or at least the `#include "unicode/uchar.h"`

**Comment by cyanglaz** [comment]
Having some issue with local build and im trying to fix it. Meanwhile, im pushing the `#include "unicode/uchar.h"` to wait for ci

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 3.
View them at https://flutter-engine-gold.skia.org/cl/github/36621

**Comment by yoonk-ang** [comment]
Thanks for your hard work 👍 Just FYI: This issue still happens in 16.1 beta 5.

**Comment by jmagman** [comment]
I didn't see ` error: Simulator not implemented` error, what command are you running?  I tried:
```
$  ./flutter/tools/gn --no-goma --unoptimized --ios --simulator && ninja -C out/ios_debug_sim_unopt  ios_test_flutter
```


Not sure why it's missing from the logs, but I reproduced the test failure locally:
```
FlutterTextInputPluginTest.mm:465 testCachedComposedCharacterClearedAtKeyboardInteraction: ((inputView.text) equal to (finalText)) failed: ("👨‍👩‍👧‍��아") is not equal to ("�아")
FlutterTextInputPluginTest.mm:424 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦아")) failed: ("👨‍👩‍👧‍��아") is not equal to ("👨‍👩‍👧‍👦아")
FlutterTextInputPluginTest.mm:435 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦😀아")) failed: ("👨‍👩‍👧‍����아") is not equal to ("👨‍👩‍👧‍👦😀아")
/FlutterTextInputPluginTest.mm:446 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦😀아")) failed: ("👨‍👩‍👧‍����아") is not equal to ("👨‍👩‍👧‍👦😀아")
```

When I cherry-picked in https://github.com/flutter/engine/pull/34508 to see if `--icu-data-file-path=Frameworks/Flutter.framework/icudtl.dat` in the test scheme was needed but those failed as well:
```
FlutterTextInputPluginTest.mm:500 testCachedComposedCharacterClearedAtKeyboardInteraction: ((inputView.text) equal to (finalText)) failed: ("👨‍👩‍👧‍��아") is not equal to ("�아")
FlutterTextInputPluginTest.mm:459 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦아")) failed: ("👨‍👩‍👧‍��아") is not equal to ("👨‍👩‍👧‍👦아")
FlutterTextInputPluginTest.mm:470 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦😀아")) failed: ("👨‍👩‍👧‍����아") is not equal to ("👨‍👩‍👧‍👦😀아")
FlutterTextInputPluginTest.mm:481 testSystemOnlyAddingPartialComposedCharacter: ((inputView.text) equal to (@"👨‍👩‍👧‍👦😀아")) failed: ("👨‍👩‍👧‍����아") is not equal to ("👨‍👩‍👧‍👦😀아")
FlutterTextInputPluginTest.mm:424 testDeletingBackward: ((inputView.text) equal to (@"ឹ😀 text 🥰👨‍👩‍👧‍👦")) failed: ("ឹ😀 text 🥰👨‍👩‍👧‍👦🇺�") is not equal to ("ឹ😀 text 🥰👨‍👩‍👧‍👦")
FlutterTextInputPluginTest.mm:426 testDeletingBackward: ((inputView.text) equal to (@"ឹ😀 text 🥰")) failed: ("ឹ😀 text 🥰👨‍👩‍👧‍👦🇺") is not equal to ("ឹ😀 text 🥰")
FlutterTextInputPluginTest.mm:429 testDeletingBackward: ((inputView.text) equal to (@"ឹ😀 text ")) failed: ("ឹ😀 text 🥰👨‍👩‍👧‍👦�") is not equal to ("ឹ😀 text ")
FlutterTextInputPluginTest.mm:437 testDeletingBackward: ((inputView.text) equal to (@"ឹ😀")) failed: ("ឹ😀 text 🥰👨‍👩‍") is not equal to ("ឹ😀")
FlutterTextInputPluginTest.mm:439 testDeletingBackward: ((inputView.text) equal to (@"ឹ")) failed: ("ឹ😀 text 🥰👨‍👩") is not equal to ("ឹ")
FlutterTextInputPluginTest.mm:441 testDeletingBackward: ((inputView.text) equal to (@"")) failed: ("ឹ😀 text 🥰👨‍�") is not equal to ("")
```

@cyanglaz can you try to step through these and see why these tests are failing?

**Comment by godofredoc** [comment]
> @cyanglaz and I are actively debugging this right now, can we hold on the release hotfix until this is complete?
Sounds good, please let me know when resolved to start the release.

**Comment by jmagman** [comment]
> When I cherry-picked in #34508 to see if `--icu-data-file-path=Frameworks/Flutter.framework/icudtl.dat` in the test scheme was needed but those failed as well:


I think I hadn't built the engine properly on both changes; it does seem to pass if #34508 is cherry-picked before https://github.com/flutter/engine/pull/36295.  However I don't have permission to push to your fork, @cyanglaz, can you try that?

**Comment by jmagman** [comment]
> However I don't have permission to push to your fork, @cyanglaz, can you try that?

Created https://github.com/flutter/engine/pull/36807 to try the tests there.

**Comment by jmagman** [comment]
The tests pass on https://github.com/flutter/engine/pull/36807 which means it should also pass on this one https://ci.chromium.org/p/flutter/builders/try/Mac%20Unopt/19879 since they are now the same.

**Pull request closed without merging**
